### ISSUE TITLE
Create new plugin reusing gradle-docker-plugin features

### ISSUE THREAD

**Issue by sharathkuncham** [bmuschko/gradle-docker-plugin#1000]
I would like to have a wrapper plugin which can preconfigure the base image.  
I didn't want to repeat the configuration for each springboot apps I have.  Once the base image is set with my custom  value all the apps needs is to provide the configuration for image tag. How to set the pre configuration on the springboot extension with default value for base image ? And is it feasible to write a wrapper plugin to just set the base image ?

### Expected Behavior
docker {
      springBootApplication {
          maintainer = 'Benjamin Muschko "benjamin.muschko@gmail.com"'
          ports = [9090, 8080]
          tag = 'awesome-spring-boot:1.115'
          jvmArgs = ['-Dspring.profiles.active=production', '-Xmx2048m']
      }
 }

### Current Behavior
docker {
      springBootApplication {
          baseImage = 'openjdk:8-alpine'
          maintainer = 'Benjamin Muschko "benjamin.muschko@gmail.com"'
          ports = [9090, 8080]
          tag = 'awesome-spring-boot:1.115'
          jvmArgs = ['-Dspring.profiles.active=production', '-Xmx2048m']
      }
 }

**Comment by bmuschko** [comment]
Yes, you can write that kind of plugin. Looks like you solved your issue.
