### ISSUE TITLE
Plugin Failing with JDK 16

### ISSUE THREAD

**Issue by teagy** [bmuschko/gradle-docker-plugin#1003]
The dockerCreateDockerFile task is failing to build with JDK 16 set as the target java version in Gradle. It outputs this error with no other information.

> Unsupported class file major version 60

I noticed that you made a recent change 8 days ago for adding support for JDK 16. https://github.com/bmuschko/gradle-docker-plugin/commit/3c9d2788362a430f35e73132ccda7f567eeb4a82

How long until the next tagged release with this change is available? We are switching over our apps to JDK 16 and this is holding it back.

**Comment by bmuschko** [comment]
I will try to release a new version sometime this week.

Closing as duplicate of https://github.com/bmuschko/gradle-docker-plugin/issues/999.
