### ISSUE TITLE
Publish changelog

### ISSUE THREAD

**Issue by iNikem** [bmuschko/gradle-docker-plugin#1007]
Currently it is impossible to understand what changed from version to version. E.g. is it safe for me to update from 6.7.0 to 7.0.0? I understand that maintaining the proper changelog may be too cumbersome for you, but can you consider it least doing proper GitHub releases? Then everybody can easily compare two versions and see all PRs between them.

**Comment by bmuschko** [comment]
Are you asking about this? https://bmuschko.github.io/gradle-docker-plugin/current/user-guide/#change_log

**Comment by iNikem** [comment]
Ou, my bad! That is certainly good enough for me! :) Maybe then have a link to that more visible on GitHub?

**Comment by bmuschko** [comment]
When you say "more visible on GitHub", what exactly would you expect? The README file already has links to it: https://github.com/bmuschko/gradle-docker-plugin/blob/master/README.adoc

**Comment by iNikem** [comment]
It has link to user guide. In my case it did not come to my mind to go to user guide to look for changelog. E.g. having a separate link to the changelog in the README will help users.

**Comment by bmuschko** [comment]
Ah, got it. Sure. Added.
