### ISSUE TITLE
Cannot access 'com.bmuschko.gradle.docker.tasks.image.Dockerfile$File'

### ISSUE THREAD

**Issue by asarkar** [bmuschko/gradle-docker-plugin#1009]
Following error is shown in `build.gradle.kts`.

```
import com.bmuschko.gradle.docker.tasks.image.Dockerfile

plugins {
    id("com.bmuschko.docker-remote-api")
}

tasks.create<Dockerfile>("createDockerfile") {
    copyFile(Dockerfile.CopyFile("$workingDir/dependencies", "./").withStage(stageName))
}                                                                   ^^^ Error
```

> Cannot access 'com.bmuschko.gradle.docker.tasks.image.Dockerfile$File' which is a supertype of 'com.bmuschko.gradle.docker.tasks.image.Dockerfile.CopyFile'. Check your module classpath for missing or conflicting dependencies

The build works, but the error is always there.

### Expected Behavior
No errors should be shown in the `build.gradle.kts`.

### Current Behavior
Described above.

### Context
Described above.

### Steps to Reproduce (for bugs)
Described above.

### Your Environment
Kotlin 1.4.32
docker-remote-api v7.0.0

**Comment by bmuschko** [comment]
Can you please provide the code snippet you posted above so that the issue become reproducible (optimally with a checked-in version of the Wrapper in a separate GitHub repo)? Right now I can't reproduce without making additional assumptions about your build script.

**Comment by asarkar** [comment]
[gradle-docker-plugin-issue-1009.zip](https://github.com/bmuschko/gradle-docker-plugin/files/6535561/gradle-docker-plugin-issue-1009.zip)

Here's a reproducible project with no source code at all, just build scripts. When it is opened in IntelliJ and set up with Java 11, the errors reported above are seen in the `app/build.gradle.kts`.

**Comment by bmuschko** [comment]
Thanks, I can reproduce this in IntelliJ but do not see the issue when running the build just with Gradle from the console. I assume this is an issue with the Kotlin version used in the IDE. The implementation of `Dockerfile` didn't really change in the meantime that would explain this problem. Maybe report the issue to Jetbrains. They can probably explain what's going on here. I am not going to further investigate the issue.

**Comment by bmuschko** [comment]
I tried this out with an older version of the plugin: 6.1.0. I get the same issue. I am sure that's an issue with the version of Kotlin. Would you mind reporting it to JetBrains?

**Comment by asarkar** [comment]
Opened https://youtrack.jetbrains.com/issue/IDEA-271382.

**Comment by bmuschko** [comment]
Thanks!
