### ISSUE TITLE
Cannot add extension with name 'docker' with spotless plugin included

### ISSUE THREAD

**Issue by chenqi0805** [bmuschko/gradle-docker-plugin#1010]
### Expected Behavior

I have two gradle files in root project:

integration.gradle

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:6.6.1'
    }
}

apply plugin: DockerRemoteApiPlugin

import com.bmuschko.gradle.docker.DockerRemoteApiPlugin
import com.bmuschko.gradle.docker.tasks.network.DockerCreateNetwork
import com.bmuschko.gradle.docker.tasks.network.DockerRemoveNetwork

import com.bmuschko.gradle.docker.tasks.network.DockerCreateNetwork
import com.bmuschko.gradle.docker.tasks.network.DockerRemoveNetwork

task createDockerNetwork(type: DockerCreateNetwork) {
    networkName = "test_network"
}

task removeDockerNetwork(type: DockerRemoveNetwork) {
    dependsOn createDockerNetwork
    networkId = createDockerNetwork.getNetworkId()
}
```

build.gradle:
```
plugins {
    id 'com.bmuschko.docker-remote-api' version '6.6.1'
}

plugins {
    id 'java'
    id "com.diffplug.spotless" version "5.12.4"
}

apply plugin: 'com.diffplug.spotless'
apply from: "integration.gradle"

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

spotless {
    format 'misc', {
        target '*.md', '.gitignore', '*.yml', '*.yaml'
        // TODO: enrich format rules
        trimTrailingWhitespace()
        endWithNewline()
    }
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

### Current Behavior

With the above two files, it shows `Cannot add extension with name 'docker', as there is an extension already registered with that name.` when I run `./gradlew build` or `./gradlew removeDockerNetwork`

If I remove spotless plugin, the above error disappears.

If I combine the above two files into a single build.gradle as follows, it also works by running `./gradlew removeDockerNetwork`:

```
plugins {
    id 'com.bmuschko.docker-remote-api' version '6.6.1'
}

plugins {
    id 'java'
    id "com.diffplug.spotless" version "5.12.4"
}

apply plugin: 'com.diffplug.spotless'

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

apply plugin: DockerRemoteApiPlugin

import com.bmuschko.gradle.docker.DockerRemoteApiPlugin
import com.bmuschko.gradle.docker.tasks.network.DockerCreateNetwork
import com.bmuschko.gradle.docker.tasks.network.DockerRemoveNetwork

import com.bmuschko.gradle.docker.tasks.network.DockerCreateNetwork
import com.bmuschko.gradle.docker.tasks.network.DockerRemoveNetwork

task createDockerNetwork(type: DockerCreateNetwork) {
    networkName = "test_network"
}

task removeDockerNetwork(type: DockerRemoveNetwork) {
    dependsOn createDockerNetwork
    networkId = createDockerNetwork.getNetworkId()
}

spotless {
    format 'misc', {
        target '*.md', '.gitignore', '*.yml', '*.yaml'
        // TODO: enrich format rules
        trimTrailingWhitespace()
        endWithNewline()
    }
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

### Context

We are trying to use spotless for code-formatting while using the gradle docker plugin for testing

### Steps to Reproduce (for bugs)

Only need the above two gradle files

### Your Environment

macOs and linux, gradle 6.6.1

**Comment by bmuschko** [comment]
Why exactly do you apply the Docker plugin with the `plugins` DSL in the root build script and then again in the `integration.gradle` file? That's probably your issues. Remove it from the root build script. You are not using the functionality there. Do me favor and create a sample GitHub repo with the code so I can reproduce.

**Comment by chenqi0805** [comment]
> Why exactly do you apply the Docker plugin with the plugins DSL in the root build script and then again in the integration.gradle file?

@bmuschko Thanks for point that out! I just tried removing

```
plugins {
    id 'com.bmuschko.docker-remote-api' version '6.6.1'
}
```
from `build.gradle` and then replaced 

```
apply plugin: DockerRemoteApiPlugin

import com.bmuschko.gradle.docker.DockerRemoteApiPlugin
```

with
```
apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin
```
in the external script `integration.gradle` and now everything works!

> Do me favor and create a sample GitHub repo with the code so I can reproduce.

Oh. This can be reproduced by just starting a fresh gradle project from intelliJ and then modified build.gradle and add integration.gradle as in the description. For some reason, it does not complain if spotless plugin is not included. But I think the root cause is probably as you pointed out.
