### ISSUE TITLE
Current way of mount volume in DockerCreateContainer?

### ISSUE THREAD

**Issue by chenqi0805** [bmuschko/gradle-docker-plugin#1013]
### Expected Behavior

I expect

```
binds = [(project.file(pipelineConfigYAML).toString()):"/usr/share/data-prepper/pipelines.yaml",
                 (project.file(serverConfigYAML).toString()):"/usr/share/data-prepper/data-prepper-config.yaml"]
```
works

### Current Behavior

Could not set unknown property 'binds' for task

**Comment by bmuschko** [comment]
Did you have a look at the [Groovydocs of the version](https://bmuschko.github.io/gradle-docker-plugin/current/api/) you are using? It should tell you what properties you can use. Replace `current` with your version.

**Comment by bmuschko** [comment]
Closing as we haven't received a response.
