### ISSUE TITLE
DockerWaitHealthyContainer removed - Context?

### ISSUE THREAD

**Issue by napstr** [bmuschko/gradle-docker-plugin#1014]
Hi, I noticed that the `DockerWaitHealthyContainer` task was removed in v7.0.0. According to the commit log it had bugs  that noone was willing to solve (fwiw I never noticed any in my usage). Searching the issues I don't see any recent and still open issues for that task. Could you elaborate what exactly were the issues? I might be able to help.

On a tangential note, I did not see the deprecations of 6.7.0 for these tasks in my builds despite using `--warning-mode all` - I wonder how to enable them?

**Comment by cdancy** [comment]
@napstr in hindsight the implementation was kind of cobbled together from other tasks and should have been done as a stand-alone custom task which leads to the actual point: this plugin is meant to provide 1-to-1 tasks for docker operations that you, the end-user, can wire up together in your own plugins/scripts to create more higher level tasks that users can invoke. This plugin is not the place for custom code as that is better suited for downstream plugins/impls/etc.

**Comment by napstr** [comment]
Understandable! I'll just pull this task into my `buildSrc` then. In case anyone else washes up here looking for a solution, here's the last state of the source code of the task: https://github.com/bmuschko/gradle-docker-plugin/blob/fa758050cdc6942d1b90659af2f5d92cab43f886/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerWaitHealthyContainer.groovy

**Comment by bmuschko** [comment]
The deprecation API you are referring to is a private API in Gradle core. I don't think the functionality is exposed as public API for plugin developers. Therefore, the console output of Gradle would not indicate the deprecation. It was only added to the Groovydocs of the plugin with no warning to end users at runtime.
