### ISSUE TITLE
Reduce number of transitive docker-java dependencies

### ISSUE THREAD

**Issue by Sineaggi** [bmuschko/gradle-docker-plugin#1015]
Currently gradle-docker-plugin depends on the docker-java dependency, which according to https://github.com/docker-java/docker-java/pull/1627#issuecomment-851217033 is a meta-package. If we change that dependency to core + api, we can reduce the number of dependencies as the meta-package pulls in both the jersey and netty transports.

Example dependency lists when using meta package [shaded_current.txt](https://github.com/bmuschko/gradle-docker-plugin/files/6570992/shaded_current.txt) vs using core + api only [shaded_minimal.txt](https://github.com/bmuschko/gradle-docker-plugin/files/6570993/shaded_minimal.txt)

Only missing file is DockerClientBuilder, but that just delegates to DockerClientImpl, so and example patch would look like https://github.com/bmuschko/gradle-docker-plugin/compare/master...Sineaggi:cleanup-dependencies

**Comment by bmuschko** [comment]
Are you interested in sending a PR for this? I won't get around to it anytime soon.

**Comment by Sineaggi** [comment]
I was going to, but the new pr submission page said to open an issue first, to gauge interest. If you are interested, PR is now up at #1016
