### ISSUE TITLE
Plugin breaks on gradle configuration cache, any plans to support it?

### ISSUE THREAD

**Issue by high-stakes** [bmuschko/gradle-docker-plugin#1020]
Let me just begin by thanking you for your hard work on this plugin, I really love the attention to detail and actual proper design behind it as opposed to most of the docker plugins out there.

I would like to use the plugin with configuration cache enabled as it brings significant performance benefits however
when executing a docker task which inherits from AbstractDockerRemoteApiTask and the new gradle configuration cache is enabled the configuration cache breaks in multiple ways.

### Expected Behavior
Configuration cache does not throw a build exception because of incompatibility with the plugin

### Current Behavior
Configuration cache throws multiple exceptions because of certain violations of its rules in the plugin.
The main issue seems to be the @Memorized annotation:
https://github.com/bmuschko/gradle-docker-plugin/blob/4e3014e7ecbf7afcdcf5dc463a7b1cd06601c57c/src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy#L143

It seems to cause some kind of concurrency issue in the configuration cache.
There are also multiple warning regarding the plugin and using the completion handlers also violates configuration cache.

### Context
I would like to use gradle configuration cache as it significantly speeds up the build (basically removes gradle configuration phase)

### Steps to Reproduce (for bugs)
put into gradle.properties:
org.gradle.unsafe.configuration-cache=true

Use this plugin to perform any task derived from AbstractDockerRemoteApiTask and you will get a build failure with errors and warnings due to multiple violations of the configuration cache.
Adding a completion handler also causes further errors.

### Your Environment
gradle 7.1
latest plugin version
multi-project build on multiple cpu cores
java 11

**Comment by bmuschko** [comment]
This was also mentioned in https://github.com/bmuschko/gradle-docker-plugin/issues/987 but with a slightly different angle. Are you interested in submitting a pull request for this? I won't have the time to work on it.

**Comment by high-stakes** [comment]
yes, if I get the time I will submit a PR, any preference on how to get rid of @Memorized?

**Comment by bmuschko** [comment]
Not really. AFAIR we tried to avoid creating multiple Docker Java clients. Maybe as a first step, try to implement this as a Singleton instead of using the annotation. If that doesn't help then I guess we'll simply have to create multiple instances.

**Comment by bmuschko** [comment]
@high-stakes Were you able to make any progress on this?

**Comment by high-stakes** [comment]
I checked the options but it seems a bit tricky I will try to implement it on the weekend based on another plugin who had this issue:
 https://github.com/runningcode/gradle-doctor/issues/71

**Comment by high-stakes** [comment]
@bmuschko There is an issue with the fix because the plugin is supporting gradle 5.2 but the buildservice api which replaces buildfinished is only since 6.1

**Comment by bmuschko** [comment]
@high-stakes That's fine. We can introduce a breaking change. You can upgrade this plugin to 6.1.

**Comment by high-stakes** [comment]
I spent quite some time trying to get things working but I gave up after running into too many issue in the tests. When configuration cache is enabled multiple tests are affected (as they violate config cache) and I could not find an equivalent replacement because for example some config cache functions are not even available in 6.1 (like provider api for gradle project properties).

Is it ok if I do not add testing for configuration cache? It is annoying because it is easy to break so even if I fix it someone might break it in the future.

**Comment by bmuschko** [comment]
Can you elaborate a bit? I don't think I fully understand what's going on. Shouldn't the existing tests work as-is? Which ones are failing?

I think it's fine to not adds tests for configuration cache behavior. I feel that would have to be test code in Gradle core.

**Comment by high-stakes** [comment]
> Can you elaborate a bit? I don't think I fully understand what's going on. Shouldn't the existing tests work as-is? Which ones are failing?
> 
> I think it's fine to not adds tests for configuration cache behavior. I feel that would have to be test code in Gradle core.

I basically enabled configuration cache for all the tests and ran them that way but as it's not enough to have the plugin support configuration cache your usage of gradle has to also follow the configuration cache requirements which not all the tests do.
I was originally planning to run tests with both config cache enabled and disabled for this reason but there were several tests affected when cache is enabled. They are a 100% possible to migrate but I do not have time for that at the moment.

**Comment by bmuschko** [comment]
Thanks for having a look at it. Totally understood, I won't have the time either. Maybe you can push your changes to a branch so somebody can pick up the work if they want to.

**Comment by bmuschko** [comment]
Closing this for now as no more work is being done it.
