### ISSUE TITLE
Failed to call Dockerfile.instructionsFromTemplate()

### ISSUE THREAD

**Issue by barryzhounb** [bmuschko/gradle-docker-plugin#1023]
### Steps to Reproduce (for bugs)

This is our abc.gradle,
```
buildscript {
    repositories {
        maven {
            url "${artifactory_contextUrl}/gradle-plugins-virtual"
            credentials {
                username = "${artifactory_user}"
                password = "${artifactory_password}"
            }
        }
    }
    dependencies {
		classpath 'com.bmuschko:gradle-docker-plugin:7.0.1'
    }
}

plugins {
	id 'com.bmuschko.docker-remote-api'
}

import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage


task createDockerfile(type: Dockerfile) {
	instructionsFromTemplate("Dockerfile")
	label(['version'    : "1.0.0",
		   'maintainer' : "Team"])
	destFile.set(file("${projectDir}/Dockerfile.tmp"))
}
```

When we run command: ./gradlew clean createDockerfile

Then we got error:

```
Could not find method instructionsFromTemplate() for arguments [Dockerfile] on task ':abc:createDockerfile' of type com.bmuschko.gradle.docker.tasks.image.Dockerfile.
```

**Comment by bmuschko** [comment]
What's the question exactly?

BTW: You are not applying the plugin correctly. Either use the `plugins` notation _or_ the `buildscript` notation but not both. see https://plugins.gradle.org/plugin/com.bmuschko.docker-remote-api.

**Comment by barryzhounb** [comment]
It complains about "Could not find method instructionsFromTemplate()".

Even I change to legacy buildscript mode followed your suggestion https://plugins.gradle.org/plugin/com.bmuschko.docker-remote-api, it failed as well.

**Comment by bmuschko** [comment]
Doesn't happen for me for this build script and Gradle 7.0.01.

```
plugins {
  id "com.bmuschko.docker-remote-api" version "7.0.1"
}

import com.bmuschko.gradle.docker.tasks.image.Dockerfile

task createDockerfile(type: Dockerfile) {
    instructionsFromTemplate('DockerfileTemplate')
}
```

**Comment by barryzhounb** [comment]
You mean your gradle version is 7.0.1 as well?

My gradle version is 4.6

**Comment by bmuschko** [comment]
Not necessarily saying that's your issue but our documentation states the following for the latest version:

> This plugin requires Gradle >= 5.2 to work properly.

Yes, my build uses Gradle 7.0.1 as well as plugin version 7.0.1. They are the same version just by accident.

Please create a public GitHub repository with a Gradle Wrapper that reproduces your issue. Minimal code please.

**Comment by bmuschko** [comment]
Do you still need any help with this? If you don't, I am going to close the issue.
