### ISSUE TITLE
Could not find method defaultDependencies() for argument

### ISSUE THREAD

**Issue by christianhuening** [bmuschko/gradle-docker-plugin#103]
Hi there,
just tried your plugin with the default java application example. This is what I get:

A problem occurred evaluating root project 'product-composite-service'.
> Failed to apply plugin [id 'com.bmuschko.docker-java-application']
   > Could not find method defaultDependencies() for arguments [com.bmuschko.gradle.docker.DockerRemoteApiPlugin$_configureAbstractDockerTask_closure1_closure3@47b269c4] on configuration ':dockerJava'.

What am I doing wrong?

Cheers and thanks
Christian

**Comment by bmuschko** [comment]
The method [defaultDependencies](https://docs.gradle.org/2.5/release-notes#simpler-default-dependencies) has been introduced with 2.5. Therefore your project has to use Gradle >= 2.5. I won't backport the plugin to earlier versions. If that's not an option for you, you'll have to go with an earlier, published version.

**Comment by christianhuening** [comment]
Oh that's weird, thought I were using 2.6. Will check. Thanks!

**Comment by programsam** [comment]
Hmm, I have checked, am sure that I'm using Gradle v2.8 and still git this error.
