### ISSUE TITLE
Are port bind ranges supported currently in DockerCreateContainer tasks?

### ISSUE THREAD

**Issue by AlastairMiller** [bmuschko/gradle-docker-plugin#1030]
I have a container from which requires a port range to bound to the host machine corresponding ports. Looking at the source groovy of `DockerCreateContainer` this does not seem possible. Am I making the correct conclusion? 

### Expected Behavior

Would expect this or similar to expose port 40000 -> 41000 on the container to 40000 -> 41000 on the host machine.
`hostConfig.portBindings = ['40000-40100:40000-40100']`

This is performed on the Docker CLI with a command similar to this 
`docker run -p 40000-40100:40000-40100 containerName`

### Current Behavior

Running the task causes the following exception

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':createContainer'.
Caused by: java.lang.IllegalArgumentException: Error parsing PortBinding '40000-40100:40000-40100'
	at com.github.dockerjava.api.model.PortBinding.parse(PortBinding.java:57)
	at com.github.dockerjava.api.model.PortBinding$parse.call(Unknown Source) 
```

**Comment by bmuschko** [comment]
This exception is coming from [Docker Java](https://github.com/docker-java/docker-java). You will need to ask over there if this notation is supported. Thanks!
