### ISSUE TITLE
Extend the DockerCreateContainer about --env-file

### ISSUE THREAD

**Issue by fjahoda** [bmuschko/gradle-docker-plugin#1031]
To make easy to pass outside environments into a new container please expose `--env-file`.
https://docs.docker.com/engine/reference/commandline/create/

This enables to pass multiple variables at once. Otherwise I'm forced to extract the variables in gradle and pass them individually.

**Comment by bmuschko** [comment]
This is already supported: https://bmuschko.github.io/gradle-docker-plugin/current/api/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.html#envVars
