### ISSUE TITLE
Entrypoint elements are not encoded for the Dockerfile

### ISSUE THREAD

**Issue by iyzana** [bmuschko/gradle-docker-plugin#1033]
Regarding the java application plugin:
When providing jvmArgs containing a single backslash that single backslash is copied over as is into the Dockerfile generated by the Dockerfile task.
Docker expects the ENTRYPOINT statement to be valid JSON, but a single backslash in a string is not valid json.
If the ENTRYPOINT is not valid JSON, docker interprets the whole ENTRYPOINT string as a shell script.

### Expected Behavior

All strings that are written to the Dockerfile ENTRYPOINT are properly encoded for JSON strings.
For the repro provided below the following Dockerfile should be generated
```dockerfile
FROM dockerfile/java:openjdk-7-jre
LABEL maintainer=maintainer
WORKDIR /app
COPY classes classes/
ENTRYPOINT ["java", "-Dsomearg=TEXT\\HERE", "-cp", "/app/resources:/app/classes:/app/libs/*", "dockerfile.repro.App"]
EXPOSE 8080
```

### Current Behavior

String contents that are invalid in json are not properly encoded for the ENTRYPOINT.
For the repro provided below the following Dockerfile is being generated
```dockerfile
FROM dockerfile/java:openjdk-7-jre
LABEL maintainer=maintainer
WORKDIR /app
COPY classes classes/
ENTRYPOINT ["java", "-Dsomearg=TEXT\HERE", "-cp", "/app/resources:/app/classes:/app/libs/*", "dockerfile.repro.App"]
EXPOSE 8080
```

notice the single backslash between TEXT and HERE

### Context

Provinding an ActiveDirectory Path containing a single backslash as a jvm argument.
A suitable workaround is providing the correctly encoded string to the docker plugin, i.e. in this specific case running
```kotlin
.replace("\\", "\\\\")
```
on all jvmArgs before passing them to the plugin

### Steps to Reproduce (for bugs)

Reproduction project archive:
[dockerfile-repro.tar.gz](https://github.com/bmuschko/gradle-docker-plugin/files/6937854/dockerfile-repro.tar.gz)

contains the following build.gradle.kts:
```kotlin
plugins {
    application
    java
    id("com.bmuschko.docker-java-application") version "7.1.0"
}

docker {
    javaApplication {
        baseImage.set("dockerfile/java:openjdk-7-jre")
        maintainer.set("maintainer")
        jvmArgs.set(listOf("-Dsomearg=TEXT\\HERE"))
    }
}

application {
    mainClass.set("dockerfile.repro.App")
}
```

to generate the problematic Dockerfile at `app/build/docker/Dockerfile` run
```sh
./gradlew dockerCreateDockerFile
```

### Your Environment

```
------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.12 (Oracle Corporation 11.0.12+7)
OS:           Linux 5.13.7-arch1-1 amd64
```

**Comment by bmuschko** [comment]
Implementing encoding for Strings can have a lot of corner cases so things can go wrong easily. I am not planning to implement the behavior for the plugin at this time. You will need to handle the encoding on your end.
