### ISSUE TITLE
Add the ability to add environment variables in doFirst

### ISSUE THREAD

**Issue by DrunkenDolphin** [bmuschko/gradle-docker-plugin#1038]
### Expected Behavior

It should be possible to set envVars in doFirst block like this:
```
    doFirst {
        if (env != null) {
            envVars.putAll(project.variables.get(env))
        }
    }
```
### Current Behavior

It is not possible to set a `envVars` in doFirst. When I set envVars in doFirst block:

   > Failed to calculate the value of task ':myProject:createContainer' property 'envVars'.
   > java.lang.NullPointerException (no error message)

### Context

I have a task that only starts a docker container on the local machine. In this task I have set envVars too. But I don't want to run this task when building in the cloud. So I use doFirst to avoid triggering actions when the task is not called directly.

**Comment by bmuschko** [comment]
You should be able to set the value of the field during the configuration phase and not within a task action. That's already too late. What exactly is `project.variables`? Make sure that's actually available when you try to set it. To ensure the task is not running, you should use `Task.onlyIf`.

**Comment by bmuschko** [comment]
Closing as I haven't heard back.
