### ISSUE TITLE
How to set ENV value in Dockerfile via JavaApplication version of plugin

### ISSUE THREAD

**Issue by christianhuening** [bmuschko/gradle-docker-plugin#104]
Ho can I add and ENV entry to the Dockerfile when using the javaApplication plugin version?
I found the environmentVariable method and static Instruction in the Dockerfile Task type in the sources, but have no clue how to access these.

Or is that only possible in the remote API version?

Cheers,
Christian

P.S.: Pretty new to Gradle ;-)

**Comment by christianhuening** [comment]
edit: Name of the issue

**Comment by bmuschko** [comment]
The API is the same. The only difference is that the task has already been created with the name `dockerDistTar ` and populated with instructions. You can add more instructions.

    dockerDistTar.environmentVariable('SOME_ENV', 'value')

**Comment by bmuschko** [comment]
Closing issue. Just reopen if you need additional help.

**Comment by christianhuening** [comment]
Thanks!
Just to clarify: If I want to tar-pack the contents of my build, provide some ENV variable to my Dockerfile and then build an Image from that, I would express this like so:
``` groovy
task dockerize {        
 dockerDistTar.environmentVariable('JAVA_OPTS', '-Dspring.profiles.active=docker')
 dockerBuildImage
}
```
Is that correct?

**Comment by bmuschko** [comment]
The task dependencies have already been established by the plugin. Just run `dockerBuildImage`. Have a look at the README for more info.
