### ISSUE TITLE
Depending on other images in the same build

### ISSUE THREAD

**Issue by mouradxmt** [bmuschko/gradle-docker-plugin#1040]
I would like to be able to have dependency between images on the same gradle build. for example I have a submodule `images:customLinux` and another one `images:customJava` , and I want `images:customJava` to have an image dependency on `images:customLinux` 

### Expected Behavior

for example, for `images:customJava`
  ```
  val createDockerFileForCustomJava by creating(Dockerfile::class) {
        destFile.set(File("$buildDir/Dockerfile"))
        from(theImageCreatedByCustomLinux)
...
}
```
and for `images:customLinux`
```
    val buildImage by creating(DockerBuildImage::class) {
        dependsOn(createDockerfile)
        inputDir.set(File("$buildDir"))
        images.add("${rootProject.extra["myCustomTagName"]}")
    }
```

How to access to `theImageCreatedByCustomLinux` without using `"${rootProject.extra["myCustomTagName"]}` , because the logic for generating the name is a bit more complex than that.
### Current Behavior

I tried using the task output, but there is some issues with lazy configuration that I could not figure out.

**Comment by bmuschko** [comment]
You can access the value of the field `images` of that task type `DockerBuildImage`: https://bmuschko.github.io/gradle-docker-plugin/current/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#images. We do the same internally in one of our plugins: https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerConventionJvmApplicationPlugin.groovy#L193

**Comment by bmuschko** [comment]
Closing as I haven't heard back.
