### ISSUE TITLE
Can not enable Buildkit, when building image

### ISSUE THREAD

**Issue by tillbier** [bmuschko/gradle-docker-plugin#1041]
### Expected Behavior

In the class DockerBuildImage, there should be a property to enable the buildkit.

### Current Behavior

At the moment there is no way, that i am aware of, to enable the buildkit in this plugin.

### Context

In order to use the following syntax in the Dockerfile, the buildkit needs to be enabled:

`ADD --chmod=664 http://someurl destinationfile`

This is the documentation of docker regarding the buildkit:
* https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds

**Comment by bmuschko** [comment]
BuildKit is currently not supported by the Docker API. We are not using the command line tool. That's why it's not supported.
