### ISSUE TITLE
"exposePort" method only supports default TCP protocol

### ISSUE THREAD

**Issue by tiwebdev** [bmuschko/gradle-docker-plugin#1047]
### Expected Behavior
It would be nice if the com.bmuschko.gradle.docker.tasks.image.Dockerfile.exposePort method could support not just the default TCP protocol but could also support UDP by allowing an additional parameter to specify the port's protocol

### Current Behavior
Currently the method in question does not allow for the specification of the protocol, thereby only allowing the exposed ports to support the default TCP protocol.

### Context
Currently I will have to create a static dockerfile and copy that into the docker build directory in lieu of the dockerfile creation functionality of the plugin.

### Steps to Reproduce (for bugs)
1. Using an example project, add an "exposePort" command to the createDockerfile task in your build.gradle file
2. Run the "buildImage" task in Gradle
3. Start the image in a container and look at the open ports of the container - the exposed port will be expecting TCP protocol, as there has been no protocol specified and TCP is the default

### Your Environment
This feature is not specific to an environment, but I am developing using Intellij Idea on a Macbook Pro running Mac OS Catalina 10.15.7.  The image I am using for Docker is openjdk:11.0.11-jdk

**Comment by bmuschko** [comment]
You can use the [`instruction` method](https://bmuschko.github.io/gradle-docker-plugin/current/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html#instruction(java.lang.String)) which allows for provide any instruction you want. Are you interested in providing a pull request for specifying the protocol?

**Comment by tiwebdev** [comment]
Yea, let me see if I can get to it this weekend

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bmuschko** [comment]
Looks like you are not interested in sending a PR for this. I am going to close the issue as I provided a viable solution.
