### ISSUE TITLE
Enable Docker build kit

### ISSUE THREAD

**Issue by EslamElHusseiny** [bmuschko/gradle-docker-plugin#1048]
Hi,
Is there a way to enable the Docker's build kit while building Docker images using the Gradle docker plugin? 
According to the [Docker documentation](https://docs.docker.com/develop/develop-images/build_enhancements/), you need only the environment variable `DOCKER_BUILDKIT=1`

**Comment by bmuschko** [comment]
The Docker remote API does not support buildkit: https://github.com/bmuschko/gradle-docker-plugin/issues/1041

**Comment by ckchow** [comment]
Looking at the [1.44 API](https://docs.docker.com/engine/api/v1.44/#tag/Image/operation/ImageBuild), `version` parameter, I think I'm seeing an option to use a buildkit backend. Would you know otoh how to try to enable this in the plugin, to see if it works?

**Comment by sschuberth** [comment]
> Looking at the [1.44 API](https://docs.docker.com/engine/api/v1.44/#tag/Image/operation/ImageBuild), `version` parameter, I think I'm seeing an option to use a buildkit backend.

Indeed this seems to have been [available since API v1.38](https://github.com/moby/moby/commit/0c3b8ccda7fd71a9d90b29848dce4a2010bced7e).

**Comment by tkrah** [comment]
@bmuschko Can this be reopened? According to https://github.com/docker/for-linux/issues/1136#issuecomment-2159656470 the old repo is deprecated and the current repo has support for buildkit - can you add that version parameter?

**Comment by bmuschko** [comment]
@tkrah It needs to be available in Docker Java first. Happy to review a PR if you want to send one.

**Comment by sschuberth** [comment]
> It needs to be available in Docker Java first.

I'm trying to revive [this issue](https://github.com/docker-java/docker-java/issues/1657#issuecomment-2160631906) for that.

**Comment by tkrah** [comment]
@sschuberth There is already https://github.com/docker-java/docker-java/issues/1381 for this.

**Comment by tkrah** [comment]
> @tkrah It needs to be available in Docker Java first. Happy to review a PR if you want to send one.

I'll do, created one for docker-java, lets see if we can get that done :) .
