### ISSUE TITLE
DockerListImages  with filter call a wrong function from ListImagesCmdImpl.java

### ISSUE THREAD

**Issue by Webaib** [bmuschko/gradle-docker-plugin#105]
No signature of method: com.github.dockerjava.core.command.ListImagesCmdImpl.withFilter() is applicable for argument types: (java.lang.String) values: [busybox]
Possible solutions: withFilters(java.lang.String), getFilters()

**Comment by bmuschko** [comment]
Thanks for reporting. I fixed the issue. The commit also provides a test case.

As a side note: The Docker Java API for the `filters` is kind of clumsy. It expects a JSON String. The long run we might run that into something more usable on a task level.

**Comment by Webaib** [comment]
Thanks for the fix.

Best Regards
Oleg
