### ISSUE TITLE
Plugin incompatible with Gradle 7

### ISSUE THREAD

**Issue by BenedictQ** [bmuschko/gradle-docker-plugin#1050]
Cannot build project using this plugin with Gradle 7 as DockerPullImage is missing an annotation (there may well be further incompatibilities, but this is the one I've come across).

### Expected Behavior

Plugin works with Gradle 7.

### Current Behavior

Plugin is incompatible with Gradle 7. I have added the following task to my build.gradle file

```
task pullImage(type: DockerPullImage) {
	repository = 'amazon/dynamodb-local'
	tag = '1.17.2'
}
```

I get the error `com.bmuschko.gradle.docker.tasks.image.DockerPullImage' property 'imageId' is missing an input or output annotation.` when I try to build the project. I believe this is due to a missing annotation introduced in Gradle 7 (I see a number of other projects on GitHub have similar issues raised).

### Context

I am trying to use the plugin to run the aws dynamodb local image before running integration tests. The build is failing before even pulling the image.

### Steps to Reproduce (for bugs)

Add the following code to a gradle build:

```
buildscript {
	repositories {
		maven {
			url 'https://plugins.gradle.org/m2/'
		}
	}
	dependencies {
		classpath 'com.bmuschko:gradle-docker-plugin:3.2.3'
	}
}

import com.bmuschko.gradle.docker.tasks.image.DockerPullImage

task pullImage(type: DockerPullImage) {
        // Which image is not important here.
	repository = 'amazon/dynamodb-local'
	tag = '1.17.2'
}
```

### Your Environment

Java 17, Gradle 7.3

**Comment by bmuschko** [comment]
You are using a very outdated version of the plugin. Please upgrade to the latest version. We are already a couple of major versions ahead: 7.1.0.
