### ISSUE TITLE
group id is too big. Use STAR or POSIX extensions to overcome this limit

### ISSUE THREAD

**Issue by Kent1** [bmuschko/gradle-docker-plugin#1051]
See https://github.com/docker-java/docker-java/pull/1787 and https://github.com/docker-java/docker-java/issues/1747

Created issue to track the error and update the dependencies once it is solved upstream.

**Comment by bmuschko** [comment]
Have your changes to the Docker Java been released yet?

**Comment by Kent1** [comment]
It did yes. https://github.com/docker-java/docker-java/releases/tag/3.2.13

**Comment by bmuschko** [comment]
OK, thanks. The next release will include that Docker Java version: https://github.com/bmuschko/gradle-docker-plugin/pull/1058
