### ISSUE TITLE
Gradle Remote API Plugin Failing with Spring Boot and OpenAPI Generator

### ISSUE THREAD

**Issue by shub-kalloli** [bmuschko/gradle-docker-plugin#1054]
We are building a multi module project with Spring Boot and Open API Generator. We are interested in using the Docker Spring Boot plugin(com.bmuschko.docker-spring-boot-application) to generate docker images. When we apply the plugin, the application build is failing with an error.

### Expected Behavior

The application builds successfully without the plugin.

### Current Behavior

The application build is failing with the error
Execution failed for task ':spring-generated:generateApiClient'.
> 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'

### Steps to Reproduce (for bugs)

Please find the zip file attached herewith.

In order to recreate the issue

1. The application builds successfully with `gradle clean build`
2. If we uncomment the dependency for the plugin in buildSrc/build.gradle and run `gradle clean build` in the root folder, we are seeing the error mentioned above

### Your Environment

We are using MacBook Pro, both M1 Chips and Intel Chips. See the same issue in both of them.
[spring-openapi-generator.zip](https://github.com/bmuschko/gradle-docker-plugin/files/8003046/spring-openapi-generator.zip)

**Comment by bmuschko** [comment]
Gradle does not provide isolated classpaths for applied plugins. It's very likely that the Jackson library version you are pulling in is conflicting with the one pulled in by Docker Java. Hence you see the issue. You'd probably have to settle on some version of Jackson that's compatible with Docker Java _and_ Spring Boot.

IMHO I don't understand why you add the plugin dependency in the top-level `build.gradle` file under `buildSrc`.  Any reason why you do not apply the plugin directly in the build script of `spring-generated`?

**Comment by shub-kalloli** [comment]
We have added the plugin dependency in the top-level `build.gradle` as it is a multi-module project and the plugin would be used by all the sub modules.

We have found a resolution by adding the Jackson dependencies in the `build.gradle` in the `buildSrc`.

The updated build.gradle would look like the following:

```
plugins {
    // Support convention plugins written in Groovy. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    id 'groovy-gradle-plugin'
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
   implementation 'com.bmuschko:gradle-docker-plugin:7.2.0'
   implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.12.4'
   implementation 'com.fasterxml.jackson.core:jackson-core:2.12.4'
}
```
Updated project: [spring-openapi-generator.zip](https://github.com/bmuschko/gradle-docker-plugin/files/8760151/spring-openapi-generator.zip)
