### ISSUE TITLE
Cannot pass application arguments to the main method through the generated Dockerfile

### ISSUE THREAD

**Issue by loukandr** [bmuschko/gradle-docker-plugin#1056]
I have a Java application that expects the filename of a configuration file with an application argument. However, I couldn't find a way in the docker-java-application plugin to pass such arguments. By application arguments, I mean an array of String expected by the main method.

### Expected Behavior
I would expect to be able to configure the following property in the `javaApplication` namespace.
```
docker {
    javaApplication {
        args = ['arg1', 'arg2', 'argN']
    }
}
```
### Current Behavior
In the current `javaApplication` namespace, there is no `args` or any other similar property for the main method arguments.

### Context
In a custom Dockerfile, I add the application arguments (e.g. arg1, arg2, argN) like this:

```
ENTRYPOINT ["java", "-cp", "/app/resources:/app/classes:/app/libs/*", "com.example.main.AppMain", "arg1", "arg2", "argN"]
```

**Comment by mucst** [comment]
I suppose utilizing the `jvmArgs` property is not an option to you? https://bmuschko.github.io/gradle-docker-plugin/#extension_2

**Comment by loukandr** [comment]
@mucst I tried, but the arguments must be placed after the jar file name in the ENTRYPOINT for the main class to pick them up. The jvmArgs property places the args before the jar file name.

**Comment by bmuschko** [comment]
The plugin doesn't currently support defining application arguments via the DSL. You could modify the original instruction, as described here: https://bmuschko.github.io/gradle-docker-plugin/current/user-guide/#modifying_instructions_of_a_dockerfile_task. I understand that it would be more user-friendly to provide such a DSL option. Would you be interested in providing a pull request for this. The option should be added to the "Java Application Plugin" and the "Spring Boot Application Plugin".

**Comment by bmuschko** [comment]
Sounds like the community doesn't want to contribute to this. I am going to close this for now. We can reopen is somebody is sending a pull request.
