### ISSUE TITLE
Is DockerBuildImage task no longer cacheable?

### ISSUE THREAD

**Issue by JavierTobar** [bmuschko/gradle-docker-plugin#1061]
### Expected Behavior
Release notes for v4.0.0 mentioned that `DockerBuildImage` is incremental and cacheable. 

### Current Behavior
I can make incremental builds with `DockerBuildImage` task locally, but on CI the task is not cacheable. 

### Context
I want to avoid building images if nothing has changed on CI. I noticed the release notes for v4.0.4 which links the issue https://github.com/bmuschko/gradle-docker-plugin/issues/697. In that thread, it was mentioned that the change was reverted https://github.com/bmuschko/gradle-docker-plugin/issues/697#issuecomment-435698049 but I don't understand what was reverted. The cacheable was reverted/removed, but the incremental was kept? And so, as of today, `DockerBuildImage` is not cacheable in CI, correct?

**Comment by bmuschko** [comment]
There's no `@CacheableTask` annotation assigned to the `DockerBuildImage` class: https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy#L46. So, no it's not cacheable. Incremental build functionality does not have to be enabled explicitly. As long as one input and one output is defined (via annotations or the runtime API), it is checked.
