### ISSUE TITLE
docker-java-application coordinates incompatible with version catalog?

### ISSUE THREAD

**Issue by abendt** [bmuschko/gradle-docker-plugin#1062]
I am using the gradle version catalog to share dependencies across modules (https://docs.gradle.org/current/userguide/platforms.html)

I does not seem possible to put the [docker-java-application plugin](https://plugins.gradle.org/plugin/com.bmuschko.docker-java-application) into the catalog as its coordinates do not seem to be valid.

### Expected Behavior

i want to be able to define the _docker-java-application_ plugin in a version catalog and reference it from a module

### Current Behavior

my _.toml_ file
```
gradlePlugin-dockerJavaApplication = "com.bmuschko.docker-java-application:7.3.0"

```

error message
```
> Invalid TOML catalog definition:
    - Problem: In version catalog libs, on alias 'gradlePlugin-dockerJavaApplication' notation 'com.bmuschko.docker-java-application:7.3.0' is not a valid dependency notation.

      Reason: When using a string to declare library coordinates, you must use a valid dependency notation.

      Possible solution: Make sure that the coordinates consist of 3 parts separated by colons, eg: my.group:artifact:1.2.
```

### Context

trying to extract definition of dependencies that are used in multiple modules to a central location

### Steps to Reproduce (for bugs)

i can create an example if needed. just let me know

### Your Environment

```
$ gw --version

------------------------------------------------------------
Gradle 7.4.1
------------------------------------------------------------

Build time:   2022-03-09 15:04:47 UTC
Revision:     36dc52588e09b4b72f2010bc07599e0ee0434e2e

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.14 (Azul Systems, Inc. 11.0.14+9-LTS)
OS:           Mac OS X 12.1 x86_64
```

**Comment by bmuschko** [comment]
You are not providing a GAV (group ID, artifact ID, version) as far as I can tell from what you posted. You'll need to use `com.bmuschko:gradle-docker-plugin:7.3.0`.

**Comment by abendt** [comment]
my bad, i put the plugin definition into the wrong section in the _.toml_ file. I can confirm that it works with the following configuration

libs.version.toml:
```
[versions]
gradleDockerPlugin = "7.3.0"

[plugins]
dockerJavaApplication = { id = "com.bmuschko.docker-java-application", version.ref="gradleDockerPlugin" }
```

build.gradle.kts:
```
plugins {
       alias(libs.plugins.dockerJavaApplication)
}
```
