### ISSUE TITLE
Support multiple images for DockerSaveImage

### ISSUE THREAD

**Issue by Vampire** [bmuschko/gradle-docker-plugin#1067]
### Expected Behavior
It would be nice if the `DockerSaveImage` task would support multiple images to be saved into the target tar.
This could for example also be used to export an image with two tags like `1.1.0` and `latest`.
The CLI is able to do that, as well as `docker-java`, it is just not exposed by this plugin.

### Current Behavior
You can only supply one image to the task

### Your Environment
Gradle 7.4.2, Plugin 7.3.0

**Comment by bmuschko** [comment]
Can you please provide a PR for this? I won't get around to implementing this.

**Comment by Vampire** [comment]
Sure: https://github.com/bmuschko/gradle-docker-plugin/pull/1069
When can I get a release? ;-)

**Comment by Vampire** [comment]
Work-around in the meantime:
```kts
val saveDockerImage by tasks.registering(DockerOperation::class) {
    val images = buildDockerImage.map { it.images.get() }
    inputs.property("images", images)

    val destFile = base
        .distsDirectory
        .file("${project.name}-${project.version}-docker-image.tar.gz")
    outputs.file(destFile).withPropertyName("destFile")

    onNext {
        this as DockerClient
        val saveImagesCmd = saveImagesCmd()
        images.get().forEach { image ->
            val (name, tag) = image.split(':', limit = 2)
            saveImagesCmd.withImage(name, tag)
        }
        saveImagesCmd.exec().use { imageIn ->
            destFile
                .get()
                .asFile
                .outputStream()
                .let(::GZIPOutputStream)
                .use(imageIn::copyTo)
        }
    }
}
```

**Comment by Vampire** [comment]
@bmuschko you asked for a PR here, I provided it and even two more but you ignore them for over a month without any comment, while you are active in the project.

Can you give a rough estimate when you maybe will have time to have a look?
There were conflicting changes and I mainly want to know whether it is worth putting the effort in keeping the PRs up to date right now.

**Comment by bmuschko** [comment]
@Vampire Let's make the tasks `DockerBuildImage` and `DockerSaveImage` never up-to-date first: https://github.com/bmuschko/gradle-docker-plugin/issues/1071. With that https://github.com/bmuschko/gradle-docker-plugin/pull/1073 and https://github.com/bmuschko/gradle-docker-plugin/pull/1072 should be closed if I am not mistaken. We can then have a look at supporting multiple images for the `DockerSaveImage` task. Sounds good?

**Comment by Vampire** [comment]
However you prefer.
I'm fine with both ways.
But I guess it's fine to be up-to-date if state is ok and it definitely is a performance improvement,
because Docker is not Gradle, it does not see it is all up-to-date but just does the work again.
That's why I hopefully fixed the up-to-date checks.

**Comment by bmuschko** [comment]
Honestly, I'd have to think through the problem through from all angles. That'll require a deliberate effort from my end and I don't know when I will have the time and mental bandwidth for it right now. I am just too busy with other work. The problem with complex PRs or significant changes is that merging them is simply not enough. Getting it wrong will simply just cause more work down the road.

I know that's an unsatisfying answer. I have been searching for new maintainers for the project for a very long time but nobody signed up for it. I will try to look at this again in July but at the moment I don't see myself carving out time for it.

**Comment by Vampire** [comment]
Ok, that's fine, take your time.
I know that situation pretty well too unfortunately.
I rebased all three PRs to latest state now.
Maybe you can at least activate the GitHub Action runs? :-)
