### ISSUE TITLE
Extension with name 'registryCredentials' does not exist. Currently registered extension names: [ext]

### ISSUE THREAD

**Issue by IvayloHrTonev** [bmuschko/gradle-docker-plugin#1076]
I have a custom plugin , which is applying gradle-docker-plugin and configure it.
I'm using Gradle 7 with Java 8 and gradle-docker-plugin version 6.6.1

Here us simplified version of my plugin:

```
class ExamplePlugin : Plugin<Project> {
    override fun apply(target: Project) {
	   target.pluginManager.apply(DockerRemoteApiPlugin::class.java)
	   val dockerObj = target.extensions.getByName("docker")
	   val registryCredentials =
	      (dockerObj as ExtensionAware).extensions.getByName("registryCredentials") as DockerRegistryCredential
	   registryCredentials.password.set(pass)
	   registryCredentials.username.set(user)
	   registryCredentials.url.set(url)
	   
	}
}
```

I can access docker extension  with ` val dockerObj = target.extensions.getByName("docker")`
But when I try to access `registryCredentials ` I got the error from the title:

```
Extension with name 'registryCredentials' does not exist. Currently registered extension names: [ext]
```

**Comment by bmuschko** [comment]
`DockerRegistryCredential` is not an extension of `DockerExtension`. It's a field so you'll have to call the getter method for it. See https://bmuschko.github.io/gradle-docker-plugin/current/api/com/bmuschko/gradle/docker/DockerExtension.html#registryCredentials.
