### ISSUE TITLE
Support Java 17

### ISSUE THREAD

**Issue by SimonHaenle2** [bmuschko/gradle-docker-plugin#1084]
Hi together,
since Java 17 has LTS and many advantages over Java11, it would be highly appreciated if you could migrate the project from Java11 to Java17.

Regards,
Simon

**Comment by bmuschko** [comment]
There are still plenty of projects that are using Java 11 if not 8. We want to be as backward compatible as possible.

What exactly makes you think that you wouldn't be able to use Java 17 as a consumer of the project? Or is the question about the Java version we are using to compile this project?

**Comment by lazvaha** [comment]
I can confirm that plugin works fine with Java 17.
The plugin version that I use is 7.3.0.

**Comment by SimonHaenle2** [comment]
Yes I'm sorry the issue can be closed. I thought the library causes some compatibility issues with Java11 / Java17 but the issue was something else :)
