### ISSUE TITLE
Building multiple docker images is not parallelized

### ISSUE THREAD

**Issue by evantahler** [bmuschko/gradle-docker-plugin#1092]
Hello! 

We use this excellent plugin at [Airbyte](https://github.com/airbytehq/airbyte), and I'm investigating if we can speed up our builds by parallelizing things.  [Here's a link to a Gradle build scan for our OSS project](https://scans.gradle.com/s/uyuvdnkjhpq4q/timeline).  You can see that building docker images is the slowest part of the process.  The build scan confirms that each docker build does not depend on a previous one as a dependency in the DAG. 

<img width="1428" alt="Screen Shot 2022-09-01 at 6 04 16 PM" src="https://user-images.githubusercontent.com/303226/188037336-27c6f15b-74fd-409f-8fee-7c74e3a28b19.png">

### Expected Behavior
The docker build steps happen in parallel. I don't see any mention of parallelization limits in the project.  We are using `org.gradle.parallel=true`... 

### Current Behavior
The docker build steps happen serially

### Context
See above.

### Steps to Reproduce (for bugs)
Check out the Aribyte repo, and build: `SUB_BUILD=PLATFORM ./gradlew build -x test --scan`

### Your Environment
M1 Mac using `com.bmuschko:gradle-docker-plugin:8.0.0`

```
$ uname -a
Darwin evan-airbyte-mac.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

$ java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Homebrew (build 17.0.2+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.2+0, mixed mode, sharing)

$ ./gradlew --version

------------------------------------------------------------
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (Homebrew 17.0.2+0)
OS:           Mac OS X 12.5.1 aarch64
```

**Comment by bmuschko** [comment]
The `parallel` option you are using will only execute tasks in parallel if they live in different projects: https://docs.gradle.org/current/userguide/performance.html#parallel_execution. I assume those tasks you mention all belong to the same Gradle project?

**Comment by evantahler** [comment]
Ah! Thank you for the information about `parallel`, I guess that's a red herring.  Regardless, I do believe that there are no interdependencies between our DockerBuildImage tasks.  They all share some common JAR building tasks, but those are rather quick. No DockerBuildImage depends on another.  The Gradle "Predecessors" report confirms that:

<img width="1101" alt="Screen Shot 2022-09-02 at 8 54 20 AM" src="https://user-images.githubusercontent.com/303226/188192484-3f8dc471-62db-4187-bb7b-152af9932233.png">

**Comment by bmuschko** [comment]
There's nothing in a custom task implementation that would prevent a plugin developer to execute parallel execution.

What I am noticing in your project is that you are defining the Docker tasks in the root project. Why exactly are they defined there and not in the projects that copies the TAR file e.g. `:buildDockerImage-server -> :airbyte-server:copyGeneratedTar`. You are defining inter-project dependencies so that might lead to a specific order especially if subprojects also depend on each other. I'd move the Docker tasks to the subproject that they belong to.

**Comment by evantahler** [comment]
Thanks @bmuschko! That's certainly the culprit.  I'll close this issue... thanks for the help!
