### ISSUE TITLE
Plugin doesn't work on Gradle 6.9.x

### ISSUE THREAD

**Issue by Sineaggi** [bmuschko/gradle-docker-plugin#1096]
### Expected Behavior
Build succeeds

### Current Behavior
Build fails with exception
```
> Task :dockerCreateDockerfile
FAILURE: Build failed with an exception.

* What went wrong:
Receiver class com.bmuschko.gradle.docker.tasks.image.Dockerfile$CopyFile does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.
2 actionable tasks: 2 executed
```

### Steps to Reproduce (for bugs)

Checkout the smoke-tests pr, run smoke tests on gradle 6.9.x

### Your Environment

Java 11, Gradle 6.9.x

**Comment by bmuschko** [comment]
Can you give me some background on why you want this to be fixed? Can you not upgrade to Gradle 7.x or what's the reasoning?

**Comment by bmuschko** [comment]
I released a new version of the plugin. Thanks again for your work. Do you want to give it try with that one?

**Comment by Sineaggi** [comment]
So internally our tests now pass with Gradle 6.9.3 again. I'll try to rework https://github.com/bmuschko/gradle-docker-plugin/pull/1097 to be simpler.
