### ISSUE TITLE
Trying to use with Java 18/19

### ISSUE THREAD

**Issue by robatxumo** [bmuschko/gradle-docker-plugin#1100]
### Expected Behavior

Gradle 7.5.1 claims to support java 18 but when I run the task to make the file I get the an error.

### Current Behavior

<img width="450" alt="image" src="https://user-images.githubusercontent.com/108505317/192625147-38d016ea-216b-4453-84a4-fd6e6b22c63a.png">

### Context

Not sure why the article by the author shows you have to make tasks in your gradle file for these lifecycle events. I see the tasks in the gradle window and am simply trying to run them.

### Steps to Reproduce (for bugs)

Just run the task to create the file:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/108505317/192625424-c878f0a3-f650-4766-a630-d25283a05010.png">

### Your Environment
Here is what I have in the build file:

    docker {
        springBootApplication {
            baseImage = 'openjdk:18-jdk-alpine'
            maintainer = 'Rob Williams "rwilliams@hepelscap.com"'
            ports = [8080]
        }
    }

**Comment by bmuschko** [comment]
Can you run the build from the command line? I want to make sure this isn't an issue with IntelliJ.

**Comment by robatxumo** [comment]
The build still works, just getting this error when trying to run one of the tasks that I assume that the plugin defined? should I try to run that task from the command line? my IntelliJ is setup to use the wrapper, btw. I tried to just tell it to use gradle 7.5 and 18.0.1 and then 7.5.1 but to no avail.

**Comment by bmuschko** [comment]
Yes, see if you get the same error when running the task **without** IntelliJ on the command line. If this only happens in IntelliJ then it must be an issue with your project configuration in IntelliJ which I can't really help you with.

**Comment by robatxumo** [comment]
Yes that also fails: 

> ~$ ./gradlew :dockerCreateDockerfile
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not open settings generic class cache for settings file '/Users/rwilli823/workspaces/features/features-services/settings.gradle' (/Users/rwilli823/.gradle/caches/7.5.1/scripts/cs5jx5wnk8luceobbbld5fccy).
> > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
>

**Comment by bmuschko** [comment]
OK, thanks. Please provide a sample build script to reproduce in a separate repository + the checked in Gradle wrapper files.

**Comment by robatxumo** [comment]
Do you want me to make an example project? I could try that. Just use initializr (Springboot) and then install the plugin and try and run it?

**Comment by Sineaggi** [comment]
In the first screenshot is says version 62, and in the following logs it says 63. Version 62 is java 18 and 63 is 19. Which one are you trying to run?

**Comment by robatxumo** [comment]
When it didn't work on 18, I upgraded to 19.

**Comment by Sineaggi** [comment]
Not positive that this is the case, but it's possible that if you're using the spring boot plugin that you need to specify the spring boot main class file to prevent spring's auto main finder from dying.
```groovy
tasks.named("bootJar") {
    mainClass = 'com.example.ExampleApplication'
}
```
Would need a call with `--stacktrace` to see the exact reason the build is failing.

**Comment by robatxumo** [comment]
@Sineaggi but the app runs. And assemble works?

**Comment by bmuschko** [comment]
The fix for this will be https://github.com/bmuschko/gradle-docker-plugin/pull/1107.
