### ISSUE TITLE
Support auto-detection DOCKER_HOST on macOS Ventura with latest Docker Desktop

### ISSUE THREAD

**Issue by donbeave** [bmuschko/gradle-docker-plugin#1109]
Most of my builds suddenly failed on the latest macOS version with the latest Docker Desktop app, the error is:

```
com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.HttpHostConnectException: Connect to http://127.0.0.1:2375 [/127.0.0.1] failed: Connection refused
```

The issue is because the unix socket file location was changed to user dir, in my case it is: `unix:///Users/donbeave/.docker/run/docker.sock`.

It can be fixed with the fix:

```
export DOCKER_HOST="unix://${HOME}/.docker/run/docker.sock"
```

But I think it's better to do such checking inside the plugin directly and autodetect the proper location.

### Your Environment

Apple M1 Max
macOS Ventura 13.0 (22A380)
Docker Desktop 4.13.0 (89412) for ARM64

**Comment by bmuschko** [comment]
Thanks for reporting. The logic that would have to be changed is [here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerExtension.groovy#L94-L110). Would you be interested in providing a pull request for this?

**Comment by gesellix** [comment]
This seems to be related with https://github.com/docker/for-mac/issues/6529. Please note that the change has been rolled back with [Docker Desktop 4.13.1](https://docs.docker.com/desktop/release-notes/#docker-desktop-4131) and they are going to retry with a better upgrade path and docs.

**Comment by bmuschko** [comment]
@gesellix Thanks for the pointer.
@donbeave Despite the fix in Docker Desktop I think it still makes sense to integrate your changes. I am going to have another look at your PR soon.
