### ISSUE TITLE
Add support of removeVolumes to com.bmuschko.gradle.docker.tasks.container.DockerRemoveContainer

### ISSUE THREAD

**Issue by stepan-romankov** [bmuschko/gradle-docker-plugin#111]
docker client supports this via 
RemoveContainerCmd.withRemoveVolumes

**Comment by bmuschko** [comment]
Could you please provide a pull request for this?

**Comment by stepan-romankov** [comment]
Sent you pull request https://github.com/bmuschko/gradle-docker-plugin/pull/112

**Comment by stepan-romankov** [comment]
Hello,

Sent you pull request
https://github.com/bmuschko/gradle-docker-plugin/pull/112


Best regards,
Stepan Romankov

**Comment by stepan-romankov** [comment]
Hello!
Would you please merge my pull request? I need it a lot especially container exit code for Wait Container. 

Best regards,
Stepan Romankov

**Comment by christianhuening** [comment]
+1 . This will probably solve my problem here: #115 as well.
THX!
