### ISSUE TITLE
Convert to java

### ISSUE THREAD

**Issue by Sineaggi** [bmuschko/gradle-docker-plugin#1118]
Currently the plugin is written mostly in groovy. As mentioned here https://github.com/bmuschko/gradle-docker-plugin/pull/1097#issuecomment-1250415025 and elsewhere, migrating from groovy to java would help our backwards compatibility https://github.com/bmuschko/gradle-docker-plugin/issues/1096

Intellij provides a "Refactor - Convert to Java" function that will rewrite the groovy into a partially compiling java equivalent. This seems like a good baseline for converting groovy to java. It will insert missing semi-colons and add method and class access modifiers to match java's rules which would otherwise be tedious and error-prone.

Things like automatic casts and boolean conversions are replaced with DefaultGroovyMethod calls, as well as custom Closure impls. Those would have to be manually rewritten into their equivalent java-isms.

**Comment by Sineaggi** [comment]
This issue is a requirement for compatibility with more gradle versions, see https://github.com/bmuschko/gradle-docker-plugin/issues/1096

**Comment by bmuschko** [comment]
Thanks again for your work. Your initial PR has been merged. Let me know when you are planning to tackle other classes.

**Comment by Sineaggi** [comment]
This should be complete as of https://github.com/bmuschko/gradle-docker-plugin/pull/1140 and https://github.com/bmuschko/gradle-docker-plugin/pull/1141
