### ISSUE TITLE
Tasks should not set values of properties

### ISSUE THREAD

**Issue by britter** [bmuschko/gradle-docker-plugin#1119]
When tasks are instantiated they should not `set` values of properties because setting values breaks behavior with conventions.

### Expected Behavior

It should be able to configure a conventions when using tasks from this plugin.

### Current Behavior

It's not possible to set a convention e.g. for `DockerCreateContainer.entrypoint` because `empty()` is called in the constructor which sets the value overriding any convention.

### Context

I'm writing a custom plugin on top of this plugin that configures several tasks provided by this plugin. My custom plugin should set some conventions for task values that can be overridden by build script authors. However setting conventions it in some cases not possible due to calls to `empty` and `set` in some of the tasks constructors.

### Reproducer

See https://github.com/britter/gradle-sandbox/tree/main/docker-plugin-conventions-issue

**Comment by britter** [comment]
Another example of this is `DockerRegistryCredentials` which _sets_ the default URL instead of setting a convention.

**Comment by britter** [comment]
Hey @bmuschko 👋 I will put a reproducer together!

**Comment by britter** [comment]
@bmuschko I've added a link to a reproducer that contains some more documentation about this issue.

**Comment by bmuschko** [comment]
Thanks for providing the example. I had a look at it. It's more clear now. Do you think you'll be able to help us out by providing a pull request for this?

**Comment by britter** [comment]
@bmuschko Yes I think I can have a look at this.
