### ISSUE TITLE
Apidoc Links in documentation point to 6.7.0

### ISSUE THREAD

**Issue by aconstantin** [bmuschko/gradle-docker-plugin#1121]
In the documentation of v9.0.0 located at https://bmuschko.github.io/gradle-docker-plugin the links to the apidoc of the gradle tasks point to an outdated documentation (the one from 6.7.0).

e.g. the link in chapter 2.3.1 for DockerOperation points to https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/DockerOperation.html which belongs to https://bmuschko.github.io/gradle-docker-plugin/api/overview-summary.html which states its version as 6.7.0.

I assume, the correct link would be to https://bmuschko.github.io/gradle-docker-plugin/current/api/com/bmuschko/gradle/docker/tasks/DockerOperation.html which belongs to
https://bmuschko.github.io/gradle-docker-plugin/current/api/overview-summary.html which states its version correctly as 6.7.0.

The linked url misses the `current` path segment.

**Comment by bmuschko** [comment]
The link you mentioned here is for an old version of the plugin. Where did you find the link? All references in the README.md now point to https://bmuschko.github.io/gradle-docker-plugin/current/user-guide/.

**Comment by aconstantin** [comment]
Here are some screenshots with explanation, so you can see where I found the links.

Starting at https://github.com/bmuschko/gradle-docker-plugin and following the link on the right

<img width="1004" alt="1-githup-repo-page" src="https://user-images.githubusercontent.com/1051339/201857147-5aafe03a-6195-4453-a20b-b62b89213d2f.png">

In the linked userguide located at https://bmuschko.github.io/gradle-docker-plugin/current/user-guide/ (it is `current`)

I browsed to [2.3. Custom task types](https://bmuschko.github.io/gradle-docker-plugin/current/user-guide/#custom_task_types) (still `current`)

<img width="1004" alt="2-linked-userguide-at-current" src="https://user-images.githubusercontent.com/1051339/201857801-80035c5b-261d-4a56-9517-98c91ac2cf01.png">

There I followed the link to [DockerOperation](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/DockerOperation.html) (not `current` anymore).

<img width="1004" alt="3-linked-apidocs-not-current" src="https://user-images.githubusercontent.com/1051339/201857903-fffdb705-4125-4804-81ae-6e9ac16618ed.png">

To see what apidocs I was browsing I followed the [Overview](https://bmuschko.github.io/gradle-docker-plugin/api/overview-summary.html) link, which took me here

<img width="1004" alt="4-overview-of-linked-apidocs-not-current" src="https://user-images.githubusercontent.com/1051339/201858038-db184b3e-0bc8-45df-ac46-10e358ddf841.png">

and here it states v6.7.0

I hope this helps to reproduce this.

**Comment by bmuschko** [comment]
Thanks, this will be fixed with the next release: https://github.com/bmuschko/gradle-docker-plugin/pull/1122.

Side note: You can add the version of the API docs you need in the URL, e.g. https://bmuschko.github.io/gradle-docker-plugin/9.0.0/api/overview-summary.html
