### ISSUE TITLE
DockerRemoteApiPlugin broken in multi project build since 9.0.0

### ISSUE THREAD

**Issue by mattlong-finocomp** [bmuschko/gradle-docker-plugin#1123]
I get the following error when attempting to upgrade to version 9.0.0 or 9.0.1 of this plugin.
`A problem occurred evaluating project ':javascript-app'.
> Could not create task ':javascript-app:buildImage'.
   > Cannot set the value of task ':javascript-app:buildImage' property 'dockerClientService' of type com.bmuschko.gradle.docker.internal.services.DockerClientService using a provider of type com.bmuschko.gradle.docker.internal.services.DockerClientService.
`

I suspect this issue was introduced in https://github.com/bmuschko/gradle-docker-plugin/pull/1108

### Expected Behavior
Project with configuration that works in 8.1.0 should continue to work

### Current Behavior
Above error appears when loading the Gradle project in IntelliJ.
See context below for details on project structure, but when upgrading the plugin version  from 8.1.0 in either subproject in isolation the Gradle project cleanly loads. When both are upgraded the above error occurs.

### Context
I have a Gradle multi-project build.
There is a root project which mainly contains no code, but just configures repositories for all projects and configures some unrelated gradle plugins.
There is a java application in a subproject which is using the docker-java-application plugin.
There is a static web application in a subproject which is using the docker-remote-api plugin.
In my real application I use the openapi generator gradle plugin to generate typescript definitions based on an Open API Specification document. I've omitted this from the sample reproduction repo as applying the plugin is enough to trigger the issue.

### Steps to Reproduce (for bugs)
See https://github.com/mattlong-finocomp/gradle-docker-plugin-error
Look at javascript-app/build.gradle and uncomment indicated problematic plugins.
Subsequently downgrading the docker-java-application plugin in the :java-app project will cause the error to not appear even though javascript-app is still using 9.0.1.

### Your Environment
Linux Pop!_OS 20.04 LTS
Java Temurin 17.0.1

**Comment by Sineaggi** [comment]
Does it work if you if you add the plugin with an `apply false` in the root project?

```groovy
plugins {
    id 'base'
    id 'com.bmuschko.docker-remote-api' version '9.0.1' apply false
}
```

**Comment by bmuschko** [comment]
@Sineaggi Thanks for the pointer. Seems like that's the issue. I am going to close the issue.

**Comment by twarner-sofi** [comment]
I don't think this issue should be closed. Requiring an "apply false" in the root is not really a solution, just a workaround, and besides it isn't even documented.

**Comment by bmuschko** [comment]
@twarner-sofi The issue has to be fixed in Gradle core. We can't really fix it on the plugin-level and it does apply to any plugin that uses the build service functionality. It's not specific to this one plugin. I would suggest the following:

1. Please comment or upvote the Gradle core GitHub issue so that it can be fixed.
2. Please provide a pull request with a functional test and/or documentation if you'd like to see it clarified.
