### ISSUE TITLE
Feature Request: Ability to filter out libs copied into images

### ISSUE THREAD

**Issue by mattlong-finocomp** [bmuschko/gradle-docker-plugin#1126]
Spring Boot has a gradle configuration called developmentOnly which is used for things like spring-boot-devtools and the h2 jdbc driver.
Spring Boot apps are usually configured such that the runtime classpath extends from the developmentOnly classpath.
This means that the developmentOnly dependencies show up on the runtime classpath and get bundled into the libs directory and are included in images built by this plugin.
This is something that only affects exploded deployments because the JARs built by Spring Boot exclude the developmentOnly dependencies.

See discussion here: https://github.com/spring-projects/spring-boot/issues/15382

The Jib project added this feature as mentioned here https://stackoverflow.com/questions/61074597/spring-boot-devtools-being-used-inside-docker-container-even-after-exclusion-in/65238580#65238580

I don't expect this to be some implicit knowledge built into this plugin, but a generic mechanism similar to the solution Jib has provided where a user could configure exclusions would be helpful.

**Comment by bmuschko** [comment]
The task `dockerSyncBuildContext` is of type `TaskProvider<Sync>`. You can probably just call the `exclude` method on it and provide the file pattern you don't need. See the [Gradle API docs](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Sync.html) for more info.

**Comment by mattlong-finocomp** [comment]
Ah of course, my mistake I completely overlooked that!
`tasks['dockerSyncBuildContext'].exclude "**/spring-boot-devtools-*.jar"`
Using that did the trick.
Thanks for the tip.
