### ISSUE TITLE
DockerPushImage should return success/failure value

### ISSUE THREAD

**Issue by davidartplus** [bmuschko/gradle-docker-plugin#113]
Groovy class related:
https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy

When failing to push images to Docker, the gradle task is completed and the Gradle build is successful, and it shouldn't. This is a snippet of a build log for the DockerPushImage failure case:

    :pushTaskUsingDockerPushImage
    Pushing image with name ‘domain.com:5050/image’.
    The push refers to a repository [domain.com:5050/image] (len: 1).
    Sending image list.
    :nextGradleTask

Note that **the build still succeeds**

This is a snippet for a successful DockerPushImage case:

    :pushTaskUsingDockerPushImage
    Pushing image with name ‘domain.com:5050/image’.
    The push refers to a repository [domain.com:5050/image] (len: 1).
    Sending image list.
    Pushing repository domain.com:5050/image (1 tags).
    Image b4c0381b769 already pushed, skipping.
    Image 8b44529354f already pushed, skipping.
    Image 8ec23262868 already pushed, skipping.
    ...
    Pushing 6ff768e8019.
    :nextGradleTask

Is it possible to change the void nature of the method to a boolean or int value to know how to proceed in case the image push fails?

**Comment by bmuschko** [comment]
My assumption was that `PushImageResultCallback` would throw an exception of some sort if something went wrong. It doesn't seem to be the case. Can you look into Docker Java and see how this could be handled?

**Comment by bmuschko** [comment]
@davidartplus Can you please follow up on the question raised on the docker-java issue?

**Comment by bmuschko** [comment]
Seems like the issue was closed on Docker Java. I am also going to close it here. This is very likely just an issue in Docker Java. Feel free to reopen if you need further assistance. However, you'd need to provide a reproducible example.
