### ISSUE TITLE
Dockerfile type task does not work with gradle doLast

### ISSUE THREAD

**Issue by GhassanGuessous** [bmuschko/gradle-docker-plugin#1145]
### Expected Behavior
Should create dockerfile.

### Current Behavior
Caused by: java.lang.IllegalStateException: Please specify instructions for your Dockerfile

### Context
Simple gradle build.

### Steps to Reproduce (for bugs)
- create a gradle task with type Dockerfile
- put dockefile instructions inside a doLast
- run the task 

### Your Environment
Local dev environement.

The error is thrown by verifyValidInstructions method, checking if instructions are emtpty. Could you please advise about incompatibility with doLast? why is it different compared with a task without a doLast.

**Comment by bmuschko** [comment]
You do not set instructions in `doLast`. You need to configure the task so that it happens at execution time. Calling a method in `doLast` is not the correct way to do it.

**Comment by GhassanGuessous** [comment]
Thanks for the explanation, I'll close the issue.
