### ISSUE TITLE
Failing the build upon WaitContainer-Task returning non-zero exit code

### ISSUE THREAD

**Issue by christianhuening** [bmuschko/gradle-docker-plugin#115]
Hi there,

I intend to use the WaitContainer-Task to fail my build in case it returns a non-zero exit code from the container it is waiting for. 
Currently I have something like this:

```groovy
task createContainerForCDT(type: DockerCreateContainer){
    imageId = '<MyFancyImageID'
}

task startContainerForCDT(type: DockerStartContainer, dependsOn: [createContainerForCDT]) {
    targetContainerId{ createContainerForCDT.getContainerId()}
}

task consumerDrivenTest(type: DockerWaitContainer, dependsOn: [startContainerForCDT]){
    targetContainerId{ createContainerForCDT.getContainerId()}
}
``` 

Now I want to fail in task "consumerDrivenTest" if the created container returns exit code != 0.
How can I do this?

Thanks!
Christian

**Comment by bmuschko** [comment]
You probably have to inspect the response from the Docker Java call. If the response indicates a failure then throw a `GradleException`. Can you open a pull request for this?

**Comment by bmuschko** [comment]
See pull request #112.

**Comment by bmuschko** [comment]
I am not going to pull in #112. Some of the issues have been resolved already. If you can provide me with a pull request that exposes the exit code I'd be happy to review and merge.

**Comment by marbon87** [comment]
Was this problem solved? I am using ```DockerWaitContainer``` the same way as shown above, but the Gradle-Tasks is not failing when the container exists with status code 1

**Comment by cdancy** [comment]
@marbon87 we do not expose and/or return the exit code. If you'd like to send in a PR we'd be more than happy to review it.

**Comment by marbon87** [comment]
@cdancy please merge https://github.com/bmuschko/gradle-docker-plugin/pull/189

**Comment by cdancy** [comment]
Closing as we now return exit-code for `DockerWaitContainer`.
