### ISSUE TITLE
Incorrect annotation in DockerCopyFileToContainer

### ISSUE THREAD

**Issue by gjvoosten** [bmuschko/gradle-docker-plugin#1150]
Gradle gives the following warning:

> Execution optimizations have been disabled for task ':someTask' to ensure correctness due to the following reasons:
> - In plugin 'com.bmuschko.docker-remote-api' type 'com.bmuschko.gradle.docker.tasks.container.DockerCopyFileToContainer' property 'tarFile' has `@Input` annotation used on property of type 'RegularFileProperty'. Reason: A property of type 'RegularFileProperty' annotated with `@Input` cannot determine how to interpret the file. Please refer to https://docs.gradle.org/7.6/userguide/validation_problems.html#incorrect_use_of_input_annotation for more details about this problem.

https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/java/com/bmuschko/gradle/docker/tasks/container/DockerCopyFileToContainer.java#L60 should probably be annotated with `@InputFile` instead.

**Comment by bmuschko** [comment]
Would you be interested in providing a pull request for this?

**Comment by gjvoosten** [comment]
> Would you be interested in providing a pull request for this?

Quite possibly. However, on a clean checkout, `./gradlew functionalTest` seems to have some failing tests, and `./gradlew functionalTest --tests=DockerCopyFileToContainerFunctionalTest` doesn't show the warning (after upgrading with `./gradlew wrapper --gradle-version=7.6`). That makes it hard to determine if the warning has gone after fixing.
