### ISSUE TITLE
Debug with IntelliJ

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [bmuschko/gradle-docker-plugin#1157]
Someone has been able to debug a project which uses `gradle-docker-plugin` with IntelliJ?

I tried to follow [these instructions](https://blog.jetbrains.com/idea/2019/04/debug-your-java-applications-in-docker-using-intellij-idea/) with no luck.

**Comment by bmuschko** [comment]
Your question isn't really specific to the plugin's functionality. This plugin may start a container with the help of a task, but it's not doing anything special here. I would suggest you ask the question on the Gradle forum.

**Comment by JavierSegoviaCordoba** [comment]
Yeah, I know it is not related to the plugin itself. Still, probably someone here found this use case before in other plugins due to the nature of this problem as the problem is directly related to the fact that IntelliJ Remote config is asking for a Dockerfile.

**Comment by bmuschko** [comment]
It doesn't look like anyone is going to chime in. Please ask on the Gradle forum.
