### ISSUE TITLE
How to lazily initialize commands for DockerExecContainer?

### ISSUE THREAD

**Issue by ThomGeG** [bmuschko/gradle-docker-plugin#1159]
Hey all,

I'm just looking for a bit of help on how to lazily provide the commands for a `DockerExecContainer` task. 

My project builds a docker image using the gradle-docker-plugin, however I now also want to scan that image for vulnerabilities using [Trivy](https://github.com/aquasecurity/trivy). They don't have a gradle plugin but do have a docker image, so I'm trying to use the `DockerCreateContainer` and `DockerStartContainer` tasks to get a container of it up and running and then run the necessary commands inside of it with a `DockerExecContainer`. The relevant part currently looks like this:
```
        def trivy = project.tasks.register('trivy', com.bmuschko.gradle.docker.tasks.container.DockerExecContainer) {
            group = "Trivy"
            description = "Identifies and reports on known vulnerabilities (CVEs) in the generated docker image for this project"
            dependsOn buildImage, trivyStart
            targetContainerId trivyCreate.get().containerId

            withCommand(['mkdir', '/trivy/'])  // create the directory we'll be saving reports too (trivy can't do it)
            withCommand(['trivy', 'version'])  // print the version for debugging
            withCommand(["trivy", "image", "${-> buildImage.get().imageId.get()}", "-f", "json", "-o", "/trivy/trivy.json", "--security-checks", "vuln", "--timeout", "15m"])
            withCommand(["trivy", "image", "${-> buildImage.get().imageId.get()}", "-f", "table", "-o", "/trivy/trivy.txt", "--security-checks", "vuln", "--timeout", "15m"])

            finalizedBy trivyLog, trivyCopy
        }
```

**The problem I'm having is that the `commands` for the `DockerExecContainer` are eagerly evaluated, but I need them to be lazily evaluated so I can pass in the ID for the image I've just built.** 

Has anybody ever had to do anything similar and found a nice way of doing it? I've tried a couple of different things, most notably trying to add the commands at execution time when the image ID is known, however the `commands` property is already finalized by that point and can't be modified.

The only solution I can see to my problem would be extending the `DockerExecContainer` and overriding the `doRunRemoteCommand` to instead build the commands on the fly using an input containing just the image ID.

**Comment by bmuschko** [comment]
Use the property named `commands` instead. It's of type `ListProperty<String[]>`. The `withCommand` method will be removed in the future. It only takes a `String[]` which isn't lazy, as described by you.

**Comment by bmuschko** [comment]
Oh, nm. I see what you are getting at. You'll probably have to implement your own task for that, as the `commands` doesn't take itself a list of Property types.

**Comment by ThomGeG** [comment]
Trivy is capable of scanning images via their ID rather than name, as that's what I currently do with the CLI tool outside Gradle, however because of the eager evaluation problem I've only been able to get this working by hardcoding it in.

Using the name instead is an interesting idea as at least one of the tags should be fixed/known, but my original aspiration was to have Trivy act as a gate before tagging the image. I might do it that way in the short term to prevent having to use an overly complicated custom task.

**Comment by ThomGeG** [comment]
For any future visitors in a similar predicament, be sure to check the referenced PR.

You can lazily evaluate the entire `commands` list by mapping one `Provider` to another, which is how I managed to lazily provide the `imageId`.
