### ISSUE TITLE
No value has been specified for property 'classpath' when run in custom plugin

### ISSUE THREAD

**Issue by jochenchrist** [bmuschko/gradle-docker-plugin#116]
Related to #17 and #35.

When applying the `com.bmuschko.docker-remote-api` in a custom plugin to share configuration, the exception `No value has been specified for property 'classpath'`occurs.

I have provided some demo code to reproduce the issue:

1) Custom Standalone Plugin
https://github.com/jochenchrist/spring-boot-gradle-docker-plugin

2) Demo Project using this plugin
https://github.com/jochenchrist/spring-boot-gradle-docker-plugin-demo-project

Steps to reproduce are described in https://github.com/jochenchrist/spring-boot-gradle-docker-plugin/blob/master/README.asciidoc

Probably there is an issue with the sction
```
buildscript {
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:2.6.1'
    }
}
```

which must be defined twice in the plugin and the demo project to compile the script.

**Comment by bmuschko** [comment]
This is likely happening as a script plugin has it's own classloader. Looking at your custom standalone plugin it is very unusual to apply a script plugin from a binary plugin. What I'd recommend to do instead is to implement the logic in the `apply` method.

    import org.gradle.api.Plugin
    import org.gradle.api.Project

    public class DockerPlugin implements Plugin<Project> {

        void apply(Project project) {
            project.buildscript {
                repositories {
                    jcenter()
                }
                dependencies {
                    classpath 'com.bmuschko:gradle-docker-plugin:2.6.1'
                }
            }

            project.apply plugin: 'com.bmuschko.docker-remote-api'
        
            ...
        }
    }

**Comment by jochenchrist** [comment]
Hi bmuschko,

thanks for your quick reply.
Your suggested solution works fine :-)

Pushed to demo in
https://github.com/jochenchrist/spring-boot-gradle-docker-plugin

:+1:
