### ISSUE TITLE
missing image name and tag with docker-remote-api

### ISSUE THREAD

**Issue by genbutsu** [bmuschko/gradle-docker-plugin#1160]
### Expected Behavior
when creating a docker image with docker-remote-api, is there any command to set NAME+TAG? 
I'm searching command to set it in "createDockerImage"

### Current Behavior
no image name and or tag

### Context
id 'com.bmuschko.docker-remote-api' version '9.1.0'

task createDockerImage(type: DockerBuildImage) {

**Comment by bmuschko** [comment]
All properties of the task are documented in the [Javadoc](https://bmuschko.github.io/gradle-docker-plugin/9.1.0/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html). The user guide has [full examples](https://bmuschko.github.io/gradle-docker-plugin/current/user-guide/#creating_a_dockerfile_and_building_an_image).
