### ISSUE TITLE
On macOS Docker Desktop 4.16.2 (95914), "Use containerd for pulling and storing images" must be unchecked; otherwise, DockerBuildImage and buildKit: false docker build commands fail with 502

### ISSUE THREAD

**Issue by doctorpangloss** [bmuschko/gradle-docker-plugin#1168]
The legacy docker builder doesn't work with a specific Docker Desktop configurations. Specifically, if you see the error:
```
➜  xxx git:(main) ✗ gradle xxx-containers:createImage_xxx_builder_linux_amd64
Error during callback
com.github.dockerjava.api.exception.DockerException: Status 502: Bad response from Docker engine

        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:249)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)

> Task :appmana-containers:createImage_appmana_builder_linux_amd64 FAILED
Building image using context '/Users/xxx/Documents/xxx/xxx-containers/src/main/resources/docker/xxx/builder'.
Using Dockerfile '/Users/xxx/Documents/xxx/xxx-containers/src/main/resources/docker/xxx/builder/Dockerfile'
Using images 'xxx:latest-amd64', 'xxx:latest'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xxx-containers:createImage_xxx_builder_linux_amd64'.
> Status 502: Bad response from Docker engine
```
uncheck "Use containerd for pulling and storing images."

### Expected Behavior
Building images.

### Current Behavior
A mysterious error.

### Context
This will resolve issues for users who have this checked.

### Steps to Reproduce (for bugs)
 1. Check Use containerd for pulling and storing images in the Features in development section of Docker Desktop
 2. Observe DockerBuildImage tasks stop working.
### Your Environment
macOS 15
OpenJDK 17
Docker Desktop 4.16.2 (95914)
docker plugin 9.2.1

**Comment by bmuschko** [comment]
When you say "legacy Docker builder", what exactly do you mean by that? FYI: Docker Java may not be compatible with containerd. You will likely have to open an issue with the Docker Java project. It handles all the low-level communication with the Docker daemon (as you can see by the stack trace).

**Comment by bmuschko** [comment]
I am going to close this issue. Please raise an issue for the [Docker Java project](https://github.com/docker-java/docker-java).
