### ISSUE TITLE
Support for '--privileged' for DockerCreateContainer

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#117]
Support for creating containers in "privileged" mode. We are just exposing another property of the docker-java library here. I can take on this work.

**Comment by bmuschko** [comment]
Go for it.

**Comment by bmuschko** [comment]
Are you ready to provide a pull request for this one as well?

**Comment by cdancy** [comment]
@bmuschko sent in PR #130. Should be good to go. Thanks.
