### ISSUE TITLE
DockerPushImage does not fail the task / build if the upload fails

### ISSUE THREAD

**Issue by tkrah** [bmuschko/gradle-docker-plugin#1178]
### Expected Behavior
If a DockerPushImage task is executed but fails (here it fails because of missing privileges of the user) the build should fail and not be marked as successful.

### Current Behavior
If you run a DockerPushImage task it will finish at the moment with:
```

> Task :pushDockerImage
Pushing image '$registry/image:version' to registry.

BUILD SUCCESSFUL in 6s
```

In the debug logs however you will find this:

`2023-04-24T14:42:02.971+0200 [DEBUG] [com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.wire] http-outgoing-2 << "{"errorDetail":{"message":"unauthorized: User is unauthorized to upload to $registry/image/_uploads"},"error":"unauthorized: User is unauthorized to upload to $registry/image/_uploads"}[\r][\n]"`

The image failed to upload because the user does not have the rights to do so.

### Context
Push an image and expect the build to fail if the push fails.

### Steps to Reproduce (for bugs)
1. Call a DockerPushImage to a registry where you don't have the privilege to upload anything.

### Your Environment
Plugin Version 9.3.1 with Gradle 8.1 and JDK 17.

**Comment by bmuschko** [comment]
Good catch. Would you be interested in providing a pull request for this? Step 1 would be to write a functional test that reproduces the issue, step 2 to actually fix it.

**Comment by tkrah** [comment]
I'll try to provide a PR, may take some time though, need to get familiar again with the setup in the plugin here.

**Comment by MarkRx** [comment]
Can confirm. Issue might be in the docker-java library. I tried updating to 3.3.2 but it still doesn't fail.

> 00:01:05.946  2023-07-11T09:50:37.315-0400 [DEBUG] [com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.wire] http-outgoing-0 << "{"errorDetail":{"message":"trying to reuse blob sha256:b51194abfc91510e7cc523fd1735ea595e9ab7b8fbb8697e7e2ac6bb04b0f5e3 at destination: pinging container registry us-east4-docker.pkg.dev: Get \"[https://us-east4-docker.pkg.dev/v2/\](https://us-east4-docker.pkg.dev/v2//)": dial tcp 64.233.176.82:443: connect: connection refused"},"error":"trying to reuse blob sha256:b51194abfc91510e7cc523fd1735ea595e9ab7b8fbb8697e7e2ac6bb04b0f5e3 at destination: pinging container registry us-east4-docker.pkg.dev: Get \"[https://us-east4-docker.pkg.dev/v2/\](https://us-east4-docker.pkg.dev/v2//)": dial tcp 64.233.176.82:443: connect: connection refused"}[\n]"
