### ISSUE TITLE
mainClassName cannot refer to a class that is in a project dependency

### ISSUE THREAD

**Issue by mkeefe-ac** [bmuschko/gradle-docker-plugin#1184]
### Expected Behavior

It should be possible for mainClassName to refer to a class that exists within a project dependency.  This is the same issue described in https://github.com/bmuschko/gradle-docker-plugin/issues/893 but with some additional context.

### Current Behavior

Using 'com.bmuschko:gradle-docker-plugin:9.3.1' this fails with the error "Main class name could not be resolved"

This worked in version 4.0.4 (we are in the process of upgrading Gradle from 5.x to 8.x and we had to upgrade gradle-docker-plugin as a result)

[This](https://github.com/bmuschko/gradle-docker-plugin/pull/892/files#r354324936) seems to reference the problem.

Expanding the check for the existence of the class or providing another attribute to skip the check entirely would suffice without introducing much additional complexity to the plugin.  Also, based on the code, it isn't clear to me why the value of "mainClassName" isn't simply being returned and the check is executing at all.

### Context

Our Spring (not Spring Boot) application is divided into a generic "runner" component which is shared among several other microserivce components.  Each microservice provides its own distinct functionality, but they all rely on the same "runner" for bootstrapping/configuration.  

This is currently a blocking issue for our upgrade unless we make some significant changes to our overall build structure.

**Comment by mkeefe-ac** [comment]
I did some more digging and it looks like the problem is actually that getApplicationMainClassName() is called when the plugin is loaded while our scripts were trying to set 'mainClassName' after the load.

I also discovered that 'mainClassName' is being utilized by yet another plugin ('com.github.johnrengelman.shadow') in our build scripts so it isn't clear if the original intent was to configure that plugin or the gradle-docker-plugin, shadow, or both.  (This is a legacy project with the original developers long gone.)  

So, the good news is that it looks like I should be able to pass a value to gradle-docker-plugin's "mainClassName" property directly for the impacted modules.  However this wouldn't be necessary if the plugin could auto-detect the main class coming from a project dependency.  In any case, it looks like there was a breaking change at some point that causes the existing scripts to fail.

**Comment by bmuschko** [comment]
1. Setting a custom main class name from the extension

I suspect that you are experiencing some side effect by configuring the `mainClassName` from somewhere else. The plugin has at least a functional test in place to verify the correct behavior, e.g. see [DockerJavaApplicationPluginFunctionalTest."Can provide a specific main class name"](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginFunctionalTest.groovy#L130-L147). I would suggest to set up a sample project that reproduces the issue (if there is one).

2. Auto-resolving a main class in a project dependency

I personally won't have the time in the next couple of months to look at this. I am happy to review a pull request for this functionality if you'd like to provide it. Your best option with the least effort would be to identify why 1. isn't working for you.

**Comment by bmuschko** [comment]
I am closing this issue for now. Let me know if you can either reproduce 1. or want to provide a PR for 2.
