### ISSUE TITLE
Feature: buildx & cache-to

### ISSUE THREAD

**Issue by nbrugger-tgm** [bmuschko/gradle-docker-plugin#1186]
### Expected Behaviour
When defining a task of the type `DockerBuildImage` i should be able to define a `buildx` docker build along the lines of:
```
buildx.set(true)
```
With this comes a new, not yet usable argument called `cache-to` which would be the output equivalent to the current `cache-from`.
### Current Behaviour
to execute a buildx build a large setup of multiple tasks is needed and all the work from `DockerBuildImage` needs to be redone (gradle caching use for example). (using `DockerOperation`) with tasks such as: `createDockerContainerBuilder`, `useDockerContainerBuilder`, `revertUsingDockerContainerBuilder` and of course `dockerxBuild`

### Context
This is needed to use remote caches with docker

**Comment by bmuschko** [comment]
Docker Java and more specifically the Docker remote API doesn't support buildx AFAIK. Please point me to the relevant method/API/documentation that explains how to use it if you think it is available.

**Comment by nbrugger-tgm** [comment]
As far as I was able to figure out there is an option in the api to use buildkit using grpc (see https://github.com/moby/moby/issues/41711  first comment)

That said "There is a Grpc endpoint" is... not a flawlessly documented api to say the least. So for buildx/buildkit to work with this plugin the following things would need to happen:
- docker / moby (idk who does what) release a documentation for their mysterious grpc api
- docker for Java implements the calls to this api
- the new api in the docker for Java lib is used by the plugin

Right? This sounds like a "in the best case it just takes a very long time" thing and might not happen at all.

Docker for Java has no open ticket because all of them were closed as stale, but at least the ticket on docker/moby side is open althought there seems to be minor to no interest from both sides

**Comment by bmuschko** [comment]
OK, thanks for the info. It's a long shot. I'd try opening an issue for the Docker Java project first and see where it goes. Once supported there, we can think about integrating it into the plugin. Thanks! I am going to close the issue here for now. Comment here if the feature gets more traction.

**Comment by sschuberth** [comment]
> OK, thanks for the info. It's a long shot. I'd try opening an issue for the Docker Java project

For reference: https://github.com/docker-java/docker-java/issues/1657
