### ISSUE TITLE
the plugin tasks does not appear in gradle

### ISSUE THREAD

**Issue by asafm-logzio** [bmuschko/gradle-docker-plugin#120]
I added this code to my build.gradle file:
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:2.6.1'
    }
}
apply plugin: 'com.bmuschko.docker-remote-api'
```
but when I run ```gradlew tasks``` I don't see any new tasks related to this plugin

**Comment by bmuschko** [comment]
The plugin does not create task instances out-of-the-box. It only provides custom task types. You'll have to create them yourself in your build script based on the type.
