### ISSUE TITLE
Cannot invoke "java.util.List.containsAll(java.util.Collection)" because "repoTags" is null

### ISSUE THREAD

**Issue by balage1551** [bmuschko/gradle-docker-plugin#1212]
I've configured my task (Kotlin DSL) as follows:

```kotlin
val buildDocker by tasks.registering(DockerBuildImage::class) {
    dependsOn("rebuild")
    if (deployModeParam != "local") {
        dockerFile.set(file("Dockerfile"))
    } else {
        dockerFile.set(file("Dockerfile-local"))
    }
    println("Using dockerfile: ${dockerFile.get()}")
    inputDir.set(project.projectDir)
    images.add("tatooine/frontend:${deployModeParam}")

    println(images)
}
```

When I run this task, I got `Cannot invoke "java.util.List.containsAll(java.util.Collection)" because "repoTags" is null` exception  at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage$1.isSatisfiedBy(DockerBuildImage.java:329)

I debugged the code and this is the call in DockerBuildImage:

```java
rivate final Spec<Task> upToDateWhenSpec = new Spec<Task>() {
        @Override
        public boolean isSatisfiedBy(Task element) {
            File file = getImageIdFile().get().getAsFile();
            if (file.exists()) {
                try {
                    String fileImageId;
                    try {
                        fileImageId = Files.readString(file.toPath());
                    } catch (IOException e) {
                        throw new UncheckedIOException(e);
                    }
                    // This causes the error:
                    List<String> repoTags = getDockerClient().inspectImageCmd(fileImageId).exec().getRepoTags();
                    // This where the error raises:
                    if (!getImages().isPresent() || repoTags.containsAll(getImages().get())) {
                        return true;
                    }
                } catch (DockerException ignored) {
                }
            }
            return false;
        }
    };
```

I've debugged the code and  evaluated the `getDockerClient().inspectImageCmd(fileImageId).exec()` call chain and it returns an object where the `rawValues` contains the correct data, but all the fields are null.

To test it, I added this code snippet to my task:

```kotlin
val file = imageIdFile.get().asFile
    val fileImageId: String
    try {
        fileImageId = Files.readString(file.toPath())
    } catch (e: IOException) {
        throw UncheckedIOException(e)
    }
    val response = dockerClient.inspectImageCmd(fileImageId).exec()
    println("RT: " + response.rawValues["RepoTags"] + " -> " + response.repoTags)
```

and it prints: 
``` 
RT: [tatooine/frontend:local] -> null
```

My gradle is 7.4.2.
The plugin used:   id("com.bmuschko.docker-remote-api") version "9.4.0"

**Comment by balage1551** [comment]
As it turned out, it was caused by a version clash on docker-java plug-in.

**Comment by nvilagos** [comment]
For those who are still facing this issue, I have found a possible workaround and I have [opened an issue](https://github.com/bmuschko/gradle-docker-plugin/issues/1227).

Before every Docker image build, delete either the previously built Docker image, or the following file: `build/.docker/docker_buildImage-imageId.txt`.

It's not convenient, but can be applied, and unfortunately I haven't found any version change that could help in my case.
