### ISSUE TITLE
DockerPushImage task does not fail, when push is unsuccessful

### ISSUE THREAD

**Issue by tillbier** [bmuschko/gradle-docker-plugin#1215]
### Expected Behavior

When the image can not be pushed to the repository, the gradle task should fail

### Current Behavior

When executing a DockerPushImage task to push a docker image to a repository, that I am logged in to, I do not get any error:

![image](https://github.com/bmuschko/gradle-docker-plugin/assets/38524338/bfade400-7b93-4ac4-8d1d-2a05fe60c0f1)

When pushing the exact same image to my repository without being logged in, I get this error message:

![image](https://github.com/bmuschko/gradle-docker-plugin/assets/38524338/9fca39e2-d3f2-41cd-8060-43e7a92f2fde)

I would expect the task/build to be unsuccessful, when the image can not be pushed.

### Context

Jobs in my gitlab pipeline are presumable run successfully, although that was not the case. 

### Steps to Reproduce (for bugs)

1. Build a image for a docker repository, that you have no rights to push to
2. Create a DockerPushImage task to push that image
3. Execute the task -> the task does not fail

**Comment by bmuschko** [comment]
I think we should cover this case properly with this [test](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImageFunctionalTest.groovy#L9-L48) but maybe your use case is different. What version of the plugin do you use?

**Comment by tillbier** [comment]
I use the version 9.3.1

**Comment by bmuschko** [comment]
A change had been made in 9.3.2 to fix this issue: https://github.com/bmuschko/gradle-docker-plugin/issues/1178

**Comment by tillbier** [comment]
Yes, updating to the newest version actually helped. I will close the issue. Thank you very much!
