### ISSUE TITLE
Support podman//buildah

### ISSUE THREAD

**Issue by mouradxmt** [bmuschko/gradle-docker-plugin#1217]
### Expected Behavior
Gradle docker plugin to support custom flags that can be passed to buildah
### Current Behavior
The plugin is based on docker java and not the CLI which limits the use of buildah or pass flags 
### Context
I want to use podman and benefit from the remote cache mechanism that comes from buildah, however it is impossible to pass any flags that is not supported directly by docker java API

### Steps to Reproduce (for bugs)
n/a
### Your Environment
n/a

**Comment by bmuschko** [comment]
Supporting the buildkit or buildah CLI instead of using the Docker remote API would mean a complete rewrite of the plugin. You will want to look into other Gradle plugins that support your use case.
