### ISSUE TITLE
Support for docker step reports for DockerBuildImage

### ISSUE THREAD

**Issue by rfhayashi** [bmuschko/gradle-docker-plugin#123]
When using `DockerBuildImage` task, I miss docker step reports, example:

    Step 1 : FROM jenkins:1.625.1

       ---> 496f04f9620b

    Step 2 : COPY plugins.txt /usr/share/jenkins/plugins.txt

       ---> Using cache

       ---> ab0554ac035b

    Step 3 : RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt

       ---> Using cache

 	   ---> 228d801a2adc

	Successfully built 228d801a2adc

As I could find, it would be a case of subclassing `BuildImageResultCallback`, overwritting `onNext` and log `BuildResponseItem.stream`. The thing is that `BuildImageResultCallback` is instantiated by reflection as docker-java dependency is injected dinamically (btw, I didn't understand why, probably my gradle newbieness). I'm not sure what would be the best way of subclassing using reflection.

What do you think? I'd be willing to work on that, but I'd like to discuss the best approach first.

**Comment by bmuschko** [comment]
The reason for having to use a custom classloader in the plugin is classloader isolation. If you don't do that you have Gradle core libraries bleeding into the classpath of your plugin and might cause version conflicts with the libraries provided by Docker Java. This something that needs to be improved in Gradle core.

I never had the need to create a subclass via reflection. I guess you'd have to look into that. Docker Java changes the API all the time. In fact in an earlier version of the plugin (that used an earlier version of Docker Java) the use case you describe was already solved. However, new features in Docker Java required an upgrade which now makes it more complex to create a custom callback.

Feel free to work on a pull request for this. I'd be happy to review and merge.

**Comment by cdancy** [comment]
Closed due to #145
