### ISSUE TITLE
docker push token auth attempt

### ISSUE THREAD

**Issue by geoHeil** [bmuschko/gradle-docker-plugin#125]
HI, I try to perform a `gradle dockerPushImage` for https://github.com/geoHeil/lab04/blob/master/build.gradle

The image is built correctly. However trying to push this image results in an error:
```
Execution failed for task ':dockerPushImage'.
> Could not push image: Post https://registry-1.docker.io/v2/geoheil/lab04-current/blobs/uploads/: token auth attempt for registry: https://auth.docker.io/token?account=%22geoheil%22&scope=repository%3Ageoheil%2Flab04-current%3Apush%2Cpull&service=registry.docker.io request failed with status: 401 Unauthorized
```

Pushing the image using the native docker client works without a problem.

**Comment by bmuschko** [comment]
Sounds like you have to provide credentials for pushing. Did you assign them via [DockerPushImage.registryCredentials](http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.html)?

**Comment by cdancy** [comment]
@geoHeil were you able to solve this problem or is it still an issue?

**Comment by geoHeil** [comment]
Thank you for asking. Problem solved. Docker-machine is using HTTPS as default.
