### ISSUE TITLE
Support for build-arg when building an image

### ISSUE THREAD

**Issue by alenkacz** [bmuschko/gradle-docker-plugin#127]
Currently there is no way to specify a build arg, which is a new feature in docker 1.9

**Comment by bmuschko** [comment]
You are right. It doesn't exist at the moment. I am guessing you are referring to [ARG](https://docs.docker.com/engine/reference/builder/#arg)? Would you be interested in providing a pull request for this?

You can still get this working right now even though there's no method exposed at the moment via [GenericInstruction](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/test/groovy/com/bmuschko/gradle/docker/tasks/image/DockerfileTest.groovy#L15).

**Comment by bmuschko** [comment]
Can you please clarify which argument you mean here by directly pointing out the parameter in the Docker Remote API?

**Comment by cdancy** [comment]
@alenkacz were you interested in sending in a PR or looking for us to take on the work? Just wondering so that we can prioritize accordingly.

**Comment by alenkacz** [comment]
I'll do it :) hopefully this weekend

**Comment by bmuschko** [comment]
@alenkacz Before you work on a PR could you please explain the functionality you are planning to add?

**Comment by bmuschko** [comment]
@alenkacz It's unclear to me what exactly we are trying to implement here. I am going to close the issue. Please provide the relevant information if you are still interested in pursuing your issue.

**Comment by christianbauer** [comment]
This is a new feature of the remote API:

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/ 

**POST /build HTTP/1.1**

Query Parameters:

**buildargs** – JSON map of string pairs for build-time variables. Users pass these values at build-time. Docker uses the buildargs as the environment context for command(s) run via the Dockerfile’s RUN instruction or for variable expansion in other Dockerfile instructions

**Comment by cdancy** [comment]
@christianbauer so long as [docker-java](https://github.com/docker-java/docker-java) supports it, which we are based on, then it can be done here as well. If you're interested in sending in a PR we'd be happy to review.

**Comment by gringofe** [comment]
Hello,

how can I pass an argument to the dockerfile from my `task buildImage(type: DockerBuildImage)`? 
You say you support it, but your documentation doesn't specify how.

**Comment by orzeh** [comment]
@gringofe please take a look at our tests: https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy#L414
