### ISSUE TITLE
Creation of DockerLogsContainer task

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#132]
Use of this task, especially within a dev-ops environment, can be critical as one does not generally know when a given container, and its app therein, is "live". Exposing this task is an easy win for those needing to know when a container, and its app, have reached the "live" point via some log message.

In keeping with the spirit of the naming convention in place, it seems this name is as good as any. I can take on the work here.

**Comment by double16** [comment]
I'd like to see log functionality added to the DockerWaitContainer task as well. Seems like most of the code should be able to be shared between these two tasks,

**Comment by cdancy** [comment]
@double16 I assume you're referring to something like: poll the docker logs waiting until some message is seen? This is indeed possible, and would be very useful, but we've been shying away from such things in attempt to keep the plugin clean and simple. We've been advising folks to use this plugin as a base to further build on with ideas like this. We do the same here though I can see where folks might not be able to produce and host their own artifact. I've been mulling around the idea of putting together a 'gradle-docker-ext-plugin' for reasons such as this. If there is enough need/want for it I may make something available.

**Comment by double16** [comment]
I'd like the functionality of `docker logs --follow`. I'm working on running functional tests in a container and using the `DockerWaitContainer` to wait for them to be done. There is no output. Rather, if I could mimic `docker logs --follow`, it would show all of the logs and exit when the container exists.

**Comment by cdancy** [comment]
This plugin is based on [docker-java](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/command/LogContainerCmdImpl.java) and from what I can tell they so support the `follow` param. Looks like this would get us back an InputStream that we could pipe to stdout. I'll keep this in mind when putting together the first pass of this task.
