### ISSUE TITLE
Creation of DockerCopyFileToContainer task

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#133]
Much like the DockerCopyFileFromContainer task only in this case to copy files into a given container. 

I'll take on the work here.

**Comment by cdancy** [comment]
We'll have to wait until docker-java releases updated version of its library which includes the docker-copy-file-to-container functionality. Until then we are on hold ;(

**Comment by bmuschko** [comment]
I just did the upgrade.

**Comment by cdancy** [comment]
Closing this issue. docker-java-2.1.4 did not have expected changes and latest snapshots from docker-java break this plugin in general. We'll revisit at a later date.
