### ISSUE TITLE
AWS ECR Support

### ISSUE THREAD

**Issue by gpiper14** [bmuschko/gradle-docker-plugin#136]
AWS has just released their new docker registry service.  However since the [docker client doesn't support AWS style login](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html) support, you must make an API call to get a credentials that are only valid for 24 hours.  It might be nice to integrate this functionality into the plugin.

**Comment by cdancy** [comment]
@gpiper14 that may be out of the scope of this plugin. The functionality found here mainly exposes that found within https://github.com/docker-java/docker-java. It feels that it would make more sense for them to write this functionality into their library with us forwarding the credentials much like we do now. I'd open an issue with the aforementioned project and tag @marcuslinke. He is the maintainer and very responsive and easy to deal with.

Or ... you could write your own higher level plugin and pull this in as a dependency. Write the necessary API call there getting your 12 hour credentials, then invoke the relevant tasks of this plugin passing in said credentials as per usual, which we will then forward to docker-java for execution. We do similar things here to great success and what is recommended for use-cases like this.

Does that help or make sense?

**Comment by bmuschko** [comment]
I agree with @cdancy. I'd rather see this functionality in Docker Java. If they provide it then we can exposed that in the plugin as well. Alternatively, write your own "wrapper plugin" with the added functionality.

**Comment by gpiper14** [comment]
Ok thanks,  Ill look into it
