### ISSUE TITLE
Add a property to DockerRemoveImage task to select images based on a filter criteria.

### ISSUE THREAD

**Issue by abhijitsarkar** [bmuschko/gradle-docker-plugin#137]
I'm trying to clean up orphan images that the plugin appears to be leaving after a build. These're the images with `REPOSITORY` as `<none>`. There is a `DockerRemoveImage` task that depends on an image id and has no properties. There doesn't seem to be any tasks available that can select images from the local filesystem based on a filter. There's one for the registry though, `DockerListImages`.

Deleting a local image based on id is not very useful because most of the times the id is unknown at the time of the build. Please add a property to `DockerRemoveImage` to select images based on a filter criteria.

**Comment by bmuschko** [comment]
Not sure if Docker Java support this functionality. If it does then we can incorporate it. Would you mind having a look at their code or ask on their forum?

**Comment by cdancy** [comment]
@bmuschko docker-java does support this functionality: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#list-images

@abhijitsarkar any interest in sending in a PR to expose this functionality here?

**Comment by bmuschko** [comment]
@cdancy That's the command `DockerListImages` uses. I don't think it works for the use case.

**Comment by cdancy** [comment]
@bmuschko yea I only meant that it's there and possible to due so with the implication we'd have to call the DockerlistImages task here to do so. On further thought this may be better for a downstream plugin which uses this as its base.

**Comment by cdancy** [comment]
Closing issue as I don't think this is something we want to move forward and address. Enhancements like this, while admittedly would be helpful, belong in a downstream plugin based on this.
