### ISSUE TITLE
Create Vagrant box used for functional testing

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#148]
To be able to execute the whole suite of functional tests a running instance of Docker needs to up and running. It would be far more convenient to provide a Vagrant box which uses Linux as base image and already has Docker installed and pre-configured. The Docker installation should also pre-configure a private registry to test relevant use cases. Given this setup, the [Gradle Vagrant plugin](https://github.com/bmuschko/gradle-vagrant-plugin) could be used to start up/tear down the Vagrant box as part of the functional test fixture from the build. Instead of using Vagrant, [Otto](https://www.hashicorp.com/blog/otto.html) could be explored as an option here as well. An initial Vagrant box definition can be found in PR #70.

This setup would also allow other contributors to execute functional tests before submitting their PR.

**Comment by bmuschko** [comment]
Alright, we got a Vagrant box with Docker installed and properly configured to run all functional tests. No more excuses for contributors. :-)

**Comment by cdancy** [comment]
;)

**Comment by cdancy** [comment]
@bmuschko both tests within [AbstractDockerRemoteApiTaskFunctionalTest.groovy](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/AbstractDockerRemoteApiTaskFunctionalTest.groovy) fail for me as it is trying to assert that dockerClientConfig.username, password are my own but with vagrant are set to 'dockeruser', 'ilovedocker'. Not sure how we can programmatically, at least in this context, check if we are executing with vagrant or not. Thoughts?

**Comment by bmuschko** [comment]
@cdancy Are you sure these are tests that are failing for you? The tests don't even make a call to Docker. They just configure the Docker client but never call out.

**Comment by cdancy** [comment]
@bmuschko I'm sure. They don't fail under normal circumstances but for whatever reason under the vagrant umbrella they do.

**Comment by bmuschko** [comment]
@cdancy That's weird. I ran them against the Vagrant box. What's the stack trace?

**Comment by cdancy** [comment]
Expected no exception to be thrown, but got 'org.gradle.testkit.runner.UnexpectedBuildFailure'
	at spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at com.bmuschko.gradle.docker.AbstractDockerRemoteApiTaskFunctionalTest.Can create and execute custom remote API task with extension values(AbstractDockerRemoteApiTaskFunctionalTest.groovy:72)
Caused by: org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /tmp/junit4930952919469730276 with arguments [customDocker]

Output:
:customDocker FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/junit4930952919469730276/build.gradle' line: 44

* What went wrong:
Execution failed for task ':customDocker'.
> assert dockerClient.dockerClientConfig.username == 'cdancy'
         |            |                  |        |
         |            |                  |        false
         |            |                  dockeruser
         |            DockerClientConfig{uri=http://remote.docker.com:2375, version='RemoteApiVersion{major=1, minor=16}', username='dockeruser', password='ilovedocker', email='dockeruser@github.com', serverAddress='https://index.docker.io/v1/', dockerCfgPath='/home/cdancy/.dockercfg', sslConfig='LocalDirectorySSLConfig{dockerCertPath=/tmp/junit4930952919469730276/mydocker}'}
         com.github.dockerjava.core.DockerClientImpl@3c46dadf

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.912 secs

	at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:213)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:210)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:273)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:210)
	at com.bmuschko.gradle.docker.AbstractFunctionalTest.build(AbstractFunctionalTest.groovy:100)
	at com.bmuschko.gradle.docker.AbstractDockerRemoteApiTaskFunctionalTest.Can create and execute custom remote API task with extension values(AbstractDockerRemoteApiTaskFunctionalTest.groovy:69)

**Comment by bmuschko** [comment]
@cdancy My guess is that Docker Java pulls this from somewhere. Do you have your `username` configured in some local configuration file? If yes, we could change the test to also read that configuration file. If found there, then use it. Otherwise just go with the `System.properties['user.name']`. That's probably the logic in Docker Java also.

**Comment by cdancy** [comment]
@bmuschko yea it was configured in my "~/.docker.io.properties" file. This was a stock file I copied from the projects site some time ago and forgot it was even there. This is on my ubuntu linux machine. I noticed something was up when I ran from my osx laptop and everything was fine.

**Comment by bmuschko** [comment]
@cdancy Did you mean [docker-java.properties](https://github.com/docker-java/docker-java/#properties-docker-javaproperties)?

**Comment by bmuschko** [comment]
@cdancy Added a fix. It will likely work for you now.

**Comment by cdancy** [comment]
@bmuschko no I did in fact mean "~/.docker.io.properties". This was the old way and the new way, "~/docker-java.properties", I believe is supposed to be only for the 3.x release line though I may be mistaken on that. Perhaps they are supporting both in the interim.

**Comment by bmuschko** [comment]
@cdancy Oh lord. IMHO having these controls hard-wired into an API is wrong. This should be up to the consumer to define the source of such properties.

**Comment by bmuschko** [comment]
@cdancy Done
