### ISSUE TITLE
Execute functional tests using HTTPS instead of plain HTTP

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#149]
The task `functionalTest` currently executes all functional test against a Docker instance by communicating via HTTP. Given that HTTPS is the default Docker remote API protocol, functional tests need to properly work using that protocol. This would require a change in [TestConfiguration.groovy](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/testSetup/groovy/com/bmuschko/gradle/docker/TestConfiguration.groovy) and [TestPrecondition.groovy](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/testSetup/groovy/com/bmuschko/gradle/docker/TestPrecondition.groovy#L19).

**Comment by ericweinberg** [comment]
Does this mean that a TLS enabled docker-machine and the plugin won't work until this is completed?

**Comment by bmuschko** [comment]
@ericweinberg It does work. This issue is only related to the internal test infrastructure of the plugin.

**Comment by cdancy** [comment]
Functionality now exists within master to do so if required (though we don't by default). No need to keep this open IMO.
