### ISSUE TITLE
Statement catch(NotFoundException notFoundException) doesn't work

### ISSUE THREAD

**Issue by kiril-akshonau** [bmuschko/gradle-docker-plugin#151]
Java: Java HotSpot 1.7.0_67 64 bit
Gradle:  2.11
Windows: 7 64bit
gradle-docker-plugin: 2.6.5
Docker: 1.9.1

Hi, 

Based on [issue 131](https://github.com/bmuschko/gradle-docker-plugin/issues/131) I wanted to catch `NotFoundException` during removing old image. But I faced with strange behavior: exception wasn't catched at `NotFoundException` route. After investigation I'd found that docker-java is loaded by custom classLoader. I this fact is cause of this behavior.

So, is this expected behavior and what shall I do if I want to catch different exceptions from plugin?

I've prepared [test case](https://gist.github.com/kiril-akshonau/86c15bb83ce7638d9e0f)
Steps to reproduce:

1. Download mentioned test case
2. Run "gradle removeUnknown"

Expected result: Build successful. 'Same classLoader' in logs
Actual result: Build failed. `removeUnknown` task fails with message 'all.class != NotFoundException.class'

**Comment by neiljbrown** [comment]
Hi, FYI, we have a similar requirement to #131 - to treat a non-existent container as a non-fatal error on stop (or restart) and remove. I have added a comment to #131 to find out the status of this feature request, as it seems a fair number of people would benefit from it, avoiding them all needing to implement the suggested workaround of extending and overriding the custom task(s).

Thanks.

**Comment by cdancy** [comment]
@kiril-akshonau that is expected behavior. We use this plugin as a base and provide what we dub an 'extension' version to get around this sort of thing. I've provided the code-snippet below for what we do. Eventually we will introduce something like a ResponseHandler (which is actually implemented in a few spots) to allow the user to register an object to receive the output and do with it what they will.

```
class DockerRemoveContainerExt extends DockerRemoveContainer {

    @Override
    void runRemoteCommand(dockerClient) {
        try {
            super.runRemoteCommand(dockerClient)
        } catch (Exception e) {
            if (e.message =~ /.*no such id.*/){
                println e.message.trim()
                this.containerId = "-1"
            } else {
                throw e
            }
        }
    }
}
```

**Comment by cdancy** [comment]
@neiljbrown I understand downstream users not wanting to fail on such things and not wanting to roll their own plugin. Until we have a real solution rolled out this is unfortunately what one will have to do.

**Comment by cdancy** [comment]
Put together #153 to capture the start of this work. Feel free to provide comments.

**Comment by neiljbrown** [comment]
@cdancy - Hi, many thanks for following up on this, creating the issue to capture the work, and also including providing an additional code snippet. Very helpful, and much appreciated. Thanks.

**Comment by kiril-akshonau** [comment]
@cdancy I think new feature [#153](https://github.com/bmuschko/gradle-docker-plugin/pull/153) is great, but I'm not sure that it will resolve situation with different classLoaders. Solution with `e.message =~ /.*no such id.*/` has its own drawbacks(for example: it can be not `NotFoundException`, but something else with similar message). I was really confused when I wasn't able to catch exception inside `catch (NotFoundException notFoundException)` route.
Anyway, thanks for quick answer. Issue may be closed now

**Comment by cdancy** [comment]
@kiril-akshonau because we are using a custom class loader the best you can do is search for the generic exception and query its message and then move on from there. You really don't need to roll your own classloader, or have us not do that anymore, as the exception thrown should have all the information you need.
