### ISSUE TITLE
Registry authentication got broken

### ISSUE THREAD

**Issue by dainiusvaznys** [bmuschko/gradle-docker-plugin#152]
>             project.docker.registryCredentials {
                url = "https://$REGISTRY"
                username = project.property('docker.registry.username')
                password = project.property('docker.registry.password')
                email = project.property('docker.registry.email')
            }
This piece of code authenticates against our private registry successfully on the following versions of the artifacts:

>     'com.bmuschko:gradle-docker-plugin:2.6.1'
    'com.github.docker-java:docker-java:2.1.2'

However it fails with authentication error when using these:

>     'com.bmuschko:gradle-docker-plugin:2.6.5'
    'com.github.docker-java:docker-java:2.1.4'

The error reported is given below (in order to build the image its base image called fat-jar cannot be retrieved from the registry which only allows authenticated pulls:

> Could not build image: Get https://docker-registry.dev.4finance.net/v2/fat-jar/manifests/latest: no basic auth credentials

**Comment by bmuschko** [comment]
Another argument to get #148 done asap so we have a reproducible Docker runtime environment for testing.

**Comment by dainiusvaznys** [comment]
Please see pull request #159 which fixes the issue.
We need to give a little help to com.github.dockerjava.jaxrs.AbstrDockerCmdExec.registryConfigs so that it knows which API version is being used (which by default happens to be UNKNOWN_VERSION).

**Comment by bmuschko** [comment]
@dainiusvaznys OK, can you please revisit your PR to only provide the changes relevant to the problem?

**Comment by cdancy** [comment]
Closing issue as one can now supply the required apiVersion in the just released 2.6.8 version. @dainiusvaznys I'd like to circle back at some point and implement the ideas you put forward in #159 but a few things need to be done before moving ahead there. Still keeping that PR open but closing this issue as one can now pass in the API version.
