### ISSUE TITLE
Example of Functional Tests

### ISSUE THREAD

**Issue by edog305** [bmuschko/gradle-docker-plugin#161]
The example for functional tests only shows how to prepare a container for testing. It doesn't show an example of a test. The "functionalTestMyApp" function extends the Test task, which I thought was typically used for Java or Groovy unit tests. Can tests be written in these languages? If so, how would the tests connect?

Thanks!

**Comment by cdancy** [comment]
@edog305 is this a question related to the gradle-docker-plugin or are you asking a general gradle question? If the latter you may be better served using the gradle forums or stackoverflow.

**Comment by edog305** [comment]
@cdancy  I understand how to run Java/Groovy unit tests for traditional Gradle Java/Groovy projects. It's a question related to the grade-docker-plugin.

The created test method, in the examples, doesn't appear do anything. It simply depends on and is finalized by image/container creation Gradle tasks. My question is, what do actual Docker functional tests look like.

**Comment by bmuschko** [comment]
@edog305 It's not the responsibility of this plugin to provide examples on how to write a functional test. That's completely up to the developer using it. It also depends on _what_ you want to test in your functional test e.g. your Docker container runs a web app and you want to hit certain URLs. You'd have to make a choice what to use for this functionality. Some users might write a HTTP request themselves, some other users might choose to use Selenium, some other users something else. I can give you an idea of what could be done but it really depends on your use case. If you want _some_ idea then check ["Gradle in Action"](https://www.manning.com/books/gradle-in-action), chapter 7 for example. It explains how to set up functional testing with Geb.

**Comment by cdancy** [comment]
"If you want some idea then check "Gradle in Action", chapter 7 for example."

@bmuschko shameless self promotion ;)
