### ISSUE TITLE
Not able to expose multiple ports

### ISSUE THREAD

**Issue by allenxiang** [bmuschko/gradle-docker-plugin#164]
Docker supports exposing multiple ports but the plugin only takes one integer.
https://docs.docker.com/engine/reference/builder/#expose

**Comment by bmuschko** [comment]
[Dockerfile.exposePorts(Integer... ports)](http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html#exposePort(java.lang.Integer)) does allow you to expose multiple ports. Or do you mean something else?

**Comment by allenxiang** [comment]
I see. But the java application plugin only takes one port.

docker { javaApplication { baseImage = 'dockerfile/java:openjdk-7-jre' maintainer = 'Benjamin Muschko "benjamin.muschko@gmail.com"' port = 9090 tag = 'jettyapp:1.115' } }

**Comment by bmuschko** [comment]
You can simply reconfigure the existing task. It works the same way.

    dockerPushImage.exposePorts 8080, 9090

**Comment by allenxiang** [comment]
Great. Thanks a lot.
