### ISSUE TITLE
verbose output for DockerBuildImage 

### ISSUE THREAD

**Issue by llamahunter** [bmuschko/gradle-docker-plugin#167]
It would be very nice if DockerBuildImage output the same information as the 'docker' command line utility.  This probably should be the default behavior to better match the 'docker' command, but if not, it should at least be an attribute that can be set on the DockerBuildImage task.

It should *not* require setting gradle to log at its 'info' level, which causes a lot of uninteresting stuff to be printed.

**Comment by cdancy** [comment]
Closing as DockerBuildImage will output step reports by default with 2.6.7.
