### ISSUE TITLE
DockerBuildImage skipped even when inputs have changes since v2.6.6

### ISSUE THREAD

**Issue by vpartington** [bmuschko/gradle-docker-plugin#168]
First of all, thank you for writing this Docker plugin for Gradle. Nice stuff!

However, I did notice a problem with v2.6.6 of the plugin though: the `previouslyBuiltImageExists` logic in the `DockerBuildImage` task causes the task to be skipped even if the inputs (the Dockerfile or the context) change.

And when I do a `gradle clean buildDockerImage` the task fails with the following error message:
````
:buildDockerImage
Building image using context '/home/vinny/git/xebialabs/app/build/docker'.
Using tag 'dkr-reg:5000/app' for image.
Created image with ID 'd47a39991717'.
:buildDockerImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildDockerImage'.
> /home/vinny/git/xebialabs/app/build/docker/state/DockerBuildImage_Decorated (No such file or directory)
```

I've downgraded to v2.6.5 of the plugin to get reliable builds again.

**Comment by cdancy** [comment]
@vpartington can you post your build.gradle file?

**Comment by vpartington** [comment]
Sure. This is it:

```
buildscript {
  repositories {
    mavenCentral()
    jcenter()
  }

  dependencies {
    classpath 'com.bmuschko:gradle-docker-plugin:2.6.6'
  }
}

apply plugin: 'war'
apply plugin: 'jetty'
apply plugin: 'com.bmuschko.docker-remote-api'

import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

repositories {
  mavenCentral()
}

dependencies {
  compile group: 'commons-io', name: 'commons-io', version: '1.4'
  compile group: 'log4j', name: 'log4j', version: '1.2.15', ext: 'jar'
}

docker {
  url = 'https://192.168.99.100:2376'
  certPath = new File(System.properties['user.home'], '.docker/machine/machines/dkr-dev')
}

task copyWebapp(type: Copy) {
  from('src/main/webapp')
  into('build/docker/webapp')
}

task copyNginx(type: Copy) {
  from('src/main/nginx')
  into('build/docker/nginx')
}

task createDockerfile(type: Dockerfile) {
  dependsOn copyWebapp, copyNginx
  destFile = project.file('build/docker/Dockerfile')
  from 'nginx'
  maintainer 'Vincent Partington <vpartington@xebialabs.com>'
  copyFile('webapp', '/usr/share/nginx/html')
  copyFile('nginx', '/etc/nginx/conf.d')
}

task buildDockerImage(type: DockerBuildImage) {
  dependsOn createDockerfile
  inputDir = createDockerfile.destFile.parentFile
  tag = 'dkr-reg:5000/rest-o-rant-web'
}

task wrapper(type: Wrapper) {
  gradleVersion = '2.11'
}

httpPort = 8080
stopPort = 9451
stopKey = 'stop-rest-o-rant-web'
```

I solved my issue for now by changing `com.bmuschko:gradle-docker-plugin:2.6.6` into `com.bmuschko:gradle-docker-plugin:2.6.5`. But that's not the way forward of course. :-)

**Comment by wfhartford** [comment]
I'm seeing the same behaviour in a significantly different situation. I am using one gradle build file to generate a handful of docker images, based on some configuration files. Each of these configuration files causes a new DockerBuildImage task to be created.

The relevant parts of the build file boil down to:
```
def names = [...]
names.forEach {
  def dockerfileTask = task("create${name}Dockerfile") { ... }

  task("create${name}DockerImage", type: DockerBuildImage, dependsOn: dockerfileTask) {
    inputDir project.file("$buildDir/docker/$name")
    tag = name
  }
}
```

I have also reverted to version 2.6.5, which fixed the issue.

**Comment by cdancy** [comment]
@vpartington @wfhartford can you post your "buildDir/.state/DockerBuildImage" output? Are you trying to build the same image again the same name/tag/etc..? If you run with '-i' do you see messages that say something like "Image ##### found via call to inspectImage"?

**Comment by wfhartford** [comment]
The intent of my build is to create several similar docker images, part of the docker build involves editing a handful of files with configuration details specific to certain deployment environments. Each of the images produced has a different name.

The build output with the -i option is available in this Gist: https://gist.github.com/wfhartford/fdf90c5bf20a32839cf2 For brevity, I redacted one very large command which edits the files. That command would be different in each of the Dockerfiles.

For each of the DockerBuildImage tasks after the first, `Image 5223f164846f found via call to inspectImage` is printed.

I assume you mean the `build/docker/state/DockerBuildImage_Decorated` file. It contents are:

```
#Thu Mar 03 15:22:22 PST 2016
imageId=5223f164846f
```

**Comment by cdancy** [comment]
@wfhartford so the implementation here is broken. If you want to use 2.6.6 the easiest way to move forward would be to do a 'doLast { project.delete("$buildDir/docker/state/DockerBuildImage_Decorated") }'. It's a hack no doubt about it but will get you moving forward. I'll look into getting a proper fix ready for 2.6.7.

@bmuschko This was a "fix" on the original implementation but it itself has issues. The only real way to solve this would be to get a list of all images and compare the tag to see if it already exists. Thoughts?

**Comment by cdancy** [comment]
The more I think about it the more I just want to rip this code out. How can we truly know when an image is the same as the one that's being requested to be built? I can't honestly think of a way I can't programmatically, at least through docker, create the same named image but with different contents. I don't like the solution in place now, which I unfortunately implemented, nor the one that was proposed previously the more I think on it. In the Gradle world I'm not sure if there is a way we can tell that the inputs, in this case the potentially previously named image id/tag, are/are-not exactly what we currently want to create.

**Comment by vpartington** [comment]
When I execute `gradle clean`, followed by `gradle buildDockerImage` (see my `build.gradle` file above), I get this:

```
$ cat build/docker/state/DockerBuildImage_Decorated 
#Fri Mar 04 10:19:35 CET 2016
imageId=bc78278e22e3
```

Repeated runs of `gradle buildDockerImage` cause the `buildDockerImage` task to be SKIPPED. The contents of that file don't change. This happens regardless of whether any of the inputs have changed.

And yes, I am trying to rebuild the same image many times, without a tag, but with different inputs, until I am happy with the results. I am developing it. Only when I am happy, will I tag it, push it to my local registry and promote it to other environments.

As for ripping this code out; I agree that that might be the best solution. Docker already takes care of figuring out whether the image is really different and reusing an existing image if it's already there. The only gain would be that you save the time you'd otherwise wait for Docker to build the image. And while I think Gradle should be able to tell you whether the inputs have changed, I don't think you'd be able to capture all changes. For example, what about the whole `apt-get update && apt-get install -y ...` thing?

I'd just keep the plugin simple and leave the rest to Docker. :-)

**Comment by bmuschko** [comment]
@cdancy I'd say rip it out completely. It's really hard to properly cover all the cases. If users want such functionality, they can implement their own strategy.

**Comment by cdancy** [comment]
@vpartington version 2.6.7 is now in maven central. Would you mind giving that a go and see how things fare?

**Comment by wfhartford** [comment]
Version 2.6.7 worked for me. Thanks.

**Comment by vpartington** [comment]
v2.6.7 works for me. Thanks!
