### ISSUE TITLE
How to reliably get an `imageId`

### ISSUE THREAD

**Issue by adrianbk** [bmuschko/gradle-docker-plugin#169]
I have the following tasks: 

```
task buildImage(type: DockerBuildImage, group: 'docker') {
    dependsOn tasks.resources
    inputDir = file("docker/")
    tag = "my-database"
}

task createContainer(type: DockerCreateContainer, group: 'docker') {
    dependsOn tasks.buildImage
    containerName = 'my-db-container'
    targetImageId { (tasks.buildImage as DockerBuildImage).getImageId() }
}
```
This works fine when executed for the first time but on subsequent builds the `buildImage` task is skipped and  ` (tasks.buildImage as DockerBuildImage).getImageId() ` returns null. What is the recommended way to reliably get the image id? 

This can be kind-of worked around by deleting `..state/DockerBuildImage_Decorated` but that feels like a very bad idea.

**Comment by cdancy** [comment]
@adrianbk what you're referring to is an attempt we made at marking the DockerBuildImage task as "UP-TO-DATE" should that file exist. Are you trying to build the same image with the same tag? What does your ".state/DockerBuildImage" file say from run to run?

**Comment by adrianbk** [comment]
It contains the following: 
```
#Thu Mar 03 08:01:56 AEDT 2016
imageId=98e5537d421a

```

**Comment by adrianbk** [comment]
The main reason I down-graded to `2.6.5` was that I need to build 2 images from within the same gradle project and it appears that the file: `.../build/docker/state/DockerBuildImage_Decorated` is used by all `DockerBuildImage`.

**Comment by cdancy** [comment]
@adrianbk we're going to rip this functionality out of the plugin with the next release. This is causing too many headaches and does not work as expected. Issue is currently being discussed here #168.

**Comment by adrianbk** [comment]
@cdancy Thanks for the quick response on this :+1:

**Comment by cdancy** [comment]
@adrianbk version 2.6.7 is now in maven central. Can you give that a go and see how things fare?

**Comment by cdancy** [comment]
@adrianbk have you had a chance to give this a go? Others have reported success in this area with the latest release and wanted to confirm the same was true for you as well.

**Comment by adrianbk** [comment]
@cdancy yes I've upgraded and it is working as expected. I have not yet verified that it works when building more than one image from the same gradle project but I don't see a reason for it not to work.

**Comment by cdancy** [comment]
@adrianbk Ok I'm closing the issue. If it pops again feel free to open it back up.
