### ISSUE TITLE
No value has been specified for property 'imageId' while creating docker container

### ISSUE THREAD

**Issue by dmakshay** [bmuschko/gradle-docker-plugin#171]
Hi bmuschko,

I followed the example to [build/create/start/stop container](https://github.com/bmuschko/gradle-docker-plugin#executing-functional-tests-against-a-running-container). 
Here is my gradle file snippet.

```
import com.bmuschko.gradle.docker.tasks.container.*
import com.bmuschko.gradle.docker.tasks.image.*

task copyJar(type: Copy) {
	dependsOn   'jar'
	from        'build/libs/rest-app-0.0.1-SNAPSHOT.jar'
	into        'build/docker'

	from        'src/main/resources/Dockerfile'
	into        'build/docker'
}

task buildImage(type: DockerBuildImage) {
	dependsOn 'copyJar'
	inputDir = file('build/docker');
	url = 'unix:///var/run/docker.sock'
	tag = 'rest-app/nci:0.1'
}

task createContainer(type: DockerCreateContainer) {
	dependsOn buildImage
    containerName = 'my-rest-app'
	targetImageId { buildImage.getImageId() }
    portBindings = ['8080:8080']
}

task startContainer(type: DockerStartContainer) {
    dependsOn createContainer
    targetContainerId { createContainer.getContainerId()}
}

build.dependsOn copyJar
build.dependsOn buildImage
build.dependsOn createContainer
```

Only buildImage task seems to work. When creating a container it gives 

> No value has been specified for property 'imageId'

Here is the stacktrace.

> .
> .
> :rest-app:copyJar
> :rest-app:buildImage
> Building image using context '/home/akshay/.jenkins/workspace/NCI/rest-app/build/docker'.
> Using tag 'rest-app/nci:0.1' for image.
> Created image with ID '8cf8fc8d2af9'.
> :rest-app:check
> :rest-app:createContainer
> ID !!!!!!!8cf8fc8d2af9
> :rest-app:createContainer FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem was found with the configuration of task ':rest-app:createContainer'.
> > No value has been specified for property 'imageId'.
> 
> * Try:
> Run with --info or --debug option to get more log output.
> 
> * Exception is:
> org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':rest-app:createContainer'.
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:55)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
>         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
>         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
>         at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
>         at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
>         at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
>         at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
>         at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
>         at org.gradle.internal.Factories$1.create(Factories.java:22)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
>         at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
>         at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
>         at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
>         at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
>         at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
>         at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
>         at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
>         at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
>         at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
>         at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
>         at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
>         at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
>         at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
>         at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
>         at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
>         at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
>         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
>         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
>         at org.gradle.launcher.Main.doAction(Main.java:33)
>         at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
>         at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
>         at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
>         at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
> Caused by: org.gradle.api.InvalidUserDataException: No value has been specified for property 'imageId'.
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
>         ... 53 more
> 
> 
> BUILD FAILED

@bmuschko Can you please let me know how to solve this? Not able to get going after creating an image.

Thanks,
Akshay

**Comment by cdancy** [comment]
@dmakshay by any chance does the image already exist? We made a change recently that looks to be confusing others as well. If the image already exists, meaning same name/tag/etc, then the task is essentially "UP-TO-DATE" and we skip building.

**Comment by dmakshay** [comment]
@cdancy Thanks for you reply. No the image doesn't exist. Everytime I manually delete the created image in docker too before running gradle. The image is created when i run the gradle build. As you can see in the beginning of the stacktrace, the image is getting created with the ID(Created image with ID '8cf8fc8d2af9').

**Comment by cdancy** [comment]
@dmakshay this functionality does not work as expected and is being removed with the next release. Please downgrade to 2.6.5 to get around the current problem.

**Comment by dmakshay** [comment]
@cdancy was about to post the same. Meaning I downgraded the version a while ago and everything seems to work with no flaws. Thanks much though.

**Comment by avarabyeu** [comment]
Still have this issue on 3.0.1. Do you plan to fix it?

**Comment by cdancy** [comment]
@avarabyeu can you post a reproducible snippet of what you're doing along with a stacktrace? This `bug` reported here was a side-effect of a change we made and then backed out many versions ago.

**Comment by avarabyeu** [comment]
@cdancy just found a solution - it was my fault. thanks for prompt answer!

**Comment by jengstrom** [comment]
@avarabyeu I am interested in what you found for the solution?  :)

**Comment by dpeger** [comment]
@cdancy I had this very same problem after updating from 4.1.0 to 4.9.0.

I "solved" this by adding `outputs.upToDateWhen { false }` to the `DockerBuildImage` tasks to make them skip the default UP-TO-DATE tests:

```
task createImage(type: DockerBuildImage) {
  outputs.upToDateWhen { false } // without this line createContainer complains about missing imageId
  ...
}

task createContainer(type: DockerCreateContainer) {
  dependsOn createImage

  targetImageId createImage.getImageId()
  ...
}
```

**Comment by orzeh** [comment]
@dpeger this is a known bug (see #818). There is a PR on the way (#819). Once merged we'll kick out a release.

**Comment by dpeger** [comment]
@orzeh thanks for this information.

What checks are performed to determine if a `DockerBuildImage` task is up-to-date? IMHO checking for an image with the same name and tags is not a good idea. If you don't add additional tags an image will always be up-to-date only using the `latest` tag...

Additionally, if there are no real changed Docker itself will use the build cache to skip known layers, making the build really fast. By implementing something in the gradle-plugin you cancel this built-in mechanism.

**Comment by orzeh** [comment]
@dpeger We use Gradle capabilities to detect if either Dockerfile or directory with build context changed (see #672). We also save image id in a file and in subsequent builds we check if image with that id still exists. For details please refer to #807.

>Additionally, if there are no real changed Docker itself will use the build cache to skip known layers, making the build really fast. By implementing something in the gradle-plugin you cancel this built-in mechanism.

I think using this plugin you can still leverage that.
