### ISSUE TITLE
Create an ISSUES.md file for folks to follow when reporting potential problems.

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#174]
I think we need to have a clear format for folks to follow when reporting an issue. Too many times we end up saying the same thing: what version of gradle are you using, can you post your build.gradle file, can you post a stacktrace, have you tried running the workload outside of the plugin, does '-i' provide any more information about the problem, and questions like these. I see other projects doing this and think it may be a good idea here. 

Often times when I'm responding to issues its either on the weekend, at night, or when I find a few minutes between things at work. Having all the information up front would be a big help.

@bmuschko thoughts? Assuming yes any particular format you want to follow? I see a few that I like that I think we can adopt here. Maybe we just make things more clear in the README?

[adobe issues](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
[bundler](https://github.com/bundler/bundler/blob/master/ISSUES.md)

**Comment by bmuschko** [comment]
Sounds good to me though in my experience people won't read it nevertheless. However, you'll be able to point them to it when you want them to provide more information. A file named `ISSUES.md` is probably good enough.

**Comment by cdancy** [comment]
Yea I've submitted patches to projects to fix an issue I'm interested in only to find out there is a standard/format to follow. I've probably done the same here. So you're right in that people, even with the best intentions, will avoid such things. IDK. I'm all for less is better. Maybe a section in the README will suffice? I think we should have something if only to point folks to a format they should follow or at least give the bare minimum when reporting bugs/issues. Let me think on this a bit more.

**Comment by bmuschko** [comment]
`README.md` is already pretty long. I'd create a new file and then probably link to it from `README.md`.
