### ISSUE TITLE
Not able to build image

### ISSUE THREAD

**Issue by dmakshay** [bmuschko/gradle-docker-plugin#177]
Hi @cdancy, @bmuschko,

I have been using gradle with docker plugin and it seems to be working like a charm. But now I've run into a weird issue. Here goes... I have 5 modules for which I am using docker to build and create different containers and use remote API to deploy onto different machines. In those 5, all 4 modules are successfully build i.e. create image, create container and start the container etc. But while creating the image for the 5th module i get an error, it says 

> error during call back, request to {}->http://192.168.140.206:4000: Broken pipe

Here is the stacktrace.

> ...
> Using tag 'module5/project:0.0.1.snapshot' for image.
> [pool-1-thread-1] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.140.206:4000: Broken pipe
> [pool-1-thread-1] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
> org.apache.http.client.ClientProtocolException
> 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
> 	at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:441)
> 	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
> 	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
> 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
> 	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
> 	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
> 	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
> 	at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
> 	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:45)
> 	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
> 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:107)
> 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
> 	... 18 more
> Caused by: java.net.SocketException: Broken pipe
> .........
> :module5:buildImage FAILED

This seems like a very weird problem since all the other 4 modules are deployed and working fine. Here is my build.gradle snippet.

```
 dependencies {
        classpath("com.bmuschko:gradle-docker-plugin:2.6.5")
    }
apply plugin: 'com.bmuschko.docker-remote-api'

import com.bmuschko.gradle.docker.tasks.container.*
import com.bmuschko.gradle.docker.tasks.image.*

docker {
    url = 'http://192.168.140.206:4000'
}

task copyJar(type: Copy) {
    dependsOn   'jar'
    from        'build/libs/module5-0.0.1-SNAPSHOT.jar'
    into        'build/docker'

    from        'src/main/resources/Dockerfile'
    into        'build/docker'
}

task buildImage(type: DockerBuildImage) {
    dependsOn 'copyJar'
    inputDir = file('build/docker');
    // For local system deployment
	//url = 'unix:///var/run/docker.sock'
    tag = 'module5/project:0.0.1.snapshot'
}

task createContainer(type: DockerCreateContainer) {
    dependsOn buildImage
	containerName = 'module5-boot'
    targetImageId { buildImage.getImageId() }
}

task startContainer(type: DockerStartContainer) {
	dependsOn createContainer
	targetContainerId { createContainer.getContainerId()}
}

build.dependsOn copyJar
build.dependsOn buildImage
build.dependsOn createContainer
build.dependsOn startContainer
```

Can you please let me know how I can resolve this issue? or I have to change in my build script?

I have tried in my local system too by specifying 

> url = 'unix:///var/run/docker.sock'

and commenting 

> url = 'http://192.168.140.206:4000'

in my build script. But still same issue persists. 
Thank you so much in advance.

Thanks,
Akshay

**Comment by cdancy** [comment]
@dmakshay that does seem odd. Let's get a couple of things out of the way first:

1.) Is this 5th container/node running against a docker daemon that is different than the others?
2.) Can you manually reproduce this issue (i.e. command line) without using the plugin?
3.) Have you checked the logs for the docker daemon to see if they provide any clues?

**Comment by dmakshay** [comment]
@cdancy Thanks for your reply. Here are my comments.
1) All the docker daemons run on the same port 4000 but on different machines i.e. different ip's.
2) Yes can manually create/run the image without using the plugin.
3) Yes I've. Its again odd. Here is what it says in the docker logs. 

> Mar  7 22:25:35 localhost docker: time="2016-03-07T22:25:35.571449373+05:30" level=error msg="Handler for POST /build returned error: invalid reference format: repository name must be lowercase"

Here is my dockerfile.

```
FROM java:8
VOLUME /data
ADD module5-0.0.1-SNAPSHOT.jar /data/module5.jar
EXPOSE 9000
ENTRYPOINT ["java","-jar","/data/module5.jar"]
```

My repository name is in lower case.

**Comment by cdancy** [comment]
Docker can be funny with what it allows as a "proper" name. How about this: try putting in for the tag something as simple as "hello/world" and see what happens. 

Is this particular docker daemon a different version by any chance?

**Comment by dmakshay** [comment]
@cdancy I tried and still the same error. No matter what I specify after 

> FROM <repository>

 in the Dockerfile, it gives the same error. Don't understand why. But when I try manually i.e. by `docker pull dockercloud/hello-world` it works.
No both are on same version 1.10.2. As of now i'm running on my local linux machine itself.

**Comment by cdancy** [comment]
@dmakshay this plugin is built on top of [docker-java](https://github.com/docker-java/docker-java) and I'm not sure if they support the latest and greatest version of docker. Looking over the docs it appears no but they are working towards it. Have you tried running against a docker daemon that is not bleeding edge?

**Comment by dmakshay** [comment]
@cdancy Running against a docker daemon? i'm sorry didn't get you. 
And @cdancy the configurations are the same for all the 5 modules in my Dockerfile as well as in the build.gradle script. Rest all seem to build and run except for the fifth one. Can you please tell me if anything wrong in my Dockerfile and the gradle config from my top post? Can't seem to understand this weirdness since it works for other modules.

**Comment by cdancy** [comment]
docker-daemon being just docker. I was basically saying have you tried running against docker that is not bleeding edge, maybe 1.9 or 1.8?

These other modules: are they also doing more/less the same workload? Are they building images as well? They must be doing something different, or named differently, which is allowing them to succeed.

**Comment by dmakshay** [comment]
@cdancy no I've not tried with older versions.

Yeah it's the same. Except for the module name and other build dependencies, the docker plugin script is the same. I've verified with comparison tool too. I'll try this: add the plugin to the latest svn copy and build.

**Comment by dmakshay** [comment]
@cdancy I got it working finally. I guess there is a character limit for specifying the tag name. I changed this 

> module5/project:0.0.1.snapshot

to 

> mod5/project:0.0.1 

and it worked fine. Thanks for your inputs and help too. Appreciate it.

**Comment by cdancy** [comment]
@dmakshay np and glad you got things working.
