### ISSUE TITLE
Having trouble mounting a volume 

### ISSUE THREAD

**Issue by ericweinberg** [bmuschko/gradle-docker-plugin#178]
Hopefully this is another easy one, but I'm having trouble getting DockerCreateContainer.volumes working. 

When I run,  `run docker run -v /Users/me/logs:/opt/app/logs  d23432dc985a   `
Everything mounts fine.  copy and pasting that -v option into my code doesn't though. 
```

task buildContainer(type: DockerCreateContainer) {
  //snip
  //also tried this volumes = ["/Users/me/logs","/opt/app/logs"]
  volumes = ["/Users/me/logs:/opt/app/logs"]
  //snip
}
```

**Comment by ericweinberg** [comment]
Looks like 'binds' is the right answer, not volumes.  

```
...
binds = ["/host/foo":"/container/bar"] 
...
```

**Comment by cdancy** [comment]
@ericweinberg +1

**Comment by eladchen** [comment]
It is a shame it isn't documented anywhere.

Helping with writing the docs requires vast knowledge - 🐔& 🥚

**Comment by bmuschko** [comment]
@eladchen I assume you are talking about the Javadocs for this plugin? Or are you referring to the documentation of Docker Java?

**Comment by eladchen** [comment]
Hey quick response :)

This plugin! (Which is awesome BTW)

**Comment by bmuschko** [comment]
> This plugin! (Which is awesome BTW)

Yeah, we'll definitely want to improve on the Javadocs (see https://github.com/bmuschko/gradle-docker-plugin/issues/737) though in practice they won't be very different from the Javadocs for Docker Java.

**Comment by JamesXNelson** [comment]
anyone coming here trying to find `binds =` in place of `volumes =`, the workaround location has been changed:

`cnt.hostConfig.binds.put "host/dir" : "/container/dir"`
