### ISSUE TITLE
gradle-docker-plugin is not able to push into docker hub

### ISSUE THREAD

**Issue by Vad1mo** [bmuschko/gradle-docker-plugin#18]
I am  not able to push to docker hub. The build says that it is successful, but it pushes only to the local docker repository not to docker.hub.
 
```
[[Avs-macfly:zinvoice-service vadim$ gradle -S pushImage
:createDockerfile UP-TO-DATE
:buildImage
Building image from folder '/Users/v/Development/zinvoice/zinvoice-service/build'.
Using tag 'zinvoice/zinvoice-service' for image.
Created image with ID 'e7aea64dcefe'.
:pushImage
Pushing image with name 'zinvoice/zinvoice-service'.

BUILD SUCCESSFUL

vs-macfly:zinvoice-service v$ docker images 
REPOSITORY                   TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
zinvoice/zinvoice-service    latest              70b032887dd5        5 seconds ago       160.2 MB
```

I was looking at https://github.com/docker-java/docker-java and there is a distinction between serverAddress and url.

```
url The Docker URL, e.g. https://localhost:2376.
serverAddress Your registry's address. (https://index.docker.io/v1/)
```

@bmuschko  Does the plugin considers serverAddress?

**Comment by bmuschko** [comment]
You can find an example in the [integration tests](https://github.com/bmuschko/gradle-docker-plugin/blob/v0.8/src/integTest/groovy/com/bmuschko/gradle/docker/DockerWorkflowIntegrationTest.groovy#L157).

**Comment by bmuschko** [comment]
It also appears to have been a bug in Docker Java ([see conversation](https://github.com/docker-java/docker-java/issues/119)). My fix works around it.
