### ISSUE TITLE
ExposedPort in createContainer does not work

### ISSUE THREAD

**Issue by coco1979ka** [bmuschko/gradle-docker-plugin#19]
Execution failed for task ':createMyAppContainer'.
> java.lang.NoSuchMethodException: com.github.dockerjava.api.model.ExposedPort.<init>(java.lang.String, java.lang.Integer)

Maybe, because this constructor is deprecated?

**Comment by bmuschko** [comment]
Thanks for reporting. Instead of `java.lang.Integer` the type should probably be `Integer.TYPE` instead which represents the primitive type `int`. I am going to fix this soon.

**Comment by coco1979ka** [comment]
For the moment it is okay to expose the port with the CreateDockerFile Task. Could you anyway provide an example on how to do the port mapping in CreateContainer? I tried to set the portSpecs property with portSpecs = ["8080:8080"] but it will not be mapped. Thanks
