### ISSUE TITLE
Automate plugin publishing on JCenter

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#193]
As last step in the publishing process a user has to log into JCenter and click a link that makes published versions of the plugin available to the public. Hopefully, this can be automated via some REST call. Investigate if it can be automated and make it happen.

Benefit: Any plugin committer can fully release the plugin end to end.

**Comment by cdancy** [comment]
@bmuschko this is more a config issue than anything else. I know exactly the cause and will knock it out later today.

**Comment by cdancy** [comment]
Bumped version of gradle-bintray-plugin with commit 35bfc87 so that we can use the `publish = true` option to solve this very issue. Next release should auto-publish the version itself.
