### ISSUE TITLE
Trying to make "docker exec"

### ISSUE THREAD

**Issue by lukaslentner** [bmuschko/gradle-docker-plugin#195]
Hi,
I tried to build a Task for the "docker exec" command, but I always get a ClassNotFoundException for the Callback class.
Do you know the reason?

My Code:

import java.lang.reflect.Method
import java.io.OutputStream

class DockerExecute extends DockerExistingContainer {

  String shell
  
  @Input
  String getShell() {
    shell
  }

  @Override
  void runRemoteCommand(dockerClient) {
    logger.quiet "Waiting ..."
    sleep(3000)
    logger.quiet "Executing '${getShell()}' on container with ID '${getContainerId()}'."
    def containerCommand = dockerClient.execCreateCmd(getContainerId()).withAttachStdout(true).withAttachStderr(true).withCmd(getShell())
    def response = containerCommand.exec().getId()
    Class myClass = threadContextClassLoader.loadClass('com.github.dockerjava.core.command.ExecStartResultCallback')
        Method method = myClass.getMethod('getInstance', OutputStream.class, OutputStream.class)
        def result = method.invoke(null, System.out, System.err)
    dockerClient.execStartCmd(response).exec(result).awaitCompletion();  
  }

}

**Comment by cdancy** [comment]
@lukaslentner you would have to post the full stacktrace to get a better understanding of what's going on.

Were you thinking about putting together a PR? We'd be more than happy to review if you did.

**Comment by cdancy** [comment]
@lukaslentner closing. If you want to talk and/or provide a PR for this we'd be more than happy to review.

**Comment by lukaslentner** [comment]
Hi,

now I'm executing

    Class myClass = threadContextClassLoader.loadClass('com.github.dockerjava.core.command.ExecStartResultCallback')
    Constructor constructor = myClass.getConstructor(OutputStream.class, OutputStream.class)
    def result = constructor.newInstance(System.out, System.err)
    def containerCommand = dockerClient.execCreateCmd(getContainerId()).withAttachStdout(true).withAttachStderr(true).withCmd(getShell())
    dockerClient.execStartCmd(getContainerId()).exec(result).awaitCompletion(); 

which works without errors, but also without effect. The command is not executed ...
Do you know how these last 2 lines have to look like?
After this works I am more than happy to make a PR...

**Comment by lukaslentner** [comment]
Sorry to have bothered you. I got it. I will send a PR when finished ...

**Comment by cdancy** [comment]
@lukaslentner sounds good. If you are putting together a PR feel free to ping me for review and/or questions.
