### ISSUE TITLE
Plugin adding dependencies to build classpath

### ISSUE THREAD

**Issue by Zavijava** [bmuschko/gradle-docker-plugin#196]
The DockerRemoteAPIPlugin is explicitly adding dependencies(docker-java, slf4j-simpl, and cglib) to the build classpath rather than the buildscript classpath.

**Comment by cdancy** [comment]
@Zavijava is this something you are noticing with the newest release or are you noting it has been there all along?

**Comment by Zavijava** [comment]
I am using v2.6.7 in an environment with liberal repo access for build tools (e.g. buildscript plugins), but very restricted access for Gradle's "proper" build contexts. I have a simple project to build an image. I expected the DockerRemotePluginAPI's transitive dependencies to be on the buildscript classpath, not on a project configuration.

**Comment by bmuschko** [comment]
It's expected and (in fact) wanted behavior. We don't want to convolute the buildscript classpath and cause potential version conflicts. This pattern is also used by many of the Gradle core plugins.

**Comment by Zavijava** [comment]
Can you explain this further?  Are you saying project configurations are used as a namespace to avoid conflict between plugins that depend on different versions of underlying libraries?

**Comment by bmuschko** [comment]
The plugin creates a [custom configuration named dockerJava](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy#L43) just for this purpose. This configuration doesn't bleed into any other configuration of your project is completely isolated. We do use it for two different reasons:

1) To avoid version conflict for dependencies from other plugins.
2) To avoid version conflicts for dependencies coming from the Gradle core runtime.

This handling is very much an implementation detail of the plugin. What's the reason for your question?

**Comment by cdancy** [comment]
@bmuschko we've had this same conversation previously and while I understand you're reasoning I can understand the confusion folks would have when trying to use this plugin and expecting its dependencies to come from the classpath. 

Perhaps we can let folks create their own configuration and truly pass it in vs overriding it? Something which lazily creates the configuration at runtime if and only if it is needed. Folks can already pass in a FileCollection on the extension we would just need a way to lazily init the default.

**Comment by Zavijava** [comment]
We use Artifactory. We establish virtual repositories for use in our projects that preserve the distinction Gradle makes between the buildscript and build proper. Buildscript entries would allow use of 'our-plugins-repo', while build entries would be constrained to use 'our-build-repo'. Our buildscript policy is liberal (e.g. including JCenter()) to provide devs flexibility. Our build repo policy, however, is carefully managed. I understand the dockerJava configuration is intended to provide isolation, but this does bleed into repository management. I have to open our build repo up to the transitive dependencies of build plugins. Isn't the whole purpose behind the Gradle buildscript configuration to isolate the build tooling environment from the build environment?

**Comment by cdancy** [comment]
@Zavijava we face a similar issue here (Artifactory shop ourselves) and while I agree I can see the argument from the other side as well.

@bmuschko another proposal: going back to our previous conversations and requiring the user to define a project scoped repo ... what if we make that optional? Today one has to do the following:

```
repositories {
    mavenCentral()
}

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:2.6.8'
    }
}
apply plugin: 'com.bmuschko.docker-remote-api'
```
We could amend the code to first check if the project has already set any repositories (like we have above) and if not then use those repos found within buildscript.repositories. This would allow for both use-cases and would be a sort-of failover mechanism allowing for the below. Thoughts?

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:2.6.8'
    }
}
apply plugin: 'com.bmuschko.docker-remote-api'
```

**Comment by cdancy** [comment]
@Zavijava also if you're looking for tools to work with Artifactory you might want to check out [gradle-artifactory-rest-plugin](https://github.com/cdancy/gradle-artifactory-rest-plugin) or the [artifactory-rest](https://github.com/cdancy/artifactory-rest) library. I develop both as we are heavy users of Artifactory here. The artifactory client that jfrog develops is cumbersome and not very straightforward IMO.

**Comment by cdancy** [comment]
@Zavijava closing issue. If you want to discuss further feel free to re-open.
