### ISSUE TITLE
Create an image from existing Dockerfile providing parameters from gradle such as Version

### ISSUE THREAD

**Issue by Vad1mo** [bmuschko/gradle-docker-plugin#197]
Hello I have few quite big Dockerfiles. For This reason I don't like to create the Dockerfile with gradle instead I would like to use the gradle-docker-plugin to build and push the image. 

however the Dockerfile a have contains variables from the gradle for example the project version. 

`ADD api-${VERSION}.war webapps/ `

Is there a way to either extend an existing Dockerfile eg. read Dockerfile add a line and write back or to pass some variables to during the build image process.

**Comment by cdancy** [comment]
@Vad1mo this would not be the responsibility of the plugin but more on you, as the script writer, to search and replace any token within the file prior to using `DockerBuildImage`.

**Comment by Vad1mo** [comment]
ok, thanks. I was thinking maybe there is a build in feature in gradle-docker-plugin for that making providing an elegant solution.

**Comment by cdancy** [comment]
@Vad1mo we often get requests like this but end up turning them down. The idea here is that this particular plugin is meant to serve as a base of sorts for you to build a more customized, or possible combine with some other plugin, version for your own use case. We do exactly that here where we build upon this plugin to provide something which is very specific to our use case and context. I recognize that not everyone, or shop, can do such things but we want to keep this code as terse and directly correlated to dockers API that we can.
