### ISSUE TITLE
Custom Classloader and AbstractDockerRemoteApiTask

### ISSUE THREAD

**Issue by marbon87** [bmuschko/gradle-docker-plugin#198]
I have the following class to run a docker exec command several times, until it runs succesful or a maximum number of retries is reached:
```
class DatabaseStartWait extends AbstractDockerRemoteApiTask {

    @Input
    @Optional
    def timeBetweenRetries

    @Input
    Integer maxRetries

    @Input
    String databaseName

    String containerId

    Integer exitCode

    DatabaseStartWait() {
        maxRetries = 20
        timeBetweenRetries = 4000
    }

    void targetContainerId(Closure containerId) {
        conventionMapping.containerId = containerId
    }

    @Override
    void runRemoteCommand(dockerClient) {
        String id = getContainerId()

        for (int i = 0; i < maxRetries; i++) {
            logger.debug "$i. try: Create Docker command to connect to database: $databaseName"
            def execCreateCmdResponse = dockerClient
                    .execCreateCmd(id)
                    .withAttachStdout(true)
                    .withCmd('su', '-c', "db2 'CONNECT TO $databaseName'", '-', 'db2inst1')
                    .exec()

            logger.quiet "$i. try: Remote command execution-ID: $execCreateCmdResponse.id"

            ClassLoader dockerClientClassLoader = dockerClient.getClass().getClassLoader()
            Class callbackClass = dockerClientClassLoader.loadClass("com.github.dockerjava.core.command.ExecStartResultCallback")
            def callback = callbackClass.getDeclaredConstructor(OutputStream.class, OutputStream.class).newInstance(System.out, System.err);

            dockerClient.execStartCmd(execCreateCmdResponse.getId())
                    .withDetach(false)
                    .exec(callback)
                    .awaitCompletion()

            def execResponse = dockerClient
                    .inspectExecCmd(execCreateCmdResponse.getId())
                    .exec()

            exitCode = execResponse.getExitCode()
            logger.debug "$i. try: ExitCode: $exitCode"

            if (exitCode == 0) {
                logger.debug "Database is started after $i. try"
                break;
            }
            sleep(timeBetweenRetries)
        }
        if (exitCode > 0) {
            throw new GradleException("Could not connect to database in the defined time")
        }

        logger.quiet "exitCode on database-connect: $exitCode"
    }

    @Input
    String getContainerId() {
        containerId
    }
}
```

I need to included the following, to get a callback-instance, that is loaded from the correct classloader
```
            ClassLoader dockerClientClassLoader = dockerClient.getClass().getClassLoader()
            Class callbackClass = dockerClientClassLoader.loadClass("com.github.dockerjava.core.command.ExecStartResultCallback")
            def callback = callbackClass.getDeclaredConstructor(OutputStream.class, OutputStream.class).newInstance(System.out, System.err);
```

When i use new ExecStartResultCallback(...) to create the instance, i get the following error:
```
 No signature of method: com.github.dockerjava.core.command.ExecStartCmdImpl.exec() is applicable for argument types: (com.github.dockerjava.core.command.ExecStartResultCallback) values: [com.github.dockerjava.core.command.ExecStartResultCallback@3b464733]
  Possible solutions: exec(com.github.dockerjava.api.async.ResultCallback), exec(com.github.dockerjava.api.async.ResultCallback), grep(), every(), use([Ljava.lang.Object;), every(groovy.lang.Closure)
```

Why did you implement a custom classloader and how is the classloader created?

**Comment by cdancy** [comment]
@marbon87 try taking a look at [DockerThreadContextClassLoader](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/utils/DockerThreadContextClassLoader.groovy) to understand how we do things.

You could always put together a PR to get more eyes on your issue and share the code back upstream.

**Comment by everflux** [comment]
The DockerThreadContextClassLoader lacks documentation about the intent of the class. The name is misleading as well, as is it not a ClassLoader.

When creating the URLClassLoader you set the parent classloader to the extension classloader, imho.
I think this can result in loading a different versions of a class which are then incompatible.

**Comment by cdancy** [comment]
@everflux while I'll grant you the name is misleading the code itself is not terribly complex and so should be easy enough to figure out what's going on should one need to do so. The code itself I'll also grant you can be done better but as it stands now works, and has worked, for quite some time with no hiccups surrounding this particular issue to speak of. That is unless folks are doing something ad-hoc and so may encounter issues like these.

The approach taken by @marbon87 is a good one and one I currently employ for a PR I'm putting together for a future version of this plugin.

But more importantly if you guys have any ideas, or think things can be done better, please send in a PR and lets review it together. Any and all contributions are most welcome.

**Comment by everflux** [comment]
@marbon87 can you create a test case showing the issue in isolation? We can then work on a PR together if you like.

**Comment by marbon87** [comment]
@cdancy @everflux please see https://github.com/bmuschko/gradle-docker-plugin/pull/199
All functional tests are still working

**Comment by cdancy** [comment]
@marbon87 this is actually what we tried to get away from. While all functional tests may pass you risk anything that is on the gradle buildscript classpath leaking into our classloader and clobbering those classes we may depend on.

**Comment by cdancy** [comment]
Closing this issue as I think the correct way to go about things would be to send in a PR and code this task the proper way.

**Comment by everflux** [comment]
Please provide some information how you would like the PR be designed so it can fit your expectations.

**Comment by cdancy** [comment]
@everflux @marbon87 feel free to look over any of the tasks we've already written on how to get started and design a task for `DockerExecContainer`. That feels like what is needed here. We don't accept anything that is specific to one's use case but something that can be used by the greater community at large. It would be up to downstream users to then use this plugin as a base to write something more specific.

It should be noted that no PR will be accepted w/out passing functional tests.
