### ISSUE TITLE
Please support amazon ecr container registry

### ISSUE THREAD

**Issue by PatrickHuetter** [bmuschko/gradle-docker-plugin#200]
Please support amazons ecr container registry. It's a cheap alternative for other private docker repositories. 

https://aws.amazon.com/de/ecr/

**Comment by cdancy** [comment]
@PatrickHuetter is there any reason to suspect we do not? Amazon, like say Artifactory, implements the docker registry API. The onus is on them to support docker not the other way around.

**Comment by cdancy** [comment]
Closing as I don't believe this is an issue with the plugin. @PatrickHuetter please feel free to re-open should you think this not be the case.
