### ISSUE TITLE
Fallback to buildscript repos if no dependency repos have been defined.

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#204]
Currently the dependency repos are being used to resolve our internal dependencies. These however may not be defined for any number of reasons. If such is the case fallback to using the buildscript repos to resolve our internal dependencies.

**Comment by cdancy** [comment]
Added in PR #218

**Comment by bmuschko** [comment]
FYI: The Gradle team is currently working on improving the way plugins and their respective repositories can be declared. This might become a non-issue in future versions of Gradle.

**Comment by cdancy** [comment]
@bmuschko are there any docs on how this is going to be implemented? I'd love to have a look if it's readily accessible.

**Comment by bmuschko** [comment]
Check out the [feature set](https://github.com/gradle/gradle/tree/master/design-docs/features/stable-plugins-dsl) described in the Gradle repo.
