### ISSUE TITLE
Cannot push to private registry

### ISSUE THREAD

**Issue by deathtrix** [bmuschko/gradle-docker-plugin#209]
I am using boot2docker on Windows. The project is Grails 3.
My config from build.gradle looks like:
`
docker {
    url = 'https://192.168.99.100:2376'
    certPath = new File(System.properties['user.home'], '.docker/machine/machines/default')
    apiVersion = 2

```
registryCredentials {
    url = 'http://10.6.20.153:5000'
    username = ''
    password = ''
    email = 'alexandru.ganga@ymens.com'
}

javaApplication {
    baseImage = 'java:openjdk-7-jre'
    maintainer = 'Alex Ganga "alexandru.ganga@ymens.com"'
    port = 9090
    tag = "ymens/idp:${project.version}"
}
```

}
`
The problem is that when I run dockerPushImage it tries to push it to the default "index.docker.io".
Can you please check? I saw that docker-java project uses a serverAddress. My guess is that somewhere the registryCredentials.url doesn't get passed to AuthConfig.serverAddress.

PS: The username and password attributes it gets ok. And they are named the same in docker-java. That's how I arrived at the above conclusion :)

**Comment by cdancy** [comment]
@deathtrix do you have a stacktrace of any kind? Do you have a snippet from your build.gradle file we can see? Have you tried doing the same workload outside of the plugin to test if it works?

**Comment by deathtrix** [comment]
@cdancy I tries the same manually and it works. stracktrace coming in a moment

**Comment by deathtrix** [comment]
c:\work\cloudsocket-idp>gradle dockerPushImage --stacktrace
:assetCompile
Processing File 1 of 2 - bootstrap.min.css
Processing File 2 of 2 - errors.css
Finished Precompiling Assets
:buildProperties UP-TO-DATE
:compileJava UP-TO-DATE
:compileGroovy
:processResources UP-TO-DATE
:classes
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:compileIntegrationTestJava UP-TO-DATE
:compileIntegrationTestGroovy
:compileWebappGroovyPages UP-TO-DATE
:compileGroovyPages
:jar
:findMainClass
:startScripts
:distTar
:distZip
:war
:bootRepackage
:assemble
:dockerCopyDistResources
:dockerDistTar
:dockerBuildImage
Building image using context 'C:\work\cloudsocket-idp\build\docker'.
Using tag 'ymens/idp:0.12' for image.
Step 1 : FROM java:openjdk-7-jre

 ---> 63db1d3e3c2a

Step 2 : MAINTAINER Alex Ganga "alexandru.ganga@ymens.com"

 ---> Using cache

 ---> fd71bbb69366

Step 3 : ADD cloudsocket-idp-0.12.jar /

 ---> 04a226061e04

Removing intermediate container 949395dbfb82

Step 4 : CMD java -jar cloudsocket-idp-0.12.jar

 ---> Running in 934d4026cc46

 ---> 3b843043882c

Removing intermediate container 934d4026cc46

Step 5 : EXPOSE 9090

 ---> Running in 7bc2a9a69480

 ---> a163b2898158

Removing intermediate container 7bc2a9a69480

Successfully built a163b2898158

Created image with ID 'a163b2898158'.
:dockerPushImage
Pushing image with name 'ymens/idp'.
:dockerPushImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerPushImage'.
> Could not push image: Post https://registry-1.docker.io/v2/ymens/idp/blobs/upl
oads/: token auth attempt for registry: https://auth.docker.io/token?account=adm
in&scope=repository%3Aymens%2Fidp%3Apush%2Cpull&service=registry.docker.io reque
st failed with status: 401 Unauthorized

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dockerP
ushImage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
tTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
ltTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
ExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecu
ter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
ecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLa
uncher.java:154)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:151)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGra
dleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
eLauncher.java:99)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
eLauncher.java:93)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:93)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:82)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
troller.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe
cuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
ctionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin
uousBuildActionExecuter.java:77)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(Contin
uousBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.exe
cute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.exe
cute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
a:170)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
trap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
ava:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: com.github.dockerjava.api.DockerClientException: Could not push image
: Post https://registry-1.docker.io/v2/ymens/idp/blobs/uploads/: token auth atte
mpt for registry: https://auth.docker.io/token?account=admin&scope=repository%3A
ymens%2Fidp%3Apush%2Cpull&service=registry.docker.io request failed with status:
 401 Unauthorized
        at com.github.dockerjava.core.command.PushImageResultCallback.awaitSucce
ss(PushImageResultCallback.java:49)
        at com.github.dockerjava.core.command.PushImageResultCallback$awaitSucce
ss.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.image.DockerPushImage.runRemoteComma
nd(DockerPushImage.groovy:61)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_c
losure1.doCall(AbstractDockerRemoteApiTask.groovy:57)
        at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withC
lasspath(DockerThreadContextClassLoader.groovy:54)
        at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspa
th.call(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDoc
kerClassPath(AbstractDockerRemoteApiTask.groovy:62)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDoc
kerClassPath.callCurrent(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDoc
kerClassPath.callCurrent(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(Ab
stractDockerRemoteApiTask.groovy:56)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:61)
        ... 57 more


BUILD FAILED

Total time: 1 mins 15.99 secs

**Comment by deathtrix** [comment]
this is with some random values in username and password...otherwise it says authentication error without showing the url of the registry

**Comment by deathtrix** [comment]
and build.gradle:

buildscript {
    ext {
        grailsVersion = project.grailsVersion
    }
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath 'com.bertramlabs.plugins:asset-pipeline-gradle:2.5.0'
        classpath "com.bmuschko:gradle-docker-plugin:2.6.8"
        classpath "org.hidetake:gradle-ssh-plugin:2.0.0"
    }
}

plugins {
    id "io.spring.dependency-management" version "0.5.2.RELEASE"
}

group "ydp"

apply plugin: "spring-boot"
apply plugin: "war"
apply plugin: "asset-pipeline"
apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "org.grails.grails-web"
apply plugin: "org.grails.grails-gsp"
apply plugin: "com.bmuschko.docker-java-application"
apply plugin: "org.hidetake.ssh"

targetCompatibility = "1.7"
sourceCompatibility = "1.7"

docker {
    url = 'https://192.168.99.100:2376'
    certPath = new File(System.properties['user.home'], '.docker/machine/machines/default')
    apiVersion = 2

    registryCredentials {
        url = 'http://10.6.20.153:5000'
        username = 'admin'
        password = 'aaa'
        email = 'alexandru.ganga@ymens.com'
    }

    javaApplication {
        baseImage = 'java:openjdk-7-jre' // oracle-java8
        maintainer = 'Alex Ganga "alexandru.ganga@ymens.com"'
        port = 9090
        tag = "ymens/idp"
    }
}

ext {
    grailsVersion = project.grailsVersion
    gradleWrapperVersion = project.gradleWrapperVersion
}

assets {
    minifyJs = true
    minifyCss = true
}

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
}

dependencyManagement {
    imports {
        mavenBom "org.grails:grails-bom:$grailsVersion"
    }
    applyMavenExclusions false
}

dependencies {
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.springframework.boot:spring-boot-starter-jetty"
    compile "org.springframework.boot:spring-boot-starter-security"
    compile "org.grails:grails-dependencies"
    compile "org.grails:grails-web-boot"

    compile "org.grails:grails-plugin-rest"
    compile "org.grails:grails-datastore-rest-client:4.0.7.RELEASE"

    runtime "org.grails.plugins:asset-pipeline"
    runtime "org.grails.plugins:scaffolding"

    testCompile "org.grails:grails-plugin-testing"
    testCompile "org.grails.plugins:geb"

    // Note: It is recommended to update to a more robust driver (Chrome, Firefox etc.)
    testRuntime 'org.seleniumhq.selenium:selenium-htmlunit-driver:2.44.0'

    console "org.grails:grails-console"

    compile "org.grails.plugins:mongodb"
    compile "org.springframework.security.oauth:spring-security-oauth2:2.0.7.RELEASE"
    compile "org.springframework.security:spring-security-jwt"
    compile "com.google.guava:guava:18.0"
}

task wrapper(type: Wrapper) {
    gradleVersion = gradleWrapperVersion
}

**Comment by eshepelyuk** [comment]
To push to private registry you basically need to to following

1. Create docker images, e.g. `my-user/my-image`

        $ docker build ....
2. Tag the image with a tag name containing URL of repository
        
        $ docker tag my-user/my-image my.registry.com:5000/my-user/my-image
3. Push new tag to private registry, URL of registry is taken from tag

        $ docker push my.registry.com:5000/my-user/my-image

To implement this in current plugin version we did following trick

- Adjust `build.gradle` by adding `dockerTag` task and changing properties of provided `dockerPushImage` task.
```
    task dockerTag(type: com.bmuschko.gradle.docker.tasks.image.DockerTagImage) {
        imageId = 'my-user/my-image:latest'
        tag = 'latest'
        repository = 'my.registry.com:5000/my-user/my-image'
    }

    dockerPushImage.imageName = 'my.registry.com:5000/my-user/my-image'
    dockerPushImage.dependsOn dockerTag
```

- Then push from command line
       
         $ gradle dockerPushImage

**Comment by deathtrix** [comment]
@eshepelyuk Thank you. I'll try this. In the meantime I made an Exec task that runs docker push.

**Comment by litosantana** [comment]
@eshepelyuk I see your example in the above comment, but how does it create the image to begin with? I already have a `Dockerfile`, which means I should use the `DockerBuildImage` task, but I'm running into errors there with my private registry. Should I be using some other approach?

**Comment by cdancy** [comment]
Closing issue. Feel free to re-open if further discussion is needed.
