### ISSUE TITLE
Add support for fig / docker compose.

### ISSUE THREAD

**Issue by dougborg** [bmuschko/gradle-docker-plugin#21]
We use fig (http://www.fig.sh) in a few of our projects and I was considering creating a simple plugin to run fig commands. It also looks like a top-level docker command (but separate binary?) named 'compose' will be replacing fig at some point (https://github.com/docker/docker/issues/9694).

Do you think it makes sense to add support for fig / compose in this gradle plugin, or does that blow up the scope of this plugin too much?

**Comment by bmuschko** [comment]
As long as Docker Java adds this functionality to their DockerClient, it's easy to be added. You could even create your own task if you wanted. Please see [this integration test](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/integTest/groovy/com/bmuschko/gradle/docker/AbstractDockerRemoteApiTaskIntegrationTest.groovy#L4) for more info.

**Comment by bmuschko** [comment]
@dougborg Can you please open an issue for Docker Java?

**Comment by dougborg** [comment]
Sorry for the late response, but I did some further research on this and It looks like docker-compose is not actually integrated into the client and it doesn't look like there are plans to do so in the future either. I think that was the original goal, but that has since changed. 

See: http://blog.docker.com/2015/01/dockercon-eu-introducing-docker-compose/

I think it makes sense to create another plugin for compose/fig that creates some tasks types which wraps around the Exec task and perhaps another one that builds in some conventions. Is that still something you may be interested having as part of this set of docker plugins maintained in this repo or would you rather these plugins be maintained separately?

**Comment by bmuschko** [comment]
It kind of depends on what impact it has on the current plugin(s). For example I would not want to pull in other external dependencies and clutter the existing functionality. So if it's not going to be integrated with the client, I'd rather not have it in here. I might just be a separate plugin.

**Comment by dougborg** [comment]
Sounds good. I will pursue creating a separate plugin.

**Comment by Krijger** [comment]
For the combination of Gradle and Docker Compose, check out https://github.com/stackwork/stackwork or stackwork.org

**Comment by chrisgahlert** [comment]
Another plugin I recently created achieves the same goals by doing something similar to what docker-compose does:
https://github.com/chrisgahlert/gradle-dcompose-plugin

**Comment by aschrijver** [comment]
And there is https://github.com/avast/docker-compose-gradle-plugin as well

**Comment by Krijger** [comment]
@chrisgahlert @aschrijver @augi For the purpose of integration testing with Docker (using Compose). Did you consider Stackwork? It's pretty complete and easy to use (though the documentation is still lacking, sorry). If there's stuff you're missing in there I would very much like to hear your feedback and use case. Of course (my agenda), it would be nice if we could join efforts for a single good tool.
