### ISSUE TITLE
Multi-tag

### ISSUE THREAD

**Issue by whgibbo** [bmuschko/gradle-docker-plugin#210]
Hi,
Might be silly question, what is the best way to tag the image with a version and release ?

Thanks

**Comment by cdancy** [comment]
@whgibbo we have [DockerTagImage](http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/DockerTagImage.html) task which should do just what you want.
