### ISSUE TITLE
gradle-docker-plugin is not supported 'HostConfig' settings

### ISSUE THREAD

**Issue by Nekitos** [bmuschko/gradle-docker-plugin#213]
As I see in docker-java (library which used by gradle-docker-plugin) it provides HostConfig settings for docker, but gradle-docker-plugin isn't.
 Are you wants to provide this feature in future?

**Comment by cdancy** [comment]
@Nekitos what options are you specifically looking for?

**Comment by Nekitos** [comment]
@cdancy for example 'RestartPolicy'. When server with docker rebooted (due to electricity problems) it not starts previously run containers. If container starts with **--restart=always** parameter or with `"RestartPolicy": { "Name": "always", "MaximumRetryCount": 0 }` (through remote api), then it restarts all containers that was been started before reboot

**Comment by cdancy** [comment]
@Nekitos gotcha. RestartPolicy is indeed an exposed option on docker-java's CreateContainerCommand and so adding the necessary functionality to DockerCreateContainer task should not be bad.

There are many options we don't expose (due to the sheer number) and so we add them as needed and/or requested by the community. Were you interested in sending in a PR for this functionality or looking for us to do it?

**Comment by Nekitos** [comment]
@cdancy Think I can implement this feature

**Comment by cdancy** [comment]
@Nekitos that would be great! Take a look over things and see what you can make happen. I'm here if you have questions and/or need a point in the right direction.

**Comment by Nekitos** [comment]
@cdancy ok, thanks. 
Btw, I think that this issue can be labeled as **enhancement** :-)

**Comment by Nekitos** [comment]
For now I implemented RestartPolicy for HostConfig class in docker-java parameter. 
As I see, some of parameters that stored in the HostConfig class (docker-java api) was been implemented in DockerCreateContainer class. I think DockerCreateContainer class should contains object of similar class like HostConfig. This should be task for refactoring. 
So, I'll create  PR with one change (add createPolicy parameter), but need to create ticket (with label 'task') for refactoring.  Purpose of refactoring task is combine parameters that as this made in the docker-java api.

**Comment by cdancy** [comment]
@Nekitos send in a PR and I can comment and look things over. We don't really want to refactor the entire DockerCreateContainer task at this point. I would follow the model currently in place and just add the feature you need.

**Comment by cdancy** [comment]
@Nekitos fixed up the code and merged as part of #224 . Thanks for the PR!
