### ISSUE TITLE
registryCredentials url property is ignored

### ISSUE THREAD

**Issue by gdrooid** [bmuschko/gradle-docker-plugin#226]
Hi, I'm trying to use the plugin to build and push docker images to a private registry. If I set the url using the property in `registryCredentials` it is ignored and the plugin tries to upload the image to docker.io... ~~I removed the `=`, using url as a method, and then the plugin uses it! But it sends `HTTP` requests to the port `80`, unless I specify the port `443`, but then it still sends plain `HTTP` requests.~~

I'm using version `3.0.0` of the plugin.

**Comment by cdancy** [comment]
@gdrooid can you please follow the guidelines on [reporting issues here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/ISSUES.md)?

**Comment by gdrooid** [comment]
Hey @cdancy , I discovered the issue when preparing a minimal gradle build file. :sweat_smile: I didn't know I had to tag the image with the repo url, which feels really weird to me. So the problem was with me not understanding docker, rather than your plugin.

Thank you very much for your attention.

**Comment by cdancy** [comment]
@gdrooid glad you got things worked out.
