### ISSUE TITLE
Getting a container by name

### ISSUE THREAD

**Issue by itissid** [bmuschko/gradle-docker-plugin#227]
Lets say I am doing development and want to interactively run test commands on an environment on a container. I don't want to recreate the container from the image because each test command as that takes a long time to execute the first time(subsequent runs are of course faster).

Example, A test command like gradle may take many mins to download and cache jars. 

How might I use the API to make the gradle tasks to achieve this?

**Comment by cdancy** [comment]
@itissid  All container tasks accept the parameter [`targetContainerId`](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExistingContainer.groovy#L27) which is a closure that must resolve to a String. Is this what you're referring to?

    task execCommand(type: com.bmuschko.gradle.docker.tasks.container.DockerExecContainer) {
        targetContainerId { "my-container-name" }
        cmd = ["echo", "Hello World"]
    }

**Comment by itissid** [comment]
Actually assigning the value of `getContainerName` to `targetContainerId` helps create constant name which can be used in later tasks after the `DockerCreateContainer` task exits. When I saw the word `id` I assumed it was the SHA value. 
Maybe useful to clarify that in the readme?

**Comment by cdancy** [comment]
@itissid either the name or the SHA value should work much like it does on the command line. Are you saying the SHA value did not work when you tried?

**Comment by itissid** [comment]
No the SHA value is different every time. The name I can hardcode and reuse for running commands against running containers with that name and clean it up later.

**Comment by unlimitedsola** [comment]
LOL, I had the same thought (the `id` means the SHA value) with you until I saw this!
