### ISSUE TITLE
gradle-docker-plugin does not seem to be working with Docker for Mac Beta

### ISSUE THREAD

**Issue by bgulla** [bmuschko/gradle-docker-plugin#231]
When building my java project (Apache Myriad), it seems like the new departure from boot2docker and integration of the new Docker for Mac breaks the plugin. See below:

```Using tag 'mesos/myriad' for image.
java.lang.UnsatisfiedLinkError: Could not find library in classpath, tried: [libjunixsocket-macosx-1.8-x86_64.dylib, libjunixsocket-macosx-1.5-x86_64.dylib]```

.....

```[pool-9-thread-1] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
java.lang.NoClassDefFoundError: Could not initialize class org.newsclub.net.unix.NativeUnixSocket```


I hope this isn't just a mistake in our project but I didn't have another project to test it on. Thanks

**Comment by cdancy** [comment]
@bgulla can you post a snippet of your code and the full stracktrace?

Are you attending dockercon by any chance and just got the heads up they opened beta testing for all? I'm there and walking around if you want to come say hello and trouble shoot your issue.

**Comment by ericweinberg** [comment]
I don't pretend to understand this, but I think the root issue is with docker-java (which i believe this plugin depends on).  You can read about all the gory details here:  https://github.com/docker-java/docker-java/issues/537

**Comment by cdancy** [comment]
That is indeed the issue. I'll leave this ISSUE open if only to track the progress of what they are doing. With Windows/Mac beta now open to everyone I assume we will see many more folks coming in with similar problems.

**Comment by set321go** [comment]
I just ran up against the same problem.

This didn't solve it for me but maybe you have some luck. 
https://forums.docker.com/t/accessing-docker-daemon-on-port-2375/13707

If you can work out how to configure the docker for mac to open up the http port that should be a workaround.

`curl -v http://localhost:2376/info` gives me a connection refused
`curl --unix-socket /var/run/docker.sock http:/containers/json` gives me an empty array

**Comment by cdancy** [comment]
Closing this thread as a temporary solution, though still failing due to docker-java issue, is somewhat possible and is being discussed in more detail here: https://github.com/bmuschko/gradle-docker-plugin/issues/235
