### ISSUE TITLE
Cannot wait for application in container to start before running, say, integration tests

### ISSUE THREAD

**Issue by aflowers001** [bmuschko/gradle-docker-plugin#232]
when building a spring boot application and then looking to run integration tests against the application deployed in a docker container i faced an issue whereby I had to wait for the application to be started in the container before commencing the tests.

I did not want to pollute the tests with and docker specific waits so I looked for a way to monitor the container for a specific event, but could not find anything that suited.

I got around this by updating a local deployment of the plugin with a new task that monitored the docker container stdout log looking for a specific string that indicated that the application had started up.

Is there a better alternative at all? If not I will tidy up my task and submit it for review. 

The basic premise was that it read the log, checked for the string it was after, then went to sleep and repeated until it found the required string indicating the container was ready for use.

**Comment by cdancy** [comment]
@aflowers001 that's the way I've solved similar problems and have instructed others to do so as well. The standard we've set with this plugin is to provide a 1-to-1 (docker-command to gradle-task) and so we don't typically take any custom tasks so to speak. However, this is a common enough issue/question and I might entertain an enhancement to the `DockerLogsContainer` task that polls for some log output and finishes when it finds it. Feel free to put together a PR and ask any questions.

**Comment by orzeh** [comment]
@aflowers001 also check the official [Docker Compose doc](https://docs.docker.com/compose/startup-order/) - there are links to some useful utilities that you can use to solve your problem.

@cdancy I agree that this is a common problem, so we should propose some "advised" solution with regards to docker-gradle-plugin.

**Comment by cdancy** [comment]
We now have the ability to poll logs within a container and/or receive callbacks for each log output triggered. On top of this docker now supports the ability to do so natively. Think we can close this now IMO. Feel free to re-open for further discussion.
