### ISSUE TITLE
Upload a  list of files

### ISSUE THREAD

**Issue by itissid** [bmuschko/gradle-docker-plugin#233]
I don't think there is an abstraction on top of `DockerCopyFilesToContainer` to upload a select set of files (would  be nice if additonally we could provide functionality to filter em). Is this just trivial to write using gradle magic or would be more involved? If the former I could try proposing a design and then a patch..
 
I don't think  that docker API supports this natively, but I suppose might be able to do it nicely with gradle somehow by extending that class.

**Comment by cdancy** [comment]
@itissid we have the [DockerCopyFileToContainer](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCopyFileToContainer.groovy) task to "upload" files to a given container. Docker natively takes a single File (be it regular file or directory) and will upload its contents to a given location. If you want to do this for X number of files, all from different paths, then you'd have to call the task multiple times.

**Comment by cdancy** [comment]
@itissid closing this issue. If you're still having problems feel free to re-open.
