### ISSUE TITLE
Question: can't read generated tag

### ISSUE THREAD

**Issue by childnode** [bmuschko/gradle-docker-plugin#236]
```
docker {
    javaApplication {
        maintainer = project.group
        baseImage = 'java:8'
        port = 80
    }
}

task showDockerTag << {
    println "Docker tag that will be used: " + docker.javaApplication.tag
}
```
returns null for the docker tag.

which is reasonable as I see this code:
https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerJavaApplication.groovy#L22

but I can't find where / when tag default https://github.com/bmuschko/gradle-docker-plugin#extension-properties-1 `<project.group>/<applicationName>:<project.version>` comes in

**Comment by orzeh** [comment]
See [ determineImageTag() in DockerJavaApplicationPlugin](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPlugin.groovy#L108).

`DockerJavaApplication` instance is only configured by your closure from build script and it is not updated when default values are calculated later on.

**Comment by cdancy** [comment]
Closing as it appears things may be solved. @childnode feel free to re-open if you have any further questions.

**Comment by childnode** [comment]
yes, so the answer is: it is determined automatically if not set explicit but you cant read / dump the default value since the method is private and not executed until the image is build ;)
Thx anyway .. ~Marcel
