### ISSUE TITLE
Java system properties are not taken into account

### ISSUE THREAD

**Issue by eshepelyuk** [bmuschko/gradle-docker-plugin#237]
According to `FAQ` section `Executing the plugin’s test suite with custom configuration` there are few system properties that can configure Docker Engine location

* dockerServerUrl
* dockerCertPath

But seems they are not working, i.e. if I use `-DdockerServerUrl=..` when invoking `Gradle` the value is ignored.

**Comment by cdancy** [comment]
Are you running the plugin tests or trying to pass these properties on the command line when invoking say a task?

**Comment by eshepelyuk** [comment]
The latter

Are you running the plugin tests or trying to pass these properties on the
command line when invoking say a task?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bmuschko/gradle-docker-plugin/issues/237#issuecomment-230589488>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABOF9eGzzPg5TX6K42jj44k4sENLngkDks5qSrskgaJpZM4JFe7x>
.

**Comment by cdancy** [comment]
Unfortunately that won't work in this context and used primarily for running our tests. Can you not use the extension to set the docker URL?

**Comment by eshepelyuk** [comment]
I can, but 
- overriding `Docker Engine` location via system properties is quite powerful feature, used in maven plugin and allowing to use the same `Gradle` build script to work with several `Docker Engines`
- current plugin FAQ is confusing :)

**Comment by cdancy** [comment]
Fair enough. We could add an item to our backlog to optionally pass in these properties via command line to give greater flexibility.

**Comment by eshepelyuk** [comment]
I'd like to pick it up and submit a PR in a while :)
Just need some guidance about where to place the code.

What about `AbstractDockerRemoteApiTask.groovy` ??

**Comment by orzeh** [comment]
@eshepelyuk @cdancy but should these properties override values defined in build script or be used as a default value (if defined)?

**Comment by eshepelyuk** [comment]
@orzeh I believe they should, it's sort of common behaviour in other plugins. I.e. the order is following

1. use system properties
1. if no system properties defined, use build script values
1. if there's no system properties / build script values defined - use defaults

**Comment by cdancy** [comment]
@eshepelyuk I would start [here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy#L67). When we create the `DockerClientConfig` at runtime we can check there. That seems to make the most sense IMO.

As far as precedence: I think gradle properties (e.g. -Pfoo=bar) should have more weight than java properties, and java properties have more weight than environment vars. I would also follow the naming convention set by [docker-java](https://github.com/docker-java/docker-java) as we use that under the hood and would be more familiar to folks.

Thoughts?

**Comment by eshepelyuk** [comment]
Yes, sounds reasonable. I just forgot about `Gradle` properties , i.e. defined with `-P`.

**Comment by cdancy** [comment]
@orzeh thoughts one way or the other on the proposed path to move forward?

**Comment by orzeh** [comment]
@cdancy I agree with hierarchy you proposed.

However I would put that logic into [DockerThreadContextClassLoader](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/utils/DockerThreadContextClassLoader.groovy#L42)

**Comment by cdancy** [comment]
@orzeh meaning to [flesh this out a](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/utils/DockerThreadContextClassLoader.groovy#L67) bit more to account for these?

**Comment by orzeh** [comment]
@cdancy yes, I`ve pointed line 42 because we should support other settings as well (cert path and api version).

**Comment by cdancy** [comment]
@orzeh sounds good. @eshepelyuk please take the recommendation put forth by @orzeh. You can do the necessary property config inside method `getDockerHostUrl`. You noted your desire to only do this for the `url` but what you be interested in providing the same for `certPath` and `apiVersion`? If so I would follow the same design set by the aforementioned method and create something similar for these two; maybe name them `getDockerApiVersion()` and `getDockerCertPath()`.

**Comment by eshepelyuk** [comment]
Thank you for giving a hint. I'll follow recomendations above.
