### ISSUE TITLE
Starting container with HostConfig was deprecated since v1.10 and removed in v1.12

### ISSUE THREAD

**Issue by kboom** [bmuschko/gradle-docker-plugin#238]
Hi All,

Just started to use the plugin. I have docker 1.11 installed on my PC.
When running DockerStartContainer task I'm getting the error like in the issue title.
Is this a known bug? How to resolve it? I don't think nobody has noticed it yet as it's major.

Here's my config if it can be of any help:
```
    docker {
        url = 'http://192.168.99.100:2376'
        certPath = file(System.getProperty('docker.cert.path') ?: "${System.getProperty('user.home')}/.docker/machine/machines/default")
    }

    task createDockerfile(type: Dockerfile) {
        destFile = project.file("$buildDir/docker/Dockerfile")
        from 'java:8u91'
        exposePort 8080
        defaultCommand 'java', '-jar', 'app.jar'
    }

    task buildImage(type: DockerBuildImage, group: 'docker') {
        dependsOn 'bootRepackage', 'createDockerfile'

        doFirst {
            copy {
                from "$buildDir/libs"
                into "$buildDir/docker"
                include 'orangebox-storage-1.0.0.jar'
                rename 'orangebox-storage-1.0.0.jar', 'app.jar'
            }
        }

        inputDir = file("$buildDir/docker")
    }

    task createContainer(type: DockerCreateContainer, group: 'docker') {
        dependsOn buildImage
        targetImageId { buildImage.getImageId() }
    }

    task startContainer(type: DockerStartContainer, group: 'docker') {
        dependsOn createContainer
        targetContainerId { createContainer.getContainerId() }
    }

    task stopContainer(type: DockerStopContainer, group: 'docker') {
        targetContainerId { createContainer.getContainerId() }
    }
```

Thanks!

**Comment by orzeh** [comment]
I`m afraid it is [docker-java problem](https://github.com/docker-java/docker-java/issues/617), so we have to wait for them to fix it. 

You can try to specify Docker API version used, but I`m not sure if it will help.

**Comment by cdancy** [comment]
@orzeh has it right. I was actually discussing this very thing [on this thread](https://github.com/docker-java/docker-java/issues/615). Unfortunately setting the API version has no effect ;(

**Comment by ericweinberg** [comment]
I don't suppose there's any chance of not using the docker-java library?  Between this problem and the l[ack of support for docker native](https://github.com/docker-java/docker-java/issues/537), I think they're going to hurt adoption of this plugin.

**Comment by cdancy** [comment]
This plugin is tightly integrated with docker-java so we could not easily move away from it. It's a good library and the guys over there are doing a great job. The docker native problem is a bigger issue and one that requires the work of several libraries working in unison so to speak to reach the expected goal. 

With that said there are no plans to move away from the library as I don't see anything that could compete with it at this point.
