### ISSUE TITLE
Configuring javaApplication image tag in multi-module project fails

### ISSUE THREAD

**Issue by holgerstolzenberg** [bmuschko/gradle-docker-plugin#24]
I have a multi-module project consisting out of two modules. There is a parent Gradle build script and a parent `gradle.properties` file, where I define my project properties and the settings.gradle.

The modules are essentially the same, just a very small spring-boot helloworld application. The will be acting as a AMQP producer and a AMQP consumer.

The `build.gradle` files for both modules are essentially the same:

```groovy
buildscript {
  repositories {
    mavenCentral()
    jcenter()
  }
  dependencies {
    classpath "org.springframework.boot:spring-boot-gradle-plugin:$springBootVersion"
    classpath "com.bmuschko:gradle-docker-plugin:$dockerVersion"
  }
}

apply plugin: 'java'
apply plugin: 'spring-boot'
apply plugin: 'com.bmuschko.docker-java-application'

repositories {
  mavenCentral()
}

dependencies {
  compile('org.springframework.boot:spring-boot-starter-web') {
    exclude module: 'spring-boot-starter-tomcat'
  }
  compile('org.springframework.boot:spring-boot-starter-jetty')
  compile('org.springframework.boot:spring-boot-starter-actuator')
}

docker {
  url = property 'dockerHostUrl'

  javaApplication {
    baseImage = property 'baseImage'
    maintainer = property 'maintainer'
    port = property('appPort') as Integer
    tag = "$group/$project.name:$version"
  }
}
```

Running `../gradlew dockerBuildImage` I can see that the tag used falls back to the default.

When I remove one of the modules from the `settings.gradle`  file, the correct tag is picked up.

Using the default tag is sufficient for now, but we really like to configure it to have the group in it.

**Comment by bmuschko** [comment]
You will probably want to put the `docker` configuration into a `subprojects` block. Should you have more than these two subprojects, then you'll need to filter that list first and apply the logic. Does that make sense?

**Comment by holgerstolzenberg** [comment]
Hm the thing is that my project contains some modules and not all of them are dockerized java applications. I just mentioned these both as it is enough to describe the issue and lower down complexity. So the docker plugin and its configuration is only present for these two specific submodules.

Putting it into a `subprojects` block within the parent Gradle file would mean having it applied to all modules of the project, what is not wanted? Am I right with this assumption?

**Comment by bmuschko** [comment]
You will need to filter that list of subprojects. Here's how you can achieve that:

    def dockerProjects = [...] // List of project references via project(<projectPath>)

    configure(dockerProjects) {
        docker { ... }
    }

**Comment by bmuschko** [comment]
@holgerstolzenberg You got it working?

**Comment by holgerstolzenberg** [comment]
Sorry I did not have the time to try it out. I think that your suggested solution will work, but is that really straightforward? Why do I need to know in my parent build file, which kind of type my modules are? It does not really "look" good and has some kind of a smell :-)

Everything works fine if I have only one docker module in my project. I think that they should (must) not interfere with each other, if there are multiple docker modules.

It is the same with java apps. If I have more than one java app module, everything is declared in their subsequent module build files and there is no interference between them and I do not have to know about them in my parent build file.

**Comment by bmuschko** [comment]
You can also put that into a script plugin and then apply it to the relevant project(s). This discussion is not really specific to this plugin. 

I am going to close this issue. If you have more questions/concerns about configuring Gradle in general, I'd say open a question on the Gradle forum.

**Comment by holgerstolzenberg** [comment]
Hey,

I´d really like to open that one up again. I played around a bit and it seems very clear to me that there is an issue with the plugin and not with the Gradle configuration setup at all.

Imagine the following situation. You have a multi module project. You add the a fresh module and apply the docker plugin to it and configure it via `docker` extension and `javaApplication` configuration. You define maintainer "Benjamin" for this module. Everything works like expected.

Then you add the next docker sub module and configure it. You want to give it another maintainer, lets say "Holger". You apply the `docker` plugin to it. Now the setup breaks. Also the setup for the other module breaks, even if you do not touch it. Both module configurations return to their defaults.

This cannot be the desired behaviour. Even declaring them in parent build file won´t solve the issue with the different maintainers.

I do not know enough about the Gradle internals, why it works with one module and not with two modules set up. But I remembered having the same problem with a custom plugin I wrote. So I ended up adding to lines to `DockerJavaApplicationPlugin`within `apply` method. I wrapped the last `project.plugins.withType` call with a `project.afterEvaluate` closure.

```groovy
@Override
    void apply(Project project) {
        project.apply(plugin: DockerRemoteApiPlugin)

        DockerExtension dockerExtension = project.extensions.getByType(DockerExtension)
        DockerJavaApplication dockerJavaApplication = configureExtension(dockerExtension)

        project.afterEvaluate {
            project.plugins.withType(ApplicationPlugin) {
                Tar tarTask = project.tasks.getByName(ApplicationPlugin.TASK_DIST_TAR_NAME)

                Dockerfile createDockerfileTask = createDockerfileTask(project, tarTask, dockerJavaApplication)
                Copy copyTarTask = createDistCopyResourcesTask(project, tarTask, createDockerfileTask)
                createDockerfileTask.dependsOn copyTarTask
                DockerBuildImage dockerBuildImageTask = createBuildImageTask(project, createDockerfileTask, dockerJavaApplication)
                createPushImageTask(project, dockerBuildImageTask)
            }
        }
    }
```

Now everything works like a charm and as expected, but some integration tests are broken. I´ll try to fix that by now. And provide the pull request, after the ticket has been opened up.

It would be really great if we could incorporate into the plugin.

**Comment by holgerstolzenberg** [comment]
After some further digging around, it seems using `project.evaluate` is no good idea in terms of Gradle best practices.

After further investigation I found the bug that causes the configuration to be not applied. I will raise a separate issue, there is no more need opening this one up again.

**Comment by bmuschko** [comment]
Correct, `project.afterEvaluate` shouldn't be used until absolutely necessary. It has other implications.
