### ISSUE TITLE
How to use in combination with your tomcat gradle plugin?

### ISSUE THREAD

**Issue by mark-agillic** [bmuschko/gradle-docker-plugin#241]
Hi,

I am trying to deploy an embedded tomcat (using your gradle plugin) to a Docker container. 
Can you tell me how to hook this into the 'dockerBuildImage' task ?
Right now I'm getting:
A problem was found with the configuration of task ':startScripts'.
> No value has been specified for property 'mainClassName'.

My basic test project can be seen here: https://bitbucket.org/mnellemann/docker-test/src

The 'tomcatRunWar' task works as expected and the 'dockerBuildImage' task also works (when I provide a normal java main class).

Any help is appreciated :)

**Comment by orzeh** [comment]
You are using [gradle-tomcat-plugin](https://github.com/bmuschko/gradle-tomcat-plugin) which is designed to start Tomcat during Gradle build and deploy your application to it.

It seems that your goal is to deploy your application to Tomcat running in a Docker container, so why won't you just use [Tomcat Docker image](https://hub.docker.com/_/tomcat/)? Then you can simply copy  application war into an image using `ADD` instruction.

Another option is to use [Spring Boot](http://projects.spring.io/spring-boot/) which IMO fits better with Docker.

**Comment by mark-agillic** [comment]
Thank you - makes sense. I will look into the tomcat docker image. Using spring-boot would be awesome, but I'm trying to prove a case for a legacy app.
