### ISSUE TITLE
Allow to define a device mapping when creating a container

### ISSUE THREAD

**Issue by mrhaki** [bmuschko/gradle-docker-plugin#243]
When defining a container we want to configure which devices from the host are accessible in the container. With the docker `run` command this would be the `--device` option.

**Comment by orzeh** [comment]
Indeed this plugin lacks this functionality. `docker-java` supports this, so it should be straightforward to implement it.
@mrhaki or anyone interested in submitting PR?

**Comment by mrhaki** [comment]
@orzeh I can write a PR for this. Should be ready soon.

**Comment by mrhaki** [comment]
I have added PR #245 for this issue.
