### ISSUE TITLE
Supply build time variables to DockerBuildImage

### ISSUE THREAD

**Issue by dpr-rec** [bmuschko/gradle-docker-plugin#249]
Hi,

is it possible to pass build time arguments `DockerBuildImage` tasks similar to the `--build-arg` switch used with the docker command?

This would be needed to build images using the [`ARG`](https://docs.docker.com/engine/reference/builder/#/arg) Dockerfile instruction...

Best regards

**Comment by orzeh** [comment]
See https://github.com/bmuschko/gradle-docker-plugin/pull/240

**Comment by dpr-rec** [comment]
Oh, i looked for issues only...

That is, this feature will be available in 3.0.2 or is already in available in 3.0.1?

**Comment by orzeh** [comment]
Will be in 3.0.2

**Comment by dpr-rec** [comment]
Great thanks

**Comment by ousema2003** [comment]
functionality already released ?

**Comment by orzeh** [comment]
Yes: https://github.com/bmuschko/gradle-docker-plugin/blob/master/RELEASE_NOTES.md#version-302-august-14-2016
