### ISSUE TITLE
Consider adding project group information to the default tag value

### ISSUE THREAD

**Issue by holgerstolzenberg** [bmuschko/gradle-docker-plugin#25]
If a `group` property is defined for the project, is should be included in the default `tag` value.

```groovy
docker {
  javaApplication {
    tag = "$group/$project.name:$version"
  }
}
```

This will provide more sophisticated image names.

**Comment by bmuschko** [comment]
I am not sure if I want this to be the default. What's the reasoning? It will pretty much break all consumers of this plugin that currently rely on the existing default tag.

It's actually very simple to set this tagging strategy for your project as shown in your code snippet above.

**Comment by holgerstolzenberg** [comment]
You are right, I haven´t thought of backwards compatibility so far. I think that having the group within the default tag is closer to the Docker standard naming the community is cultivating right now. I find it much more pleasant to issue a `docker images` command and grep for a specific group. This gets really interesting within a companies private repo when trying to find a specific app from that company.

**Comment by bmuschko** [comment]
Fair enough. That makes sense. Can you touch up your pull request based on my comments?
