### ISSUE TITLE
Unable to connect to private docker registry

### ISSUE THREAD

**Issue by kanebryant** [bmuschko/gradle-docker-plugin#251]
I work in a restricted environment so I cannot access docker hub so I have attempted to setup my gradle build pointing to our private registry but the plugin seems to keep wanting to use docker hub?

I get the following error

Could not build image: Get https://index.docker.io/v1/repositories/frolvlad/alpine-oraclejdk8/images: dial tcp 52.22.190.106:443: connection refused

here is my docker gradle config
````groovy
docker {
  url = 'tcp://appleby.test.austrac.gov.au:2376'
  
  registryCredentials {
    url = 'tcp://cdiregistry.test.austrac.gov.au'
  }
}
````

**Comment by eshepelyuk** [comment]
What task do you try to run ?

**Comment by kanebryant** [comment]
I run buildImage

task createDockerfile(type: Dockerfile) {
    destFile = project.file('build/docker/Dockerfile')
    from 'frolvlad/alpine-oraclejdk8:slim'
    maintainer 'Kane Bryant"kane.bryant@austrac.gov.au"'
    volume '/tmp'
}

task buildImage(type: DockerBuildImage) {
    dependsOn   copyJar
    dependsOn createDockerfile
    inputDir = createDockerfile.destFile.parentFile
    tag = 'kane/hello-world-image'
}

**Comment by eshepelyuk** [comment]
You could do one of the following

-  Download image locally and retag it
```
$ docker pull cdiregistry.test.austrac.gov.au/frolvlad/alpine-oraclejdk8:slim
$ docker tag cdiregistry.test.austrac.gov.au/frolvlad/alpine-oraclejdk8:slim frolvlad/alpine-oraclejdk8:slim
```
- or adjust `build.gradle` like 

```
task createDockerfile(type: Dockerfile) {
  ...  
  from 'cdiregistry.test.austrac.gov.au/frolvlad/alpine-oraclejdk8:slim'
}
```

#### PS
I'd suggest you to try `docker-java-application` (2nd plugin available in JAR) instead of `.docker-remote-api`.
You could avoid creating boilerplate tasks (Dockerfile generation, docker image build etc), since `docker-java-application` already provides them

**Comment by orzeh** [comment]
Just a side note: using Docker image with Oracle JDK [you break the licence agreement](http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/). Take a look at [Azul Zulu](https://www.azul.com/products/zulu/) and their [Docker images](https://hub.docker.com/u/azul/).

**Comment by kanebryant** [comment]
Thanks for your help I am now trying java-application but was wondering how I use it for a spring-boot application or should I go back to using the other plugin and build the image myself?

In the meantime I am still having connection errors and was wondering where do I set the --insecure-registry option, is this done on the docker instance? or somewhere in my gradle config

Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: invalid registry endpoint https://cdiregistry.test.austrac.gov.au:500/v0/: unable to ping registry endpoint https://cdiregistry.test.austrac.gov.au:500/v0/
v2 ping attempt failed with error: Get https://cdiregistry.test.austrac.gov.au:500/v2/: dial tcp 192.168.136.213:500: i/o timeout
 v1 ping attempt failed with error: Get https://cdiregistry.test.austrac.gov.au:500/v1/_ping: dial tcp 192.168.136.213:500: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry cdiregistry.test.austrac.gov.au:500` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/cdiregistry.test.austrac.gov.au:500/ca.crt

**Comment by eshepelyuk** [comment]
1. Spring boot application are working perfectly with `docker-java-application`. Here's an example of setup https://github.com/eshepelyuk/CodeForBlog/blob/master/SpringBootZuulAuth/build.gradle
2. You should are `--insecure-registry` to your local `Docker Engine` options, i.e. to one that you're configuring with `docker.url` property.

**Comment by kanebryant** [comment]
Thanks for all your help I have managed to build and publish to our private docker registry, but when I look at existing docker spring boot docker examples their dockerfile is different to the one generated by the javaApplication plugin. I would have thought I need to change the entry-point and include a volume like in the spring examples. However I am new to docker and spring-boot so I could be missing something.

FROM cdiregistry.test.austrac.gov.au:5000/library/alpine-oraclejdk8
MAINTAINER kbryant
ADD hello-world.tar /
ENTRYPOINT ["/hello-world/bin/hello-world"]
EXPOSE 8090

**Comment by orzeh** [comment]
To use SpringBoot efectively you will have to write your own `Dockerfile` and resign from `docker-java-application`.

SpringBoot produces Fat JARs which can be run directly invoking `java` command:

````bash
java -jar my-boot-app.jar --spring.profiles.active=dev
````

So this can be set as Docker `ENTRYPOINT` or `CMD`.

However, to utilize Docker cache during image build, please take a look at [this blog post](http://bsideup.blogspot.in/2015/04/spring-boots-fat-jars-vs-docker.html). It shows also how to run _expanded_ Fat JAR. Please note that since SpringBoot 1.4 the layout of Fat JAR [has changed](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#executable-jar-layout) so this article is outdated in several places.

If I'll find some time today, I will setup sample project and share it here.

**Comment by orzeh** [comment]
@eshepelyuk you are right, but packaging your app with `application` plugin won`t let you benefit from using Docker cache during image build  - see #58 and #68.

What I`m trying to say is that neither Spring Boot Fat JAR nor application plugin works well in more advanced use cases, but of course they are good to start play with Gradle and Docker.

**Comment by eshepelyuk** [comment]
Thanks for the explanation!.
Do you have any thoughts about how long it will take to adopt #68 ?

**Comment by orzeh** [comment]
I hope I'll find some time to take a look at it.

**Comment by cdancy** [comment]
@eshepelyuk just wondering why the particular interest in that PR? It's older and needs some work to cleanup and has been around since before I came on board and may need some attention from the submitter assuming he's still interested.

**Comment by eshepelyuk** [comment]
As far as I understand this PR will improve Docker images creation (Docker cache usage), so no need to implement tricks mentioned above.

**Comment by orzeh** [comment]
@kanebryant sample project for Spring Boot https://github.com/orzeh/spring-boot-gradle-docker-sample

**Comment by kanebryant** [comment]
Thanks orzeh 

I can see you unpack the original fat jar then build the docker image oddly enough no docker image appears in the build anywhere? I can see the unpacked contents but no docker image even though the build is successful. But I won't bother you guys too much I think you both gave me enough help to get me going and I appreciate all the halp thanks!
