### ISSUE TITLE
Proposal for simplification of pushing images to private registries

### ISSUE THREAD

**Issue by eshepelyuk** [bmuschko/gradle-docker-plugin#252]
The common scenario when working with private Docker Registry is

1. Build Image

1. Tag image with new tag containing private registry URL

1. Push new tag (image) to private registry

Currently it can be achieved by creating custom image task and adjusting provided push task and this is not very straighforward.

From the other side [Mave plugin](https://github.com/spotify/docker-maven-plugin) provides an option to push image immediately from within image tag task.

What do you think about adding such feature to this plugin ?

Another option is not try to mock other plugin funtionality but go further and implement some sort of smart behaviour for `dockerPushImage` provided by `docker-java-application`.
I.e. when plugin identifies that custom registry is configured - it modifies the behavior of `dockerPushImage` task
to create tag with private registry URL and then invoke push for that tag, not original one, created by `dockerBuilIdmage` task.

**Comment by orzeh** [comment]
AFAIK this plugin philosophy is to provide basic building blocks for interacting with Docker.

What you propose is something which is IMO rather project or workflow depended, and should be covered by custom plugin / shared Gradle scripts.

@cdancy maybe you have some other thoughts?

**Comment by cdancy** [comment]
> Currently it can be achieved by creating custom image task and adjusting provided push task and this is not very straighforward.

I actually think that is as straightforward as one can get ;) Sure we could wrap multiple tasks into a single task, or something along those lines, but as @orzeh has noted: this sounds like it belongs in a custom plugin if you really want to simplify your process.

While I'm here and thinking of it: @eshepelyuk I still taking a look at your PR today. Been busy with work and haven't had much free time the past couple weeks.

**Comment by eshepelyuk** [comment]
> I actually think that is as straightforward as one can get ;)

@cdancy let me disagree. The solution for pushing to private repo we end up with (i've described [HERE](https://github.com/bmuschko/gradle-docker-plugin/issues/209#issuecomment-235815644)) doesn't look neither simple nor straighforward at all :(

Moreover, just by taking a quick look at issue list one could see a number of them ( #226 #202 #251 #209 ) related to problems while interacting with private registries.
Although, I don't think it's a plugin fault but rather confusing approach of `Docker` itself, users are blaming plugin first of all :(

My intention was to try to fill this gap in plugin functionality, providing some sort of **sensible defaults**, to improve general users experience for the functionality, used by decent number of peoples.

Honestly, I don't see a much sense in creating yet another plugin for **tag'n'push to private registry**, if we could implement it in current codebase.  
While proposed options may be not the best ones, let me dare to ask you again to think about possible solutions and do not sacrifice user experience in favour of _"simplicity"_.

**Comment by orzeh** [comment]
@eshepelyuk here is code I use to push my images to corporate registry:
````groovy
task buildDockerImage(type: DockerBuildImage) {
	inputDir = project.projectDir
	tag = "${dockerRegistryHost}/asseco-poz/${project.name}:" + tagFromProjectVersion(project)
}

task pushDockerImage(type: DockerPushImage, dependsOn: buildDockerImage) {
	imageName = "${dockerRegistryHost}/asseco-poz/${project.name}"
	tag = tagFromProjectVersion(project)
}

def tagFromProjectVersion(p) {
	p.version.toString()
}
````

IMO it's quite simple and straightforward.

Can you provide some example of _new_ syntax you propose? Then it would be easier to talk about it. I'm sure we can find some compromise between simplicity and user experience!

**Comment by cdancy** [comment]
Closing this issue as I believe nothing is technically wrong and/or broken. Feel free to re-open if you want to further discuss.

**Comment by eshepelyuk** [comment]
I am sorry for the delay in reply. Let me reopen the issue, providing details of the one of th possible implementations.

### Intention

* While working with private registry, plugin users should have a out-of-box possibility to build and push image to private registry for a sample project, i.e. when users only need `docker-java-application` plugin
* *out-of-box* implies 
    * no additional task creation, no usage of `docker-remote-api` plugin at all
    * should be provided just by applying `docker-java-application` plugin

### Implementation (one of the possible)

1. Detect if `docker.registryCredentials.url` extension property is defined during `docker-java-application` plugin application phase to the project and its value not equals to `Docker Hub` registry

1. If `docker.registryCredentials.url` is set then 

    * create default task `dockerTagImage` of type `DockerTagImage`
    * configure `dockerTagImage` task to use `docker.javaApplication.tag` as a image to tag, and use `"${docker.registryCredentials.url}/${docker.javaApplication.tag}"` as a target tag value 
    * configure task `dockerPushImage`  to use `"${docker.registryCredentials.url}/${docker.javaApplication.tag}"` as an tag to push
    * configure task `dockerPushImage` to depend on `dockerTagImage`
    * configure task `dockerTagImage` to depend on `dockerBuildImage`

1. So, when user executes

        $ gradle dockerPushImage`

    plugin will
    
    1. build image and tag it with `docker.javaApplication.tag` value

    1. tag this image with `"${docker.registryCredentials.url}/${docker.javaApplication.tag}"`

    1. push tag to `docker.registryCredentials.url` registry.

@bmuschko @orzeh @cdancy please comment

**Comment by eshepelyuk** [comment]
BTW, I can't reopen the issue :(

**Comment by cdancy** [comment]
@eshepelyuk while ease of use is great the above impl still assumes too much. This plugin, like all publicly accessible plugins, is meant to act as a building block for you to implement the above in your own build script and potentially your own plugin. While the above may seem to save on code the user has to write it has the disadvantage of hiding details and allowing the user to properly define his/her own chain of dependent tasks. This may work in a corporate setting, where the chain of tasks and inputs are constant, the same is not true for everyone else.

**Comment by eshepelyuk** [comment]
@cdancy you're 100% right when talking about `docker-remote-api`.
But `docker-java-application` (one I am only referring to in this issue) is already not just a *building block*.
`docker-java-application` implements some predefined scenario: imposes usage of `application` plugin, provides predefined and preconfigured tasks, etc.
And case of private registry is a natural extension for that scenario, imo.

**Comment by orzeh** [comment]
My thoughts:
> Detect if docker.registryCredentials.url extension property is defined during docker-java-application plugin application phase to the project and its value not equals to Docker Hub registry

Why one can't push to Docker Hub? It also supports private registries.
 
> use "${docker.registryCredentials.url}/${docker.javaApplication.tag}" as a target tag 

This block scenario when private registry requires `username` (like Gitlab). In that case the tag should be:
 "${docker.registryCredentials.url}/someuser/${docker.javaApplication.tag}"

To sum up, I fully understand your motivation, but you didn't convinced me. At this moment I agree with @cdancy that this should be covered by other plugin.

**Comment by eshepelyuk** [comment]
First of all thanks for your suggestions about tag and username, I didn't know it.

Second, unfortunately I don't understand this insistent pushing for the new plugin creation.
According to this logic, `docker-java-appication` should be removed from this repository too, because it imposes single pre-defined flow. 

If your intention is to move out `docker-java-appication` - I'm open to help on doing and maintaining it.

Otherwise, can I try to modify my initial proposal and make it (maybe) easier.

So, how else this can be done.

- Introduce new parameter `pushTag` into `docker.javaApplication` extension. I.e.

```
docker {
    javaApplication {
        tag = 'jettyapp:1.115'
        pushTag = 'my.registry.com:5555/jettyapp:1.115'
    }
}
```

- During `docker-java-application` application phase detect if `pushTag` is defined

- If defined - create task `dockerTagImage` of type `DockerTagImage`, configured like this

```
task dockerTagImage(type: DockerTagImage, dependsOn: 'dockerBuildImage') {                         
        imageId = dockerBuildImage.tag // without tag, i.e. before `:`                          
        tag = //tag part from dockerBuildImage.tag, i.e. after the `:`                                            
        repository = "${docker.javaApplication.pushTag}"                                                                  
}                                                                   
```

- If `docker.javaApplication.pushTag` is defined - make `dockerPushImage` depend on `dockerTagImage`

And thank for your attention to the issue, anyway :)
