### ISSUE TITLE
Documentation has a dead link

### ISSUE THREAD

**Issue by trogdor259** [bmuschko/gradle-docker-plugin#255]
I am wanting to use DockerExecContainer to do a docker run command. The link to the documentation for that method goes to a 404 page. I need to be able to add in several args when doing the run command. If I can get some documentation on how to do so, that'd be great.

**Comment by cdancy** [comment]
@bmuschko can you re-configure snap-ci to publish githubpages or re-run the task from your desktop? I can't do so even with the permissions you've given.

**Comment by cdancy** [comment]
@trogdor259 you always [look at the task directly](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy) to see what its inputs are.

**Comment by bmuschko** [comment]
@cdancy Published a new version of the Groovydocs from my local machine. So far I wasn't able to publish from Snap-CI. Publishing the docs requires a checkout of the `ghpages` branch which I didn't manage to check out in addition to `master`. Are you interested in looking into it?

**Comment by cdancy** [comment]
@bmuschko are you sure it requires a checkout? I use a similar setup in my own project and I think we can amend the `release` task within `release.gradle` to be something like this:

	task release {
		description = 'Publishes artifacts to Bintray and tags repository with current project version.'
		dependsOn assemble, publishGhPages, bintrayUpload, tag
	}

**Comment by bmuschko** [comment]
@cdancy That's what I remember. I might be wrong. At least the task was failing on Snap-CI when I tried it out a year ago. Can you add the `publishGhPages` as task dependency to `release` and see how it goes?

**Comment by cdancy** [comment]
@bmuschko  If you can set your github username/password as environment variables on the snap-ci job I can get this functionality working.
