### ISSUE TITLE
Could not find method registryCredentials()

### ISSUE THREAD

**Issue by MarkRx** [bmuschko/gradle-docker-plugin#262]
Hello,

I'm having problems trying to add the registryCredentials closure to DockerPushImage and DockerPullImage tasks. Exception and code snippet below. I'm using v3.0.2 of the plugin.

> Caused by: org.gradle.api.internal.MissingMethodException: Could not find method registryCredentials() for arguments [build_9o7fxvr4bt2gtvm994d32n5v$_run_closure3$_closure6@969b472] on root project 'imagepromotion'.
>         at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
>         at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
>         at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:175)

```
task dockerPull(type: DockerPullImage, group: "docker") {
	repository = "${dockerPullRegistry}/${dockerRepository}"
	tag = "${dockerTag}"
	registryCredentials {
		url = 'http://myurl.com'
	}
}
```

> vagrant@vagrant-ubuntu-trusty-64:/vagrant/imagepromotion$ ./gradlew --version
> 
> ------------------------------------------------------------
> Gradle 2.12
> ------------------------------------------------------------
> 
> Build time:   2016-03-14 08:32:03 UTC
> Build number: none
> Revision:     b29fbb64ad6b068cb3f05f7e40dc670472129bc0
> 
> Groovy:       2.4.4
> Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
> JVM:          1.7.0_91 (Oracle Corporation 24.91-b01)
> OS:           Linux 3.13.0-74-generic amd64

**Comment by cdancy** [comment]
@MarkRx have you tried adding it to the `docker` extension as [documented here](https://github.com/bmuschko/gradle-docker-plugin#extension-examples)?

**Comment by MarkRx** [comment]
Yes but that won't work in my case because the push task will be using different registryCredentials than the pull task.

**Comment by MarkRx** [comment]
This works for now:

```
task dockerPull(type: DockerPullImage, group: "docker") {
	repository = "${dockerPullRegistry}/${dockerRepository}"
	tag = "${dockerTag}"
	registryCredentials = new DockerRegistryCredentials()
	registryCredentials.url = "http://${dockerPullRegistry}"
}
```

I think for it to work the way I was expecting there needs to be a registryCredentials method that takes a closure and applies it to a DockerRegistryCredentials object.

**Comment by cdancy** [comment]
@MarkRx that is correct. Closing issue as it appears we have a working solution.
