### ISSUE TITLE
Plugin should report full error messages sent to docker client

### ISSUE THREAD

**Issue by davidmichaelkarr** [bmuschko/gradle-docker-plugin#264]
I'm trying to construct a docker image, and the "buildImage" task fails with the following:
`* What went wrong:
Execution failed for task ':ordersImage:buildImage'.
> java.lang.reflect.InvocationTargetException-->null`

This obviously doesn't tell me anything useful.  If I add "--stacktrace", I get the following from the root cause:
`DockerClientException: Could not build image: lstat ordersService.war: no such file or directory`

I know why this is giving this error message, but the point is, I shouldn't have had to wade through the stacktrace to find this. Any error messages sent back to the embedded docker client should be reported to the user.

**Comment by cdancy** [comment]
@davidmichaelkarr I believe this has more to do with the dynamic nature of our plugin, and how we are loading/executing the `docker-java` library, than anything else. It is standard practice to use `--stacktrace` to get the full output (I personally use this everywhere by default) so I don't necessarily see an issue there. I can however appreciate your frustration with the returned message as it does not give any clue as to what is wrong only that _something_ is wrong. Unfortunately there is not much we can do given how this plugin is designed (which has more plusses than minuses IMO). We'd have to wrap all calls in try/catch block, interrogate the caught exception, and re-throw that (just thinking off the top of my head here) with the particular exception we are interested in. Feels like more work than it's worth IMO. If you've got any ideas, or a PullRequest you want to put together to address this, I'd love to hear and/or review it!

**Comment by eshepelyuk** [comment]
Shouldn't it be the only one place in code to catch / process `InvocationTargetException` ?

* `com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader#withClasspath`

or 

* `com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask#runInDockerClassPath`

**Comment by orzeh** [comment]
@eshepelyuk is right.
I'm fixing it now and send PR when ready.
