### ISSUE TITLE
Add EditorConfig coding styles

### ISSUE THREAD

**Issue by orzeh** [bmuschko/gradle-docker-plugin#267]
In many PR there are formatting issues like ident with tabs, etc.

It would be convenient to setup common code styles with [EditorConfig](http://editorconfig.org/), which is supported in vast majority of IDEs.

My proposition of rules (based on current status in repo):
* ident with 4 spaces in Groovy and Gradle files
* new line at the end of a file
* LF line endings
* UTF-8 character encoding

@cdancy what do you think?

**Comment by cdancy** [comment]
@orzeh sounds good. We should circle back and apply checkstyle plugin as well as it would stop us from having to tell folks to fix silly issues. I've done that for a few of my gradle projects and can wire things up here easy enough.
