### ISSUE TITLE
Make it possible for a run of DockerBuildImage to report "UP-TO-DATE"

### ISSUE THREAD

**Issue by davidmichaelkarr** [bmuschko/gradle-docker-plugin#268]
I don't need to tell you that one of the important aims of Gradle is to allow for task runs to report "UP-TO-DATE" if all of its inputs and outputs are unchanged since the last run.

When I run my "DockerBuildImage" task, it builds the image.  If I immediately run it again, it builds the image again.

It's generally a good idea to enable tasks to work that way (possibly knowing when there's no work to do), but it's even more important for tasks that have to do a lot of work, like building a Docker image.

Is it possible to enhance the task so that it can know if all of its required inputs and outputs are up to date?

If it matters, my image build is pretty simple right now. This is the relevant excerpt from my build file:
`docker { 
  url = "unix:///var/run/docker.sock"
}
task buildImage(type: DockerBuildImage) {
  inputDir = file("${buildDir}/context")
  imageId  = "ssorderprocessingdashboard"
}`

All of the tasks that populate the context dir are "up-to-date-able".  I've verified in a repeated build that all of them report "UP TO DATE", and then when DockerBuildImage runs, it does not report "UP TO DATE".

**Comment by cdancy** [comment]
@davidmichaelkarr tried to tackle this before but upon further investigation there is no surefire way to tell if an image is different from another image or even "UP-TO-DATE". After tackling corner case after corner case we backed out the functionality all together. I'd recommend putting an `onlyIf {}` block in your "build image" task and skip say if some image exists that you know is good for you.

**Comment by davidmichaelkarr** [comment]
Thinking about this, I can see it would be next to impossible.  For instance, if I'm building from a Dockerfile that runs "apt-get/yum update" before installing packages, which I believe is a recommended practice, I imagine this could get package versions that are newer than what's in the Docker cache.
