### ISSUE TITLE
javaApplication should provide a way to override user in Dockerfile (dockerDistTar)

### ISSUE THREAD

**Issue by tclift** [bmuschko/gradle-docker-plugin#27]
Many published Docker images don't specify a user, so default to `root`. I don't really want to run my Java application as `root`, so I would like a way to override it. This is image dependent, but `daemon` seems appropriate in my case (Debian Wheezy).

What about adding a `user` property to the `DockerJavaApplication` convention?

Here's what I'm currently using as a workaround:
```gradle
tasks[com.bmuschko.gradle.docker.DockerJavaApplicationPlugin.DOCKERFILE_TASK_NAME].doFirst {
    user 'daemon'
}
```
and I'm totally fine with that, but it took a bit of poking around to work it out.

Thank you very much for this plugin.

**Comment by bmuschko** [comment]
You don't really need to use `doFirst` here. This will do:

    dockerDistTar.user 'daemon'

For now I don't really want to expose this as a property through the extension as it is so easy to do.
