### ISSUE TITLE
destFile = null error 

### ISSUE THREAD

**Issue by anandchida** [bmuschko/gradle-docker-plugin#271]
All,

I tried the example from the README
````
import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

task createDockerfile(type: Dockerfile) {
    destFile = project.file('Dockerfile')
    from "${baseImage}"
    maintainer "${maintainerEmail}"
    addFile "build/libs/${appName}-${appVersion}.jar", "${appName}-${appVersion}.jar"
    volume '/tmp'
    runCommand "sh -c 'touch ${appName}-${appVersion}.jar'"
    exposePort appPort
    entryPoint "java","-Djava.security.egd=file:/dev/./urandom","-jar","/${appName}-${appVersion}.jar"
}

task buildImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    inputDir = createDockerfile.destFile.parentFile
    tag = 'bmuschko/myimage'
}
````

`gradle createDockerfile` task generates the Dockerfile correctly while the `gradle buildImage` task fails with 

"* What went wrong:
null value in entry: destFile=null"

I'm using 3.0.2 of the plugin with Gradle 3.0

**Comment by cdancy** [comment]
@anandchida that all looks correct. Have you tried running with `gradle 2.14.1` to see if the same still pops? Here are a couple things I would try in order to diagnose this issue:

1. Try hard-coding the directory and see if that works.
2. Try putting the `Dockerfile` in some place like `project.file('build/Dockerfile')`

**Comment by anandchida** [comment]
1 and 2 fails even on gradle 2.14.1. Also now I see 

* What went wrong:
Execution failed for task ':buildImage'.
> Cannot invoke method withClasspath() on null object

Maybe something how my build and docker gradle files are configured. Here they are -
build.gradle

defaultTasks "clean","build"

project.ext.appName = "projmgmt"
project.ext.appVersion = "1.0.1"

apply from: 'docker.gradle'
apply from: 'analysis.gradle'

buildscript {
	ext {
		springBootVersion = '1.4.0.RELEASE'
	}
	repositories {
		mavenCentral()
		maven {
      			url "https://plugins.gradle.org/m2/"
    		}
	}
	dependencies {
		classpath( "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}" ) 
		classpath( 'io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE' )
		classpath( 'com.bmuschko:gradle-docker-plugin:3.0.2' )
	}

}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'spring-boot' 
apply plugin: 'io.spring.dependency-management'
apply plugin: 'com.bmuschko.docker-remote-api'

jar {
    baseName = appName
    version = appVersion
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
	mavenCentral()
}

dependencies {
	compile( 'org.springframework.boot:spring-boot-starter-actuator' )
	compile( 'org.springframework.boot:spring-boot-starter-cache' )
	compile( 'org.springframework:spring-webmvc:4.3.2.RELEASE' )
        compile( 'org.springframework.boot:spring-boot-starter-data-jpa' )
	compile( 'org.springframework.boot:spring-boot-starter-tomcat' )
	testCompile( 'org.springframework.boot:spring-boot-starter-test' ) 
}

dependencyManagement {
	imports { 
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Brixton.SR5" 
	}
}

eclipse {
	classpath {
		 containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
		 containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
	}
}

findbugs {
	findbugsTest.enabled false
}

pmd {
	pmdTest.enabled false
}

checkstyle {
	checkstyleTest.enabled false
}

-------------
docker.gradle

def baseImage = "frolvlad/alpine-oraclejdk8:slim"
def maintainerEmail = "me@gmail.com"
def appPort = 8080

buildscript {
    repositories {
        jcenter()
    }	
    dependencies {	
        classpath( 'com.bmuschko:gradle-docker-plugin:3.0.2' )
    }
}

import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

task createDockerfile(type: Dockerfile) {
    destFile = project.file('Dockerfile')
    from "${baseImage}"
    maintainer "${maintainerEmail}"
    addFile "build/libs/${appName}-${appVersion}.jar", "${appName}-${appVersion}.jar"
    volume '/tmp'
    runCommand "sh -c 'touch ${appName}-${appVersion}.jar'"
    exposePort appPort
    entryPoint "java","-Djava.security.egd=file:/dev/./urandom","-jar","/${appName}-${appVersion}.jar"
}

task buildImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    inputDir = createDockerfile.destFile.parentFile
    tag = "${appName}/${appVersion}"
}

**Comment by orzeh** [comment]
@anandchida using `gradle-docker-plugin` in separate build scripts may cause problems, due to how Gradle maintains classpath. See [this issue](https://github.com/bmuschko/gradle-docker-plugin/issues/248) and [here is a solution](https://github.com/bmuschko/gradle-docker-plugin/issues/248#issuecomment-234098958) .

**Comment by orzeh** [comment]
Hope links above helped you. If not, please reopen.
