### ISSUE TITLE
Support docker >= 1.12

### ISSUE THREAD

**Issue by svasconcelos** [bmuschko/gradle-docker-plugin#273]
I am trying to run your plugin with docker 1.12 but I am getting the error described in #238, which seemingly has been fixed in #263. Can you release a new version of the plugin?

**Comment by cdancy** [comment]
@svasconcelos got a bit of free time to work on this now. Going over one PR at the moment and should **REALLY** have something out this afternoon which should make @lukasniemeier-zalando among others. I'll reply back to this ISSUE once the release has been made available.

**Comment by cdancy** [comment]
@svasconcelos new version 3.0.3 has been released.

**Comment by svasconcelos** [comment]
Great, thanks!
