### ISSUE TITLE
DockerBuildImage fails to pull public repo images if registryUsername registryPassword are present

### ISSUE THREAD

**Issue by bitsofinfo** [bmuschko/gradle-docker-plugin#275]
This used to work about ~ a month ago w/ this plugin, but now when I run it, `DockerBuildImage` fails to pull public repo images if `registryUsername` `registryPassword` project properties are present 

(I specify them via `-PregistryUsername=myPrivateRepoUsernameForDockerTagImage` etc syntax)

I have a task like this

```
    task buildTagDockerImage(type: DockerTagImage) {
        dependsOn buildDockerImage
        targetImageId { buildDockerImage.getImageId() }

        if (project.hasProperty("registryHost")) {
          repository = "$registryHost/mypath/$project.name"
        }
        if (project.hasProperty("imageTag")) {
          tag = project.imageTag
        }

    }
```

**Comment by cdancy** [comment]
@bitsofinfo so the name of this task is `buildTagDockerImage` which is of type `DockerTageImage` yet you cite `DockerBuildImage`. Maybe you've got things confused?

Which version of the plugin were you using when things "worked" and can you provide a stacktrace?

As far as how to define a registry with credentials [that is covered here](https://github.com/bmuschko/gradle-docker-plugin#working-with-a-tls-enabled-docker-instance).

**Comment by bitsofinfo** [comment]
No this is intended. The task is `buildTagDockerImage`, it builds on top of another task I have called `buildDockerImage`, so it invokes that, then does `DockerTagImage`. My point is that if `registryUsername` or `registryPassword` properties are specified, those get passed to the public docker hub repo when `DockerBuildImage` is invoked, and i get `unauthorized` 401's from the public docker repos

**Comment by cdancy** [comment]
@bitsofinfo but this same script, with the same version, worked previously? Seems like that wouldn't be the plugin so as much as it sounds like an auth issue.

**Comment by cdancy** [comment]
@bitsofinfo closing ISSUE. Feel free to re-open if you want to talk further.
