### ISSUE TITLE
gradle build docker image behind a proxy 

### ISSUE THREAD

**Issue by ousema2003** [bmuschko/gradle-docker-plugin#276]
how to build docker image  with a build envirnment (docker server) behind a proxy ?

**Comment by orzeh** [comment]
Gradle is a Java application so [standard settings](http://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html) should be set. How to setup this in Gradle is described in the [documentation](https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy).

**Comment by ousema2003** [comment]
please note that proxy is used for (build env / docker server)
note for client side

**Comment by ousema2003** [comment]
since build-time variables are supported  to build image (https://github.com/bmuschko/gradle-docker-plugin/pull/240/commits/c6e26e4217bd6c5bd54f592ff509742f26efbac3)
could you please provide an example how to use it ?

**Comment by orzeh** [comment]
I'm afraid I've misunderstood you. To clarify your use case:
you execute Gradle build on a `hostA` which communicates with `hostB` which has `Docker Engine` installed and `hostB` is behind a HTTP proxy, so Docker can't communicate with Docker Hub. Right?

**Comment by ousema2003** [comment]
yes; my Dockerfile is built on hostB which is behind a proxy. i use curl inside the Dockerfile to download content from the internet through a proxy. i found that i can use the buildArgs to solve this issue.

inside my DockerBuildImage task i add the following param:
buildArgs = ['http_proxy': 'http://proxy-server:proxy-port', 'https_proxy': 'http://proxy-server:proxy-port']

**Comment by ousema2003** [comment]
thanks for your help!
