### ISSUE TITLE
Why nothing is cached?

### ISSUE THREAD

**Issue by least-olegs** [bmuschko/gradle-docker-plugin#277]
I was hoping that if files on which `DockerBuildImage` task depends aren't modified, then the task will not call `docker build` again, or, to be even more robust, would check the registry for the target image, and if absent, will rebuild.  Is my understanding correct that all the 165 jars this plugin downloaded are basically doing the same thing as Bash script `$ docker build <image>`?

**Comment by davidmichaelkarr** [comment]
I think perhaps the docs should state right up front that these tasks are not "up-to-dateable".  I had noticed the same thing, and filed an issue a while ago.  The problem is, in order for a task to be "up-to-dateable", it has to be absolutely certain that running the task again will produce exactly the same image. That might be the case for some Dockerfile builds, but it's quite common for Dockerfiles to do things that are not idempotent, like "apt-get update", or the like.  I'm sure there are other cases that make this determination impossible.

**Comment by cdancy** [comment]
@davidmichaelkarr has it correct: there is simply no sane way to tell if an image is different from another.

**Comment by least-olegs** [comment]
Fair point @davidmichaelkarr , but I hoped for some mechanism I can promise to the build system that things didn't change. This is by far the most complicated part of the integration with Docker. Calling Docker client for me is just a hair breadth far from being useless.

**Comment by cdancy** [comment]
@least-olegs you would have to implement something on your end that does various checks that gives you confidence that your image is "UP-TO-DATE".

**Comment by least-olegs** [comment]
Then, I wouldn't need your plugin... to do this, I need to fetch digests from image descriptions, track layer's hash-sums in my database, send special headers to Docker API etc. I'm just surprised this info doesn't appear on the front page of this repository. This is not actually an integration with Docker.  This is just a wrapper to the wrapper of its REST API...

**Comment by cdancy** [comment]
> Then, I wouldn't need your plugin... to do this

No one said you needed the plugin to do anything it just makes life easier if you're working in a gradle based context.

> I need to fetch digests from image descriptions, track layer's hash-sums in my database, send special headers to Docker API etc

You can readily implement this on your own, in whatever fashion you wish, or you could provide a PullRequest for this plugin adding in the additional functionality for others to take advantage of.

> I'm just surprised this info doesn't appear on the front page of this repository

I'm not sure why the surprise as you clearly state "this is just a wrapper around the REST API".

**Comment by gadieichhorn** [comment]
Hi, 
Just wondering if you have a code snippet to enable this cache?

I have a multi container project (each module has a docker image built) so I would like to get a new container only when the code/jar has changed.

thanks in advance.

**Comment by orzeh** [comment]
> so I would like to get a new container only when the code/jar has changed.

@gadieichhorn you probably meant new image? Then just add [`onlyIf`](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:using_a_predicate) to your build image tasks with your logic which checks if code/jar didn't changed.

**Comment by gadieichhorn** [comment]
yes, new image. Thanks  @orzeh 

I thought Gradle supports this type of caching as the build only triggered on new modules code. I think it is to do with defining inputs and outputs for the tasks. 

This can be a nice addition to the plugin as the image building takes long time ...

**Comment by orzeh** [comment]
@gadieichhorn this was discussed here many times before. Please take a look at #335
