### ISSUE TITLE
Releases 3.0.2 and 3.0.3 not in maven central

### ISSUE THREAD

**Issue by kpage** [bmuschko/gradle-docker-plugin#278]
Hi @bmuschko , thanks again for a great plugin.  I was wondering if something is wrong with the publish to Maven Central for this project.  I see that releases 3.0.2 and 3.0.3 are in jcenter but not maven central:

Present in JCenter: https://bintray.com/bmuschko/gradle-plugins/com.bmuschko%3Agradle-docker-plugin/3.0.3
Missing in Maven Central: https://repo1.maven.org/maven2/com/bmuschko/gradle-docker-plugin/

**Comment by cdancy** [comment]
This should be handled by JCenter upon publication. @bmuschko you'd have to take a look to see if something changed on that end.

**Comment by bmuschko** [comment]
Synced just now. Should be available in a couple of hours depending on the weather (as JFrog likes to say). ;-)
