### ISSUE TITLE
classpath issues when loading the plugin in a separate file

### ISSUE THREAD

**Issue by dalbertom** [bmuschko/gradle-docker-plugin#280]
I've been having some issues when loading the plugin outside of the main `build.gradle` file. I tried to isolate the problem as much as possible but please let me know if you need more info or if you have some pointers.

# Issue 1
### file1.gradle
```gradle
import com.bmuschko.gradle.docker.tasks.*

buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.bmuschko:gradle-docker-plugin:3.0.3'
  }
}

apply plugin: 'com.bmuschko.docker-remote-api'

docker {
  url = 'tcp://localhost:2376'
  certPath = file('/tmp/docker-certs-link')
}

task version(type: DockerVersion)
```
Running `gradle -b file1.gradle version` works as expected.

However, when that's not the main file, e.g.

## file2.gradle
```gradle
apply from: 'file1.gradle'
```
And then I run `gradle -b file2.gradle version` I get this error
```
> Plugin with id 'com.bmuschko.docker-remote-api' not found.
```

If I copy the `buildscript` section
## file3.gradle
```gradle
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.bmuschko:gradle-docker-plugin:3.0.3'
  }
}

apply from: 'file1.gradle'
```
And then run `gradle -b file3.gradle version` it works fine.

# Issue 2
In reality, I have more dependencies in `buildscript`
### file4.gradle
```gradle
import com.bmuschko.gradle.docker.tasks.*

buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.netflix.nebula:gradle-metrics-plugin:4.0.1'
    classpath 'com.bmuschko:gradle-docker-plugin:3.0.3'
  }
}

apply plugin: 'com.bmuschko.docker-remote-api'

docker {
  url = 'tcp://localhost:2376'
  certPath = file('/tmp/docker-certs-link')
}

task version(type: DockerVersion)
```
So running `gradle -b file4.gradle version` works fine. But if I load it from a file that has the dependencies in **different order**:

### file5.gradle
```gradle
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.bmuschko:gradle-docker-plugin:3.0.3'
    classpath 'com.netflix.nebula:gradle-metrics-plugin:4.0.1'
  }
}
apply from: 'file4.gradle'
```
And run `gradle -b file5.gradle version` I get this error:
```
> Cannot invoke method withClasspath() on null object
```

### file6.gradle
```gradle
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.netflix.nebula:gradle-metrics-plugin:4.0.1'
    classpath 'com.bmuschko:gradle-docker-plugin:3.0.3'
  }
}
apply from: 'file4.gradle'
```
If I list the dependencies in the **same order** and run `gradle -b file6.gradle version` it works as expected.

---

I'm using Gradle 3.1
```
------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Mac OS X 10.11.6 x86_64
```

**Comment by mrhaki** [comment]
You need to use the full class name to use the plugin from a build file that is not the main build file. For more details see: http://mrhaki.blogspot.nl/2015/10/gradle-goodness-apply-external-script.html

**Comment by orzeh** [comment]
@dalbertom it is a known issue, see [this](https://github.com/bmuschko/gradle-docker-plugin/issues/248#issuecomment-234098958).

@cdancy I think we should add some notes on this to README.md

**Comment by cdancy** [comment]
@orzeh while it's a gradle issue, enough people come here asking this very question. Did you want to add it in or want me to put something together?

**Comment by orzeh** [comment]
@cdancy please write something if you have time.

**Comment by dalbertom** [comment]
Thank you so much for the info! Using `apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin` instead of `apply plugin: 'com.bmuschko.docker-remote-api'` works.

**Comment by cdancy** [comment]
@orzeh on it.
