### ISSUE TITLE
Task 'pillImage' not found in root project...

### ISSUE THREAD

**Issue by daggerok** [bmuschko/gradle-docker-plugin#281]
Hello, I have next pullImage task in my build.gradle:

```groovy
import com.bmuschko.gradle.docker.tasks.image.DockerPullImage
task pullImage(type: DockerPullImage) {
    repository = "daggerok/minikube-spring-boot-docker"
    tag = "latest"
}
```
running gradle with command `gradle pullImage --debug` and have next strange error log:

```sh
...
21:16:09.393 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
21:16:09.393 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
21:16:09.393 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
21:16:09.393 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Task 'pillImage' not found in root project 'minikube-spring-boot-docker'. Some candidates are: 'buildImage', 'pullImage', 'pushImage'.
...
```

I mentioned that exception message contains strange task name **pillImage**, but not **pullImage**. I have correct task name in gradle build file, so probably there are something wrong with DSL or.. 

does anybody knows how can I fix that?
thanks!
b/r Max

**Comment by cdancy** [comment]
The only way I could see this happening was if you ran the command `gradle pillImage` instead of `docker pullImage`.

**Comment by daggerok** [comment]
seems like rebooting of workstation helps, now it's working as expected. sorry for that. can I close this thread?
