### ISSUE TITLE
double quotes in commit message

### ISSUE THREAD

**Issue by n0mer** [bmuschko/gradle-docker-plugin#282]
if Dockerfile is labeled like this:

```
    label ([
            'custom.git.commit.message.short': gitRepo.head().shortMessage,
    ])

```

and commit message contains double quotes - like this 

`Revert "Set AccessTokenValidity - x hour and RefreshTokenValidity - y days"`

then generated Dockerfile contains the following label

LABEL "custom.git.commit.message.short"="Revert "Set AccessTokenValidity - x hour and RefreshTokenValidity - y days""

docker image build fails due to this

**Comment by cdancy** [comment]
@n0mer I assume this is because the double quotes are not escaped?

**Comment by cdancy** [comment]
@n0mer closing issue. Feel free to re-open if you've not solved your issue.
