### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by develmusa** [bmuschko/gradle-docker-plugin#283]
I'd like to build a DockerImage but i always get this error:
`> org.apache.http.conn.ConnectTimeoutException: Connect to 172.0.0.1:3128 [/172.0.0.1] failed: Connection timed out`
I think this is a problem with the Docker API Url. Is there a possibility to check the Docker Api Url?

Here is my gradle file.
[build.gradle.txt](https://github.com/bmuschko/gradle-docker-plugin/files/495645/build.gradle.txt)

**Comment by cdancy** [comment]
Looks like a config issue with docker. Can you successfully hit the endpoint `/_ping` with your browser? You should get an "OK" back if your daemon is properly configured.

**Comment by develmusa** [comment]
Thanks for your reply.

When I start the deamon with  `$ sudo dockerd -D -H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock` I get the respons `INFO[0001] API listen on 127.0.0.1:2375 `. Unfortunately I can't reach the `/_ping` endpoint at this address.

**Comment by develmusa** [comment]
Now I problem is solved.

With `curl --unix-socket /var/run/docker.sock http:/_ping` i can hit the endpoint and get an "OK" back.

In my build.gradle file i changed `docker {
    url = "http://172.0.0.1:3128"
}` to `docker {
    url = 'unix:///var/run/docker.sock'
}`

Thank you!
