### ISSUE TITLE
Unhelpful exceptions upon failure

### ISSUE THREAD

**Issue by MarkRx** [bmuschko/gradle-docker-plugin#285]
Some exception conditions are not always clear. For example, the following exception occurred when attempting to build a docker image. The top level exception is a InvocationTargetException which doesn't give much information. The internal exceptions reveal the issue but these can only be seen when --stacktrace is passed in as a command line parameter

> 13:54:55 Execution failed for task ':dockerBuildApp'.
> 13:54:55 > java.lang.reflect.InvocationTargetException-->null

Here is the full stacktrace:

> 13:54:55 * Exception is:
> 13:54:55 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dockerBuildApp'.
> 13:54:55 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
> 13:54:55 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
> 13:54:55 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
> 13:54:55 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
> 13:54:55 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
> 13:54:55 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
> 13:54:55 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
> 13:54:55 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
> 13:54:55 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
> 13:54:55 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
> 13:54:55 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
> 13:54:55 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
> 13:54:55 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
> 13:54:55 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
> 13:54:55 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
> 13:54:55 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
> 13:54:55 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
> 13:54:55 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
> 13:54:55 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
> 13:54:55 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
> 13:54:55 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
> 13:54:55 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
> 13:54:55 	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
> 13:54:55 	at org.gradle.internal.Factories$1.create(Factories.java:22)
> 13:54:55 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
> 13:54:55 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
> 13:54:55 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
> 13:54:55 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
> 13:54:55 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
> 13:54:55 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
> 13:54:55 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
> 13:54:55 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
> 13:54:55 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
> 13:54:55 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
> 13:54:55 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
> 13:54:55 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
> 13:54:55 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
> 13:54:55 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
> 13:54:55 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
> 13:54:55 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
> 13:54:55 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
> 13:54:55 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
> 13:54:55 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
> 13:54:55 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
> 13:54:55 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
> 13:54:55 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
> 13:54:55 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
> 13:54:55 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
> 13:54:55 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
> 13:54:55 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
> 13:54:55 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
> 13:54:55 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
> 13:54:55 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
> 13:54:55 	at org.gradle.launcher.Main.doAction(Main.java:33)
> 13:54:55 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
> 13:54:55 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
> 13:54:55 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
> 13:54:55 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
> 13:54:55 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
> 13:54:55 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:156)
> 13:54:55 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:93)
> 13:54:55 Caused by: net.sf.cglib.proxy.UndeclaredThrowableException: java.lang.reflect.InvocationTargetException-->null
> 13:54:55 	at com.github.dockerjava.core.command.BuildImageResultCallback$$EnhancerByCGLIB$$f0c807b5.awaitImageId(<generated>)
> 13:54:55 	at com.github.dockerjava.core.command.BuildImageResultCallback$$EnhancerByCGLIB$$f0c807b5$awaitImageId.call(Unknown Source)
> 13:54:55 	at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage.runRemoteCommand(DockerBuildImage.groovy:118)
> 13:54:55 	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_closure1.doCall(AbstractDockerRemoteApiTask.groovy:57)
> 13:54:55 	at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:53)
> 13:54:55 	at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
> 13:54:55 	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:62)
> 13:54:55 	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
> 13:54:55 	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:56)
> 13:54:55 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
> 13:54:55 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
> 13:54:55 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
> 13:54:55 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
> 13:54:55 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
> 13:54:55 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
> 13:54:55 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
> 13:54:55 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
> 13:54:55 	... 60 more
> 13:54:55 Caused by: java.lang.reflect.InvocationTargetException
> 13:54:55 	at java_lang_reflect_Method$invoke.call(Unknown Source)
> 13:54:55 	at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader$_createPrintStreamProxyCallback_closure10.doCall(DockerThreadContextClassLoader.groovy:481)
> 13:54:55 	at com.sun.proxy.$Proxy72.invoke(Unknown Source)
> 13:54:55 	... 77 more
> 13:54:55 Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: lstat buid/myapp.war: no such file or directory
> 13:54:55 	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:71)
> 13:54:55 	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:48)
> 13:54:55 	... 80 more

**Comment by orzeh** [comment]
@MarkRx you didn't write which version you use, but I assume it is not the last one 3.0.3 which should fix that. Please see issue #264 and PR #265 or just use [3.0.3](https://github.com/bmuschko/gradle-docker-plugin/blob/master/RELEASE_NOTES.md#version-303-september-6-2016).

**Comment by cdancy** [comment]
@MarkRx closing issue as @orzeh has it right: we've recently implemented "better logging" for things of this nature and so I have to assume you are using an older version. Feel free to re-open if using the latest `3.0.3` does not work out for you. Thanks.

**Comment by MarkRx** [comment]
I was using 3.0.1. I will try the latest one thanks!
