### ISSUE TITLE
Ability to tag a docker build with multiple tags

### ISSUE THREAD

**Issue by MarkRx** [bmuschko/gradle-docker-plugin#286]
Docker 1.10 added the ability to tag a build with multiple tags. Doing so is convenient as it reduces the number of tasks needed in a project (for example when building and using both "latest" and "<version>" tags)

It would be nice if the plugin could support this. For docker 1.10+ it would just use the multi-tag approach. For docker < 1.10 it could run the build step then run a series of Actions afterwards that tag the image behind the scenes.

**Comment by orzeh** [comment]
I would be a nice feature. To add it we must check if `docker-java` supports this already. IMO it should work only for `docker` 1.10+, for earlier version it should throw exception.

Are you interested in submitting PR?

**Comment by orzeh** [comment]
`docker-java` doesn't support this yet. We must wait for them to implement this.
I saw you opened issue there, so we should stay tuned.

**Comment by cdancy** [comment]
@orzeh I believe knocked this out for the `docker-java` project already? Would this be an easy PR to put together to take advantage of this functionality?

**Comment by orzeh** [comment]
@cdancy yes, I'll do this after `docker-java` release
