### ISSUE TITLE
Problem with linking containers

### ISSUE THREAD

**Issue by develmusa** [bmuschko/gradle-docker-plugin#288]
When i try io link two containers together i get an Exception.

In a task with the type of "DockerCreateContainer" I set: `links =['NameOfOtherContainer']`
This leads to this exception: `java.lang.reflect.InvocationTargetException`

Do I maybe use the wrong syntax for `java.util.List<java.lang.String>`?

Thank You

**Comment by orzeh** [comment]
Can you paste full stacktarce - you can use `./gradlew -S`? There should be detailed error message. You can also upgrade to newest version, which [prints better error messages](https://github.com/bmuschko/gradle-docker-plugin/pull/265).

**Comment by develmusa** [comment]
With the help of the stacktrace it was clear that it has to be an syntax error.

> Caused by: java.lang.IllegalArgumentException: Error parsing Link 'containerName'

I'm not able to read the code so I used trial and error.
Now it is working with this syntax: `links =["containerName:imageName"]`

Thank You
