### ISSUE TITLE
Is it possible to start an image form the registry?

### ISSUE THREAD

**Issue by develmusa** [bmuschko/gradle-docker-plugin#289]
I'm trying to start an Image from the registry. After pulling the image from the registry with `DockerPullImage` i'm not able to get an `ImageId` of this Image. => I can't use `DockerCreateContainer` because it needs the `targetImageId`.

At the moment I create a Dockerfile with the `from 'wantedImage'` attribute and build an new DockerImage to get the `ImageId`.

Thank You

**Comment by orzeh** [comment]
You can use image name and tag as a `targetImageId` value, ie.:

````groovy
task createSampleContainer(type: DockerCreateContainer) {
    containerName = 'myContainerName'
    targetImageId { "my.private.registry:5000/my-repository/my-image:1.0.0" }
    //...
}
````

This will pull image from registry if it is not present automatically, so you do not need dedicated pull task.

**Comment by develmusa** [comment]
thank you very much
