### ISSUE TITLE
Add commands to build using docker-java-application

### ISSUE THREAD

**Issue by wwadge** [bmuschko/gradle-docker-plugin#290]
I want to use java:8-jre-alpine as a base image which does not contain bash and thus causes spring boot applications to fail to load. I need to add a line in the generated build file: 

```apk update && apk add bash```

but there doesn't seem to be a way to do this via the docker-java-application plugin.

Can you support adding arbitary commands eg: runCommand(...) to be appended to the generated build files?

**Comment by orzeh** [comment]
@wwadge `docker-java-application` is a _is a highly opinonated plugin_ so it supports certain workflow. However to solve your problem you can use just Gradle features.

`docker-java-application` adds task `dockerDistTar` of type [Dockerfile](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy). You can find it in the task graph and then add instructions you need - use [instruction()](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L67) method. Eg.:

````groovy
tasks.whenTaskAdded { task ->
    if(task instanceof Dockerfile) {
        task.instruction('RUN apk update && apk add bash')
    }
}
````

Please note that I didn't test this :-)

**Comment by wwadge** [comment]
Thanks, I tried it but it didn't work I'm afraid :(

**Comment by cdancy** [comment]
@wwadge do you have a stacktrace that we can look at as well as a snippet of what you're doing? There may be a "better" way of going about things.

**Comment by cdancy** [comment]
@wwadge closing this for now. Feels like you might be better off using the gradle tasks to accomplish what you need. Feel free to re-open if need be.
