### ISSUE TITLE
what is a repository

### ISSUE THREAD

**Issue by enricoag1982** [bmuschko/gradle-docker-plugin#291]
Hi,

I'm trying to use the https://github.com/bmuschko/gradle-docker-plugin
in a project and I'm stuck at the pull image request.

I deployed an image to a repository and I would like to retrieve it and then run it locally.

...
task pullImage(type: DockerPullImage){
    tag "$registryHost/$systemTestImageName:${imageTag}"
    repository ???
}

task createContainer(type: DockerCreateContainer) {
    dependsOn pullImage
    finalizedBy "removeContainer"
    targetImageId { pullImage.getImageId() }
}
...

but I don't know what should be added in repository property and can't find any doc about it.

Could you please help me out?
thanks,
Enrico

**Comment by cdancy** [comment]
@enricoag1982 the `repository` is EVERYTHING before the `tag`. You mght do something like this:

```
task pullImage(type: DockerPullImage){
    repository = "$registryHost/$systemTestImageName"
    tag "${imageTag}"
}
```

The `tag`, in docker terms, can be thought of as the version of the image. Let me know if that helps.
