### ISSUE TITLE
Clarification on the meaning of tag

### ISSUE THREAD

**Issue by ianpojman** [bmuschko/gradle-docker-plugin#294]
After a lot of (continued) struggle to get a docker java application published to a private registry, I found the only thing that actually got it working (on certain versions of docker) was embedding the hostname in the "tag", i.e.:

    docker {
        url = getProperty("docker.build.host")
        registryCredentials {
            url = getProperty('docker.registry') }
        }

        javaApplication {
            baseImage = getProperty("docker.registry") + 'baseimage:2.0'
            maintainer = "..."
            ports = [80,8080]
            
            // dockerPushImage doesn't work, even with registryCredentials.url set
            //        tag = "1.0"

            // dockerPushImage seems to work with this, but can't tag with version number at end on docker 1.9, works on docker 1.12
            tag = getProperty("docker.registry") +"blah/myapp" // ":" + version
        }
    } 

My main question here is one of terminology.

If I want to push a docker image "docker.mycompany.com:me/myapp:1.0" to my repo, isn't the "tag" in this case "1.0"?  

Is the use of the "tag" in the docker.javaApplication configuration block equivalent to the docker concept of a tag?

Side question: how do i install a modified copy of the project in a local maven repo to test changes for a PR? I was trying with gradle publish (et al) and the artifacts didn't seem to get built and copied to maven local. What's the local development process like if I want to install a modified version of the plugin for investigation purposes? I was thinking of adding "quiet" logging in a lot of places to better understand things, since debugging isn't always ideal.

**Comment by cdancy** [comment]
I've pasted a snippet below of what I use and know works. You would of course variableize things to make a bit more saner but it serves as a good example and one you can model your own code after.

The `java-application` plugin will use this behind the scenes anyway so it should work in the same way.

```
docker {
    registryCredentials {
        url = "https://some.amazon.registry.io"
        username = registryUsername
        password = registryPassword
        email = 'MyEmail.com'
    }
}

task buildImage(type: com.bmuschko.gradle.docker.tasks.image.DockerBuildImage) {
    noCache = true
    inputDir = projectDir
    tag = "some.amazon.registry.io/my-image-name:0.0.1"
}

task pushImage(type: com.bmuschko.gradle.docker.tasks.image.DockerPushImage, dependsOn: buildImage) {
    imageName = "some.amazon.registry.io/my-image-name"
    tag = "0.0.1"
}
```

**Comment by cdancy** [comment]
@ianpojman on the point of terminology: I actually agree with you. However, and because we are leveraging the `docker-java` library behind the scenes, we follow the semantics set by them and are ultimately providing a high-level wrapper around that library.

**Comment by ianpojman** [comment]
That explains a lot. Thanks so much

**Comment by cdancy** [comment]
np.
