### ISSUE TITLE
Please add possibility provide volumes on build time

### ISSUE THREAD

**Issue by Hubbitus** [bmuschko/gradle-docker-plugin#296]
According to https://github.com/docker/docker/issues/14080#issuecomment-255120452 there several implementation allow work constructions like `-v $(pwd):/target` on `docker build` stage.

Could you please add into plugin?

It will be very useful place build artifacts from other `gradle` stages into image without create blow layers and without much of hacks like squashing after build.

**Comment by orzeh** [comment]
@Hubbitus As far as I understand that thread, the  `-v` option during `docker build` is available only in custom versions of Docker engine. I don't think we should support them. But even if we do, this feature must be first implemented in [docker-java](https://github.com/docker-java/docker-java/) library which this plugin uses underneath.

I'm closing this now. Please reopen when this feature will be in official Docker engine release.

**Comment by Hubbitus** [comment]
Talks about inclusion into upstream is not ended yet. But for now it present in all Fedora, Centos, Rhel distros by default. And also in some public services like drone.io if I understand correctly. So it is not so small…

Ok, thanks, I'll copy such request into `docker-java` library.
