### ISSUE TITLE
Set Container to remove after run

### ISSUE THREAD

**Issue by dgutierrez1287** [bmuschko/gradle-docker-plugin#297]
I didn't see is an option for the DockerCreateContainer type but it would be good to add in the option to auto cleanup the container (i.e docker run --rm=true). I use build containers with my projects and this would be useful for that use case and other docker tasks.

**Comment by cdancy** [comment]
@dgutierrez1287 I think the `--rm` option is a function of the command line client and not part of the [create container api](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-container). If there is something I'm missing, or you see something I don't, feel free to chime in.

**Comment by dgutierrez1287** [comment]
ah yeah i dont see it in the remote api either, sorry about that. ill go with my work around to chain a create start wait and remove together.
