### ISSUE TITLE
Does build-arg parameter allowed while building docker image using this plugin?

### ISSUE THREAD

**Issue by borntorock** [bmuschko/gradle-docker-plugin#298]
@bmuschko @double16 @cdancy Do we have the feature of mentioning the build-arg parameter while building docker image using this plugin? If yes, then can you Please let me know the keyword to be used for this.

**Comment by orzeh** [comment]
@borntorock  it was released in version 3.0.2. See [this PR](https://github.com/bmuschko/gradle-docker-plugin/pull/240) for details.
