### ISSUE TITLE
Missing method to specify port bindings for DockerCreateContainer

### ISSUE THREAD

**Issue by jtgasper3** [bmuschko/gradle-docker-plugin#30]
Hopefully I'm just very dense but after struggling for a while and looking through code, I don't the proper way to map local port 1443 to exposed port 443. The API [1] references:

> PortBindings - A map of exposed container ports and the host port they should map to. It should be specified in the form `{ <port>/<protocol>: [{ "HostPort": "<port>" }] } `Take note that port is specified as a string and not an integer value.

The DockerCreateContainer class[2] doesn't reference this property. *Is portSpecs support to fill this role?*

Thanks for the consideration, and thanks for sharing your plugin.

[1] http://docs.docker.com/reference/api/docker_remote_api_v1.17/
[2] https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy

**Comment by bmuschko** [comment]
You are referencing two different tasks: `DockerCreateContainer` and `DockerStartContainer`. Which one are you referring to? 

At least for `DockerCreateContainer` you can use the property [portSpecs](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy#L31). A good way to find out what properties are exposed is to check the GroovyDocs for each custom task class from the [README.asciidoc](https://github.com/bmuschko/gradle-docker-plugin/blob/master/README.asciidoc) file. 

`DockerStartContainer` doesn't have this property yet. If it is missing at the moment, then we'd need to add it. The fastest way to get it started would be a pull request.

**Comment by jtgasper3** [comment]
Sorry, bad cutting and pasting on my part with too many browser tabs open. I believe it should be on the create. I'll clean up the request to properly reflect the issue. I'll try to get a PR put together.

**Comment by jtgasper3** [comment]
How is portSpecs supposed to work? There is no mention of it in the Docker Remote API, at least not latter versions? I also found old references to it in the docker-java library, but they seem to be very old and not in later versions.

I've attempted to use it "1443:443" and it does not give the desired mapping when running `docker ps`.

**Comment by bmuschko** [comment]
To be honest, I am not sure. I am basically just calling off to the Docker Java library. I think it would be best to ask the question on their project page.

**Comment by jtgasper3** [comment]
I've played with it for a while and it seems like the version of the library you are wrapping is old. Unfortunately I don't have time to play with it more.

**Comment by bmuschko** [comment]
The latest release of Docker Java is 0.10.5. That's what the latest plugin version is using. You probably had a look at their master branch which is shows their current development.

**Comment by jtgasper3** [comment]
You are probably right. I'm not sure why it wouldn't accept the portBindings addition.

I think I was also going to have an issue when using the hostConfig->Link property (`docker run --link` equivalent).

**Comment by coco1979ka** [comment]
Actually the port bindings have to be created in the DockerStartContainer task. I am also waiting for this feature. I want to run functional tests against a running container, therefore I need the ability to publish the ports.
@bmuschko are you going to solve this issue? Looking at https://github.com/docker-java/docker-java/wiki there is an example how to use port bindings.

**Comment by bmuschko** [comment]
@coco1979ka It's going to be added eventually. You can speed up the process by providing a pull request.

**Comment by coco1979ka** [comment]
@bmuschko I have already cloned the sources and tried to start working on this feature. But I need some time to understand the architecture. I'm not a plugin specialist, so first thing I was confused about is, why there is no dependency to the docker java api. This makes it very hard to work with the model classes of the api (e.g. PortBinding).

**Comment by bmuschko** [comment]
@coco1979ka The dependencies are automatically resolved by [DockerRemoteApiPlugin](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy#L57). The reason is classloader isolation. Docker Java pulls in a lot of transitive (and from my perspective undesirable) transitive dependencies that users of the plugin will not want which has certain implications. To avoid classloading issues for users of the plugin, we load the classes via a thread context classloader.
