### ISSUE TITLE
Does dependency loading have to be dynamic ? 

### ISSUE THREAD

**Issue by hsyed** [bmuschko/gradle-docker-plugin#300]
I'm building a DSL/Pipeline on top of the logic in this plugin to encode the dozens of base / service image types we using in our cluster so that they are all layered on top of a single base image hierarchy -- in a maintainable way -- i.e., changing alpine version from 3.4 to 3.5 should rebuild every image, changing the JDK version should rebuild all the JDK images etc etc.

Intelij is not aware of the underlying dependencies. I tried to get the external dependency manually and cast the object I need to the correct class (DockerClientImpl or DockerClient) but of course I can't must be a different class loader ?. I assume `com.github.dockerjava` are loaded dynamically and this is causing the problem ? Is there a way arround this ?

**Comment by orzeh** [comment]
Try to look at this [issue](https://github.com/bmuschko/gradle-docker-plugin/issues/198). Hope it helps you.

**Comment by cdancy** [comment]
@hsyed if you're just looking for the dependencies of `dockerjava` you can do so by asking gradle to print out the dependencies for a given configuration. [Here is a good article](https://solidsoft.wordpress.com/2014/11/13/gradle-tricks-display-dependencies-for-all-subprojects-in-multi-project-build/) describing how to do so.

**Comment by cdancy** [comment]
@hsyed closing issue. If you want to talk about things further feel free to re-open.
