### ISSUE TITLE
Possibility to ignore host SSL verification?

### ISSUE THREAD

**Issue by samized** [bmuschko/gradle-docker-plugin#301]
Hi, thanks for this plugin, it's a huge help to get things done.

Depending on our infrastructure, I need the possibility to ignore server certificate verification.
Because I have multiple docker hosts with all the same "dummy" SSL docker certificates the CN cannot be checked correctly by client.

Having this setup works great for all clients with a certificate signed by the same CA and calling docker with:
`$ docker --tls ps`

This plugin has the possibility to set DOCKER_CERT_PATH but there is no option to disable server verification. Now I got following error:
`javax.net.ssl.SSLPeerUnverifiedException: Host name '10.0.0.74' does not match the certificate subject provided by the peer (CN=*.xyz.ch)`

Is it possible to achieve this somehow?

**Comment by cdancy** [comment]
@samized this is a bit more complicated than you may realize and has all sorts of implications. That being said: this plugin does not support any sort of disabling of ssl checks. We simply build the request and pass that along to `docker-java` which runs the actual request. I would create an issue with them to see if they will expose anything for you or have any better ideas.
