### ISSUE TITLE
DockerJavaApplicationPlugin and CMD instead of ENTRYPOINT

### ISSUE THREAD

**Issue by ianpojman** [bmuschko/gradle-docker-plugin#306]
I have a requirement to generate docker images which use a default command instead of an ENTRYPOINT, as our containers are started with explicit commands in our production environment.

I worked around this by tweaking the default task like so:

```
    dockerDistTar.instructions.removeAll { it instanceof Dockerfile.EntryPointInstruction }
    dockerDistTar {
        String installDir = distTar.archiveName - ".${distTar.extension}"
        defaultCommand "/$installDir/bin/$project.applicationName"
    }

```

Would a PR to add support for this be considered? Perhaps something like adding a new flag to DockerJavaApplication?

```
docker { 
    javaApplication {
          useDefaultCommandInsteadOfEntryPoint = true
    } 
}
```

Or is there another suggested way to do this?

**Comment by orzeh** [comment]
I think I understand your use case and I agree that using a flag in configuration is a good idea. However, I think `useEntrypoint` with default value `true` is a better name. @cdancy any thoughts?

Please provide PR and we will discuss it further.

**Comment by cdancy** [comment]
Closing as I believe #359, which made it into our new `3.0.7` release, solves this problem.
