### ISSUE TITLE
Building docker image hangs on windows

### ISSUE THREAD

**Issue by jbaranski** [bmuschko/gradle-docker-plugin#308]
Running the command `docker build .` on its own works fine in the same console session.

I tried to provide as much info I can below, can anyone help or see any issue here?

Windows 7
Gradle 2.14
Java JDK 8
gradle-docker-plugin 3.0.4
Docker Toolbox Info:
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

My build script looks like this:
```
...
...
apply plugin: "com.bmuschko.docker-remote-api"
import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
...
...
task createDockerfile(type: Dockerfile) {
    destFile = project.file("Dockerfile")
    from "debian:jessie"
}

task buildDockerImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    inputDir = createDockerfile.destFile.parentFile
}
```

The output from gradle stops here (where it hangs)
```
10:23:43.245 [INFO] [org.glassfish.jersey.internal.ServiceFinder] Running in a n
on-OSGi environment
10:23:43.405 [QUIET] [org.gradle.api.Task] Building image using context 'C:\dev\'.
10:23:43.518 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManag
er] Connection manager is shutting down
10:23:43.519 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnecti
on] http-outgoing-1: Close connection
10:23:43.519 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnecti
on] http-outgoing-1: Close connection
10:23:43.519 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManag
er] Connection manager shut down
10:23:50.284 [INFO] [org.glassfish.jersey.process.internal.ExecutorProviders] Se
lected ExecutorServiceProvider implementation [org.glassfish.jersey.client.Defau
ltClientAsyncExecutorProvider] to be used for injection of executor qualified by
 [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
```

**Comment by cdancy** [comment]
Is this being run with `--stacktrace`? Can you change your `DockerBuildImage` task to the below? This is what I use and works for me (similar setup to yours).

```
task buildDockerImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    noCache = true
    inputDir = projectDir
    tag = 'some-host/some-image-name:1.0'
}
```

**Comment by jbaranski** [comment]
@cdancy 

Same issue with your task.

It is being run with --stacktrace and --info, but it hangs, it never actually errors out, I waited upwards of 15 minutes on a couple occasions, but running the command directly (docker build .)  takes less than 1 minute.

I think something on my system path is messed up for the way the plugin invokes the docker executable, I have to run `docker-machine env --shell cmd default` each time I open a shell and then paste that output back into the shell for docker to recognize the docker server.

Since your environment is similar do you have to do the same thing?

**Comment by orzeh** [comment]
@jbaranski  how do you configure connection to docker in build file? Can you paste `docker {...}` fragment?

**Comment by jbaranski** [comment]
I didn't have anything, now I filled it in, same result, I tried different combinations as well.... This based on the docs should work fine though.

```
docker {
    url = 'http://192.168.99.100:2376'
}
```

**Comment by cdancy** [comment]
Definitely looks to be a connection issue. Can you connect to the url `http://192.168.99.100:2376/_ping` in your browser? If successful you should get literally the message `OK` handed back, if not then _something_ is not setup correctly.

**Comment by jbaranski** [comment]
The result of that url is me downloading a binary file, not sure what it is though.

Alright let me investigate this a little more, since I didn't get any OK message, will let you know if I can get this resolved. Thanks for the tips.

**Comment by orzeh** [comment]
@jbaranski you docker daemon is TLS enabled so you have to configure certificate paths. Try this:
````gradle
docker {
    url = 'https://192.168.99.100:2376'
    certPath = new File("C:\\Users\\jbaranski\\.docker\\machine\\certs")
}
````

**Comment by jbaranski** [comment]
Tried that and also the path <home>.docker/machine/machines/default -- something is up but like you guys said most likely some bad connection issue, will try to get that ping request to work first then come back around to this, to eliminate that step from this. Thank you both.

**Comment by cdancy** [comment]
@orzeh is right in that if the connection is not public, meaning TLS is enabled, then you will need to pass in the `certPath` wherever that might be.

**Comment by cdancy** [comment]
@jbaranski closing issue for now. If you feel further discussion is necessary feel free to re-open.
