### ISSUE TITLE
Defaulting to correct docker URL for all platforms

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#310]
Currently we default to `http://localhost:2375` when connecting to docker. Think we should change this to `unix:///var/run/docker.sock` for all non-windows based systems and for windows based systems default to `npipe:////./ppe/docker_engine` (windows 10 equivalent). This allows folks to use their local docker OOTB without having to configure anything.

@orzeh @bmuschko thoughts?

**Comment by eshepelyuk** [comment]
FYI, `Docker for Windows` couldn't be installed on all versions of `Windows 10`. As far as I understand - `npipe://` is related to `Docker for Windows` product.
So it could be good if plugin can detected this and fall back to using `DOCKER_HOST` env variable, in case of `Docker Toolbox` product.

**Comment by cdancy** [comment]
@eshepelyuk absolutely agree. The impl, from my POV, would look something like:

```
if (env.DOCKER_HOST)
    url = env.DOCKER_HOST
else
    if non-windows-host
        url = `unix:///var/run/docker.sock`
    else
        if windows 10
            url = `npipe:////./ppe/docker_engine`
        else
            url = `http://localhost:2375` // best guess scenario
```

**Comment by eshepelyuk** [comment]
Once again, I have `Windows 10` and I can't install `Docker for Windows` there.
As many others laptop owners with non stadard `Windows 10` editions.
So we are forced to use `Docker Toolbox`.
Thus, your pseudo code will not work.

**Comment by cdancy** [comment]
@eshepelyuk yeah I think you need windows 10 pro or something along those lines. I've amended the pseudo-code above.

**Comment by gesellix** [comment]
@eshepelyuk do you have installed all patches?

**Comment by gesellix** [comment]
@cdancy shouldn't Docker Toolbox set the `DOCKER_HOST` env variable?

So, the default should always fallback to `unix://` or `npipe://`, but prefer `DOCKER_HOST`, if set.

**Comment by cdancy** [comment]
@gesellix honestly I have no idea as I don't own any windows machines. But if that's true then the above code snippet should cover that use-case?

**Comment by eshepelyuk** [comment]
Fall back _must be_ set to `DOCKER_HOST`. 
`http://localhost:2375` is some sort of meaningless legacy.

**Comment by cdancy** [comment]
@eshepelyuk I wouldn't say meaningless. It IS the URL for the local, non-tls, enalbed docker daemon. It's also possible the DOCKER_HOST environment variable is not set.

**Comment by gesellix** [comment]
> But if that's true then the above code snippet should cover that use-case?

yes, the last `else` won't hurt, but I wanted to stress the assumption that it won't ever be used in real life.

**Comment by eshepelyuk** [comment]
As far as I understand, docker clients are not using `http://` or `https://` URL to connect to daemon.
Instead `tcp://` should be used, as described https://docs.docker.com/engine/reference/commandline/dockerd/.

Even this plugin replaces `http://` to `tcp://` before passing daemon host to docker-java library.
Docker client or docker-java library will just fail if URL will not start from `tcp://`

**Comment by cdancy** [comment]
@eshepelyuk aaahhhh yes on that you're right. I'll amend the above.

**Comment by cdancy** [comment]
Opened PR #313 for initial implementation on this. Any thoughts/comments/concerns would be welcome!

**Comment by orzeh** [comment]
The implementation looks OK, but maybe we should combine it somehow with #237 and #250 ?

**Comment by cdancy** [comment]
Closing issue as functionality has been merged.
