### ISSUE TITLE
DockerCreateContainer ignores containerName

### ISSUE THREAD

**Issue by samized** [bmuschko/gradle-docker-plugin#314]
Hi, thanks for this plugin, it's really helpful so far

But using `DockerCreateContainer` with the property containerName does not work as expected for me
My example task looks like this (busybox is already in docker images)
```
task createExampleContainer(type: DockerCreateContainer) {
    containerName = "my_busybox"
    targetImageId { "busybox" }
}
```
Looking into `docker ps -a` shows that this container got a random name by docker
```
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                                                                     NAMES
67235b6c66b1        busybox                          "sh"                     13 hours ago        Created                                                                                       boring_ptolemy
```

I am using the latest version of this plugin. (3.0.4)

**Comment by orzeh** [comment]
But did you actually _start_ the container?

**Comment by orzeh** [comment]
@samized  I'm unable to reproduce your issue in my environment.

Could you please provide some details: build script, build log, `docker ps -a` output after build?

**Comment by samized** [comment]
Ok, I found the problem, really annoying...
For debug reasons, I defined a variable `containerName` globally like this:
```
def containerName = "blabla"

task createExampleContainer(type: DockerCreateContainer) {
    containerName = "my_busybox"
    targetImageId { "busybox" }
}

task startExampleContainer(type: DockerStartContainer){
    dependsOn createExampleContainer
    targetContainerId {createExampleContainer.getContainerId()}
}
```

Sorry for this beginner's mistake. Thanks for your help anyway ;)

**Comment by cdancy** [comment]
Aaaaahhhhh the joys of groovy and meta programming. It's greatest strength is also its greatest weakness. Something you have to learn to love ;)
