### ISSUE TITLE
Connect,  Read and Completion Timeouts

### ISSUE THREAD

**Issue by blongstreth** [bmuschko/gradle-docker-plugin#315]
Hello:

I am playing around with various tasks and docker-java commands in order to better understand how things timeout when the connection is pulled, unavailable, etc.  In short, many commands will hang indefinitely which is problematic.  As a result, I am finding the need to have better default read, connect and result callback timeouts as well as the ability to tune them on a per command (task) basis.  If I am not mistaken, the following items are what I am finding should be used/tuned:

ResultCallbackTemplate.awaitCompletion(timeout, unit),
BuildImageResultCallback .awaitImageId 
JerseyDockerCmdExecFactory withReadTimeout
JerseyDockerCmdExecFactory withConnectTimeout
Etc.

As  a quick suggestion, maybe AbstractDockerRemoteApiTask could have some input properties like: readTimeout, connectTime and completion/resultCallbackTimeout, etc.  Also, the global 'docker' DSL could have a set of these values as well for the defaults. Then, each task can update dockerClient instance appropriately.

Another suggestion (or two) would be to have AbstractDockerRemoteApiTask have a dockerClient property and configuration closure.  Then each task could customize the dockerClient before the action is executed.  Also, a generic task (GenericDockerRemoteApiTask) could be created for those who want to work with docker-java API directly (instead of extending AbstractDockerRemoteApiTask class).

Outside of hacking and extending task classes, etc. would anyone have time to investigate an approach and provide support please?

**Comment by blongstreth** [comment]
The following some code snippets show I am attempting to configure the docker client read/write timeouts.  Please note the code is not complete and may have some bugs.

```
import java.util.concurrent.TimeUnit
import com.bmuschko.gradle.docker.tasks.*
import com.bmuschko.gradle.docker.tasks.container.*
import com.bmuschko.gradle.docker.tasks.image.*

ext {
    docker = [:]
    docker.defautReadTimeout = TimeUnit.MINUTES.toMillis(5)
    docker.defautConnectTimeout = TimeUnit.MINUTES.toMillis(1)
}

/**
 * Hack AbstractDockerRemoteApiTask so that read and connect timeouts can be applied to the docker client
 */
def applyDockerClientTimeouts(dockerClient, Long readTimeout, Long connectTimeout) {
    def contextClassLoader = Thread.currentThread().contextClassLoader
    def dockerClientBuilderClass = contextClassLoader.loadClass('com.github.dockerjava.core.DockerClientBuilder')
    def method = dockerClientBuilderClass.getMethod('getDefaultDockerCmdExecFactory')
    def factory = method.invoke(null)

    if (readTimeout != null) {
        factory.withReadTimeout(readTimeout.intValue())
    }
    if (connectTimeout != null) {
        factory.withConnectTimeout(connectTimeout.intValue())
    }

    dockerClient.withDockerCmdExecFactory(factory)
    return dockerClient
}

project.tasks.withType(AbstractDockerRemoteApiTask) { task ->
    // override runCommand so that the docker client can be configured before task execution
    def oldRunRemoteCommand = task.&runRemoteCommand
    task.metaClass.runRemoteCommand = { dockerClient ->
        // apply custom read and connect timeouts to the docker client
        def readTimeout = task.hasProperty('readTimeout') ? task.readTimeout : project.ext.docker.defautReadTimeout
        def connectTimeout = task.hasProperty('connectTimeout') ? task.connectTimeout : project.ext.docker.defautConnectTimeout
        applyDockerClientTimeouts(dockerClient, readTimeout, connectTimeout)

        // execute delegate
        println "runRemoteCommand with readTimeout: ${readTimeout}, ${connectTimeout}"
        oldRunRemoteCommand(dockerClient)
    }
}

//example
task dockerExecFooCmdContainer(type: DockerExecContainer, dependsOn: ['blah']) {
    targetContainerId { dockerCreateContainer.getContainerId() }
    cmd = ['/bin/bash', '/entrypoint.sh']

    ext.readTimeout = TimeUnit.MINUTES.toMillis(30)
}
```

**Comment by orzeh** [comment]
@blongstreth it sounds like a reasonable idea.
I think we should start with ability to define connect and read timeouts globally in `docker {}` configuration block. It could look like:
````groovy
docker {
    url = 'https://192.168.59.103:2376'
    certPath = new File(System.properties['user.home'], '.boot2docker/certs/boot2docker-vm')
    connection {
        connectTimeout = 5000 //in ms
        readTimeout = 5 * 60 * 1000
    }
}
````
Then we can choose tasks that await completion and implement `timeout` property on them.
@cdancy any thoughts?

@blongstreth are you interested in submitting PR with this?

**Comment by cdancy** [comment]
Sounds like a good idea to me for folks that need it. However, I think the docker-java project allows you to set either system properties or environment variable for various things to tweak, thought these were among them.

If not feel free to send in a PR.

**Comment by cdancy** [comment]
Closing as there isn't a pressing need to have this and I've not seen a PR come this way. Feel free to re-open if you want to further discuss.
