### ISSUE TITLE
access host port number from DockerCreateContainer

### ISSUE THREAD

**Issue by akki1306** [bmuschko/gradle-docker-plugin#316]
Is there a way to access host port number that is mapped to the exposed port in the container using the DockerCreateContainer?

**Comment by orzeh** [comment]
You have to use `DockerInspectContainer`

**Comment by akki1306** [comment]
This is the output of DockerInspectContainer that I get

Image ID    : sha256:a4c94f899481afbfc1c4306f4c99a97bd10768ba1f428fa8cb5e3b62a2979696
Name        : /fervent_leavitt
Links       : []
Volumes     : []
VolumesFrom : []
ExposedPorts : [8080/tcp, 9990/tcp]
LogConfig : json-file
RestartPolicy : no
Devices : []
:removeContainer
Removing container with ID 'cfa5b535052d4d7a4d704b2e2b5cf575ecf08cd5bbafdd64015f955ef1f4234a'.

To access the docker host port using command line, I am using the following command: 

docker inspect --format='{{(index (index .NetworkSettings.Ports "8080/tcp") 0).HostPort}}' $CONTAINER_ID

Currently I do not see the NetworkSettings property in the DockerInspectContainer output. Please guide.

**Comment by orzeh** [comment]
Ohh I've forgot that `DockerInspectContainer` doesn't print all information.

You have two options:

1. implement your own [ResponseHandler](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/response/ResponseHandler.groovy) like [InspectContainerResponseHandler](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/response/container/InspectContainerResponseHandler.groovy) (which might be not very convenient) and use it in `DockerInspectContainer` using `setResponseHandler` method 
2. wait until #307 is merged and then use `onNext` like in [this](https://github.com/bmuschko/gradle-docker-plugin/pull/307/files#diff-b64b88abb09cf2a573dc856fd411d52cR287) test where you have all information from Docker

**Comment by cdancy** [comment]
@akki1306 I would wait, assuming you can, until early next week for option #2 that @orzeh. We're finishing up work on that now and I plan to do a new release by the end of this weekend.

**Comment by cdancy** [comment]
Closing this ISSUE as all tasks are now "reactive" and thus you should be able to get the expected functionality from `DockerInspectContainer` using `onNext` closure.
