### ISSUE TITLE
Expose a port to random port on host

### ISSUE THREAD

**Issue by akki1306** [bmuschko/gradle-docker-plugin#317]
I am trying to expose a port in the container to random available port on the host the following way
````
task createContainer(type: DockerCreateContainer) {
    dependsOn buildImage
    targetImageId { buildImage.getImageId() }
    exposePorts("tcp", [8080])
}
````
docker inspect output for this container returns null for property NetworkSettings.Ports. This property contains the HostPort property. If I start docker container normally using command line and use this command given below, I get the HostPort property correctly. I tried to create a ResponseHandler and passed it to DockerInspectContainer. But NetworkSettings.Ports property is null in the object received in handle method. Please suggest. 
````bash
docker inspect --format='{{(index (index .NetworkSettings.Ports "8080/tcp") 0).HostPort}}' CONTAINER_ID
````

**Comment by orzeh** [comment]
`exposePorts` in your task works the same as `EXPOSE` instruction from Dockerfile. Quoting [the docs](https://docs.docker.com/engine/reference/builder/#/expose):

> `EXPOSE` does not make the ports of the container accessible to the host. To do that, you must use either the -p flag to publish a range of ports or the -P flag to publish all of the exposed ports

So to map that port to host, you have to set `portBindings` or `publishAll` property:
````groovy
task createContainer(type: DockerCreateContainer) {
    dependsOn buildImage
    targetImageId { buildImage.getImageId() }
    exposePorts("tcp", [8080])
    publishAll = true
    //portBindings = ["8080:8080"]
}
````

BTW why did you open another issue instead of continuing #316 ?

**Comment by cdancy** [comment]
@orzeh has it right. @akki1306 the way you are using the option is correct. If you want a random port assigned, that is already in use within the container, you can use the snippet that @orzeh commented out above like so:

```
portBindings = [":8080"]
```

Omitting the left-side port tells docker to assign something at random. Hope that helps.
