### ISSUE TITLE
Pushing multiple tags

### ISSUE THREAD

**Issue by ben-gineer** [bmuschko/gradle-docker-plugin#318]
What's the correct procedure for building and pushing multiple tags on the same image? Currently we're using:

```
task buildImage(type: DockerBuildImage) {
        dockerFile = project.file("$buildDir/Dockerfile")
        inputDir = projectDir
        noCache = true
        tag = "${cdImageName}:${timestampTag}"
    }

    task tagLatestImage(type: DockerTagImage) {
        dependsOn 'buildImage'
        force = true
        repository = cdImageName
        targetImageId { buildImage.getImageId() }
        tag = latestTag
    }

 task pushLatestImage(type: DockerPushImage) {
        imageName = cdImageName
        tag = latestTag
    }

    task pushImage(type: DockerPushImage, dependsOn: 'pushLatestImage') {
        imageName = cdImageName
        tag = timestampTag
    }
```

I don't see any other way to create multiple tags on the same task.

**Comment by orzeh** [comment]
@ben-gineer this is the only way until now, I'm afraid. `docker-java` does not support this yet. We have an open issue here (#286) and on their side there is [another one](https://github.com/docker-java/docker-java/issues/720). I've made a [PR that fixed it](https://github.com/docker-java/docker-java/pull/739) but it is not merged yet.

I'm closing this, please track the other issue here for changes.
