### ISSUE TITLE
Container volumes fail

### ISSUE THREAD

**Issue by Hubbitus** [bmuschko/gradle-docker-plugin#320]
I've try start container using Systemd and it is require pass /sys/fs/cgroup volume to it, I do:

```gradle
task createEgaisappContainer(type: DockerCreateContainer, dependsOn: startEgaisdbContainer) {
    targetImageId { buildEgaisappImage.getImageId() }
    containerName "egaisapp_auto_${buildEgaisappImage.buildTagName}"
    portBindings = ['8080:8080']
    volumes = ['/sys/fs/cgroup:/sys/fs/cgroup']
}
```
But got fail:
```
{"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:359: container init caused \\\\\\\"rootfs_linux.go:54: mounting \\\\\\\\\\\\\\\"/var/lib/docker/volumes/8e225358434652235260baf1f55c5e07e5ec0abb221b0f7ab71381c126020513/_data\\\\\\\\\\\\\\\" to rootfs \\\\\\\\\\\\\\\"/var/lib/docker/btrfs/subvolumes/43e4b482e69323b79881bf47802438fcf2e75d8cef990f407e6d3105963e66d9\\\\\\\\\\\\\\\" at \\\\\\\\\\\\\\\"/var/lib/docker/btrfs/subvolumes/43e4b482e69323b79881bf47802438fcf2e75d8cef990f407e6d3105963e66d9/sys/fs/cgroup:/sys/fs/cgroup\\\\\\\\\\\\\\\" caused \\\\\\\\\\\\\\\"mkdir /var/lib/docker/btrfs/subvolumes/43e4b482e69323b79881bf47802438fcf2e75d8cef990f407e6d3105963e66d9/sys/fs/cgroup:: read-only file system\\\\\\\\\\\\\\\"\\\\\\\"\\\"\\n\""}

```

**Comment by cdancy** [comment]
Sounds like a container issue in general and less to do with this plugin specifically.

Can you confirm things work when using an ordinary directory say from your home folder?

**Comment by Hubbitus** [comment]
If I run container manually with `-v /sys/fs/cgroup:/sys/fs/cgroup` it works. Should be there another syntax?

**Comment by Hubbitus** [comment]
```
    volumes = [ '/usr:/some' ]
```
works

**Comment by cdancy** [comment]
What OS are you on, what version of the plugin are you using, and what version of docker do you have?

**Comment by Hubbitus** [comment]
Fedora Linux 25. 
classpath 'com.bmuschko:gradle-docker-plugin:3.0.5'
$ docker --version
Docker version 1.12.5, build 079fbe3/1.12.5

You may reproduce it on image: https://hub.docker.com/r/taskdata/docker-centos-7-systemd-tomcat/

**Comment by Hubbitus** [comment]
Off course it is read-only filesystem, but provide it like: ''/sys/fs/cgroup:/sys/fs/cgroup:ro'' does not help unfortunately.

**Comment by cdancy** [comment]
@Hubbitus hmmm .... might be this is an issue with btrfs? This is definitely not a plugin issue as we are just forwarding the request to docker-java who in turn forwards the request to docker. Have you tried on a different distribution? Might be that fedoras setup is slightly askew.

**Comment by Hubbitus** [comment]
but it works if I run it from console like:
```
docker run -d -v '/sys/fs/cgroup:/sys/fs/cgroup:ro' --name tomcat taskdata/docker-centos-7-systemd-tomcat
```
How it may be distribution specific?

May it be related to read-only volume support issue?

**Comment by cdancy** [comment]
@Hubbitus it may be. Open an ISSUE with docker-java to see they have anything to say about this. We are just forwarding the String along to them so it may be they are not correctly parsing it.

**Comment by marcuslinke** [comment]
Example code to start a container with read-only binds is here: https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/command/StartContainerCmdImplTest.java#L71

So in general ready-only binds are supported by docker-java. Not sure how gradle-docker-plugin handles the parsing stuff. At least `Bind.parse()` is tested here https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/api/model/BindTest.java#L80

**Comment by cdancy** [comment]
@Hubbitus try doing the below:

```
binds = ['/sys/fs/cgroup' : '/sys/fs/cgroup:ro']
```

**Comment by marcuslinke** [comment]
And I guess volumes should be also modified, so the following should do the job:
```
volumes = ['/sys/fs/cgroup']
binds = ['/sys/fs/cgroup' : '/sys/fs/cgroup:ro']
```

**Comment by Hubbitus** [comment]
Adding those lines leads to error:
> {"message":"Invalid bind mount spec \"/sys/fs/cgroup:/sys/fs/cgroup:ro:rw\": Invalid volume specification: '/sys/fs/cgroup:/sys/fs/cgroup:ro:rw'"}

Using (without mention it in volumes):
```
binds = [ '/sys/fs/cgroup': '/sys/fs/cgroup' ]
```
almost works. But mount in `rw` mode according to `docker inspect`.

**Comment by cdancy** [comment]
Closing as this is more a docker-java syntax problem more than anything else.
