### ISSUE TITLE
Support HEALTHCHECK Instruction

### ISSUE THREAD

**Issue by mam0nth** [bmuschko/gradle-docker-plugin#321]
It seems that the plugin does not yet support this https://docs.docker.com/engine/reference/builder/#/healthcheck so Im requesting to support it.

**Comment by orzeh** [comment]
@mam0nth @cdancy in `docker-java` there is already a [PR which adds support for retrieving healthcheck status in inspect container command response](https://github.com/docker-java/docker-java/pull/763). However, what we can do right now is to support `HEALTHCHECK` instruction in `Dockerfile` task - @mam0nth are you interested in submitting PR?

**Comment by cdancy** [comment]
Currently working on this here https://github.com/docker-java/docker-java/pull/805 and hoping to get in for the 3.0.6 release.

**Comment by cdancy** [comment]
My apologies this is something else :( Feature I'm working on is returning the health status through `DockerInspectContainer`.

**Comment by cdancy** [comment]
Ability to do this, either through generic instructions or a template file, exists within  master.
