### ISSUE TITLE
Add note in documentation that docker auth token can't be used directly

### ISSUE THREAD

**Issue by stormbeta** [bmuschko/gradle-docker-plugin#323]
For our automated builds, we have a pre-generated auth file for our private registry (`~/.docker/config.json`). Unlike the binary docker client, the plugin doesn't appear to read this file, but I assumed I just had to pass the token manually.

I had to look at our docker registry logs to figure out that the plugin was trying to login and pull the token itself, so it needed the actual username/password from the account instead.

While this behavior does make sense, it would be nice if this was mentioned in the README for the next person who runs into this.

**Comment by cdancy** [comment]
@stormbeta yeah we don't read that file by default. We leave it up to you to define the registry to use as "docker config" files can have N number of registries listed.

**Comment by cdancy** [comment]
I could however see a potential PR here where the user can define the config file to use and we pull out the necessary registry configs. Not sure what this would look like but it could be useful as we do something similar here.

@orzeh

**Comment by orzeh** [comment]
@cdancy @stormbeta in `docker-java` there is a [PR](https://github.com/docker-java/docker-java/pull/756) which I hope will fix that.
