### ISSUE TITLE
Allow onNext to end task or stop following logs.

### ISSUE THREAD

**Issue by ebelisle** [bmuschko/gradle-docker-plugin#326]
I'd like to write a task that watches a container and finishes when the container is ready.  DockerLogsContainer and onNext allow me to follow the log (#305), but I don't have a mechanism to complete the task before the container terminates.  

This is a suggested solution for #232.

```groovy
task containerReady(type: DockerLogsContainer) {
    dependsOn dockerContainerStart
    targetContainerId { dockerContainerCreate.getContainerId() }
    follow = true
    tailAll = true
    onNext { message ->
        if (message.toString().contains('database system is ready to accept connections')) {
            follow = false // or other syntax: stopFollowing(), endTask(), etc.
        }
    }
}
```

**Comment by cdancy** [comment]
@ebelisle here is the poor mans solution to that problem ;)

```
task containerReady(type: DockerLogsContainer) {
    dependsOn dockerContainerStart
    targetContainerId { dockerContainerCreate.getContainerId() }
    follow = true
    tailAll = true
    onNext { message ->
        if (message.toString().contains('database system is ready to accept connections')) {
            throw new Exception(message.toString())
        }
    }
    onError { exception ->
        if (!exception.message.contains("database system is ready")) throw exception
    }
}
```

**Comment by cdancy** [comment]
@double16 @orzeh may have some thoughts about how to approach this correctly as they've worked in this area previously. Perhaps we supply a way to short-circuit the executed `onNext` closure on top of providing a time-limit to iterate over logs.

**Comment by cdancy** [comment]
I actually sub-class the `DockerLogsContainer` task here and supply a "logPoller" mechanism which  iterates over executions of said task looking for a match given a max time limit.

**Comment by orzeh** [comment]
@cdancy @ebelisle @double16 I think there is no better solution than one you described above. There are no means to gracefully terminate `docker-java` LogCommand when `folllow` is set to `true`.

We should add a new task that executes `LogCommand` in some kind of a loop and user in `onNext` handler can decide to stop it.

**Comment by cdancy** [comment]
Closing as we've not come up with a more sane and practical solution that makes sense.
