### ISSUE TITLE
Add checkstyle support (PMD an option as well)

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#334]
Maybe we use [this from one of my own projects](https://github.com/cdancy/bitbucket-rest/blob/master/config/checkstyle/checkstyle.xml) which seems to work well enough.

**Comment by cdancy** [comment]
Perhaps a combination of checkstyle and PMD might be a good place to start.

**Comment by MEZk** [comment]
@cdancy 
Can I work on this issue to become more familiar with the project and PR process?

**Comment by cdancy** [comment]
@MEZk you sure can! I would focus on Checkstyle and PMD as they will both set a standard for good coding practices. I use both of theses in my own projects just haven't had the time to implement them here as it's a big chunk of work to take on (not too bad just outside of the scope of 1 hour session). Feel free to reach out with any questions/comments/concerns you may have.

For checkstyle I would use [THIS](https://github.com/project-aries/classtype-parser/blob/master/gradle/config/checkstyle/checkstyle.xml) config file. It's one I use in all my projects and think it would be good to adopt here. [THIS](https://github.com/project-aries/classtype-parser/blob/master/gradle/config/pmd/pmd.xml) pmd config file would also be a good starting point should you want to tackle that next.

**Comment by MEZk** [comment]
@cdancy 

Sub-modules of Checkstyle's TreeWalker cannot validate groovy files, because the modules receives AST based on the Java grammar. We can use only Checker modules, for example FileTabCharacter, RegexpSingleLine, etc.

I think that it would be a good idea to switch to [Codenarc](http://codenarc.sourceforge.net/).

**Comment by cdancy** [comment]
We do you codenarc internally here and it does indeed work well with groovy. Are you thinking to replace the checkstyle PR with codenarc instead?

**Comment by MEZk** [comment]
@cdancy 

1. We still are able to use some modles from Checkstyle. That what I did in #536 

> Are you thinking to replace the checkstyle PR with codenarc instead?

No, I believe that they both are not controversial and can play together as static analysis tools in the build process. In the next PR I will configure Codenarc.

**Comment by cdancy** [comment]
I only meant that if you use codrnarc will there be a need for checkstyle? I believe it does everything checkstyle does works against groovy or java files.

**Comment by MEZk** [comment]
@cdancy 

Yes, you are right. Lets postpone https://github.com/bmuschko/gradle-docker-plugin/pull/536 till we apply Codenarc. The first step is https://github.com/bmuschko/gradle-docker-plugin/pull/537 . If we cover all Checkstyle rules with Codenarc we can close #536 .

**Comment by cdancy** [comment]
Closing this as initial codenarc support is now in place.
