### ISSUE TITLE
Gradle build cache for DockerBuildImage?

### ISSUE THREAD

**Issue by dmitrygusev** [bmuschko/gradle-docker-plugin#335]
Right now even if I configure my Dockerfile to use Docker's build cache it still takes time (up to 30 seconds in my case) to pass the docker build context to the Docker daemon to build an image.

Any reasons why `DockerBuildImage` (and other tasks) don't support the [Gradle Build Cache](https://docs.gradle.org/current/userguide/build_cache.html)?

**Comment by cdancy** [comment]
@dmitrygusev these are 2 very different things. Care to elaborate a bit more as to what you're thinking and/or what you would like to see happen?

**Comment by dmitrygusev** [comment]
Let's take the following task as example:

```groovy
task buildImage(type: DockerBuildImage) {
    inputDir = file("${buildDir}/docker")
}
```

What currently happens is this task always gets executed and my Dockerfile produces an image with the same `ImageId`, because my Dockerfile uses the Docker build cache.

Docker can only understand if it can use its build cache if:
1) there's no `--no-cache`, and
2) it can see its build context.

Now what I think is happening is that the `DockerBuildImage` task is sending the build context (`inputDir`) to the Docker daemon, and if `inputDir` weights over 100MB it takes significant amount of time to do that. And all this just to produce the same image.

So what I'd like to see is that Gradle marks my task as `UP-TO-DATE` if I try to run it second time, without even trying to initiate Docker build, if its inputs (`inputDir` in my case) haven't been changed.

**Comment by orzeh** [comment]
> So what I'd like to see is that Gradle marks my task as UP-TO-DATE if I try to run it second time, without even trying to initiate Docker build, if its inputs (inputDir in my case) haven't been changed.

But what if the base image used in a `Dockerfile` has changed in a meantime?

**Comment by dmitrygusev** [comment]
@orzeh I presume you mean base image specified as `:latest`? I guess it won't notice it and you will have old image if caching is enabled for your build task.

The thing is there is an option to [disable task output cache](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskOutputs.html#cacheIf(org.gradle.api.specs.Spec)), but there's no way to enforce it if the task doesn't support caching.

If you're not using `:latest` then change of the base image is the same as change of the `inputDir`'s contents, as the `Dockerfile` lives there.

**Comment by orzeh** [comment]
@dmitrygusev `:latest` is not the only case, e.g: `openjdk:8`. If between your two Gradle builds someone tells Docker to pull newer base image you will get two different images even if the build context doesn't change. Moreover, you can tell Docker to always try to pull newer base image.

What I trying to say is that only you as a developer can tell if `DockerBuildImage` is up to date or not. If so you are also responsible for implementing it by your own means.

**Comment by cdancy** [comment]
@orzeh brings up a good point: it's nearly impossible, if not entirely so, to determine if an image is up-to-date. We tried to implement something a while back but the corner cases just kept piling up, so much so that we ripped it out of this code base altogether once we realized it's just not possible.

**Comment by dmitrygusev** [comment]
I understand that.

But if I, as developer, know that my image only depends on contents of `inputDir`, because I designed my `Dockerfile` that way on purpose -- there's no moving parts outside of the build context -- why shouldn't I use caching?

**Comment by cdancy** [comment]
Fair enough ... but the question is how do WE tell if that is so? The feature you noted above is also incubating and is new as of 3.0. Not sure how many folks have upgraded yet (I know we haven't) as there is a lot of catch-up going in the gradle community at large with migrating plugins/code/etc to 3.0.

**Comment by dmitrygusev** [comment]
Yeah, I guess you can't know that for sure in general.

The best way it can be done is by providing an option to enable caching for special cases like mine. And I guess you would also need to check if the cached image wasn't deleted manually from `docker images`.

I'll try to play with it by subclassing `DockerBuildImage` and declaring `imageId` as task output, let's see how it'll go.

Closing this issue for now, thanks for your comments.

P.S.
I've tried upgrading wrapper of plugin to latest Gradle 3.3, was able to compile and run it without any issues.

**Comment by cdancy** [comment]
@dmitrygusev if you come up with a solution that you think might work for the greater community at large than by all means share it and we can pick it apart. You're not the first to bring this up and I initially coded the work (however feeble) thinking it could be done. As you note: gradle may have a better more OOTB solution that could potentially deal with the problem better, that combined with various docker calls may prove fruitful. It's a long shot to get right but if you come up with something that works send it this way ;)

**Comment by dmitrygusev** [comment]
Storing `ImageId` in a file inside `buildDir` worked fine for me.

```groovy
class CachingDockerBuildImage extends DockerBuildImage {
    CachingDockerBuildImage() {
        doLast({
            getCachedImageId().write(getImageId())
        })
    }

    @Override
    String getImageId() {
        return super.getImageId() ?: getCachedImageId()?.text
    }

    @OutputFile
    File getCachedImageId() {
        return new File("${project.buildDir}/docker-cache/${name}")
    }
}

task buildImage(type: CachingDockerBuildImage) {
    dependsOn prepareForDockerBuild
    inputDir = file("${buildDir}/docker")
}
```

**Comment by Jolter** [comment]
I wanted to do this same thing but it seems getImageId() has been made `final`.
=(

**Comment by bmuschko** [comment]
@Jolter The field `imageId` has been made `final` but it's only a container for the actual value similar to Java's `Optional`. You can still get or set values.

BTW: We attempted to make the task cacheable in general but reverted at some point as it had unexpected side-effects. For example f you manually delete the image with the `docker` command from the CLI then Gradle doesn't know anything about it. It would still think that the image exists because it finds the file. Ultimately, you'd have to query the Docker registry.

**Comment by Jolter** [comment]
Thanks for answering, @bmuschko! 
In my use case I am guessing it wouldn't matter if users deleted their images manually, as the build would fail with a pretty clear error, and they could "gradlew clean" to make it work again. But it might not be worth my effort to get this working. There is a workaround I could apply...

**Comment by crkurz** [comment]
Hi @bmuschko ,

I am another happy user of your plugin (thank you!!!) and have also been through different attempts to get dockerBuildImage cacheable... some half-baked solutions, but nothing bullet-proof.

To me it looks like a clean solution would always require the imageId in the Gradle Task State *and* have *early* access to this task state e.g. during cacheIf() execution:

cacheIf {
    def imageId = taskState.get ...
    return (does imageId exists locally)
}

Are you aware of a mechanism in Gradle to access information in Gradle's build cache? Any mechanism allowing to have a peek at the cached state (to retrieve imageId) and *then* decide whether to execute the task or to restore from cache?

If so, I may be able to spend some cycles on this.

It looks like that not even LocalTaskState would give us such tool.
