### ISSUE TITLE
Dockerfile task failing when FROM instruction is not the first instruction

### ISSUE THREAD

**Issue by thijslemmens** [bmuschko/gradle-docker-plugin#338]
Behavior:
When some instructions, and then adding a FROM instruction, the validation fails when the task is executed.

Improvement:
Separate out the FROM instruction in a separate field. Run that instruction first and then the list of other instructions. That way, you can change the FROM at any time, it will always be the first instruction.

Why:
I use a chain of builds, and I add the imageId of a previous build later in the process  (because it is not available at the time of constructing the task). Now I use a workaround by storing all the instructions and adding them at the moment I have the "FROM" instruction. It works, but it makes my code less readable.

If you like the improvement, I can send a pull request.

**Comment by cdancy** [comment]
@thijslemmens yes please do send in a PR!
