### ISSUE TITLE
FR: Please add docker-compose yml support

### ISSUE THREAD

**Issue by Hubbitus** [bmuschko/gradle-docker-plugin#340]
It will be very cool to see support of docker-compose file format import.

Just like [ansible docker_service](https://docs.ansible.com/ansible/docker_service_module.html) do it additionally to manual [images and containers](https://docs.ansible.com/ansible/docker_container_module.html) management.

**Comment by orzeh** [comment]
@Hubbitus there already exist plugins that support `docker-compose`: https://plugins.gradle.org/search?term=docker-compose

**Comment by Hubbitus** [comment]
Thanks, good to known. But have it all in one will be good also.

**Comment by cdancy** [comment]
Closing issue as we don't want to reinvent the wheel here and adding this functionality to this plugin is not exactly clear to me.
