### ISSUE TITLE
Please add option to pull image for DockerCreateContainer

### ISSUE THREAD

**Issue by Hubbitus** [bmuschko/gradle-docker-plugin#341]
I see you have separate [task DockerPullImage](http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/DockerPullImage.html) but it should be easy introduce said pull=true option to do not introduce nee dependant task for container creation. Like console docker command do it automatically even without any keys on run.

Now I just get on:
```gradle
task createElasticsearchContainer(type: DockerCreateContainer) {
    targetImageId { 'elasticsearch:1.7-alpine' }
    containerName "unidata_elasticsearch_auto_${buildAppImage.buildTagName}"
}
```
error:
```
Execution failed for task ':createElasticsearchContainer'.
> {"message":"No such image: elasticsearch:1.7-alpine"}
```

**Comment by cdancy** [comment]
This is on purpose. Each task represents a potential command if you will. This plugin allows you to build out tasks or even your own plugin (like I do here) from which you can do similar things and more. Think of the gradle-docker-plugin as a low-level library from which you can build on top of should you need to do so.

**Comment by Hubbitus** [comment]
What plugin do you mention on top of that? And why additional functionality does not desired?

**Comment by cdancy** [comment]
@Hubbitus building your own plugin and using this as the base, or framework you build on top of, is what I'm referring to. We consider this a "low level" plugin which maps tasks to docker API endpoints. Anything use-case specific would have to be done downstream by yourself or some other plugin. I do exactly this in a plugin we have here which uses this plugin in the backend but creates "high level" tasks for our developers to use.
