### ISSUE TITLE
Thoughts on switching to use jclouds-docker vs docker-java

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#343]
docker-java does not iterate as fast as I would like and maybe it may be worth looking into using something else in the backend. I'm thinking of maybe using [jclouds-docker](https://github.com/jclouds/jclouds/tree/master/apis/docker) or even forking it and naming it something else. I personally have a lot of experience using this library as I've written [more than a few](https://github.com/cdancy/bitbucket-rest) based off of it myself. Forking our own would allow us to iterate fast and able to churn out newer features and not have to wait for a middle-man.

Thoughts?

**Comment by orzeh** [comment]
@cdancy I'm also rather disappointed by the `docker-java`. However, I don't have any experience with `jclouds-docker`. In my opinion, if we want to change something, we should fork one of these libraries and take 100% control and responsibility ;)

**Comment by gesellix** [comment]
@cdancy @orzeh have you considered contributing more code/PRs to docker-java instead of waiting for them to add features? If its not about code, but about the release cycle, you might ask them for automated releases or at least higher frequent ones. Forking and maintaining a Docker lib can be hard considered Docker's pace. I can tell from my own experience maintaining yet another docker-client, so I'm not sure if you really _want_ to maintain a client on your own. Maybe they accept you as contributors?

**Comment by cdancy** [comment]
@orzeh in spirit I agree but all of the json processing/handling that docker-java does is unnecessary and I'd hate to carry that bloat forward. `jclouds-docker` would be a good library to fork and move forward on IMO as all of the json processing is done seamlessly behind the scenes using gson. The library itself heavily leverages reflection and meta programming so really all the end users would have to do, that being us or contributors, is add [endpoints and annotations](https://github.com/cdancy/bitbucket-rest/blob/master/src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java#L61).

Also ... the only reason I bring up forking jclouds-docker is that the Api we'd be forking is built into jclouds as a whole so to speak. As such, and much like docker-java, the rate of change tends to be slower. They only do a couple releases a year and they tend to focus solely on "compute" and "node" abstractions.

**Comment by gesellix** [comment]
Regarding `jclouds-docker`: do they support unix sockets (Linux/macOS) or even named pipes (Windows)? I didn't see any docs mentioning that.

**Comment by cdancy** [comment]
@gesellix not sure to be honest. More just talking out loud here. I'd have to look into things a bit more. Definitely would not want to maintain another library if we don't have to.

**Comment by gesellix** [comment]
@cdancy yeah, I also have the impression that docker-java is too slow, so I understand your thoughts. I'm just playing devil's advocate - in fact, I had my own (similar) [thoughts about that topic](https://www.gesellix.net/choosing-a-library/), but without clear outcome ;-)

**Comment by orzeh** [comment]
@gesellix I've submitted several PR to `docker-java` and this is the best path to follow. But see how many issues and PR are open in `docker-java`. There is definitely a problem in feedback. The community is quite active but the maintainers seems to be busy with something else. If so, maybe they need some help.

@KostyaSha @marcuslinke how can we help to _speed up_ `docker-java`?

**Comment by KostyaSha** [comment]
what exactly PR?

**Comment by orzeh** [comment]
@KostyaSha we are not discussing here any particular PR but `docker-java` as a whole. 

We have an impression that the release cycle is not as fast as it could be.

**Comment by KostyaSha** [comment]
You can join maintaining if you have time, most of PRs didn't follow docs, messing existing things. 
If you have no any open delayed PRs then what we are discussing?

**Comment by orzeh** [comment]
@KostyaSha OK I can join maintaining `docker-java` - I will focus on things that are used/missing here.

@cdancy maybe we should create new label to mark issues _waiting_ for `docker-java` to easily track them?

**Comment by cdancy** [comment]
@gesellix you're right in that jclouds-docker does not currently support unix sockets or windows named pipes. Talking witht the devs on IRC they are strictly an http library but understood the need to be able to run locally on unix and windows machines at least for docker. Opened a [JIRA issue](https://issues.apache.org/jira/browse/JCLOUDS-1238) with them incase we decide to go this route at some future date. They seemed on board to getting this in at some  point just don't know when.

@orzeh helping out on docker-java sounds awesome. @KostyaSha if you need help in maintaining things feel free to add myself as well as a maintainer and point us to any relevant docs to help move things forward and/or get us on board quicker. Think we've all submitted PR's at one point or another so the code base should be familiar enough.

**Comment by cdancy** [comment]
@KostyaSha my "issue" if you will with `docker-java` is more around style and ease of use at least WRT adding new code and features. I'm comparing this with `jclouds-docker`, and other similar libraries that I noted above that are API/annotation driven, in that adding new features is as simple as adding a new "endpoint", adding the necessary annotations, and writing a mock and integration test. That's really it. The jclouds framework hides all of the json processing behind the scenes so you don't end up with the verbosity that using jackson can get you.

I certainly don't want to move away from docker-java if we don't have to just throwing out suggestions and getting a feel for what folks think.

**Comment by KostyaSha** [comment]
Feel free to provide PRs. That what people usually do before get permissions. If you have any ready pr that stuck, feel free to point me. Atm swarm tests failing in parallel run and requires additional work.

**Comment by cdancy** [comment]
Closing as it appears consensus, at least for the time being, is to stick with docker-java. Though I would love to see support for windows named pipes as a lot of users have been asking at this point...
