### ISSUE TITLE
Replace boot2docker with Docker Machine or Docker for Mac

### ISSUE THREAD

**Issue by arun-gupta** [bmuschko/gradle-docker-plugin#344]
https://github.com/bmuschko/gradle-docker-plugin#executing-the-plugins-test-suite-with-custom-configuration still refers to boot2docker. This should be at least updated to Docker Machine, better would be Docker for Mac.

**Comment by cdancy** [comment]
Maybe just set to `/home/user/.docker`as that seems to be what[ docker is standardizing on](https://docs.docker.com/engine/security/https/).

**Comment by arun-gupta** [comment]
I think it's more a documentation issue than using `/home/user/.docker` directory.

**Comment by cdancy** [comment]
@arun-gupta yeah I agree I was just noting that maybe our documentation remove the boot2docker references and instead use the above.

**Comment by cdancy** [comment]
Tests can be run natively now and so I think this ISSUE has become largely irrelevant. Feel free to re-open if necessary.
