### ISSUE TITLE
new gradle plugin syntax not working

### ISSUE THREAD

**Issue by matthiasbalke** [bmuschko/gradle-docker-plugin#347]
I switch from old to "new" gradle plugin syntax.
```groovy
plugins {
    id 'base'
    id 'com.diffplug.gradle.spotless' version '3.0.0' apply false
    id 'org.sonarqube' version '2.2.1' apply false
    id 'org.springframework.boot' version '1.5.1.RELEASE' apply false
    id 'com.jfrog.bintray' version '1.7.3' apply false
    id 'org.ajoberstar.github-pages' version '1.5.1' apply false
    id 'org.asciidoctor.gradle.asciidoctor' version '1.5.1' apply false
    id 'com.sourcemuse.mongo' version '0.14.0' apply false
    id 'com.bmuschko.docker-remote-api' version '3.0.3' apply false
}
...
```
When executing the docker tasks I always get the following error. The same error was also described in #280 scenario `file5.gradle`, but the issue was closed due to resolving another bug described in there.

How can I fix my build to use the new syntax?

build log: https://gist.github.com/matthiasbalke/fec93a4be79a0ae49163c832ebe14f67

**Comment by cdancy** [comment]
@matthiasbalke looks more like a gradle issue than anything to do with this plugin. What version of gradle are you using to get this failure? Have you tried the latest and greatest? Do you have a small reproducible script I could give a go?

**Comment by orzeh** [comment]
@matthiasbalke how do you apply plugin to subprojects?

**Comment by matthiasbalke** [comment]
@cdancy I'm using Gradle 3.3 this is my https://github.com/matthiasbalke/infiniboard/blob/gradle/build.gradle

The same error was also described in #280 scenario `file5.gradle` I think that should work as a minimal example to reproduce.

@orzeh Thats how I apply the plugin
* https://github.com/matthiasbalke/infiniboard/blob/gradle/quartermaster/build.gradle
* https://github.com/matthiasbalke/infiniboard/blob/gradle/harvester/build.gradle

**Comment by matthiasbalke** [comment]
@orzeh I just realized the given example is not the exact same setup, so I build a minimal example setup here https://github.com/matthiasbalke/gradle-docker-plugin-issue-347

**Comment by orzeh** [comment]
@matthiasbalke this is the same issue as in #248 (see my [comment](https://github.com/bmuschko/gradle-docker-plugin/issues/248#issuecomment-234098958)).

To fix just adjust build script classpath, see my [PR](https://github.com/matthiasbalke/gradle-docker-plugin-issue-347/pull/1) to your project.

**Comment by matthiasbalke** [comment]
@orzeh ok this is working for two plugins, but in case I use a bunch of plugins, do I have to include all plugins in the classpath block?

**Comment by orzeh** [comment]
@matthiasbalke you have to add all of them, I'm afraid :disappointed:

**Comment by bmuschko** [comment]
@matthiasbalke Why do you declare `apply false` for your plugins? You will want to apply those plugins and not just add them to the build script's classpath. All the logic implemented in the plugins will not apply otherwise.

**Comment by orzeh** [comment]
@bmuschko I thnik @matthiasbalke has multiproject build https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl

**Comment by matthiasbalke** [comment]
@bmuschko I have a multi module build and apply the plugins just to a subset of the modules.

**Comment by bmuschko** [comment]
@matthiasbalke You are actually describing two different use cases here:

1. You use the new plugin DSL in the root project with `apply false`. In the subprojects you apply the plugin.
2. In the [other example](https://github.com/matthiasbalke/gradle-docker-plugin-issue-347) you provide you mix the new plugin DSL and the `buildscript` notation in combination of a script plugin.

Can you describe what you are trying to solve or are these just different attempts to solve a specific problem?

Generally speaking the issue you are seeing occurs if you _do not_ apply the remote API plugin. It's is required to properly set up the classpath of Docker Java. Just adding the plugin to the buildscript's classpath does not work even if you just want to add a task of a type provided by the plugin.

**Comment by matthiasbalke** [comment]
@bmuschko In one of my projects (https://github.com/reflectoring/infiniboard) I want to switch to the new gradle plugin syntax, as it is said to be more performant.

When using the `gradle-docker-plugin` ([here](https://github.com/reflectoring/infiniboard/blob/master/gradle.d/02-docker.gradle)) I need to import the Task class `com.bmuschko.gradle.docker.tasks.image.DockerBuildImage` to be able to define some tasks to create and tag docker images within my release process. I didn't find any solution to use this class without defining the plugin again within the `buildscript` block. This is why I am mixing the new and the old plugin definition style.

I really appreciate any hint on how to solve this problem.

**Comment by typekpb** [comment]
@matthiasbalke I ran into same problem (just different plugin: `id "com.bmuschko.cargo-base" version "2.2.3"`)
@bmuschko ideas?

**Comment by typekpb** [comment]
OK, as reported by @bmuschko using the plugin syntax:

	plugins {
	  id "XXX" version "YYY" apply false
	}

in the root project and in the subproject using old syntax with classname (no qoutes) works fine:

	buildscript {
	  repositories {
	      jcenter()
	  }
	  dependencies {
	      classpath group: 'ZZZ', name: 'XXXX', version: 'YYY'
	  }
	}

	apply plugin: com.bmuschko....Plugin

works just fine!

**Comment by cdancy** [comment]
Closing. Feel free to re-open if need be.
