### ISSUE TITLE
Build next release

### ISSUE THREAD

**Issue by dataduke** [bmuschko/gradle-docker-plugin#349]
As a gradle-docker-plugin user
I need a new release version within the next week for using it in production
so that changes implement by my colleague @jmewes on 20th January are included

Thanks a lot in advance @cdancy

**Comment by cdancy** [comment]
@dataduke I can knock that out for you. Working on getting one last thing in which should be done within the next few days or so. If I don't release by the time you need it just ping again and I'll knock one out for you.

**Comment by dataduke** [comment]
@cdancy that was really fast. Cool. Looking forward to it!

**Comment by dataduke** [comment]
Hi @cdancy, just a quick reminder. If you could bundle the next release soon I would try to implement it into our pipeline tomorrow. That would be sooo awesome. Thanks!

**Comment by dataduke** [comment]
@cdancy I see your trouble. Great that you offer the possibility to do two incremental releases if it does not work out now. 👍

**Comment by cdancy** [comment]
@dataduke `3.0.6` is now released. Let me know how things work out. Thanks.

**Comment by dataduke** [comment]
@cdancy awesome. will provide when in use

**Comment by dataduke** [comment]
@cdancy awesome. will provide feedback when in use soon 💯

**Comment by dataduke** [comment]
@cdancy everything works fine in our pipeline. I could not be happier with all your support and short response time. I wish you the best weekend ever! Maybe we met someday in real life. This would be legendary. ;-)

**Comment by cdancy** [comment]
@dataduke your welcome and this is a small world so you never know ;)
