### ISSUE TITLE
No value has been specified for property 'classpath'

### ISSUE THREAD

**Issue by davidsowerby** [bmuschko/gradle-docker-plugin#35]
I've looked at #17 but it is not clear to me why I am getting the same error.

To an existing multi-project build.gradle all I have added is:

to the buildscript dependency closure

    classpath 'com.bmuschko:gradle-docker-plugin:2.0.2'  

imports

    import com.bmuschko.gradle.docker.tasks.container.*
    import com.bmuschko.gradle.docker.tasks.image.*

and the tasks you give as an example for executing functional tests against a running container

running gradle buildMyAppImage produces the error

I cannot see anything I have done which would indicate  either of the points you mention, unless I have achieved one of them without trying!

>This can only happen if you set the classpath property to null for at least one of your Docker tasks. It could potentially also happen if you assign an empty list of dependencies to the configuration dockerJava. There's really no good reason I can see why you'd want to change the built-in capabilities of the plugin.

**Comment by bmuschko** [comment]
* What's the stack trace you are seeing?
* What version of Gradle are you using?
* Are you declaring a repository in the same project that applies the plugin?
* Which of the plugins are you actually applying?
* Can you provide a simple, reproducible example?

**Comment by davidsowerby** [comment]
Thanks for the quick response.  Now I have to think of a good reason for my embarrassingly dumb mistake .... I'd somehow commented out the line which applies your plug in, and didn't see it in a fairly large file.  I guess the error message is a bit unusual, but still no excuse - apologies for taking up your time.

**Comment by drallgood** [comment]
I'm seeing the same issue and no, I didn't forget to apply the plugin.

Simply moving the code to `build.gradle` vs `other.grade` fixes the issue

**Comment by bmuschko** [comment]
Same questions here. What's the version of Gradle you are using? Please provide a sample build script that reproduces the issue.

**Comment by drallgood** [comment]
I'm using 2.2.1

I figured out that it seems to happen when I use shadowJar before creating an image. So, I'm not sure whose fault it is. 

Here's a very simple example:

build.gradle 
```
plugins {
	id 'com.bmuschko.docker-remote-api' version '2.1'
	id 'com.github.johnrengelman.shadow' version '1.2.1'
}

apply from: 'other.gradle'

repositories {
	jcenter()
}
```

other.gradle:
```
buildscript {
    repositories { jcenter() }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:2.1'
    }
}

apply plugin: 'application'    
apply plugin: 'com.bmuschko.docker-remote-api'


mainClassName = 'de.MainClass'

shadowJar {
    mergeServiceFiles()
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/*.RSA'
}


import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

docker {
	url dockerUrl
}

task createDockerfile(type: Dockerfile, dependsOn: 'shadowJar') {
    from "java:8u40"
    maintainer 'me'
 }

task buildImage(type: DockerBuildImage, dependsOn: 'createDockerfile') {
    inputDir = createDockerfile.destFile.parentFile
    tag = "test/test"
}

```

**Comment by bmuschko** [comment]
JCenter does not have the [version 0.10.5 of Docker Java](https://bintray.com/bintray/jcenter/com.github.docker-java%3Adocker-java/view). That's the reason why the artifact cannot be resolved.

**Comment by bmuschko** [comment]
The reason this is failing for you is that you apply the Docker plugin twice. Once with the new Gradle DSL (`plugins` method) and then again with the "old" mechanism (`buildscript`). Multiple comments:

- You only need to apply the plugin where it matters - in this case in `other.gradle`.
- Mixing the old and new mechanism seems to have side-effects. Settle for one mechanism.
- The "new" mechanism is still an incubation feature and has limitations. See Gradle documentation and plugin portal.
- If you apply a plugin in a script plugin (`other.gradle`) you need to apply it by type. This is a known Gradle limitation. The solution looks like this: `apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin`

So to fix your issue, remove plugins `{ id 'com.github.johnrengelman.shadow' version '1.2.1' }` in `build.gradle` and change `apply plugin: 'com.bmuschko.docker-remote-api'` to `apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin`

**Comment by drallgood** [comment]
Awesome. That did it!

The reason I also put the plugin into the plugins section was that the build was complaining about the apply. 

Thanks for your help!

**Comment by ericweinberg** [comment]
I want to first apologize for reviving these old threads.  I'm struggling with the fix for this one, probably because I don't have a good understanding of gradle.  I'm having the same issue as @drallgood has up above, I just don't understand the fix. I'm stumbling on how to either convert my plugins block to apply plugin or to convert the gradleDockerPlugin apply plugin to the plugins structure

I created a sample project [here](https://github.com/ericweinberg/gradleDockerPlugin_issue35_question) that shows the problem.

**Comment by bmuschko** [comment]
@ericweinberg If you apply an external plugin in a script plugin then you need to apply it by type: `apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin`. It's a limitation in Gradle.

**Comment by ericweinberg** [comment]
Thanks for the quick reply.  I updated the plugin definition in docker.gradle to be : 

`apply plugin: 'com.bmuschko.gradle.docker.DockerRemoteApiPlugin'`

and got: 

`Plugin with id 'com.bmuschko.gradle.docker.DockerRemoteApiPlugin' not found`

I've got the plugin in the dependencies block and tried sticking an import above the apply plugin block. I'm not sure what I'm missing though.

**Comment by bmuschko** [comment]
@ericweinberg Remove the single quotes. It's a class reference.

**Comment by ericweinberg** [comment]
....doh   
Thanks again for the help on this one. I'm up and running.
