### ISSUE TITLE
Conditional building of image

### ISSUE THREAD

**Issue by tdudgeon** [bmuschko/gradle-docker-plugin#351]
How is it best to configure a DockerBuildImage to only do the build when necessary?
For instance, let's assume we have a Java web application build built with the gradle war plugin.
If I call the war target the war file only gets rebuilt if it's necessary to do so.
But if I use the gradle-docker-plugin to build a docker image that incorporates that war file it rebuilds the docker image every time, even if the war has not been updated.
The scenario here could be a multi-project build when you are running integration tests using docker images from some of the sub-projects, and you only want to rebuild when something has changed in  that sub-project.
In simplest terms this means make the DockerBuildImage task run only when the output of the war task is newer than the docker image that was last built.

**Comment by cdancy** [comment]
@tdudgeon this issue has come up numerous times, and at one point even tried to implement a solution, but upon further investigation it was deemed impossible to tell whether an image was different from some other image. Looking at things from our point of view, meaning not taking into account your war file, how would we be able to tell if this image being built would be newer than some previously existing image? We're looking at things from the docker POV and there really is no sane way to determine

You could probably implement something on your end (i.e. maybe using an `onlyIf` block on this particular task) if you're sure the image is different than some other already built image.
