### ISSUE TITLE
Configure With Dockerfile

### ISSUE THREAD

**Issue by pluttrell** [bmuschko/gradle-docker-plugin#353]
How would someone configure this plugin if they only have:

* An existing Dockerfile at `src/main/Docker/Dockerfile`
* A single executable JAR (SpringBoot) that to end up at the root of the file system `/app.jar`
* Wants it tagged with 2 tags, such as `0.1.0` and `latest`

Thanks.

**Comment by cdancy** [comment]
@pluttrell have you tried putting together a script already and it didn't work or are you looking for help on how to use this plugin? If you've got a script somewhere please share it and we can look it over. If not, and you need help, please read over this projects [README](https://github.com/bmuschko/gradle-docker-plugin/blob/master/README.asciidoc) first to get an understanding of how things work.

**Comment by cdancy** [comment]
There are also loads of tests we have which provide good examples on how various things work.

https://github.com/bmuschko/gradle-docker-plugin/tree/master/src/functTest/groovy/com/bmuschko/gradle/docker

**Comment by pluttrell** [comment]
@cdancy Many thanks for getting back to me so quickly.

Prior to posting this question, I did read the project's README completely. And while it's clear that this plugin can support an impressive set of advanced use cases and customizations with tie-ins at many aspects of the lifecycle it uses, I didn't see any example or understand where to start to define the simplest of use cases - the one I mentioned in this question. In looking at several other plugins related to docker, all show this use case quite early in the docs. This plugin appears to be very well maintained and would love to use it, so thought I would reach out to see how to accomplish this simple use case.

Thanks also for the link to the tests. I glanced at them just now but didn't find any examples of what I want to accomplish.

**Comment by cdancy** [comment]
@pluttrell take a look at [DockerBuildImage](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy). It allows you to specify the build context (i.e. the directory relative to your Dockerfile) and also allows you to define labels for said image. [Here is an example](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy#L117) that pretty much does everything you're asking for.

**Comment by eddumelendez** [comment]
@pluttrell hope my [example](https://github.com/eddumelendez/javaee7-docker-gradle) can help

**Comment by cdancy** [comment]
@eddumelendez good example and thanks for posting. Closing issue as I believe there is more than enough here to solve OP's problem.
