### ISSUE TITLE
Problems mounting a host volume

### ISSUE THREAD

**Issue by joernott** [bmuschko/gradle-docker-plugin#356]
Hi,

I want to use the golang container to compile a static binary which will then be put into the container I am building. I tried to figure out, how to actually bind mount $projectDir/src/usr/bin into /go/bin in the container, but I nver got this to work.

Maybe, you can give me a hint on what I am doing wrong:

```
task createBuildContainer(type: DockerCreateContainer) {
    doFirst {
        def hostPath = (file("$projectDir/src/usr/bin")).getAbsolutePath()
        println "******** Installing into " + hostPath
    }
    dependsOn pullBuildContainer
    attachStderr = true
    attachStdout = true
    targetImageId { pullBuildContainer.repository + ":" + pullBuildContainer.tag }
    volumes = [ '/go/bin' ]
    binds = [ hostPath : '/go/bin' ]
    env = [ "http_proxy=" + httpProxy, "https_proxy=" + httpProxy ]
    cmd = [ "/bin/bash", "-c", "(go get -v -u github.com/influxdata/influxdb-relay ; chmod a+w /go/bin/influxdb-relay)" ]
}

task startBuildContainer(type: DockerStartContainer) {
    dependsOn createBuildContainer
    targetContainerId { createBuildContainer.getContainerId() }
}

task checkBuildResult(type: DockerWaitContainer) {
    dependsOn startBuildContainer
    targetContainerId {startBuildContainer.getContainerId()}
    doLast{
        if(getExitCode() != 0) {
            println "Build Container failed with exit code \${getExitCode()}"
        } else {
            println "Build Container successful"
        }
        assert file("$projectDir/src/usr/bin/influxdb_relay").exists()
    }
}
```

**Comment by cdancy** [comment]
@joernott what is the actual error you see? Can you post the stacktrace?

**Comment by orzeh** [comment]
@joernott as @cdancy said it is hard to say anything without stacktrace. What I can spot looking at your build script is that `hostPath` variable used to bind volume is set when task is being executed and  you use it in `binds` when task is being configured. Maybe this cause problems.

**Comment by joernott** [comment]
@cdancy: The container is created and started. it runs perfectly, but due to the fact, that the folder is not mounted, the compiled binary is not stored on the host file system but inside the container and thus, it is lost, when the container finished building. The only stack trace I can get is for the assert line I added to verify if the binary has been stored on the mounted host FS. Attached, you can find the stacktrace and the debug log of the build.
[debug.txt](https://github.com/bmuschko/gradle-docker-plugin/files/858058/debug.txt)
[stacktrace.txt](https://github.com/bmuschko/gradle-docker-plugin/files/858059/stacktrace.txt)

PS: Sorry for the late reply, I needed to get our test ELK cluster up and running, which took a large portion of my time

**Comment by joernott** [comment]
@orzeh: I have changed hostPath to a property defined in ext, ensuring, that it is defined before its being used. The result doesn't change. The container is started properly and doies what it's supposed to except for mounting src/usr/bin to /go/bin inside the container. As a result, the compiled binary is lost upon termination and the assert line fails.

**Comment by joernott** [comment]
[influxdb_relay.tar.gz](https://github.com/bmuschko/gradle-docker-plugin/files/858122/influxdb_relay.tar.gz) is a stripped down project which can run without access to our private Nexus, registry and images. This should run anywhere, if you want to test.

I also left my workaround in (commented out), so you can see the docker run statement which actually mounts the folders the way I want.

**Comment by orzeh** [comment]
@joernott ok I've found your mistake.
in:
````groovy
binds = [ hostPath : '/go/bin' ]
````
you use `hostPath` as key, but Groovy will use `"hostPath"` string as a key not the variable value. Change it to:
````groovy
binds = [ (hostPath): '/go/bin' ]
````
and it should work (see [Groovy docs](http://www.groovy-lang.org/syntax.html#_maps)).

Also in your sample project there is a mistake in assertion:
````groovy
assert file("$projectDir/src/usr/bin/influxdb_relay").exists() 
````
but created file is named `influxdb-relay`.

**Comment by cdancy** [comment]
@joernott or to add to @orzeh recommendation: you're more than free to define properties within the `doFirst` block. I do this here all the time actually to great success.

doFirst {
    def hostPath = (file("$projectDir/src/usr/bin")).getAbsolutePath()
    println "******** Installing into " + hostPath
    binds = [ hostPath : '/go/bin' ]
}

**Comment by joernott** [comment]
Thanks for your help!
