### ISSUE TITLE
Enhancement: add nameFilter to DockerListImages

### ISSUE THREAD

**Issue by DALDEI** [bmuschko/gradle-docker-plugin#360]
The 'filters' property of DockerListImages is applied to 'withLabelFilter'.
It is very useful to list images by name.
It would be nice to have a nameFilter  (and while your at it , arrays of filters and dangling )

    ListImagesCmd withImageNameFilter(String imageName);

**Comment by orzeh** [comment]
@DALDEI are you interested in submitting PR?

**Comment by childnode** [comment]
@DALDEI how do you look for images "by name" on console?! a filter for that is unknown to me

**Comment by cdancy** [comment]
Closing as it seems OP is not up for putting together a PR for this proposed functionality (assuming it can be done). Feel free to re-open if necessary.
