### ISSUE TITLE
Exit codes for TaskType:DockerExecContainer

### ISSUE THREAD

**Issue by kish3007** [bmuschko/gradle-docker-plugin#361]
I have tried to use this for my project, one of my requirement is to exec into a container and run a script, check for exit codes if the scripts fails(return a non-zero exit code) and fail the task. Is there a way to check exit codes for taskType:DockerExecContainer if cmd[] fails?

**Comment by orzeh** [comment]
@kish3007 it will be possible when #362 is merged. In new functional tests you should find solution to your question.

**Comment by cdancy** [comment]
PR has been merged to master. Next release will have change. Would like to get it out as soon as #369 is resolved.
