### ISSUE TITLE
DockerBuildImage hangs on osx

### ISSUE THREAD

**Issue by JLLeitschuh** [bmuschko/gradle-docker-plugin#365]
I'm trying to build a docker image with your plugin in a subproject.

My build is using [gradle script kotlin](https://github.com/gradle/gradle-script-kotlin):
```kotlin
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.Dockerfile

buildscript {
    // This sets up my companies internal repositories
    applyFrom("${rootProject.projectDir}/sharedValues.gradle.kts")
    val configureRepository: (Any) -> Unit by extra
    configureRepository.invoke(repositories)
    dependencies {
        classpath("com.bmuschko:gradle-docker-plugin:3.0.6")
    }
}
apply {
    plugin("com.bmuschko.docker-remote-api")
}

docker {
    url = "unix:///var/run/docker.sock"
}

val createDockerFile = task<Dockerfile>("createDockerFile") {
    destFile = file("$buildDir/coreDocker/Dockerfile")
    from("ubuntu:12.04")
    maintainer("Company")
}

task<DockerBuildImage>("buildImage") {
    dependsOn(createDockerFile)
    inputDir = createDockerFile.destFile.parentFile
    tag = "company/testimage"
}


/**
 * Retrieves or configures the [docker][com.bmuschko.gradle.docker.DockerExtension] project extension.
 */
fun Project.docker(configure: com.bmuschko.gradle.docker.DockerExtension.() -> Unit = {}) =
    extensions.getByName<com.bmuschko.gradle.docker.DockerExtension>("docker").apply { configure() }
```

The task `buildImage` hangs and doesn't ever seem to complete.
I've tried both with and without the gradle daemon.

I can successfully run:
```bash
> curl --unix-sock /var/run/docker.sock localhost:2376/version
{"Version":"17.03.1-ce","ApiVersion":"1.27","MinAPIVersion":"1.12","GitCommit":"c6d412e","GoVersion":"go1.7.5","Os":"linux","Arch":"amd64","KernelVersion":"4.9.13-moby","Experimental":true,"BuildTime":"2017-03-24T00:00:50.070226199+00:00"}
```
so I'm fairly confident this isn't a problem with needing certs.

```
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

```
OS: macOs Sierra version 10.12.3 (16D32)
```
Gradle version: `3.5-20170404014535+0000`

Running with either `-debug` or `-info` provides no real useful info.
Here are the last few lines of the run of debug before I kill gradle:
```
16:47:12.876 [INFO] [org.glassfish.jersey.internal.ServiceFinder] Running in a non-OSGi environment
16:47:13.144 [QUIET] [org.gradle.api.Task] Building image using context '/Users/jonathanleitschuh/work/git2/plexxicontrol/PlexxiDocker/build/coreDocker'.
16:47:13.337 [QUIET] [org.gradle.api.Task] Using tag 'plexxi/testimage' for image.
16:47:13.574 [INFO] [org.glassfish.jersey.process.internal.ExecutorProviders] Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
```

**Comment by orzeh** [comment]
@JLLeitschuh can you build image from this dockerfile using Docker CLI?

**Comment by JLLeitschuh** [comment]
Yes, I can navigate to the output directory of `createDockerFile` and run 
`docker build -t plexxi/testimage .`
it works correctly.

Any thoughts as to what would cause this?

**Comment by JLLeitschuh** [comment]
So, I've done a bit more digging.
I created an example project that just uses the docker-java API.

```kotlin
import com.github.dockerjava.core.DefaultDockerClientConfig
import com.github.dockerjava.core.DockerClientBuilder
import com.github.dockerjava.core.command.BuildImageResultCallback
import java.io.File

class Main {

}

fun main(args: Array<String>) {
    val dockerFile = File(Main::class.java.getResource("/Dockerfile").file)
    val baseDirectory = dockerFile.parentFile
    println(baseDirectory)
    val config = DefaultDockerClientConfig.createDefaultConfigBuilder()
        .withDockerHost("unix:///var/run/docker.sock")
        .build()
    val client = DockerClientBuilder.getInstance(config).build()
    val imageId = client
        .buildImageCmd()
        .withBaseDirectory(baseDirectory)
        .withDockerfile(dockerFile)
        .withTag("plexxi/testimage2")
        .exec(BuildImageResultCallback())
        .awaitImageId()
    println("Image id: $imageId")
}
```

This seems to work as expected.

Some things that I have observed, the usage of the the docker API in this plugin doesn't use the `awaitImageId` that takes a timeout.
I think that exposing the ability to configure this would be useful for ensuring CI servers that have this problem eventually terminate.
This doesn't fix my specific problem however. I'm going to continue digging.

**Comment by JLLeitschuh** [comment]
I solved our problem.
We had a bunch of our dependencies forced to prevent version conflicts.
I had this resolution strategy configured for all configurations.
One of these dependencies doesn't work with the docker java api. (I'm not sure what dependency was causing the problem). But I bet that somewhere a `MethodDefNotFound` exception was being thrown and not handled in a way that causes `awaitImageId` to terminate.

When I made it so that the resolution strategy wasn't applied to the `dockerJava` configuration everything started working.

I wish I'd gotten an exception that propagated or was at least logged.

**Comment by cdancy** [comment]
> Some things that I have observed, the usage of the the docker API in this plugin doesn't use the awaitImageId that takes a timeout.

@JLLeitschuh care to send in a PR?

**Comment by orzeh** [comment]
@JLLeitschuh @cdancy some discussion about timeouts was in #315. Maybe it's time to fix it.

**Comment by JLLeitschuh** [comment]
I don't really have the time right now.
If I encounter the problem again I'll add something.


*Side note*
Thanks devs for making the DSL strongly typed. Otherwise it would have made writing this logic in Gradle Script Kotlin a lot more work.
