### ISSUE TITLE
Failures from remote api do not fail build

### ISSUE THREAD

**Issue by stevendpclark** [bmuschko/gradle-docker-plugin#37]
Hi,

I was wondering if I am missing something. Currently when there is an error building an image gradle is still reporting a success from at least a DockerBuildImage task. I am currently handling this by looking for an image id within a doLast closure within the task. 

Is there a better way? Was this behaviour on purpose, as it seems all the response handlers have the same behaviour when errors are being reported from the api?

```gradle
task buildImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    inputDir = createDockerfile.destFile.parentFile
    tag = 'bmuschko/myimage'

    doLast {
        if ( getImageId() == null ) {
            throw new GradleException( 'Failed to build image' )
        }
    }
}
```

**Comment by bmuschko** [comment]
Good point. We should fail the build if we encounter an error in a `ResponseHandler`. Otherwise, it would lead to the behavior you are mentioning. I'll put something into place.

**Comment by stevendpclark** [comment]
Thanks for the fix!
