### ISSUE TITLE
failed to bind ports between host and container 

### ISSUE THREAD

**Issue by kiosk123** [bmuschko/gradle-docker-plugin#376]
I used the 'portBindings' property, and mapped ports but it don't work.

after making container, I typed command 'docker ps -a' and knew PORTS is null.

command result is below

CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
8b3455293079        scrooge:latest      "catalina.sh run"   5 minutes ago       Created                                 scroogeApp

my code is below ...

task createContainer(type: DockerCreateContainer) {
    dependsOn buildImage
    targetImageId { buildImage.getTag() }
    containerName = 'scroogeApp'
    portBindings = ['9090:8080'] //['host':'container'] 
}

and Dockerfile

 FROM tomcat
 ADD ./build/libs/scrooge.war /usr/local/tomcat/webapps/
 CMD ["catalina.sh", "run"]

What is wrong?

**Comment by cdancy** [comment]
@kiosk123 you actually have to start the container after creating it. If you [look at our README.md](https://github.com/bmuschko/gradle-docker-plugin#executing-functional-tests-against-a-running-container) you will see an example of how to do so.
