### ISSUE TITLE
Wait on container startup?

### ISSUE THREAD

**Issue by edesdan** [bmuschko/gradle-docker-plugin#381]
Is there any way to wait for a specific string in a log file or wait on a port to become open when starting a container? 

Use case: sometimes starting a container can take a while so executing a functional test might fails if the container takes a while to start up.

**Comment by cdancy** [comment]
@edesdan the name is escaping me at the moment but docker has an OOTB way you can build an image and only have it in the "started" state once some script returns true or something along those lines. 

However, and I assume like most folks you're not in control of this container, you need to poll the container for some log to be present we've got you covered. Now this is a poor mans solution to the problem until we have something better in place but it works and I personally use it here and with great success. Consider the below:

```
task logContainer(type: DockerLogsContainer) {
    targetContainerId { "container-that-does-exist" }
    follow = true
    tailAll = true
    onNext { message ->
        def foundMessage = message.toString() 
        if (foundMessage.matches('Some string that says we are live')) {
            throw new RuntimeException('SHORT-CIRCUIT-POLLING')
        }
    }
    onError { exception ->
        if(!exception.message.contains('SHORT-CIRCUIT-POLLING')) {
            throw exception
        }
    }
}
```
So what we are doing is polling some container, after it has started and via our reactive-stream method `onNext`, to check for some log line. Once we've found it we throw an exception to stop the polling as it will continue until the container has stopped. We then use our reactive-stream method `onError` to catch the just thrown exception and interrogate it to make sure it contains the expected "short circuit" message and if not then re-throw as something beyond our control has clearly gone wrong.

Give that a go and let me know how it works out for you assuming this is what you're looking for.

**Comment by edesdan** [comment]
Hi, thanks for the reply.
Yes sure I can use that but it seems like an hacky solution to the problem. I'd like to have something like a 'wait' phase on the startDockerContainer gradle task.

When I use maven with docker I use the fabric8 plugin that as something like that: https://dmp.fabric8.io/#start-wait . It is very handy because you know when the container is started is ready to be used because you were waiting for the specific condition to happen. 

I hope you can added something similar in the future.

**Comment by cdancy** [comment]
> Yes sure I can use that but it seems like an hacky solution

Admittedly it is but it gets the job done. A proper solution would be to stop polling on some condition but the current way things are wired up does not make that exactly easy to do.

> I'd like to have something like a 'wait' phase on the startDockerContainer gradle task

This is the OOTB solution I was referring to above that docker provides. The image itself would have to have this built in. You might try asking the maintainer of said image to add it.

> It is very handy because you know when the container is started is ready to be used because you were waiting for the specific condition to happen.

They're more/less using the same commands behind the scenes we are they are just tying them together into 1 easy to use call. This plugin specifically maps 1 docker endpoint to 1 task acting as a low-level building blocks for you to chain multiple tasks together: which is the gradle way after all. I do exactly what you're looking for here but within a corporate plugin we use behind the scenes. All folks have to do is call something like `startDatabase` and behind the scenes we invoke a chain of tasks from this plugin to make it all work seamlessly. We (this project) purposely do not try to create a public version of something similar as there could an infinite number of use-cases all of which we'd never be able to satisfy. Best to give the low-level building blocks to devs and let you guys decided how you want to further build things out and/or chain tasks together.

**Comment by gabrielhuff** [comment]
@cdancy I'm also trying to find a way to wait for a container to be ready be but can't do it even with the polling solution. Considering the snippet you posted:

```groovy
     1.   onNext { message ->
     2.     def foundMessage = message.toString() 
     3.     if (foundMessage.matches('Some string that says we are live')) {
-->  4.       throw new RuntimeException('SHORT-CIRCUIT-POLLING')
     5.     }
     6.   }
     7.   onError { exception ->
     8.     if(!exception.message.contains('SHORT-CIRCUIT-POLLING')) {
     9.       throw exception
     10.    }
     11.  }
```

Throwing an exception on line *4* won't trigger the `onError` callback. The log task will just fail instead.

I'm using version *3.1.0*

Since this is a relatively old post, is there a better way to do it? Something like waiting for health checks

**Comment by Wrayos** [comment]
You can try removing the `onError` completely if you throw a `StopExecutionException` - https://docs.gradle.org/2.2/javadoc/org/gradle/api/tasks/StopExecutionException.html

> A StopExecutionException is thrown by a Action or task action closure to stop execution of the current task and start execution of the next task.
> Note that throwing this exception does not fail the execution of the task or the build.

```
task waitForContainerStartup(type: DockerLogsContainer) {
    dependsOn startDockerContainer
    targetContainerId { createDockerContainer.getContainerId() }
    follow = true
    tailAll = true

    onNext { message ->
        def foundMessage = message.toString()
        if (foundMessage.contains("log message to know internal service is up")) {
            throw new StopExecutionException('CONTAINER-STARTED')
        }
    }
}

task stopDockerContainer(type: DockerStopContainer) {
    targetContainerId { createDockerContainer.getContainerId() }
}

task tmpRunIt(type: DefaultTask) {
    dependsOn waitForContainerStartup
    finalizedBy stopDockerContainer
}
```

Seems to be working for me.

**Comment by gabrielhuff** [comment]
@Wrayos Sounds good! I didn't know about this Gradle feature

Anyway, I think I found a better way to do it by using docker native Health Checks.
Health Checks can be [defined on the dockerfile](https://docs.docker.com/engine/reference/builder/#healthcheck) or [overridden at runtime](https://docs.docker.com/engine/reference/run/#healthcheck).

When creating an image using the Docker Java Application plugin, it is possible to define add a `HEALTHCHECK` instruction on the dockerfile by adding the following on the build file:

```groovy
dockerDistTar {
    instruction { "HEALTHCHECK CMD <command>" }
}
```

In my particular case, `<command>` was `curl -I --fail http://localhost:8080/ || exit 1` since I was building a web service image.

Then I needed to create a task that would wait for the container to be healthy. I didn't find a way to do it with the standard tasks from the Remote API plugin so I had to create a new one by using the docker remote API (subclassing `DockerExistingContainer` is a good starting point):

```groovy
class DockerWaitHealthyContainer extends DockerExistingContainer {

    @Input @Optional Integer timeout = 60
    @Input @Optional Integer checkInterval = 5

    @Override
    void runRemoteCommand(dockerClient) {
        logger.quiet "Waiting for container with ID '${getContainerId()}' to be healthy."

        long finalTime = System.currentTimeMillis() + timeout * 1000
        long sleepTime = checkInterval * 1000
        while(System.currentTimeMillis() < finalTime) {
            if (isHealthy(dockerClient)) return
            sleep(sleepTime)
        }
        if (!isHealthy(dockerClient)) throw new TimeoutException("Health check timeout expired")
    }

    private boolean isHealthy(dockerClient) {
        def command = dockerClient.inspectContainerCmd(getContainerId())
        def response = command.exec()
        def healthStatus = response.state.health.status
        return healthStatus == "healthy"
    }
}
```

And then adding a task to the project (assuming that `startContainer` is a `DockerStartContainer` task dependant on a `createContainer` task from the `DockerCreateContainer` type):

```groovy
task waitContainer(type: DockerWaitHealthyContainer) {
    dependsOn startContainer
    targetContainerId { createContainer.getContainerId() }
}
```

**Comment by cdancy** [comment]
Closing this issue as we now have multiple ways to solve the given problem which don't require any changes to this plugin.

**Comment by edesdan** [comment]
@gabrielhuff That's kind of nice solution. I think the DockerWaitHealthyContainer should be integrated into the library, maybe you can think of creating a PR for that?

**Comment by cdancy** [comment]
@edesdan @gabrielhuff while we've historically pushed back on things like this and kept the standard that this plugin is sort of a "low level" library from which you can build other plugins on top of I wouldn't be opposed to you sending in a PullRequest for this work and put it say under a new package at `com.bmuschko.gradle.docker.tasks.container.extras`. 

We've had a lot of great and useful suggestions/snippets over the years that we've turned down and I'm thinking that maybe for truly useful code that the greater community could take advantage of we can start making exceptions. @orzeh any thoughts?

**Comment by orzeh** [comment]
@cdancy I think we can do an exception here. `DockerWaitHealthyContainer` seems to be _docker related_ as it doesn't have any custom logic to check whether container is healthy but use standard docker capabilities. @edesdan @gabrielhuff please submit PR so we can start working on it :+1:

**Comment by gabrielhuff** [comment]
@edesdan @cdancy @orzeh Thanks for the feedback guys. I'll create a PR as soon as I have time to do so.

Note that the plugin currently does not define an API to setup health checks. If you take a look at the example I posted, I had to manually append `HEALTHCHECK CMD <command>` to the docker file. Docker also allows setting the health check instruction when running a container.Do you think it would also be interesting to add this functionality? Maybe on the `Dockerfile` and ``

**Comment by edesdan** [comment]
@gabrielhuff yes sure, it would be good but the most important is to add
the task to the gradle-docker-plugin library so we can use it directly, at
the moment I have to define it in every project. BTW I'm using it in my
project and I solved my problem with functional testing! Thanks!

**Comment by orzeh** [comment]
@gabrielhuff in terms of `HEALTHCHECK` instruction support please see #321 #431. To sum up we probably don't need anything more about that.

Waiting for the PR.

**Comment by gabrielhuff** [comment]
Pull request [here](https://github.com/bmuschko/gradle-docker-plugin/pull/485)

**Comment by cdancy** [comment]
Closing per merge of https://github.com/bmuschko/gradle-docker-plugin/pull/485

**Comment by aamielsan** [comment]
With `DockerWaitHealthyContainer` being deprecated and removed in newer plugin versions. What would be the alternative for waiting for a container to be ready?

We tried using the `StopExecutionException`:

```gradle
val startAndWaitLocalStack = register("startAndWaitLocalStack", DockerLogsContainer::class.java) {
    dependsOn(startLocalStack)

    follow.set(true)
    tailAll.set(true)
    containerId.set(startLocalStack.flatMap { it.containerId })

    onNext {
        if (this.toString().contains("Ready.")) {
            throw StopExecutionException("Container has started")
        }
    }
}
```

but encountering this message, without Gradle moving to the next task:

```
Failed to handle frame
org.gradle.api.tasks.StopActionException: Container has started
        at Build_gradle$3$startAndWaitLocalStack$1$2.execute(build.gradle.kts:73)
        at com.bmuschko.gradle.docker.tasks.container.DockerLogsContainer$2.onNext(DockerLogsContainer.groovy:160)
        at com.bmuschko.gradle.docker.tasks.container.DockerLogsContainer$2.onNext(DockerLogsContainer.groovy)
        at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onNext(AbstrAsyncDockerCmdExec.java:41)
        at com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:78)
        at com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:12)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by bmuschko** [comment]
@aamielsan There's no real alternative. It has been removed without replacement. You can copy the code from an older tag from this repo to your project if you need it.
