### ISSUE TITLE
about support of --shm-size when building docker image with gradle plugin ?

### ISSUE THREAD

**Issue by ousema2003** [bmuschko/gradle-docker-plugin#382]
Hi 

i'm used to build docker image with option --shm-size 
E.g : docker build  --shm-size =4g ...etc

Does --shm-size option is  supported when building docker image with docker-gradle-plugin ?
if yes , could you please provide an example how to use it  ?

Thanks in advance 

Best Regards,
Oussema

**Comment by ousema2003** [comment]
Bingo !!

THe solution was by increasing the shm on system level and add this line 
in build gradle on create docker file task ; 
	volume('/dev/shm','/dev/shm')

**Comment by cdancy** [comment]
@ousema2003 there is an option but we don't yet support or maybe expose it. I've heard of folks needing this for oracle based images and had it on my backlog to tackle at some point. I'm going to re-open this ISSUE if only to keep it visible that we really should have support for this.

**Comment by ousema2003** [comment]
thank you for ur feedback
