### ISSUE TITLE
Ensure all tests clean up after themselves

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#383]
After running integration tests we have loads of images and containers hanging around. We shouldn't be doing this and really need to set a standard either for cleaning up as we go or to have some sort of finally task that executes after integration tests have finished running and clean up then.

**Comment by edesdan** [comment]
I think this is very annoying. I had a quick look and maybe we can do something like this:
inside the AbstractFunctionalTest class we can store all created containers/images names and then we can clean up after tests. We need a way to use a docker client to remove all the containers based on container names. Something like this:
```

package com.bmuschko.gradle.docker

import org.gradle.testkit.runner.BuildResult
import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import spock.lang.Specification

abstract class AbstractFunctionalTest extends Specification {
    @Rule
    TemporaryFolder temporaryFolder = new TemporaryFolder()

    File projectDir
    File buildFile

    static final String TEST_IMAGE = "alpine"
    static final String TEST_IMAGE_TAG = "3.4"
    static final String TEST_IMAGE_WITH_TAG = "${TEST_IMAGE}:${TEST_IMAGE_TAG}"

    String dockerServerUrl

    def containers = []

    def setup() {
        projectDir = temporaryFolder.root
        buildFile = temporaryFolder.newFile('build.gradle')

        buildFile << """
            plugins {
                id 'com.bmuschko.docker-remote-api'
            }
			
            repositories {
                mavenCentral()
            }
        """

        setupDockerServerUrl()
        setupDockerCertPath()
        setupDockerPrivateRegistryUrl()

        buildFile << """
            task dockerVersion(type: com.bmuschko.gradle.docker.tasks.DockerVersion)
        """

        when:
        BuildResult result = build('dockerVersion')

        then:
        result.output.contains('Retrieving Docker version.')
    }

    def cleanupSpec() {
        println("Cleanup after all tests!")
        // remove all used containers (containers list)
    }

    private void setupDockerServerUrl() {
        dockerServerUrl = TestConfiguration.dockerHost

        if (dockerServerUrl) {
            buildFile << """
                docker.url = '$dockerServerUrl'
            """
        }
    }

    private void setupDockerCertPath() {
        File dockerCertPath = TestConfiguration.dockerCertPath

        if (dockerCertPath) {
            buildFile << """
                docker.certPath = new File('$dockerCertPath.canonicalPath')
            """
        }
    }

    private void setupDockerPrivateRegistryUrl() {
        String dockerPrivateRegistryUrl = TestConfiguration.dockerPrivateRegistryUrl

        if (dockerPrivateRegistryUrl) {
            buildFile << """
                docker.registryCredentials {
                    url = '$dockerPrivateRegistryUrl'
                }
            """
        }
    }

    protected BuildResult build(String... arguments) {
        createAndConfigureGradleRunner(arguments).build()
    }

    protected BuildResult buildAndFail(String... arguments) {
        createAndConfigureGradleRunner(arguments).buildAndFail()
    }

    private GradleRunner createAndConfigureGradleRunner(String... arguments) {
        def args = ['--stacktrace']
        if (arguments) {
            args.addAll(arguments)
        }
        GradleRunner.create().withProjectDir(projectDir).withArguments(args).withPluginClasspath()
    }

    protected String createUniqueImageId() {
        "gradle/${generateRandomUUID()}"
    }

    protected String createUniqueContainerName() {
        String containerName = generateRandomUUID()
        containers << containerName
        containerName
    }

    protected String createUniqueNetworkName() {
        generateRandomUUID()
    }

    private String generateRandomUUID() {
        UUID.randomUUID().toString().replaceAll('-', '')
    }
}
```

**Comment by cdancy** [comment]
> I think this is very annoying

@edesdan you and I both :) As long as we create all images/containers with a specific prefix I think that would make things easier (which we do to some extent).

There are 2 avenues to tackle here: images and containers: 

For removing images we have the `DockerListImages` task which we can use to get all images, match against our prefix, and create a `DockerRemoveImage` command on the fly to delete.

For removing containers we don't have something similar and may make sense to code a new task. If it's easier, as you say, to keep a list of created containers, so long as things don't look too messy, I'm OK with that.

If you want to tackle images first I can look at what it would take to add another say `DockerListContainers` task to make the second part easier and knock that out as well.

**Comment by cdancy** [comment]
Shouldn't be too bad to add a `DockerListContainers` task given this:

https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/ListContainersCmd.java

**Comment by edesdan** [comment]
Yeah, sure I can look at that. I was wondering, can we use like a docker-client to submit commands directly to the docker daemon. It would make everything easier I guess. That way I would be able to do something like:

```
def cleanupSpec() {
        println("Cleanup after all tests!")
        // remove all used containers (containers list)
        client.execRemoteCommand("docker rm [containers list] ")
    }
``` 

Sorry I have just started to look at the code, maybe I may not have a clear picture yet.

**Comment by cdancy** [comment]
You can do that as well. We have a few tests which exercise the AbstractDockerTask that allows you to do this very thing.

**Comment by edesdan** [comment]
OK cool, do you have an example? Which class I can use as reference?

**Comment by cdancy** [comment]
@edesdan have a look at this previous ISSUE:

https://github.com/bmuschko/gradle-docker-plugin/pull/199/files#diff-aa336f9939c800838bf9ddecc8d69c58R101

**Comment by edesdan** [comment]
@cdancy ok I think I found a clean solution for this to both removing the images and containers as well. I'm working on it. Let you know.

**Comment by cdancy** [comment]
@edesdan that would be a life saver ;)

**Comment by childnode** [comment]
just my 50¢: can't we just use [dind](https://hub.docker.com/r/library/docker/tags/) and throw away that single build env docker container afterwards?

**Comment by orzeh** [comment]
> Although running Docker inside Docker is generally not recommended, there are some legitimate use cases, such as development of Docker itself.

I don't think we have here _legitimate use case_.

**Comment by childnode** [comment]
yeah, I read that, I wouldn't recommend it to a self build productive environment - but only because I didn't got any "legitmate arguments" why not to do ;)
Anyhow it seems not that unstable or problematically since http://rancher.com/rancher-os/ is using it e.g., another popular one is gitLab which gives official examples running tests in dind ... anyhow ... your choice ... just thought this would be a shortcut to solve this issue ;)

**Comment by cdancy** [comment]
@bmuschko I think as a goal for some release in the future we make it a priority to ensure each test cleans up after itself. Any custom image/container created should be removed by the test. As things stand now the docker environment is left pretty dirty afterwards.

**Comment by bmuschko** [comment]
@cdancy I already made some changes to functional tests to ensure that images/containers are removed. It's far from done though. This should be easier now that we have the auto-remove feature. Definitely needed!

**Comment by cdancy** [comment]
Closing for now if only to trim down on the number of open issues that don't need to be open.
