### ISSUE TITLE
DockerJavaApplicationPlugin configuration seems impossible with gradle script kotlin

### ISSUE THREAD

**Issue by JLLeitschuh** [bmuschko/gradle-docker-plugin#385]
I'm trying to use this awesome plugin in my [Gradle Script Kotlin (GSK)](https://github.com/gradle/gradle-script-kotlin) build.

The `DockerJavaApplicationPlugin` is dynamically added to the `DockerExtension` at runtime using "Groovy metaClass hackery" (quoting the PM of GSK).

There doesn't seem to be a good way to configure the `DockerJavaApplicationPlugin` without using some reflection trickery.

----

The PM of GSK offered this solution that works (and might be nice to have documented in the README).

```kotlin
configure<DockerExtension> {
    with (getProperty("javaApplication") as DockerJavaApplication) {
       // your configuration code here
    }
}
```

**Comment by cdancy** [comment]
@JLLeitschuh do you have a snippet of what you're trying to do and a stracktrace to show what popped? It might be that is the only way to go about things. Haven't played around with Kotlin yet and so can't say too much on that end.

@bmuschko @orzeh any thoughts one way or another?

**Comment by JLLeitschuh** [comment]
In gradle script kotlin doing this:
```kotlin
docker {
    javaApplication {
    }
}
```
won't give you a meaningful stack trace, it just won't compile.

Kotlin is a statically typed language so you need statically available fields/methods for it to compile.

In order to get the same syntax parody between kotlin and groovy you need to do this:

```kotlin
docker {
    javaApplication {

    }
}


// This is pretty normal, you have to do this with pretty much all plugins
/**
 * Retrieves or configures the [docker][com.bmuschko.gradle.docker.DockerExtension] project extension.
 */
fun Project.`docker`(configure: com.bmuschko.gradle.docker.DockerExtension.() -> Unit = {}) =
    extensions.getByName<com.bmuschko.gradle.docker.DockerExtension>("docker").apply { configure() }

// This is unusual; it works; but it's not particularly pretty.
fun com.bmuschko.gradle.docker.DockerExtension.javaApplication(configure : com.bmuschko.gradle.docker.DockerJavaApplication.() -> Unit = {}) =
    with(getProperty("javaApplication") as com.bmuschko.gradle.docker.DockerJavaApplication) {
        configure()
    }
```

**Comment by orzeh** [comment]
@JLLeitschuh @cdancy In order to support GSK we probably must rewrite `DockerJavaApplicationPlugin` logic. The question is if we should because this functionality can be achieved using regular tasks from `DockerRemoteApiPlugin`. @JLLeitschuh maybe you should create your own plugin which will be _Kotlin-friendly_ and meet your functional requirements?

**Comment by cdancy** [comment]
I think @orzeh has it right and don't think we want to rewrite any major portions of our codebase at this point. The snippet above, while maybe not potentially pleasing to the eye, will work as you noted so I would go with that.

**Comment by JLLeitschuh** [comment]
That's what I plan to do.
On the whole the plugin is solid and I'm really happy with the features it offers. I don't want to reinvent the wheel. However, its rough around the edges when it comes to using it in a strongly typed context.

Would it make sense to update the README to note the above syntax to get this plugin to work with GSK?

**Comment by cdancy** [comment]
@JLLeitschuh send in a PR for the documentation change and we'd be happy to take it!

**Comment by JLLeitschuh** [comment]
Do you have a specific location in the readme you'd like to see it? At the very bottom or just below the `javaApplication` example?

**Comment by cdancy** [comment]
@JLLeitschuh I would say put something under the `FAQ` section in the README.
