### ISSUE TITLE
Allow all Dockerfile instructions in javaApplication.exec closure

### ISSUE THREAD

**Issue by lanwen** [bmuschko/gradle-docker-plugin#389]
Now it is possible to define only `CMD` end `ENTRYPOINT` instructions.

It will be very cool to allow any instructions - as for now it's no way to set additional `RUN` or `ENV` instruction.

Also documentation refers (https://github.com/bmuschko/gradle-docker-plugin#exec-property) to Dockerfile task, but actually it is the only subset of this task.

**Comment by cdancy** [comment]
@lanwen you can use a [generic instruction as described here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L86). We also have a templating feature which one can use as well within that same file. Take a look through functional tests as we have quite a few examples using these.

**Comment by lanwen** [comment]
For example, with `gradle dockerBuildImage`:

```groovy
docker {
    javaApplication {
        baseImage = 'java'
        maintainer = 'Kirill Merkushev (github:lanwen)'
        ports = [8080]
        tag = "${dockerRepoPrefix}${project.name}:${project.version}"
        exec {
            instruction {'ENV envvar envval'}
            defaultCommand "./${project.name}-${project.version}/bin/${project.name}",
                    '--spring.profiles.active=${CLOUD_ENVIRONMENT:dev}',
                    '--server.port=${CLOUD_HTTP_PORT:8080}'
        }
    }
}
```
I get:

```
* Where:
Build file '/project/build.gradle' line: 77

* What went wrong:
A problem occurred evaluating project ':project'.
> No signature of method: static com.bmuschko.gradle.docker.tasks.image.Dockerfile.instruction() is applicable for argument types: (build_e8pubbqu4a1jtq5qf3ttrwjjd$_run_closure4$_closure7$_closure8$_closure9) values: [build_e8pubbqu4a1jtq5qf3ttrwjjd$_run_closure4$_closure7$_closure8$_closure9@75d95050]
  Possible solutions: instruction(groovy.lang.Closure), instruction(java.lang.String), getInstructions()
```

In [Application Functional tests](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginFunctionalTest.groovy) I cant find any `env` or `run` custom directives.


So the question is - should I just drop gradle-application-plugin and implement all this functionality from scratch with base tasks, or it can be fixed inside of application-plugin?

**Comment by orzeh** [comment]
@lanwen you are right, `exec` in `javaApplication` is of type [CompositeExecInstruction](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L831) which only supports `defaultCommand` and `entrypoint` _instructions_.

I think it would be better to use generic tasks than further change `DockerJavaApplication` to add `ENV` and/or `RUN` commands.

**Comment by lanwen** [comment]
But it's very inconvenient to implement all the steps of application plugin if I only want to add one additional `env` variable... :'( Why not just add base _instruction_ dsl here?

**Comment by orzeh** [comment]
@lanwen ok, I understand your case. What about using [templating feature](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L55) in `Dockerfile` task:
````gradle
project.tasks.getByName("dockerDistTar").instructionsFromTemplate file("Dockerfile.tmpl")
````

In `Dockerfile.templ` put all `ENV` and `RUN` instructions you need.

Hope it helps.

**Comment by lanwen** [comment]
Such a cool workaround :) Yep, it works! Thanks!

Also in the form 

```gradle
project.tasks.getByName("dockerDistTar").instruction {'RUN ls -la'}
```

maybe you can add a mention about this to docs?

**Comment by orzeh** [comment]
@lanwen feel free to submit PR if you think docs need updates.
