### ISSUE TITLE
dockerPushImage reruns dockerBuildImage task without checking if it is upto date

### ISSUE THREAD

**Issue by vasanth-asokan** [bmuschko/gradle-docker-plugin#39]

**Comment by vasanth-asokan** [comment]
@bmuschko said the following in an email conversation

>Right now, the build image command does not support up-to-date checks at the moment for various technical reasons. The command should run very quickly though. Can you open an issue on GitHub for this? I need to look into this again.

**Comment by bmuschko** [comment]
Oh, I thought you mean the task that creates the Dockerfile. I am not sure how you'd be able to avoid running the `dockerBuildImage` task. You somehow have to compare the existing image (if it does exist) with the image you are about to build. I don't think there's even a capability to compare images in Docker. Let me know if you have some smart ideas here but I don't think this is easy or even possible.

**Comment by vasanth-asokan** [comment]
Hi Ben,

Not sure if I have anything particularly useful to add in terms of
specifics, but my naive expectation was -- nothing in the project source
files, build.gradle, or docker input artifacts (such as Dockerfile) have
changed. Therefore, running dockerPushImage, shouldn't re-run
dockerBuildImage as the timestamp of the last docker image created via the
previous dockerBuildImage will be newer than all the source artifacts that
result in the image. Shouldn't this be possible to declare / detect via
each gradle task's inputs and outputs?

Vasanth

**Comment by bmuschko** [comment]
> Not sure if I have anything particularly useful to add in terms of
specifics, but my naive expectation was -- nothing in the project source
files, build.gradle, or docker input artifacts (such as Dockerfile) have
changed. 

Up-to-date checks require you to define inputs and outputs to work properly. A change to the `build.gradle` cannot be defined as input. All the other inputs you mention sound good. However, the output is the image created on the remote Docker machine. To be able to check a timestamp, I'd have to have the timestamp (the build image response doesn't contain a timestamp) store it and make a remote call to get the latest. While this is probably possible somehow, this sounds pretty complex and error-prone to me.
