### ISSUE TITLE
Add other CPU related parameters to DockerCreateContainer

### ISSUE THREAD

**Issue by dlachica** [bmuschko/gradle-docker-plugin#396]
It would be helpful in managing server resource if you could add other CPU related options for docker.
Other options can be seen here https://docs.docker.com/engine/admin/resource_constraints/#cpu 
We need specifically --cpus=<value> value exposed (and the other params) so that we could stop some containers from hogging resources.

Thanks!

**Comment by orzeh** [comment]
@dlachica `--cpus=value` is supported since docker 1.13 and AFAIK it is not already implemented in `docker-java` which we use in this plugin. However, other options are available there. Can you submit PR?

**Comment by dlachica** [comment]
I see. I'll get the docker-java people do some enhancements first. Should I close this issue for the meantime?

**Comment by orzeh** [comment]
@dlachica leave it open

**Comment by cdancy** [comment]
@dlachica I would just add that when you open an ISSUE with those guys please link to this ISSUE so that we can follow what's going on.

**Comment by dlachica** [comment]
They've introduced a solution at https://github.com/docker-java/docker-java/pull/867 . The solution uses --cpu-quota and --cpu-period.

**Comment by orzeh** [comment]
@dlachica so I assume it fixes your issue and we can close this?

**Comment by cdancy** [comment]
@orzeh no I think we still need to expose these properties on our end.

**Comment by dlachica** [comment]
@cdancy That's right. The DockerCreateContainer task has only cpuSet exposed as of 3.0.7

**Comment by cdancy** [comment]
@dlachica care to submit a PR for this change? Looking at that `docker-java` thread it would appear the functionality is already present we just need to expose it here.

**Comment by cdancy** [comment]
Closing this issue as it appears the conversation has died down. If someone wants to submit a PR we'd be more than happy to review.
