### ISSUE TITLE
docker tag not populate the value

### ISSUE THREAD

**Issue by RameshMuthuraj** [bmuschko/gradle-docker-plugin#397]
````
task dockerBuildImage(type: DockerBuildImage) {
    dependsOn build
    group = DOCKER_GROUP
 
    url = 'unix:///var/run/docker.sock'
    inputDir = project.projectDir
    dockerFile = project.file('./devops/docker/' + '/Dockerfile')
    tag = 'Ramesh'
    registryCredentials = dockerRegistryCredentials
}
````

Output 
````
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

<none>              <none>              90bbd13f2ad2        5 minutes ago       541 MB
````

Still image tag shows as `<none>`

**Comment by orzeh** [comment]
@RameshMuthuraj can you paste gradle build output? Also `tag` property should probably be in `image_name:tag` format. Try: 
````
task dockerBuildImage(type: DockerBuildImage) {
   //...
   tag = 'Ramesh:0.0.1'
   //...
}
````

**Comment by RameshMuthuraj** [comment]
still same

[ramesh@jenkins ]$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              437939ca3152        42 seconds ago      649 MB
centos              7                   3bee3060bfc8        2 weeks ago         193 MB

**Comment by cdancy** [comment]
@RameshMuthuraj I typically use `DockerBuildImage` like so:

```
task buildImage(type: com.bmuschko.gradle.docker.tasks.image.DockerBuildImage) {
    noCache = true
    inputDir = projectDir
    tag = "${project.dockerHost}/${project.dockerRepo}:${project.dockerTag}"
}
```
I've done this testing with the latest and greatest docker so if things are not working for you if might be a config issue. If you're still having a problem can you create a repo on github that recreates this issue and is reproducible that we can give a go?
