### ISSUE TITLE
Turn off docker-java DEBUG logging

### ISSUE THREAD

**Issue by dfernandezm** [bmuschko/gradle-docker-plugin#398]
I cannot find anywhere in docs how to turn off annoying DEBUG logging during image build process:

```
15:32:30.932 [dockerjava-jaxrs-async-0] DEBUG c.g.d.c.c.BuildImageResultCallback - BuildResponseItem[stream=Successfully built ec1b9c398b37
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
15:32:30.949 [dockerjava-jaxrs-async-0] DEBUG org.apache.http.wire - http-outgoing-0 << "0[\r][\n]"
15:32:30.949 [dockerjava-jaxrs-async-0] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
15:32:30.949 [dockerjava-jaxrs-async-0] DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection [id: 0][route: {}->unix://localhost:80] can be kept alive indefinitely
1
```

Is there any setting in build.gradle docker {} or related I can set to turn this off? Thank you

**Comment by cdancy** [comment]
@dfernandezm that would only happen if you ran gradle with `--debug`. Are you saying that you're seeing this without that?

**Comment by cdancy** [comment]
Closing as this appears to be a user triggered issue and not something relevant to the plugin.

**Comment by dfernandezm** [comment]
This was happening without --debug. I managed to get rid of docker-java by removing some spurious classpath aggregations and configurations.

If I see it again I will reopen. Thank you.

**Comment by cdancy** [comment]
@dfernandezm would you mind telling us what dependencies you removed? You surely should not be seeing those debug messages unless some logback config was on the classpath saying to pipe debug to stdout.

**Comment by dfernandezm** [comment]
@cdancy The build file had previous plugins in it and some unnecessary classpath:

* Removed `classpath 'com.github.docker-java:docker-java:3.0.9'` from `buildscript` `dependencies` closure.
* Removed `apply plugin: com.bmuschko.gradle.docker.DockerJavaApplicationPlugin`
* Removed a `doFirst` block with `        classpath = configurations.dockerConf + sourceSets.main.compileClasspath` line in it inside a `buildImage` task
* Also removed `classpath =  configurations.compile` from inside that task

It is possible that docker-java is running under DEBUG logging somehow.

**Comment by sundarrajanm** [comment]
I also faced the same issue today. After removing the below entries the noisy log vanished.

- Removed a `doFirst` block with `classpath = configurations.dockerConf + sourceSets.main.compileClasspath` line in it inside a buildImage task
- Also removed `classpath = configurations.compile` from inside that task

Thanks @dfernandezm
