### ISSUE TITLE
DockerCreateContainer task in gradle

### ISSUE THREAD

**Issue by maverickuser** [bmuschko/gradle-docker-plugin#40]
I have added the DockerCreateContainer task and want to run a image.
Something like this
docker run -d -p 80:80 -p 8125:8125/udp -p 8126:8126 --name kamon-grafana-dashboard kamon/grafana_graphite

added task in gradle script 
task createMyAppContainer(type: DockerCreateContainer) {
    targetImageId { 2124414a69ae } 
    exposedPorts =['80/tcp':80,'8125/udp':8125,'8126':8126]
}

Though as per remote API it may be
    exposedPorts = {"80/tcp":{80},"8125/udp":{8125},"8126/tcp":{8126}}

can anyone guide /point themistake?

**Comment by bmuschko** [comment]
Your declaration looks correct to me.

> Though as per remote API it may be
exposedPorts = {"80/tcp":{80},"8125/udp":{8125},"8126/tcp":{8126}}

Can you elaborate? I don't quite understand that comment.

**Comment by maverickuser** [comment]
I am trying to create container of  grafana_graphite image on docker using gradle remote plugin (com.bmuschko:gradle-docker-plugin:2.0.3)

task createMyAppContainer(type: DockerCreateContainer) {
    targetImageId { e45a5af57b00 } 
    exposedPorts = {"80/tcp":{80},"8125/udp":{8125},"8126/tcp":{8126}}
}
 the container is not created.
Can you please guide or give example howto set he exposed ports

**Comment by bmuschko** [comment]
You are not using the correct data types for declaring the [exposedPorts property](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy#L95). In the example above you are assigning a closure.

**Comment by maverickuser** [comment]
I tried this.The build task runs but it does not create the container.
task createMyAppContainer(type: DockerCreateContainer) {
    targetImageId {2124414a69ae} 
    exposedPorts = ["80/tcp":80,"8125/udp":8125,"8126/tcp":8126]
}

**Comment by bmuschko** [comment]
I'd need more information on what happens. Do you get an error message, does the build fail or what happens exactly?

**Comment by maverickuser** [comment]
The build is successful without any errors

**Comment by bmuschko** [comment]
Sounds like it worked then. Did you check if the container is listed in your Docker instance with `docker ps -l`?

**Comment by maverickuser** [comment]
Not sure why but it didn't start.Just copying the configuration.
I can access docker remote API (rest api like list container etc)
docker {
    url = 'http://192.168.59.103:2375'
}
import com.bmuschko.gradle.docker.tasks.container.*

task createMyAppContainer(type: DockerCreateContainer) {
    targetImageId {2124414a69ae} 
    exposedPorts =['80/tcp':80,'8125/udp':8125,'8126':8126]
}

**Comment by bmuschko** [comment]
Starting the container is a different command: `DockerStartContainer`.

**Comment by maverickuser** [comment]
Thanks for the info.
I added the DockerStartContainer task too.But still not starteed

task createMyAppContainer(type: DockerCreateContainer) {
    targetImageId {2124414a69ae} 
    exposedPorts =['80/tcp':80,'8125/udp':8125,'8126':8126]
}
task startMyAppContainer(type: DockerStartContainer) {
    dependsOn createMyAppContainer
    targetContainerId { createMyAppContainer.getContainerId() }
}

**Comment by bmuschko** [comment]
Did you check the list of running containers on Docker or how do you make this determination?

**Comment by maverickuser** [comment]
I ran these command for list of ri
docker ps  and docker ps -l
also i checked the historyfor the image
docker history <image id>

**Comment by bmuschko** [comment]
Use `docker ps -a` instead.

**Comment by maverickuser** [comment]
Not coming up :(

**Comment by bmuschko** [comment]
No sure. Works fine for me. Please provide a full build on GitHub so I can try it out myself.

**Comment by maverickuser** [comment]
Sorry, got busy in some other task
task createMyAppContainer(type: DockerCreateContainer) {
targetImageId {'2124414a69ae'} 
exposedPorts =['80/tcp':80,'8125/udp':8125,'8126':8126]
}
task startMyAppContainer(type: DockerStartContainer) {
dependsOn createMyAppContainer
targetContainerId { createMyAppContainer.getContainerId() }
}
running
gradle startMyAppContainer --stacktrace
gives
by: java.lang.reflect.InvocationTargetException
 at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.createInternetProtocol(DockerThreadContextClassLoader.groovy:149)
 at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.createExposedPort(DockerThreadContextClassLoader.groovy:139)
 at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$createExposedPort$0.call(Unknown Source)
 at com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer$_setContainerCommandConfig_closure3.doCall(DockerCreateContainer.groovy:19

 at com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer.setContainerCommandConfig(DockerCreateContainer.groovy:192)
Caused by: java.lang.IllegalArgumentException: Error parsing Protocol '80/tcp'

**Comment by maverickuser** [comment]
checked the code
changed the task to 
task createMyAppContainer(type: DockerCreateContainer) {
targetImageId {"2124414a69ae"} 
exposedPorts =["tcp":80,"udp":8125,"tcp":8126]
}

It worked  :+1: 
Thanks
