### ISSUE TITLE
Not supporting relative path 

### ISSUE THREAD

**Issue by RameshMuthuraj** [bmuschko/gradle-docker-plugin#400]
My gradle task
````groovy
task dockerBuildImage(type: DockerBuildImage) {
    dependsOn build
    group = DOCKER_GROUP

    url = 'unix:///var/run/docker.sock'
    inputDir = project.projectDir
    dockerFile = project.file('./devops/docker/Dockerfile')
    tag = '$applicationName:$commitid'
    registryCredentials = dockerRegistryCredentials
}
````
==================
**Dockerfile**
````Dockerfile
FROM centos:7

# Install dependencies
RUN yum update -y
RUN yum install -y git curl java epel-release
RUN yum install -y python-pip
RUN pip install boto3

# Install app
## Expects Build ran already and artifacts available in target
ADD build/libs/*.jar /opt/ups.jar
ADD devops/docker/application.properties /opt/application.properties
ADD devops/docker/scripts/startapp.py /opt/startapp.py
ADD devops/docker/scripts/kms_ops.py /opt/kms_ops.py
ADD devops/cert/stage.cert /opt/cert
RUN mkdir /opt/logs

# Configure UPS

EXPOSE 8080
````
====================
**Folder structure**

├── devops
│   ├── cert
│   │   └── stage.cert
│   ├── docker
│   │   ├── application.properties
│   │   ├── Dockerfile
│   │   └── scripts
│   │       ├── kms_ops.py
│   │       └── startapp.py
│   ├── scripts -> docker/scripts
│   └── terraform
│       ├── container_def
│       │   ├── dev-container.json
│       │   └── pt-container.json
│       ├── dev.tfvars
│       ├── main.tf
│       ├── outputs.tf
│       ├── pt.tfvars
│       ├── required-policy
│       ├── terraform.tfstate.backup
│       └── vairables.tf
├── Jenkinsfile
├── service
│   ├── build.gradle
│   ├── devops -> ../devops
│   ├── gradle
│   │   └── wrapper
│   │       ├── gradle-wrapper.jar
│   │       └── gradle-wrapper.properties
│   ├── gradle-common
│   │   ├── artifactory.gradle
│   │   └── versioning.gradle
│   ├── gradle.properties
│   ├── gradlew
│   ├── gradlew.bat

I'm getting error while copy the docker properites when buyilding a docker image

Error:- 

````
---> da8bf1dbf2bb
Removing intermediate container 714ed7517a33
Step 6/13 : ADD build/libs/*.jar /opt/ups.jar
---> 7d3f7ec273b3
Removing intermediate container ee4f93a725ce
Step 7/13 : ADD devops/docker/application.properties /opt/application.properties
:dockerBuildImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerBuildImage'.
> Could not build image: lstat devops/docker/application.properties: no such file or directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
````

**Comment by orzeh** [comment]
@RameshMuthuraj you define Docker build context as `inputDir = project.projectDir` so file `devops/docker/application.properties` is outside of it and that is causing the error.
