### ISSUE TITLE
Provide static accessor functions for javaApplication extension on DockerExtension

### ISSUE THREAD

**Issue by JLLeitschuh** [bmuschko/gradle-docker-plugin#406]
Follow On discussion to #385 as I can't re-open that issue.

I came up with a far better solution for providing the static accessor functions than simply documenting it in the readme. I implemented this solution successfully in the JUnit 5 gradle plugin.

The pr:
https://github.com/junit-team/junit5/pull/904

The commit:
https://github.com/junit-team/junit5/commit/4a2e8e04ecf054c01841c5f863d8ca5af9acd0d9

If you look over the PR you can see that this is the solution that [Stefan Oehme](https://github.com/oehme) (Gradle project maintainer) supports.

I propose adding the following method to the `DockerExtension`:

```groovy
    void javaApplication(org.gradle.api.Action<DockerJavaApplication> closure) {
        closure.execute(getProperty("javaApplication") as DockerJavaApplication)
    }
```

While in there it may be nice to add static methods for `DockerExistingContainer.targetContainerId` and `DockerCreateContainer.targetImageId`. This would make it so that the README section added in #388 could be removed.

**Comment by cdancy** [comment]
@JLLeitschuh that all looks fine to me. Care to put together a PR with this?

**Comment by JLLeitschuh** [comment]
Yep. Might take me a few days though. Just wanted to get it cleared as a good way to solve the problem.

**Comment by cdancy** [comment]
@JLLeitschuh I agree and it does look clean. Feel free to add those static methods as well if you're poking around as I think those would be helpful.

**Comment by bmuschko** [comment]
I am not very fond of this change as there's no separation of concerns. The `DockerExtension` belongs to the `DockerRemoteApiPlugin` and doesn't have any knowledge about other plugins that apply it internally e.g. the `DockerJavaApplicationPlugin`.

With this approach you introduced strong coupling between those plugins and would not be able to physically separate them. At the moment this approach only works as all classes are bundled in a single JAR file. I am going to look into some better options.

**Comment by JLLeitschuh** [comment]
@bmuschko sounds like your extension to be something like `ExtensionAware`?

**Comment by bmuschko** [comment]
@JLLeitschuh It automatically is `ExtensionAware` as soon as you register it via the `ExtensionContainer`. See [this](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplicationPlugin.groovy#L52) for example.

I just talked to the Gradle Kotlin DSL team and they said that 4.8 [automatically supports discoverability in the IDE for the Kotlin DSL](https://github.com/gradle/kotlin-dsl/blob/9f2f138a6c57c346986b36798b19d9eb946d0ef5/subprojects/integ-tests/src/test/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaAccessorsIntegrationTest.kt#L454). That means we can simply remove the methods. I am happy for you to give it a shot after we make the change to let us know if it's still working as expected.

**Comment by JLLeitschuh** [comment]
I'd recommend adding a unit test that tries calling these API's after you remove them to make sure that Gradle generates them correctly for your use case.

**Comment by bmuschko** [comment]
@JLLeitschuh I made the relevant changes in https://github.com/bmuschko/gradle-docker-plugin/commit/f1173b751520c93861e76887b0725f966e4e8fcb. The important piece is the removal of the methods on `DockerExtension` and the [functional test case for the Kotlin DSL](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/KotlinDslCompatibilityFunctionalTest.groovy). Let me know if I am missing something.

**Comment by JLLeitschuh** [comment]
LGTM!
