### ISSUE TITLE
add clean task variants for default task lifecycles

### ISSUE THREAD

**Issue by childnode** [bmuschko/gradle-docker-plugin#407]
While [default tasks are defined](https://github.com/bmuschko/gradle-docker-plugin#default-tasks), the gradle auto populated `clean<Taskname>`'s simply do nothing but they should revert what the normal task do.

so e.g. `dockerBuildImage` should get a companion `cleanDockerBuildImage`.

perhaps, Gradle 4 will help us here [with the new `PropertyState<String>` provider](https://docs.gradle.org/4.0/release-notes.html#public-type-for-representing-lazily-evaluated-properties) that can be used to re-read the settings applied to `dockerBuildImage.imageId`

**Comment by childnode** [comment]
as for the moment, some code like this works for me BUT in some cases it has to be applied/set up before the plugin is applied, else task  `:cleanDockerBuildImage` is auto-defined of type `org.gradle.api.tasks.Delete` and can't be redefined

```groovy
    task cleanDockerBuildImage(type: com.bmuschko.gradle.docker.tasks.image.DockerRemoveImage) {
        conventionMapping.imageId = {
            project.tasks.getByName(com.bmuschko.gradle.docker.DockerJavaApplicationPlugin.BUILD_IMAGE_TASK_NAME).getTag()
        }
    }
```

**Comment by orzeh** [comment]
@childnode I think only the `cleanDockerBuildImage` task make sense. Feel free to submit PR.

**Comment by childnode** [comment]
mhh.. yep, a minor fix should be added for `dockerDistTar` as a `Dockerfile` task which depends on `dockerCopyDistResources` but `cleanDockerDistTar` doesn't depend on `cleanDockerCopyDistResources` so tar is not removed but Dockerfile

looking forward to do the PR

**Comment by orzeh** [comment]
@childnode I'm closing it now. We can reopen when PR will be ready.
