### ISSUE TITLE
Can't push tagged image created with docker-java-application to private repo

### ISSUE THREAD

**Issue by david-resnick** [bmuschko/gradle-docker-plugin#41]
This configuration 
```
docker {
	javaApplication {
		tag = 'private-registry.company.com:5000/namespace/project:latest'
	}
}
```
fails with this outcome:
```
...
:dockerPushImage
Pushing image with name 'private-registry.company.com:5000/namespace/project:latest'.
:dockerPushImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerPushImage'.
> Invalid repository name (facts-repo:latest), only [a-z0-9-_.] are allowed
```

This can be fixed by overriding the dockerPushImage convention defaults:

```
dockerPushImage.imageName = 'private-registry.company.com:5000/namespace/project'
dockerPushImage.tag = 'latest'
```

The real problem here is the confusing way docker chose to have images named, tagged and pushed. Sometimes a tag is just a tag, while other times it includes the registry, namespace and "repository".

**Comment by bmuschko** [comment]
I agree, it's really a Docker issue. Would you care for providing an integration test for this use case?

**Comment by david-resnick** [comment]
A (currently) failing integration test?

Is there a setup list that describes how I can successfully run the integration tests you already have? I tried running them yesterday and had failures. I also aborted them before they finished because they were taking a very long time.

**Comment by bmuschko** [comment]
> A (currently) failing integration test?

No, it would a a new integration test.

Is there a setup list that describes how I can successfully run the integration tests you already have? 
> Not really. Currently, they assume TLS to be disabled. However, this can be made configurable. Didn't have the time to do it yet.

**Comment by bmuschko** [comment]
This might just be a Docker Java issue (see [issue](https://github.com/docker-java/docker-java/issues/190)).

**Comment by johnrengelman** [comment]
This is working fine for me:
```
project.docker.javaApplication {
  tag = "registry.mydomain.com/myapp:latest"
}

project.tasks.dockerPushImage {
  imageName = project.tasks.dockerBuildImage.getTag().split(':')[0]
  tag = project.tasks.dockerBuildImage.getTag().split(':')[1]
  registry = new DockerRegistry(url: 'http://registry.mydomain.com/v1', username: 'user', password: 'pass', email: 'user@mydomain.com')
}
```

**Comment by holgerstolzenberg** [comment]
Same problem here, but was able to workaround. This is what works for me:

```groovy
docker {
  url = property 'dockerHostUrl'

  registryCredentials {
    username = property 'artifactoryUser'
    password = property 'artifactoryPassword'
  }

  javaApplication {
    baseImage = property 'baseImage'
    maintainer = property 'maintainer'
  }
}

dockerPushImage {
  imageName = "${dockerRegistry}" + "/" + "${dockerGroup}" + "_any_application"
  tag = project.version.toLowerCase()
}
```

But it would be nice to have it configured just within the `docker` section.

**Comment by perryn** [comment]
We just ran into this too. I think it is actually a problem with the plugin code.

The code here sets the image name on the push task to the 'full name' (including the tag)
https://github.com/bmuschko/gradle-docker-plugin/blob/3cac3b34fdbcf662674f0395a4c5a91665592482/src/main/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPlugin.groovy#L122

The code here sets the image name AND then tries to set the tag, which implies to me that it is expecting 'image name' to mean WITHOUT the tag

https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy#L52

If we set the imageName on the push command directly to the name without the tag, then everything seems to work.

**Comment by saadmufti** [comment]
I hit this too when trying to use with my company private repo. Is the recommendation to do the workaround as mentioned above or is there a fix in the works?

**Comment by cdancy** [comment]
@perryn interested in sending in a PR?

**Comment by cdancy** [comment]
Closing issue. Concerns above are valid but we are simply copying the semantics provided by docker-java as we build upon that library here. When version 3.0.0 is released of that library we'll circle back and see if we can correct some of these mis-understandings.

**Comment by kgeis** [comment]
I'm running into this now with gradle-docker-plugin 3.6.1. docker-java 3.0.0 was released in June 2016. Can we re-open this issue?

**Comment by kgeis** [comment]
Thanks for the workaround, @johnrengelman. I made it DRYer and Groovier:
```
project.tasks.dockerPushImage {
    (imageName, tag) = project.tasks.dockerBuildImage.tag.split(':')
}
```
