### ISSUE TITLE
plugins.gradle.org - outdated version

### ISSUE THREAD

**Issue by kucharzyk** [bmuschko/gradle-docker-plugin#411]
Version 3.0.12 was released few days ago but plugins.gradle.org still shows 3.0.8 as latest version

**Comment by cdancy** [comment]
@kucharzyk asking around now...

**Comment by jordanjennings** [comment]
Any updates here? I'm hitting the issue from #366 which should be fixed in 3.0.12. Thanks!

**Comment by jordanjennings** [comment]
Looks like the latest release is in jcenter, just in case anyone else reading this also wasn't aware. Upgrading to release 3.0.11 fixes the issue with the credentials file. Thanks!

**Comment by cdancy** [comment]
Release 3.0.12 is definitely in jcenter/maven. Folks can source from there.

**Comment by jordanjennings** [comment]
@cdancy It's not in maven.

https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.bmuschko%22%20AND%20a%3A%22gradle-docker-plugin%22

**Comment by cdancy** [comment]
@bmuschko it seems our last few releases have not been published to maven? I believe this is hooked up on jcenter/bintray to push to maven. Maybe something went sideways?

**Comment by bmuschko** [comment]
@cdancy Maven syncing needs to be triggered manually on Bintray. I can do it quick. 

@jordanjennings Why can't you just get the artifact from JCenter? You just have to declare another repository in your build. BTW: Resolving from JCenter is faster than from Maven Central and also proxies Maven Central.

**Comment by cdancy** [comment]
> Maven syncing needs to be triggered manually on Bintray

@bmuschko really? There must be a way to automate this. I'll poke around the bintray plugin to see if anything sticks out.

**Comment by bmuschko** [comment]
@cdancy I think they do that to avoid having to store Maven credentials in any form. Would be great if you could have a look. Thanks!

**Comment by jordanjennings** [comment]
@bmuschko No issue with getting it from JCenter. I was just pointing out that it's not in maven as @cdancy stated. I think it has caused some confusion because the versions in the gradle plugins repo, maven, and jcenter aren't in sync.

**Comment by cdancy** [comment]
@bmuschko so you can [sync to maven centra](https://github.com/bintray/gradle-bintray-plugin#maven-central-sync)l with the below snippet. It would mean we would have to set the relevant properties on our Travis job if you're up for it.
```
            //Optional configuration for Maven Central sync of the version
            mavenCentralSync {
                sync = true //[Default: true] Determines whether to sync the version to Maven Central.
                user = 'userToken' //OSS user token: mandatory
                password = 'paasword' //OSS user password: mandatory
                close = '1' //Optional property. By default the staging repository is closed and artifacts are released to Maven Central. You can optionally turn this behaviour off (by puting 0 as value) and release the version manually.
            } 
```

**Comment by bmuschko** [comment]
@cdancy Sounds good to me. I will add the environment variables soon and will let you know afterward.

**Comment by bmuschko** [comment]
@cdancy Create the env. vars `MAVEN_CENTRAL_USER_TOKEN` and `MAVEN_CENTRAL_PASSWORD`. You can go ahead and make the code change.

**Comment by cdancy** [comment]
@bmuschko thanks and will do!
