### ISSUE TITLE
DockerJavaApplication plugin do not support multiple tags

### ISSUE THREAD

**Issue by evgeniy-maltsev** [bmuschko/gradle-docker-plugin#417]
Tag field in DockerBuildImage task is depricated. DockerJavaApplication do not use tags field. And so to workaround that, you need to reconfigure DockeBuildImage task created by DockerJavaApplication plugin. 
i.e write something like
```
"dockerBuildImage"(DockerBuildImage::class) {
        tag = null
        tags = setOf("$repoUrl/$repoArtifact:0.0.1", "$repoUrl/$repoArtifact:latest")
    }
```

**Comment by evgeniy-maltsev** [comment]
And you cannot push images for all the tags. you need to create your own task. and change default dockerPushImage.

```
    "dockerPushImageLatest"(DockerPushImage::class) {
        imageName = "$repoUrl/$repoArtifact:latest"
    }
    "dockerPushImage"(DockerPushImage::class) {
        setDependsOn(listOf("dockerPushImageLatest"))
        imageName = "$repoUrl/$repoArtifact:0.0.1"
    }
```

**Comment by cdancy** [comment]
@evgeniy-maltsev we still support it but logically we allow only one or the other. It's going to be removed soon anyway so better to use `tags`.
