### ISSUE TITLE
Creating a container is not offering options for linking container

### ISSUE THREAD

**Issue by MartinAhrer** [bmuschko/gradle-docker-plugin#42]
Are there any plans to include container linking along with container creation? The Java API seems to provide that capability: https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/model/HostConfig.java

**Comment by bmuschko** [comment]
Generally speaking, yes. Do you know with which version of Docker Java this was added? The plugin is still on version 0.10.5. I am waiting for 1.0.1 which is still not release. 1.0.0 had an issue.

Would you be interested in working on a pull request for this?

**Comment by MartinAhrer** [comment]
To me it looks like this feature is already in 0.10.5: https://github.com/docker-java/docker-java/blob/docker-java-0.10.5/src/main/java/com/github/dockerjava/api/model/HostConfig.java. HostConfig is encapsulating much of the more advanced settings.

Ok, yes I can try working on a pull request. It shouldn't be too hard to pass through a collection of links to the Java API.

**Comment by bmuschko** [comment]
As a side note: You'll need to create `HostConfig` via reflection. See [DockerThreadContextClassLoader.groovy](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/utils/DockerThreadContextClassLoader.groovy) for more info.

**Comment by MartinAhrer** [comment]
I'm already working on it and have already fleshed out the factory for the HostConfig, Links and Link types of the Docker Java API. However I seem to be running into a issue introduced with DockerThreadContextClassLoader. The [Links](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/model/Links.java) type unlike most other container types does not offer a constructor accepting a List but only a Link[]. 

```groovy
    def createLinks(List<Object> links) {
        def linkClass = loadClass('com.github.dockerjava.api.model.Link')
        def linksClass = loadClass('com.github.dockerjava.api.model.Links')
        def linksArray=Array.newInstance(linkClass, 0)
        Constructor constructor = linksClass.getConstructor(linksArray.class)
        constructor.newInstance((Object)links.toArray(linksArray))
    }
```
Doing the same with classes loaded with ```Class.fromString``` in some extra test project works fine. The easiest thing to do will be asking the Docker Java API maintainer to add the extra constructor to Links. But this will probably take much more time - so I would appreciate your input.

**Comment by bmuschko** [comment]
I asked for [something similar](https://github.com/docker-java/docker-java/issues/122) before. I'd say open an issue with them and see if they can incorporate it quickly. Optimally, you'd provide a pull request right away.

**Comment by MartinAhrer** [comment]
Ok, my change was accepted in docker-java through [issue 191](https://github.com/docker-java/docker-java/issues/191). Also, version [1.1.0](https://github.com/docker-java/docker-java/tree/docker-java-1.1.0) of docker java has been released ;)

**Comment by paclat** [comment]
It is great that you guys are on this as I was just needing it today.  Is there an ETA on when it will get merged and released?

**Comment by bmuschko** [comment]
@MartinAhrer I just released a new version of the plugin that uses the latest version of the Docker Java plugin.

**Comment by MartinAhrer** [comment]
Thanks for the update. I just double checked and I'm sorry that the docker-java guy did the [release](https://github.com/docker-java/docker-java/compare/docker-java-1.1.0...master) 30 minutes before he accepted the [pull request](https://github.com/docker-java/docker-java/pull/192) with the constructor addition. So I fear I have to wait for his next release.

**Comment by bmuschko** [comment]
@MartinAhrer Try to push the guy a little bit if you want this to become part of a Docker Java release. His release cycle is very infrequent (maybe once every 2 months).

**Comment by MartinAhrer** [comment]
A short update, docker-java 1.2 has been released on my request. So expect a pull request soon for container linking.

**Comment by bmuschko** [comment]
@MartinAhrer Cool. I'd actually prefer two different pull requests if possible. Easier to merge and verify.

**Comment by MartinAhrer** [comment]
I'm going to provide that with a separated pull-request anyway. My current implementation and integration tests already work. Just for the *Workflow* test I need the container name feature pull-request in master so I can rebase my container-linking branch and implement the *Workflow* test.
So I hope soon you can consider the container name pull request #44 to be ready for a merge.
