### ISSUE TITLE
Excluded Docker dependency makes dependencyReport fail

### ISSUE THREAD

**Issue by MrBuddyCasino** [bmuschko/gradle-docker-plugin#423]
We depend on Netty, and thus excluded the version pulled in by the plugin:

```
buildscript {
    repositories { jcenter() }
    dependencies {
        classpath('com.bmuschko:gradle-docker-plugin:3.0.12') {
            exclude module: 'io.netty'
        }
    }
}
```

This works for building, but the dependencyReport task fails with this message:

```
Execution failed for task ':dependencyReport'.
> Could not resolve all dependencies for configuration ':dockerJava'.
   > A conflict was found between the following modules:
      - io.netty:netty-codec:4.1.11.Final
      - io.netty:netty-codec:4.1.7.Final
```

I'm at a loss on how to resolve this.

**Comment by cdancy** [comment]
@MrBuddyCasino can you provide a reproducible project/snippet that we can look at? Most likely this is a gradle issue more than anything else.

**Comment by MrBuddyCasino** [comment]
@cdancy you're probably right in that its a generic Gradle issue. I "solved" it by explicitly overriding all the conflicting Netty modules in the dependencies section. If there is no way to isolate the different classpaths, then I guess thats the only solution. Thanks for the reply!
