### ISSUE TITLE
Cannot set container's ipaddress (ipv4) 

### ISSUE THREAD

**Issue by ekoon** [bmuschko/gradle-docker-plugin#424]
DockerCreateContainer should have an option to set ipv4.
See --ip from https://docs.docker.com/engine/reference/commandline/create/#usage

**Comment by cdancy** [comment]
@ekoon we build on top of `docker-java` so if they don't have support for it neither can we. Have you checked their source to see if they support it? If so would you be willing to send in a PR for this functionality?

**Comment by ekoon** [comment]
Can you link me to the docker-java project.

I am not sure if this is the project, but I see here (
https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java)
there is a get IPv4 option.



On Tue, Jul 25, 2017 at 9:35 AM, Christopher Dancy <notifications@github.com

**Comment by cdancy** [comment]
That's the one ;)

**Comment by ekoon** [comment]
So I see a CreateContainerCmd withIpv4Address(String ipv4Address);

**Comment by cdancy** [comment]
It's that method we would need to add support for in our `DockerCreateContainer` task.

**Comment by cdancy** [comment]
@ekoon were you planning on submitting a PR for this or should we close the issue?

**Comment by ekoon** [comment]
PR  #449

**Comment by orzeh** [comment]
@ekoon LGTM :+1: however would you mind to add similar support for IPv6?

**Comment by bmuschko** [comment]
@orzeh @cdancy Can we close this issue? The IPv4 has been merged and it doesn't look like @ekoon is going to follow up. We should either add the IPv6 option ourselves or close this issue.

**Comment by cdancy** [comment]
@bmuschko closing for now. Folks can feel free to re-open if they want to further discuss things.
