### ISSUE TITLE
Version 3.0.11 is not available via Gradle Plugins Portal

### ISSUE THREAD

**Issue by carstenlenz** [bmuschko/gradle-docker-plugin#425]
Hey.
The version `3.0.11` cannot be retrieved when using the Gradle plugin DSL but only by using a `buildscript` section. The last version working is `3.0.8`. Can you push it also to the plugin portal?

Thanks :)
Carsten

**Comment by cdancy** [comment]
@carstenlenz source from jcenter and you will be fine. This particular issue should be resolved with the next release.
