### ISSUE TITLE
DockerCreateNetwork fails with I/O exception

### ISSUE THREAD

**Issue by maksi** [bmuschko/gradle-docker-plugin#427]
DockerCreateNetwork always fails with the message:

`[Task worker] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (com.fasterxml.jackson.core.JsonGenerationException) caught when processing request to {}->unix://localhost:80: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?)
`

Seems I came too early and functionality is not implemented/tested yet?

UPDATE
Actually it creates the network...
`docker network ls` shows that network is created. So the problem is that task fails after it.

**Comment by maksi** [comment]
Problem in my local configuration. Pls ignore.

**Comment by cdancy** [comment]
No worries ;)
