### ISSUE TITLE
How to add multiple tags to image  ?

### ISSUE THREAD

**Issue by manikantabandaru** [bmuschko/gradle-docker-plugin#428]
While pushing the docker image to repo i need push with multiple tags for same image ?
```
task pushDocker(type: DockerPushImage) {
    dependsOn buildDocker
    imageName = buildDocker.tag
    
}
```
How can i modify above code to add multiple tags ?

**Comment by cdancy** [comment]
@manikantabandaru you have to first add those tags to your built image THEN you push said image:

http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#tags
