### ISSUE TITLE
Can't Use Own Registry For Pull Requests

### ISSUE THREAD

**Issue by pjreid** [bmuschko/gradle-docker-plugin#430]
Even when I provide my own url in the registryCredentials closure when I make a DockerPullImage request,  the request is directed towards _https://registry-1.docker.io_  rather than my own registry.

**Comment by cdancy** [comment]
@pjreid can you provide a reproducible snippet? My hunch is that you're not building out the image correctly in the first place with a proper host in place.

**Comment by cdancy** [comment]
Closing issue. Feel free to re-open if necessary.
