### ISSUE TITLE
Add support for HEALTHCHECK when creating DockerFile

### ISSUE THREAD

**Issue by schaliasos** [bmuschko/gradle-docker-plugin#431]
It would be really helpful if you could add support for [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) instruction in [DockerFile](http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html) task.

**Comment by cdancy** [comment]
@schaliasos we have support for that through the generic instructions one can pass in. Have a look at this example to understand how you can apply this to your own code.

https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerfileFunctionalTest.groovy#L160

**Comment by schaliasos** [comment]
@cdancy I didn't notice the generic instruction. Thank you.
