### ISSUE TITLE
Unable to use DockerCreateNetwork task

### ISSUE THREAD

**Issue by edesdan** [bmuschko/gradle-docker-plugin#439]
Hi All, I need to use the DockerCreateNetwork gradle task to create my docker network but I'm not able to do that at the moment and I cannot figure out why it is not working. I'm attaching a screenshot, I should have followed all the steps to import the plugin dependences... Any help?

![screen shot 2017-08-14 at 17 49 42](https://user-images.githubusercontent.com/5745049/29282076-590700a8-8119-11e7-89ab-8120e3a983dd.png)

**Comment by cdancy** [comment]
Try with version `3.0.12`. It shouldn't matter but 3.0.11 was a "bad" release and actually the upcoming `3.1.0` should have all of these bugs ironed out.

**Comment by edesdan** [comment]
Hi @cdancy, I see. I tried 3.0.12, still the same. I guess I need to wait the 3.1.0. Do you know when will be out? Thanks!

**Comment by cdancy** [comment]
The version here shouldn't matter so long as you're on the latest. Do you have a reproducible snippet? I can use these tasks here easily enough and all works as expected.

**Comment by edesdan** [comment]
Uhm, I have attached a simple test IntelliJ project. Can you check it and tell me if you found the cause of that? Thanks!

[test.zip](https://github.com/bmuschko/gradle-docker-plugin/files/1224560/test.zip)

**Comment by edesdan** [comment]
Hi, again. I think I found the cause. Basically the 'network' package is not packaged inside the jar (gradle-docker-plugin-3.0.12.jar) that gets downloaded from gradle, thats why I cannot access that class. You can check yourself by downloading the latest version on maven central: https://search.maven.org/remotecontent?filepath=com/bmuschko/gradle-docker-plugin/3.0.12/gradle-docker-plugin-3.0.12.jar

**Comment by cdancy** [comment]
@edesdan I can confirm this is indeed true. Package is also missing in jcenter as well. How this would have happened I have no idea. I can build locally fine and see the package is present here. I'll poke around and see if can make sense of this...

**Comment by edesdan** [comment]
@cdancy yes very strange. Just as hint maybe you can check any release tool/plugin you are using to deploy the jar to maven/ jcenter. 

Let me know I really need to use the docker network feature. Thanks for all your support! let me know if I can help. I'm also working on the PR to submit...

**Comment by cdancy** [comment]
> Let me know I really need to use the docker network feature

What do you mean?

**Comment by edesdan** [comment]
I mean I cannot use the DockerCreateNetwork() task and I need to do that.

**Comment by cdancy** [comment]
@edesdan gotcha. Ok ... just reached out to one open PR to see if the individual wants to clean things up for an immediate new release. I can get the `3.1.0` version out and any work you'd like to add on we can put into a `3.1.1` release. Point releases are no big deal around these parts and I can spin one up whenever.

**Comment by edesdan** [comment]
Ok so the 3.1.0 should then fix the issue? that would be good. I think this is a priority... Thanks!

**Comment by cdancy** [comment]
@edesdan can confirm `3.1.0` does have these tasks. Can't make sense of why it was not in the previous release but at least going forward I think we are good to go.

**Comment by edesdan** [comment]
@cdancy that's very nice, thanks! I will try that version then. I can see now the package is there.
