### ISSUE TITLE
Unable to pull / push to GCR

### ISSUE THREAD

**Issue by mmscibor** [bmuschko/gradle-docker-plugin#441]
Having some issues with the plugin when my base images and registry are on GCR. I am logged in as my self and have followed [these](https://cloud.google.com/container-registry/docs/advanced-authentication) instructions to enable communication with Google Cloud.

I am now able to run `docker pull` and `push`, but when I try to run the commands provided by the `gradle` plugin, I am getting permission errors.

**Comment by cdancy** [comment]
@mmscibor can you provide a snippet of how things worked for you when running from command line and then a gradle snippet of how you have things wired up?

**Comment by mmscibor** [comment]
```
ext.dockerImage = "gcr.io/insights/" + applicationName + ":" + version + "-" + "git rev-parse --short HEAD".execute().text.trim()
ext.dockerImageStateDir = "${projectDir}/build/docker"
ext.dockerImageStateFile = file("${dockerImageStateDir}/image-name")

docker {
  javaApplication {
    baseImage = "gcr.io/internal-base-images/trusty-java:0.26"
    maintainer = "mmscibor@gmail.com"
    tag = dockerImage
    port = 8080
  }
}

dockerBuildImage {
  // skip building if we've already built one (useful when dockerPushImage is executed separately)
  onlyIf { !dockerImageStateFile.exists() || dockerImageStateFile.text.trim() != dockerImage }
  doLast {
    file(dockerImageStateDir).mkdirs()
    dockerImageStateFile.createNewFile()
    dockerImageStateFile.write dockerImage
  }
}
```

**Comment by mmscibor** [comment]
Then, when running `gradle clean build`:

```
* What went wrong:
Execution failed for task ':dockerBuildImage'.
> Could not build image: repository gcr.io/internal-base-images/trusty-java not found: does not exist or no pull access
```

It definitely exists, so this is a permission issue. After following the instructions linked in the original question on Google docs, I am able to run `docker pull` and get this image just fine. Just not through gradle.

**Comment by cdancy** [comment]
@mmscibor are you setting the credentials anywhere or can is anonymous access allowed? I've never used GCR so forgive my ignorance here.

**Comment by mmscibor** [comment]
Ah, so perhaps the support is not yet here for that. GCR works using google cloud credentials, so I run something like `gcloud auth application-default login` which prompts me to login in on a browser using a Google account, then once that command has been run, I should be able to communicate with any of the google tools from my machine using my credentials. There are some alternative permission mechanisms where you can point to a credentials file for the lifetime of a single command. E.g. `gcloud auth activate-service-account --key-file=<FILE_PATH> <COMMAND>`

**Comment by mmscibor** [comment]
In both cases, however, gradle does not seem to recognize the gcloud permissions, I assume it's not running scripts but running on a JVM and therefore not picking them up?

**Comment by cdancy** [comment]
@mmscibor this plugin, and the library being used behind it `docker-java`, uses typical docker credentials.

https://github.com/bmuschko/gradle-docker-plugin#working-with-a-tls-enabled-docker-instance

**Comment by mmscibor** [comment]
Is there any support for pointing at a credentials file, similar to the `docker login` command documented here: https://cloud.google.com/container-registry/docs/advanced-authentication#using_a_json_key_file

**Comment by cdancy** [comment]
@mmscibor don't think so. I would open an ISSUE with `docker-java` to see what they have to say.

https://github.com/docker-java/docker-java/issues

**Comment by mmscibor** [comment]
Awesome, thanks for the help

**Comment by orzeh** [comment]
@mmscibor just use content (password) of this file:
````gradle
docker {
    registryCredentials {
        url = 'https://gcr.io'
        username = '_json_key'
        password = file('keyfile.json").text
    }
}
````

**Comment by mmscibor** [comment]
@orzeh that worked! Thank you

**Comment by cdancy** [comment]
@orzeh @mmscibor going to update our README.md with this snippet for future use-cases.
