### ISSUE TITLE
Evaluation of tags

### ISSUE THREAD

**Issue by atomfrede** [bmuschko/gradle-docker-plugin#444]
Following up the discussion in https://github.com/jhipster/generator-jhipster/pull/6271

Currently it is not possible to use e.g. `project.version` in case the version is declared after the docker build task:

```gradle
version = '0.0.1-SNAPSHOT' // This must be declared before the docker task
task buildDocker(type: DockerBuildImage, dependsOn: 'copyDockerFiles') {
    inputDir = project.file("${project.buildDir}/docker")
    tags = ["jhipster:${project.version}"]
}
version = '0.0.1-SNAPSHOT' // Defining the version here results in a tag like jhipster:undeclared
```

**Comment by cdancy** [comment]
@atomfrede while this has nothing to do with the plugin itself, and is more a gradle/groovy issue, you could probably get away with using the arrow operator to solve your problem:

```
task buildDocker(type: DockerBuildImage, dependsOn: 'copyDockerFiles') {
    inputDir = project.file("${project.buildDir}/docker")
    tags = ["jhipster:${->project.version}"]
}
version = '0.0.1-SNAPSHOT'
```

**Comment by atomfrede** [comment]
@cdancy Cool, didn't know that is possible, will try it, thx.

**Comment by gclayburg** [comment]
FYI - I ran into this same issue.   You can also fix it by building a String in groovy without using GString like this:

```
tags = ['jhipster:' + project.version]
```

I suspect that the plugin is expecting a String and not able to deal with a GString

**Comment by cdancy** [comment]
Less the plugin and more the docker-java library in use behind the scenes.

**Comment by cdancy** [comment]
Closing this issue as I feel it's more due to groovy "issues" than anything else.
