### ISSUE TITLE
MAINTAINER deprecated in Docker Engine v1.13.0

### ISSUE THREAD

**Issue by sdavids** [bmuschko/gradle-docker-plugin#445]
https://docs.docker.com/engine/deprecated/#maintainer-in-dockerfile

https://github.com/bmuschko/gradle-docker-plugin#user-content-extension-properties-1

"maintainer - Default value: Value of user.home system property"

Please provide a way not to set MAINTAINER or set an appropriate LABEL instead.

**Comment by cdancy** [comment]
@sdavids are you experiencing an issue or would just noting that this is deprecated?

**Comment by sdavids** [comment]
I would like to build a image w/o maintainer set.

**Comment by sugun999** [comment]
+

**Comment by cdancy** [comment]
PullRequests welcome if anyone wants to send something in!!!

@orzeh while folks use the `DockerJavaApplicationPlugin` I wonder if we should just remove it altogether and if devs really need it they can use an older version of the plugin. It's a pain in the butt to maintain especially when you can get better functionality through our OOTB tasks IMO.

**Comment by javajon** [comment]
Support for labels +1.

Consider adding a deprecation warning message at build time indicating support for Maintainer will be removed in an upcoming release. This gives community awareness and some time to adjust.
