### ISSUE TITLE
Use docker-java parse for binds

### ISSUE THREAD

**Issue by rwittrick** [bmuschko/gradle-docker-plugin#448]
In line with other methods using parse from docker-java, could the same be done for Bind, e.g in DockerThreadContextClassLoader createBind

```groovy
def createBind(String path, String volume) {
  Class bindClass = loadBindClass()
  Method bindParseMethod = bindClass.getMethod("parse", String.class)
  method.invoke(null, String.join(":", path, volume))
}
```

the tests in DockerThreadContextClassLoaderIntegrationTest look like there would be minimal changes, if any

An example of why this is useful:
`createBind('/proc','/hostfs/proc:ro')`
to bind host system drives as readonly.  The default access mode in docker-java is rw.

If that looks sensible, I'll submit a pull request

**Comment by orzeh** [comment]
@rwittrick any PR are welcome!
