### ISSUE TITLE
DockerBuildImage conflates location of Dockerfile with build context

### ISSUE THREAD

**Issue by llamahunter** [bmuschko/gradle-docker-plugin#45]
The root of the build context is the default location for the Dockerfile, but sometimes the Dockerfile is elsewhere, and not even called 'Dockerfile'.  Currently, the plugin has only one attribute 'inputDir' to specify the location of the build context.  There is no way to pass the specific path to the Dockerfile (i.e. what you would pass using the '-f' or '--file' option if running from the command line).

This is particularly important if you are programmatically building up the Dockerfile, and thus want to put it in the 'build' directory, but have a lot of non built, checked in artifacts that you want to copy into the image.  Thus, in these cases, the 'inputDir' would want to be '$projectDir', while the --file would want to be something like '$buildDir/docker/Dockerfile'

You could certainly copy all the checked in artifacts to '$buildDir/docker', but as they are checked in, they are likely read-only, and gradle does not do well in incremental builds when copying read-only files.  Better to leave them where they are (especially if they're large).

**Comment by bmuschko** [comment]
This is a relatively new Docker feature. I am not sure if [Docker Java](https://github.com/docker-java/docker-java) provides the functionality. Last time I checked it didn't. Would you mind checking whether the library provides the functionality with the latest version? If it doesn't, can you open an issue on their GitHub page?

**Comment by llamahunter** [comment]
It appears to have support using separate withDockerfile() and withBaseDirectory() methods.
https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/command/BuildImageCmdImpl.java
(wow... indentation is really a mess in that file.  people who use tabs in source code should be tarred and feathered)

**Comment by llamahunter** [comment]
So, I did manage to fix gradle-docker-plugin to allow the specification of a different dockerfile than one at the root of the build context, but it appears from reading the Go script for the docker cli that it *insists* that the dockerfile at least be somewhere within the build context (tho not necessarily at the top level or named 'Dockerfile').  https://github.com/docker/docker/blob/master/api/client/build.go#L147

So, gonna close this issue as I can't get what I *really* want, which is complete separation of the Dockerfile location from the build context, without changes to docker itself.
