### ISSUE TITLE
Add buildArgs with space delimiter?

### ISSUE THREAD

**Issue by gclayburg** [bmuschko/gradle-docker-plugin#451]
I am trying to build a docker image with a description like this:

```
task buildImage(type: DockerBuildImage, dependsOn: copyDockerResources){
    inputDir = project.file(dockerBuildDir)
    tags = [dockerimage+':' + version, dockerimage +':latest']
    buildArgs = ['VERSION':version,'DESCRIPTION':'just a sentence']
}
```

When I do a `docker inspect` I see the LABEL in the docker image looks like this:

```
            "Labels": {
...
                "org.label-schema.description": "just+a+sentence",
                "org.label-schema.version": "0.5.5"
            }
```

Where does the "+" come from?  I don't see this behavior when building the image from the command line like this:

```
docker build -t junk/memuser --build-arg DESCRIPTION="just some stuff" .
```

**Comment by orzeh** [comment]
@gclayburg It looks like there is something wrong with encoding of `buildArgs`. Probably this issue is related to `docker-java`. We have to dig there to confirm.

**Comment by orzeh** [comment]
@gclayburg I can now confirm that this is a `docker-java` issue. I will try to fix it there.

**Comment by cdancy** [comment]
Closing ISSUE as this should be resolved with latest release. Feel free to re-open if necessary.

**Comment by gclayburg** [comment]
Ok thanks guys - I just tried to test with 3.2.0.   I don't see a difference.  I was using 3.1.0 before.  Do you think the issue is fixed, or do we need to wait for something in docker-java to be released?

**Comment by cdancy** [comment]
Closing issue once more. Feel free to re-open should this arise once more.
