### ISSUE TITLE
Example for setting ENV

### ISSUE THREAD

**Issue by sdavids** [bmuschko/gradle-docker-plugin#454]
Please add an additional example to [Additional instructions in Dockerfile](https://github.com/bmuschko/gradle-docker-plugin#additional-instructions-in-dockerfile) for setting an ENV variable:

```
dockerDistTar {
  environmentVariable('JAVA_OPTS', '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap')
}
```

**Comment by cdancy** [comment]
@sdavids care to send in a PR with this change?

**Comment by cdancy** [comment]
Added snippet. Closing ISSUE.
