### ISSUE TITLE
How to correctly chain tasks?

### ISSUE THREAD

**Issue by thokari** [bmuschko/gradle-docker-plugin#458]
I am confused about the properties of the tasks.
`BuildImage` takes only a `tag` parameter? What should its value be?
Should it be `<imageName>:<imageTag>` where `imageName` is the repository name on DockerHub and `imageTag` is the version of the project?

`PushImage` takes an `imageName` parameter and a `tag` parameter. What should their values be? Is the `tag` supposed to include the  `imageName` or not? Or vice versa?

How does the `PushImage` task know which image to push, and how can I make sure it pushes the correct one that I just built?

Examples how to create tasks for the most typical use cases would be very helpful!

**Comment by thokari** [comment]
This is how I am using it now:

```
def dockerImageName = 'myorg/myproject'

task buildImage(type: DockerBuildImage) {
    dependsOn createDockerfile, copyDist
    mustRunAfter test
    inputDir = createDockerfile.destFile.parentFile
    tag = "${dockerImageName}:${version}"

}

task pushImage(type: DockerPushImage) {
    dependsOn buildImage
    imageName = dockerImageName
    tag = version
    doFirst {
        println "Using docker credentials for '${dockerRegistryUsername}'"
    }
}
```

Is this the correct way to handle the properties of the tasks?

**Comment by cdancy** [comment]
@thokari that all looks well enough. Here is a snippet of what I use here and works well enough:

```
task buildImage(type: com.bmuschko.gradle.docker.tasks.image.DockerBuildImage) {
    description 'Build docker image from local Dockerfile'
    noCache = true
    inputDir = projectDir
    tag = "${project.dockerHost}/${project.dockerRepo}:${project.dockerTag}"
}

task pushImage(type: com.bmuschko.gradle.docker.tasks.image.DockerPushImage, dependsOn: buildImage) {
    imageName = "${project.dockerHost}/${project.dockerRepo}"
    tag = "${project.dockerTag}"
}
```

**Comment by cdancy** [comment]
Closing issue. Feel free to re-open if need be.
