### ISSUE TITLE
Using an AWS ECR registry

### ISSUE THREAD

**Issue by jbisotti** [bmuschko/gradle-docker-plugin#464]
My company uses Amazon EC2 Container Registry (ECR) instead of Docker Hub or Artifactory. This requires either AWS' CLI or (REST) API be used to obtain a login token/password that's only good for 12 hours. I've currently cobbled something together but it's not very elegant.

The AWS CLI must be installed and available via the PATH. It requires a region, access key, & secret. There are a few different ways to provide these but I'm using environment variables). Executing the following AWS CLI command:
`aws ecr get-login --no-include-email`

... returns a Docker CLI login command, like this:
`docker login -u <AWS_USER> -p <TWELVE_HOUR_PWD> https://XXXXXX.dkr.ecr.us-east-1.amazonaws.com`

This must then be executed to log-in the Docker client.

In my Gradle build script, I've come up with this to retrieve (not execute) the Docker login command:
```
def getDockerLoginCommand = {
    def ecrStdOut = new ByteArrayOutputStream()
    exec {
        environment([
                AWS_DEFAULT_REGION: 'us-east-1',
                AWS_ACCESS_KEY_ID: '...',
                AWS_SECRET_ACCESS_KEY: '...'
        ])
        commandLine 'aws', 'ecr', 'get-login', '--no-include-email'
        standardOutput = ecrStdOut
    }
    final String dockerLoginCommand = ecrStdOut.toString()
    dockerLoginCommand
}
```

Then, I use it like this:
```
docker {
    def dockerLoginCommandArray = getDockerLoginCommand().split()
    def url = dockerLoginCommandArray[6]
    def u = dockerLoginCommandArray[3]
    def p = dockerLoginCommandArray[5]

    registryCredentials {
        url = url
        username = u
        password = p
    }
}
```

For others that might also be trying to use AWS ECR, I was wondering if it would be a good idea to get this added to the documentation or possibly even enhance the plugin to make working with AWS ECR more elegant. Thoughts?

**Comment by cdancy** [comment]
Interesting. Feel free to supply something to our wiki which I think is perfect for this type of example.

**Comment by nikolaidueck** [comment]
try this one: https://bitbucket.org/double16/gradle-aws-ecr-plugin
it works with bmuschko/gradle-docker-plugin

**Comment by cdancy** [comment]
Yeah he's a contributor here and builds on top of our plugin to create his.

**Comment by mkjois** [comment]
@jbisotti Does the linked plugin work nicely for you? Asking because I'm going to need to do this soon. If so, can you close the issue?

**Comment by cdancy** [comment]
I'm actually closing this now as it's less a question about the plugin but more how to wire things up to work with AWS so that one can further use this plugin.

As noted @double16 does provide a wrapper around this to make things easier if folks want to go that route.

**Comment by dalegaspi** [comment]
the `gradle-aws-ecr-plugin` did not work for me; always getting the auth error which leads me to believe that somehow the ECR login to get the token is not happening...the above script worked for me with a minor modification:

```groovy
exec {
  commandLine 'aws', 'ecr', 'get-login', '--no-include-email', '--region', 'us-east-1'
  standardOutput = ecrStdOut
}
```
