### ISSUE TITLE
Support COPY --from (multi-stage builds)

### ISSUE THREAD

**Issue by andybug** [bmuschko/gradle-docker-plugin#465]
As of gradle-docker-plugin 3.0.11, it does not appear to support the `COPY --from=` syntax. The `FROM as` works as expected. A simple example is below.

    task dockerAssemble(type: Dockerfile, dependsOn: dockerAssembleBuild) {
      description 'creates project Dockerfile'
      destFile = dockerBuildDir.resolve('Dockerfile').toFile()

      from "debian:latest as base_image"
      // do stuff
      from "alpine:latest"
      //copyFile "--from=base_image", "/etc/debian_version",  "/etc/debian_version"

This results in a Dockerfile that looks as expected:

    FROM debian:latest as base_image
    FROM alpine:latest

Uncommenting the copy line yields:

    > Could not find method copyFile() for arguments [--from=base_image, /etc/debian_version, /etc/debian_version] on task ':nifi:dockerAssemble' of type com.bmuschko.gradle.docker.tasks.image.Dockerfile.

There doesn't appear to by a `copyFile` method that supports the from field in [Dockerfile](http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html).

**Comment by andybug** [comment]
Note, I was able to get around this by using the generic `instruction`:

    instruction "COPY --from=base_image /etc/debian_version /etc/debian_version"

**Comment by orzeh** [comment]
@andybug this seems to be an easy fix would you like to submit PR?

**Comment by andybug** [comment]
I'll take a look at it this weekend

**Comment by cdancy** [comment]
Closing issue. Feel free to re-open should you care to send in a PR.
