### ISSUE TITLE
Please add support for squashing images

### ISSUE THREAD

**Issue by FWiesner** [bmuschko/gradle-docker-plugin#470]
as far as I can see `docker build --squash` is not yet supported by the plugin, but it would be great if it would

**Comment by cdancy** [comment]
@FWiesner we build on top of the `docker-java` library and I don't believe they have support for the `--squash` arg at this point unless I'm missing something. You can reach out and ask them to support it or submit a PR. We can certainly help move things along but like to empower the potential contributor to do so themselves if they are willing.

https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/command/BuildImageCmdImpl.java

**Comment by cdancy** [comment]
Closing issue. Feel free to re-open should you, or any developer, like to take on this work and send in a PR.

**Comment by pun-ky** [comment]
any changes here? just asking

**Comment by bmuschko** [comment]
@pun-ky Still doesn't look like Docker Java is supporting the flag: https://github.com/docker-java/docker-java/blob/master/docker-java-api/src/main/java/com/github/dockerjava/api/command/BuildImageCmd.java. You will have to raise an issue there.

**Comment by pun-ky** [comment]
ok thanks @bmuschko
