### ISSUE TITLE
Cannot change Dockerfile location

### ISSUE THREAD

**Issue by sergey-morenets** [bmuschko/gradle-docker-plugin#484]
Hi 

I tried to change location of Dockerfile in project. I assumed it is docker folder of project. I would like change it to the root folder of the project. However I got exception "Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Cannot locate specified Dockerfile: /D:/complete/Dockerfile"}"

My project folder is D:/complete.

My build.gradle:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:3.2.0'
    }
}

apply plugin: 'java'
apply plugin: 'com.bmuschko.docker-remote-api'

import com.bmuschko.gradle.docker.tasks.image.*

task buildImage(type: DockerBuildImage) {
    dockerFile = file('Dockerfile')
}

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8
```

Thanks.

**Comment by orzeh** [comment]
@sergey-morenets you must set `inputDir` property for `buildImage` task, because it is set to `project.file('docker')` by default. You don't have to set `dockerFile` property because it is `Dockerfile` by default.

Try this:
````gradle
task buildImage(type: DockerBuildImage) {
    File inputDir = project.file('.')
}
````

**Comment by cdancy** [comment]
By default (not sure I even agree with this) we will look under `<project-root>/docker/` for your `Dockerfile`. You can override the default directory using the [input dir](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy#L29) property. Try that out and let me know how it works for you.

**Comment by cdancy** [comment]
@orzeh ha! You beat me to the response ;)

**Comment by sergey-morenets** [comment]
Hi

Thank you for the responses. I tried to options:

```
task buildImage(type: DockerBuildImage) {
    File inputDir = project.file('.')
}
```
It didn't change anything. Plugin still looked at docker folder

and second option

```
task buildImage(type: DockerBuildImage) {
    inputDir = project.file('.')
}

```
In that case I got an exception:

Caused by: java.io.IOException: 
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2146)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1107)
        at com.github.dockerjava.core.util.CompressArchiveUtil.archiveTARFiles(CompressArchiveUtil.java:105)
        at com.github.dockerjava.core.dockerfile.Dockerfile$ScannedResult.buildDockerFolderTar(Dockerfile.java:134)
        ... 55 more
        Suppressed: java.io.IOException: This archives contains unclosed entries.
                at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:225)
                at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:241)

Please advise

**Comment by orzeh** [comment]
@sergey-morenets this is a known issue, see #432 

IMHO it is better to use dedicated folder as a docker build context.

The reason why this
````groovy
task buildImage(type: DockerBuildImage) {
    File inputDir = project.file('.')
}
````
didn't work is that you created variable `inputDir` instead of setting `buildImage` tasks property.

**Comment by cdancy** [comment]
Or ... through the use of a `copy` task just copy the file into the expected location and be done with it.

**Comment by cdancy** [comment]
Closing this issue as conversation has died down. Feel free to re-open if you'd like to talk about things further.

**Comment by Coobik** [comment]
still it's not clear how to use this plugin to build a docker image from the existing dockerfile

**Comment by orzeh** [comment]
@Coobik did you check [User Guide](https://bmuschko.github.io/gradle-docker-plugin/#usage) and `DockerBuildTask` [documentation](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html)? What exactly is unclear for you?
