### ISSUE TITLE
DockerCreateContainer portBindings not working for me

### ISSUE THREAD

**Issue by nwillc** [bmuschko/gradle-docker-plugin#486]
I'm trying to create a container. My image works when run manually with -p 8080:8080 to publish ports. However, using the portBindings = ['8080:8080'] in my DockerCreateContainer results in a container being created but w/o the ports published.  I'm running gradle 4.2.1, gradle-docker-plugin 3.2.0, Docker 17.05.0-ce-rc1, on OS X.

Any thoughts?

**Comment by cdancy** [comment]
@nwillc did you start the container or just create the container? Those are 2 different steps.

**Comment by nwillc** [comment]
Created it, and then started it. Both from gradle and cli.  When I created a container with the "docker run" cli, then "docker ps" showed ports, but with the one created in gradle no ports appeared.

**Comment by nwillc** [comment]
Additionally, docker inspect of the container, seems to show the same values when done through cli or gradle.

**Comment by nwillc** [comment]
Wait .... your create vs start got me thinking. So, if I both create and start from gradle, all is good.  It just was confusing to me that the bindings are placed in the create, but don't show up then in a docker ps, but if started (where they arn't defined) then they appear.  My bad.

**Comment by cdancy** [comment]
@nwillc no worries. Docker does all of this behind the scenes and we just provide the "low level" building blocks so to speak to allow the developer to chain the tasks together to re-create what docker does. In this case you need to first create the container and then start it using the relevant tasks.
