### ISSUE TITLE
Not reading .dockercfg

### ISSUE THREAD

**Issue by bradkwadsworth** [bmuschko/gradle-docker-plugin#487]
I'm using a Jenkinsfile with docker.withRegistry() to create a .dockercfg file on my Jenkins slave and it is not being read by the plugin. Getting ```Authentication is required``` error from Docker. If I run local Docker commands it works fine from the Jenkins slave

**Comment by orzeh** [comment]
@bradkwadsworth this plugin uses `docker-java` library to communicate with Docker daemon. This library will read `.dockercfg` file if you set `DOCKER_CONFIG` env variable (see [docs](https://github.com/docker-java/docker-java#configuration)). Please note that there may be some [issues](https://github.com/docker-java/docker-java/issues/316) with newer version of Docker.

You can also configure `gradle-docker-plugin` directly to pass credentials to private registries. For details see [Extension properties](https://github.com/bmuschko/gradle-docker-plugin#extension-properties) in README.

**Comment by orzeh** [comment]
@bradkwadsworth I'm closing this assuming your problem was fixed.
