### ISSUE TITLE
Asserting that Docker is available on the local machine

### ISSUE THREAD

**Issue by gabrielhuff** [bmuschko/gradle-docker-plugin#488]
Currently, if Docker is not setup in the local machine, the plugin tasks will fail as expected. However, they won't inform the user that Docker is not installed (or running) - instead, they will just forward any exception thrown by the Docker API.

Consider the following scenario:

- Two developers **A** and **B** are working on a project. The difference between both is that **A** has knowledge about Docker and the Gradle Docker plugin, while **B** has none.
- **A** includes the Gradle Docker plugin on the project and than sets up a `functionalTest` Gradle task that depends on some Docker related tasks provided by the plugin.
- Since the plugin requires Docker to be installed on the local machine, **A** updates the project documentation so that Docker is listed as prerequisite. Knowing that **B** is not familiar with Docker, **A** also adds some setup instructions.
- **B** becomes aware of the new `functionalTest` task. However, for some reason, he does not check the new documentation.
- **B** tries to run the `functionalTest` task. The task fails as expected. However, **B** has no idea why. The error message consists on an exception stack that has nothing to do with Docker not being installed.

I think it would be great to inform a user that Docker is not correctly setup on the local machine.

One could argue that the plugin should delegate this responsibility to the Docker API instead, like everything else. Personally, I agree with delegating most of the stuff to the Docker API directly, however, I see no harm in creating a simple error handling layer on top of it.

The first solution that comes to mind would be to make all tasks fail with a friendly message and some installation instructions if Docker is not available. However, this would be a relatively big change: all tasks and tests would have to adapt to this new logic.

A simpler alternative would be to create an assertion task, that succeeds if Docker is available or fails with a friendly message if not. This task could be used as a dependency by other Docker related tasks, such as:

```groovy
task assertAvailable(type: DockerAssertAvailable)

task buildImage(type: DockerBuildImage) {
  dependsOn assertAvailable
  ...
}
```

Running `buildImage` on a Docker-less machine would fail with a message like:

> Docker not available. Make sure that Docker is installed and running. You can find installation instructions here: https://docs.docker.com/engine/installation/

**Comment by cdancy** [comment]
@gabrielhuff hmmm ... I don't disagree, and your proposed solution seems sound enough, but how would we check whether docker is available or not? Maybe you're saying that this `DockerAssertAvailable` task would simply try to do something like a `docker get version` and if that fails to connect in any way then the aforementioned task would pop as well?

**Comment by gabrielhuff** [comment]
@cdancy I confess that I didn't stop to think about the implementation, only the interface.

The Docker engine works as a client-server application, where both communicate through the Engine API. The concept of 'Docker being unavailable' would be equivalent to 'the client failing to communicate with the server'. If the client has a way to ping the server, then it becomes able to verify if it's available or not: if the server reacts as expected to the ping, it's available; otherwise it isn't.

So all we need would be a way to ping the server. In our case, the Docker API would be the client and the target Docker daemon would be the server. I just took a quick look at the Docker API and I didn't find any sort of ping functionality - something like a `PingCmd` to be issued by a `DockerClient`.

However, even if there's no defined API to do it, I think that your suggestion would be a valid way to ping the server. If we fail to fetch the version from the daemon, it should be considered unavailable. So we could so something like:

```groovy
class DockerAssertAvailable extends AbstractDockerRemoteApiTask {
  @Override
  void runRemoteCommand(dockerClient) {
    logger.quiet "Checking Docker availability."
    try {
      dockerClient.versionCmd().exec()
    }
    catch (Exception e) {
      throw new GradleException("Docker not available...")
    }
}
```

**Comment by cdancy** [comment]
Just thinking out loud: the problem I could see us running into is where and when to do this check. Do we attach it to all tasks as a dependency thereby repeating this check potentially N number of times? If we don't do that, and say do this check as part of an "init" pass when applying the plugin, that only covers the case when the script first runs and docker potentially could have gone down sometime after that. Not exactly sure how best to approach this. 

We had a similar PR send to use a year or so back with a similar idea in that we would, as part of applying the plugin, do a "check version" and cache the version for later use (won't go into the details of that or why it was needed here) which would cover our use-case here but leaves things open for failing further downstream.

IDK. Can't think of a great solution off the top of my head but I'm open to suggestions ;)

**Comment by orzeh** [comment]
> Just thinking out loud: the problem I could see us running into is where and when to do this check. Do we attach it to all tasks as a dependency thereby repeating this check potentially N number of times? If we don't do that, and say do this check as part of an "init" pass when applying the plugin, that only covers the case when the script first runs and docker potentially could have gone down sometime after that. Not exactly sure how best to approach this.

I totally agree with the above. IMO there is no sense in adding `DockerAssertAvailable` task for several reasons:
* Docker daemon may become unavailable just after we asserted it is up and running
* users can do it themselves by existing means
* if we are unable to connect to the daemon, it's hard to say what exactly is wrong, so we won't be able to help novice users anyway
* nowadays everybody use Docker on local machine :rofl:

**Comment by gabrielhuff** [comment]
I see your point. Well, I guess we can close this for now and reopen whenever the Docker API allows us to react to communication errors on command executions.

**Comment by cdancy** [comment]
And should that happen I think the best place for said logic would in docker-java and they throwing an appropriate detailed exception noting what popped.
