### ISSUE TITLE
How to customise Dockerfile created by docker-java-application plugin

### ISSUE THREAD

**Issue by holgerstolzenberg** [bmuschko/gradle-docker-plugin#49]
I am creating a Docker image for a Spring Boot java application. I can control what base image to use, but I cannot apply additonal steps to the Dockerfile, like 'ADD'.

What I am trying to achieve is to add a self signed CA certificate to the `cacerts` keystore of the JDK installed on the final image.

Currently the only solution visible to me is to create a separate base image with the cert included and reference this one from my java application docker image.

It would be great to have some hook to do some additional things to the created `Dockerfile` before the image is build, for example something like this:

```groovy
docker {
  url = 'http://docker.repository.com'

  javaApplication {
    baseImage = 'hanswesterbeek/google-debian-oracle-jdk:8'
    maintainer = property 'maintainer'

    dockerfile {
      env ANY_VAR=xyz
    }
  }
}
```

or hook into the `Dockerfile` task somehow for not having to rewrite all the stuff the java application plugin does.

```groovy
docker {
  url = 'http://docker.repository.com'

  javaApplication {
    baseImage = 'hanswesterbeek/google-debian-oracle-jdk:8'
    maintainer = property 'maintainer'
  }

  dockerfileAdditions {
      env ANY_VAR=xyz
   }
}
```

**Comment by holgerstolzenberg** [comment]
Maybe there is already a possibility to do this but I do not see it so far.

**Comment by bmuschko** [comment]
The [integration tests](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/integTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginIntegrationTest.groovy#L60) shows an example for that. Also keep in mind that the task `dockerDistTar ` is of type `Dockerfile` so you can call all methods/properties it exposes. See the [Groovydocs](http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html) for more info.

**Comment by holgerstolzenberg** [comment]
Okay thanks for the clarification. I am fine with that.
