### ISSUE TITLE
In gradle 4.2, 4.3 onError is evaluated with null exception

### ISSUE THREAD

**Issue by DALDEI** [bmuschko/gradle-docker-plugin#490]
Using a reactive streams task like ListImages causes the onError method to be invoked with a null pointer.
This appears to be a gradle bug,  the task input properties are validated before execution which is evaluating the closure.  I dont know why onError is affected but not onNext, OnSuccess etc.
debug output surrounding an example with a stack dump injected in onError()

`
09:27:07.618 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :cds-data-hpe - Transitioning model element 'tasks.whyWontMatchIMageDoThis' to state Discovered.
09:27:07.618 [DEBUG] [org.gradle.caching.configuration.internal.DefaultBuildCacheConfiguration] Found class org.gradle.caching.local.internal.DirectoryBuildCacheServiceFactory registered for class org.gradle.caching.local.DirectoryBuildCache
09:27:07.618 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for resourceHashesCache, path /nexstra/cds/docker/.gradle/4.3/fileHashes/resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@7c3652cd
09:27:07.618 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for taskHistory, path /nexstra/cds/docker/.gradle/4.3/taskHistory/taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@8b8d79e
09:27:07.619 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Acquiring file lock for task history cache (/nexstra/cds/docker/.gradle/4.3/taskHistory)
09:27:07.619 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on task history cache (/nexstra/cds/docker/.gradle/4.3/taskHistory).
09:27:07.619 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on task history cache (/nexstra/cds/docker/.gradle/4.3/taskHistory).
09:27:07.619 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for outputFiles, path /nexstra/cds/docker/.gradle/buildOutputCleanup/outputFiles.bin, access org.gradle.cache.internal.DefaultCacheAccess@42a5fe10
09:27:07.619 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Acquiring file lock for Build Output Cleanup Cache (/nexstra/cds/docker/.gradle/buildOutputCleanup)
09:27:07.619 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on Build Output Cleanup Cache (/nexstra/cds/docker/.gradle/buildOutputCleanup).
09:27:07.619 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on Build Output Cleanup Cache (/nexstra/cds/docker/.gradle/buildOutputCleanup).
09:27:07.619 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Finalize build cache configuration' started
09:27:07.619 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Finalize build cache configuration'
09:27:07.619 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Finalize build cache configuration' completed
09:27:07.619 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Using 4 parallel executor threads
09:27:07.620 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': acquired lock on :
09:27:07.620 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.51 started (1 worker(s) in use).
09:27:07.620 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': acquired lock on root.1.51
09:27:07.620 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :cds-app:matchImage2 (Thread[Task worker for ':',5,main]) started.
09:27:07.620 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Task :cds-app:matchImage2' started
09:27:07.620 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :cds-app:matchImage2
09:27:07.620 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':cds-app:matchImage2'
09:27:07.620 [INFO] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':cds-app:matchImage2' into context took 0.0 secs.
09:27:07.620 [QUIET] [system.out] ON ERROR
09:27:07.621 [ERROR] [org.gradle.api.Task] Error in matchImage: null 
09:27:07.621 [ERROR] [system.err] java.lang.Exception: Stack trace
09:27:07.621 [ERROR] [system.err] 	at java.lang.Thread.dumpStack(Thread.java:1336)
09:27:07.621 [ERROR] [system.err] 	at java_lang_Thread$dumpStack$0.call(Unknown Source)
09:27:07.621 [ERROR] [system.err] 	at docker_core_4kj7id8fs1gjklccarworacyx$_run_closure19$_closure64.doCall(/nexstra/cds/gradle-common/docker-core.gradle:348)
09:27:07.621 [ERROR] [system.err] 	at docker_core_4kj7id8fs1gjklccarworacyx$_run_closure19$_closure64.doCall(/nexstra/cds/gradle-common/docker-core.gradle)
09:27:07.621 [ERROR] [system.err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:27:07.621 [ERROR] [system.err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:27:07.621 [ERROR] [system.err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:27:07.621 [ERROR] [system.err] 	at java.lang.reflect.Method.invoke(Method.java:498)
09:27:07.621 [ERROR] [system.err] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
09:27:07.621 [ERROR] [system.err] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
09:27:07.621 [ERROR] [system.err] 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
09:27:07.621 [ERROR] [system.err] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
09:27:07.621 [ERROR] [system.err] 	at groovy.lang.Closure.call(Closure.java:414)
09:27:07.621 [ERROR] [system.err] 	at groovy.lang.Closure.call(Closure.java:408)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.util.GUtil.uncheckedCall(GUtil.java:436)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.util.DeferredUtil.unpack(DeferredUtil.java:37)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo$3.validate(TaskPropertyInfo.java:105)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.TaskPropertyValue.validate(TaskPropertyValue.java:38)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.DefaultTaskInputPropertySpec.validate(DefaultTaskInputPropertySpec.java:53)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.DefaultTaskInputs.validate(DefaultTaskInputs.java:168)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
09:27:07.621 [ERROR] [system.err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:27:07.621 [ERROR] [system.err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:27:07.621 [ERROR] [system.err] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
09:27:07.621 [ERROR] [system.err] 	at java.lang.Thread.run(Thread.java:748)
09:27:07.621 [QUIET] [system.out] ON NEXT
09:27:07.622 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':cds-app:matchImage2' is up-to-date
09:27:07.622 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Up-to-date check for task ':cds-app:matchImage2' took 0.0 secs. It is not up-to-date because:
  Task has not declared any outputs.
09:27:07.622 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':cds-app:matchImage2'.
09:27:07.622 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Execute start for :cds-app:matchImage2' started
09:27:07.622 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :cds-app:dockerJava' started
09:27:07.622 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver] Resolving configuration ':cds-app:dockerJava'
09:27:07.622 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] Creating new in-memory cache for repo 'MavenLocal' [999d735982a5dae584847b8be0274aae].
09:27:07.622 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] Creating new in-memory cache for repo 'maven' [5f19dd04d69dc59dd9e7721d584ced20].
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] Creating new in-memory cache for repo 'ivy' [9f576ea2469a434e52b42f44a623ddf4].
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] Creating new in-memory cache for repo 'ivy2' [3d4de0324ff809c36acc04d03c04573d].
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] Reusing in-memory cache for repo 'BintrayJCenter' [24808588df9b7159a893e6b391f72fa1].
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder] Visiting configuration nexstra:cds-app:1.9.73(dockerJava).
09:27:07.623 [INFO] [org.gradle.composite.internal.CompositeBuildDependencySubstitutions] Found no composite build substitute for module 'com.github.docker-java:docker-java'.
09:27:07.623 [INFO] [org.gradle.composite.internal.CompositeBuildDependencySubstitutions] Found no composite build substitute for module 'org.slf4j:slf4j-simple'.
09:27:07.623 [INFO] [org.gradle.composite.internal.CompositeBuildDependencySubstitutions] Found no composite build substitute for module 'cglib:cglib'.
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/com/github/docker-java/docker-java/3.0.13/docker-java-3.0.13.pom
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/m2/com/github/docker-java/docker-java/3.0.13/docker-java-3.0.13.pom
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/ivy/com.github.docker-java/docker-java/3.0.13/ivy-3.0.13.xml
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/tmp/nexstra-repo/com.github.docker-java/docker-java/3.0.13/ivy-3.0.13.xml
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.pom
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/cglib/cglib/3.2.0/cglib-3.2.0.pom
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/m2/cglib/cglib/3.2.0/cglib-3.2.0.pom
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/ivy/cglib/cglib/3.2.0/ivy-3.2.0.xml
09:27:07.623 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/tmp/nexstra-repo/cglib/cglib/3.2.0/ivy-3.2.0.xml
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for com.github.docker-java:docker-java:3.0.13 using repositories [MavenLocal, maven, ivy, ivy2, BintrayJCenter]
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/com/github/docker-java/docker-java/3.0.13/docker-java-3.0.13.pom
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/com/github/docker-java/docker-java/3.0.13/docker-java-3.0.13.jar
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'com.github.docker-java:docker-java:3.0.13' in repository 'MavenLocal'.
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/m2/com/github/docker-java/docker-java/3.0.13/docker-java-3.0.13.pom
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/m2/com/github/docker-java/docker-java/3.0.13/docker-java-3.0.13.jar
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'com.github.docker-java:docker-java:3.0.13' in repository 'maven'.
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/ivy/com.github.docker-java/docker-java/3.0.13/ivy-3.0.13.xml
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/ivy/com.github.docker-java/docker-java/3.0.13/docker-java-3.0.13.jar
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'com.github.docker-java:docker-java:3.0.13' in repository 'ivy'.
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/tmp/nexstra-repo/com.github.docker-java/docker-java/3.0.13/ivy-3.0.13.xml
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/tmp/nexstra-repo/com.github.docker-java/docker-java/3.0.13/docker-java-3.0.13.jar
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'com.github.docker-java:docker-java:3.0.13' in repository 'ivy2'.
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'com.github.docker-java:docker-java:3.0.13' in 'BintrayJCenter'
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using com.github.docker-java:docker-java:3.0.13 from Maven repository 'BintrayJCenter'
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for org.slf4j:slf4j-simple:1.7.5 using repositories [MavenLocal, maven, ivy, ivy2, BintrayJCenter]
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.pom
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for org.slf4j:slf4j-parent:1.7.5 using repositories [MavenLocal, maven, ivy, ivy2, BintrayJCenter]
09:27:07.624 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom
09:27:07.625 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] Metadata file found for module 'org.slf4j:slf4j-parent:1.7.5' in repository 'MavenLocal'.
09:27:07.625 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using org.slf4j:slf4j-parent:1.7.5 from Maven repository 'MavenLocal'
09:27:07.625 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.jar
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] Metadata file found for module 'org.slf4j:slf4j-simple:1.7.5' in repository 'MavenLocal'.
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using org.slf4j:slf4j-simple:1.7.5 from Maven repository 'MavenLocal'
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for cglib:cglib:3.2.0 using repositories [MavenLocal, maven, ivy, ivy2, BintrayJCenter]
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/cglib/cglib/3.2.0/cglib-3.2.0.pom
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/space/dlee/maven/repo/cglib/cglib/3.2.0/cglib-3.2.0.jar
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'cglib:cglib:3.2.0' in repository 'MavenLocal'.
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/m2/cglib/cglib/3.2.0/cglib-3.2.0.pom
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/m2/cglib/cglib/3.2.0/cglib-3.2.0.jar
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'cglib:cglib:3.2.0' in repository 'maven'.
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/ivy/cglib/cglib/3.2.0/ivy-3.2.0.xml
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/repo/dev/ivy/cglib/cglib/3.2.0/cglib-3.2.0.jar
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'cglib:cglib:3.2.0' in repository 'ivy'.
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/tmp/nexstra-repo/cglib/cglib/3.2.0/ivy-3.2.0.xml
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/tmp/nexstra-repo/cglib/cglib/3.2.0/cglib-3.2.0.jar
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'cglib:cglib:3.2.0' in repository 'ivy2'.
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'cglib:cglib:3.2.0' in 'BintrayJCenter'
09:27:07.626 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using cglib:cglib:3.2.0 from Maven repository 'BintrayJCenter'
`

**Comment by DALDEI** [comment]
Correction, all the reactive methods are invoked once with a null argument.
I did not see it because the other methods implicitly used null-avoiding expressions

**Comment by cdancy** [comment]
@DALDEI is this with gradle 4.3?

**Comment by orzeh** [comment]
@DALDEI @cdancy I can reproduce it on Gradle 4.3 and 4.3.1. On 4.1 it works as expected. 

Since it is a Gradle issue I doubt we can find a generic workaround. Users just have to check for null in their closures.

**Comment by cdancy** [comment]
@orzeh yeah and same here. We had to upgrade an in-house plugin recently to account for this when we bumped to gradle 4.3. Not sure if this is a bug or not with gradle.

**Comment by cdancy** [comment]
@bmuschko if you get a chance do you know anything about this? I can't tell if this is a regression or a fix or a feature. Seems that closures being passed in (i.e. `onNext`) to a task are being executed once during the config phase, thus resulting in a null being passed like what we are seeing above, and then actually executed at runtime like one would expect. I can put together a reproducible snippet if the above is not clear enough.

**Comment by bmuschko** [comment]
@cdancy Try this out with Gradle 4.3.1: https://github.com/gradle/gradle/releases/tag/v4.3.1. We fixed an issue in the area of task input validation that might affect you here.

**Comment by cdancy** [comment]
@bmuschko just getting back around to this now. Please have a look at this [gist](https://gist.github.com/cdancy/436a4672d2c4e9bdd9d45c93234d6469) and let me know if you need anything more. The snippet is based on the use of this plugin and so docker is required to run it. Not sure if this is more due to the fact this plugin is doing something ... odd ... or this is an actual regression or something else. Let me know if you want me to open an actual ISSUE with gradle or not. Thanks AOT.

**Comment by cdancy** [comment]
@bmuschko bump ^^^

**Comment by bmuschko** [comment]
@cdancy In 4.3 there was some change that now evaluates all input properties during the configuration phase...in this case your Closures. [This plugin had the same issue.](https://github.com/ben-manes/gradle-versions-plugin/issues/185). You will have to change your plugin code to make it work. [This recommendation](https://github.com/ben-manes/gradle-versions-plugin/issues/185#issuecomment-337686708) will likely help.

**Comment by cdancy** [comment]
Thanks @bmuschko . I'll update the plugin accordingly to deal with this issue if only to save users the headache of reporting this over and over again.

For everyone else stumbling upon this thread: a hack/solution we came up with to get around this is to define your `on*` closures within a `doFirst` block. It's not great, and does require you to massage your code a bit, but will work until a new release is spun (which will be sooner rather than later).

**Comment by JLLeitschuh** [comment]
Is this fix in the current release? I don't see a PR or commit ID that closed this.

**Comment by cdancy** [comment]
@JLLeitschuh not sure of the commit/PR but latest release should have the fix. All @Input annotations have been removed from the necessary closures.

**Comment by Hubbitus** [comment]
What is correct way to fix NPE on:
```gradle
task removeEgaisappContainer(type: DockerRemoveContainer) {
    onlyIf { removeContainersOnExit && createEgaisappContainer.didWork }
    targetContainerId { createEgaisappContainer.containerName }
    removeVolumes true
    force true
    onError { exception ->
        if (!exception.message.contains('No such container')) // ignore exception if container does not exist otherwise throw it
            throw exception
    }
    doFirst{
        println "Delete created egaisapp container"
    }
}
```
Is it:
```gradle
        if (exception && !exception.message.contains('No such container'))
```
?
