### ISSUE TITLE
API For checking if Docker is available and running 

### ISSUE THREAD

**Issue by JLLeitschuh** [bmuschko/gradle-docker-plugin#491]
I have a project where some developers don't have docker installed/running. The project that sets up and tears down docker containers is only one small subproject. I'd like developers to be able to run the Gradle `check` task and have docker related logic get skipped if docker does not exist.

For example, I'd like to be able to do the following:
```kotlin
tasks.withType<Test> {
    onlyIf { com.bmuschko.gradle.docker.DockerStatus.isRunning() }
}
```

**Comment by cdancy** [comment]
@JLLeitschuh take a look at this recent discussion we had from another developer asking for something similar and why we ultimately turned the idea down:

https://github.com/bmuschko/gradle-docker-plugin/issues/488

**Comment by JLLeitschuh** [comment]
I don't really want an exception to get thrown though. I'd like to be able to disable test tasks if Docker isn't available. I can't catch an exception in the task failing.

**Comment by orzeh** [comment]
@JLLeitschuh Why not use just environment variable or project property?

````gradle
tasks.withType<Test> {
    onlyIf { !System.env.getProperty("SKIP_DOCKER") }
}
````

With this approach you won't accidentally skip your tests if docker is down, for example during CI build.

**Comment by JLLeitschuh** [comment]
Even with that, it would be nice to be able to do something like this:
```kotlin
if (!com.bmuschko.gradle.docker.DockerStatus.isRunning()) {
    logger.error("Docker isn't running, use the flag `SKIP_DOCKER` to disable docker tasks.")
}
```

**Comment by orzeh** [comment]
@JLLeitschuh @cdancy There is a [Ping endpoint](https://docs.docker.com/engine/api/v1.30/#operation/SystemPing) exposed by Docker. It is [supported]() in `docker-java` so we can add `DockerPingTask` and in `OnError` handler users will be able to do whatever they want.

Anyone interested in submitting PR?

**Comment by JLLeitschuh** [comment]
Does it need to be a task? Could it be an exposed API without being wrapped in a task? Maybe that's not a good idea.

**Comment by orzeh** [comment]
@JLLeitschuh This plugin provides set of tasks so IMO it must be a task.

You can always do `GET` to that endpoint by yourself and expose it as an API.

**Comment by cdancy** [comment]
I agree with @orzeh. And building on his example you could probably get away with doing something like (semi pseudo-code here and did not run):

```
task getVersion(type: DockerVersion) {
    onError {
        System.env.setProperty('SKIP_DOCKER', 'true')
    }
}

tasks.withType<Test> {
    dependsOn getVersion
    onlyIf { !System.env.getProperty('SKIP_DOCKER') }
}
```

**Comment by JLLeitschuh** [comment]
Wouldn't the `getVersion` task failing cause the rest of the build to fail??

**Comment by cdancy** [comment]
@JLLeitschuh not if you use the `onError` callback that I noted above. In this case you decide if it's worth truly failing or not.

**Comment by JLLeitschuh** [comment]
Oh, I suppose that would solve my problem.

**Comment by cdancy** [comment]
@JLLeitschuh give it a go and let us know how it works out.

**Comment by JLLeitschuh** [comment]
`onError` is of type `Closure` which means creating it is a PITA from kotlin. Working on a solution, will post when I have a solution.

**Comment by JLLeitschuh** [comment]
Related:
https://github.com/gradle/kotlin-dsl/issues/593

**Comment by JLLeitschuh** [comment]
Related: #494

**Comment by JLLeitschuh** [comment]
This is the code that I eventually came up with to solve this problem. Seems to work for me at the moment.
```kotlin
/**
 * Workaround for https://github.com/gradle/kotlin-dsl/issues/593
 */
class CustomKotlinClosure1<in T : Any?, V : Any>(
    val function: T.() -> V?,
    owner: Any? = null,
    thisObject: Any? = null) : groovy.lang.Closure<V?>(owner, thisObject) {

    @Suppress("unused") // to be called dynamically by Groovy
    fun doCall(it: T): V? = it.function()
}

val skipDockerPropertyName = "skipDocker"
val skipDocker = hasProperty(skipDockerPropertyName) && property(skipDockerPropertyName) != "false"

fun Task.skipIfSkipDockerSpecified() {
    onlyIf { !skipDocker }
}

val getDockerVersion = task<DockerVersion>("getDockerVersion") {
    onError = CustomKotlinClosure1<Exception?, Unit> ({
        if (this == null) {
            // TODO: Fix after this is resolved: https://github.com/bmuschko/gradle-docker-plugin/issues/490
            return@CustomKotlinClosure1 Unit
        }
        val message = "Docker is not installed or is not running."
        if (skipDocker) {
            logger.error(message + " Skipping Docker dependent tasks.")
        } else {
            throw GradleException("$message To skip Docker tasks run with -P$skipDockerPropertyName flag.")
        }
    })
}
```

In my first Docker task I do this:
```
val pullRabbitmqContainer = task<DockerPullImage>("pullRabbitmq") {
    tag = "latest"
    repository = "rabbitmq"
    dependsOn(getDockerVersion)
    skipIfRabbitmqRunning()
    skipIfSkipDockerSpecified()
}
```

**Comment by cdancy** [comment]
Closing as I believe we have a working solution here. Feel free to re-open if folks want to continue the conversation.
