### ISSUE TITLE
gradle-docker-plugin + Jenkins ?

### ISSUE THREAD

**Issue by edesdan** [bmuschko/gradle-docker-plugin#492]
Hi all,
I don't know if this is an out of topic question. At the moment I'm using this plugin to build images and run functional tests with docker containers in my project locally. I'd like to know how to configure/use Jenkins to run the docker tasks I have defined in the project. The goal I'm trying to achieve is to execute the FunctionalTest docker task during a CI build with Jenkins. Has anyone got an advice/guide on that? Thank you so much.

**Comment by cdancy** [comment]
@edesdan so we use cloudbees jenkins here for CI. There are a couple of ways you can go about this that I can think of off the top of my head:

1.) Mount the docker socket from the host instance into docker nodes and within your Jenkinsfile just run things as you normally would. The plugin will detect that `/var/run/docker.sock` is present and use that to communicate with the daemon.

2.) Pass along the environment variable `DOCKER_HOST=tcp://host-ip:port` and the plugin will detect if this is present and use whatever value you gave it to connect to the daemon.

Not sure if any of those is what you were looking for.

**Comment by edesdan** [comment]
Ok so I just need to make sure the docker deamon is installed on the machine where Jenkins is running and set the DOCKER_HOST variable. ok I'll try that, thanks for your suggestions!

**Comment by cdancy** [comment]
Closing. Feel free to re-open if you want to chat some more on this subject.
