### ISSUE TITLE
DockerCreateContainer Binds

### ISSUE THREAD

**Issue by a4chet** [bmuschko/gradle-docker-plugin#493]
Currently the DockerCreateContainer class uses a Map for storing binding points for the container. This prevents multiple host volume entries as keys in the map. 

For example I cannot mount a host "logs" directory more than once in the container as:

`volumes = [:]`
`volumes['C:/logs']='c:/consul/logs'`
`volumes['C:/logs']='c:/apache24/logs'`
`setBinds( volumes )`

**Comment by a4chet** [comment]
I apologize for the brevity of my post. I have provided a sample below.

I believe the root of the issue is using a `Map` for the binds as originates in `DockerCreateContainer`.

Ultimately the `DockerThreadContextClassLoader.groovy` parses the maps to an Array (line 331) using the ":" as a join on the key/value pair.

Docker does allow the host volume to be mounted into the docker container more than once. 

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies{
        classpath 'com.bmuschko:gradle-docker-plugin:3.1.0'
    }
}

apply plugin: 'com.bmuschko.docker-remote-api'
import com.bmuschko.gradle.docker.tasks.container.*

task createAContainer( type: DockerCreateContainer ){
    targetImageId {
        "microsoft/nanoserver"
    }

    containerName = "Test"
    Map<String,String> volumes = [:]
    volumes["c:/test/logs"] = "c:/logs"
    volumes["c:/test/logs"] = "c:/consul/logs"

    binds( volumes )
}
```

**Comment by cdancy** [comment]
Care to send in a PR for this work? Shouldn't be too bad to knock out just need to use a different data-structure than a map (whilst also being backwards compatible with maps).

**Comment by cdancy** [comment]
Closing as this has been open for quite sometime. Feel free to send in a PR in the future should you care to see this done.

**Comment by talberadt** [comment]
I just encountered this problem myself.
I am willing to create a PR for this, I would just like a direction on which different data-structure to go with?
Thanks.
