### ISSUE TITLE
DockerCreateContainer: Volume binds fails when we run with jdk7 

### ISSUE THREAD

**Issue by SandeepGolla** [bmuschko/gradle-docker-plugin#496]
code snippet to reproduce:

	 buildscript() {
		repositories {
			mavenLocal()
			mavenCentral()
		}
		dependencies {
			classpath (group: 'com.bmuschko', name: 'gradle-docker-plugin', version: '3.2.0')
		}
	}

	apply plugin: "com.bmuschko.docker-remote-api"

	task pullImage(type: com.bmuschko.gradle.docker.tasks.image.DockerPullImage) {
		repository = "ubuntu"
		tag = "latest"
	}

	task createContainer(type: com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer, 
		dependsOn: ['pullImage']) {
		targetImageId {
			project.tasks.getByName('pullImage').repository + ":" + project.tasks.getByName('pullImage').tag
		}
		def volumeMounts = [:]
		volumeMounts["/home"] = "/opt/"

		containerName = "test"
		privileged = true
		stdinOpen = true
		binds = volumeMounts
	}

 It is failing with below error :
   
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createContainer'.
> No signature of method: static java.lang.String.join() is applicable for argument types: (java.lang.String, java.lang.String, java.lang.String) values: [:, /home, /opt/]
  Possible solutions: wait(), trim(), find(), notify(), split(), toSet()

**Comment by cdancy** [comment]
I'm able to reproduce the issue and I would indeed say it's a bug. This is most likely and oversight on our end in allowing a java 8 function to slip through the cracks. I'll get this fixed and spin up a new version shortly. Thanks for reporting @SandeepGolla

**Comment by cdancy** [comment]
@SandeepGolla @petehayes version `3.2.1` has been released. Please upgrade and give things a go.

Also ... you can shorten up that logic above to something like this. Hopefully we're not being that verbose in our code in anywhere.... :)

```
task createContainer(type: com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer) {
    dependsOn pullImage
    targetImageId { pullImage.imageId }
    def volumeMounts = [:]
    volumeMounts["/home"] = "/opt/"

    containerName = "test"
    privileged = true
    stdinOpen = true
    binds = volumeMounts
}
```
