### ISSUE TITLE
Add chown flag to ADD and COPY commands

### ISSUE THREAD

**Issue by hermitmaster** [bmuschko/gradle-docker-plugin#497]
Add support for chown flag to comply with Docker API.
https://github.com/moby/moby/pull/34263

**Comment by cdancy** [comment]
@hermitmaster you can use the [generic instruction parameter](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L88) to add anything you want to a Dockerfile. Give that a go and let me know how it works out.

**Comment by hermitmaster** [comment]
@cdancy That's what I'm doing now and it works just fine, but it would be nice to see first-class support for it since it's part of the API.

**Comment by cdancy** [comment]
@hermitmaster yeah I can appreciate that but personally I go back and forth on designs like this. I personally favor flexibility over rigidness, at least in this context, but that may be more due to my expertise in this area and just wanting things to get out of me more than anything else. I'd entertain a PR for this if you're up for as it shouldn't be bad otherwise I'd just recommend to keep on doing what you're doing.

**Comment by cdancy** [comment]
@hermitmaster closing this as a solution already exists. If someone wants to send in a PR with this functionality I'd be more than happy to review it.

**Comment by ccadek** [comment]
> @hermitmaster you can use the [generic instruction parameter](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L88) to add anything you want to a Dockerfile. Give that a go and let me know how it works out.

The link to the page you mentioned here no longer exists. In the documentation I can unfortunately not find any mention of a generic instruction parameter. I am currently trying to implement COPY with chown and am a little bit stuck as I can not find a way to do this right now. 

I am using version 9.1.0

**Comment by bmuschko** [comment]
@ccadek The [README](https://github.com/bmuschko/gradle-docker-plugin/blob/master/README.adoc) file provides links to all documentation pages. Have a look at the [Javadoc of the Dockerfile class](https://bmuschko.github.io/gradle-docker-plugin/current/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html). It explains all available methods.
