### ISSUE TITLE
java.io.IOException: This archives contains unclosed entries.

### ISSUE THREAD

**Issue by rossh** [bmuschko/gradle-docker-plugin#5]
Hi guys, I'm getting the following when running 

`gradle clean --stacktrace buildExtractorImage`

`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildExtractorImage'.`
`Caused by: com.kpelykh.docker.client.DockerException: Error occurred while preparing Docker context folder.`
`Caused by: java.io.IOException: This archives contains unclosed entries.`

Any ideas?

**Comment by quorak** [comment]
I had the same error message.
deleting a file with umlaute and strange unicode encoding solved the problem for me
´rm /images/sofortu\314\210berweisung_icon.png´

**Comment by mosesonline** [comment]
when I execute gradle buildImage I get also the "This archives contains unclosed entries." in the stacktrace. It seems that it is an issue between creation of an Dockerfile and the image building.
I use Docker wit Docker Toolkit on windows.

Works:
docker {
    url = 'https://192.168.99.100:2376'
    certPath = new File(System.properties['user.home'], '.docker/machine/certs/')
}

task createDockerfile(type: Dockerfile) {
    destFile = project.file('Dockerfile')
    from 'mosesonline/gradle'
    addFile 'src', '/usr/src/workshopper/'
    addFile 'build.gradle', '/usr/src/workshopper/'
    addFile 'settings.gradle', '/usr/src/workshopper/'
    defaultCommand 'clean', 'build', 'bootRun'
    entryPoint 'gradle'
}

**task buildImage(type: DockerBuildImage) {
    inputDir = projectDir
    dockerFile = project.file('Dockerfile')
    tag = 'mosesonline/workshopper-gradle'
}**
Doesn't work:
...
**task buildImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    inputDir = projectDir
    dockerFile = createDockerfile.destFile
    tag = 'mosesonline/workshopper-gradle'
}**
