### ISSUE TITLE
multiple tags

### ISSUE THREAD

**Issue by nwillc** [bmuschko/gradle-docker-plugin#507]
Can I tag an image with both a version, and latest?  Docker supports this, but I can't see it here, it appears the "tag" is a single string.

**Comment by orzeh** [comment]
@nwillc please see our [wiki page](https://github.com/bmuschko/gradle-docker-plugin/wiki/examples) or/and [functional tests](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy#L56) for examples.

**Comment by SoltauFintel** [comment]
I would prefer a new tags property (type: Set<String>) for javaApplication. I think it's a common case to tag a version and also 'latest'.

**Comment by sdavids** [comment]
Maybe reopen? 

Or open a new issue explicitly for the javaApplication plugin supporting multiple tags?

**Comment by orzeh** [comment]
@sdavids we have already pending [PR](https://github.com/bmuschko/gradle-docker-plugin/pull/505), however it needs some work as you can see in the discussion. I hope I'll find some time to finish it.
