### ISSUE TITLE
Docker tasks do not work with Gradle releases higher than 4.3 + 

### ISSUE THREAD

**Issue by sshogunn** [bmuschko/gradle-docker-plugin#508]
Greetings,
I am using Gradle 4.3.1(I also checked it with Gradle 4.3 and 4.4.1). 

I added the plugin in my build.gradle file 
```
buildscript {
    ext {
        springBootVersion = '2.0.0.M7'
    }
    repositories {
        jcenter()
        mavenCentral()
        mavenLocal()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath('com.bmuschko:gradle-docker-plugin:3.2.1')
    }
}
...
apply plugin: 'com.bmuschko.docker-java-application'
...
docker {
    url = 'http://127.0.0.1:2375'
    javaApplication {
        baseImage = 'java:8'
        ports = [8083]
        tag = 'template'
    }
}
```

And when I run
`gradle clean dockerBuildImage` 

I see the following error(it is clear that it says that the task is not available):
```
What went wrong:
Task 'dockerBuildImage' not found in root project 'spring-boot-2-gradle-spock-liquibase-docker'.
```
May be I did something wrong, but it does not work with latest gradle releases. Could you help me to find a workaround?

**Comment by orzeh** [comment]
@sshogunn without reproducible snippet it would be hard to say what's wrong.

There are some existing issues related to SB like #467

**Comment by sshogunn** [comment]
I think that I have the same problem like in #467 we can link tickets and close this one
