### ISSUE TITLE
Update to dependency to ajoberstar/grgit

### ISSUE THREAD

**Issue by JamesXNelson** [bmuschko/gradle-docker-plugin#509]
Hi.

We use your plugin, and also use ajoberstar's git plugin, locked to the same version as you are using, to keep downloads smaller / faster.

The original gradle-git plugin is abandoned, and broken up into new projects (ajoberstar/grgit likely being the better one to use).

**Comment by cdancy** [comment]
It's on the local backlog to tackle. If folks want to send in a PR with this updated we'd be happy to review.

**Comment by cdancy** [comment]
This has been done in latest release.
