### ISSUE TITLE
The creatContainer command does not allow the user to explicitly set the name.

### ISSUE THREAD

**Issue by paclat** [bmuschko/gradle-docker-plugin#51]
The docker java api CreateContainerCmd has support for a "withName" that will let you explicitly set the name of the container.  It would be great if the api could support referring to containers by name as well as id.   Adding containerName as an attribute of the DockerCreateContainer would be a great start.

**Comment by bmuschko** [comment]
See pull request #44.

**Comment by bmuschko** [comment]
I am going to close this as a duplicate.
