### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by JamesXNelson** [bmuschko/gradle-docker-plugin#510]
DockerWaitHealthyContainer is not yet released, and I need it to remove flakiness when the docker container being tested is non-trivial.  While I _can_ build and deploy this to company repo, it would still make sense to do a release since the documentation contains references to a task definition that is not actually available yet.

**Comment by JamesXNelson** [comment]
Woops.  I should have checked w/ central first...

...it's surprisingly hard to grok current released version from source.  Might be nice to put it in README.

**Comment by cdancy** [comment]
We have a badge on the README already which points to the latest version. Was this not enough or maybe you missed it?

**Comment by JamesXNelson** [comment]
Aye. Heh, I did not see it there.  My bad!  Sorry for the issue spam...
