### ISSUE TITLE
SIGTERM not passed to java process

### ISSUE THREAD

**Issue by gadieichhorn** [bmuschko/gradle-docker-plugin#511]
Hi,

I am trying to stop my java app gracefully. any suggestions on how to stop main?

I think I should use the exc block but not sure how. an example will be great. 

```
docker {
    javaApplication {
        exec {
            defaultCommand ''
            entryPoint "/my-app/bin/my-app"
        }
   }
}
```

is this something I need to do in code?

Thanks
G.

**Comment by orzeh** [comment]
@gadieichhorn if your application is running in a container you can simply stop that container, which basically sends `SIGTERM` to the app (see Docker [documentation](https://docs.docker.com/engine/reference/commandline/stop/#extended-description) for details).
