### ISSUE TITLE
DockerJavaPlugin is throwing runtime error with DockerPullImage custom task

### ISSUE THREAD

**Issue by mursilsayed** [bmuschko/gradle-docker-plugin#512]
I am using docker-java plug-in for building docker image for my application. I then added a new task(pullImage) to pull a docker image from docker repository(using DockerPullImage as the parent task). Its throwing runtime error. 
> Cannot invoke method withClasspath() on null object

This 'pullImage' task works correctly if I apply Docker-remote-api plugin instead of Docker-Java-Plugin. I tried using both the plugin in separate script files and it also throws error. 

I can see in the documentation that docker-java plugin also applies docker-remote-api plugin. How can I use the docker-plugin along with the custom-docker tasks?

[code.zip](https://github.com/bmuschko/gradle-docker-plugin/files/1602034/code.zip)

**Comment by mursilsayed** [comment]
This only happens when I use a separate script for encapsulating the docker-related code. If I keep all the code in the build.gradle file, this is not a problem.

**Comment by orzeh** [comment]
@mursilsayed please check if [this](https://github.com/bmuschko/gradle-docker-plugin/issues/248#issuecomment-234098958) solves your problem.

**Comment by orzeh** [comment]
@mursilsayed closing for now. Hope you find the solution.
