### ISSUE TITLE
configuration for different evnvironaments

### ISSUE THREAD

**Issue by gadieichhorn** [bmuschko/gradle-docker-plugin#514]
Hi, This is a gradle/setup  question

I have 3 different env:
1. my local fedora linux
2. my 32 bit raspberry pi -> docker-machine rpi-32
3. my 64 bit raspberry pi ->  docker-machine rpi-64

** Note you have to build images for ARM on the hardware, linux docker doesn't have the simulator to build ARM.

How can I make one build to make 3 different images on 3 different docker-machines (remote-api) and local docker using 3 different base images?

like: 
* FROM arm32v6/openjdk:8-jre-alpine
* FROM arm64v8/openjdk:8-jre-alpine

I successfully built directly on the PI :
```
task raspberryPi(type: DockerBuildImage) {
    docker {
        url = dockerMachineUrl
        certPath = new File(System.properties['user.home'], dockerMachineName)
    }
}

```
but I want a more generic solution that can work on a multi project (many docker images) way.

Thanks.
G

**Comment by orzeh** [comment]
@gadieichhorn I understand your use case, however currently it's not possible to do it in one build. I would suggest run 3 build with different config (docker host, SSL certs, etc.) and build tasks (1 for each base image).

**Comment by gadieichhorn** [comment]
right, ok, thanks
