### ISSUE TITLE
Remove image to build another

### ISSUE THREAD

**Issue by lPegz** [bmuschko/gradle-docker-plugin#516]
Well, our project is using your plugin a lot, thanks for developing and maintaining it. 

We want to add a cleanUpImage before creating another DockerImage.

And after reading your documentation I am not sure in how to follow. 

The following code fails with this message: `Could not find method imageId() for arguments [build_4dilmyfm2kcv01qwberlb93rw$_run_closure5$_closure13@432b6426] on task ':cleanDockerImages' of type com.bmuschko.gradle.docker.tasks.image.DockerRemoveImage.`

```gradle
task cleanDockerImages(type: DockerRemoveImage, dependsOn: build) {
	imageId { "${imagePrefix}/${appName}" }
}
```

If I am mistaken, could you please add in the README.md an example of how this should be done?

Thanks a lot.

**Comment by orzeh** [comment]
@lPegz you should use `targetImageId` method:
````groovy
task cleanDockerImages(type: DockerRemoveImage, dependsOn: build) {
	targetImageId { "${imagePrefix}/${appName}" }
}
````

Please see our [functional tests](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerRemoveImageFunctionalTest.groovy#L25) for examples.

**Comment by lPegz** [comment]
just for clarification I could'nt using like this
`{ "${imagePrefix}/${jar.archiveName}" }`

I needed to do this
```gradle
task cleanDockerImages(type: DockerRemoveImage, dependsOn: build) {
	targetImageId { imagePrefix + "/" + appName }
	onError {
		System.out.println("No previous image to delete")
	}
}
```

Thanks anyway. it was pretty good.

**Comment by shilpashreevsk** [comment]
How do you remove the previous version of images of the one with <none>  after building a new version ?

**Comment by J00540873** [comment]
How do I incorporate your plugin?
