### ISSUE TITLE
'unauthorized: authentication required': dockerPushImage

### ISSUE THREAD

**Issue by bmenaman** [bmuschko/gradle-docker-plugin#519]
when using auth to a corporate remote repo.  I can execute docker login and push manually.  Perhaps the real problem here is that I have no way to troubleshoot this.  I had got to the point of checking out docker-java so I could rebuild it with custom logging, however I can't even build that because https://github.com/docker-java/docker-java/issues/962...

All suggestions welcome (not sure I should run wireshark in work btw)

**Comment by cdancy** [comment]
Can you provide a reproducible snippet? Does the same code work against other repos and only fails against this one?

**Comment by bmenaman** [comment]
hey sorry for the slow reply, it's all a bit of a locked down corporate environment.  I'd have to setup another docker registry somewhere internal to test.

The issue isn't so much that I want help connecting to the registry, it's that I don't have any way to get insight into what's happening.

Anyway my conf is something like:

docker {
  println("$docker_secret") //sanity check
  registryCredentials {
     url = 'https://corp.repo/v2/'
     username = 'none'
     password = '$docker_secret'
}

so that 
```
./gradlew dockerPushImage -Pdocker_secret=********
```
fails but

```
docker login -u none -p ******* corp.repo
docker push ...
```
works

**Comment by orzeh** [comment]
@bmenaman in your sampel config you used single quot for password property:
````password = '$docker_secret'````
Groovy won't replace `$docker_secret` value, I hope it's just a sample config :)

**Comment by bmenaman** [comment]
good spot but sadly no, copy-error

**Comment by orzeh** [comment]
@bmenaman ok. I think you can find some hints how to nail down the issue in [Gitlab help](https://gitlab.com/help/user/project/container_registry.md#advanced-troubleshooting).

**Comment by bmenaman** [comment]
oh that looks useful, thanks!

**Comment by cdancy** [comment]
Closing this issue. Feel free to re-open if you're still having an issue and would like to discuss.
