### ISSUE TITLE
Incorporate tagging docker images with git commit hash

### ISSUE THREAD

**Issue by brandshaide** [bmuschko/gradle-docker-plugin#521]
Hi and thanks for your awesome work! 

I'd be great if you could add a feature to `(type: com.bmuschko.gradle.docker.tasks.image.DockerBuildImage`
which makes it possible to add the current git commit hash to be used as tag for the docker image, e. g. 

```
inputDir = file("$buildDir/docker")
      tags = ["qc/${project.name}".toString(),
                 "qc/${project.name}".getAbbreviatedId().toString()]
```

Which makes basically this: 

```
git log -1 --format=%h
```

There's already a [plugin](https://github.com/ajoberstar/gradle-git), but I'd be awesome, if this could be incorporated into your plugin 🎆  and not to introduce yet another dependency ;-)

**Comment by orzeh** [comment]
@brandshaide adding git hash to the image tag is only one of possible _tagging_ strategy. I doubt we can support all of them. As you mentioned, it's possible to implement this by existing means. In the end there will be additional JARs on classpath, but let users decide if they want them.

@cdancy any thoughts on this?

**Comment by brandshaide** [comment]
@orzeh of course, you're right: after some research and discussions in my company we've decided to use the commit hash as tag as you can easily and  exactly pinpoint one commit to one image - rather than to have e.g. `dateTime` . 

Especially in terms of having images being build in a CI environment where you have multiple builds a day.

**Comment by orzeh** [comment]
@brandshaide OK, sounds reasonable. Personally, I prefer to tag images with project version and use [LABEL](https://docs.docker.com/engine/reference/builder/#label) to add such metadata. But that's just my opinion :) Anyway, we won't add any of these as a built-in feature.

**Comment by brandshaide** [comment]
@orzeh thanks for your feedback.
