### ISSUE TITLE
entryPoint should accept an array

### ISSUE THREAD

**Issue by antegulin** [bmuschko/gradle-docker-plugin#525]
Docker's `ENTRYPOINT` is an array of strings, it is expected that `entryPoint(java.lang.String)` also accepts an array instead of a string.

Because of this mismatch, passing an array to the `entryPoint` will wrap the array with additional double quotes forcing it to be a string.

**Gradle DockerFile configuration:**
`entryPoint('"java","argA=foo","app.war"')`
**Produces Dockerfile:** _(note the extra double quotes)_
`ENTRYPOINT [""java","argA=foo","app.war""]`

A simple, obvious hack to fix this issue is to omit the double quotes in `entryPoint` as following:
`entryPoint('java","argA=foo","app.war')`
Would produce a desired output:
`ENTRYPOINT ["java","argA=foo","app.war"]`

**Comment by orzeh** [comment]
@antegulin `entryPoint` accepts array of strings, see our [test](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/test/groovy/com/bmuschko/gradle/docker/tasks/image/DockerfileTest.groovy#L78) and [source](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L301).
