### ISSUE TITLE
DockerWaitHealthyContainer task should throw exception if unhealthy

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#526]
If the `unhealthy` status is received, there's no more point in waiting on the timeout. The task can throw an exception and exit right away. At the moment the task continues to check the status even if the `unhealthy` status was already received.

**Comment by bmuschko** [comment]
I guess receiving `unhealthy` could still be OK as we might receive `healthy` later?

**Comment by bmuschko** [comment]
Also wondering if the `timeout` is actually needed as you can set the parameter on the `HEALTHCHECK` instruction.

**Comment by gabrielhuff** [comment]
About the `unhealthy` state, as you mentioned on your second comment, the status can be `unhealthy` before becoming `healthy`. Also, it can become `unhealthy` after being `healthy`.

What the task is doing is basically blocking until the first `healthy` status.

About the `timeout`, I'm almost certain that the one from the `HEALTHCHECK` instruction is slightly different from the one defined on the task. The timeout from the task means 'how long the task should block before throwing an exception'. On the other hand, the one from `HEALTHCHECK` means 'how long each individual health check should take before falling back to unhealthy'.

Health checks are periodic checks made by Docker: they never stop, kinda like a heart rate monitor. They are not something used exclusively when starting a container.

You can find more on the [docs](https://docs.docker.com/engine/reference/builder/#healthcheck).

**Comment by bmuschko** [comment]
@gabrielhuff Thanks for the clarification. Closing the issue.
