### ISSUE TITLE
DockerCreateContainer Labels

### ISSUE THREAD

**Issue by blongstreth** [bmuschko/gradle-docker-plugin#527]
Would anyone have time to implement Labels to the DockerCreateContainer task please?  I believe the code would be almost identical to DockerBuildImage task.

**Comment by orzeh** [comment]
@blongstreth would it be possible for you to implement this?

**Comment by blongstreth** [comment]
Thank you very much for adding the feature!  Any ETA when it will be released?

**Comment by cdancy** [comment]
One more PR to review and merge and could probably do something tonight. Stay tuned...

**Comment by cdancy** [comment]
@blongstreth version `3.2.4` has been released.
