### ISSUE TITLE
Renaming Container / add DockerRenameContainer

### ISSUE THREAD

**Issue by brauchle** [bmuschko/gradle-docker-plugin#532]
Would be great to add the ability of renaming containers (would need it for a deployment process, otherwise I would have to remove the old container before I can create a new one with the same name)

The `docker-java` library seems to be able to do it.

Link to the api [https://docs.docker.com/engine/api/v1.35/#operation/ContainerRename](https://docs.docker.com/engine/api/v1.35/#operation/ContainerRename)

```
POST /containers/{id or name}/rename?name=new_name
Rename the container id to a new_name

**Comment by orzeh** [comment]
@brauchle would you like to send PR?

**Comment by cdancy** [comment]
@orzeh planned on doing a new release either today or tomorrow. If OP does,not chime in I can knock this out as you've done more than your share the past couple days ;)

**Comment by orzeh** [comment]
@cdancy sounds good 👍

**Comment by brauchle** [comment]
Unforunately i am not that deep into this project.
Would be great if one of you could do it 😃

**Comment by cdancy** [comment]
Task `DockerRenameContainer` has been added and version `3.2.4` has been released.

**Comment by brauchle** [comment]
Just tested it, works like a charm!
Thanks guys!
