### ISSUE TITLE
Q: Need help with building java-app and creating docker image

### ISSUE THREAD

**Issue by Docjones** [bmuschko/gradle-docker-plugin#535]
Hello,

using the following (simplified) build.gradle, i am able to build my java-springboot application, pack it into a docker image and store that image into our private repository (sonatype nexus) using the command `gradle dockerPushImage`.

```
buildscript {
	repositories {
 	    maven {
			url idsPublicURL
		}
	}
	dependencies {
		classpath("com.bmuschko:gradle-docker-plugin:3.0.7")
	}
}


apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'application'

apply plugin: 'com.bmuschko.docker-remote-api'
apply plugin: 'com.bmuschko.docker-java-application'

import com.bmuschko.gradle.docker.tasks.*
import com.bmuschko.gradle.docker.tasks.image.*
import com.bmuschko.gradle.docker.tasks.container.*

docker {
  url = "${idsDockerURL}" 
    
  registryCredentials {   
    url = "${idsDockerRepoURL}"
    username="****"
    password="***"
  }
}
    
  javaApplication {
    baseImage = 'openjdk:alpine'
    maintainer = '****'
    ports = [8080]
    tag = "${idsDockerRepoURL}/${project.name}:${project.version}"
  }
}

repositories {
  maven {
    url idsPublicURL
  }
}

dependencies {
....
}
```
Now i am trying to create a container from that pushed image on `$idsDockerUrl` but i am completely lost here. Executing a `gradle dockerCreateContainer` or something else (eg. dockerRunContainer,...) does not work, since those tasks are not defined. Do i need to create them manually? If so, how?

If i missed some documentation, i would be grateful if someone could put me on the right track.

thanks and best regards
/M

**Comment by cdancy** [comment]
We have specific tasks to do each of these things. They are all documented on this plugins README and within the source/tasks itself. Essentially you need to:
- DockerPullImage
- DockerCreateContainer
- DockerStartContainer
