### ISSUE TITLE
DockerSaveImage needs a file to exist instead of creating it

### ISSUE THREAD

**Issue by kalap92** [bmuschko/gradle-docker-plugin#539]
DockerSaveImage expects a file to exist. Proper behavior would be creating the file.

**Comment by cdancy** [comment]
@kalap92 this would be the proper way of going about doing things :) I know you have created a branch already so the next step would be to either view this projects main page which you should then be presented with a "create pull request" button somewhere near the top. If it's not there you can go [HERE](https://github.com/bmuschko/gradle-docker-plugin/compare) which will walk you through the process. I'll be in Cambridge tomorrow so I can walk you through things then if you want.

**Comment by kalap92** [comment]
Alright we can go through it tomorrow - thanks !

2018-02-19 16:20 GMT-05:00 Christopher Dancy <notifications@github.com>:
