### ISSUE TITLE
DockerStartContainer - no value for 'containerId'

### ISSUE THREAD

**Issue by djemerson01** [bmuschko/gradle-docker-plugin#541]
I'm trying to wrap your docker plugin to simplify a test scenario shared by a lot of users. I'm pulling an image and creating the container fine, but when I try to start the container, I get "No value has been specified for property 'containerId'". Another issue is that I'm writing the plugin in Java. It seems that the property that must be set on DockerStartContainer is targetContainerId, but it seems that it's not being called at the right time. I'd really appreciate any help you can give.

At the moment I've got the following:
```
startMockContainerTask.targetContainerId( StringToCallable(dockerCreateContainer));

    private Callable<String> StringToCallable(DockerCreateContainer dockerCreateContainer)
    {
        return new Callable<String>()
        {
            public String call()
            {
                return (dockerCreateContainer.getContainerId());
            }
        };
    }

```

**Comment by djemerson01** [comment]
I'm kicking off the task from the gradle runner and the start task depends on the create which depends on the pull. The create and pull work ok, but when I try to retrieve the containerId from the create task, it's not set. I'm trying to write a custom plugin in Java. I think the code above is the the important part of the code. I'm not sure it adds much, but here's the apply method:
`    public void apply(Project project)
    {
        project.getPluginManager().apply(S3MockPlugin.class);
        DockerRemoteApiPlugin dockerRemoteApiPlugin = project.getPlugins().apply(DockerRemoteApiPlugin.class);
        S3MockExtension s3MockExtension = project.getExtensions().create(S3MockExtension.NAME, S3MockExtension.class, project);

        DockerPullImage pullS3MockImage = createPullS3MockImageTask(project, s3MockExtension);
        DockerCreateContainer createMockContainer = createS3MockContainerTask(project, pullS3MockImage, s3MockExtension);
        DockerStartContainer dockerStartContainer = startS3MockContainerTask(project, createMockContainer, s3MockExtension);

        dockerStartContainer.dependsOn(createMockContainer);
        createMockContainer.dependsOn(pullS3MockImage);
    }
`

**Comment by cdancy** [comment]
Are you sure that the "create container" task has executed?

**Comment by djemerson01** [comment]
I've confirmed that the container exists and is functional using the docker command line. While it's possible that the execution phase isn't running for the start task, the other tasks are running and seem to be functioning Ok. I'm not sure when the failing task validation is run, is it at the beginning of the execution phase or the end of the configuration phase?

**Comment by djemerson01** [comment]
I was finally able to get this working with the following:

```
        startMockContainerTask.targetContainerId(
            new Callable<String>()
            {
                @Override
                public String call()
                {
                    return (dockerCreateContainer.getContainerId());
                }
            });

```
I'm still not clear on why the other attempt didn't work,, but I'll take the win

**Comment by cdancy** [comment]
Interesting. Glad you got things working.
