### ISSUE TITLE
almost no examples for the plugin

### ISSUE THREAD

**Issue by safronau** [bmuschko/gradle-docker-plugin#542]
i see only one example. it should be much more to show how to use existing tasks, how to use bindings, mounts, task parameters and so on.

**Comment by cdancy** [comment]
Have you looked at our plethora of functional tests which do just this? We link to them on the README as well. If however this is not enough feel free to send in a PR to update the docs or add to the wiki.

**Comment by safronau** [comment]
I've got about PR. I'll consider it.

it just was not an obvious way to find from readme a link like:  [functional tests directory](https://github.com/bmuschko/gradle-docker-plugin/tree/master/src/functTest/groovy/com/bmuschko/gradle/docker)
Anyway, for instance, I still have not found a complete example of DockerStartContainer (and others), there are examples like : 
```
            task startContainer(type: DockerStartContainer) {
                dependsOn createContainer
                targetContainerId { createContainer.getContainerId() }
            }
```
but there are much more task params than 2.

**Comment by cdancy** [comment]
@safronau that is true and you can use each as you need them. I'll grant you that we have loads of properties for the end-user to set, and not functional tests to cover every single use-case, but even attempting to do so, with all the possible combinations, would take all year to write and would be more confusing than naught to end-users.

**Comment by cdancy** [comment]
Closing this ISSUE. Feel free to send in a PR or to edit our wiki as this plugin is mainly driven by community contributions.
