### ISSUE TITLE
Does this plugin have a similar functionality to docker --net=host

### ISSUE THREAD

**Issue by nealarmstronglumira** [bmuschko/gradle-docker-plugin#546]
Hi, awesome work here. Can something like ... docker **--net=host** be done with this plugin?

**Comment by cdancy** [comment]
@nealarmstronglumira if you're just looking to use a different network you can use the `DockerCreateContainer` task specifying the `network=<some-value>` should do the trick.

https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy#L108

**Comment by nealarmstronglumira** [comment]
nice thanks!
