### ISSUE TITLE
gradle-docker-plugin doesn't use .dockerignore file like the native docker client

### ISSUE THREAD

**Issue by atanass** [bmuschko/gradle-docker-plugin#547]
Hi,
If I want to ignore everything but a single file in my project in order to minimize the build context sent to the daemon, I like to ignore everything in the .dockerignore and then negate the files I would like to not be ignored, example:
```
*
!build/libs/*[0-9].jar
```
This works when building the image with the native docker client but not with the gradle task from the plugin (type: DockerBuildImage).
The first issue is with Dockerfile not being sent to the daemon, which is somehow reasonable and can be easily worked around with:
```
*
!Dockerfile
!build/libs/*[0-9].jar
```
The second problem is that apparently the plugin does not read negation of subdirectories as I get the following log:
```
....
---> Using cache
---> 8e5ebb5a4fba
Step 3/4 : COPY build/libs/*[0-9].jar /

:buildDockerImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildDockerImage'.
> Could not build image: COPY failed: no source files were specified
```
Even if I replace !build/libs/*[0-9].jar with a specific filename there is no success.

Is there a plan to make the .dockerignore reading compatible with the docker client's format?

- Gradle task declaration:
```
    project.task('buildDockerImage', type: DockerBuildImage) {
      description = 'Builds a Docker image based on the Dockerfile instructions'
      group = dockerBuildGroup
      inputDir = project.rootDir
      imageId = "${project.name}"
      tag = dockerArtifactoryTag
    }
```
- gradle-docker-plugin version: 
```
com.bmuschko:gradle-docker-plugin:3.2.4
```

**Comment by orzeh** [comment]
@atanass we delegate `.dockerignore` handling to `docker-java`, please refer to thier [tests](https://github.com/docker-java/docker-java/blob/master/src/test/java/com/github/dockerjava/core/dockerfile/DockerfileAddMultipleFilesTest.java) and see if you correctly define pattern.

**Comment by kboom** [comment]
Posted a [bug](https://github.com/docker-java/docker-java/issues/999) on their side. There's clearly a bug.

**Comment by orzeh** [comment]
@kboom thanks for your feedback!

**Comment by hermitmaster** [comment]
Use a double asterisk on the first line, like below. Works fine for me.
```
#Ignore everything by default, we only want the Dockerfile and the `root` directory in the build context.
**
!Dockerfile
!root
```

**Comment by bmuschko** [comment]
Sounds like there's is a workaround with `**`. Any other issue will need to be addressed in Docker Java. Closing this issue for now.
