### ISSUE TITLE
Can not mount host volume into container

### ISSUE THREAD

**Issue by petehayes** [bmuschko/gradle-docker-plugin#55]
When creating a container using the DockerCreateContainer task, I need to mount a host directory as a volume in the container. 

I tried this syntax:

```
task createDatabaseContainer(type: DockerCreateContainer) {
	imageId = "postgres"
	volumes = [ "${projectDir}/src/main/docker:/docker-entrypoint-initdb.d", "/var/lib/postgresql/data" ]
}
```

This doesn't do the host mapping though and just creates a volume inside the container including the colon.  Am I missing something or is this not supported?

**Comment by bmuschko** [comment]
Did you check the [Groovydocs of the task](http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.html)? If the task doesn't allow for configuring it yet, it would need to be added. Would love to get a pull request for it.

**Comment by petehayes** [comment]
Yes, you can assign an array of volumes or a list of volumes from but it won't honor the host:container syntax used on the docker command line.

**Comment by bmuschko** [comment]
Is this potentially provided by pull request #54?

**Comment by petehayes** [comment]
Yes it does look that way. I'll close it and watch the pull request.

**Comment by bmuschko** [comment]
Cool, I am still waiting on some additional tests for the pull request. After that I going to merge and release.
