### ISSUE TITLE
How to pass additional groups to docker containers

### ISSUE THREAD

**Issue by mursilsayed** [bmuschko/gradle-docker-plugin#551]
You can use `--group-add` to pass additional groups while creating docker container. How can I achieve this functionality with the plugin?

https://docs.docker.com/engine/reference/commandline/create/#options

**Comment by orzeh** [comment]
@mursilsayed our plugin uses `docker-java` under the hood and in that library there is a [PR](https://github.com/docker-java/docker-java/pull/950) waiting. After it's released we can add this capability to `gradle-docker-plugin`.

**Comment by bmuschko** [comment]
@orzeh The Docker Java PR has been released with 3.1.0-rc-6. Are you planning to work on this?

**Comment by orzeh** [comment]
@bmuschko sure.

**Comment by orzeh** [comment]
@cdancy can you spin shaded version of docker-java 3.1.0-rc-6?

**Comment by cdancy** [comment]
@orzeh  and others sorry for the long wait: relevant PR has been merged to master and bumped docker-java to rc-7.

**Comment by orzeh** [comment]
@cdancy thanks! I'll prepare PR soon.

**Comment by bmuschko** [comment]
Thanks for your work, @cdancy!
