### ISSUE TITLE
Credentials changed?

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#553]
@bmuschko just tried to do a new release and it popped trying to push to Bintray with an authentication exception. Checkout this log:

https://api.travis-ci.org/v3/job/347970099/log.txt

**Comment by cdancy** [comment]
@orzeh anything stick out to you here?

**Comment by bmuschko** [comment]
I changed the credentials recently but made sure that they are available on Travis. I just reset the environment variables `BINTRAY_USER` and `BINTRAY_KEY`. Could you please again?

**Comment by orzeh** [comment]
@cdancy i don’t know what’s wrong. Let’s try if it works now.

**Comment by cdancy** [comment]
Giving things a go now...

**Comment by cdancy** [comment]
@bmuschko @orzeh so it _seems_ things are working now, and a new version released, and everything looks OK, gut gradle-grgit plugin is [throwing an exception at the last moment](https://api.travis-ci.org/v3/job/348321005/log.txt) though I can't figure out what it's actually affecting.

```
:generatePomFileForMavenJavaPublication
:publishMavenJavaPublicationToMavenLocal
:bintrayUpload
:gitPublishReset
:gitPublishCopy
:gitPublishCommit FAILED
:gitPublishClose

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gitPublishCommit'.
> Exception caught during execution of add command

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gitPublishCommit'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
```

**Comment by cdancy** [comment]
@bmuschko and thanks for jumping on things. Can you do the same for the `gradle-kubernetes-plugin` job? Can you also import the project into Bintray under your `gradle-plugins` repo when you get a chance? I know we talked previously about that potentially not needing to be the case but did so for another project and indeed things fail fast. Once we do an initial release, and having something like a 0.0.1 ready, you'll also have to go back into Bintray and ask them to make it available for public consumption.

**Comment by bmuschko** [comment]
@cdancy See https://bintray.com/bmuschko/gradle-plugins/gradle-kubernetes-plugin. Also reset the environment variables.

RE: GitHub - It's hard to say what went wrong. Do you have a stack trace?

**Comment by cdancy** [comment]
@bmuschko [here you go](https://api.travis-ci.org/v3/job/348321005/log.txt)

**Comment by bmuschko** [comment]
@cdancy Hhhhmm, no idea what's going on there. The error message doesn't really help. @orzeh might be able to comment on this.

**Comment by orzeh** [comment]
@cdancy @bmuschko I have no idea what went wrong. Hope it is a temporary issue.

**Comment by cdancy** [comment]
@orzeh fair enough ;) Again ... everything seems to have worked so I'm not really sure what actually failed. I guess we can call it a win :)

And @orzeh when are you going to jump in on the kubernetes work :) Planned on knocking out the general purpose "pod tasks" this weekend in hopes of doing an initial `0.0.1` release within the next couple of weeks.

**Comment by orzeh** [comment]
@cdancy Being quite busy at the moment, but I'll try to do my best to crack on.

**Comment by cdancy** [comment]
@orzeh hahaha I'm joking. Come and help out when you have time of course. No pressure or rush. If anything come critique it and point fingers and see if things make sense or say what can be done better.

**Comment by cdancy** [comment]
@bmuschko thanks for setting up the `gradle-kubernetes-bintray` project on Bintray. As I noted above: I'm going to knockout the handful of CRUD tasks surrounding "pods" over the next couple weeks and once done I'm going to attempt to kick the `0.0.1` release or maybe do a `0.9.0` release as this is a bit more work than a single digit patch version would imply. In either event I'll ping you again to share the project publicly on Bintray and then I should be off your back for a while ;)
