### ISSUE TITLE
How to specify build options when building the docker image

### ISSUE THREAD

**Issue by pgcortina** [bmuschko/gradle-docker-plugin#555]
We need to set the --network [options](https://docs.docker.com/engine/reference/commandline/build/#options) for some of our images. Is there any way we can set those when creating the image via DockerBuildImage task?
e.g something equivalent to
docker build -t test/image:latest --network=host --build-arg VERSION=A123 
Thanks!

**Comment by orzeh** [comment]
@pgcortina currently we don't have this option because `docker-java` which we use to make API calls to docker daemon doesn't have it either. Are you interested in sending PR to `docker-java`?
