### ISSUE TITLE
What version of dockerjava is used?

### ISSUE THREAD

**Issue by jimcarreer** [bmuschko/gradle-docker-plugin#559]
I don't see it anywhere in the dependencies path but obviously its used. I'm not familiar with the class loading method being used to build that libraries objects used by this plugin.  I ask because recently it was updated to support more filters:

https://github.com/docker-java/docker-java/commit/2582dce26e44fdecce0c1026b901966532fc72e0

which I would like to add some support for, In particular the name filter seems very useful.

**Comment by cdancy** [comment]
@jimcarreer the library is loaded [dynamically at runtime](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy#L53) and not part of the "traditional" dependency management. We're currently on the latest and greatest and can always bump to something newer should a newer version be released.

**Comment by jimcarreer** [comment]
Weird, I was getting some runtime errors trying to call withNameFilter on List Command in a new Docker Task I was trying to implement.  Anyway,  it turns out what I was trying to do was supported anyway, digging around in your test code made me realize I could use my container name to remove the container instead of the id docker randomly assigns, which was my ultimate goal.
