### ISSUE TITLE
Add support for DockerCPContainer to copy files out of a container

### ISSUE THREAD

**Issue by petehayes** [bmuschko/gradle-docker-plugin#56]
I have a need to copy files that are created within the container as part of a gradle build process.  Supporting the docker cp command would be useful via this API.

**Comment by bmuschko** [comment]
As long as Docker Java supports this functionality, we can add that.

**Comment by petehayes** [comment]
Looks like it does via [CopyFileFromContainerCmd] (https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/CopyFileFromContainerCmd.java)

**Comment by bmuschko** [comment]
Thanks. I won't be able to implement this anytime soon. If you want to have it asap, I'd welcome a pull request.
