### ISSUE TITLE
Use Provider API instead of convention mapping

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#561]
### Expected Behavior

The code uses the [`Provider` API](https://docs.gradle.org/current/userguide/lazy_configuration.html) instead of the internal API for convention mapping when configuring lazy-evaluated properties.

### Current Behavior

The current code uses convention mapping which will go away sooner or later. As a user, I don't want to use an internal API to configure lazy values (meaning I need to know how it works but it is undocumented).

**Example:**

```
task pushImage(type: DockerPushImage) {
    dependsOn buildImage
    conventionMapping.imageName = { buildImage.getTag() }
}

```

### Context

Avoid using an internal API. Usage of a public API.

**Comment by cdancy** [comment]
Yeah never liked this and I push back on developers when I see them use this vs other more intuitive and well defined ways of doing the same thing.

**Comment by bmuschko** [comment]
Assigned a major release to it as it will likely be a breaking change.
