### ISSUE TITLE
Docker images as inputs/outputs

### ISSUE THREAD

**Issue by rjbell4** [bmuschko/gradle-docker-plugin#569]
Apologies for basically asking a question as an issue, but I'm not aware of a better forum.

This is one of the leading plugins for Gradle regarding Docker.  Like most Docker-related Gradle plugins, it seems primarily concerned with constructing Docker images from Gradle.  Unfortunately, that's not really my use case.

In my use case, I'm using Gradle as the "glue" between some pre-existing repositories.  Those repositories have their own build scripts, and do not use Gradle.  However, some of them produce Docker images.  It is my desire to have Gradle's up-to-date checks and build cache working, but this is foiled with Docker images, as they don't produce distinct object on the filesystem.

I was wondering if this plugin did anything to make up-to-date checks work for Gradle tasks that use Docker images as inputs?  I didn't see anything, but I thought that if anyone already had a solution for this, @bmuschko probably would.

Thanks in advance for your response and any help you can provide.

**Comment by bmuschko** [comment]
> Apologies for basically asking a question as an issue, but I'm not aware of a better forum.

The best way for interactive communication is probably the [Gitter forum](https://gitter.im/gradle-docker-plugin/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) for this plugin.

> I was wondering if this plugin did anything to make up-to-date checks work for Gradle tasks that use Docker images as inputs? I didn't see anything, but I thought that if anyone already had a solution for this, @bmuschko probably would.

At the moment this plugin doesn't support this kind of functionality. I believe most of the task do not declare an output and therefore are not incremental or cacheable. You could probably achieve the behavior you want to writing a file with the image name or something similar (probably better would be a hash of some sort) to disk. With that you can declare it as output for the producing task and as input as a consuming task.

**Comment by rjbell4** [comment]
That's kind of what I was thinking.  I also need to store these images in Artifactory for later retrieval, so I was thinking of either:
1. Using `docker import` and `docker export`, and relying on the resulting tarballs (and storing/retrieving them as such, rather than as a Docker repository, _or_
2. Using a file, as you indicate, probably with the image ID in it.
I'm leaning towards the second option.

Thanks for confirmation.  I wish something was pre-existing, but it's at least good to know that I'm not inventing something unnecessarily.
