### ISSUE TITLE
PushImage task doesn't seem to really push 

### ISSUE THREAD

**Issue by lemm-leto** [bmuschko/gradle-docker-plugin#571]
I've private registry which is hidden behind nginx. I don't face any issues during building process from another machine. However it seems that image never really get tagged and pushed to registry.

Here is my config (credentials and urls changed):
```
docker {
    url = 'https://myurl:2375'
    apiVersion = 2

    registryCredentials {
        url = 'https://myurl/registry/'
        username = 'user'
        password = 'pass'
        email = 'email'
    }
}

import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.DockerTagImage
import com.bmuschko.gradle.docker.tasks.image.DockerPushImage
import com.bmuschko.gradle.docker.tasks.image.DockerPullImage

task dockerBuildImage(type: DockerBuildImage) {
    tag = 'xmetrics/grabbler-service:latest'
    registryCredentials = docker.registryCredentials
}

task dockerTagImage(type: DockerTagImage) {
    dependsOn 'dockerBuildImage'
    imageId = "xmetrics/grabbler-service"
    tag = "latest"
    force = true
    repository = "xmetrics/grabbler-service"
}

task pushImage(type: DockerPushImage) {
    dependsOn 'dockerTagImage'
    imageName = 'xmetrics/grabbler-service'
    tag = "latest"
    registryCredentials = docker.registryCredentials
}
```

### Expected Behavior
I'm going to see newly pushed repository and tags using v2 api, however I get just one image which was pushed manually by me:
![image](https://user-images.githubusercontent.com/6231493/38771463-71714892-402c-11e8-8f9f-2e7e94f63c17.png)

Trying to query by url https://myurl/registry/xmetrics/grabbler-service/tags/list also fails:
![image](https://user-images.githubusercontent.com/6231493/38771471-9001dad8-402c-11e8-82e4-f3de817e9392.png)

But I can see built image using docker images command:
![image](https://user-images.githubusercontent.com/6231493/38771481-a6e44f60-402c-11e8-861c-3180fc7f04e5.png)

Also, no erros during build:
```
:dockerBuildImage
Building image using context 'D:\Projects\microservices\grabbler-service\docker'.
Using tag 'xmetrics/grabbler-service:latest' for image.
Step 1/5 : FROM openjdk:8-jdk-alpine

---> 224765a6bdbe
Step 2/5 : VOLUME /tmp

---> Using cache
---> c21bf5ec0c9e
Step 3/5 : ARG JAR_FILE

---> Using cache
---> 1b2b1a644568
Step 4/5 : ADD ${JAR_FILE} grabbler-service.jar

---> Using cache
---> 38d7986ae6ab
Step 5/5 : ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/grabbler-service.jar"]

---> Using cache
---> 90b9b6729a55
Successfully built 90b9b6729a55
Successfully tagged xmetrics/grabbler-service:latest
Created image with ID '90b9b6729a55'.
:dockerTagImage
Tagging image with ID 'xmetrics/grabbler-service'.
:pushImage
Pushing image with name 'xmetrics/grabbler-service:latest'.

BUILD SUCCESSFUL in 6s
3 actionable tasks: 3 executed
```

Any advices? Maybe I'm doing smth wrong?

**Comment by cdancy** [comment]
Can you navigate to the registry to see where this image was pushed to? I would also try removing the `apiVersion` option as it's generally not needed and may lead to unexpected behavior.

**Comment by orzeh** [comment]
@lemm-leto I see you use context path `/registry` in your URLs. I suppose this is the source of problems.

**Comment by cdancy** [comment]
Closing this issue. Feel free to re-open if you'd like to further discuss things.
