### ISSUE TITLE
Cannot invoke method withContext() on null object

### ISSUE THREAD

**Issue by Geethree** [bmuschko/gradle-docker-plugin#575]
### Expected Behavior

For the docker image `hello-world` to be pulled

### Current Behavior

Throws error 
```
Cannot invoke method withContext() on null object
```
### Context

I am currently implementing a custom gradle plugin which will start various containers, which our tests will run again. I'm running into the issue below. Any thoughts?

#### buildSrc/build.gradle
```groovy
repositories {
    jcenter()
}

dependencies {
    compile 'com.bmuschko:gradle-docker-plugin:3.2.7'
}
```

#### buildSrc/src/main/groovy/foo.groovy
```groovy
package foo

import org.gradle.api.Plugin
import org.gradle.api.Project

import com.bmuschko.gradle.docker.tasks.image.*

class TestAgainstDocker implements Plugin<Project> {
    void apply(Project project) {
       project.task('pullImage', type: DockerPullImage) {
                repository = "hello-world"
        }
    }
}
```

**Comment by Geethree** [comment]
If I remove the `repository = "hello-world"` from the above `foo.groovy` I get:

```shell
* What went wrong:
A problem was found with the configuration of task ':pullImage'.
> No value has been specified for property 'repository'.
```

**Comment by Geethree** [comment]
It seems to me like `createDockerClientConfig` is returning null [here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy#L56)?

**Comment by cdancy** [comment]
Think you need to apply the plugin first as is documented [HERE](https://github.com/bmuschko/gradle-docker-plugin#remote-api-plugin). When writing a custom plugin (be it using buildSrc or some other means) you still need to apply the plugin in order to init things.

**Comment by Geethree** [comment]
Applying the plugin in `buildSrc/build.gradle` results in the same `withContex()` error

```groovy
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:3.2.7'
    }
}

apply plugin: 'com.bmuschko.docker-remote-api'

repositories {
    jcenter()
}

dependencies {
    compile 'com.bmuschko:gradle-docker-plugin:3.2.7'
}
```

**Comment by Geethree** [comment]
Applying the plugin in `buildSrc/src/main/groovy/foo.groovy` results in forcing me to change the Plugins name, and then results in the same `withContext` error.

**Comment by Geethree** [comment]
But if I add this to the main `build.gradle`:

```groovy
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:3.2.7'
    }
}
apply plugin: 'com.bmuschko.docker-remote-api'
apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin
```

It works.

How can I just add this to the buildSrc plugin?

**Comment by cdancy** [comment]
Nonono ... it needs to be applied INSIDE the plugin:
```
class TestAgainstDocker implements Plugin<Project> {
    void apply(Project project) {
       project.plugins.apply('com.bmuschko.docker-remote-api')
       project.task('pullImage', type: DockerPullImage) {
                repository = "hello-world"
        }
    }
}
```

**Comment by Geethree** [comment]
Yeah! I just made it that far. Now it is attempting to resolve the jar from maven. Any chance you know how to apply the jcenter repository to the plugin?

**Comment by Geethree** [comment]
Woo thanks
```groovy
class TestAgainstDocker implements Plugin<Project> {
    void apply(Project project) {
       project.repositories.jcenter()
       project.plugins.apply('com.bmuschko.docker-remote-api')
       project.task('pullImage', type: DockerPullImage) {
                repository = "hello-world"
        }
    }
}
```
