### ISSUE TITLE
Cache dependencies during Docker Build

### ISSUE THREAD

**Issue by johnrengelman** [bmuschko/gradle-docker-plugin#58]
Right now with the Application plugin, then entire project `installDir` is copied as a single `ADD` step to the Docker container. It would be much more efficient if the `${installDir}/lib` path (excluding the project jar) was copied in an `ADD` first, then the application jar (would also need to copy the `${installDir}/bin` directory). 

This would allow Docker to cache the layer of the dependencies between builds when dependencies aren't changing thus increasing the build speed and saving space on devices since the resulting layer that is changing would be smaller (only the size of the application jar).

**Comment by bmuschko** [comment]
Sounds like a great idea. Would you be interested in providing a pull request for this?

**Comment by cdancy** [comment]
@johnrengelman any interest in providing a PR?

**Comment by bmuschko** [comment]
@cdancy I believe that's PR #68.

**Comment by cdancy** [comment]
Closing on account of #68 being closed. Feel free to re-open if we think some value can be added.
