### ISSUE TITLE
buildImage task results in "the process cannot access the file because another process has locked a portion of the file"

### ISSUE THREAD

**Issue by mikesol314** [bmuschko/gradle-docker-plugin#582]
I recently began experimenting with Docker on Windows and found a simple Java project that utilized this plugin to check out. You can find said project here: https://github.com/gregwhitaker/ratpack-docker-example

When I checked that out, I attempted to run `./gradlew buildImage --stacktrace` which resulted in an error that I've pasted here: https://gist.github.com/mikesol314/2b8ae00414881238255aea0a1a16ec1d#file-buildimage-error-L86 (`the process cannot access the file because another process has locked a portion of the file`).

I _am_ able to get this project to build by running the command `docker build -f src/docker/Dockerfile .` and then doing a `docker run -p5050:5050 -d <image>` - which leads me to believe there must be something going on with this plugin (that or the `buildImage` task is configured incorrectly in which case my apologies). 

### Expected Behavior
I would expect that the `buildImage` task would build the Docker image and return no error.

### Current Behavior
Right now, I get the error that I posted above instead.

### Context
I can't run the command `./gradlew buildImage` to create my Docker image as I'd like to be able to do. 

### Steps to Reproduce (for bugs)
1. Checkout https://github.com/gregwhitaker/ratpack-docker-example
2. Run the command `./gradlew buildImage`
3. The error occurs

### Your Environment
I've found some other posts online that suggest that this type of thing tends to happen with badly configured anti-virus software. I've tried disabling mine altogether and restarting my computer and still saw this error (I'd expect that if it was an anti-virus thing that it would make a normal docker build not work either but I could definitely be misunderstanding something here).

- I'm currently running this on Windows 10 Pro Version 1709 with an OS Build of 16299.371. 
- My Docker version is 18.03.1-ce, build 9ee9f40
- My Java version is "10" 2018-03-20 with a Runtime Environment of 18.3 (build 10+46)
- I'm running these commands inside of a Git Bash shell (https://gitforwindows.org/) but I've also tried just the general command prompt in Windows and running the command `gradlew buildImage` instead.

Please let me know if I can provide any other information or run any other commands for you. Thanks so much for your time!

**Comment by orzeh** [comment]
@mikesol314 please take a look at #432.
