### ISSUE TITLE
DockerRemoveNetwork does not remove the network

### ISSUE THREAD

**Issue by dpancs** [bmuschko/gradle-docker-plugin#584]
```build.gradle
def networkName = "sample-network"

task createAppNetwork(type: DockerCreateNetwork) {
    dependsOn removeAppNetwork
    networkId = "${networkName}"
}

task removeAppNetwork(type: DockerRemoveNetwork) {
    targetNetworkId { networkName }
    onError { exception ->
        if (exception.message.contains('not found')) {
            println 'Docker Network not found.'
        }
    }
}
```
### Expected Behavior
On running `./gradlew removeAppNetwork`, I would expect the network to be removed.

### Current Behavior
After executing `./gradlew removeAppNetwork` if I run `docker network ls` I see that the network is still existing.

### Context
I have a build.gradle file where I am trying to programmatically bring up a database container and an application container.  The clean task needs to remove all things related to docker and there is a startDBContainer which will create a network and then connect database to that network along with the application container.  Everytime, when I restart my project build, I get an error as follows with the network count incrementing each time
```
* What went wrong:
Execution failed for task ':startDBContainer'.
> {"message":"network sample-network is ambiguous (3 matches found on name)"}
```

### Your Environment

I am using `Gradle v4.7.1` and `gradle-docker-plugin v3.7.2` on a macOS v10.13.4 with spring boot v1.5.12.RELEASE

**Comment by cdancy** [comment]
@dpancs when you call the task to remove the network does anything fail? It looks like from the snippet above you're not re-throwing the exception should one occur.

**Comment by dpancs** [comment]
Sorry... My mistake.  It does throw an error `{"message":"network sample-netowrk id bd2afea5edc919d6756ebd1cc25943bfc6591bec6a73fe227b1aad2612481514 has active endpoints"}`
