### ISSUE TITLE
Unable to configure which distribution to use to create docker image

### ISSUE THREAD

**Issue by ArtushGhandilyan** [bmuschko/gradle-docker-plugin#593]
### Current Behavior

Sync installTask = project.tasks.getByName(DistributionPlugin.TASK_INSTALL_NAME)
Jar jarTask = project.tasks.getByName(JavaPlugin.JAR_TASK_NAME)

**Comment by orzeh** [comment]
@ArtushGhandilyan can you provide some more detail? What is your use case?

**Comment by ArtushGhandilyan** [comment]
I have spring boot application and want to create docker image which run spring boot application through spring boot loader. In apply method of DockerJavaApplicationPlugin plugin docker file created based on installTask and jarTask

`Dockerfile createDockerfileTask = createDockerfileTask(project, installTask, jarTask, dockerJavaApplication)`

installTask is a default DistributionPlugin's task named installDist.
jarTask is a default JarPlugin's task named jar

`
Sync installTask = project.tasks.getByName(DistributionPlugin.TASK_INSTALL_NAME)
Jar jarTask = project.tasks.getByName(JavaPlugin.JAR_TASK_NAME)
`

But 'org.springframework.boot' plugin added another tasks such as

1. bootJar
2. bootDistZip
3. bootDistTar
4. installBootDist

and I want to use installBootDist task result instead of installDist. 

installDist create a executable file to run java through Main class
installBootDist create executable file to run spring boot loader


I think it can be done by adding some configuration property to specify installTask name.
`Sync installTask = dockerExtension.installTaskName ? dockerExtension.installTaskName : project.tasks.getByName(DistributionPlugin.TASK_INSTALL_NAME)`

And also want to say that jarTask can be optional in that case. Spring boot disable jar task.

**Comment by bmuschko** [comment]
The `DockerJavaApplicationPlugin` is not well suited for this use case. There will be a different plugin to support Spring Boot application. For more information, see https://github.com/bmuschko/gradle-docker-plugin/pull/619.
