### ISSUE TITLE
How push multiply images to registry?

### ISSUE THREAD

**Issue by Alykoff** [bmuschko/gradle-docker-plugin#598]
Could you add tags params to `DockerPushImage` for multiply pushing images to registery.

I want push multiply images to docker from one gradle task (like build image in `DockerBuildImage` with 'tags' params). But with `DockerPushImage` I could not use only one tasks, because `DockerPushImage` has only 'tag' param.

So I write this raw gradle script to resolve this problem:
```groovy
def imagePath = 'imageName'
def tagsList = ['imageName:dev', 'imageName:latest', 'imageName:0.1.0']
def pureTagsName = ['dev', 'latest', '0.1.0']
task buildDocker(type: DockerBuildImage) {
    // ...
    tags = tagsList
}

task pushDocker {
    def i = 0
    pureTagsName.each { t ->
        def newTaskName = "pushDocker-$i"
        task(newTaskName, type: DockerPushImage) {
            dependsOn 'buildDocker'
            dependsOn 'build'
            imageName = imagePath
            tag = t
        }
        pushDocker.dependsOn newTaskName
        i++
    }
}
```

**Comment by cdancy** [comment]
Did you want to send in a PR for this? I think it would be worthwhile to do such a thing. If not we can look to get something put together.

**Comment by Alykoff** [comment]
@cdancy 
ok
When I have a time I will make a PR.

**Comment by bmuschko** [comment]
You could just create multiple tasks with different names. That's probably the most straight forward solution.

```
['a', 'b', 'c'].each {
    task buildDocker${it.capitalize()}(type: DockerBuildImage) {
        ....
    }
}

task pushAll {
    dependsOn ['a', 'b', 'c'].collect { buildDocker${it.capitalize()} }
}
```

I don't think we'll want to overcomplicate the API we have in place right now.

**Comment by bmuschko** [comment]
I am going to close this issue for now. Please let me know if you are unsure about how to implement this in your own build.
