### ISSUE TITLE
pushing to quay.io fails when using docker 1.5+

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#61]
Seems that credentials get screwy somehow, or possibly docker changed how they are passed/formatted, when using docker version 1.5 or greater. We've also tested with all versions of gradle-docker-plugin from 2.1 onwards. Below is the debug output when attempting to push. We're using gradle 2.3 and running on RedHat7. Any ideas? Is this a known issue? 

`def quayCredentials = new DockerRegistryCredentials(url: quayHost, username: quay_username,
        password: quay_password, email: '')`

`task publishQuay(type: DockerPushImage) {
    dependsOn tagImageForQuay
    imageName "${quayHost}/${quayNamespace}/${dockerName}"
    tag "${dockerTag}"
    registryCredentials quayCredentials
}`

':publishQuay'
build	23-Apr-2015 11:17:36	14:17:36.271 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :publishQuay FAILED
build	23-Apr-2015 11:17:36	14:17:36.271 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :publishQuay (Thread[main,5,main]) completed. Took 1.044 secs.
build	23-Apr-2015 11:17:36	14:17:36.271 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 9 mins 12.899 secs, idle: 0.005 secs
error	23-Apr-2015 11:17:36	14:17:36.275 [ERROR] [org.gradle.BuildExceptionReporter] 
error	23-Apr-2015 11:17:36	14:17:36.276 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
error	23-Apr-2015 11:17:36	14:17:36.276 [ERROR] [org.gradle.BuildExceptionReporter] 
error	23-Apr-2015 11:17:36	14:17:36.276 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
error	23-Apr-2015 11:17:36	14:17:36.276 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':publishQuay'.
error	23-Apr-2015 11:17:36	14:17:36.276 [ERROR] [org.gradle.BuildExceptionReporter] > Error: Status 403 trying to push repository test/devops: {"info_url": "http://docs.quay.io/issues/no-repo-write-permission.html", "error": "You do not have permission to modify repository test/devops"}
error	23-Apr-2015 11:17:36	14:17:36.276 [ERROR] [org.gradle.BuildExceptionReporter] 
error	23-Apr-2015 11:17:36	14:17:36.276 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
error	23-Apr-2015 11:17:36	14:17:36.277 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':publishQuay'.
error	23-Apr-2015 11:17:36	14:17:36.277 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
error	23-Apr-2015 11:17:36	14:17:36.277 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
error	23-Apr-2015 11:17:36	14:17:36.277 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
error	23-Apr-2015 11:17:36	14:17:36.277 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
error	23-Apr-2015 11:17:36	14:17:36.277 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
error	23-Apr-2015 11:17:36	14:17:36.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
error	23-Apr-2015 11:17:36	14:17:36.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
error	23-Apr-2015 11:17:36	14:17:36.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
error	23-Apr-2015 11:17:36	14:17:36.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
error	23-Apr-2015 11:17:36	14:17:36.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:306)
error	23-Apr-2015 11:17:36	14:17:36.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
error	23-Apr-2015 11:17:36	14:17:36.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
error	23-Apr-2015 11:17:36	14:17:36.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
error	23-Apr-2015 11:17:36	14:17:36.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
error	23-Apr-2015 11:17:36	14:17:36.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
error	23-Apr-2015 11:17:36	14:17:36.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
error	23-Apr-2015 11:17:36	14:17:36.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
error	23-Apr-2015 11:17:36	14:17:36.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
error	23-Apr-2015 11:17:36	14:17:36.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
error	23-Apr-2015 11:17:36	14:17:36.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
error	23-Apr-2015 11:17:36	14:17:36.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
error	23-Apr-2015 11:17:36	14:17:36.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
error	23-Apr-2015 11:17:36	14:17:36.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
error	23-Apr-2015 11:17:36	14:17:36.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
error	23-Apr-2015 11:17:36	14:17:36.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
error	23-Apr-2015 11:17:36	14:17:36.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
error	23-Apr-2015 11:17:36	14:17:36.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
error	23-Apr-2015 11:17:36	14:17:36.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
error	23-Apr-2015 11:17:36	14:17:36.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
error	23-Apr-2015 11:17:36	14:17:36.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
error	23-Apr-2015 11:17:36	14:17:36.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
error	23-Apr-2015 11:17:36	14:17:36.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
error	23-Apr-2015 11:17:36	14:17:36.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
error	23-Apr-2015 11:17:36	14:17:36.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
error	23-Apr-2015 11:17:36	14:17:36.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
error	23-Apr-2015 11:17:36	14:17:36.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
error	23-Apr-2015 11:17:36	14:17:36.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
error	23-Apr-2015 11:17:36	14:17:36.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
error	23-Apr-2015 11:17:36	14:17:36.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
error	23-Apr-2015 11:17:36	14:17:36.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
error	23-Apr-2015 11:17:36	14:17:36.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:33)
error	23-Apr-2015 11:17:36	14:17:36.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
error	23-Apr-2015 11:17:36	14:17:36.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
error	23-Apr-2015 11:17:36	14:17:36.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
error	23-Apr-2015 11:17:36	14:17:36.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
error	23-Apr-2015 11:17:36	14:17:36.282 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.GradleException: Error: Status 403 trying to push repository test/devops: {"info_url": "http://docs.quay.io/issues/no-repo-write-permission.html", "error": "You do not have permission to modify repository test/devops"}
error	23-Apr-2015 11:17:36	14:17:36.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.response.PushImageResponseHandler$_handle_closure1.doCall(PushImageResponseHandler.groovy:45)
error	23-Apr-2015 11:17:36	14:17:36.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.response.PushImageResponseHandler.handle(PushImageResponseHandler.groovy:33)
error	23-Apr-2015 11:17:36	14:17:36.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.response.PushImageResponseHandler.handle(PushImageResponseHandler.groovy)
error	23-Apr-2015 11:17:36	14:17:36.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.response.ResponseHandler$handle.call(Unknown Source)
error	23-Apr-2015 11:17:36	14:17:36.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.response.ResponseHandler$handle.call(Unknown Source)
error	23-Apr-2015 11:17:36	14:17:36.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.tasks.image.DockerPushImage.runRemoteCommand(DockerPushImage.groovy:65)
error	23-Apr-2015 11:17:36	14:17:36.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_closure1.doCall(AbstractDockerRemoteApiTask.groovy:48)
error	23-Apr-2015 11:17:36	14:17:36.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:37)
error	23-Apr-2015 11:17:36	14:17:36.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
error	23-Apr-2015 11:17:36	14:17:36.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:47)
error	23-Apr-2015 11:17:36	14:17:36.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
error	23-Apr-2015 11:17:36	14:17:36.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
error	23-Apr-2015 11:17:36	14:17:36.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
error	23-Apr-2015 11:17:36	14:17:36.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
error	23-Apr-2015 11:17:36	14:17:36.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
error	23-Apr-2015 11:17:36	14:17:36.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
error	23-Apr-2015 11:17:36	14:17:36.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
error	23-Apr-2015 11:17:36	14:17:36.284 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
error	23-Apr-2015 11:17:36	14:17:36.284 [ERROR] [org.gradle.BuildExceptionReporter] 	... 44 more
error	23-Apr-2015 11:17:36	14:17:36.284 [ERROR] [org.gradle.BuildExceptionReporter] 
build	23-Apr-2015 11:17:36	14:17:36.284 [LIFECYCLE] [org.gradle.BuildResultLogger] 
build	23-Apr-2015 11:17:36	14:17:36.284 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
build	23-Apr-2015 11:17:36	14:17:36.284 [LIFECYCLE] [org.gradle.BuildResultLogger] 
build	23-Apr-2015 11:17:36	14:17:36.284 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 9 mins 18.573 secs

**Comment by bmuschko** [comment]
I'd think that the general mechanics for pushing an image to a private repository work (including authentication). The reason I am saying this is because I have a [test case](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/integTest/groovy/com/bmuschko/gradle/docker/DockerWorkflowIntegrationTest.groovy#L175) for pushing to DockerHub. The only difference I see is that you are not using the plugin extension. Would you mind trying the extension approach instead?

**Comment by cdancy** [comment]
Actually I think you can close this. It appears the latest docker build that is coming from RedHat is causing the issue as we can successfully do so with generic docker 1.5 builds.
