### ISSUE TITLE
Using the deprecated env property causes arguments to be lost

### ISSUE THREAD

**Issue by watzerm** [bmuschko/gradle-docker-plugin#612]
Hello,

since the commit https://github.com/bmuschko/gradle-docker-plugin/commit/efd328ad725000ce55ced09f97b4e58f61767475 I ended up losing arguments with the old env property, for example:

`env = ['JAVA_OPTS=-XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m']`

Now splitting the environment variable by `def keyValuePair = envVar.split('=')` and adding it to the new map using `envVars.put(keyValuePair.first(), keyValuePair.last())` causes all arguments that are placed before the last assignment to be lost.

### Expected Behavior
Using the env property with environments like `'JAVA_OPTS=-XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m'` without losing any argument

### Current Behavior
Environments like` 'JAVA_OPTS=-XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m'` are losing their arguments if the string contains an assignment

Is there a chance that this will be fixed in the future or is this never going to happen since the env property is deprecated by now?

**Comment by cdancy** [comment]
@watzerm Apologies for breaking things. I'll spin up a patch/bug release now.

**Comment by cdancy** [comment]
This PR was resolved via #614

**Comment by cdancy** [comment]
Bug fix release `3.4.1` has been released with this fix.
