### ISSUE TITLE
Howto build multiple docker images

### ISSUE THREAD

**Issue by rage-shadowman** [bmuschko/gradle-docker-plugin#615]
### Context
I'm trying to run integration tests using docker.

My ideal workflow is:
1. Create a "main" docker image (the main service being tested)
2. Create a "test" docker image (for running the integration tests)
3. Start up any "dependent" docker images (such as localstacks), waiting for them to finish loading (possibly running setup after they load)
4. Start up the "main" docker image to test against, waiting for a specific log entry to finish starting up
5. Start up the "test" docker image to run the tests
6. Verify the tests by copying the reports back to the local machine build directory
7. Shut everything down
8. Pushing the "main" docker image if all tests have passed

Is this something that can be done with this plugin? All of the examples I see are for creating a single main image, and then starting it up, then maybe run integration tests locally against it, then shutting it down. I've seen no examples of creating more than 1 image, or even of starting up any remote dependency images.

**Comment by cdancy** [comment]
@rage-shadowman so the idea of this plugin is to provide low-level building blocks in the form of tasks around all of the various docker API endpoints (e.g. create container, start container, inspect container, etc.). The scenario you're describing is what this plugin is mainly used for it just requires you to chain all the tasks together that you want.

However, you would not be the first to ask this question and/or become confused at how to use this plugin as it can admittedly be a bit daunting at first. With this in mind I created the [gradle-docker-applications-plugin](https://github.com/project-aries/gradle-docker-applications-plugin) which uses this plugin behind the scenes but makes it stupid-simple to stand up dockerized applications with an easy to use and follow DSL. I would highly recommend checking it out as I think it would fit your use-case perfectly.

**Comment by rage-shadowman** [comment]
@cdancy I think the main reason anything here is daunting is the lack of documentation and examples. Everything I'm seeing is all about creating a single docker image, starting it up, and running tests against it. I'll give your link a shot though. Thanks.

**Comment by cdancy** [comment]
To be fair the functional tests provide loads of examples on how to do any and everything this plugin provides. We could provide endless examples in the README but the problem becomes who best to serve and potentially at the risk of muddling up our initial insight into the plugin IMO.

**Comment by rage-shadowman** [comment]
I've looked at the src/funcTest directory in this project and picked one at random (since none of the names seemed to indicate a multi-container test) and it appeared to be dealing only with a single docker container. I then picked another at random, and another, and a few more, and they all appeared to deal only with a single container.

Perhaps I just don't know how to read them (I am fairly new to gradle -- most of my experience has been with maven -- so I can totally believe that what I think I'm seeing isn't what I'm actually seeing)? Can you point me to a specific multi-container test example?

**Comment by orzeh** [comment]
@rage-shadowman this plugin won't do everything for you. As mentioned above it gives you building blocks, but you have to put them together.

I agree you won't find here a complete example which covers your use case, but I hope existing functional tests can help you to create one. Probably it only requires some time to grasp how things work.

Below you can find a hint what tasks to use on each step of your use case:

>My ideal workflow is:
>    Create a "main" docker image (the main service being tested)
    
`DockerBuildImage`

> Create a "test" docker image (for running the integration tests)

`DockerBuildImage`

> Start up any "dependent" docker images (such as localstacks), waiting for them to finish loading (possibly running setup after they load)

`DockerCreateContainer`, `DockerStartContainer`, `DockerWaitHealthyContainer`, `DockerExecContainer`

> Start up the "main" docker image to test against, waiting for a specific log entry to finish starting up

`DockerCreateContainer`, `DockerStartContainer`, `DockerWaitHealthyContainer`, `DockerLogsContainer`

> Start up the "test" docker image to run the tests

`DockerCreateContainer`, `DockerStartContainer`

> Verify the tests by copying the reports back to the local machine build directory

`DockerCopyFileFromContainer`

> Shut everything down

`DockerStopContainer`, `DockerRemoveContainer`

> Pushing the "main" docker image if all tests have passed

`DockerPushImage`

Gluing this all together probably require some Gradle knowledge but you will find everything in the docs. Also feel free to ask further questions here.

**Comment by rage-shadowman** [comment]
Thanks @orzeh ! No need to clutter up your issue list with this. Closed.
