### ISSUE TITLE
Breaking Change in v3.2.0

### ISSUE THREAD

**Issue by mfulgo** [bmuschko/gradle-docker-plugin#618]
As of commit f42e16ab, files are now copied into an `app-lib` folder. Unfortunately, that seems to break some assumptions from dependent plugins such as nebula-docker. See [NebulaDockerPlugin.groovy#L78](https://github.com/nebula-plugins/nebula-docker-plugin/blob/v1.2.3/src/main/groovy/nebula/plugin/docker/NebulaDockerPlugin.groovy#L78)

I'm also open to this being a case of "they're using it wrong" and having this issue closed but documented.

### Expected Behavior
Version 3.x.x should copy files to `$build/docker/`.

### Current Behavior
Version 3.2.0+ copies files to `$build/docker/app-lib`

### Context
Incompatibilities between gradle plugins breaks builds and prevents updating to the latest versions of various plugins.

### Steps to Reproduce (for bugs)
(I can create something if necessary.)

### Your Environment
n/a

**Comment by bmuschko** [comment]
Optimally, the relevant task would expose a property that refers to the target directory. Any other code could then reference the property and always get the correct value independent of the underlying implementation.

This was a breaking change and we made a change to optimize image creation.

**Comment by bmuschko** [comment]
I am going to close this issue. My plan is to break up the layers even more (classes, resources, external libs). At that time we'll also expose methods that allows for retrieving the target directories though its somewhat of an internal implementation detail.
