### ISSUE TITLE
Request to read registry credentials from .dockercfg

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#62]
Is it possible to have the plugin read registry credentials from the .dockercfg file if it exists as part of the push? Maybe something like adding a 'file' property to DockerRegistryCredentials to load them from a given file at runtime. Or maybe simpler have a boolean that when flipped will attempt to check the users .dockercfg file for credentials if they exist?

Thoughts?

**Comment by bmuschko** [comment]
I believe Docker Java already [supports that functionality](https://github.com/docker-java/docker-java/pull/100). Generally, this logic should live in the library rather than in this plugin.

**Comment by cdancy** [comment]
That is true. Is there a way to support this from the plugin?

**Comment by bmuschko** [comment]
Looks like you just have to set the appropriate system property.

**Comment by cdancy** [comment]
@bmuschko from testing if I have a docker.io.properties located under "/home/user/" with the below it will work as expected:

'docker.io.enableLoggingFilter=true
docker.io.dockerCertPath=/home/user/.docker
docker.io.dockerCfgPath=/home/user/.dockercfg'

however what won't work is the following content:

'docker.io.enableLoggingFilter=true
docker.io.dockerCertPath=${user.home}/.docker
docker.io.dockerCfgPath=${user.home}/.dockercfg'

The ${user.home} is not getting set properly and I'm not sure if that's an issue with the plugin or docker-java itself?

**Comment by bmuschko** [comment]
The system properties are defined by the Docker Java library. So anything that breaks in that logic needs to be fixed there. Another alternative you have is to read the `.dockercfg` yourself in the build code and assign the values to the appropriate task or extension.

**Comment by cdancy** [comment]
@bmuschko fair enough. Yes reading the .dockercfg file, and parsing it, is what we are doing now. I think we can close out this issue. I'll open another with docker-java to see about the system properties issue. Thanks.
