### ISSUE TITLE
make a convention to imitate docker-compose?

### ISSUE THREAD

**Issue by rinswind** [bmuschko/gradle-docker-plugin#621]
Since there are tasks to reflect every docker primitive command I think a plugin can be made that will encode the docker-compose behaviour within the gradle build script.
If I can define the Dockerfile in gradle, why not the  `docker-compose.yml`'s. It is nice to have the gradle script as the single source of truth and also be able to use groovy anywhere and hook tasks etc.
Do you find value in such a feature?
Here is an example I just cobbled up from  one of my `docker-compose.yml`
```
services {
  mysql {
    image = 'mysql:5.5.60'
    environment = [
      MYSQL_DATABASE: 'logins',
      MYSQL_USER: 'user',
      MYSQL_PASSWORD: 'password',
      MYSQL_ROOT_PASSWORD: 'password'
    ]
  } 
  auth {
    image = 'osgic-login-web-service'
    stdin_open = true
    tty = true
    environment = [
      JWT_SECRET: 'something',
      DB_URL: 'jdbc:mysql://mysql:3306/logins',
      DB_USER: 'root',
      DB_PASSWORD: 'password'
    ]
    ports = [
      41001: 41000,
      40001: 40000,
      10034: 10033,
    ]
    depends_on = [mysql]
  }
  ...
}
```

**Comment by bmuschko** [comment]
Docker Compose works somewhat separate from the actual Docker commands that are run invoked through the Docker client. In fact it's a different executable (at least on the command line). While I can see the need for wanting to have a uniform Gradle plugin with functionality for both, it would make the architecture of the plugin far more complex. I've made some good experience with a different Gradle plugin specialized on Docker Compose. You can read all about it in this [blog post](https://bmuschko.com/blog/gradle-docker-compose/).

**Comment by cdancy** [comment]
Agreed. Lets not re-invent the wheel if we don't have to. If other plugins/libraries do this easily enough I would say use them if only to gain all the knowledge the communities around said libraries have and can help you with.

**Comment by rinswind** [comment]
If I am not mistaken `docker-compose` is a utility program which translates the `docker-compose.yml` to a stream of calls to the docker daemon, using the same interface that this plugin's tasks use. It does not have any privileged access to the containers etc. So it doesn't seem technically impossible to do it's job. Right?
With that said I understand you point - this was just an inquiry.

**Comment by bmuschko** [comment]
@rinswind Technically it's absolutely possible. It's a matter of wanting to have two different code paths (one that communicates with Docker Java, the other that calls an executable) and having to maintain it. Apart from that the plugin's DSL would have to reflect configuration options for Compose making it harder to understand, document and evolve.

**Comment by rinswind** [comment]
@bmuschko Understood.
What compelled you to have a gradle DSL for the Dockerfile? Similar arguments hold there it seems.
Should I move this discussion somewhere else?

**Comment by bmuschko** [comment]
@rinswind When referring to the DSL I mainly mean the exposed extension (so everything in the `docker` configuration block). The instruction-specific API of the task Dockerfile was exposed for convenience reasons. You do not have to use it. You can also [declare "plain" instructions](http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html#instruction(java.lang.String)). Please check the Javadocs of task type for more information.

For further discussion please use the [Gitter channel](https://gitter.im/gradle-docker-plugin/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge).
