### ISSUE TITLE
Add custom flag input to DockerBuildImage, or add explicit support for --cache-from

### ISSUE THREAD

**Issue by exFalso** [bmuschko/gradle-docker-plugin#628]
Currently there's no way to pass in `--cache-from` to `DockerBuildImage`.

### Expected Behavior

We should be able to specify the flag.

### Current Behavior

Currently we cannot specify this flag.

### Context

I'm trying to use the build cache using `--cache-from` to speed up CI builds.

**Comment by bmuschko** [comment]
`DockerBuildImage.cacheFrom` does exist now.
