### ISSUE TITLE
Docker build type plugin

### ISSUE THREAD

**Issue by conormullen** [bmuschko/gradle-docker-plugin#64]
Hi

First off, great work on the plugin. It has been a really useful and well designed.

While using the plugin  I had found myself having a lot of duplication across different projects in the organization. To help with this I created another gradle plugin which wraps up some of the common  workflows which your plugin can be used for. 

I have made an attempt to add this to your plugin here: https://github.com/conormullen/gradle-docker-plugin

I was wondering if this is something you would have any interest in my finishing up (Adding tests etc), or would this not be something you would see as fitting well with the goals of your plugin?

**Comment by bmuschko** [comment]
Cool, good to see additional plugins on top of the basic functionality I am providing. So far I didn't have to deal with the use case of having to provide multiple Docker build types. To avoid having to maintain another plugin, I'd want to stay away from pulling in the code. Thanks so much!
