### ISSUE TITLE
Output of docker command : example buid

### ISSUE THREAD

**Issue by defender** [bmuschko/gradle-docker-plugin#65]
Hi
Sometime it is very important to monitor docker output.
When Im running docker build with the plugin my output :

Building image from folder 'jdk-8u45'.
Using tag 'test/jdk' for image.
Created image with ID '8e934741e572'.

What is expected it to see regular docker output to monitor right execution of layers, where docker using cache etc ...

Thanks.

**Comment by bmuschko** [comment]
Did you run your build with `-i`? That should provide you with enough information.

**Comment by defender** [comment]
Should I provide this parameter as gradle parameter ? 


Sent from my Samsung device


-------- Original message --------

**Comment by bmuschko** [comment]
Yes

**Comment by bmuschko** [comment]
Does this do the trick for you?

**Comment by defender** [comment]
Unfortunately no, I still not see any build layers like I see in push output 

Thanks 


Sent from my Samsung device


-------- Original message --------

**Comment by bmuschko** [comment]
What message are you exactly looking for? Can you provide an example? It's not what has been covered in [this test case](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/test/groovy/com/bmuschko/gradle/docker/response/BuildImageResponseHandlerTest.groovy#L32) is it?

I might want to make the [response handler](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy#L26) non-final so you can pop in your own implementation.

**Comment by bmuschko** [comment]
I changed the code so you can inject your own response handling logic.

**Comment by ajmath** [comment]
Can you provide an example of how someone would output the standard docker output to stdout?

**Comment by bmuschko** [comment]
@ajmath Are you asking how to create and change the `ResponseHandler` for a task? There's no "standard" output from Docker (as you might be used to from the command line). Communication is done through the Docker HTTP(s) API.

**Comment by ajmath** [comment]
Yes, I'd like to have the gradle tasks for docker behave like the docker cli with regards to output of running/building containers.  Ideally, this would be a way I could configure the gradle task so that it would always output to standard out.  This makes it much easier to troubleshoot failures during long builds.

**Comment by bmuschko** [comment]
@ajmath Supporting Docker from the command line would mean a complete rewrite of all tasks which is not going to happen. I also don't see any benefit for wanting to do that. There are rather more benefits in using the Docker remote API. If you want to use the Docker command line, I'd recommend not to use the plugin and instead writing your own tasks of type `Exec` that call off to the executable.

**Comment by ajmath** [comment]
So are you saying that a custom `ResponseHandler` would not help in this case?

**Comment by bmuschko** [comment]
@ajmath The response handler can only handle what comes back from the HTTP call via the Docker remote API. It does not make a CLI call. Yes, you can use that. I am not sure if it suits your needs as I am not quite sure what you are looking for. Give it a try.
