### ISSUE TITLE
How to specify build options ulimit when building the docker image

### ISSUE THREAD

**Issue by reds7373** [bmuschko/gradle-docker-plugin#650]
We need to set the --ulimlit options for some of our images. Is there any way we can set those when creating the image via DockerBuildImage task?
e.g something equivalent to
docker build **--ulimit nofile=65536:65536** -t test/image:latest
Thanks!

**Comment by cdancy** [comment]
@reds7373 this is indeed currently not supported. Would you be interested in sending in a PR for this functionality?

**Comment by cdancy** [comment]
Conversation has died down here so closing issue. Feel free to re-open should you want to discuss things anymore.
