### ISSUE TITLE
defaultCommand incorrectly format CMD

### ISSUE THREAD

**Issue by Hubbitus** [bmuschko/gradle-docker-plugin#656]
Hello.

```gradle
task createMainDockerfile(type: Dockerfile) {
    from 'tomcat:9-alpine'
    defaultCommand ''' sh -c 'echo "$HELLO"' '''
}
```

### Expected Behavior
`Dockerfile` have string:
```Dockerfile
CMD sh -c 'echo "$HELLO"'
```

### Current Behavior
`Dockerfile` have instead:
```Dockerfile
CMD ["sh -c 'echo "$HELLO"' "]
```

### Context
I want write in file environment variable if it present on run time:

It work with:
```Dockerfile
CMD sh -c '[ "$LICENSE_TEXT" ] && echo "$LICENSE_TEXT" | install -D /dev/stdin /etc/unidata/license.bin && catalina.sh run'
```
But generated variant:
```Dockerfile
CMD [" sh -c 'test -n "$LICENSE_TEXT" && echo "$LICENSE_TEXT" | install -D /dev/stdin /etc/unidata/license.bin && catalina.sh run' "]
```
by plugin from:
```gradle
defaultCommand ''' sh -c 'test -n "$LICENSE_TEXT" && echo "$LICENSE_TEXT" | install -D /dev/stdin /etc/unidata/license.bin && catalina.sh run' '''
```

obviously fails with error on start:
`/bin/sh: [ sh -c 'test -n -----BEGIN: not found`
where `-----BEGIN: not found` is part of variable, passed in run time.

According to [docker documentation](https://docs.docker.com/engine/reference/builder/#cmd) it is not correct transform string into `[]` form. Furthermore double quotes does not escaped properly.

**Comment by cdancy** [comment]
@Hubbitus the [defaultCommand](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L192) method takes a _List of Strings_ which may be your problem.

**Comment by Hubbitus** [comment]
@cdancy you point to method which takes `variable amount of Strings`, not `List of String`:
so
```gradle
    defaultCommand ( [ ''' sh -c 'test -n "$LICENSE_TEXT" && echo "$LICENSE_TEXT" | install -D /dev/stdin /etc/unidata/license.bin && catalina.sh run' ''' ] )
```
lead to error:
> Could not find method defaultCommand() for arguments [[ sh -c 'test -n "$LICENSE_TEXT" && echo "$LICENSE_TEXT" | install -D /dev/stdin /etc/unidata/license.bin && catalina.sh run' ]] on task ':createMainDockerfile' of type com.bmuschko.gradle.docker.tasks.image.Dockerfile.
That expected.

If you speak I could provide 3 arguments instead of 1 string like:
```gradle
    defaultCommand 'sh', '-c', '''(test -n "$LICENSE_TEXT" && echo "$LICENSE_TEXT" | install -D /dev/stdin /etc/unidata/license.bin) && catalina.sh run'''
```
that possible, but again in plugin work incorrectly and in `Dockerfile` will be present like:
```Dockerfile
CMD ["sh", "-c", "(test -n "$LICENSE_TEXT" && echo "$LICENSE_TEXT" | install -D /dev/stdin /etc/unidata/license.bin) && catalina.sh run"]

```

**Comment by cdancy** [comment]
@Hubbitus yeah this might be one of those things you'll have to play around with a bit to get exactly right. You could try using the generic `instruction` method which will just inject the string exactly as-is into the Dockerfile.

**Comment by bmuschko** [comment]
We might have to revisit the internal logic. @Hubbitus Why do you pass in a multi-line String (`'''`) but then only use a single line?

**Comment by bmuschko** [comment]
At the moment the "shell form" is not supported. Only the "exec form" is supported.

From the Docker documentation:

> exec form, this is the preferred form

You method call should look like this:

```
defaultCommand 'sh', '-c', 'echo $HELLO'
```

which produces

```
CMD ["sh", "-c", "echo $HELLO"]
```

I am going to close the issue. Let us know if you have further questions.
