### ISSUE TITLE
Requesting new release with updated docker java library version to 3.1.0-rc-5

### ISSUE THREAD

**Issue by santhoshk2311** [bmuschko/gradle-docker-plugin#658]
### Expected Behavior

Requesting new release of gradle docker plugin that consumes docker java library version 3.1.0-rc-5.

### Current Behavior
Currently it uses docker java version 3.1.0-rc-3.

### Context

Docker java library was released recently with few bug fixes. I am looking in specific the resolution for the below issue in the docker java library.
https://github.com/docker-java/docker-java/issues/921.
its fixed in docker java library version 3.1.0-rc-5.
So requesting a new release of the gradle docker plugin consuming the latest docker java library version 3.1.0-rc-5

**Comment by bmuschko** [comment]
@cdancy Can you upgrade the shaded library and release a new version? We'll need this for multiple PRs.

**Comment by cdancy** [comment]
PullRequest going [HERE](https://github.com/bmuschko/gradle-docker-plugin/pull/660). Assuming all goes well I'll merge shortly.

**Comment by cdancy** [comment]
Looks like tests are hanging on `DockerReativeMethodsFunctionalTest > should call onNext when waiting for a container`. I'll have to look into this when I get a chance today.

**Comment by bmuschko** [comment]
@cdancy Thanks! This is the same issue as reported earlier by @mwhipple: https://github.com/bmuschko/gradle-docker-plugin/pull/639#issuecomment-411105645

**Comment by cdancy** [comment]
@bmuschko Ok so it's a more general issue. Lets take this PR in then and we can continue to poke at what is going on. Aside from this gotcha everything else appears to work as expected.

**Comment by bmuschko** [comment]
@cdancy Let me know once the CI build is fixed again before merging `master` into my branch.

**Comment by mwhipple** [comment]
reading this thread from the top I was hoping the race condition just went away in rc5 :disappointed: I'll resume poking at that tonight.

**Comment by bmuschko** [comment]
@mwhipple Unfortunately, it didn't. The CI build is currently broken on `master` so we might have to revert in the meantime.

**Comment by bmuschko** [comment]
@cdancy I ignored the failing test for now to unblock development on `master`: https://github.com/bmuschko/gradle-docker-plugin/commit/9aa296a5d7b9391cdf2c8dc330ed37e2e183252b. Please re-enable as soon as the issue has been fixed.

**Comment by cdancy** [comment]
Roger that.

**Comment by santhoshk2311** [comment]
i dont see the latest release with this change in maven here. Any idea when will it be uploaded to maven repo?
https://search.maven.org/search?q=a:gradle-docker-plugin

**Comment by cdancy** [comment]
@santhoshk2311 I publish to jcenter/bintray only. It acts as a proxy to maven-central as well, and is stupid-simple to deploy to, so I prefer to use that service over maven-central.

**Comment by santhoshk2311** [comment]
@cdancy i dont see the latest release here. http://jcenter.bintray.com/com/bmuschko/gradle-docker-plugin/
Not sure if i am looking at the wrong place. I see the latest release available is still v3.6.1.

**Comment by cdancy** [comment]
@santhoshk2311 aaahhh ... you're looking for the latest release of this plugin? Hasn't been released yet as we still have an issue on `master` branch that is causing hangs due to the upgraded version of `docker-java`. Investigation is on-going...
