### ISSUE TITLE
It should be clearer that existing container tasks support container names and not just generated ids.

### ISSUE THREAD

**Issue by mwhipple** [bmuschko/gradle-docker-plugin#666]
### Expected Behavior

The existing container tasks should rely on a property with a name that conveys that either a (generated) container id **or** a specified container name (such as provided during container creation) can be used. Documentation should be updated appropriately.

### Current Behavior

The current name of and documentation for `targetContainerId` obscure the fact that a container name could also be used, and that support does not seem easily discoverable (I picked it out of the Docker API docs).

### Context

Using explicit container names can ease several aspects of managing containers during development.
See #637

**Comment by cdancy** [comment]
Whatever we decide to use so long as things are backwards compatible, at least for 1 major release, I'm OK with entertaining ideas. We (here internally) as well as my own projects/plugins that depend on this plugin use this option extensively.

**Comment by bmuschko** [comment]
@cdancy Yes, absolutely. There will have to be a deprecation cycle for sure.

**Comment by mwhipple** [comment]
FWIW, I think the documentation updates could be sufficient (I probably should update the issue title to be more problem rather than solution oriented). The Docker API docs use `id` (potentially for the sake of REST convention) and then just have `ID or name of the container` in the parameter description.
> Naming things is hard

**Comment by bmuschko** [comment]
@mwhipple Added some documentation here: https://github.com/bmuschko/gradle-docker-plugin/pull/698
