### ISSUE TITLE
Use task configuration avoidance API for task type of this plugin

### ISSUE THREAD

**Issue by JLLeitschuh** [bmuschko/gradle-docker-plugin#674]
This is different from using the `Provider` API for gradle, this is more using the lazy task configuration API like `register` instead of `create`.

https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

For example, instead of `project.task(DOCKERFILE_TASK_NAME, type: Dockerfile) { ...` using
`project.tasks.register(DOCKERFILE_TASK_NAME, type: Dockerfile) {`

**Comment by bmuschko** [comment]
Thanks for creating the issue. I wanted to do this as well sooner or later. We might have a wait a little though as this feature was only introduced in a recent version of Gradle. In turn all consumers will have to upgrade the Gradle version in their projects. Sometimes it's hard and long process to do this leaving behind users stuck on an older version of Gradle.

**Comment by bmuschko** [comment]
@JLLeitschuh With the introduction of the `Provider` API, the minimum version of the plugin is already Gradle 4.8. I think I'd be OK with using the new API for task avoidance and raising the minimum version to 4.9. Would you be interested in providing a PR?

**Comment by JLLeitschuh** [comment]
Something we may want to try because it seems to work in my plugin is something like this:
https://github.com/JLLeitschuh/ktlint-gradle/blob/64693e1b253eb10e7ad1bcbd3ddeb79127b3b03a/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBasePlugin.kt#L18-L25
```kotlin
        val filterTargetApplier: FilterApplier = {
            if (GradleVersion.current() >= GradleVersion.version("4.9")) {
                // API only added in Gradle 4.9
                target.tasks.withType(KtlintCheckTask::class.java).configureEach(it)
            } else {
                target.tasks.withType(KtlintCheckTask::class.java, it)
            }
        }
```

**Comment by bmuschko** [comment]
@JLLeitschuh Yes, that would be an option but it would make the plugin code much harder to maintain.  going forward. Apart from that `GradleVersion` is an internal class. I'd rather "force" users to upgrade to Gradle 4.9 if they want to use the latest features of the plugin. I'd don't expect a lot of breaking changes between 4.8 and 4.9.

**Comment by bmuschko** [comment]
@JLLeitschuh Still interested in contributing this change? I'd be OK with raising the minimum Gradle version to 4.9 now that 5.0 is already out.

**Comment by JLLeitschuh** [comment]
I don't have the time to dedicate to fixing this right now, but perhaps I will shortly.

**Comment by bmuschko** [comment]
@cdancy The benefit only exists for plugins that create a new task. That applies to `DockerJavaApplicationPlugin.groovy` and `DockerSpringBootApplicationPlugin.groovy`. Any other code that creates tasks with one of the Docker task types will have to call `register` instead of `create`. The link in the initial comment of this issue explains the rest.

By "our" I guess you mean one of your internal plugins that wraps the `bmuschko/gradle-docker-plugin`?

**Comment by tylernhoward** [comment]
I thought I would start the process and issued a PR for a change that _we_ required to make use of the configuration avoidance api in a plugin that used `AbstractDockerRemoteApiTasks`  from the `DockerRemoteApi`. Let's start this migration slowly but surely!

**Comment by bmuschko** [comment]
I think now would be a good time to get the process started. Looking forward to a pull request from someone that wants to take on the work.

**Comment by cdancy** [comment]
Folks can checkout similar things I did with a plugin I wrote below which depends on this one. Im not sure how much benefit we will get here however.

https://github.com/project-aries/gradle-docker-applications-plugin/blob/master/src/main/groovy/com/aries/gradle/docker/applications/plugin/tasks/Up.groovy

**Comment by bmuschko** [comment]
@JLLeitschuh Interested in contributing this functionality? I guess I am going to close the issue otherwise until somebody wants to contribute.

**Comment by JLLeitschuh** [comment]
I'm not using this plugin anymore now that I'm at Gradle. I think it's still a worthwhile feature & I'm more than happy to review any PR that someone contributes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bmuschko** [comment]
Alright, I am closing this issue until somebody decides to step up.

**Comment by ryandens** [comment]
Hi @bmuschko, I'm taking a quick look into this issue to see if that's something I could this week but I have a couple of questions.

First, are you looking for this to be all done in one PR or are you looking for an incremental change, gradually cutting all task creation/registration over to using the configuration avoidance APIs?

Second, I noticed a circular dependency between the `dockerSyncBuildContext` and the `dockerCreateDockerfile` tasks in the `DockerSpringBootApplicationPlugin`. Specifically, the `dockerCreateDockerfile` task depends on the `dockerSyncBuildContext` but the `dockerSyncBuildContext` task needs to be registered after the `dockerCreateDockerfile` so that the `dockerSyncBuildContext` task can access the `dockerCreateDockerfile` destDir. In its state today it seems to be working fine, but this gets uglier when the configuration avoidance APIs start getting used:
```java
project.plugins.withType(JavaPlugin) {
            project.plugins.withId(SPRING_BOOT_PLUGIN_ID) {
                TaskProvider<Dockerfile> createDockerfileTaskProvider = createDockerfileTask(project, dockerSpringBootApplication)
                TaskProvider<Sync> syncBuildContextTaskProvider = createSyncBuildContextTask(project, createDockerfileTaskProvider)
                createDockerfileTaskProvider.get().dependsOn syncBuildContextTaskProvider
                DockerBuildImage dockerBuildImageTask = createBuildImageTask(project, createDockerfileTaskProvider, dockerSpringBootApplication)
                createPushImageTask(project, dockerBuildImageTask)
            }
        }
```

Do you have any thoughts/general refactoring goals for this part of the plugin that I should take into account while working this?

**Comment by bmuschko** [comment]
@ryandens

> Second, I noticed a circular dependency between the dockerSyncBuildContext and the dockerCreateDockerfile tasks in the DockerSpringBootApplicationPlugin. Specifically, the dockerCreateDockerfile task depends on the dockerSyncBuildContext but the dockerSyncBuildContext task needs to be registered after the dockerCreateDockerfile so that the dockerSyncBuildContext task can access the dockerCreateDockerfile destDir. 

Gradle doesn't allow users to create circular dependencies between tasks. Your evaluation isn't completely correct. I'd have to have a deeper look to identify potentially issues. I see that you already created a PR so let's iterate from there.

> Do you have any thoughts/general refactoring goals for this part of the plugin that I should take into account while working this?

Generally speaking we can take this incrementally. It shouldn't be too much work though as it only applies to the `DockerJavaApplicationPlugin` and `DockerSpringBootApplicationPlugin`. We should take into account everything described here: https://docs.gradle.org/current/userguide/lazy_configuration.html.

**Comment by sa-mendez** [comment]
I have recently been working on changing over our Gradle build to leverage the task avoidance API.  In our build we are using your plugin.  I have a test case that evidences a problem with this plugin not conforming to the use of the configuration avoidance API.

I realize that changing your plugins is still in progress, and I should not expect things to work.  However, I wanted to mention that the configuration avoidance API use appears to affect more than just DockerJavaApplicationPlugin and DockerSpringBootApplicationPlugin.

Here is a simple build file that evidences the problem:

```gradle
plugins {
        // Apply the application plugin to add support for building an application
        id 'application'
 	 
 	 /**
 	  * Gradle plugin that adds support for building(running, etc) Docker images
 	  * For more info see:
 	  * https://bmuschko.github.io/gradle-docker-plugin/
 	  */
 	 id "com.bmuschko.docker-remote-api" version "5.3.0"
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}


dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    implementation 'com.google.guava:guava:27.0.1-jre'    
}

// Import task types
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.DockerPushImage
import com.bmuschko.gradle.docker.tasks.image.DockerRemoveImage

// DockerBuildImage, DockerPushImage fails, DockerRemoveImage succeeds
tasks.register("dockerTask", DockerBuildImage) {
	throw new GradleException("This task should never be configured")
}
```
If you run _gradlew clean_, the dockerTask that I register, should never be configured and the exception never thrown.  However, the exception does get thrown.  It seems to work if you set the task type to DockerRemoveImage.  If you use DockerBuildImage, or DockerPushImage as the type, then the exception gets thrown.  FYI, I ran this using Gradle 5.6.1, and 6.0 and had the same results.

I figured I would provide you guys with a simple test case to verify that at least those three tasks work with the new configuration avoidance API, when you guys finalize this effort.

Thank you,

Sergio

**Comment by bmuschko** [comment]
@sa-mendez At this time, I don't think anyone is working on this change. As usual we are happy to receive a pull request from the community. The remote API plugin configures those tasks initially. That's why you see the behavior.

**Comment by sa-mendez** [comment]
Ok.  Thank you for the explanation.

**Comment by gaiazov** [comment]
Its a one line change, see #940

**Comment by bmuschko** [comment]
Not quite a one liner change, @gaiazov ;-)
