### ISSUE TITLE
Spring Boot Application Plugin does not support Spring Boot Gradle Plugin 1.x

### ISSUE THREAD

**Issue by jonatan-ivanov** [bmuschko/gradle-docker-plugin#679]
Spring Boot Application Plugin fails with Spring Boot Gradle Plugin 1.x

### Expected Behavior
The Spring Boot Application Plugin to build the docker images if Spring Boot Gradle Plugin 1.x is present.

### Current Behavior
The Spring Boot Application Plugin (`com.bmuschko.docker-spring-boot-application`) fails if Spring Boot Gradle Plugin 1.x (`org.springframework.boot`) is present, it seems it needs the 2.x version of the plugin.

```
* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin [id 'com.bmuschko.docker-spring-boot-application']
   > Task with name 'bootJar' not found in root project 'pacman'.
```

### Context
I'm trying to build and push docker images using  `org.springframework.boot:spring-boot-gradle-plugin:1.5.15.RELEASE` and `com.bmuschko:gradle-docker-plugin:3.6.2`.

It seems that the Spring Boot Application Plugin needs some tasks and classes (`bootJar`) which are only available in the 2.x version of the Spring Boot Gradle Plugin.

[According to the docs of Spring Boot Gradle Plugin 2.x](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#packaging-executable-jars), the `bootJar` task is doing a simirar job to the `bootRepackage` [task in the 1.x versions of the plugin](https://docs.spring.io/spring-boot/docs/1.5.x/reference/html/build-tool-plugins-gradle-plugin.html#build-tool-plugins-gradle-packaging).

### Steps to Reproduce (for bugs)
Sample `build.gradle` file which reproduces the issue:

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.5.15.RELEASE'
        classpath 'com.bmuschko:gradle-docker-plugin:3.6.2'
    }
}


apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'com.bmuschko.docker-spring-boot-application'
```

### Your Environment
```
classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.5.15.RELEASE'
classpath 'com.bmuschko:gradle-docker-plugin:3.6.2'
```

```
$ gradle -version
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10.0.2 ("Oracle Corporation" 10.0.2+13)
OS:           Mac OS X 10.13.6 x86_64
```

**Comment by bmuschko** [comment]
That's correct. The underlying Spring Boot Gradle plugin changed quite a bit between 1.x and 2.x. I don't think we'll want to maintain logic tailored to multiple versions. It will make our plugin very hard to maintain. On your end you'll likely be better off by upgrading to the new Spring Boot plugin and therefore a newer version of Spring Boot.

I will add a note to the documentation that only Spring Boot 2.x is supported.

**Comment by bmuschko** [comment]
Add a note to the documentation: https://github.com/bmuschko/gradle-docker-plugin/commit/5ffec06e862f2de80f864b50cf18e0df102041be

**Comment by bmuschko** [comment]
I am going to close this issue as the effort for supporting the Spring Boot plugin version 1.x would be too high. The implementation will likely be straightforward. However, it would require a whole suite of tests to ensure that it works properly.

**Comment by bmuschko** [comment]
@gganssauge I recently ran into the same issue when I tried out the plugin in standalone project even though our tests are passing. There's some sort of evaluation order issue going on (I believe in the Spring Boot plugin from Pivotal) or it is a bug in Gradle core of some sort. You can work around it by applying the plugin with the `buildscript` notation. Would you mind verifying it in your project and opening a new issue?

**Comment by kpb** [comment]
I can confirm that using Spring boot 2.1.0.RELEASE and Gradle 4.10.2, I have to use the (heinous) buildscript notation or the plugin fails as describe by @gganssauge .
