### ISSUE TITLE
Window bind paths are not parsed correctly using the static Bind.parse function in dockerjava 

### ISSUE THREAD

**Issue by a4chet** [bmuschko/gradle-docker-plugin#682]
Referencing issue logged with [dockerjava](https://github.com/docker-java/docker-java/issues/1118). 

In version 3.2.5 of gradle-docker-plugin, the `createBind()` function was updated to use the [Bind.Parse](https://github.com/bmuschko/gradle-docker-plugin/blob/6acab4231b5927cbdf3e87de9098ad6da6345b73/src/main/groovy/com/bmuschko/gradle/docker/utils/DockerThreadContextClassLoader.groovy#L340) in the DockerThreadContextClassLoader.groovy.

This breaks running on Windows, as Windows uses colons to delimit the drive letters (e.g. `c:\temp`). 

### Expected Behavior
I would expect the gradle-docker-plugin to work on Windows paths as a bind point for Docker containers.

### Current Behavior
The plugin from dockerjava throws an `IllegalArgumentException` when using Windows paths (e.g. `c:\temp:c:\logs`)

### Context
I have recompiled the DockerThreadContextClassLoader.groovy with the original `createBinds/createBind` functions that existed prior to 3.2.5 of the gradle-docker-plugin

### Your Environment
Windows 10.

**Comment by bmuschko** [comment]
Would you be interested in providing us with a pull request for this change?

**Comment by cdancy** [comment]
@a4chet have a go at using a custom parse method and we can see how that looks and feels and go from there.

**Comment by MortlMcCrisis** [comment]
Any progress on this issue? I am heavily using the plugin for testing and this issue is an impediment for debugging.

**Comment by bmuschko** [comment]
@MortlMcCrisis We are happy to accept pull requests. At the moment I just don't have time to implement it myself.

**Comment by bmuschko** [comment]
This issue didn't get tracking for over a year. Closing it for now.

**Comment by mariuszs** [comment]
This issue is still valid

**Comment by bmuschko** [comment]
@mariuszs That is correct. As you can see in the history of this issue we were looking for external contributions to fix the issue. Unfortunately, nobody signed up for it. To avoid getting overwhelmed by issues that likely will never get addressed, we closed it. If you are interested in fixing the issue, please open a pull request. We'd be more than happy to guide, review and merge.
