### ISSUE TITLE
Application Default Ports

### ISSUE THREAD

**Issue by devinrsmith** [bmuschko/gradle-docker-plugin#694]
The docker java application plugin sets the default ports to `[8080]`,

https://github.com/bmuschko/gradle-docker-plugin/blob/f10bb61cd91c66ebde10b895aeeb79c50799d049/src/main/groovy/com/bmuschko/gradle/docker/DockerJavaApplication.groovy#L42-L43

but the [documentation](https://github.com/bmuschko/gradle-docker-plugin/blob/f10bb61cd91c66ebde10b895aeeb79c50799d049/src/docs/asciidoc/22-extension.adoc) shows that it should be `[]` by default.

I'm assuming that the documentation is correct, and the code should be updated?

**Comment by bmuschko** [comment]
The documentation was incorrect. I just [corrected it](https://github.com/bmuschko/gradle-docker-plugin/commit/9f061a1da6da826355a0dcd354509d08578c597e). The change will go out with the next version.
