### ISSUE TITLE
DockerSaveImage does not respect the tag option

### ISSUE THREAD

**Issue by robbie-demuth** [bmuschko/gradle-docker-plugin#703]
The DockerSaveImage task always saves all images from a repository, even when a particular tag is specified.

It is possible to workaround this issue by specifying both the repository and the tag in the repository property.

You can reproduce this issue using the following build script:

```groovy
import com.bmuschko.gradle.docker.tasks.image.DockerPullImage
import com.bmuschko.gradle.docker.tasks.image.DockerSaveImage

plugins {
  id 'com.bmuschko.docker-remote-api' version '4.0.4'
}

task pullAlpine35(type: DockerPullImage) {
  repository = 'alpine'
  tag = '3.5'
}

task pullAlpine36(type: DockerPullImage) {
  repository = 'alpine'
  tag = '3.6'
}

task saveAlpine36(type: DockerSaveImage) {
  dependsOn pullAlpine35, pullAlpine36
  repository = 'alpine'
  tag = '3.6' // This is not respected
  destFile = file('alpine-3.6.tar')
}
```

If you run `gradle saveAlpine36` and then `docker load -i alpine-3.6.tar`, the `docker load` command will load all images in the `alpine` repository:

```
$ docker load -i alpine-3.6.tar 
Loaded image: alpine:3.5
Loaded image: alpine:3.6
```

It should only load the `alpine:3.6` image since that is how the task was configured

**Comment by bmuschko** [comment]
Do you have an idea which version of the plugin broke the functionality? Did this ever work? My guess is that it is (still) an issue in the Docker Java library.

**Comment by cdancy** [comment]
Yeah fix was never merged. This actually just hit us this past week and has us up until the wee hours of the morning trying to figure out what was up until one of our devs stumbled across the issue which I had forgotten about.

**Comment by bmuschko** [comment]
@cdancy Thanks for the background info.
@robbie-demuth I'd suggest you follow up with the Docker Java project to get the functionality implemented on their end first.

**Comment by bmuschko** [comment]
@robbie-demuth I don't think we can do anything about the issue until it doesn't get fixed in Docker Java. I would suggest you follow up with them if you'd like to get some traction. Thanks!

**Comment by cdancy** [comment]
PR was just merged! I'll try to lean on him for a new release ;)

**Comment by cdancy** [comment]
He just released `3.1.1`.

**Comment by bmuschko** [comment]
@cdancy Cool, can you create a new shaded version of Docker Java when it becomes available on Maven Central?

**Comment by bmuschko** [comment]
@robbie-demuth Docker Java 3.1.1 has been released and the library is now shaded in this code base. You would now be able to work on a fix for this if you'd like to send a pull request.

**Comment by cdancy** [comment]
> Cool, can you create a new shaded version of Docker Java when it becomes available on Maven Central?

Had no idea I was this far behind :( But at least I no longer have to maintain that project anymore so thanks @bmuschko ! ;)

Lets close this issue for now as the problem should be resolved. Folks on this thread feel free to re-open the issue should the need arise.
