### ISSUE TITLE
Feature Request: DockerPushImage doesn't seem to use default docker hub credentials / config

### ISSUE THREAD

**Issue by packplusplus** [bmuschko/gradle-docker-plugin#705]
### Expected Behavior
It would be nice for DockerPushImage to use whatever is in the ~/.docker/config for credentials / config for pushing to a remote image repository (like docker hub). 

### Current Behavior
You can specify a remote repo, with creds, and a url using `registryCredentials`, which is great, but requires users to have environment variable set, shared keys hardcoded in your build.gradle, or some other such machination. 

### Context
There aren't really simple ways to script pulling docker login creds back out of docker. Simplifying developer config / setup is paramount, and asking them to export variables, or keep env vars in remote logins in sync with their bash profiles is a much bigger lift than it should be. 

### Workaround
I used the java-api directly to get the functionality I needed. 
```
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'com.github.docker-java:docker-java:3.0.14'
    classpath 'javax.activation:activation:1.1.1' /* Needed for some java version nonsense */
  }
}

import com.github.dockerjava.core.DockerClientBuilder
import com.github.dockerjava.core.command.PushImageResultCallback

task dockerUpload {
  def client = new DockerClientBuilder().getInstance().build()

  client.pushImageCmd('some_org/some_project')
    .withTag('some_tag')
    .exec(new PushImageResultCallback())
    .awaitSuccess() // will error out on failed uploaded or failed builds
}
```

There seems to be a differences between AuthConfig() and [effectiveAuthConfig()](https://github.com/docker-java/docker-java/blob/60d7800cd885d3035344de044ae4c8d28dfe511c/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java#L263)

**Comment by bmuschko** [comment]
Definitely sounds like a good idea. Would you be interested in contributing this feature?

**Comment by packplusplus** [comment]
I'm willing to take a swing at it, but I'm Ops by trade, so my java is super hacky. I was super confused as to how / if gradle-docker-plugin actually using the docker-java libraries until I found [this](https://github.com/bmuschko/gradle-docker-plugin/blob/efdb9298468b7b7deee7aa577b5a41017d20ac2c/src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy#L34-L43) chunk of code that pulls down the libs, and even includes the `javax.activation` nonsense. 

My guess would be hack the registryCredentials methods to include code like the [effectiveAuth](https://github.com/docker-java/docker-java/blob/60d7800cd885d3035344de044ae4c8d28dfe511c/src/main/java/com/github/dockerjava/core/DefaultDockerClientConfig.java#L263-L276). Looks up the destination url in the config files, and grabs the creds based on that. Maybe add an `dockerConfigFile = true` to be explicit about if its going to try to pull those values? It could later be extended to dockerConfigFilePath if needed.

**Comment by bmuschko** [comment]
>  I was super confused as to how / if gradle-docker-plugin actually using the docker-java libraries until I found this chunk of code that pulls down the libs, and even includes the javax.activation nonsense.

This is more a workaround for an issue in Gradle core than anything else. Gradle core does not run plugins in their own classloader. Without running plugins in their own classloader, the classpath could contain incompatible versions of transitive dependencies for Docker Java. In the meantime, the situation got a bit better. We are using a shaded version of Docker Java that moves the default packages for transitive dependencies so this workaround might not be necessary anymore.

> My guess would be hack the registryCredentials methods to include code like the effectiveAuth. Looks up the destination url in the config files, and grabs the creds based on that. Maybe add an dockerConfigFile = true to be explicit about if its going to try to pull those values? It could later be extended to dockerConfigFilePath if needed.

I'd check first if Docker Java provides some sort of configuration that tells it to automatically read configuration from `~/.docker/config`. There might already be a method in place that you can use. If the library provides the functionality then it should be as easy as calling the method (and potentially verifying if the configuration was found or is available). If the configuration is already available then use it. Alternatively, a user can override the read configuration by providing the information through the DSL. I don't think we'll need to add a new flag for it. It will simply be a convention.

It's weird that the method `effectiveAuthConfig` requires you to pass in an image name. I don't understand why you'd have to do that.

Overall sounds like a reasonable approach. I am sure the maintainers of this plugin can help.

@cdancy @orzeh Any thoughts on this?

**Comment by cdancy** [comment]
Yeah that _sounds_ reasonable enough and I echo all the points @bmuschko made above. Feel free to send in a PR.

**Comment by packplusplus** [comment]
I've been battling getting a dev environment working (gradle plugin development is tricky, mavenLocal() doesn't find the local maven repo). I'm going to keep at it, but if anyone finds this issue, I've been using this gross work around.

```
task setupDockerUser {
  def tdockerUser = new ByteArrayOutputStream()
  def tdockerPass = new ByteArrayOutputStream()

  exec{
    commandLine 'bash', '-c', "jq -r '.auths.\"https://index.docker.io/v1/\".auth' ~/.docker/config.json | base64 --decode | awk -F : '{print \$1}'"
    standardOutput = tdockerUser;
  }

  exec{
    commandLine 'bash', '-c', "jq -r '.auths.\"https://index.docker.io/v1/\".auth' ~/.docker/config.json | base64 --decode | awk -F : '{print \$2}'"
    standardOutput = tdockerPass;
  }

  ext.dockerUser = tdockerUser.toString().trim()
  ext.dockerPass = tdockerPass.toString().trim()
  //println("User: ${dockerUser} Pass: ${dockerPass}")
}

docker {
  registryCredentials {
    username = setupDockerUser.dockerUser
    password = setupDockerUser.dockerPass
  }
}
```

**Comment by bmuschko** [comment]
I am going to close this issue for now. We are looking forward to your PR in case you are planning to contribute.
