### ISSUE TITLE
How to push docker image to repository

### ISSUE THREAD

**Issue by ivanstefko** [bmuschko/gradle-docker-plugin#708]
I would like to build & push my custom docker image into my private artifactory. 

Currently I have following gradle tasks:

```javascript
task buildImage(type: DockerBuildImage) {
    description "Builds custom docker image."
    dependsOn createDockerfile
    inputDir = createDockerfile.destFile.get().asFile.parentFile
    tag = "company/keycloak:${keycloakVersion}".toString()
}
```

The buildImage taks works as expected and I can see built image as: 

REPOSITORY | TAG | IMAGE ID | CREATED | SIZE
-------------- | ---- | ----------- | ---------- | -------
company/keycloak | 4.6.0.Final | 197fc13e5fcd | 12 days ago | 818MB

Now I would like to push this image to artifactory with gradle task: 

```javascript
task pushImage(type: DockerPushImage) {
    description "Push custom docker image."
    tag = "${keycloakVersion}"
    imageName = "company/keycloak" 
}
```

This one fails because know nothing about my private artifactory

```javascript
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pushImage'.
> Could not push image: denied: requested access to the resource is denied`
```

I have find the way how can I push this image to artifactory but it requires to use artifactory url in tag like so: 

```javascript
project.ext.artifactory= "artifactory.company.com:443/"
...
task buildImage(type: DockerBuildImage) {
    description "Builds custom docker image."
    dependsOn createDockerfile

    inputDir = createDockerfile.destFile.get().asFile.parentFile
    tag = "${artifactory}company/keycloak:${keycloakVersion}".toString()
}
```
and 
```javascript
task pushImage(type: DockerPushImage) {
    description "Push custom docker image."

    tag = "${keycloakVersion}"
    imageName = "${artifactory}company/keycloak"  
}
```
now it works and I can find my docker image in my artifactory but only problem is that I don't want to have docker image in following form (with artifactory url in the name)

REPOSITORY | TAG | IMAGE ID | CREATED | SIZE
-------------- | ---- | ----------- | ---------- | -------
**artifactory.company.com:443**/company/keycloak | 4.6.0.Final | 197fc13e5fcd | 12 days ago | 818MB

I need to only simple name of the image `company/keycloak`. Is there any way how to define artifactory url for pushImage task? 

Plugin: 
```javascript
plugins {
    id 'java'
    id 'com.bmuschko.docker-remote-api' version '4.0.5'
}
```
docker version: 
```javascript
$ docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 Kubernetes:
  Version:          v1.10.3
  StackAPI:         v1beta2
```

Thanks!

**Comment by cdancy** [comment]
I'm not sure I understand your problem. Docker needs a URL to know where to push. Are you thinking of sourcing the URL from some other location?

**Comment by ivanstefko** [comment]
@cdancy I'm able to push docker image to artifactory only if docker image name contains artifactory URL. I'm looking for the way how to create docker image without artifactory URL (see below like official jboss/keycloak has) and  only when I would like to push this docker image to artifactory I would like to set some way the artifactory URL. 
Currently I have to define artifactory URL for my custom docker image (see bellow) if I would like to push it into artifactory. 

```javascript
$ docker images
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
artifactory.zoomint.com:443/zoomint/keycloak          4.6.0.Final         6a0f9fa695da        24 hours ago        818MB
jboss/keycloak                                        4.5.0.Final         7874d3a082ee        2 months ago        858MB
```
In this case If I would like to use my custom docker image e.g. in helm chart I have to define something like this: 
```javascript
keycloak:
  replicas: 1

  image:
    repository: artifactory.zoomint.com:443/zoomint/keycloak    ## << this looks really strange 
    ## repository: zoomint/keycloak                             ## << this is the goal 
    tag: 4.6.0.Final
    pullPolicy: IfNotPresent
```

my goal: 
```javascript
$ docker images
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
zoomint/keycloak                                      4.6.0.Final         6a0f9fa695da        24 hours ago        818MB
jboss/keycloak                                        4.5.0.Final         7874d3a082ee        2 months ago        858MB
```

so regarding to your plugin I'm looking for the way how to build docker image without artifactory url

```javascript
task buildImage(type: DockerBuildImage) {
    group "docker"
    description "Builds custom docker image."

    dependsOn createDockerfile, copyKeycloakMetricsSpi, copyKeycloakRealmInitScripts
    
    inputDir = createDockerfile.destFile.get().asFile.parentFile
    tags = ["zoomint/keycloak:${project.dockerTag}".toString()]    // no artifactory URL here
}
```

and for pushImage task define where to push this image

```javascript
task pushImage(type: DockerPushImage, dependsOn: buildImage) {
    group "docker"
    description "Push custom docker image."

   // <<< somehow define here the artifactory URL 
    tag = project.dockerTag
    imageName = "${project.dockerHost}/${project.dockerRepo}".toString()
}
```

I think docker doesn't need to know artifactory URL when docker image is building ... docker needs to know the artifactory URL if would like to push this docker image to artifactory.

**Comment by orzeh** [comment]
@ivanstefko I'm afraid everything works as expected. See docs:
https://docs.docker.com/engine/reference/commandline/push/
https://blog.docker.com/2013/07/how-to-use-your-own-registry/

> I think docker doesn't need to know artifactory URL when docker image is building ... docker needs to know the artifactory URL if would like to push this docker image to artifactory.

That's true.

**Comment by ivanstefko** [comment]
@orzeh mentioned examples only explain how docker push command works and I agree there should be artifactory URL for push - that make sense. But nothing about building docker image. Why I have to use artifactory URL in docker name if only build the docker image... 

If you see the docs the normal flow for build & tag & push image: 

```javascript
$docker build -t my-custom-image:1.1.0 . 
// builds the custom docker image with name my-custom-image in version 1.1.0
// ! here is not required define ANY artifactory URL

$docker tag my-custom-image:1.1.0 my.local.artifactory:5000/my-image
// creates tag for my image -> artifactory URL required

$docker push my.local.artifactory:5000/my-image
// push docker image to artifacotry 

```
this is a normal standard case and we can see that for build docker image we don't need to define artifactory url ... this is required only for tag and push. 

So if I would like to do it using your plugin.. what should I do? 

Additional questions ... if I have in my build.gradle tasks 'buildImage' and 'pushImage' .. whitch tasks is reponsible for tag the docker image? Is it happening in 'pushImage' method where I define 'tag' property?

**Comment by orzeh** [comment]
@ivanstefko your workflow should be: build image, tag image, push image. Documentation for each of these tasks can be found in our [User Guide](https://bmuschko.github.io/gradle-docker-plugin/#images).

**Comment by ivanstefko** [comment]
@orzeh thanks.. I've already tried to tag my docker image but I had a problem with following
```javascript
* What went wrong:
A problem was found with the configuration of task ':tagImage'.
> No value has been specified for property 'imageId'.
```

My tagImage task looks like this: 
```javascript
task tagImage(type: DockerTagImage) {
    repository = "artifactory.zoomint.com:443"
    tag = "zoomint/keycloak :4.6.0.Final"  // if I understand correctly this one should be the image name which I need to tag
}
```

Documentation say nothing about 'imageId' for DockerTagImage - [here](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerTagImage.html)

I've already tried to use something like this but didn't help: 
```javascript
imageId = buildImage.getImageId()
```

**Comment by orzeh** [comment]
@ivanstefko please try 
`targetImageId = buildImage.getImageId()`

I agree that there is no documentation for such basic usage scenario. Are you interested in submitting PR to User Guide?

**Comment by orzeh** [comment]
@ivanstefko sorry it should be:
````groovy
targetImageId buildImage.getImageId()
````

**Comment by ivanstefko** [comment]
@orzeh great! Works fine now. Just for summary here is the complete flow with build -> tag -> push docker image using the plugin

```javascript
project.ext {
    dockerRegistry = project.dockerRegistry
    dockerRepo = project.dockerRepo
    dockerTag = "${keycloakVersion}".toString()
}

...

task buildImage(type: DockerBuildImage) {
    description "Builds custom docker image."

    dependsOn createDockerfile
    
    inputDir = createDockerfile.destFile.get().asFile.parentFile
    tags = ["${project.dockerRepo}:${project.dockerTag}".toString()]
}

task tagImage(type: DockerTagImage, dependsOn: buildImage) {
    description "Tag custom docker image."

    targetImageId buildImage.getImageId()
    repository = "${project.dockerRegistry}/${project.dockerRepo}".toString()
    tag = project.dockerTag
}

task pushImage(type: DockerPushImage, dependsOn: tagImage) {
    group "docker"
    description "Push custom docker image."

    tag = project.dockerTag
    imageName = "${project.dockerRegistry}/${project.dockerRepo}".toString()
}
```

just FYI: the 'tag' task creates new record in docker list for images... 
```javascript
$ docker images
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
zoomint/keycloak                                      4.6.0.Final       bec72afd5e84        About an hour ago   818MB
artifactory.office.zoomint.com:443/zoomint/keycloak   4.6.0.Final       bec72afd5e84        About an hour ago   818MB

```
