### ISSUE TITLE
Multiple Exposed Ports

### ISSUE THREAD

**Issue by stevelaw** [bmuschko/gradle-docker-plugin#71]
There does not appear to be a way to expose multiple ports (or the docs don't specify how).  My image requires 8080 and 8181 to be exposed.

Is this currently available?

**Comment by bmuschko** [comment]
Are you asking about the `DockerCreateContainer` task? If yes, multiple ports can defined by using the property [exposedPorts](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy#L111).

**Comment by stevelaw** [comment]
Sorry, I was referring to `DockerBuildImage`.

**Comment by bmuschko** [comment]
Are you sure you don't want to define the ports when you run the container and not when you build the image? It doesn't look like the Docker API doesn't give you an option for providing a port when [creating an image](https://docs.docker.com/reference/api/docker_remote_api_v1.18/#create-an-image).

**Comment by bmuschko** [comment]
I am closing this issue as it's not supported by Docker.
