### ISSUE TITLE
DockerLoadImage imageStream property example?

### ISSUE THREAD

**Issue by anthonywendt** [bmuschko/gradle-docker-plugin#710]
I am new to gradle and trying to figure out how to set the imageStream property in the DockerLoadImage task type. I have a base image in my project that I need to load before building the new image. Our environment doesn't have access to a registry yet to push and pull images from and is a closed system. Any help on how to set the imageStream property in my build.gradle file would be greatly appreciated.

Thanks,
Anthony

**Comment by anthonywendt** [comment]
I got it to work. Below is the task I created to load my base image for our project. Seems to do the trick.

task loadBaseImage(type: DockerLoadImage) {
    imageStream = {file('docker/base-image.tar').newInputStream()}
}

**Comment by cdancy** [comment]
@anthonywendt glad you got it to work. Yeah this is more a gradle issue, and how to wire things up correctly, than anything else.
