### ISSUE TITLE
Set JVM parameters at runtime in spring boot application

### ISSUE THREAD

**Issue by richardshelby** [bmuschko/gradle-docker-plugin#711]
### Overview

I need to be able to dynamically modify the heap size @ runtime.  Previously we used this docker file:

```docker
FROM openjdk:8-jdk-alpine
VOLUME /tmp
 ...
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar
```

When using your plugin I see no option to create the ENTRYPOINT command in shell form (provided is only the exec form... which is preferred so that makes sense).  I see no way of expanding the JAVA_OPTS at runtime since no console is invoked.  I would like to start the container like so:

```bash
$ docker run -e JAVA_OPTS="-Xmx4g -Xms1g" <container>
```

This problem is further complicated by the following:
- JVM arguments should come after the java command and before the -jar <jar>... so I cannot put them after on the cmd line (tried that)
- without the shell form of ENTRYPOINT the JAVA_OPTS will not be expanded
- spring boot does not care about 'JAVA_OPTS'... that is tomcat specific. This means it must be expanded (I think)

This topic was referenced here (but I do not see a solution to my problem): https://github.com/bmuschko/gradle-docker-plugin/issues/647

Lastly... Thank you for this plugin and awesome documentation!  Really stellar!  
-Rich

---

### Expected Behavior
I would like a variable to be expanded at runtime and I would like to keep using dockerCreateDockerfile task in the spring boot application plugin.

### Current Behavior
the JVM option variable is not expanded and I see no correct way of applying JVM parameters at runtime.

### Context
the sprint boot application needs special memory settings and should be dynamic without a new build.

### Your Environment
mac osx - mojave
gradle 4.10.2
java 8
spring boot 2.1.0-RELEASE

**Comment by richardshelby** [comment]
follow up:

I think I solved this.  I defined a custom Dockerfile task and used the instruction command:

```groovy
task appDockerCreateDockerfile(type: Dockerfile) {
    destFile = project.file(dockerBuildDir + 'AppDockerfile')

    from 'openjdk:8-jre-alpine'
    volume '/tmp'
    addFile bootJar.archiveName, '/app.jar'
    instruction("ENTRYPOINT exec java \$JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar")
}
```
_note: dockerBuildDir is a var_

This works fine.  Since the 'exec' form of ENTRYPOINT does not support variable expansion I don't see another way. Please let me know if I missed something or this looks invalid... posting this for others if they come across the same problem.  Java JVM args. seems like a common use case.

**Comment by bmuschko** [comment]
I'll have to have another look at the recommendations I gave and add integration tests + documentation for them. I was planning to do it for a long time but didn't get around to actually doing it. You are using the [Spring Boot Application Plugin](https://bmuschko.github.io/gradle-docker-plugin/#spring_boot_application_plugin) then you don't need to create a new `Dockerfile` task. You can just modify the one that's also in place.

I am glad you found a solution. I'll keep this issue open as a reminder to provide good examples for those use cases.

**Comment by bmuschko** [comment]
I am going to look at this soon and add some documentation. Give me a couple of days.

**Comment by bmuschko** [comment]
I added some documentation for this: https://github.com/bmuschko/gradle-docker-plugin/commit/6d128488f0999f32969edf5c4c2502a1e2db2ce6. Will be available in the user guide with the next release. Hope that will make it more clear.
