### ISSUE TITLE
DockerBuildImage tags.add/addAll only work after using tags.set

### ISSUE THREAD

**Issue by jnehlmeier** [bmuschko/gradle-docker-plugin#712]
`DockerBuildImage` supports multiple tags and provides a `tags` property to define them. The `tags` property supports `add/addAll/set` but it seems that calling `add/addAll` has no effect unless you have previously called `set` as well. See example below.

Using Gradle 5, Kotlin DSL, Plugin version 4.1.0

```kotlin
tasks.create<DockerBuildImage>("buildImage") {
    inputDir.set(file("docker/build-context"))

    // calling set here will also make add/addAll work
    // tags.set(setOf("set1/test:$version", "set2/test:$version"))

    // Does not work. No tags are created unless previous line is uncommented
    tags.add("add/test:$version")
    tags.addAll(
            "addall1/test:$version",
            "addall2/test:$version")
}
```

**Comment by bmuschko** [comment]
I believe we are missing the default value for the property which should be an empty list. Gradle 5.0 took away the default value so we have to initialize all `Property` fields. I'll get it fixed.

**Comment by bmuschko** [comment]
I made the relevant change: https://github.com/bmuschko/gradle-docker-plugin/commit/465c1951146dce85f42fa83e48dbb57897745a1f. Would it be possible for you to build a local version and see if it fixes your issue?

**Comment by cdancy** [comment]
> I believe we are missing the default value for the property which should be an empty list. Gradle 5.0 took away the default value so we have to initialize all Property fields.

Keep forgetting about this new feature as we are still on gradle 4.10 and have yet to make the jump. It's going to be loads of fun when we do :)
