### ISSUE TITLE
DockerBuildImage fails to pull public repo images if registryUsername registryPassword are present

### ISSUE THREAD

**Issue by roastario** [bmuschko/gradle-docker-plugin#714]
I have the exact same issue as: #275 which was closed for some reason. 

I have docker gradle file that has the following closure. 

    docker{
        registryCredentials  {
            username = System.env.DOCKER_USERNAME
            password = System.env.DOCKER_PASSWORD
        }
    }

    task buildOfficialCorrettoDockerImage(type: DockerBuildImage, dependsOn: [buildDockerFolder]) {
        inputDir = new File(project.buildDir, "docker-temp")
        tags = correttoBuildTags
        dockerFile = new File(new File(project.buildDir, "docker-temp"), "DockerfileAL")
    }

When running this the following error:

`Could not build image: Get https://registry-1.docker.io/v2/library/amazonlinux/manifests/2: unauthorized: incorrect username or password`

When I run without the credentials closure, it builds fine, but then obviously I cannot push to the registry because we do not have the credentials.

**Comment by cdancy** [comment]
@roastario so it sounds like your credentials are just bad? If that's so why are you supplying them at all?

**Comment by roastario** [comment]
@cdancy as with #275 I think you misunderstand what the issue comments. 

The credentials are definitely correct - I prove as follows

1.) attempt to build using above snippets - fail due to pulling *PUBLIC* image
2.) pull image locally using `docker pull amazonlinux:2`
3.) build using above snippet, no problems and pushes to our private repo correctly

This issue is with the following setup

1.) You need to pull a public image from hub.docker.com (amazonlinux:2 for example)
2.) You need to push an image to a private repo (my.private.repo/super-image:latest)

**Comment by cdancy** [comment]
@roastario OK I see where this hiccup is. Have you tried passing in a custom `registryCredentials`? The `DockerBuildImage` task we have implements `RegistryCredentialsAware` which allows you to define a custom registry. Have you given this a go yet?

https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy

**Comment by roastario** [comment]
Will try asap, not at computer for today!

**Comment by bmuschko** [comment]
@roastario Did you have a chance to try this out?

**Comment by bmuschko** [comment]
I am going to close this issue for now. Let us know if you still run into issues.

**Comment by a01fe** [comment]
I'm struggling with the same problem. What is the right way to create a custom `registryCredentials`?

This doesn't seem to work:

```
plugins {
    id 'com.bmuschko.docker-remote-api' version '4.8.0'
}

ext.imageName = "ds-dtr.eis.wwu.edu/eas/foo"
ext.imageVersion = "1.2"

import com.bmuschko.gradle.docker.tasks.image.*

task dockerCreateDockerfile(type: Dockerfile) {
    from "tomcat:8-alpine"
}

task dockerBuildImage(type: DockerBuildImage) {
    dependsOn dockerCreateDockerfile
    tags.add("${imageName}:${imageVersion}")
    docker {
        registryCredentials {
            url = publicDockerRegistryUrl
            username = publicDockerRegistryUsername
            password = publicDockerRegistryPassword
            email = publicDockerRegistryEmail
        }
    }
}

task dockerPushImage(type: DockerPushImage) {
    dependsOn dockerBuildImage
    imageName = project.imageName
    tag = project.imageVersion
    docker {
        registryCredentials {
            username = easDockerRegistryUsername
            password = easDockerRegistryPassword
            email = easDockerRegistryEmail
        }
    }
}
```

**Comment by a01fe** [comment]
I got it working with this. Not sure if this is the best way, though.

```
task dockerBuildImage(type: DockerBuildImage) {
    dependsOn dockerCreateDockerfile
    tags.add("${imageName}:${imageVersion}")
    def credentials = new DockerRegistryCredentials(project.objects)
    credentials.url.set publicDockerRegistryUrl
    credentials.username.set publicDockerRegistryUsername
    credentials.password.set publicDockerRegistryPassword
    credentials.email.set publicDockerRegistryEmail
    registryCredentials = credentials
}

task dockerPushImage(type: DockerPushImage) {
    dependsOn dockerBuildImage
    imageName = project.imageName
    tag = project.imageVersion
    def credentials = new DockerRegistryCredentials(project.objects)
    credentials.username.set easDockerRegistryUsername
    credentials.password.set easDockerRegistryPassword
    credentials.email.set easDockerRegistryEmail
    registryCredentials = credentials
}
```

**Comment by bmuschko** [comment]
@a01fe As a side note: The code in https://github.com/bmuschko/gradle-docker-plugin/issues/714#issuecomment-491387342 will only set the property values on the extension. The extension is a concept on the top-level of a build script and has no direct relation to a task except if the plugin maps the properties from the extension to task properties.

**Comment by cdancy** [comment]
```
task dockerBuildImage(type: DockerBuildImage) {
    dependsOn dockerCreateDockerfile
    tags.add("${imageName}:${imageVersion}")
    def credentials = new DockerRegistryCredentials(project.objects)
    credentials.url.set publicDockerRegistryUrl
    credentials.username.set publicDockerRegistryUsername
    credentials.password.set publicDockerRegistryPassword
    credentials.email.set publicDockerRegistryEmail
    registryCredentials = credentials
}
```
@bmuschko bumped into this locally and its kind of clunky to setup IMO. Maybe we could amend the "reg creds aware" task so that we can do something like:
```
task dockerBuildImage(type: DockerBuildImage) {
    dependsOn dockerCreateDockerfile
    tags.add("${imageName}:${imageVersion}")
    registryCredentials {
        url = publicDockerRegistryUrl
        username = publicDockerRegistryUsername
        password = publicDockerRegistryPassword
        email = publicDockerRegistryEmail
    }
}
```
Don't know if it could work _exactly_ like that just a minor grip with how we set this on the extension vs everywhere else.

**Comment by bmuschko** [comment]
@cdancy I assume you are just asking about the DSL-aspect of it? And the use case is only the one if you wanted to assign different credentials for two different custom tasks? If that's the case then it's easy to achieve. I'd suggest opening a new issue.

**Comment by bmuschko** [comment]
@cdancy I already made those improvements in https://github.com/bmuschko/gradle-docker-plugin/pull/879 as it will also make https://github.com/bmuschko/gradle-docker-plugin/pull/865 easier to implement.

**Comment by cdancy** [comment]
@bmuschko well I don't want to change the existing credentials just point at a different registry for this specific task which I believe your PR addresses.

**Comment by bmuschko** [comment]
@cdancy Yes, that will work now with the proposed DSL.

**Comment by asarkar** [comment]
For anyone coming across this issue because the `DockerBuildImage` tasks fails to pull from the Docker hub, here's the workaround. In the `DockerBuildImage` task, explicitly set the URL:
```
registryCredentials {
    url.set("docker.io/library")
}
```
