### ISSUE TITLE
docker links are broken with upgrade from 4.0.1 to 4.1.0 (and to gradle 5.0)

### ISSUE THREAD

**Issue by pradeepk** [bmuschko/gradle-docker-plugin#715]
The docker links are no longer setup correctly in the latest version (4.1.0)

### Expected Behavior

Given the following build definition: 

```gradle
task createDBContainer(type: DockerCreateContainer) {
    targetImageId 'postgres:latest'
    containerName = 'my-db'
}

task createMyAppContainer(type: DockerCreateContainer) {
    dependsOn createDBContainer
   containerName = 'my-app'
    targetImageId '...some-image-id'
    portBindings = ['8080:8080']
 
    // doFirst required! #319
    doFirst{
        // `database` there will be host used by application to DB connect
        links = [ "${createDBContainer.getContainerId().get()}:database" ]
    }
}
```
After running `gradle createMyAppContainer`, if you examine the link set up with `docker inspect -f "{{ .HostConfig.Links }}" my-app` you should see a valid link configuration such as `[/my-db:/my-app/database]`

### Current Behavior

`docker inspect -f "{{ .HostConfig.Links }}" my-app` shows an empty list

### Context

This used to work in 4.0.1. We were trying to upgrade gradle to 5.0 - which means we need to use 4.1.0 (the current latest) of the gradle-docker-plugin. And then the docker links are not established. So this is preventing us from upgrading to gradle 5.

### Steps to Reproduce (for bugs)

See gradle definition above

### Your Environment

```
docker --version
Docker version 18.09.0, build 4d60db4
```
```
./gradlew -version

------------------------------------------------------------
Gradle 5.0
------------------------------------------------------------

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.1 (Oracle Corporation 11.0.1+13-Ubuntu-2ubuntu1)
OS:           Linux 4.18.0-12-generic amd64
```

**Comment by bmuschko** [comment]
Thanks for identifying the version. It's likely some sort of breaking change in Gradle 5.0 that causes the issue. I am going to look at it soon.

**Comment by bmuschko** [comment]
The `doFirst` call for setting the links was likely a hack we had to do to ensure lazy evaluation. This is not needed anymore with the usage of the `Provider`. In fact [the functional test has been changed](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/DockerWorkflowFunctionalTest.groovy#L104) to reflect it. Can you please use the same notation as in the test? We'll have to fix the example in the user guide.

**Comment by pradeepk** [comment]
Yes that worked. Thanks.

**Comment by bmuschko** [comment]
Thanks. Example fixed in https://github.com/bmuschko/gradle-docker-plugin/commit/3f651e54a0a8b47c08470fcdaf8ba1bd322aaa0d.
