### ISSUE TITLE
DockerCommitImage fails to execute because "No signature of method"

### ISSUE THREAD

**Issue by rroques** [bmuschko/gradle-docker-plugin#716]
### Expected Behavior
A task with type `DockerCommitImage` should execute properly and create a new Docker image from a running container.

### Current Behavior
A task with type `DockerCommitImage` fails to execute with the following error:

> No signature of method: com.github.dockerjava.core.DockerClientImpl.commitCmd() is applicable for argument types: (org.gradle.api.internal.provider.DefaultPropertyState) values: [property(class java.lang.String, fixed(class java.lang.String, c2ce37fc543512d3da4e55837b721c86a162b7cfdd5eeab43074d5f19fa8b6a3))]
  Possible solutions: commitCmd(java.lang.String)

### Context
I am trying to create a new Docker image from a running container.

### Steps to Reproduce (for bugs)
Here is a sample `build.gradle` file:

```
import com.bmuschko.gradle.docker.tasks.image.DockerCommitImage
import com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer
import com.bmuschko.gradle.docker.tasks.container.DockerStartContainer

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:4.1.0'
    }
}

apply plugin: 'com.bmuschko.docker-remote-api'

task createContainer(type: DockerCreateContainer) {
    targetImageId "centos"
    autoRemove = true
}

task startContainer(type: DockerStartContainer) {
    dependsOn createContainer
    targetContainerId createContainer.getContainerId()
}

task commitImage(type: DockerCommitImage) {
    dependsOn startContainer
    targetContainerId createContainer.getContainerId()
    tag = 'myimage:latest'
}
```

Running `gradle commitImage` fails with the error message above.

Looking at the code base for `com.bmuschko.gradle.docker.tasks.image.DockerCommitImage`, line 71, `dockerClient.commitCmd(getContainerId())` is feeding a `Property` (`getContainerId()`) type instead of a `String` (`getContainerId().get()`)

### Your Environment

```
gradle -version

------------------------------------------------------------
Gradle 5.0
------------------------------------------------------------

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Mac OS X 10.14.2 x86_64
```

**Comment by cdancy** [comment]
@rroques yeah we've recently done many big changes around the plugin and you look to have caught a bug. As to why this is not popping during testing I have no idea and will have to look into that. In either event let me spin up a fix now and get a new patch release out. Thanks for reporting the issue!

**Comment by bmuschko** [comment]
> As to why this is not popping during testing I have no idea and will have to look into that.
I think we didn't have a functional test for the commit operation. That test was added with this PR.

**Comment by rroques** [comment]
No worries, and thanks for the feedback on the PR. I will go through the PR comments and update the code & tests.
