### ISSUE TITLE
What is the correct way to tag an image, given the existing image name (not the id)

### ISSUE THREAD

**Issue by hirowla** [bmuschko/gradle-docker-plugin#719]
I'm trying to add a tag to an existing image (it isn't an image I just created). I know the name (and tag) of the existing image, and want to add an additional tag to the image (and then push it out, but that's another story).

When creating a "tagImage" task, I am getting an error saying "invalid Tag format".

My gradle snippet is as follows:

```
   task tagImage(type: DockerTagImage) {
       
        imageId = dockerImageTagSource
        tag = dockerImageTagDestination
        repository = "registryName.com"
    }

```
The "dockerImageTagSource" contents is (as an example): "registryName.com/project/imageName:testTag" 

The dockerImageTagDestination is similar (but a different tag)

What is the recommended way to do this?

**Comment by cdancy** [comment]
@hirowla have a look at [THIS](https://github.com/bmuschko/gradle-docker-plugin/blob/cbbd8c39f75757db0ad2ae1a48b9e4b03ad5a084/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerRemoveImageFunctionalTest.groovy#L75) functional test and see if that makes things more clear.

**Comment by hirowla** [comment]
I've had a look, but the issue I have is that I can't call (say) "buildImage.getImage()" because I didn't build the image - the image exists in the (remote) repository. I'm not sure how to get the imageId from the remote image.

**Comment by bmuschko** [comment]
Please have a look at the [API of the task](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerTagImage.html). The parent class also provides a [method for setting the target ID by String](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerExistingImage.html#targetImageId(java.lang.String)).

**Comment by bmuschko** [comment]
@hirowla Did that clarify your question? Please close the issue if you got passed your issue.

**Comment by hirowla** [comment]
Maybe there was a change between 3.6.10 and 4.1.0 (I must have been trying it with 3.6.2 - as you know, I have another issue with migrating to 4.1.0). Got it working now. Thanks.
