### ISSUE TITLE
The functional test `DockerLivenessFunctionalTest` should execute faster

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#722]
The functional test `DockerLivenessFunctionalTest` currently takes 2 minutes on average on my machine to execute 3 test methods. The code starts PostgreSQL in a container and waits until it is up and running.

1. The test should use shorter intervals for checking if the service is healthy. Right now it only checks every 30 seconds.
2. A different service should be used that can be started up quicker.

Changing the test will significantly speed up test execution in local development and CI.

**Comment by cdancy** [comment]
Yeah 30 seconds can be a bit of a wait :) We can plug in anything really. Let me poke around to see if there is something smaller. Maybe like an existing image or `alpine` to mimic the same behavior.
