### ISSUE TITLE
Dockerfile task does not produce Dockerfile if depended on it

### ISSUE THREAD

**Issue by mxab** [bmuschko/gradle-docker-plugin#723]
### Expected Behavior
My DockerBuildImage task depends on the Dockerfile task. I expect that the Dockerfile is created and used by the DockerBuildImage task

### Current Behavior
The DockerBuildImage task fails and claims that there is no Dockerfile (which is correct). The Dockerfile Task did not produce a Dockerfile even though the task run.
If I execute the DockerFile task solely it works. But it does not work if I execute the DockerBuildImageTask even if I run both explicitly in one run

### Context
I was trying to build a custom docker image with a dockerfile

### Steps to Reproduce (for bugs)
https://github.com/mxab/docker-gradle-problem

### Your Environment
MacOS Mojave 10.14
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

**Comment by mxab** [comment]
*facepalm* ... thanks for clarifying, obviously this was the problem.

I'm actually having a spring boot application but the spring boot docker plugin did too much. Will revalidate application plugin.

Thank you!

**Comment by bmuschko** [comment]
@mxab Can you clarify what you'd consider "too much"?

**Comment by mxab** [comment]
For my current use case I unfortunately need a custom entrypoint and need to have jar class named differently.
I think for other cases I would be perfectly happy with the spring boot docker plugin

**Comment by bmuschko** [comment]
Thanks for the feedback. You can tweak the existing `Dockerfile` task of that plugin to make that happen if you wanted to go down that route.

**Comment by mxab** [comment]
This was my first idea as well, but you'll end up with multiple entrypoint and cmd instructions in one file which will look a bit odd in my opinion
