### ISSUE TITLE
Plugin should declare and use Docker Java on compilation classpath

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#728]
### Expected Behavior

No need for a thread context classloader. Docker Java classes can be imported into plugin classes. IDE support through auto-completion. No more reflection hacks.

### Current Behavior

1. Initially, the Docker Java library used by the plugin was not shaded. To mitigate the situation, the plugin used its own thread context classloader and loads Docker Java classes at runtime.
2. Later, dependencies used by Docker Java were packaged in the same JAR and move to a different package.

Given that 2. has been done, 1. is not needed anymore. @cdancy Is this a correct assessment?

### Context

Gradle does not isolate the classpath across all applied plugins in a build. As a result, dependencies required by applied plugins can conflict and result in unexpected behavior e.g. two plugins require Guava but they depend on different versions.

The shaded Docker Java library moves all external library imports into a different package to avoid conflicts with dependencies in build scripts on the build script classpath.

**Comment by cdancy** [comment]
Yes this is all true. And if and when we move to using the spotify client it also has a shaded version which should shield us from any type surrounding this area.

**Comment by cdancy** [comment]
So the idea here would be to remove the runtime resolution of the library like we are doing now and instead do things the more "normal" way as a proper dependency? It would make debugging things easier. The only potential gotcha I see is that in massive projects like ours (almost 200 subprojects at this point) we have points in our build pipeline that invoke the greater build but don't require docker. Furthermore those points are executed on separate nodes. If we put this into place then in theory every time our project is run, no  matter how big or small the context, the docker-java-shaded jar will be resolved which I believe is a good 15MB or so.

**Comment by bmuschko** [comment]
That's correct. I'd like to use actual Docker Java classes than reflection. It also makes it easier for users to deal with callback for example.

> If we put this into place then in theory every time our project is run, no matter how big or small the context, the docker-java-shaded jar will be resolved which I believe is a good 15MB or so.

That depends on your setup. Do you use ephemeral nodes? Usually, you'd be able to just download it once and reuse it from Gradle's dependency cache. Either way, don't you have the same problem with other dependencies in your project?

**Comment by cdancy** [comment]
Yeah ephemeral nodes. Same problem elsewhere but other deps tend to be smaller. This will most likely not be such a big deal for us as we have an Artifactory instance sitting side-by-side with our CI infrastrcuture so all downloads are more/less local.

**Comment by cdancy** [comment]
I would say we can move forward just wanted to note it.

**Comment by bmuschko** [comment]
@cdancy I just merged the pull request. BTW: This will also give us the chance to shade the Docker Java library right here in this project without you have to do it in a separate project. It will become far less burden on your end.

**Comment by bmuschko** [comment]
Shading has been done as well.
