### ISSUE TITLE
Not honoring docker.io.url variable when set inside .docker.io.properites

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#73]
Looking at the docker-java project here:

https://github.com/docker-java/docker-java

It looks like if I set 'docker.io.url=http://10.11.22.33:2375' inside /home/user/.docker.io.properties that should be getting picked up and used but it appears not to be when using this plugin as the plugin keeps going back to 'http://localhost:2375' by default. Now I know you can set the value through the extension just wondering if there is a way you can honor it if it's NOT set through the extension but IS set inside .docker.io.properties.

The use-case here is building INSIDE docker containers, which I have control over and can create the .docker.io.properties file, but I don't have control over the gradle build scripts or their projects and editing them at runtime, while feasible, seems a bit hackish.

**Comment by bmuschko** [comment]
Without having a look at the Docker Java code there's no way to know (documentation doesn't speak about it) what the precedence of resolution is for the property file, environment variables or the programmatic approach. IMHO a library shouldn't specific "magic" properties and files to resolve configuration values. That should be up to the consumer of the library.

What's happening in my plugin is that the extension provides a default value `http://localhost:2375`. This is set no matter what. You'd only be able to resolve a different value if you set it for a task or the extension. What value you assign is up to your logic. If you wanted to read `.docker.io.properties` then you can do that. My plan is not to build that into my plugin. You can easily write an abstraction on top of my plugin that does these kinds of things.

**Comment by cdancy** [comment]
Yea I understand and was thinking you were going to say as much. We are actually writing an abstraction on top of your library as you note just trying to get out of writing yet another abstraction and/or means of reading properties to pass further downstream. But I understand your reasoning and thanks for chiming in. Feel free to close this.
