### ISSUE TITLE
OWASP Dependency Checker report vulnerabilities in Docker-java-shaded library used by gradle-docker-plugin

### ISSUE THREAD

**Issue by picaron** [bmuschko/gradle-docker-plugin#730]
### Expected Behavior

No vulnerabilities reported by [OWASP dependency checker](https://jeremylong.github.io/DependencyCheck/) when using Gradle-docker-plugin in my project

### Current Behavior

When running the dependency check, multiple vulnerabilities are reported related to the Docker-java-shaded library

Here is an example report [dependency-check-vulnerability.html.zip](https://github.com/bmuschko/gradle-docker-plugin/files/2769214/dependency-check-vulnerability.html.zip)

### Steps to Reproduce (for bugs)

1. Configure the plugin in your project: 

```
buildscript {
        ...
	dependencies {
		classpath("com.bmuschko:gradle-docker-plugin:4.3.0")
		classpath("org.owasp:dependency-check-gradle:4.0.2")
	}
}

apply plugin: "com.bmuschko.docker-remote-api"
apply plugin: "org.owasp.dependencycheck"
```

### Your Environment

- Gradle wrapper 5.1.1
- `org.owasp:dependency-check-gradle:4.0.2`
- `com.bmuschko:gradle-docker-plugin:4.3.0`

**Comment by bmuschko** [comment]
Thanks for providing the OWASP report. All dependencies of this plugin are provided by the Docker Java library which is an essential piece of functionality we can't get rid of easily. We are thinking about replacing Docker Java with the Spotify library (https://github.com/bmuschko/gradle-docker-plugin/issues/688) but that'll be a lot of work.

IMHO we can't actively do something about fixing security issues. Would you mind running the report against [Docker Java](https://github.com/docker-java/docker-java) and ask for the fixes there? We can upgrade to a new version of Docker Java if they do fix the issues.

**Comment by bmuschko** [comment]
Hhhm, that's weird. @cdancy Are you adding more dependencies in the shaded project? Maybe they remove dependencies in the meantime. Any ideas?

**Comment by picaron** [comment]
I opened a ticket on Docker Java for the Guava vulnerability: https://github.com/docker-java/docker-java/issues/1150

**Comment by cdancy** [comment]
@bmuschko actually we do add at least 1+ dependencies. We add an additional dependency on `cglib` which in turn probably brings in more deps. Cglib tends to be very finicky though...

https://github.com/project-aries/docker-java-shaded/blob/master/gradle/artifacts.gradle#L28

**Comment by bmuschko** [comment]
@picaron Seems like the Docker Java project somewhat ignored the issue by closing your issue. As long as we don't switch to a different library, there's no much we can do. I am closing this issue for now. We will upgrade to the latest version of Docker Java from time to time. So if they decide to fix their CVE issue we'll pick it up automatically.

**Comment by picaron** [comment]
yeah it seems the project didnt owners understand the point of my request

I'll have to settle with using a "suppression file" to ignore the reported issues

I totally understand there isnt much you can do, thanks for following up @bmuschko
