### ISSUE TITLE
[Feature Request] Support ENTRYPOINT & CMD customization for SpringBootApplication

### ISSUE THREAD

**Issue by unlimitedsola** [bmuschko/gradle-docker-plugin#732]
support `ENTRYPOINT` & `CMD` customization like what we did for `javaAppliation` would make solving #711 easier, also spring-boot's `bootJar` has `launchScript()` support providing powerful launching customization that we can't do at runtime after JVM started

or simply react with `bootJar.launchScript`, when it has been enabled, instead of using `java -jar xxx.jar` entrypoint, just execute the fully executable jar file.

**Comment by bmuschko** [comment]
You can change instructions of the `Dockerfile` task as you see fit. Did you see the section ["Modifying Instructions of a Dockerfile Task"](https://bmuschko.github.io/gradle-docker-plugin/#modifying_instructions_of_a_dockerfile_task) in the user guide?

**Comment by unlimitedsola** [comment]
@bmuschko  yes, I did. as I mentioned #711 above, having this supported could make things easier.

**Comment by bmuschko** [comment]
With the introduction of the `jvmArgs` property in the extension, do you think this request is still relevant? If yes, can you please describe the exact ENTRYPOINT and CMD you'd like to describe?

**Comment by unlimitedsola** [comment]
I think it's enough for our use case now. Thanks for your effort.
