### ISSUE TITLE
DockerPullImage kept using default docker registry instead one specified by url

### ISSUE THREAD

**Issue by rhibiscusc** [bmuschko/gradle-docker-plugin#738]
gradle-docker-plugin version used: com.bmuschko:gradle-docker-plugin:3.6.1

applied gradle-docker-plugin and configured the docker extension and the DockerPullImage task, but task always tried to access default registry instead of the one specified in url

docker {
   url = "xxx"

  registryCredentials {
     url = "https://xxxxx"
     username = "xxx"
     password = "xxx"
     email = "xxx"
 }

task pullImage(type: com.bmuschko.gradle.docker.tasks.image.DockerPullImage) {
    repository = "xxx"
    tag = "xxx"
    url = "xxx"

    def credentials = new com.bmuschko.gradle.docker.DockerRegistryCredentials()
    credentials.setUrl("xxx")
    credentials.setUsername("xxx")
    credentials.setPassword("xxx")
    credentials.setEmail("xxx")
 
    registryCredentials = credentials
 }

running the task pullImage always get:

Execution failed for task ':pullImage'. com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://registry-1.docker.io/v2/xxxx/manifests/xxxx: unauthorized: incorrect username or password"}

### Expected Behavior

registry url specified in docker extension or in the PullImageTask should be used instead of the default registry.

### Current Behavior

DockerPullImage task failed.

### Context

try to understand how to debug this issue

**Comment by bmuschko** [comment]
Would you mind putting together an example project on GitHub for this so we can reproduce the issue?

**Comment by rhibiscusc** [comment]
user error. please close this issue
