### ISSUE TITLE
When branch ISSUE-716 will be pushed into master?

### ISSUE THREAD

**Issue by FirninFactoryPostProcessor** [bmuschko/gradle-docker-plugin#739]
Hi, may I ask when ISSUE-716 will be pushed into master(and will be available from jcenter)? I tested it locally on my local maven repo and everything is ok while master doesn't work for me.

**Comment by bmuschko** [comment]
As indicated by the milestone in the [issue](https://github.com/bmuschko/gradle-docker-plugin/issues/716), this has been release with version 4.2.0 of the plugin. Please provide a self-contained sample repository that reproduces the issue.

**Comment by FirninFactoryPostProcessor** [comment]
Sorry, I had no access to my github account and couldn't reply. I see that these changes https://github.com/bmuschko/gradle-docker-plugin/compare/ISSUE-716 are not in master now. I have a problem with 4.4.0 version of the plugin - "> Could not set unknown property 'tag' for task 'mytask' of type com.bmuschko.gradle.docker.tasks.image.DockerBuildImage." but everything is working fine with a jar of branch  ISSUE-716 from my local maven repo.

**Comment by bmuschko** [comment]
See comment https://github.com/bmuschko/gradle-docker-plugin/pull/720#issuecomment-447347461. The pull request https://github.com/bmuschko/gradle-docker-plugin/pull/720 has been been merged into master.

Can you please provide a sample project (as a GitHub repository) that reproduces the issue?

**Comment by FirninFactoryPostProcessor** [comment]
Here's a simple spring boot project https://github.com/FirninFactoryPostProcessor/docker-plugin-test 
I can't even build it because of "Could not set unknown property 'tag' for task ':buildImage' of type com.bmuschko.gradle.docker.tasks.image.DockerBuildImage."

Commented dependency in a build.gradle file is a dependency of branch ISSUE-716 from my local maven repo.

**Comment by bmuschko** [comment]
The property `tag` has been deprecated for a while and we removed it with version v4.2.0 (see [release notes](https://bmuschko.github.io/gradle-docker-plugin/#change_log)). You'll have to use the `tags` property. You can find an [example in the user guide](https://bmuschko.github.io/gradle-docker-plugin/#creating_a_dockerfile_and_building_an_image).

**Comment by FirninFactoryPostProcessor** [comment]
Thanks, now it works for me. I didn't notice that property tag is deprecated

**Comment by bmuschko** [comment]
No worries, closing the issue.

**Comment by AceHack** [comment]
Is 'tags' deprecated in the latest?  Does not seem to work.

**Comment by bmuschko** [comment]
@AceHack The property has been renamed to `images` to better reflect its purpose. See the [release notes](https://bmuschko.github.io/gradle-docker-plugin/#change_log) for v6.0.0.
