### ISSUE TITLE
error publishing image

### ISSUE THREAD

**Issue by camechis** [bmuschko/gradle-docker-plugin#74]
I am getting the following error while attempting to push an image to a docker hub account.

Status 403 trying to push repository company/spark-jobserver to official registry: needs to be forced

Any ideas on this?

**Comment by bmuschko** [comment]
Pushing to DockerHub works fine for me (see [test case](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/integTest/groovy/com/bmuschko/gradle/docker/DockerWorkflowIntegrationTest.groovy#L175)).

- Does the repository exist?
- Did you provide the credentials and are they correct?

> Status 403 trying to push repository company/spark-jobserver to official registry: needs to be forced

Is this the error message?

**Comment by camechis** [comment]
I can push the repository by hand via docker push.  When I do that it is asking me if I want to push it to the public docker hub. Is it possible this is what is hanging it up?  Side note it worked via boot2docker on my mac.  The env that I am working on is a centos7  machine.

**Comment by bmuschko** [comment]
Sorry, no idea. You might want to raise the question with the Docker Java project. It's doing all of the communication. I am just passing through the configuration really.

**Comment by bmuschko** [comment]
Did you manage to solve your issue in the meantime?

**Comment by camechis** [comment]
I have not,  I ended up falling back to execing a shell command to perform
the push for me.

**Comment by bmuschko** [comment]
Sorry, I don't know how to help here. I am going to close the issue.
