### ISSUE TITLE
Cannot copy arbitrary file into Docker image from src/main/resources

### ISSUE THREAD

**Issue by jmckitt** [bmuschko/gradle-docker-plugin#740]
copyFile method from Groovy DSL takes a fully qualified path and prepends it with /var/lib/docker/tmp/docker-builder857692325  (where the number changes).    This causes the gradle job to fail as the files don't exist in the temp directory.

A real error message is:   > Could not build image: COPY failed: stat /var/lib/docker/tmp/docker-builder857692325/build/resources/main/environments: no such file or directory

### Expected Behavior

Would expect the groovy DSL would copy the file to an opaque temp dir before issuing a COPY in the underlying Docker file or there would be something documented to demonstrate how to copy to this dynamically generated directory.  I can't even find how to get a handle to it.   If I could, I could easily write Groovy code myself to copy the stuff in there.

**Comment by bmuschko** [comment]
The path of the files to copy into the image are based on the build context directory used by the `Dockerfile`. By default that is `$buildDir/docker`. Whatever you want to copy into the image will need to be copied to the build context directory first. IMHO that's the same behavior as if you would run this from the Docker CLI.

You can get a reference to the build context directory with the method [`Dockerfile.getDestDir()`](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html#getDestDir()).

BTW: The API exposed by the `Dockerfile` task is not specific to the Groovy DSL. You can use it from the Kotlin DSL as well.

**Comment by jmckitt** [comment]
I Ben,

Yes thank you for your help.   I had a colleague that was more familiar with the plugin and he advised me of a Sync task ,  e.g.  task foo(type: Sync) { } .       We had a $buildDir defined and I was able to use that, but I think your advice on Dockerfile.getDestDir() is also helpful.   Once I got the $buildDir/docker in my understanding then I was unblocked.   It was hard initially to figure out where stuff had to be to end up in the Docker image.   Especially because coming from a Maven background,  Gradle obviously has 20 ways to do everything.

Thanks,

Joseph

**Comment by bmuschko** [comment]
> It was hard initially to figure out where stuff had to be to end up in the Docker image.

It's always based on the `WORKDIR` (if defined in your `Dockerfile`) or the default build context directory (which by default is the one the parent directory of your `Dockerfile`. Can you explain how this is different from plain Docker? How could we improve documentation to make it more clear from your perspective?

BTW: If you find the `Dockerfile` task hard to use then you can of course also write the file yourself in a task. You don't have to rely on the custom task.

> Especially because coming from a Maven background, Gradle obviously has 20 ways to do everything.

That might be the case for some of the DSL constructs in Gradle (e.g. creating a task wit the `task` method or through the `TaskContainer`). 20 different ways is a little exacterated. ;-) It's not necessarily the case for this plugin. It's all based on the exposed API. I'd recommend having a look a the Javadocs. Can you give an example if you got the impression that something can achieved in multiple way for this plugin?

**Comment by jmckitt** [comment]
You are right, it doesn't differ from standalone Docker other than in Gradle you don't structure stuff you want in the Docker image all in one directory next to a Dockerfile (in source control).   Or in my case I inherited a project where the Dockerfile didn't even exist and was getting generated by the plugin.     Ultimately the DSL you made is pretty clear, but when it ultimately generates an ADD or COPY in a Dockerfile, it wasn't clear where those files had to be put by me so those commands would work when Docker builds the image.

Your line:   "By default that is `**$buildDir/docker**`" .  crystallized the issue entirely for me.   I knew there was a variable and path I could use to do what I needed.    I might suggest making this more prominent if you have seen my question before.  

The Spotify docker plugin for Maven makes it pretty clear in their approach.  It's stated pretty prominently and early in their doc:  https://github.com/spotify/docker-maven-plugin

"To use a Dockerfile, you must specify the dockerDirectory element. If specified, the baseImage, maintainer, cmd and entryPoint elements will be ignored. The contents of the dockerDirectory will be copied into **${project.build.directory}/docker**. Use the resources element to copy additional files, such as the service's jar file."

**Comment by bmuschko** [comment]
Thanks for clarifying. This makes more sense now. Happy to accept pull requests in case you are interested in contributing to the documentation to help others!

**Comment by JuanMorenoS** [comment]
Hello, everybody.

I want to share how I solved this problem.

I have the same problem that @jmckitt, I used kotlin with gradle

`
import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

plugins {
    id("com.bmuschko.docker-remote-api") version "6.4.0"
}

tasks.create("createDockerfile", Dockerfile::class) {

    destFile.set(file("$projectDir/Dockerfile"))

    val user = "microConfig"

    from("some-image")

    environmentVariable("APP_JAR", "${rootProject.name}-${version}.jar")

    user("root")
    runCommand("useradd -l -u 5000 $user")

    copyFile("docker/opt", "/tmp")
    copyFile("build/libs/\${APP_JAR}", "/tmp")

    runCommand("mv /tmp/docker /opt/")
    runCommand("chown -R $user:$user /opt/docker/")

    workingDir("/opt/docker")
    runCommand("chmod +x bin/run_container")
    user(user)
}

tasks.create("buildDockerImage", DockerBuildImage::class) {
    dependsOn("createDockerfile")
    inputDir.set(file("$projectDir"))
    images.add("{rootProject.name}:latest")
}
`
