### ISSUE TITLE
Cannot set publishAll property without error

### ISSUE THREAD

**Issue by thyming** [bmuschko/gradle-docker-plugin#741]
Hi, thanks for making/maintaining this plugin! 
I'm running into an issue where I want to use publishAll to avoid static host ports, but when I configure my task like so
```kotlin
val createContainer by registering(DockerCreateContainer::class) {
...
    publishAll.set(true)
...
}
```
I receive this error when running the task:
> No signature of method: com.github.dockerjava.core.command.CreateContainerCmdImpl.withPublishAllPorts() is applicable for argument types: (Boolean) values: [true]

I've tried debugging this but the thread context classloader situation makes things a bit opaque.

**Comment by thyming** [comment]
For what it's worth, I get a similar error if I try to publish individual ports like
```portBindings.add(":5432")```

**Comment by bmuschko** [comment]
Looks like Docker Java removed the method and we recently upgraded the version. I am not quite sure why it was removed. I also don't see a [replacement method](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/command/CreateContainerCmdImpl.java). To be investigated. Happy for you to look into it if you'd like.

**Comment by thyming** [comment]
Looks like they moved it to HostConfig. So the fix should be setting it on that instead of directly on the CreateContainerCommand. Given that you're not using a provided docker-java there are no compatibility concerns, are there?

**Comment by bmuschko** [comment]
> Given that you're not using a provided docker-java there are no compatibility concerns, are there?

I don't quite understand the question. We are using Docker Java but we are shading the external dependencies and repackage the classes.

Would you be interested in working on PR for this?

**Comment by thyming** [comment]
Happy to.
All I wanted to confirm was that since this plugin's dependency on docker-java is opaque to the plugin user, there would be no potential compatibility issues arising from changing the way publishAll is set (which could happen if a user was using an older version of docker-java that did not allow setting publishAll from hostConfig). I don't think it's an issue.

**Comment by bmuschko** [comment]
> All I wanted to confirm was that since this plugin's dependency on docker-java is opaque to the plugin user, there would be no potential compatibility issues arising from changing the way publishAll is set (which could happen if a user was using an older version of docker-java that did not allow setting publishAll from hostConfig).

This can only happen if you actively reassign the version of Docker Java to the `docker-java` configuration. I don't think anyone is really doing that as the plugin code would likely be incompatible as Docker Java changes its API so much.

We'll just guarantee compatibility with the version of Docker Java that we assign internally.
