### ISSUE TITLE
 dockerPushImage: Docker credential helpers don't apply 

### ISSUE THREAD

**Issue by dlazerka** [bmuschko/gradle-docker-plugin#743]
First of all, thank you for the awesome plugin! Couldn't find your patreon page though...

### Expected Behavior
`./gradlew dockerPushImage` should work on a properly tagged image (`docker push <mytag>` works fine).

### Current Behavior
`./gradlew dockerPushImage` fails with error
```
> Could not push image: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```
However, if I do `docker push gcr.io/my-project/my-image` then it works fine. Because I already followed the steps by that link above and did  `gcloud auth configure-docker`. Looks like it wrote auth tokens to gcr.io to `~/.docker/config.json`. So it seems like gradle-docker-plugin just doesn't use it.

### Context
I have the following in my gradle.build.kts:
```kotlin
tasks {
    docker {
        // https://bmuschko.github.io/gradle-docker-plugin/#java-application-plugin
        javaApplication {
            baseImage.set("openjdk:11-jre-slim")
            maintainer.set("")
            ports.set(listOf())
            tag.set("gcr.io/my-project/my-image")
        }
    }
}
```

And the following in `~/.docker/config.json`:
```json
        "credHelpers": {
                "asia.gcr.io": "gcloud",
                "eu.gcr.io": "gcloud",
                "gcr.io": "gcloud",
                "marketplace.gcr.io": "gcloud",
                "staging-k8s.gcr.io": "gcloud",
                "us.gcr.io": "gcloud"
        }
```

### Your Environment
id("com.bmuschko.docker-java-application") version "4.4.0"
Docker version 18.09.1, build 4c52b90
Google Cloud SDK 231.0.0

**Comment by bmuschko** [comment]
Thanks for asking for it. I guess should be possible to configure Docker Java to leverage this information. Would you be interested in looking into it?

**Comment by dlazerka** [comment]
Thanks. Will try, let me see how easy is that.

**Comment by bmuschko** [comment]
I am currently working on https://github.com/bmuschko/gradle-docker-plugin/issues/728 so that should make it easier to navigate the Docker Java API. But definitely feel free to get started.

**Comment by cdancy** [comment]
@dlazerka @bmuschko I'm actually surprised this does not auto-magically work. I would also open an issue with the `docker-java` guys as I would expect whatever is in your `config.json` to take effect by default if found as it's "part of the environment" and we're not necessarily configuring additional creds which would make sense to do programmatically.

**Comment by bmuschko** [comment]
@cdancy You might have to set some option here: https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy#L136-L159 or we are overwriting the behavior somewhere. Didn't have the chance to look at it yet.

**Comment by cdancy** [comment]
@bmuschko yeah there is an option to specify the config file but if you don't it essentially init's an empty POJO. We _could_ pass this in by default if we note the default location is present just not sure if there are any drawbacks or breaking behavior for existing customers if we did so. We could always provide the option to set it of course but I _like_ the idea of auto-magically loading it if it's present.

FWIW: @dlazerka any others coming upon this issue: you can set the `DOCKER_CONFIG` env-var and it will get picked up and do what you expect should the need arise until we decide how to move forward.

Tagging @orzeh for any thoughts/opinions.

**Comment by cdancy** [comment]
@orzeh @bmuschko any thoughts on the above? We could default to checking in the default location for the given config file and load it and pass that along whilst optionally allowing the user to pass in one programmatically. I don't think adding one, if present, would change anything for existing users as it just amounts to more definitions to use so to speak.

**Comment by orzeh** [comment]
@cdancy IMO sounds good. Ideally it should be done in `docker-java`, but ... you know :smiley:

**Comment by cdancy** [comment]
@orzeh I know ;) Ok let me throw together a PR this weekend and I'll tag you guys. Hopefully nothing pops. Devs here have asked similar things as well so to just have this magically work I think would be a win.

**Comment by bmuschko** [comment]
@cdancy I am planning to have a look at it tomorrow.

**Comment by bmuschko** [comment]
For inspiration: The TestContainers project tries to discover existing authentication. See https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/utility/RegistryAuthLocator.java.

**Comment by cdancy** [comment]
It even builds on docker-java! Maybe we can just rip what we need out and call it a day :)

**Comment by patricklucas** [comment]
Curious if any progress has been made here.

**Comment by cdancy** [comment]
@patricklucas never got around to it due to other priorities and not enough folks asking for it. Interested in sending in a PR?

**Comment by kgrech** [comment]
It looks like docker-java does not support this as well, I see they have the issue [#1048](https://github.com/docker-java/docker-java/issues/1048) is the open state

**Comment by kgrech** [comment]
@cdancy if you would like so, I can contribute RegistryAuthLocator from the above PR to docker-plugin. The issue above seems to be open for since Nove on the docker-java side...

**Comment by kgrech** [comment]
@bmuschko @cdancy So far I came with [this](https://github.com/kgrech/gradle-docker-plugin/commit/c7068cfb224eea58c2a360d11312d720bc40c728).
It almost works, the problem is that ``if(registryCredentials)`` statement in ``PushImageCmd`` always evaluates to true, so it never goes to ``else`` branch. Any idea on what am I missing?

Any feedback about my groovy is also welcome, as I am Java guy

**Comment by cdancy** [comment]
@kgrech yeah send in a PR. That is odd. I would put in some debug output to see what exactly the registry credentials object looks like.

**Comment by kgrech** [comment]
I've found where is it created (DockerRemoteApiPlugin class): 
```
    @Override
    void apply(Project project) {
        DockerExtension dockerExtension = project.extensions.create(EXTENSION_NAME, DockerExtension, project.objects)
        DockerRegistryCredentials dockerRegistryCredentials = ((ExtensionAware) dockerExtension).extensions.create('registryCredentials', DockerRegistryCredentials, project.objects)
        configureRegistryAwareTasks(project, dockerRegistryCredentials)
    }
```

I think ``create`` method always creates the object by passing the ``ObjectFactory``, but it might have or don't have credentials set. 

I have solved it by adding the method to check credentials validness. You can see [here](https://github.com/kgrech/gradle-docker-plugin/commit/56a938c5d03eb1401b885261977ad01320d2befe).
It works for me.

If it looks ok, I will add the set of unit tests and sent a PR

**Comment by kgrech** [comment]
@cdancy @bmuschko  create a [PR#865](https://github.com/bmuschko/gradle-docker-plugin/pull/865)
