### ISSUE TITLE
Refactor spring boot dependency into a different artifact

### ISSUE THREAD

**Issue by JamesXNelson** [bmuschko/gradle-docker-plugin#744]
The introduction of `implementation` dependency on spring boot caused our company's internal license checks to fail because it was not explicitly allowed.

We've simply excluded the dependency manually, but it might be nice if it was deployed as a different artifact that spring boot users would need to choose to get the plugin / dependencies they need.

**Comment by bmuschko** [comment]
The dependency `org.springframework.boot:spring-boot-loader-tools` is already a transitive dependency of the Spring Boot plugin so you'd pull that in anyway (expect if you are not building a Spring Boot application - is that the case?):

```
./gradlew buildEnvironment

> Task :buildEnvironment

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
+--- org.springframework.boot:org.springframework.boot.gradle.plugin:2.1.2.RELEASE
|    \--- org.springframework.boot:spring-boot-gradle-plugin:2.1.2.RELEASE
|         +--- org.springframework.boot:spring-boot-loader-tools:2.1.2.RELEASE
|         |    +--- org.springframework:spring-core:5.1.4.RELEASE
|         |    |    \--- org.springframework:spring-jcl:5.1.4.RELEASE
|         |    \--- org.apache.commons:commons-compress:1.18
|         +--- io.spring.gradle:dependency-management-plugin:1.0.6.RELEASE
|         \--- org.apache.commons:commons-compress:1.18
\--- io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.0.6.RELEASE
     \--- io.spring.gradle:dependency-management-plugin:1.0.6.RELEASE
```

The only option I see is to pull the code into the plugin that finds the main class in a classpath. Happy to accept pull requests. Would you be interested?

**Comment by bmuschko** [comment]
Do you have any thoughts on my response?

**Comment by JamesXNelson** [comment]
Ah, sorry.  We are building an application that doesn't use spring at all.  When we upgraded to the latest version of gradle-docker-plugin, we inherited the spring boot dependency that we did not need or want.  

We have license checks that fail if anything new is added without an entry confirming the license is usable (OSS or purchased); obviously spring boot wasn't a problem, but we chose to exclude it any as we don't need it.

The ticket is to refactor this runtime dependency so that people who want to use spring would inherit a different artifact that has the transitive dependency and related class(es).  It's ok if it's too much trouble, but I decided to open a ticket in case others have protections against unexpected transitive dependency inclusion.

**Comment by JamesXNelson** [comment]
I'd be willing to contribute this on a weekend / evening, but I can't get company time to do it.

If you express exactly how you'd like it handled, I will make it so.

**Comment by bmuschko** [comment]
Thanks for the explanation. Makes sense. We can probably just pull in the method [`org.springframework.boot.loader.tools.MainClassFinder.findSingleMainClass(File, String)`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/MainClassFinder.java#L107) and whatever it calls off to.

**Comment by JamesXNelson** [comment]
ok, cool.  I actually have main-class-finder code of my own that I've used with decent success, so it shouldn't be too hard to deal with.  Looks like they're using a repackaged asm to read the class files.  Gradle seems to have a few different versions of repackaged asm as well; wonder if it is better to use one that is similar, or to have yet-another repackaged version that matches what spring expects (it appears to be a very simple read-only usage).

Not sure if it would be better to pull in the code, or just make it a compileOnly dependency with an extra publication that adds an explicit runtime dependency; might take me a little while to get to it as I have an international move looming in the next few weeks, but I'll leave a note on my backlog.

**Comment by bmuschko** [comment]
> ok, cool. I actually have main-class-finder code of my own that I've used with decent success, so it shouldn't be too hard to deal with.

I think it would probably be easier to just extract the code in Spring Boot and put it in here. It's battle-proven and has been used by millions of users.

> Gradle seems to have a few different versions of repackaged asm as well; wonder if it is better to use one that is similar, or to have yet-another repackaged version that matches what spring expects 
(it appears to be a very simple read-only usage).

I would suggest that we ship with the ASM library for two reasons. 1) The version bundled with Gradle is shaded which means the import is different, 2) the ASM version will likely change with newer versions of Gradle which then could break the code in the plugin.

> Not sure if it would be better to pull in the code, or just make it a compileOnly dependency with an extra publication that adds an explicit runtime dependency

Let's not make this overcompilated for now. We can add the ASM library as a `implementation` dependency.

**Comment by bmuschko** [comment]
I already took a crack at it: https://github.com/bmuschko/gradle-docker-plugin/pull/752. Feel free to comment on the pull request.
