### ISSUE TITLE
DockerWaitHealthyContainer - Unable to bind StartPeriod and Interval from HEALTHCHECK - out of range of int

### ISSUE THREAD

**Issue by mikealdo** [bmuschko/gradle-docker-plugin#745]
### Expected Behavior
When specifying task `DockerWaitHealthyContainer`, then there is an Json mapping exception for resolving Interval and StartPeriod properties.

It should be working for bigger values specified in HEALTCHECK like 
`HEALTHCHECK --interval=1m --start-period=5m`

### Current Behavior

For (from docker inspect)

`
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "\"$ORACLE_BASE/$CHECK_DB_FILE\" >/dev/null || exit 1"
                ],
                "Interval": 60000000000,
                "StartPeriod": 300000000000
            },
`

it returns

`
11:48:14.592 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':btn-web:waitForOracleStart'.
11:48:14.592 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > com.github.dockerjava.shaded.com.fasterxml.jackson.databind.JsonMappingException: Numeric value (300000000000) out of range of int
11:48:14.592 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    at [Source: (com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 5169] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Config"]->com.github.dockerjava.api.model.ContainerConfig["Healthcheck"]->com.github.dockerjava.api.model.HealthCheck["StartPeriod"])
`

### Context

gradle-docker-plugin uses [docker-java](https://github.com/docker-java/docker-java) library throu [shaded version](https://github.com/project-aries/docker-java-shaded). There seems to be [fixed](https://github.com/docker-java/docker-java/blob/4eef5ed7171ef6657d93bf72d6560028bb2c3c93/src/main/java/com/github/dockerjava/api/model/HealthCheck.java#L59) in latest version. 

So, maybe it would be sufficient to bump up the version of docker-java in shaded version. But it's only my guess ...

### Steps to Reproduce (for bugs)

Define any task `task waitForContainerStart(type: DockerWaitHealthyContainer) {` for container based on image which has HEALTCHECK interval or startperiod set by minutes (5m or so).

### Your Environment

MacOS, Docker 18.09.1, gradle 5.2, gradle-docker-plugin 4.4.0

**Comment by bmuschko** [comment]
> There seems to be [fixed](https://github.com/docker-java/docker-java/blob/4eef5ed7171ef6657d93bf72d6560028bb2c3c93/src/main/java/com/github/dockerjava/api/model/HealthCheck.java#L59) in latest version.

Which released version of Docker Java contains the fix? The [version the plugin uses](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy#L36) right now is `3.1.0-rc-7`.

**Comment by mikealdo** [comment]
The change in docker-java was made [15 days ago](https://github.com/docker-java/docker-java/commit/a2df1fc9c40e4d40fb1e577131b5c9fa789c9a68), so I would suppose that the latest version - 3.1.1 would contain this change.

**Comment by bmuschko** [comment]
@cdancy Can you create a new shaded JAR for 3.1.1?

**Comment by cdancy** [comment]
Been busy with on a new team at work and missed this comment. Let me spin up something tonight and put together a PR. 

And if don't respond in a timely manner in the future you have my permission to spam me :)

**Comment by bmuschko** [comment]
@cdancy Thanks!

**Comment by bmuschko** [comment]
@cdancy Here's the spam! :-) Can you please release a new version?

**Comment by bmuschko** [comment]
@mikealdo Docker Java 3.1.1 has been released and the library is now shaded in this code base. You would now be able to work on a fix for this if you'd like to send a pull request.

**Comment by bmuschko** [comment]
Closing the issue as the next release will container Docker Java 3.1.1.

**Comment by cdancy** [comment]
@bmuschko planning on doing a release within the next couple of days but want to get in some minor changes/enhancements in a follow up PR also over the next couple days. Not sure if you were looking to pull the trigger but hold off if you do! ;)

**Comment by bmuschko** [comment]
@cdancy I have no release planned at the moment. You go for it.
