### ISSUE TITLE
Dockerfile.FileInstruction does not use flags if Dockerfile.File is passed in using a Provider

### ISSUE THREAD

**Issue by schoeneu** [bmuschko/gradle-docker-plugin#747]
If a `FileInstruction` is created using the constructor using a `Provider` : 

https://github.com/bmuschko/gradle-docker-plugin/blob/703ce60f498314092f2964ca6fd6fe19630bd428/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L1020-L1034

Then the `FileInstruction`s `flags` field is never set. However, the logic building the line for the docker file looks at `FileInstruction::flags` only, ignoring `File::flags`. 

https://github.com/bmuschko/gradle-docker-plugin/blob/703ce60f498314092f2964ca6fd6fe19630bd428/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L1048-L1050

Since `file.flags` is non-null but `this.flags` is `null` in this case, this leads to a line like
```
ADD null src dst
```
being added to the Dockerfile, which crashes the image build.

This seems to be a simple case of a forgotten check. If so, I'm happy to provide a PR to fix it. Am I missing something that would make that more complicated than it seems at first glance?

**Comment by bmuschko** [comment]
Yeah, you are right. That's a bug. It should say `keyword += " $file.flags"`. Sure, go ahead a create pull request if you'd like to work on it. Optimally, the pull request would also create an integration test for it that passes a `Provider`.

**Comment by bmuschko** [comment]
@schoeneu Just checking...are you currently working on a pull request for this?

**Comment by schoeneu** [comment]
@bmuschko Just got around to this. Created PR #753
