### ISSUE TITLE
version 4.4.1 (PR 736) breaks Java Application Plugin support

### ISSUE THREAD

**Issue by nitzan-n** [bmuschko/gradle-docker-plugin#749]
With version 4.3.0, the Entrypoint in the docker file used the Java Application plugin script, including (for example) picking up runtime environment variables (i.e. configured at deployment and not at image build time). 
With version 4.4.1, due to changes done in PR736, this is no longer true.
If there is a way to pick up runtime environment variables into the container (as the Application plugin startup script does), I couldn't find it.

Docker file generated in 4.3.0 (with Java Application plugin creating Java startup scripts at "/my-app/bin/my-app"):
FROM xxxx
ADD my-app /my-app
ADD app-lib/my-app.jar /my-app/lib/my-app.jar
ENTRYPOINT ["/my-app/bin/my-app"]

Docker file generated in 4.4.1:
WORKDIR /app
COPY libs libs/
COPY resources resources/
COPY classes classes/
ENTRYPOINT ["java", "-cp", "/app/resources:/app/classes:/app/libs/*", "my.app.Main"]

**Comment by bmuschko** [comment]
> With version 4.3.0, the Entrypoint in the docker file used the Java Application plugin script, including (for example) picking up runtime environment variables (i.e. configured at deployment and not at image build time).

You will have to be explicit about which environment variable you want to set by modifying the `Dockerfile` in your build script. What exactly do you mean by "deployment"? Do you mean at the time of container creation?

> If there is a way to pick up runtime environment variables into the container (as the Application plugin startup script does), I couldn't find it.

Which one specifically in the generated start script?

**Comment by nitzan-n** [comment]
I don't want to set the environment variables in my Dockerfile. I want to get the values of my environment variables (specifically JAVA_OPTS env var) in the containerized application,  as they are set externally at the time of the container's creation, for example by the "env" configuration in a Kubernetes deployment.

Previously, the Java Application-plugin startup script was called as the Entrypoint, it got the value of JAVA_OPTS that was set at container creation, and passed it to the Java executable in the command line. 
With the direct call to the Java executable in v.4.4.1, the value of JAVA_OPTS at container creation time is not passed to the Java program.

**Comment by bmuschko** [comment]
You could probably achieve that by adding a `CMD` instruction to the Dockerfile that uses `JAVA_OPTS`. That would be the equivalent to what the Gradle application plugin is doing. Something like this could work (I didn't try it out):

```
dockerCreateDockerfile {
    defaultCommand "\$JAVA_OPTS"
}
```

**Comment by s4nk** [comment]
do the docs need to be updated? The guide currently says that the default value of `docker.javaApplication.exec` is `Create ENTRYPOINT using script from Application plugin`

**Comment by bmuschko** [comment]
@s4nk Yeah, I must have missed that. Happy to receive a PR for it. Not sure when I will get around to fixing it.

@nitzan-n Can we close the issue?

**Comment by nitzan-n** [comment]
Seems like the behavior of the Application plugin's startup script can be reached with adding the following 'exec' to the javaApplication section:

javaApplication {
        ...
        exec {
            entryPoint '/bin/sh -c'
            defaultCommand "exec java \\$JAVA_OPTS -cp /app/resources:/app/classes:/app/libs/* ${mainClassName}"
        }
}
