### ISSUE TITLE
Determine running containers

### ISSUE THREAD

**Issue by aleclerc** [bmuschko/gradle-docker-plugin#75]
Is there a task that I can use to query running containers?

There are a couple of scenarios that I'm trying to fulfil:
- I want to start a container IF the container isn't yet running. I was going to check docker to see if it's running, if it's not I would start it.
- I want to have one gradle task for creating/starting up containers and another one for stopping/removing them. Since I get the container id from the create/start task, I'm not sure how to persist that and save that for when i run the stop job. If I could query containers I'd be able to figure out the image ids and stop them.

**Comment by bmuschko** [comment]
> Is there a task that I can use to query running containers?

I don't think there is. What would be the equivalent if you'd run the plain `docker` command? The other question then will be: Does Docker Java support it?

**Comment by aleclerc** [comment]
Yeh it's basically a 'docker ps'. I looked at the Java Lib and it does support it as well. I'm made a task for it based off of List Images for my purpose and I'll try to contrib back to the repo. I've never done much gradle dev before so no promises, but reading through you're awesome book so hopefully that'll help.

**Comment by bmuschko** [comment]
The task already exists: [DockerListImages](http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/DockerListImages.html). At the moment it just prints out the list of images to the console so you cannot access that response. However, what you can do is to write a custom task that extends `AbstractDockerRemoteApiTask`. With that you have a `DockerClient` instance that you can use to run any logic you want. This [test case](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/integTest/groovy/com/bmuschko/gradle/docker/AbstractDockerRemoteApiTaskIntegrationTest.groovy#L4) demonstrates an example.

**Comment by bmuschko** [comment]
I don't think we want to have a "specific" List task. Instead of introducing a new one, I'd rather expose the response handling to consumers. In this case introduce an implementation of `ResponseHandler`, use it in the existing class and allow for setting a custom handler with a setter method.

**Comment by bmuschko** [comment]
Any chance you want to provide a pull request for this?

**Comment by toedter** [comment]
@bmuschko Would it help if an optional container name could be specified when creating it? Then you could use this name in the next build to stop and remove the container. E.g. you could always use the name "myRunningContainer", stop it, remove it and then start a new container "myRunningContainer" from the newly created image.

**Comment by bmuschko** [comment]
@toedter Not sure how that would help. Assigned values are not persisted between two builds. You'd have to write your own logic to make it happen. BTW: You can access the image ID of a built image with the method `getImageId()`. I don't think it's obvious from the Groovydocs as it is a Closure assigned to a property using Gradle's extension mechanism.

**Comment by bmuschko** [comment]
You can now set a `ResponseHandler` for the task that allows you to handle the response the way you want.
