### ISSUE TITLE
Docker task to remove all containers for a particular image

### ISSUE THREAD

**Issue by jk1** [bmuschko/gradle-docker-plugin#750]
Hi,

First of all, thanks a lot for the great work implementing and maintaining the plugin.

In our builds we're often in need to remove all the containers for a particular image.
To do so we've created a small extension task, as simple as

```
class DockerRemoveContainersForImage extends DockerExistingImage {

    @Override
    void runRemoteCommand(dockerClient) {
        dockerClient.listContainersCmd().withShowAll(true).exec().forEach { container ->
            if (container.image == imageId.get()) {
                dockerClient.removeContainerCmd(container.id).withForce(true).withRemoveVolumes(true).exec()
            }
        }
    }
}
```

It may be a nice addition to the toolset plugin offers, so other plugin users can enjoy it as well.
Please let me know if this seems of any value to you and if it's worth creating a pull request.

**Comment by bmuschko** [comment]
Thanks for proposing. I don't think we'll want an additional custom task type in the plugin. From my perspective, this is a perfect example of a custom, in-house plugin built on top of this plugin to suite your needs. Your use case clearly demonstrates that you can enhance the base functionality of the plugin for your own purposes.

@cdancy @orzeh Any other thoughts?

**Comment by orzeh** [comment]
@bmuschko I agree with you. Such type of tasks should be in custom plugins.

**Comment by jk1** [comment]
@bmuschko @orzeh no problem. 
Thank you for considering it.
