### ISSUE TITLE
DockerBuildImage not having registryCredentials passed into the command

### ISSUE THREAD

**Issue by danielfs1** [bmuschko/gradle-docker-plugin#76]
We are trying to build a docker image FROM a image that is in our private repo on Docker Hub.

We noticed that the following line is not a part of the DockerBuildImage command creation:

```java
if(getRegistryCredentials()) {
    def authConfig = threadContextClassLoader.createAuthConfig(getRegistryCredentials())
    buildImageCmd.withAuthConfig(authConfig)
}
```

Are there any plans to implement this into the DockerBuildImage task?

**Comment by bmuschko** [comment]
It doesn't look like Docker Java currently supports that functionality (see [BuildImageCmdImpl.java](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/core/command/BuildImageCmdImpl.java)). You'd have to ask there. Once they support it when can easily add it to the task implementation.

**Comment by danielfs1** [comment]
On line 191 of that file that you linked it looks like they support ```public BuildImageCmd withBuildAuthConfigs```.

I'm assume what you are saying is that buildAuthConfig and authConfig are for different things?

**Comment by bmuschko** [comment]
I am not quite sure what the difference is. It seems to me like you can assign more than one `AuthConfig`. Sounds pretty confusing. Not sure when you'd have more than one `AuthConfig`. If you want, you can create a pull request and I can incorporate it. At the moment I don't have time to work on it myself.

**Comment by bmuschko** [comment]
@danielfs1 Interested in providing a pull request?
