### ISSUE TITLE
Please add support for additional parameters to DockerBuildImage task

### ISSUE THREAD

**Issue by m-raab** [bmuschko/gradle-docker-plugin#760]
DockerBuildImage does not support the "--target" for multistage Docker builds.

### Expected Behavior

The DockerBuildImage task supports this parameter or it is possible to extend the DockerBuildImage task with additional parameters.

### Current Behavior

Currently it is not possible to add easily new parameters to this task.

### Context

We use Docker multistage builds to build different images from the same base image. Currently we have to use different Dockerfiles. The Docker cache is not usable in this case. As long we use the same files it is possible to use cached intermediate files.

**Comment by bmuschko** [comment]
Would you be interested in providing a pull request for this?

**Comment by m-raab** [comment]
I never did this bevor, but I can try this.

Regards
Matthias

Von: Benjamin Muschko <notifications@github.com>
Antworten an: bmuschko/gradle-docker-plugin <reply@reply.github.com>
Datum: Mittwoch, 6. März 2019 um 16:31
An: bmuschko/gradle-docker-plugin <gradle-docker-plugin@noreply.github.com>
Cc: Matthias Raab <M.Raab@intershop.de>, Author <author@noreply.github.com>
Betreff: Re: [bmuschko/gradle-docker-plugin] Please add support for additional parameters to DockerBuildImage task (#760)


Would you be interested in providing a pull request for this?

**Comment by bmuschko** [comment]
OK, let us know if you need any help.

**Comment by eladchen** [comment]
@bmuschko Isn't this the purpose of the code below?

https://github.com/bmuschko/gradle-docker-plugin/blob/2222ab6b759037a028bf06e3219d1418a251a11d/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy#L185-L189

**Comment by bmuschko** [comment]
@eladchen No, I don't think so. `build-arg` is a different parameter. See the [Docker docs](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg).

**Comment by eladchen** [comment]
Yep :) totally missed that.

Is there a gitter or some official chat room so we can discuss?

**Comment by bmuschko** [comment]
@eladchen You can find a link to the [plugin's Gitter channel](https://gitter.im/gradle-docker-plugin/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) in the README file.
