### ISSUE TITLE
com.bmuschko.docker-java-application - not able to set spring profiles

### ISSUE THREAD

**Issue by Annie0507** [bmuschko/gradle-docker-plugin#761]
We upgraded our version of 'com.bmuschko.docker-java-application' to '4.6.0' and Spring Boot version 2.1.3.RELEASE and gradle version gradle-5.2.1-all and when we are trying to run the application, we are not able to set the profiles. 

We have tried the following things: 
docker run {image_id} --spring.profiles.active=dev

dockerCreateDockerfile {
    environmentVariable 'JAVA_OPTS', '-Dspring.profiles.active=dev'
}

and also,
docker {
   springBootApplication {
        args = ['-Dspring.profiles.active=dev'] - Complains that args is not a valid argument.
   }
}

Before the upgrade, it was picking up the profile from helm templates correctly.

### Expected Behavior
When the app is deployed to dev, it should pick up the env and setup the profile.

### Current Behavior
No active profile set, falling back to default profiles: default

### Context
When out application is deployed to an environment, instead of picking up the correct application.properties file, it is reading the variables from the local application.properties.

### Steps to Reproduce (for bugs)
plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot' version '2.1.3.RELEASE'
    id 'com.bmuschko.docker-java-application' version '4.6.0'
}

mainClassName = "xxx"

docker {
    url = lookupDockerHost()
    certPath = lookupSslKeysDirectory()
    registryCredentials {
        url = registry
        username = lookupDockerRegistryUser()
        password = lookupDockerRegistryPassword()
    }

    javaApplication {
        baseImage = "${dockerBaseImage}"
        maintainer = "${teamName} ${teamEmail}"
        tag = registry + "/${group}/${name}:${project.version}"
    }
}
Then run the command:

./gradlew :{project-name}:dockerBuildImage 

then docker run with the image that was build:

docker run {image-id} ----spring.profiles.active=dev

### Your Environment
Dev, Perf, Prod

**Comment by bmuschko** [comment]
Please find the details on why this changed in https://github.com/bmuschko/gradle-docker-plugin/pull/736. We are not using the generated startup script anymore provided by Gradle's application plugin. It internally sets `JAVA_OPTS` before executing the `java` command.

```
dockerCreateDockerfile.environmentVariable 'JAVA_OPTS', '-Dspring.profiles.active=dev'
```

This probably doesn't work as you the environment variable is set _after_ the `java` command is run in the Dockerfile and therefore won't be evaluated. Have a look at the generated `Dockerfile`. You will have to set it before hand. The [user guide explains](https://bmuschko.github.io/gradle-docker-plugin/#modifying_instructions_of_a_dockerfile_task) how to manipulate the generated `Dockerfile`.

```
springBootApplication.args = ['-Dspring.profiles.active=dev']
```

This won't work as you don't apply the [Docker Spring Boot application plugin](https://bmuschko.github.io/gradle-docker-plugin/#spring_boot_application_plugin). BTW: You should probably go with that one anyway.

We will want to work on some more documentation around this topic. It comes up every so often.

**Comment by Annie0507** [comment]
I had tried both the options, didn't seem to work - When using args for Docker Spring Boot application plugin, it complained about args not being an acceptable parameter and when setting the variable in the Dockerfile, didn't reflect the changes.

Had to explicitly add spring.profiles.active in the application.properties (didn't want to do that here, instead in the gradle file)

**Comment by bmuschko** [comment]
> When using args for Docker Spring Boot application plugin, it complained about args not being an acceptable parameter...

This is because there is no args method or property on the extension [DockerSpringBootApplication](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplication.groovy). Did you see the `args` parameter somewhere?

> ...when setting the variable in the Dockerfile, didn't reflect the changes.

I will try to find some time over the weekend to add a working example to the documentation.

> Had to explicitly add spring.profiles.active in the application.properties (didn't want to do that here, instead in the gradle file)

I agree. This is suboptimal.

**Comment by m410** [comment]
Hello I'm trying to figure out the same issue.  I was hoping I could do something like this:
```
docker {
    registryCredentials {
        //...
    }
    springBootApplication {
        baseImage.set("openjdk:11.0.2-slim-stretch")
        ports.set(listOf(8080, 8443))
        tag.set("${dockerBase}/${space}/app:${project.version}")
        exec({
            environment("SPRING_PROFILES_ACTIVE","stage")
        })       
    }
}
```
but exec only seems to apply to javaApplication not springBootApplication.  I get the error `execCommand == null!` from gradle when I run this.

What is the best way to set the spring active profile?

**Comment by bmuschko** [comment]
Could both of you describe the use case/workflow you are trying to solve? I am wondering why you want to set the profile as part of the `Dockerfile` and not at container-creation time. Are you building a Docker image per environment? In the light of Continuous Delivery best practices I'd suggest to not do that if that's what you are doing right now. An artifact should only be built once independent of the environment.

What I have done in the past is to inject [the environment variable `SPRING_PROFILES_ACTIVE`](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html#howto-set-active-spring-profiles) at container-creation time. That could happen when creating the container via Docker CLI (`docker create --env`), Docker Compose or when using Kubernetes with or without Helm. Did you try that?

**Comment by bmuschko** [comment]
@Annie0507 @m410 Did my suggestion help? Could you please also answer the question from my previous post?

**Comment by Annie0507** [comment]
I was not building a Docker image per environment, but one Docker image independent of the environment and then injecting  environment variables via Helm templates. It is not picking up from the helm templates so had to inject it via application.properties with SPRING_PROFILES_ACTIVE.

**Comment by bmuschko** [comment]
@Annie0507 Thanks for the info. I don't have a Helm environment at hand at the moment but I will try with Kubernetes.

@cdancy Is this something you can verify on Helm?

**Comment by cdancy** [comment]
I can certainly help to verify anything helm related using OpenShift. If you guys have a chart. I'm curious though as to how you may be injecting these with helm as it may be that's where your issue lies.

**Comment by sfriberg** [comment]
I hit a similar issue just now and the issue is the JVM doesn't pick up JAVA_OPTS.

The JVM will pick up the _JAVA_OPTIONS ENV variable, so if you replace JAVA_OPTS with that it should work.

**Comment by bmuschko** [comment]
Apart from all the suggestions (usage of environment variables `_JAVA_OPTIONS` or `SPRING_PROFILES_ACTIVE`), I implemented a change that allows for passing in JVM arguments _at build time_. That's likely not your use case as you want to change a runtime value at _container creation time_.

**Comment by bmuschko** [comment]
FYI: I added documentation here: https://bmuschko.github.io/gradle-docker-plugin/#providing_container_build_time_and_runtime_parameters
