### ISSUE TITLE
Missing support for tmpfs/mounts 

### ISSUE THREAD

**Issue by thyming** [bmuschko/gradle-docker-plugin#762]
Hi, I don't believe there's a way exposed through the gradle-docker-plugin to create tmpfs mounts. I'd like to leverage this feature in test database containers.

**Comment by bmuschko** [comment]
What task are you looking to use? `DockerCreateContainer`?

**Comment by thyming** [comment]
Yes, that’s correct.

**Comment by thyming** [comment]
Happy to submit a PR if this isn’t already supported in a way that I don’t
see.

**Comment by bmuschko** [comment]
I am not quite sure if it is or isn't supported yet. Did you look at the properties in the task?

@cdancy @orzeh Do you have any advice here?

**Comment by thyming** [comment]
It didn’t seem to be at a glance. It’s a property on hostConfig in the
docker-java api.

**Comment by bmuschko** [comment]
Closing this. We are happy to receive a PR for it.
