### ISSUE TITLE
npipe support instead of 2375 on windows

### ISSUE THREAD

**Issue by malejpavouk** [bmuschko/gradle-docker-plugin#769]
### Question
Would it be possible to support on windows the npipe instead of using tcp:2375?   

### Current Behavior
Only tcp over unsecured 2375 port is supported to connect to docker deamon. localhost:2375 is disabled by default in docker.

### Context
In Docker for windows, the exposure of deamon on 2375 is buggy*. I know, not fault of anyone related to this plugin, but still, it makes it unusable...

* In some of the previous versions Docker was to be restarted to start listening again. With the current one it seems that the port is not exposed at all (even though its enabled)...

### Your Environment
W10, Docker for windows

**Comment by malejpavouk** [comment]
Btw: I took a look into other java-docker integration components such as testcontainers and it seems that the groundwork was already done.
https://github.com/testcontainers/testcontainers-java/blob/52d7126c19cbde76937dcabe1b589662fd15f9a5/core/src/main/java/org/testcontainers/dockerclient/NpipeSocketClientProviderStrategy.java

So if it would be possible to add this support also to this plugin, it would be really appreciated.

**Comment by bsideup** [comment]
FYI we plan to contribute our (Testcontainers) OkHttp transport back to docker-java once it is split into modules

**Comment by cdancy** [comment]
I've opened an ISSUE with these guys about 2 years ago now. It looks like they may be getting around to thinks. IDK. In either event lets close this issue as there currently isn't anything we can do until they move ahead. Once they do the support should just work as is and folks can feel free to pass in the npipe URL.

https://github.com/docker-java/docker-java/issues/765
