### ISSUE TITLE
Dockercon 2019

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#774]
We (at least myself currently) will be attending dockercon 2019. If you'd like to meet up, or network, or suggest ideas, or buy us a beer feel free to ping us either on **THIS** issue or on our gitter channel. Hope to see you all there!!!

https://www.docker.com/dockercon/

**Comment by bmuschko** [comment]
I won't be there unfortunately. 😭

**Comment by bmuschko** [comment]
@cdancy Did you have the chance to meet any users of this plugin?

**Comment by cdancy** [comment]
@bmuschko sadly no :( When I got there they did have this idea of an ad-hoc user-talk that you could do off to the side, and folks could come if they wanted to chat, but we/I didn't plan for it and had a bunch of other things going on. All in all though it was a good con. Lots of talk around Istio. I would 95% of all vendors there were talking/selling docker monitoring or security based software. I took that to mean that the community and docker software in general has matured and stabilized and now the big things to talk about are those products build on top of docker. Docker itself had some neat things to show around building on windows, and building windows images on linux (still not sure how that magic happened), but nothing ground breaking.
