### ISSUE TITLE
Can't build docker image

### ISSUE THREAD

**Issue by hcabnettek** [bmuschko/gradle-docker-plugin#776]
gradle version 5.2.1

```
'com.bmuschko.docker-spring-boot-application' version '4.6.2'

docker {
	springBootApplication {
		baseImage = 'openjdk:8-alpine'
		ports = [9090, 8080]
		tag = 'builder-portal-data:1.0'
	}

	registryCredentials {
		username = getConfigurationProperty('DOCKER_USERNAME', 'docker.username')
		password = getConfigurationProperty('DOCKER_PASSWORD', 'docker.password')
		email = getConfigurationProperty('DOCKER_EMAIL', 'docker.email')
	}
}

String getConfigurationProperty(String envVar, String sysProp) {
	System.getenv(envVar) ?: project.findProperty(sysProp)
}
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.DockerPushImage
import com.bmuschko.gradle.docker.tasks.image.Dockerfile

task createDockerfile(type: Dockerfile) {
	group = 'Docker'
	destFile = project.file('build/docker/Dockerfile')
	from 'openjdk:8-jre-alpine'
	copyFile jar.archiveFileName, '/app/builder-portal-data.jar'
	entryPoint 'java'
	defaultCommand '-jar', '/app/builder-portal-data.jar'
	exposePort 8080
}


task buildImage(type: DockerBuildImage) {
	dependsOn createDockerfile
	tag = "hcabnettek/builder-portal-data:$jar.version"
}

task pushImage(type: DockerPushImage) {
	dependsOn buildImage
	conventionMapping.imageName = { buildImage.getTag() }
}

```

**Comment by bmuschko** [comment]
The `com.bmuschko.docker-spring-boot-application` plugin already provides the task you have been writing yourself. You may have missed that in the [documentation page for the plugin](https://bmuschko.github.io/gradle-docker-plugin/#tasks_2)? You should be able remove every below the first `import` statement.

Please provide the error/stack trace you are seeing once you fixed the code.

**Comment by hcabnettek** [comment]
Ahh that makes more sense. There is no problem with the plugin, the problem is me not knowing enough about Gradle. ./gradlew DockerBuildImage and ./gradlew DockerPushImage both work as expected. Why do they not show up when I run ./gradlew tasks, only the dockerSyncBuildContext shows in the gradle popout in Intellij. Is there any way to make these tasks show up as well? Thanks

**Comment by bmuschko** [comment]
It's because some of the tasks didn't assign a `group`. This has been fixed but released yet. You can render all tasks with `gradle tasks --all`. For more info, see the Gradle docs on this.

**Comment by cdancy** [comment]
@bmuschko I can kick a new point release with this fix as well as `docker-java` bump I got in. I haven't done a release in a while and might be good to get me back into the swing of things :) Also I don't think we have anything in-flight at the moment so a point release seems safe enough.

**Comment by hcabnettek** [comment]
gradle tasks --all Yes @bmuschko that works perfect. Thanks so much for all of your help!
