### ISSUE TITLE
docker-java-application plugin fails when project has no 'classes' output

### ISSUE THREAD

**Issue by sgilhooly** [bmuschko/gradle-docker-plugin#780]
### Expected Behavior
`gradle dockerBuildImage` should complete without error

### Current Behavior
The build task fails with  the error:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':subproject:dockerBuildImage'. <41 internal calls> 
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: COPY failed: stat /TEMP_DIR/classes: no such file or directory
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:79)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:51)
	at com.github.dockerjava.core.command.BuildImageResultCallback$awaitImageId.call(Unknown Source)
	at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage.runRemoteCommand(DockerBuildImage.groovy:195)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:70) <39 internal calls>
	... 37 more
```

### Context
I use a gradle multi-project style build to separate modules under the same build environment. One of the projects is nothing more than the java application wrapper which bundles up the necessary modules as an application distributable. So this project has no java source files of its own. All classes come from the dependencies of this otherwise empty project. In other words:
```
project-root
 +-- core-module 
 |    +--- build.gradle (builds core-module.jar)
 |    +--- src/main/java/Main.java
 +-- bundler (depends on core-module)
      +--- build.gradle (only has application + docker tasks)
```

### Steps to Reproduce (for bugs)

This project will reproduce this issue: https://github.com/sgilhooly/gradle-docker-app-example
A simple `./gradlew build` should do the trick

### Your Environment

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.14.3 x86_64
```

**Comment by bmuschko** [comment]
Generally speaking I think the better option to model your use case would be to make the `bundler` build script a [Gradle script plugin](https://docs.gradle.org/current/userguide/plugins.html#sec:script_plugins) that you apply from the build script of `core-module`. There's no real benefit of having a submodule just for the purpose of keeping build logic separate.

**Comment by bmuschko** [comment]
Did my comment make sense? I think you should model your build in a different way to solve your issue. It's reasonable to assume that a project produces class files.

**Comment by bmuschko** [comment]
I am going to close the issue as we haven't heard back. Let us know if you want to further discuss the topic.

**Comment by sgilhooly** [comment]
Sorry I was on vacation but you can keep it closed. If my sample program had been the extent of the project I was part of, then yes it makes sense that the application plugin could be applied directly to the java project. In our particular case, however, we have a large project which builds and combines may different things (microservices). Bundling it into a docker container is one of many different deployment strategies. Granted we might be doing it all wrong, so I'm fine if you want to keep this closed, but organizing the deployment mechanisms separate from the code libraries works for us. I ended up creating our own custom plugin which just uses the docker-remote plugin to build things the way we need them.

**Comment by bmuschko** [comment]
I am definitely not saying you are doing it wrong. My argument here is that you don't need to model another subproject to achieve your goal. This might be a typical thing you have to do in Maven. In Gradle you use a script plugin that can be "mixed" into the build script that needs the functionality. Implementing a custom binary plugin is even more preferable as you can keep that code completely separate.
