### ISSUE TITLE
Upgrade to latest docker-java client

### ISSUE THREAD

**Issue by padas2** [bmuschko/gradle-docker-plugin#786]
Our plugins are making use of gradle-docker-plugin to launch containers in parallel.
When launching in parallel, we are facing [this]( https://github.com/kohlschutter/junixsocket/issues/45) issue .

For this to be fixed, the docker-java client needs to be upgraded to use the latest junix dependencies i.e. 2.2.0 . This is already included in the latest release 3.1.2 [Link](https://github.com/docker-java/docker-java/milestone/34?closed=1).

We need the gradle-docker-plugin to use this version of docker-java client.

**Comment by cdancy** [comment]
I'll spin up a PR and get this in for the next release (assuming no issues) which we are due for. Stay tuned...

**Comment by cdancy** [comment]
Change has been merged to master.

**Comment by padas2** [comment]
@cdancy When can we get a new version of this plugin published ?
