### ISSUE TITLE
We cannot import com.bmuschko.gradle.docker.tasks.image.Dockerfile with gradle 5.3.1. I got error:unable to resolve class com.bmuschko.gradle.docker.tasks.image.Dockerfile

### ISSUE THREAD

**Issue by lukavucko** [bmuschko/gradle-docker-plugin#791]

**Comment by lukavucko** [comment]
this is my docker.gradle file:
buildscript {
    repositories {
        maven { url mavenResolveUrl }
    }

    dependencies {
        classpath "com.bmuschko:gradle-docker-plugin:${dockerGradlePluginVersion}"
    }
}

apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin

import com.bmuschko.gradle.docker.DockerRegistryCredentials

**Comment by cdancy** [comment]
@lukavucko looks like you haven't read our docs. Check out our [getting started](https://bmuschko.github.io/gradle-docker-plugin/#getting_started) section to help you hit the ground running.

**Comment by lukavucko** [comment]
If I try with this solutions:
buildscript {
    repositories {
        gradlePluginPortal()
    }

    dependencies {
        classpath "com.bmuschko:gradle-docker-plugin:${dockerGradlePluginVersion}"
    }
}

apply plugin: 'com.bmuschko.docker-remote-api'

I got this error: Plugin with id 'com.bmuschko.docker-remote-api' not found.

If I try with this solution:
buildscript {
    repositories {
        gradlePluginPortal()
    }

    dependencies {
        classpath "com.bmuschko:gradle-docker-plugin:${dockerGradlePluginVersion}"
    }
}

apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin

I got the same error: unable to resolve class com.bmuschko.gradle.docker.tasks.image.Dockerfile

**Comment by cdancy** [comment]
Which version of our plugin are you specifying?

**Comment by lukavucko** [comment]
com.bmuschko:gradle-docker-plugin:4.7.1

**Comment by cdancy** [comment]
Can you paste a complete reproducible script that you are using?

**Comment by lukavucko** [comment]
docker.gradle:

/**
 * Dont apply docker in Eclipse. There are tasks like ear missing and excluded
 * as well.
 */
if (rootProject.ext.buildInEclipse) {
   logger.info("Build in Eclipse: No docker plugins applied")
   return;
}

buildscript {
    repositories {
        gradlePluginPortal()
    }

    dependencies {
        classpath "com.bmuschko:gradle-docker-plugin:${dockerGradlePluginVersion}"
    }
}

apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin


import com.bmuschko.gradle.docker.DockerRegistryCredentials
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.DockerPushImage
import com.bmuschko.gradle.docker.tasks.image.DockerRemoveImage
import com.bmuschko.gradle.docker.tasks.image.Dockerfile

//
// lifecycle tasks
//
task createDockerFiles {
    dependsOn project.tasks.withType(Dockerfile)
}

task buildDockerImages {
    dependsOn project.tasks.withType(DockerBuildImage)
}

task pushDockerImages {
    dependsOn project.tasks.withType(DockerPushImage)
}

task removeDockerImages {
    dependsOn project.tasks.withType(DockerRemoveImage)
}

//
// Login to Docker registry.
//
if (project.hasProperty('dockerRegistryUsername') && project.hasProperty('dockerRegistryPassword')) {
    def createRegistryCredentials = { String url, String username, String password ->
        def registryCredentials = new DockerRegistryCredentials()
        registryCredentials.url = url
        registryCredentials.username = username
        registryCredentials.password = password
        registryCredentials
    }

    project.tasks.withType(DockerBuildImage) {
        registryCredentials = createRegistryCredentials('redhat.adcr.io', project.dockerRegistryUsername, project.dockerRegistryPassword)
    }

    project.tasks.withType(DockerPushImage) {
        registryCredentials = createRegistryCredentials('syrius.adcr.io', project.dockerRegistryUsername, project.dockerRegistryPassword)
    }
}

//
// images
//
apply from: "${rootProject.projectDir}/gradle/docker/presentation-server.gradle"
apply from: "${rootProject.projectDir}/gradle/docker/application-server.gradle"
apply from: "${rootProject.projectDir}/gradle/docker/batch-client.gradle"

**Comment by cdancy** [comment]
Where are you getting this error from? Can you run things from the command line?

**Comment by lukavucko** [comment]
When I want to execute command ./gradlew build --parallel in terminal

**Comment by navithachetty06** [comment]
Could not resolve all artifacts for configuration `'classpath'`.
   > Could not find com.bmuschko:gradle-docker-plugin:3.6.2.
   
   Context: I’m using Gradle version 6.9 on Windows.
   
   

Running ./gradlew clean and then ./gradlew build - but it fails.

Any help would highly be appreciated.
