### ISSUE TITLE
Implement generic Retry on Tasks

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#792]
Port over from the `gradle-kubernetes-plugin` the ability to retry any given Task that fails. We often hit hiccups of sorts when querying the docker daemon due to the extremely high number of containers and load we put on it. Having the ability to retry those failed task executions (not literally re-run the task just the underlying `docker-java` invocation) would help mitigate this.

What do you guys think? I can knock this out easily enough as it should be a straight enough port with some tests written for our use-case.

https://github.com/bmuschko/gradle-kubernetes-plugin#on-retry

**Comment by orzeh** [comment]
I don't have a strong opinion on that. It might be useful on some edge cases as you mentioned so I won't be blocking adding this to the codebase :)

**Comment by bmuschko** [comment]
I think this should be a functionality in Gradle core. In fact there's already an[ open issue](https://github.com/gradle/gradle/issues/1449) for it. You may want to vote for it.

The Gradle issue doesn't really help you though to solve your immediate problem. From my perspective that should probably functionality wrapped in a plugin that you can add to any Gradle build so that 1) we don't have to swallow the maintenance cost here, 2) you can just add it to your project as needed.

**Comment by bmuschko** [comment]
Thought about this more. IMHO this shouldn't be added to the plugin directly. This is a cross-cutting concern and should be provided by a different plugin.

**Comment by cdancy** [comment]
That's fair I suppose but would be really hard to do, if not outright impossible, to retry the logic of an arbitrary task.

**Comment by bmuschko** [comment]
I am not sure if it would be _really_ hard. I can think of various options:

1. Write an abstract or delegating task implementation that encapsulates the logic. Consuming tasks need to decide to actively use it.
2. Some sort of Groovy runtime a la AOP around a task action implementation (a method that adds the `TaskAction` annotation).

**Comment by cdancy** [comment]
I guess I was thinking more along the lines of what I did with the kubernetes plugin and have the logic be injected with a dsl that devs could edit. Something devs could use OOTB now with their tasks. I dont think that's possible but if it is let me know and I'd throw something together.
