### ISSUE TITLE
Implements docker services tasks

### ISSUE THREAD

**Issue by hefberk** [bmuschko/gradle-docker-plugin#795]
hi,

is it plan to manage docker services tasks ?
docker service update and docker service update --force
your plugin works perfectly but i have to update service by hands at end of pushImage task.

ty for reading

**Comment by cdancy** [comment]
There is currently no plan but it could be easily done. Care to send in a PR?

**Comment by bmuschko** [comment]
Most users gravitated toward Kubernetes instead of Docker Swarm. I am not sure if it is worth the effort to add the functionality. We are happy to accept to a pull request for this. I am pretty sure its a significant amount of work as there are many options to be exposed by the relevant tasks.

**Comment by cdancy** [comment]
All the call should be under the `services` umbrella if folks really want it. Indeed this functionality is better off with Kubernetes, as that's what it is designed for, but deploying and using it can be quite heavy and a pure docker solution, while I would never use for production, could be beneficial for development use-cases.

**Comment by bmuschko** [comment]
I'll close this issue for now. It doesn't look like anyone wants to contribute a PR for it. We can reopen in case somebody wants to put in the work.
