### ISSUE TITLE
Validation error - ImageName not set - how to set it?

### ISSUE THREAD

**Issue by djkingCanada** [bmuschko/gradle-docker-plugin#796]
plugins {
    id 'java'
    id 'application'
    id 'distribution'
    id 'com.bmuschko.docker-remote-api' version '4.8.0'
}
...
import com.bmuschko.gradle.docker.tasks.image.*

docker{
 // I have a custom registry entry here, but problem occurs when that's been commented out.
}

task buildAxelImage(type: DockerBuildImage) {
    inputDir = file('docker')
    tags.add('brightside/axel:latest')
}

./gradlew buildAxelImage fails with a validation exception:
Caused by: org.gradle.api.InvalidUserDataException: No value has been specified for property 'imageName'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:69)

I can't find anything in the docs that would tell me how to set the imageName, so not sure what I'm missing.  I freely admit I'm new to docker.

Env info:
------------------------------------------------------------
Gradle 5.4
------------------------------------------------------------

Build time:   2019-04-16 02:44:16 UTC
Revision:     a4f3f91a30d4e36d82cc7592c4a0726df52aba0d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.14.4 x86_64

**Comment by djkingCanada** [comment]
Doh, wasn't running the task I thought I was.  My bad.

**Comment by cdancy** [comment]
Was at Dockercon which is why I didn't see this. Glad you figured it out.
