### ISSUE TITLE
DockerBuildImage broken on Master

### ISSUE THREAD

**Issue by llaforest** [bmuschko/gradle-docker-plugin#804]
The plugin throws an exception when I try to call the DockerBuildImage task.

I bisected and the faulty commit is: 
```
commit c4ed8379bac3e7602b87eb9ace6eec64295599ce
Author: Benjamin Muschko <benjamin.muschko@gmail.com>
Date:   Mon Apr 22 21:29:27 2019 -0600
```

The exception I get is:
```
* What went wrong:
A problem occurred evaluating root project 'test'.
> Failed to apply plugin [id 'com.bmuschko.docker-remote-api']
   > Could not create an instance of type com.bmuschko.gradle.docker.DockerExtension.
      > Could not create an instance of type com.bmuschko.gradle.docker.DockerRegistryCredentials.
         > The constructor for class com.bmuschko.gradle.docker.DockerRegistryCredentials should be annotated with @Inject.
```

### Expected Behavior
To run and build a docker image

### Current Behavior
Crashing and does not build the image

### Context
I rebased my code to be on the tip. I troubleshooted why the code would not run anymore.
 
### Steps to Reproduce (for bugs)
```
task createDockerfile(type: Dockerfile) {
    from 'redhat-registry.artifactory.kaloom.io/rhel:7.6-202'
    arg('HTTP_BIN=http://artifactory.kaloom.io/artifactoryhfh') 
    environmentVariable('DP_CODE_BASE','/opt/kaloom/src/flowfabric')
    runCommand('install -d /etc/kaloom /root/.docker /root/.ssh')
    //copyFile('./docker/entrypoint.sh', '/opt/kaloom/entrypoint.sh')
    workingDir('/opt/kaloom/')
    //defaultCommand('./entrypoint.sh')
}

task buildImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    tags.add('flowfabric/gradle-plugin-test:1.0')
}
```

### Your Environment
Running on my machine, Fedora 28

**Comment by bmuschko** [comment]
Are you sure you rebased correctly? Because the code indicates that the class has the annotation: https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerRegistryCredentials.groovy#L84. Also, the functional tests are green.

**Comment by llaforest** [comment]
Basically I just checked out the latest and it crashes. I am far from confident of my claim but I do not see what I'm missing if it's a code 12.
 Here is the top of my git log:
```
commit b80a981543538226593cdfb0319d3b0e757a71f3 (HEAD -> ISSUE-800, upstream/master, upstream/HEAD)
Author: Benjamin Muschko <benjamin.muschko@gmail.com>
Date:   Fri May 10 07:27:41 2019 -0600

    Mention breaking change

commit b31271ff223535efe8084770b98445da077df2e5
Author: Benjamin Muschko <benjamin.muschko@gmail.com>
Date:   Fri May 10 07:26:34 2019 -0600

    Add more documentation

commit 7114c0f1a1f96d3d340f0b27886e4efe2110edad
Merge: 9ccc454d 445b0fc7
Author: Benjamin Muschko <benjamin.muschko@gmail.com>
Date:   Fri May 10 07:15:14 2019 -0600

    Merge pull request #802 from bmuschko/bm/docker-client-on-demand
    
    Initialize and return Docker Java client on demand

```

**Comment by bmuschko** [comment]
What do you mean by "code 12"? Are you using Java 12? How are you testing this meaning how do you build the binary and use it in a sample project?

**Comment by llaforest** [comment]
Code 12 is just a way of saying the problem is 12 inch behind the keyboard. hehe
I build locally with assemble, publish to mavenlocal and run my sample project yes.

**Comment by bmuschko** [comment]
Wild guess: You are building a SNAPSHOT version and Gradle still uses the cached version.

Add the following and try again.

```
configurations.all {
    resolutionStrategy {
       cacheChangingModulesFor 0, 'seconds'
    }
}
```

If that's not your issue then I'll need to try it myself but I am not sure if I'll get to it until Monday.

**Comment by hugares** [comment]
I tried on my side and I have the same issue as Laurence reported.

**Comment by bmuschko** [comment]
I could reproduce the issue but still don't understand why it is happening. I did something similar before but for a plugin written in Java and not Groovy. I'd need to investigate more.

For now I reverted the change to what it was before: https://github.com/bmuschko/gradle-docker-plugin/commit/4936290f8935821976060e94115ddccf3e7a0f1d.

**Comment by cdancy** [comment]
Going to kick a new release today with the handful of these minor changes that have gone in unless I hear otherwise.

**Comment by llaforest** [comment]
Perfect, I will rebase on this and continue my work. Thanks!
