### ISSUE TITLE
Unable to find method 'org.gradle.api.model.ObjectFactory.directoryProperty()Lorg/gradle/api/file/DirectoryProperty;'.

### ISSUE THREAD

**Issue by jzoran05** [bmuschko/gradle-docker-plugin#805]
Used gradle:

plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.31'
    id 'application'
    id 'com.bmuschko.docker-java-application' version '4.8.0'
}

Error:

Unable to find method 'org.gradle.api.model.ObjectFactory.directoryProperty()Lorg/gradle/api/file/DirectoryProperty;'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by bmuschko** [comment]
You will need to use at least Gradle 5.1 to run the plugin (see [introduction chapter in user guide](https://bmuschko.github.io/gradle-docker-plugin/#introduction)).

**Comment by jzoran05** [comment]
So the plugin doesn't work with the gradle version provided with the latest version of intellij?

**Comment by bmuschko** [comment]
I don't think that IntelliJ provides an a Gradle runtime. You have to point it to either an installation of Gradle on your machine or to a [Gradle Wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html). You should always use the Gradle Wrapper which defines the compatible Gradle version for a project.
