### ISSUE TITLE
addShutdownHook leaks Gradle classloaders

### ISSUE THREAD

**Issue by ldaley** [bmuschko/gradle-docker-plugin#809]
Hi @bmuschko,

While investigating something else, I found a memory leak in this plugin.

https://github.com/bmuschko/gradle-docker-plugin/blob/b80a981543538226593cdfb0319d3b0e757a71f3/src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy#L164

These hooks are leaking the classloaders used to load the plugin, which can be very expensive. The only reliable solution here is to only register the hook when truly needed and remove the hook when it is no longer needed.

**Comment by ldaley** [comment]
This is actually leaking Project instances too, so is quite costly.

**Comment by breskeby** [comment]
I think the hook can also be registered in a less leaking way. currently the closure passed holds the reference to the task.

**Comment by breskeby** [comment]
having another look I wonder if it wouldn't be better to use gradle buildFinished hook here:

```
        // register buildFinished-hook to close kubernetes client.
        project.gradle.buildFinished {
            dockerClient.close()
        }
```

**Comment by cdancy** [comment]
@breskeby yeah that's not a bad idea. Folks can feel free to send in a PR to expedite this process!

**Comment by cdancy** [comment]
Actually ... think it _might_ be better to just attach it to the dockerClient itself:
```
dockerClient.addShutdownHook {
    dockerClient.close()
}
```
Looks a little silly writing it that way but we should only ever have one instance of the client so this should be OK. Thoughts? Or Maybe @breskeby suggestion above?

**Comment by breskeby** [comment]
I think the problem with the snippet above is that the closure passed down to the shutdown hook still leaks its owner (the task) which holds references to project etc. Also this would not be executed after a build finished when using a gradle daemon (the default in gradle) With the buildFinished hook we can ensure the references is removed once the build has finished.

**Comment by cdancy** [comment]
@breskeby that makes sense. Care to send in a PR?
