### ISSUE TITLE
On support for setting log-driver for DockerCreateContainer task

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#81]
This is mainly WRT this known issue:

https://github.com/docker/docker/issues/9139

Because we are using this plugin in a CI environment we are often running into OOM problems due to the way docker is handling, or not handling, logs. To get around this one can set '--log-driver=none' on the command line so docker is not saving the logs. We are already recording the logs anyway so it's not necessary for docker to keep these logs around and run out of memory. The docker remote api exposes this at HostConfig.LogConfig which can be found here:

https://docs.docker.com/reference/api/docker_remote_api_v1.19/#create-a-container

Is it possible we could expose this through the DockerCreateContainer task? Maybe something as simple as a variable 'disableLogging' which is set to false by default but if true will pass in the necessary json.

Thoughts?

**Comment by bmuschko** [comment]
I guess it could be added through the [HostConfig parameter](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java#L58) in Docker Java. If you send me a pull request for it I will merge.

**Comment by cdancy** [comment]
@bmuschko update: change has been made and committed to docker-java and now we are just waiting on a new release. Once that happens we will have to wait for you to re-base off of the updated docker-java and then I can make the change here.

https://github.com/docker-java/docker-java/issues/218

**Comment by cdancy** [comment]
@bmuschko looks like you just released 5 days ago but the new docker-java was released 3 days ago! Does the plugin pull in the latest docker-java library?

https://github.com/docker-java/docker-java/releases/tag/docker-java-2.0.0

**Comment by bmuschko** [comment]
I won't be able to get to it till next week. You might want to send a pull request to speed up the process.

**Comment by bmuschko** [comment]
I integrated the latest Docker Java version. You can go ahead and work on a pull request for this issue.

**Comment by cdancy** [comment]
@bmuschko I seen that and thank you! I've got the code teed up from a couple months ago. Let me pull the latest changes and look things over and send in a PR.

**Comment by cdancy** [comment]
@bmuschko thoughts?
