### ISSUE TITLE
Manifest information not to invalidate cache key

### ISSUE THREAD

**Issue by llaforest** [bmuschko/gradle-docker-plugin#816]
### Expected Behavior
It is usually good practice to have some kind of manifest in artefacts. One or many of the following: Version, Build Date, Build Id, Commit Id, etc... This kind of information changes all the time but it should not trigger a rebuild all the time.

To have such a thing in a docker image, it could be saved either as a manifest file, or in image labels for example. The manifest file is tricky because it must be part of the staging dir and it will invalidate the cache key all the time. The labels as we know them will also invalidate the build unless another type of labels is created...

Let's say there is a new property called 'notInvalidatingLabels' in DockerBuildImage, these labels would be added to the buildImageCommand.withLabels in the execution but they would not be tagged @input. This way we append the information to the image but only when it rebuilds.

Would this be accepted?

### Current Behavior
So far nothing can be added to an image without invalidating cache key.

**Comment by bmuschko** [comment]
I can think of multiple viable solutions here. I do not like the proposed solution in the PR as it will be very confusing to end users.

1. A user can disable up-to-date checking for any field that shouldn't be considered. Currently, I believe the `TaskInputs` or `TaskOutputs` API does not allow removing an existing input or output marker. That would be my preferable solution as it wouldn't require a code change to the plugin.
2. We remove the input annotation for that specific field. Any change to the values in the Map would not be considered for up-to-date checking.
3. Users with special needs will have to implement their own task. It's more work for the build author but the plugin stays multi-purpose.

**Comment by llaforest** [comment]
I like what you propose it is much more generic. I just have no idea how we could enable or disable annotations on demand from the gradle task that extends DockerBuildImage. I will do some research but if you know how let me know I could give it a try.

**Comment by hugares** [comment]
@bmuschko If I understand correctly, in option 2, you are suggesting to remove the @Input annotation on the existing `labels` field?

Would you be OK with that option as it would be easier/shorter than option 1 (which requires to implement a new feature in Gradle)?

**Comment by bmuschko** [comment]
> I like what you propose it is much more generic. I just have no idea how we could enable or disable annotations on demand from the gradle task that extends DockerBuildImage. I will do some research but if you know how let me know I could give it a try.

If it possible then via https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskInputs.html#getProperties--. My guess is that it only returns a copy of of the registered properties. You may want to write a super simple build script with a custom task that you try to modify. Either way it's probably worth it to open a question on the Gradle forum. Maybe I am missing something.

> For caching of layers, it is true that labels are the last layers so most of the image could be reused but I prefer to have the same image since they end up on artifactory as different artefacts all the time.

I see. I am planning to think about some other options. I'll be pretty busy with other work till next week though.

> @bmuschko If I understand correctly, in option 2, you are suggesting to remove the @Input annotation on the existing labels field?

That's correct. It comes with a tradeoff though. A change in labels would not trigger a rebuild of the task action which might or might not be desired. For example, you add a new label, the image isn't rebuilt and therefore the pushed image is still the same as before. Not sure if you would expect this to work differently.

**Comment by hugares** [comment]
Another option would be to allow DockerBuildImage properties to be overrided by removing `final` keyword and then it would be as simple as this for the build author to make remove a property from the up-to-date inputs:

```
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

class CustomDockerBuildImage extends DockerBuildImage {
	@Override
	@Internal
	MapProperty<String, String> getLabels() {
		super.getLabels()
	}
}
```

**Comment by llaforest** [comment]
In the PR #821 above, I removed `final` on all properties for consistency. In fact we only need it on `labels` but others might need it on other properties.

**Comment by bmuschko** [comment]
@hugares There's a good reason why these fields are `final`. We only want end users change the internal value of the property but not the wrapping object itself. I am not even sure if overriding the method + `@Internal` annotation would work properly. BTW: `@CacheableTask` isn't inherited so you'd also have to assign it to your subclass.

@llaforest Thanks for the work you are putting in but let's discuss viable solutions first before jumping to implementations aka PRs right away.

I am going to ask about it on the Gradle Slack channel about the best way forward.

**Comment by llaforest** [comment]
@bmuschko Yeah no problem with the work. I was under the impression you always prefer to have concrete stuff when discussing. These are small PR so it's not a big deal.

Why would you want to prevent user changing the wrapping? Isn't all this discussion about how to allow users to be able to change wrapping to affect behaviour?

About the @Cacheable it's good to know but it is no more annotated since the remote cache does not work.

**Comment by hugares** [comment]
> @hugares There's a good reason why these fields are final. We only want end users change the internal value of the property but not the wrapping object itself.

Do you mean that end users could change the wrapping object by calling the setter from their build script? something like:

```
task myTask (type: DockerBuildImage) {
    setLabels(...)
}
```

> I am not even sure if overriding the method + @Internal annotation would work properly.

I tested it and and it works, i.e. if I override `getLabels` and annotate with `@Input`, labels are considered in the upd-to-date check, if I override `getLabels` and annotate with `@Internal` (or no annotation), labels are ignored from the up-to-date-check.

I took this idea from the Gradle documentation: https://docs.gradle.org/current/userguide/build_cache.html#using_annotations

> BTW: @CacheableTask isn't inherited so you'd also have to assign it to your subclass.

I know but for now this is not an issue as `DockerBuildImage` only support up-to-date, not yet the cache so neither the `DockerBuildImage` class or the subclass has/need the `@CacheableTask` annotation.

> @llaforest Thanks for the work you are putting in but let's discuss viable solutions first before jumping to implementations aka PRs right away.

Sorry, this is my fault, I suggested him to do the PR in case you liked the idea, it would have been ready to merge. We were following Linus suggestion "Talk is cheap. Show me the code." :-) We will stop opening PRs until we agree on a way forward.

**Comment by hugares** [comment]
Continuing on the idea of the build authors defining their own DockerBuildImage(while waiting for a response on slack), we can use delegation instead of subclass if removing the final keyword from the properties is a no go.

Instead of extending the DockerBuildImage class and overriding the getter, we can create a Custom task which will redefine all the properties and delegate the calls to an internal instance of DockerBuildImage.

That way, no change have to be done on the DockerBuildImage task, but it is less friendly for the build authors.

**Comment by hugares** [comment]
Using delegation won't work as it is not allowed to instantiate a task from another task

**Comment by bmuschko** [comment]
> Why would you want to prevent user changing the wrapping? Isn't all this discussion about how to allow users to be able to change wrapping to affect behaviour?

For more info see https://docs.gradle.org/current/userguide/lazy_configuration.html#sec:unmodifiable_property.

> Sorry, this is my fault, I suggested him to do the PR in case you liked the idea, it would have been ready to merge. We were following Linus suggestion "Talk is cheap. Show me the code." :-) We will stop opening PRs until we agree on a way forward.

Usually, I would propose opening a PR for straightforward changes. This change seems to be more architectural and will potentially result in additional maintenance cost for the our plugin.

Let's summarize what I've learnt so far:

1. Gradle does not provide a way to remove a declared input from a property through the runtime API. [Not an option]
2. You can override the getter of a property and assign other annotations. This would require making the field non-final. [Low impact on plugin code]
3. A build author has to completely redefine the custom task [Heavy burden on end user, no impact on plugin code]
4. I played around with Groovy meta programming for redefining the method but that didn't work. [Not an option]

I guess 2. would be a compromise for both sides, plugin authors and consumers, though I'd only want to do that for that single field for now. I'll leave the final decision up to @cdancy and @orzeh who are the primary maintainers of the plugin.

**Comment by cdancy** [comment]
#2 would be the compromise but I personally dont care for it but I also dont have a better idea at the moment ;)

We can go with that as it's as low impact as we can get IMO.

@orzeh any thoughts?

**Comment by orzeh** [comment]
I don't have a strong opinion on that, but option 2 seems to be a good compromise.

**Comment by hugares** [comment]
@llaforest is on vacation so I could not amend is PR, that's why I created another one.
