### ISSUE TITLE
DockerBuildImage should not return null on up-to-date executions

### ISSUE THREAD

**Issue by stevendpclark** [bmuschko/gradle-docker-plugin#818]
### Expected Behavior
The contract to get the built imageId from the docker image is honoured if the DockerBuildImage task ran successfully by being able to query the "internal" getImageId() member in subsequent tasks. Such as was fixed within https://github.com/bmuschko/gradle-docker-plugin/issues/686
 
### Current Behavior
Seems like 4.9.0 broke this behaviour as I now get back null when the build task is considered up-to-date. Looks like https://github.com/bmuschko/gradle-docker-plugin/pull/807 might have introduced this breakage. 

From a very quick glance at the code within the outputs.upToDateWhen block it should read the image id from the file and set the imageId variable within it, since it's not the variable is never set.

### Context
We have a specific Dockerfile that we build within the gradle build to compile some C++ binaries for various linux versions. So the docker image itself will get compiled once, the first time but will be re-used/up-to-date on subsequent gradle executions as the docker image simply mounts the codebase the developers are editing within it.

Additional context:
Downgrading back to 4.8.1 version does not this problem, the DockerBuildImage task always runs and returns an imageId value.

### Steps to Reproduce (for bugs)
```
task buildDevEnvImage(type: DockerBuildImage) {
    def uid = new com.sun.security.auth.module.UnixSystem().getUid()
    def gid = new com.sun.security.auth.module.UnixSystem().getGid()
    def username = System.properties['user.name']

    inputDir = file('buildenv/')
    tags.add("${project.name}-build:latest")
    buildArgs = ['UID': "${uid}",
                 'GID': "${gid}",
                 'USERNAME': username]
}

task createDevEnvContainer(type: DockerCreateContainer) {
    def uid = new com.sun.security.auth.module.UnixSystem().getUid()
    def gid = new com.sun.security.auth.module.UnixSystem().getGid()

    dependsOn buildDevEnvImage
    targetImageId buildDevEnvImage.getImageId()
    autoRemove = true
    binds = ["${project.rootDir}": "${project.rootDir}"]
    user = "${uid}:${gid}"
    cmd = ['cat', '-']
    tty = true
}
```

### Your Environment
Latest Centos 7 + Docker version 18.09.6, build 481bc77156

**Comment by orzeh** [comment]
@stevendpclark thanks for reporting. Would you like to submit a PR?

**Comment by stevendpclark** [comment]
@orzeh Sure I could look into a fix.

Would the team be okay with my proposed fix of setting the variable within the up-to-date block from the contents of the file, or would another solution be preferable?

**Comment by llaforest** [comment]
This fix was part of my other pull request. I will make it available here. It's basically setting the imageId when the image is up-to-date within the upToDateWhen statement.
