### ISSUE TITLE
The ChangeLog in the user's guide still says version 4.9.0 is TBA

### ISSUE THREAD

**Issue by sschuberth** [bmuschko/gradle-docker-plugin#822]
### Expected Behavior

The ChangeLog should mention a release date for released version 4.9.0.

### Current Behavior

The ChangeLog says version 4.9.0 is "TBA".

**Comment by cdancy** [comment]
Hmmm ... not sure what you mean. Looking below I see the date:

https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/docs/asciidoc/50-changes.adoc#v490-may-25-2019

**Comment by sschuberth** [comment]
See https://bmuschko.github.io/gradle-docker-plugin/#change_log which still says "v4.9.0 (TBA)" for me.

**Comment by cdancy** [comment]
@sschuberth that is weird. Maybe the docs didn't get updated last release? @bmuschko any thoughts here? Nothing popped during release...

**Comment by bmuschko** [comment]
My guess is that the release was published before the release notes have been finalized. Release notes are pushed as part of the release process. I guess you could republish them if there's no breaking change in them that should only go out with the next release.

**Comment by cdancy** [comment]
Yeah that was probably me...

**Comment by cdancy** [comment]
Closing this ISSUE as it's a known fudge up on our side when the changelog is not updated prior to releasing. Thanks for reporting @sschuberth

**Comment by bmuschko** [comment]
The published documentation has been fixed with the release of 4.10.0.
