### ISSUE TITLE
How to run application in non ROOT user

### ISSUE THREAD

**Issue by biswajitpain** [bmuschko/gradle-docker-plugin#828]
task createDockerfile(type: Dockerfile) {
    def buildGitHash = "undefined"
    if ("CODEBUILD_RESOLVED_SOURCE_VERSION" in System.env) {
        buildGitHash = System.getenv("CODEBUILD_RESOLVED_SOURCE_VERSION")
    }

    destFile = project.file("${dockerBuildDir}/Dockerfile")
    from "openjdk:8-jre-alpine"
    maintainer "'"
    runCommand("addgroup -S one && adduser -S -G one one")
    environmentVariable("BUILD_GIT_HASH", buildGitHash)
    addFile("app.jar", "/home/one/app.jar")
    **switchUser("one")**
    runCommand("touch /home/one/app.jar")
    exposePort(8080)
    entryPoint("sh", "-c", "java \$JAVA_OPTS -Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom -jar /hone/one/app.jar")
}

### Expected Behavior
container should run in one user's privileges.

### Current Behavior

FAILURE: Build failed with an exception. 
 
* Where: 
Build file '/codebuild/output/src758433847/src/build.gradle' line: 167 
 
* What went wrong: 
A problem occurred evaluating root project 'pos-proxy'. 
> Could not find method switchUser() for arguments [one] on task ':createDockerfile' of type com.bmuschko.gradle.docker.tasks.image.Dockerfile. 
 
* Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
 
* Get more help at https://help.gradle.org 
 
BUILD FAILED in 19s 

### Your Environment

AWS code build

**Comment by orzeh** [comment]
@biswajitpain please look at our [User Guide](https://bmuschko.github.io/gradle-docker-plugin), in [section 2.5.1](https://bmuschko.github.io/gradle-docker-plugin/#modifying_instructions_of_a_dockerfile_task) you can find examples how to add various instructions to `Dockerfile` task. 

I think in your case you have to use generic `instruction`:
```groovy
task createDockerfile(type: Dockerfile) {
   instruction "USER not_root_user"
}
```

**Comment by bmuschko** [comment]
The task exposes an [explicit method](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html#user(java.lang.String)) for setting a user.
