### ISSUE TITLE
Possibility to specify docker credentials by task

### ISSUE THREAD

**Issue by rbuehlma** [bmuschko/gradle-docker-plugin#829]
With the latest version (4.10.0) of the plugin it does not seem to be possible to specify the registry credentials by task.

### Expected Behavior
It should be possible to specify the registry credentials on task basis.

### Current Behavior
If the registry credentials are defined in any task, they are used for all other docker tasks as well

### Context
While the image build should run locally, the push is done to a remote repository which requires an authentication.

### Your Environment
Gradle 5 with gradle-docker-plugin 4.10.0

**Comment by bmuschko** [comment]
If you look at the Javadocs, then you will find that many of the task types implement the interface `RegistryCredentialsAware`. For those types you can set specific credentials.

Examples:
- [DockerBuildImage](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html)
- [DockerPushImage](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.html)

You can also find [complete examples](https://github.com/bmuschko/gradle-docker-plugin/issues/714#issuecomment-491894905) in some of the other issues that were asked on the same topic. It probably requires better documentation. Let us know if you are interested in contributing.

**Comment by rbuehlma** [comment]
Thanks for the help. I did not know this syntax:
`credentials.username.set easDockerRegistryUsername`
This solve my issue.

**Comment by cdancy** [comment]
Just wired up something this morning for a similar use-case. Providing the snippet incase anyone stumbles upon this ISSUE and is looking for a quick win:
```
pushImage {
	registryCredentials = new DockerRegistryCredentials(url: pushImageRegistryUrl,
									username: pushImageRegistryUsername,
									password: pushImageRegistryPassword)

	imageName = pushImageRegistryRepo
	tag = pushImageRegistryTag
}
```
The `pushImage` task is an instance of `DockerPushImage` if that's not immediately obvious :)

**Comment by bmuschko** [comment]
@cdancy I think it would be better to provide a full example in the user guide.

**Comment by cdancy** [comment]
@bmuschko agreed. I'll put something together today for folks.
