### ISSUE TITLE
Disabling TLS issue

### ISSUE THREAD

**Issue by tdudgeon** [bmuschko/gradle-docker-plugin#83]
I'm having problems running with TLS disabled.The docs seem to assume you are running using boot2docker, which I'm not doing (using standard Linux approach).
I have these 2 environment variables defined:
DOCKER_TLS_VERIFY=0
DOCKER_TLS=no
and a configuration like this:

    docker {
        url = 'http://localhost:2375'
    }

but when I run the DockerBuildImage task its still looking for the certPath:

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    A problem was found with the configuration of task ':core-services/core-services-server:dockerImage'.
    > Directory '/home/timbo/.boot2docker/certs/boot2docker-vm' specified for property 'certPath' does not exist.

Could you clarify how to deal with this?

Thanks
Tim

**Comment by bmuschko** [comment]
I'd say set `docker.certPath` to null. This should happen automatically based on the the assigned URL. If the protocol is `http://` then always assign null. Interested in providing a pull request for this?

**Comment by tdudgeon** [comment]
Yes, explicitly setting docker.certPath to null did the trick. Thanks.

**Comment by bmuschko** [comment]
What version of the plugin do you use? In the latest version `.boot2docker/certs/boot2docker-vm` is not assigned automatically.

**Comment by bmuschko** [comment]
I am going to close the issue. This should be not happen anymore.

**Comment by tdudgeon** [comment]
I had been using 2.4.1

**Comment by bmuschko** [comment]
OK, I could not find the assignment in my code. I don't think that's where it was coming from.
