### ISSUE TITLE
If where is two or more dependency jars with same artefact name and version but different group id just one will be copied to libs folder in result image

### ISSUE THREAD

**Issue by comdiv** [bmuschko/gradle-docker-plugin#830]
Build two java maven jars with same artefact id and version,  but different groups. Assume both jars are named mylib-1.0.jar and for maven first will be X:mylib:1.0 and second Y:mylib:1.0

Add both of them as dependencies to java application. 

Build docker image with docker-java-application. 

### Expected Behavior
All dependencies will be copied in lib directory with some kind of ambiguity resolution in file names. 

### Current Behavior
It creates plain lib directory and only one mylib-1.0.jar will be there. So dependency is lost.

**Comment by comdiv** [comment]
Think that it's required to do something here : https://github.com/bmuschko/gradle-docker-plugin/blob/550a2a81c8e2c2c3933c2307eae31181811198a3/src/main/groovy/com/bmuschko/gradle/docker/utils/ConventionPluginHelper.groovy#L39

**Comment by bmuschko** [comment]
At the time of copying the file, Gradle only deals with file names so the group ID as unique information is already lost. A `Copy` or `Sync` task doesn't provide a way to deduplicate those file via https://docs.gradle.org/current/javadoc/org/gradle/api/file/DuplicatesStrategy.html. I cannot offer you any good advice here except for renaming the artifact. I don't think we'll want to write some deduplicating logic just for the purpose of this use case. That's really more the responsibility of Gradle core.

**Comment by cdancy** [comment]
@bmuschko hmmm ... I don't know. We _could_ iterate over the configurations files, resolve them locally one by one, and pass in that folder location to the copy-spec. We do something similar here for a similar use-case. Not sure if it will work as well here or not which is why I'm talking it out loud.

**Comment by bmuschko** [comment]
I personally wouldn't want to swallow the maintenance cost but feel free to implement. It's too bad that you can't pass in a custom `DuplicatesStrategy`. If that would be the case then any consumer could just implement it themselves. I believe at the moment I would _have_ to be part of the plugin code.

**Comment by cdancy** [comment]
Yeah that would be nice. I can feel the pain as it's not the clients/consumers fault that multiple artifacts have the same name but slightly different GAV coordinates. That's just bad luck to have to deal with that.

@comdiv just curious: what is your use-case and is this an internal artifact or something publicly available?

**Comment by comdiv** [comment]
It's real case.
It was 2 repositories with multi-module kotlin gradle projects.
Both of them has module `utils` 
One repository publish to maven `org.mycompany.foo:utils:0.1-SNAPSHOT`
And second was `org.mycompany.bar:utils0.21-SNAPSHOT`
When we create docker `./libs` contained `utils-0.1.jar` and `utils-0.21.jar` and all is OK

After some time version was graded to 1.0 for BOTH of them:
`org.mycompany.foo:utils:1.0` and `org.mycompany.bar:utils:1.0`
And after it we met random bug `ClassNotFound` and after not long investigations we have found
single random  `utils-1.0.jar` in `./libs`.

While it's not convient (for us) to make such naming and better is to rename to  `org.mycompany.bar:bar-utils:1.0` - it's generic problem while two independent vendor can (nothing prevent) two jars with same name and version.

So it's suggested to add DuplicateStrategy or better some renaming common logic to default implementation of Sync task in your plugin on one of following way:
1. Add normalized prefix from parent(s) directory name for jar with special delimiter for example - `org-mycompany-bar--utils-1.0.jar` for both of duplicates - this variant is better while it will 
2. Or just add numeric suffix such - `utils-1.0--02.jar` - it's simpler to implement but it will be more random-like and less informal

Thank you for quick resonse to issue

**Comment by klass-ivan** [comment]
Also affected by this.
Work-arounded by explicit `archivesBaseName`
```
// foo:bar:utils build.gradle
archivesBaseName = 'foo-bar-utils'
```
```
// baz:utils build.gradle
archivesBaseName = 'baz-utils'
```

**Comment by cdancy** [comment]
Aaaahhhh ... yeah this can pop in these cases. @klass-ivan @comdiv interested in sending in a PR to address this?

**Comment by bmuschko** [comment]
I am going to close this issue. The same behavior would show for any other `Copy` and/or archiving task and is not specific to this plugin. I do not want to maintain a de-duplication strategy `Copy` tasks as part of this plugin. for I'd suggest you open an [issue with the Gradle project](https://github.com/gradle/gradle/issues). @klass-ivan describes a viable way to tackle the situation.
