### ISSUE TITLE
Deprecation warning for DefaultTask.newOutputFile() in Gradle 5.4.1

### ISSUE THREAD

**Issue by bwaldvogel** [bmuschko/gradle-docker-plugin#831]
Gradle 5.4.1 logs a deprecation warning when using the `docker-remote-api` plugin in version `4.10.0`:

```
The DefaultTask.newOutputFile() method has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the ObjectFactory.fileProperty() method instead.
        at org.gradle.api.DefaultTask.newOutputFile(DefaultTask.java:53)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage.<init>(DockerBuildImage.groovy:176)
        at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage_Decorated.<init>(Unknown Source)
        […]
```

**Comment by cdancy** [comment]
Yeah there are others as well I've noticed during testing/etc. Lets leave this ISSUE open if only to remind ourselves of the things we need to clean up prior 6.0. If folks want to jump and attack these AOT however we'll always take a PR!

**Comment by bmuschko** [comment]
Originally, we held off on it as we still wanted to support Gradle 4.x. I believe we already made a change that requires Gradle 5.0 now so it's fine if we clean them all up. Unfortunately, the `Provider` API keeps on evolving heavily across multiple major version.
