### ISSUE TITLE
Symlinks in DockerBuildImage input directory are not preserved

### ISSUE THREAD

**Issue by hugares** [bmuschko/gradle-docker-plugin#837]
When the DockerBuildImage input dir contains symlinks, the symlinks are not sent to the docker daemon. This causes docker build to fail or it succeed but with missing symlinks depending if the DockerFile uses the expected symlinks directly of if it uses a folder containing the symlinks.

### Expected Behavior
The symlinks sould be sent as is to the docker daemon, same as what the native docker client does.

### Additional info
The root cause of this bug is in the docker-java library, a bug was already reported in upstream project: https://github.com/docker-java/docker-java/issues/532

**Comment by orzeh** [comment]
@hugares thanks for reporting! Let's wait for your changes in docker-java and then we can consume latest version here.

**Comment by hugares** [comment]
Sure. FYI, I already have the fix for docker-java library, I am just waiting for the maintainer to merge the first or 3 changes to upload 2nd and so on for 3rd (3 changes are, add test coverage, remove code duplication and fix symlink issue).

**Comment by hugares** [comment]
One functional test failed, I am looking into it, most likely related to another change that was done in the library.

**Comment by hugares** [comment]
I bisected and the here is the commit that causes the test failures: https://github.com/docker-java/docker-java/commit/32b4db656a428fa6cd1f5b64e124954e9d187130

**Comment by hugares** [comment]
If I understand the change correctly, the returned message is no longer JSON in some cases which breaks this plugin. Should we adapt or ask to revert the change?

**Comment by cdancy** [comment]
@hugares under what circumstances are things no longer in json? And what format are they in when not json? It may be we can work around this just need to understand the context better.

**Comment by hugares** [comment]
@cdancy I am not sure yet under what circumstances things are no longer in json. I was hoping that it would ring a bell for one of you guys :) I will keep investigating how this works and if this plugin should adapt to the library or if the change in the library should be reverted.

**Comment by cdancy** [comment]
@hugares I would open an issue and ask those guys and reference the above commit along with any data/examples you have.

**Comment by hugares** [comment]
@cdancy I opened an issue https://github.com/docker-java/docker-java/issues/1222 and also opened the MR to fix the issue. When my change is in and released, I will amend this MR

**Comment by cdancy** [comment]
@hugares awesome and thanks!

**Comment by hugares** [comment]
It's all good now, I amended my PR with version 3.1.4 and all the tests passed.

**Comment by orzeh** [comment]
Thanks @hugares! I'll take a look at evening.

**Comment by hugares** [comment]
When are you planning to release 5.0.0?

**Comment by bmuschko** [comment]
@cdancy @orzeh Can you create a new release? I don't have any other changes coming. You may want to finish https://github.com/bmuschko/gradle-docker-plugin/pull/835 for the 5.0.0 release as it is a breaking change.

**Comment by orzeh** [comment]
@bmuschko @cdancy I think multiple tags feature need still some work, so I would release 5.0 with what we have and continue working on that feature. I can do the release if you agree.

**Comment by bmuschko** [comment]
@orzeh -1 to merging an incomplete solution. I'd rather release without it.

**Comment by orzeh** [comment]
@bmuschko sorry, I wasn't clear. I don't want to include #835 in 5.0 release.

**Comment by cdancy** [comment]
If it's not in the release does a new release really warrant being a major bump? Maybe a new minor release would be better.

**Comment by cdancy** [comment]
Also ... I've been travelling the past couple weeks and still am until the end of this week so my responses may be delayed.

**Comment by cdancy** [comment]
Just getting back into the swing of things as I'm home now from vacation. With that said I see a lot of new windows users having issues when supplying paths to various things. I think it makes good sense to provide better support for windows users as a `5.0` requirement. We've got folks here hitting the same issues. I can do a search through our code base and see if it's easy enough to knock out but basically anywhere we are using `project.someFileMethod` replace with `new File("").getPath()`. That _should_ suffice though the devil is in the details.

**Comment by llaforest** [comment]
So will it be a minor release for this issue alone or does it go in the next 5.0 release with the improvement mentioned above?

**Comment by cdancy** [comment]
Probably just do a 5.0 since that is what we decided on. There will technically be breaking changes of a sort just nothing earth shattering as far as features are concerned.

**Comment by hugares** [comment]
Hi, I am back from vacation so that is why I did not reply for the last 2 weeks.

If there is still some changes that you would like to put in 5.0.0 that are not completed yet, are you open to create a "stable-4.10" branch to release 4.10.1 with my fix for the symlinks?

We are are in the progress of migrating all our builds from our internal docker plugin to this one and the only thing left blocking us is the symlink fix not being released.

**Comment by cdancy** [comment]
@hugares kicking release now.

**Comment by hugares** [comment]
Thanks!

**Comment by cdancy** [comment]
`5.0.0` is now available.
