### ISSUE TITLE
Remote paths fail on Git Bash (Windows) when copying to container

### ISSUE THREAD

**Issue by rkrisztian** [bmuschko/gradle-docker-plugin#838]
I use Docker Desktop for Windows (Version 2.0.0.3), and `gradle-docker-plugin` version `3.6.2`, as upgrading the plugin is not easy (forces Gradle 5 on every project we use), but based on the history of `DockerCopyFileToContainer`, I think the latest version would work the same way. Here is a sample Gradle build script snippet I tried in a test code:

```
		task copyTestResourceToContainer(type: DockerCopyFileToContainer) {
			targetContainerId { createContainer.containerId }
			hostPath = file 'src/test/resources/dummy-file.txt'
			remotePath = '/tmp'
		}
```

This code simply fails when I use Git Bash on Windows:

```
Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"Could not find the file C:\\Work\\projects\\my-plugin\\build\\junit8616686919012175066\\tmp in container e8f221f5aea956f39d4a7df2c759edfc2c9ef10e391587c082be57d61c91e59b"}
```

My biggest problem is: I can't work this around. Remote paths should never be relative to the local project path, so I don't understand the following line:

https://github.com/bmuschko/gradle-docker-plugin/blob/v4.10.0/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCopyFileToContainer.groovy#L89

**Comment by rkrisztian** [comment]
If I change your code the following way, it works:

```groovy
		def localRemotePath
		if (copyFileToContainer.remotePath instanceof Closure) {
			localRemotePath = copyFileToContainer.remotePath.call()
		} else {
			localRemotePath = copyFileToContainer.remotePath
		}

		containerCommand.withRemotePath(localRemotePath as String)
```

While it's definitely not the most perfect solution, the idea is to leave the remote path unchanged... Even a simple `new File(path)` assumes the wrong path about the remote location, rewriting it to `\\tmp`, which is still wrong for a Linux filesystem being the remote one.

**Comment by cdancy** [comment]
hmmm ... using a `new File()` _should_ in theory solve this problem and should have been in place all along. Not sure why we went this route to begin with. In either event your original example should succeed when using `new File()` right? I don't see how the wrong location can be assumed if you're using absolute paths either to/from the container regardless of the OS. So long as the path is correct docker should magically make it all work.

**Comment by rkrisztian** [comment]
If I remember correctly, `new File('/tmp' ). path` becomes `\\tmp`, which is wrong for me.

**Comment by cdancy** [comment]
Yeah you've got a point. That will become normalized to the execution environment which is not necessarily the same as what is within the container. Hmmm ... feels like, at least for remote path, we should simply honor whatever the user passes in and let that be it. Don't try to do any normalization one way or another.

**Comment by rkrisztian** [comment]
Thanks, @cdancy. In the meantime, I re-confirmed the above:

```none
λ echo 'public class Test { public static void main(String[] args) { System.out.println(new java.io.File("/tmp").getPath()); } }' > Test.java
λ "$JAVA_HOME/bin/javac" Test.java
λ "$JAVA_HOME/bin/java" Test
\tmp
```

**Comment by bmuschko** [comment]
@cdancy Are you planning to implement a fix for this? I don't currently see a course of action.

**Comment by cdancy** [comment]
@bmuschko would love to just haven't had the time. Github needs something like a JIRA backlog/integration to track these types of things :)

**Comment by bmuschko** [comment]
Looks like we haven't gotten any PRs for this from the community. I am going to close the issue for now.
