### ISSUE TITLE
Can't execute ./gradlew tasks --all with v4.1.0

### ISSUE THREAD

**Issue by tranpeter** [bmuschko/gradle-docker-plugin#839]
> gradle-docker-plugin-4.10.0 $ ./gradlew tasks --all
Downloading https://services.gradle.org/distributions/gradle-5.4.1-bin.zip
...................................................................................

Welcome to Gradle 5.4.1!

Here are the highlights of this release:
 - Run builds with JDK12
 - New API for Incremental Tasks
 - Updates to native projects, including Swift 5 support

For more details see https://docs.gradle.org/5.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :buildSrc:compileKotlin
w: /Users/ptran/Downloads/gradle-docker-plugin-4.10.0/buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/ShadedArtifactsPlugin.kt: (55, 13): 'setter for classifier: String?' is deprecated. Deprecated in Java

> Configure project :
No git repository found. Build may fail with NPE.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ptran/Downloads/gradle-docker-plugin-4.10.0/build.gradle.kts' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'com.bmuschko.gradle.docker.release']
> Failed to apply plugin [class 'org.ajoberstar.gradle.git.base.GrgitPlugin']
   > Could not get unknown property 'grgit' for root project 'gradle-docker-plugin' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s

**Comment by bmuschko** [comment]
You are not stating what you are trying to achieve or what you are running exactly. If you are tying to build the plugin then you'll need to have a checked out GitHub repository of this project. Meaning you'll have to have a `.git` directory on the root directory. Without it, it won't work as it's part of the release process.

**Comment by tranpeter** [comment]
Ok thanks. I just downloaded the v4.1.0 tar.gz source and tried to list out Gradle tasks.
