### ISSUE TITLE
Configure a container to continue running after build script finishes

### ISSUE THREAD

**Issue by bkeyser** [bmuschko/gradle-docker-plugin#841]
### Expected Behavior
A container may be configured to allow it to remain running after the build script has stopped.

### Current Behavior
When the build script finishes, the container is stopped and optionally removed.

### Context
Gradle, along with the com.bmuschko.docker-remote-api plugin, are being used to create a cloud environment.  The container launched through the script is needed by additional initialization tasks once the Gradle script is complete.

**Comment by cdancy** [comment]
@bkeyser can you provide some more context here? Once you kick a task to run a container there is nothing in this plugin that will tear things down auto-magically. The only way I can see this happening for you is that you have something tearing things down or the container is built/wired-up to only run for some given amount of time and then exit.

**Comment by bkeyser** [comment]
@cdancy yeah, ummm, this is one of those easy problems to solve as it has to do with the individual rather than your fine library.  I made a mistake in my usage and should have also been a little more patient.  Thanks for your quick response and not pointing out that more than likely the problem is PEBKAC (problem exists between keyboard and chair)

**Comment by cdancy** [comment]
No worries and glad you figured it out. One should never assume anything as it's entirely possible it's _something_ that was over looked on accident. We are humans after all ;)
