### ISSUE TITLE
No support for running containers in detached mode 

### ISSUE THREAD

**Issue by pierrepook** [bmuschko/gradle-docker-plugin#842]
Hi, I would like the ability to run containers in detached mode. Some containers I pull down from DockerHub require the container to only be run with the -d flag 

### Current Behavior
Need to use command line gradle argument to run in detached mode

### Context
Some docker images from docker hub require containers to be started in detached mode. From the API for the DockerCreateContainer there is no support for it but I believe although I may be wrong here that the java docker API seems to support it

**Comment by bmuschko** [comment]
Care to send a pull request?

**Comment by pierrepook** [comment]
Yh sure, don't have much time in the next 2 weeks but will get in after that. The detached mode is only available on  `ExecStartCmd` and not  on `StartContainerCmd` that is used in `DockerStartContainer`. So plan would be to create a new class `DockerExecStartContainer` that extends `DockerExistingContainer `which is very similar to `DockerStartContainer  `but uses `ExecStartCmd `

**Comment by bmuschko** [comment]
Were you planning on contributing this change? If not, I am going to go ahead and close the issue.

**Comment by cdancy** [comment]
Closing issue for now as there hasn't been any response. If folks would like to contribute a PR for this functionality we'd be more than willing to review.
