### ISSUE TITLE
gradle-docker-plugin fails on ppc64le

### ISSUE THREAD

**Issue by rashmi-sakhalkar** [bmuschko/gradle-docker-plugin#844]
### Expected Behavior
Want to build the gradle-docker-plugin on ppc64le vm.

### Current Behavior
Caused by: java.lang.RuntimeException: Unhandled architecture/OS: ppc64le-Linux
	at org.newsclub.net.unix.NarSystem.getAOLs(NarSystem.java:110)
	at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:30)

### Context
The gradle project I am working on has dockerize image tasks.

### Steps to Reproduce (for bugs)
How can have the plugin working on ppc64le ?

### Your Environment
ppc64le

**Comment by bmuschko** [comment]
I am pretty sure the [junix dependency](https://github.com/kohlschutter/junixsocket) is a transitive dependency of Docker Java. I'd try to ask there to support your architecture/OS. There's nothing we can do in this plugin at the moment until it hasn't been fix in the library, published and consumed by Docker Java.
