### ISSUE TITLE
DockerCreateContainer with binds doesnt work on windows

### ISSUE THREAD

**Issue by pierrepook** [bmuschko/gradle-docker-plugin#845]
**OS : windows 10
gradle : v5.5** 

Using binds when creating a task of type 

> DockerCreateContainer 

fails on windows. I keep getting an error to do with "invalid volume specification: '/host_mnt/c/..." . I have tried using the same path when running docker manually from the command line with the **-v** flag and it works fine but with the plugin it errors out every time. 

I want to mount the project build directory and have tried using 

> getAbsolutePath

 and many other different iterations but every time it still errors out. The only time it does work is if i give it a random name like 'foo' 

**Expected Behavior** 

`it.bind = [project.getProjectDir().getAbsolutePath(): "/opt/var/"`

No error and binds the path correctly

**Current Behavior** 

`it.bind = [project.getProjectDir().getAbsolutePath(): "/opt/var/"`

errors out 
Manually hard coding the host directory path to the build directory still doesn't work either 

defining volume mounts doesnt work either
```

it.privileged = true
def volumeMounts = [:]
volumeMounts["C:/DirToMount"] = "/opt/var/"
it.stdinOpen = true
it.binds = volumeMounts
it.tty = true
```

But still no luck

Any help with solving this issue would be much appreciated!

**Comment by cdancy** [comment]
I suspect this has more to do with the fact that we are using `project.get**` calls which expects the paths to be relative to the project dir. If you use something which is relative to the project dirs does that work?

**Comment by pierrepook** [comment]
Tried that. Still the same issue unfortunately

**Comment by pierrepook** [comment]
If I give it the relative path it gives me an error saying the volume name is not valid for the regex and tells me to use absolute path. It seems like if you don't give it an absolute path it assumes its a volume name, and any slashed cause the regex to fail

**Comment by pierrepook** [comment]
Ok so found a solution. If you specify the path as `/host_mnt/c `then it works. If you specify the full windows path such as 

> `C:/.... `

 it fails. The Binds.parse in DockerCreateContainer is parsing on `:` so having a a windows path with `C:` breaks the binds mechanism. 

```
List<Bind> createdBinds = binds.get().collect { Bind.parse([it.key, it.value].join(':')) }
            containerCommand.hostConfig.withBinds(createdBinds)
```

**Comment by cdancy** [comment]
aaahhh ... interesting... and makes sense. Care to send in a PR to fix this?

**Comment by pierrepook** [comment]
Yh sure, don't have much time in the next 2 weeks but will get in after that

**Comment by bmuschko** [comment]
Closing as this issue didn't get any traction. Feel free to open if you are willing to contribute a pull request.
