### ISSUE TITLE
ApplicationPlugin configuration is orthogonal to DockerJavaApplicationPlugin cofiguration.

### ISSUE THREAD

**Issue by fearthewildllama** [bmuschko/gradle-docker-plugin#846]
```DockerJavaApplicationPlugin``` doesn't really rely on any of  the work that the ```ApplicationPlugin``` (and ```DistributionPlugin```) does. That means that using any of the [handy configuration](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.JavaApplication.html) available for those plugins won't affect the final Docker image.

I'd like to put a PR out that uses [JavaApplication:applicationDistribution](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.JavaApplication.html#org.gradle.api.plugins.JavaApplication:applicationDistribution)'s ```CopySpec``` to drive the Docker image generation ```COPY``` commands, and set the entry point to the script provided by the ```ApplicationPlugin```. Any thoughts?

### Expected Behavior
The `distTar`, `distZip`, and Docker image should all be the same, applying any customizations supported by the `ApplicationPlugin` and the `DistributionPlugin`.

### Current Behavior
The `distTar`, `distZip`, and Docker image should all be the same, applying any customizations supported by the `ApplicationPlugin` and the `DistributionPlugin`.

### Context
This code will cause the folder `properties` to be copied from the source tree into the application distributions `distTar` and `distZip`.

```gradle
apply plugin: 'application'
apply plugin: 'com.bmuschko.docker-java-application'

application {
    applicationDistribution.from("properties") {
        into "properties"
    }
}

```

However, that folder won't make its way into the Docker image.

Letting the ```ApplicationPlugin``` call the shots should also make customizing startup and JVM args easier, since that plugin natively supports it.

### Your Environment
Gradle 5.5.1 and ```com.bmuschko:gradle-docker-plugin:4.10.0```

**Comment by bmuschko** [comment]
The plan is to get rid of the dependence on the Gradle core application plugin. I just haven't gotten around to delete the last portion of it. There are various reasons that led to the decision:

1. We took advantage of Docker layer caching.
2. Less work needed to produce an image e.g. the JAR file doesn't have to be built.
3. Issues with injecting system properties/environment variables into the generated scripts.
4. Code alignment with the Docker plugin for better maintenance. In this end, there will likely just be one.

So from my end end it's a -1 to heavily depend on the Gradle core application plugin.

**Comment by bmuschko** [comment]
I removed the last remnants of the Application Plugin which will be shipped with the next release.
