### ISSUE TITLE
allow to keep out springboot devtools from docker image

### ISSUE THREAD

**Issue by abendt-mhp** [bmuschko/gradle-docker-plugin#849]
we're using spring devtools. we have added it according to the documentation (https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html). when using springboot gradle plugin (_bootJar_) the devtools jar will not end up in the resulting JAR and thus will only be used locally. when using the docker plugin the devtools jar will end up in the docker image.

### Expected Behavior

it would be nice, if the docker gradle plugin would behave here in line  with the springboot gradle plugin: if devtools are added as described in the doc they are not packaged into the docker image.

### Current Behavior

the devtools jar is packaged into the resulting docker image.

### Context

we are migrating a spring boot app from JAR deployment to a docker based deployment.

### Steps to Reproduce (for bugs)

i updated the sample from the other issue report #848 
https://github.com/abendt/gradle-dockerplugin-resources-bug

* build a bootJar: `gradlew bootJar`
* note that devtools does not end up in the jar: `unzip -l build/libs/*.jar`
* build a image: `gradlew dockerBuildImage`
* start the container
* run a shell in the container: `docker exec -ti <containerId> /bin/sh`
* note that the devtools jar is present in the container: `find . -name "*devtools*"`

### Your Environment

```
$ gw --version
Using gradle at '/Users/abendt/Projects/spring-docker-resources/gradlew' to run buildfile '/Users/abendt/Projects/spring-docker-resources/build.gradle.kts':


------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------

Build time:   2019-07-10 20:38:12 UTC
Revision:     3245f748c7061472da4dc184991919810f7935a5

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.2 (Azul Systems, Inc. 11.0.2+9-LTS)
OS:           Mac OS X 10.14.6 x86_64
```

**Comment by bmuschko** [comment]
Pretty much the same answer applies as mentioned here: https://github.com/bmuschko/gradle-docker-plugin/issues/848.

**Comment by hesch** [comment]
Just for reference, you can exclude the devtools by specifing this in your build.gradle:
```
dockerSyncBuildContext {
    exclude '**/spring-boot-devtools-*.jar'
}
```
