### ISSUE TITLE
[q] how to pass "-D" debug argument to docker invocation

### ISSUE THREAD

**Issue by n0mer** [bmuschko/gradle-docker-plugin#85]
Benjamin , thanks for great work - plugin is working for me in terms of building spring-boot ready application wrapped as a docker image.

Now i'm trying to push it to docker hub, but getting error "The push refers to a repository [n0mer/my-backend] (len: 1)."

Hope that debug output from docker command might help to troubleshoot this issue, so can you please suggest how to configure `docker-remote-api` plugin to add "-D" command-line argument to docker command?

**Comment by bmuschko** [comment]
What you are seeing as output at the moment is handled by a class of mine that logs the web services responses with the Gradle logger. I am currently not logging everything. You can provide an implementation of your own [ResponseHandler](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy#L68) that logs everything.

**Comment by bmuschko** [comment]
I am going to close the issue. The `ResponseHandler` should get you where you want to be.

**Comment by n0mer** [comment]
for the reference, in case someone else will face the same error - i was trying to push image to docker hub, and my repository was created as "automated build".

Here is corresponding ticket in docker-hub tracker https://github.com/docker/hub-beta-feedback/issues/134
