### ISSUE TITLE
provide JAVA_OPTS environment variable for later configuration during deployment 

### ISSUE THREAD

**Issue by jonnybbb** [bmuschko/gradle-docker-plugin#853]
#

Currently the parametrisation (eg jvmArgs) of the java / springboot application is done during docker image file creation. A workaround with some custom instructions is described in  #711. Out of the box support for the docker-spring-boot-application plugin would be awesome.

### Expected Behavior

More flexibility during deployment time, eg in a Kubernetes cluster, could be achieved if a  environment variable (eg `$JAVA_OPTS`) would be part of the java `ENTRYPOINT`. This is especially useful for configuring the same docker image in different environments. The resulting docker file might look like this:

```dockerfile
ENTRYPOINT exec java $JAVA_OPTS -XX:+UseG1GC -cp /app/resources:/app/classes:/app/libs/* main.Application
```
### Current Behavior

An option is missing to provide jvmargs to the java process of the docker image during deployment time eg in kubernetes. 
 
```yaml
env:
            - name: JAVA_OPTS
              value: -Xmx256m 
```

### Workaround
`JAVA_TOOL_OPTIONS` can be used to provide these parameters to the java process via a environment variable, but it might not always be appropriate since those might be overridden by some command line parameters.

**Comment by bmuschko** [comment]
I can think of two other options here:

1. Set a value for the environment variable `_JAVA_OPTIONS` which is read by the JVM automatically.
2. Modify or completely replace the default `ENTRYPOINT` instruction created by the plugin as [described in the user guide](https://bmuschko.github.io/gradle-docker-plugin/#modifying_instructions_of_a_dockerfile_task).
3. I haven't tried it but couldn't use just assign the following? `jvmArgs = ['JAVA_OPTS', '-XX:+UseG1GC']

**Comment by jonnybbb** [comment]
> 1. Set a value for the environment variable `_JAVA_OPTIONS` which is read by the JVM automatically.

works - but probably not the best choice either - that's why [JAVA_TOOLING_OPTIONS](https://bugs.openjdk.java.net/browse/JDK-4971166) have been introduced. 

> 2. Modify or completely replace the default `ENTRYPOINT` instruction created by the plugin as [described in the user guide](https://bmuschko.github.io/gradle-docker-plugin/#modifying_instructions_of_a_dockerfile_task).

that's what I actually come up with. Modifing the entrypoint without access to the elements of the list is not very handy and result into ugly string replacements.  

> 3. I haven't tried it but couldn't use just assign the following? `jvmArgs = ['JAVA_OPTS', '-XX:+UseG1GC']`
>> You can specify a plain string for the ENTRYPOINT and it will execute in /bin/sh -c. This form will use shell processing to substitute shell environment variables

substitution of environment variables will only work in a plain [ENTRYPOINT](https://docs.docker.com/engine/reference/#shell-form-entrypoint-example) string. 

**Possible solution:** 
1. extend docker-spring-boot-application api to allow setting environment variables to be passed to the java prozess
2. detect environment variables in the jvmArgs. This will then result in using the plain `ENTRYPOINT exec java ....` instead of `ENTRYPOINT ["java", ...]`.      

Let me know if you see any benefit in extending the plugin for that feature and I will make a PR for that. I will add the `JAVA_TOOLING_OPTIONS`  and  `_JAVA_OPTIONS` into the documentation via a PR anyway. Otherwise feel free to close this issue, since some of the described solutions here will probably work in most of the use cases.

**Comment by bmuschko** [comment]
For now I'd like to avoid adding more logic to those plugins as there are viable ways to implement the use case. Of this would have to be tested and maintained moving forward. We can reconsider if more people speak up about this particular use case.
