### ISSUE TITLE
Issue with Daemon on Windows 10 

### ISSUE THREAD

**Issue by neilchaudhuri** [bmuschko/gradle-docker-plugin#854]
This is not a bug report but rather a request for clarification.

### Expected Behavior
The plugin should be able to build an image on Windows 10 without the need to expose the daemon on tcp://localhost:2375 without TLS.

### Current Behavior
The plugin fails with 

`com.bmuschko.gradle.docker.shaded.org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:2375 [/127.0.0.1] failed: Connection refused: connect`

when the daemon is not exposed on tcp://localhost:2375 without TLS, which makes sense.

### Context
I am unable to build an image of a Spring Boot application on Windows 10.

### Steps to Reproduce (for bugs)
There is no need as the issue is addressed somewhat in the documentation, and I am simply seeking further clarification.

### Your Environment
Windows 10 with Docker installed (including Docker Desktop).

The documentation mentions that the default daemon URL is not supported by the plugin and falls back to the TCP URL, which is only exposed when I explicitly check the box doing so in Docker Desktop. The thing that's confusing is that the fabric8 Maven plugin can build images without that TCP URL exposed. Is this simply a matter of this Gradle plugin not supporting a case that the fabric8 Maven plugin does (using [this code](https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/access/DockerConnectionDetector.java#L123))? Is there any configuration that will enable me to use this plugin on Windows 10 without altering any Docker daemon defaults?

**Comment by orzeh** [comment]
@neilchaudhuri the issue is with `docker-java` library which we use in this plugin to talk to Docker daemon. See #769 for details.
