### ISSUE TITLE
How to do "docker run ..."?

### ISSUE THREAD

**Issue by PerMildner** [bmuschko/gradle-docker-plugin#857]
Is there a way to do what "docker run ..." does, using these plugins?

Currently my shell script creates the image `go-unit-tests`  (without pushing it to a repository) and then does (the two last args are passed to the ENTRYPOINT executable specified in the Dockerfile):

`docker run --rm -v /tmp/my_coverage_data:/tmp/coverage_data go-unit-tests -coverprofile /tmp/coverage_data/.coverage.out`

I want to migrate my shell scripts to Gradle so I need a way to emulate these "docker run ..." invocations.

I do not use the Java or Spring plugins.

I am new to this plugin, Gradle and to Docker so maybe I am just missing something obvious, like the correct documentation.

**Comment by orzeh** [comment]
@PerMildner please read the [user guide](https://bmuschko.github.io/gradle-docker-plugin/#executing_functional_tests_against_a_running_container).

**Comment by PerMildner** [comment]
@orzeh Thanks for the pointer. I read the section you referred to but I could not get that to work (#858).
