### ISSUE TITLE
Feature Request: DockerBuildImage remote context

### ISSUE THREAD

**Issue by juwi** [bmuschko/gradle-docker-plugin#860]
### Expected Behavior

Besides consuming a folder hosting the build context, Docker also supports downloading a tar file containing the context from e.g. a webserver, which sadly this plugin does not seem to support at this time (unless I'm doing it wrong).

### Current Behavior

Currently only local build contexts supplied as a folder seem to be supported.

### Context

For building in a distributed environment I want a controlled set of Docker Daemons used for building. My idea is to have the gradle build prepare the context, then tar it and expose it via SimpleHTTPFileServer. Then I'd like to pass that link on to the Docker Build via the DockerBuildImage task.

### Your Environment

Kubernetes

**Comment by juwi** [comment]
I've gone ahead and built a prototype here: https://github.com/juwi/gradle-docker-plugin/tree/feature/buildWithTarContext

**Comment by cdancy** [comment]
Very interesting... Looking over things now...

**Comment by bmuschko** [comment]
If you happen to open a PR please make sure to cover all test cases e.g. now that you made both fields `@Optional` you should handle the case where both fields have null values.

**Comment by bmuschko** [comment]
Were you still planning to send a PR for this?

**Comment by bmuschko** [comment]
I am going to close the issue for now as we haven't heard back in a while. Let us know if you are still planning to provide a PR for this. Happy to reopen the issue.
