### ISSUE TITLE
Add support of ipcMode to DockerCreateContainer

### ISSUE THREAD

**Issue by jberglund-BSFT** [bmuschko/gradle-docker-plugin#861]
Would like to see support of ipcMode added
This is an existing setting in the docker-java HostConfig:
https://github.com/docker-java/docker-java/blob/master/docker-java/src/main/java/com/github/dockerjava/api/model/HostConfig.java#L1140

Docker run reference:
https://docs.docker.com/engine/reference/run/#ipc-settings---ipc

This would be a minor change, something like https://github.com/jberglund-BSFT/gradle-docker-plugin/commit/0d0b39d2642be71a0e364d9860ed3b0d833ea6e0

### Expected Behavior
Able to set the ipcMode

### Current Behavior
Not able to set the ipcMode

### Context
Need to be able to set the ipcMode to share memory segments for an in-memory database running in a sidecar.

### Steps to Reproduce (for bugs)
(not a bug)

### Your Environment
(not a bug)

**Comment by jberglund-BSFT** [comment]
also interested in adding sysctls

**Comment by cdancy** [comment]
@jberglund-BSFT care to send in a PR? If so I would break things up into multiple PR's for each feature requested to making reviewing easier.

**Comment by jberglund-BSFT** [comment]
@cdancy would love to, was intending that the PR template asked for an issue first. PR coming shortly.

**Comment by cdancy** [comment]
Sounds good. Looking forward to it.

**Comment by bmuschko** [comment]
@jberglund-BSFT Can you please move the relevant properties into an inner class called `HostConfig` similar to `LogConfig` and `ExposedPort`? A flat list of properties simply isn't maintainable.

**Comment by jberglund-BSFT** [comment]
> @jberglund-BSFT Can you please move the relevant properties into an inner class called `HostConfig` similar to `LogConfig` and `ExposedPort`? A flat list of properties simply isn't maintainable.
Do you want all the existing hostConfig properties moved there too, or just new ones?

**Comment by bmuschko** [comment]
> Do you want all the existing hostConfig properties moved there too, or just new ones?

Yes, absolutely. If there are other ones that actually belong to `HostConfig` then they should move as well.

**Comment by jberglund-BSFT** [comment]
@bmuschko Do you want the DockerCreateContainer task configuration to contain a `hostConfig` input  and move the properties there, breaking any backwards compatibility?

**Comment by bmuschko** [comment]
@jberglund-BSFT Yes, please. We'll bump up the version appropriately. Let's not go through a deprecation cycle just for this.

**Comment by jberglund-BSFT** [comment]
@bmuschko I'm having some trouble figuring out how to nest the hostConfig in a way that makes sense. Does this need to be an Extension (in order to use DSL)? I tried marking the property with `@Nested` but gradle complains that it can't set the property to an instance of a closure. The LogConfig and ExposePorts examples appear to prefer method constructors, and hostConfig will be quite large especially if we end up fleshing it out for all the 60+ supported properties, I think that will not be very intuitive. Perhaps you can suggest what the basic declaration/get/set for hostConfig should look like.

**Comment by bmuschko** [comment]
@jberglund-BSFT Yes, you'd go with an instance of `HostConfig` annotated with `@Nested`. Here's roughly the code in Java:

```
private final Property<HostConfig> hostConfig;

public DockerCreateContainer() {
    ObjectFactory objects = getProject().getObjects();
    hostConfig = objects.property(HostConfig.class);
}

@Nested
public Property<HostConfig> getHostConfig() {
    return platform;
}
```

I don't understand "gradle complains that it can't set the property to an instance of a closure". Where exactly would you use a `Closure`?

`HostConfig` will have individual fields annotated with `@Input`. Those can be set via the `Property` methods.

**Comment by jberglund-BSFT** [comment]
OK, thanks, I tried this syntax you fed me above, but I think I am missing something more fundamental on the build.gradle implementation of it. Syntax like -
```
   [... more docker create container config]
                containerName = "$uniqueContainerName"
                hostConfig = {
                  portBindings = ['8080:8080']
                }
                cmd = ['/bin/sh']
```
Results in gradle trying to set the host config with a closure and that error I mentioned, but which is essentially exactly what I want to do - feed it natural list of hostConfig that can be moved from the root config to the hostConfig on upgrade. Some nuance I am missing.

**Comment by bmuschko** [comment]
You are currently assigning a Closure to `hostConfig` (by using the equals sign), however, its type is `Property<HostConfig>` so that won't work. At the very least you will need to remove the `=` sign as you want to delegate the calls within the Closure toward the underlying object.

You will also want to add the following. Forgot to mention that, at least if you wanted to configure it with the help of a Closure.

```
public void platform(Action<? super HostConfig> action) {
    action.execute(hostConfig);
}
```

If I have time over the weekend, I might create an initial change that moves the existing properties as proposed. I will need to play around with the API myself a little bit. Getting a bit rusty.

**Comment by bmuschko** [comment]
I created a PR for extracting the `HostConfig`: https://github.com/bmuschko/gradle-docker-plugin/pull/873.
