### ISSUE TITLE
DockerBuildImage.cacheFrom throws NoClassDefFoundError

### ISSUE THREAD

**Issue by PM055897** [bmuschko/gradle-docker-plugin#863]
### Expected Behavior
When I use DockerBuildImage.cacheFrom, it should retrieve docker images to consider as cache sources.

### Current Behavior
Currently, inside a custom gradle task that I have created to use class DockerBuildImage, I add the cacheFrom.add(someTag) property. It throws an exception as follows:

_Could not initialize class com.github.dockerjava.core.util.CacheFromEncoder_

Stacktrace shows 
_Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.core.util.CacheFromEncoder_

### Steps to Reproduce (for bugs)
In build.gradle file, import the DockerBuildImage class.
Register a task using that imported class to build the docker image.
Use cacheFrom.add(someTag)

**Dockerfile**
FROM oraclelinux:6.9 as someName

**build.gradle**
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
tagName = "dockerTagName"
tasks.register("someTask", DockerBuildImage) {
target = "someName"
tags.add(tagName)
cacheFrom.add(tagName)
}

### Your Environment
OS : macOS High Sierra v10.13.6
Gradle wrapper version : 5.6.2
Plugin version : bmuschko.docker-remote-api , 5.1.0. Also tried with version 4.10.0

**Comment by cdancy** [comment]
Interesting ... we have tests which cover this scenario but don't pop. Is the snippet you posted above enough to reproduce the issue? If not can you provide a fully reproducible snippet?

**Comment by bmuschko** [comment]
I can't reproduce the issue with the following build script:

```
plugins {
    id 'com.bmuschko.docker-remote-api' version '5.1.0'
}

import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

def tagName = "docker"

tasks.register("someTask", DockerBuildImage) {
    inputDir = projectDir
    target = "someName"
    tags.add(tagName)
    cacheFrom.add(tagName)
}
```

Seems to work fine.

```
$ gradle sT

> Task :someTask
Building image using context '/Users/bmuschko/dev/tmp/test'.
Using tags 'docker' for image.
Step 1/1 : FROM oraclelinux:6.9 as someName
 ---> 8deb00ba1b3a
Successfully built 8deb00ba1b3a
Successfully tagged docker:latest
Created image with ID '8deb00ba1b3a'.

BUILD SUCCESSFUL in 883ms
1 actionable task: 1 executed
```

Please provide a reproducible example if you are still having issues.

**Comment by mjdamman** [comment]
It's reproducible with the above example with Java 11.

`
Execution failed for task ':someTask'.
 javax/xml/bind/annotation/XmlElement
`

Possible solution -> https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by bmuschko** [comment]
@mjdamman The root cause of the issue you are reporting is different from the original issue reported here. Therefore, please open a new issue. The issue you are reporting is specific to using Java 11 as the runtime version. You are facing the issue as [Docker Java does not declare the needed dependencies as transitive dependencies](https://github.com/docker-java/docker-java/issues/1244). We could probably declare those dependencies here but we'd have to put a lot of tests in place to ensure that the plugins still works with earlier versions of Java.

**Comment by cdancy** [comment]
@bmuschko when using the "docker java shaded" lib I put together many moons ago I was packaging this dependency, maybe others, in for these very purposes. Might make sense to spin up a PR with this change to see how things fare?

**Comment by bmuschko** [comment]
@cdancy I'd rather have Docker Java define the dependencies and the required versions. In the end it has to be compatible with their API, not ours. Adding it in our plugin is rather a workaround I'd say. 

I remember that we had to ask the Docker Java project through some channel somewhere to get a new feature or release. I would suggest we try that first and see what their plans are. Do you remember how to reach out to them?

**Comment by cdancy** [comment]
I'll reach out to them now on gitter and see what their opinions are. The problem I suspect is that because this is only an issue with jdk11 users, and with most projects that I've seen not even adopting things beyond 8, this may be a tough sell.
