### ISSUE TITLE
[q] is it possible to specify certificate file names ?

### ISSUE THREAD

**Issue by n0mer** [bmuschko/gradle-docker-plugin#87]
Hi,

currently it is possible to set certPath.

But is there any way to set certificate names?

Currently i have to symlink, so files will have proper names:

$ ls -l ~/temp/cert
total 0
lrwxrwxrwx 1 ubuntu ubuntu 18 Jul 24 14:21 ca.pem -> /etc/docker/ca.pem
lrwxrwxrwx 1 ubuntu ubuntu 22 Jul 24 14:21 cert.pem -> /etc/docker/server.pem
lrwxrwxrwx 1 ubuntu ubuntu 26 Jul 24 14:21 key.pem -> /etc/docker/server-key.pem

**Comment by bmuschko** [comment]
I don't think I quite understand the question. Why don't you just say `new File('/etc/docker/ca.pem')`?

**Comment by bmuschko** [comment]
Never mind. I understand. No, at the moment there's no way to change the behavior. This is hard-coded in the Docker Java library. You'd have to ask there.
