### ISSUE TITLE
Trouble with up-to-date detection

### ISSUE THREAD

**Issue by hnine999** [bmuschko/gradle-docker-plugin#871]
### Expected Behavior

The original bug presented itself as follows:
Dockerfile modified
build updates docker image
repeated builds are up-to-date

### Current Behavior

The original problem was:
Dockerfile modified
build updates docker image
build again updates docker image (should be up-to-date)
build is up-to-date

So, there was a single-build delay for the build to be up-to-date

However, in the PR I've submitted, afaict the build is never up-to-date

Update 16 Oct 2019:
Upgraded gradle-docker-plugin from 5.1.0 to 5.2.0 (committed).  No change.
Downgraded gradle version (via gradle wrapper) from 5.6.1 to 5.1.1 (not committed).  No change.

### Context

Want to rebuild images only from modified Docker-files. Some of the Docker-files take a long time to process, so rebuilding images from unmodified Docker-files is undesirable.

### Steps to Reproduce (for bugs)

Made a PR (#870)-- NOT TO BE MERGED.  The functional test exposes a problem, but might be written better.

### Your Environment

uname -a
Linux XXXXXXXXXXXXXX 5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bmuschko** [comment]
I can reproduce the issue but would have to further debug the root cause. The image ID stored for up-to-date checking has the correct value. I am suspecting that Docker Java either doesn't throw an exception anymore when querying for the image by ID or that we are not properly reading the file.

**Comment by bmuschko** [comment]
I added a comment to your pull request: https://github.com/bmuschko/gradle-docker-plugin/pull/870#issuecomment-544256394.
