### ISSUE TITLE
Build Image task is up to date even if image should be rebuilt

### ISSUE THREAD

**Issue by ondrej-scerba** [bmuschko/gradle-docker-plugin#875]
### Expected Behavior
I'm expecting that new image will be built, but it says that the task is up to date. I think the issue is that my dockerfile doesn't changed but in fact I'm using copy tasks in it and the files used in copy task has changed.

### Current Behavior
Build image task is up to date.

### Context
I have to delete image manually or clean build in order to get image build.

### Steps to Reproduce (for bugs)
Run built image from dockerfile which contains copy tasks with changed files.

### Your Environment
Gradle 5.6
Plugin version 5.2.0

**Comment by ondrej-scerba** [comment]
Now when I'm trying to reproduce it, it works as expected. I think you can ignore it.

**Comment by bmuschko** [comment]
OK, closing. Let us know if you are still experience unexpected behavior.
