### ISSUE TITLE
defaultCommand of createDockerfile doesnt work

### ISSUE THREAD

**Issue by Happin3ss** [bmuschko/gradle-docker-plugin#878]
I'm creating a Dockerfile with the below script:
```
task createDockerfile(type: Dockerfile) {
        ...
        defaultCommand('java', '-jar', 'target/jetty-runner.jar', '--port 9090', 'target/test.war')
}
```

The output Dockerfile will look like this
```
FROM java:8
VOLUME ["/tmp"]
COPY jetty-runner.jar /target/
COPY test.war /target/
EXPOSE 9090
CMD ["java", "-jar", "target/jetty-runner.jar", "--port 9090", "target/test.war"]
```
### Expected Behavior

I got the following error:
```
WARNING: jetty-runner is deprecated.
         See Jetty Documentation for startup options
         https://www.eclipse.org/jetty/documentation/
2019-10-23 04:38:18.139:INFO:oejr.Runner:main: Runner
ERROR: Context 'file:///--port%209090' does not exist
```
### Current Behavior

 I have to do a workaround to change from defaultCommand to use instruction to make it work:

`instruction('CMD java -jar target/jetty-runner.jar --port 9090 target/test.war')`

 Output Dockerfile will look the same except for the last CMD:

`CMD java -jar target/jetty-runner.jar --port 9090 target/test.war`

So I'm not sure it's a bug from Docker or bug from our gradle plugin.

### Steps to Reproduce (for bugs)
- Use the above Dockerfile.
- Build the image with Jetty and any war file. Then run container from it :)

### Your Environment
Ubuntu 16.04.5 LTS

**Comment by bmuschko** [comment]
I am pretty sure that `"--port 9090"` have to be defined as their own parameters. This should be `"--port", "9090"`.

**Comment by Happin3ss** [comment]
I will check it on Monday and let you know whether It works. Thank you for your response ;)
