### ISSUE TITLE
100% CPU load on DockerBuildImage task

### ISSUE THREAD

**Issue by mkuzmin** [bmuschko/gradle-docker-plugin#88]
I'm creating a Docker image by copying files without running any commands inside a container:
```
FROM java:jre
ADD server/TeamCity/ /opt/teamcity-server/
```
The layer is rather large - it's 2000 files, over 600 Mb.

Running a build by Docker takes about 3 minutes.
Running the same build by the Gradle task takes 40 minutes, and loads CPU for 100%.

Here is a [stack dump](https://gist.github.com/mkuzmin/6d675411bf668e46d800).

I'm using:
Ubuntu 14.04
OpenJDK 1.7.0_79
Gradle 2.5
plugin 2.5
Docker 1.7.1

**Comment by bmuschko** [comment]
If you look at the stack dump, you'll see that the issue is coming from the Docker Java library. The Gradle task is really just a wrapper around the API exposed by the library. Could you please open the issue there?

**Comment by mkuzmin** [comment]
Which repository do you mean?

**Comment by bmuschko** [comment]
The one mentioned in the README file: https://github.com/docker-java/docker-java

**Comment by bmuschko** [comment]
I am going to close the issue. Let me know if you need additional feedback.

**Comment by mkuzmin** [comment]
Benjamin, 

I've reported https://github.com/docker-java/docker-java/issues/283, and a maintainer of `docker-java` has prepared a PR already: https://github.com/docker-java/docker-java/pull/284

I've compiled local copies of `java-docker` and `gradle-docker-plugin` to test that. Performance is much better, but now your plugin fails with `NullPointerException`. Here is a [stacktrace](https://gist.github.com/mkuzmin/6d675411bf668e46d800#file-stacktrace-pr284-txt).

That may be а backward-incompatible change in the PR, or a bug in your code, I don't know. 
I'm just a customer of your tool, and here is a moment, when I need to involve you to solve the problem.

I appreciate, if you re-open this issue, and communicate with maintainers of `docker-java` directly.

Thanks!

**Comment by mkuzmin** [comment]
`docker-java`has fixed this issue in version 2.0. Can you update the dependency please?

**Comment by bmuschko** [comment]
I started with this but the upgrade is not that straight forward. The API of version 2.0.0 changed quite a bit.

**Comment by bmuschko** [comment]
The plugin version 2.6 will use Docker Java 2.1.0.
