### ISSUE TITLE
DockerLogsContainer stop on Ctrl-C

### ISSUE THREAD

**Issue by coder82** [bmuschko/gradle-docker-plugin#880]
Is there a way to stop the container on Ctrl-C with gradle?
This is my code and I was trying with finalized by but it doesn't work, container still runs after gradle exits. If this can't be done it's really unpractical during development.

I run:
```
gradle runDocker
```

```
task dockerImage(type: DockerBuildImage) {
    inputDir = rootDir
    tags.add("${rootProject.name}")
    dockerFile = file("${project.rootDir}/Dockerfile")
}

task createMyAppContainer(type: DockerCreateContainer) {
    dependsOn dockerImage
    targetImageId dockerImage.getImageId()
    portBindings = ["${project.ext.port}:${project.ext.port}"]
    exposePorts("tcp", [project.ext.port])
    links = ["sfn-cms_db_1:db"]
    autoRemove = true
    tty = true
    containerName = "${rootProject.name}"
    attachStdout = true
}

task startMyAppContainer(type: DockerStartContainer) {
    dependsOn createMyAppContainer
    targetContainerId createMyAppContainer.getContainerId()
}

task waitForContainerStartup(type: DockerLogsContainer) {
    dependsOn startMyAppContainer
    targetContainerId createMyAppContainer.getContainerId()
    follow = true
    tailAll = true
}

task stopDockerContainer(type: DockerStopContainer) {
    targetContainerId createMyAppContainer.getContainerId()
}

task runDocker(type: DefaultTask) {
    dependsOn waitForContainerStartup
    finalizedBy stopDockerContainer
}
```

**Comment by cdancy** [comment]
@coder82 in this scenario, and with the options you have set, it's just going to poll forever. I would recommend using the [DockerLivenessContainer](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerLivenessContainer.groovy) task as it's designed to do exactly what you want: poll the logs until some message appears. Take a look over our functionalTests to see how this is being used and let me know how you fare.

**Comment by coder82** [comment]
The thing is I wouldn't know what to poll for, Ctrl+C would't print anything, gradle captures the signal and just exits completely forgetting about the container running. finalizedBy doesn't trigger either.

**Comment by cdancy** [comment]
@coder82 hmmm ... there should be some _indication_ to let you know the container is live. Do you have nothing like that here? Is that even what you're trying to do? Maybe you're looking to test liveness in another way?
