### ISSUE TITLE
Spotify docker-client is INACTIVE

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#882]
```
INACTIVE:
Spotify no longer uses recent versions of this project internally. 
The version of docker-client we're using is whatever helios has in its pom.xml.
At this point, we're not developing or accepting new features or even fixing non-critical bugs.
Feel free to fork this repo though.
```
So it looks like, until something else arises, we are sticking with `docker-java` ;)

**Comment by bmuschko** [comment]
Seems like someone forked it: https://github.com/spotify/docker-client/issues/1166. Either way I don't see anyone putting in the time right now to switch to a different library anyway.

**Comment by bmuschko** [comment]
Out [Gitter channel](https://gitter.im/gradle-docker-plugin/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) is likely better channel for further discussion or announcement. There's no real outcome to this issue.
