### ISSUE TITLE
QUERY: Setting 'repository' value on DockerPullImage (v 5.3.0)

### ISSUE THREAD

**Issue by nheitz** [bmuschko/gradle-docker-plugin#883]
I felt like I was in some version of Dante's hell earlier....

My current build performs a docker "pull" based on a value for 'repository' that is calculated in another gradle task.  Since upgrding to v5.3.0 of this plugin, I no longer seem to be able to change the value for DockerPullImage (I was previously using v 3.2.4)...and yet the semantics seem to force me to specify a value at gradle initialisation time when I don't know the value.  This is a catch 22...

~~~~
task pullBaseImage(type: com.bmuschko.gradle.docker.tasks.image.DockerPullImage) {
    group = null
    repository = ''

    doFirst {
        def dockerFile = file("$buildDir/docker/Dockerfile")
        def matcher = file("$buildDir/docker/Dockerfile").text =~ /(?m)FROM ([^:]+)(:.+)?/

        if (!matcher)
            throw new StopExecutionException("Skip this task")

        String remoteRepo = matcher[0][1]
        println(remoteRepo)
        repository = remoteRepo
        if (matcher[0][2])
            tag = matcher[0][2].substring(1)
    }
}
~~~~

Is there any way to override the value for repository after initialisation?  The property used to be a simple string, and now it is some kind of Provider.  set(...), value(...) and '=' do not seem to work.

**Comment by cdancy** [comment]
@nheitz `repository` is Provider instance and so you can always do something like:
```
repository = project.provider { logic-to-determine-repo-at-runtime-within-closure }
```

**Comment by bmuschko** [comment]
Closing this issue. Please have a look at the [Provider API](https://docs.gradle.org/current/userguide/lazy_configuration.html) for a deeper understanding.
