### ISSUE TITLE
Modifying Instructions of a SpringBootApp Dockerfile Task

### ISSUE THREAD

**Issue by iamaverrick** [bmuschko/gradle-docker-plugin#884]
### Expected Behavior

we want to modify the instructions how is briefly mentioned on 2.5.1. Modifying Instructions of a Dockerfile Task in the documentation as i.g

```
FROM openjdk:11
LABEL maintainer=contactus@company.com
WORKDIR /app
COPY libs libs/
COPY resources resources/
COPY classes classes/
COPY node_modules node_modules/
ENTRYPOINT ["java", "-cp", "/app/resources:/app/classes:/app/node_modules:/app/libs/*", "webApplication"]
EXPOSE 8011
```

### Current Behavior

We are looking to modify dockerfile instructions being created by com.bmuschko.docker-spring-boot-application plugin. currently the plugin handles the creation of the dockerfile and creates this:

```
FROM openjdk:11
LABEL maintainer=contactus@company.com
WORKDIR /app
COPY libs libs/
COPY resources resources/
COPY classes classes/
ENTRYPOINT ["java", "-cp", "/app/resources:/app/classes:/app/libs/*", "webApplication"]
EXPOSE 8011
COPY node_modules node_modules/
```

### Context

currently we have a working app in production which uses this plugin in order to generate the dockerfile and push it to registry. the app in production doesn't have the node_modules which is causing a #lot of issues. we are looking to modify the dockerfile in order to add the proper instructions to add the node_modules to the docker image.

### Your Environment

```
plugins {
	id 'war'
	id 'java'
	id 'idea'
	id 'groovy'
	id 'eclipse'
	id 'com.patdouble.awsecr' version '0.5.2'
	id 'org.unbroken-dome.helm' version '0.4.4'
	id 'org.springframework.boot' version '2.1.7.RELEASE'
	id 'com.bmuschko.docker-remote-api' version '5.2.0'
	id 'com.bmuschko.docker-spring-boot-application' version '5.2.0'
	id 'org.unbroken-dome.helm-publish' version '0.4.4'
	id 'org.unbroken-dome.helm-releases' version '0.4.4'
	id 'io.spring.dependency-management' version '1.0.8.RELEASE'
}


docker {

	springBootApplication {
		baseImage = 'openjdk:11'
		maintainer = 'contactus@company.com'
		ports = [8011]
		tag = "123456789.dkr.ecr.us-east-1.amazonaws.com/${project.group}/${project.name}:${project.version}"
	}

	dockerCreateDockerfile {
		doFirst {
			copy {
				from "node_modules/"
				into { "${project.buildDir}/docker/node_modules" }
			}
		}
		copyFile("node_modules", 'node_modules/')


//		from("node:11")
//		copyFile("${project.projectDir}/package*.json", '/app')
//		runCommand("npm install")
//		copyFile('.', '/app')
//		entryPoint("java", "-cp", "/app/resources:/app/classes:/app/node_modules:/app/libs/*", "webApplication")
	}

	registryCredentials {
		url = 'https://123456789.dkr.ecr.us-east-1.amazonaws.com'
	}
}
```

**Comment by bmuschko** [comment]
I don't see a real question in your issue. Are you asking how to insert an instruction somewhere in the middle of the list of already existing instructions? Just defining an instruction will simply add to the end of the list as you've done it. The section "2.5.1. Modifying Instructions of a Dockerfile Task" also describes how to insert an instruction somewhere else in the second example.

**Comment by iamaverrick** [comment]
I’m sorry my question isn’t as clear.

I’m asking how to  Modifying Instructions of a Dockerfile Task described in The section "2.5.1. In the documentation. To me it isn’t as clear as I would of hoped.


Are we suppose to insert this code in the build.gradle file, or are we suppose to create a groovy class file and insert the code in section 2.5.1.

Would it be possible if you can show an example of how one would modify the docket file instructions. We should be able to handle the rest after we understand the process. 

Thank you in advance.

**Comment by bmuschko** [comment]
> Are we suppose to insert this code in the build.gradle file, or are we suppose to create a groovy class file and insert the code in section 2.5.1.

This is more a general Gradle question than one targeted toward the plugin. The difference is that either want to modify an existing task or create a completely new one. Given that you are applying the plugin `com.bmuschko.docker-spring-boot-application` the task of type `Dockerfile` has been created automatically so you'll likely just want to modify the existing one. I'd suggest read up on the differences in the Gradle user guide.

> Would it be possible if you can show an example of how one would modify the docket file instructions. We should be able to handle the rest after we understand the process.

I haven't tried it out but something like this should work.

```
import com.bmuschko.gradle.docker.tasks.image.Dockerfile.*

createDockerfile {
    List<Instruction> originalInstructions = new ArrayList<Instruction>(instructions.get())
    int lastCopyInstructionIndex = originalInstructions
            .findLastIndexOf { it.keyword == 'COPY' }
    CopyFileInstruction copyNodeModules = new CopyFileInstruction(new CopyFile('node_modules', 'node_modules/'))
    originalInstructions.add(lastCopyInstructionIndex + 1, copyNodeModules)
    instructions.set(originalInstructions)
}
```

**Comment by iamaverrick** [comment]
> This is more a general Gradle question than one targeted toward the plugin. 

**Instruction
CopyFileInstruction**

should come from  import com.bmuschko.gradle.docker.tasks.image.Dockerfile.* and its not being imported. 

you mentioned that this is more a gradle question which for the most part the code is. but as far as the imports i should be able to use the classes with in the gradle code snippet. is their a way you can make sure you are able to load the classes fine on your end?

**Comment by bmuschko** [comment]
Maybe i misunderstood your question. I thought you are referring to custom task type used when creating a new task.

> com.bmuschko.gradle.docker.tasks.image.Dockerfile.*

Yes, those come from the plugin. Looking at this again, they need to be declared as `static` imports. That might be your issue. You may also want to have a look at the [Groovydoc of this plugin](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html). Here's a [full-fledged example](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/docs/samples/code/remote-api-plugin/dockerfile-instructions/groovy/build.gradle#L5-L8) that I know works as we are running tests against it.

**Comment by bmuschko** [comment]
I am assuming this has been resolved on your end. Closing the issue for now. Reopen the issue if you need further assistance.

**Comment by iamaverrick** [comment]
Yes @bmuschko,


I managed to get the code working with the last comment you made available to me. I was going to add my resolution code here just in case anybody might be having issues with the same issue this will helped them as it did for me.

Furthermore, I think that the documentation are on point but in this particular section is would be nice if you can add the static imports so users can fully understand that they will need to add these in order to get the code to work properly. Any how I will like to thank you for taking the time to help me resolve my issues. Very well appreciated.

**Comment by bmuschko** [comment]
Showing the imports should be a relatively easy fix. It would probably require some duplication though. You might have noticed that the pieces of code are "pulled out" of the sample and are included in the documentation. Whatever should be rendered in the user guide needs to be within the opening and closing Asciidoc delimiters. Happy to receive a pull request for improvements to the documentation!
