### ISSUE TITLE
DockerLivenessContainer assumes that field `sink` is of type StringWriter

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#886]
### Expected Behavior

The class `DockerLivenessContainer` handles the field `sink` appropriately. At the moment the implementation assumes that field `sink` is typed as `StringWriter`. It calls the method `getBuffer()` on it. There needs to be appropriate handling for it.

### Current Behavior

Passing an instance of `Writer` to the field `sink` can potentially break at runtime. The method call [`getSink().getBuffer()`](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerLivenessContainer.groovy#L115) would throw an exception if the field is not of type `StringWriter`.

### Context

This issue can easily be revealed by adding the `@CompileStatic` annotation to the class `DockerLivenessContainer`.

**Comment by cdancy** [comment]
@bmuschko I'll knock this out within the next week as we have an existing feature request we'd like to get in for this specific task (liveness based on the truthiness of a passed closure).

**Comment by bmuschko** [comment]
@cdancy Were you planning to submit a PR for this soon?

**Comment by bmuschko** [comment]
Plan is to deprecated and remove those classes.
