### ISSUE TITLE
Passing Arguments to the Container

### ISSUE THREAD

**Issue by rebootmoishe** [bmuschko/gradle-docker-plugin#888]
Is there a way to provide arguments to the container at runtime.

### Expected Behavior

Some database containers require arguments to be passed as arguments at runtime.

### Current Behavior

I cannot seem to find a way to pass the arguments for the container to the task of DockerStartContainer

### Context

As an example:

In order to enable the SSL Support for Postgres the docker image there need to be arguments passed at "docker run" to the container.  Not the environment variables:

e.g. 
line 10 of postgres.sh script - https://gist.github.com/mrw34/c97bb03ea1054afb551886ffc8b63c3b

Or this answer on StackOverflow: 

https://stackoverflow.com/questions/55072221/deploying-postgresql-docker-with-ssl-certificate-and-key-with-volumes
See very last code snippet.

### Steps to Reproduce (for bugs)

build.gradle:
```
plugins {
    id 'java'
    id 'com.bmuschko.docker-remote-api' version '5.2.0'
}


import com.bmuschko.gradle.docker.tasks.image.*;
import com.bmuschko.gradle.docker.tasks.container.*;


task createDBImage (type:DockerBuildImage) {
    inputDir = file("${projectDir}")
    dockerFile = file("${projectDir}/TestDBDockerfile")
    tags.add("testjdbc:${version}")
}

task createDBContainer (type:DockerCreateContainer) {
    dependsOn createDBImage
    targetImageId createDBImage.getImageId()
    portBindings = ['5432:5432']
    envVars.put('POSTGRES_PASSWORD', 'your_password_goes_here')
    autoRemove = true
}

task runDBContainer(type:DockerStartContainer) {
    dependsOn createDBContainer
    targetContainerId createDBContainer.getContainerId()
}

task containerTearDown(type:DockerStopContainer) {
    targetContainerId createDBContainer.getContainerId()
}

```
<other code removed>

Test Docker File:
```

FROM postgres:latest

COPY ssl/server.key /var/lib/postgresql/server.key
COPY ssl/server.crt /var/lib/postgresql/server.crt

RUN chmod 600 /var/lib/postgresql/server.key
RUN chown postgres:postgres /var/lib/postgresql/server.key

```

### Your Environment

Currently running Gradle 5.6.2 with plugin version 5.2.0

**Comment by bmuschko** [comment]
It doesn't look like the [`StartContainerCmd`](https://github.com/docker-java/docker-java/blob/master/docker-java-api/src/main/java/com/github/dockerjava/api/command/StartContainerCmd.java) provided by Docker Java provides any options if I am not mistaken. That's probably the reason why we are not exposing an options. You may want to ask that project to expose more options.

Could you set your options as instructions in the `Dockerfile`?

**Comment by rebootmoishe** [comment]
Tried something like
`CMD ["postgres", "-c ssl=on", etc, etc]`

Fails usually with something like: 

2019-11-20 14:58:22.919 GMT [1] FATAL:  unrecognized configuration parameter " "ssl"

If I run from the command line with `docker run` and provide those options on the command line it works perfectly.  So while I have a workaround sort of to use the `Exec` task in the build file.  I would much rather not try to use a hack like that.

**Comment by bmuschko** [comment]
I am pretty sure that `-c` and `ssl=on` need to be their own arguments e.g. CMD `["postgres", "-c",  "ssl=on", etc, etc]`.

**Comment by rebootmoishe** [comment]
Tried that too with same effect.

**Comment by cdancy** [comment]
@rebootmoishe for the [gradle-docker-applications-plugin](https://github.com/project-aries/gradle-docker-applications-plugin) I do this in one of the [functionalTests](https://github.com/project-aries/gradle-docker-applications-plugin/blob/master/src/functionalTest/groovy/com/aries/gradle/docker/applications/plugin/EndToEndFunctionalTest.groovy#L112) I have:

```
                        stop {
                            withCommand(['su', 'postgres', "-c", "/usr/local/bin/pg_ctl stop -m fast"])
                            successOnExitCodes = [0, 127, 137]
                            awaitStatusTimeout = 60000
                            execStopProbe(60000, 10000)
                        }
```
I'd try something similar, with adding in the `ssl=on` argument in just the way that I did it here to see if it work.

**Comment by bmuschko** [comment]
@rebootmoishe I'd suggest you ask for this feature with Docker Java project. We haven't heard back from you about @cdancy's suggestion so I can going to close this issue.

**Comment by tkrah** [comment]
Hi, got the same problem like the OP in 2023, no matter how I try to arrange it, I can't put arguments to the cmd with this plugin while running via Exec it does work. Reopen or make a new issue @bmuschko ?

**Comment by bmuschko** [comment]
@tkrah Please open a new issue with a concrete, reproducible example.
