### ISSUE TITLE
containerName property for task DockerCreateContainer is not working

### ISSUE THREAD

**Issue by rocks4530** [bmuschko/gradle-docker-plugin#889]
containerName property for task DockerCreateContainer is not working

task pgBuild(type: DockerBuildImage, dependsOn: processConfigs) {
	images.add(imageName)
}
task pgCreate(type: DockerCreateContainer, dependsOn: pgBuild) {
    targetImageId imageName
    containerName = 'tc-pg'
    hostConfig.portBindings = ['8082:8082','10000:10000']
    hostConfig.autoRemove = true
}
task pgStart(type: DockerStartContainer, dependsOn: pgCreate) {
    targetContainerId pgCreate.getContainerId()
}

when i start the container it shows
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
b40a582711cc        pg-image            "/docker-entrypoint.…"   4 seconds ago       Up 3 seconds        0.0.0.0:10000->10000/tcp   **frosty_williams**

**Comment by orzeh** [comment]
@rocks4530 I couldn't reproduce it on my local. Can you create sample repository which shows the issue?

**Comment by rocks4530** [comment]
it works
