### ISSUE TITLE
Should DockerRemoveContainer/DockerStopContainer be idempotent?

### ISSUE THREAD

**Issue by jrglee** [bmuschko/gradle-docker-plugin#89]
Hi,

The docker-java client throws an `com.github.dockerjava.api.NotFoundException` when you try to remove or stop a container that does not exists. This behavior is similar to the command line that returns the status code -1 when you `docker rm` a container that does not exists. This is fine but it is not all that convenient for a build script. 

I would like to stop and remove any existing containers before starting new ones for functional tests, the most simple solution would be to capture and ignore the exception and only log that a container does not exists therefore you don't need to stop/remove it. In this way the stop/remove task can be used as dependencies of a start/create task.

Maybe a more elegant solution is to support a flag to indicate if the task should fail but I do not thing it brings any value.

Thoughts?

**Comment by bmuschko** [comment]
The tasks exposed by the plugin are not striving to align with the command line behavior as much as possible. Adding one off flags are not desirable. It's pretty easy to achieve your own behavior though. Here are some options:

- Write your own tasks that use the Docker client (see [example](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/AbstractDockerRemoteApiTaskFunctionalTest.groovy#L30)).
- Tweak existing task types to do what you want to achieve. You can always extend them and wrap their task action into a try/catch block.

**Comment by jrglee** [comment]
Writing custom tasks seems to be a easy way around it. Thanks for answering.
