### ISSUE TITLE
Multiple port in hostConfig.portBindings doesn't work

### ISSUE THREAD

**Issue by rocks4530** [bmuschko/gradle-docker-plugin#890]
Hi,

Thanks for this useful plugin. 

Is there a way to specify multiple port. I tried with
hostConfig.portBindings = ["8082:8082","10000:10000"]

But it always takes the last one. Am I missing something here?

**Comment by orzeh** [comment]
@rocks4530 your example should work. Can you create a minimal repo/example which demonstrates the issue?

**Comment by rocks4530** [comment]
HI @orzeh ,
please check this example @ 
https://github.com/rocks4530/envoy-proxy 

docker ps commands shows this

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
483f45f7a901        6f923718edf9        "/docker-entrypoint.…"   12 minutes ago      Up 12 minutes       0.0.0.0:10000->10000/tcp   envoy-proxy

**Comment by orzeh** [comment]
@rocks4530 ok, I can reproduce it with your example. I need some time to dig into this.

**Comment by rocks4530** [comment]
@orzeh thanks.

**Comment by orzeh** [comment]
@rocks4530 actually it's working, please try to access these ports.

Because of Docker API awkwardness, exposed ports are not being  _displayed_  neither in CLI nor in API responses, see also [this issue](https://github.com/docker-java/docker-java/issues/786).

**Comment by rocks4530** [comment]
good to know that. And thanks. Will try out to see.
