### ISSUE TITLE
Unable to have multiple main methods in project when building image

### ISSUE THREAD

**Issue by Robouzou** [bmuschko/gradle-docker-plugin#891]
### Expected Behavior
Running `dockerBuildImage` should either auto-select a main method to use an the entry point (as it did when using Application Plugin), or get this from some configuration value provided to it. Maybe through `mainClassName`, though some kind of per-image configuration might be useful to people wanting to build multiple images.

### Current Behavior
Whenever you have multiple files that have `main` functions, `dockerBuildImage` will give this error:
```
Unable to find a single main class from the following candidates [{classes with main methods}]
```

### Context

The project in which this is a problem has a `Main` class, with the actual `main` entry point for the application, but it also houses a few other tools which are used occasionally by themselves, each with their own `main`.

### Steps to Reproduce (for bugs)

[multiple_mains.zip](https://github.com/bmuschko/gradle-docker-plugin/files/3882760/multiple_mains.zip)

Running `gradle dockerBuildImage` in this project generates the issue.

### Your Environment

This is with Gradle 5.6.4, openjdk 11.0.4, and any version of the plugin after commit 9cfac7f2c0f58c8247c3231629d76edfaf9b3621 / v5.1.0.

**Comment by bmuschko** [comment]
The plugin you are using is looking for a [main class that is annotated with `org.springframework.boot.autoconfigure.SpringBootApplication`](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplicationPlugin.groovy#L32). Can you explain why your Spring Boot application does not use this annotation?

**Comment by Robouzou** [comment]
That's because we're not using the Spring Boot Application Plugin, but the Java Application Plugin, [which doesn't search for any annotation to specificity the main class.](https://github.com/bmuschko/gradle-docker-plugin/blob/1910be61fab63a8da578bc2a085064ba4804e724/src/main/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPlugin.groovy#L43)

**Comment by bmuschko** [comment]
Ah, OK. I must have misread your initial comment. I can [reproduce the issue](https://github.com/bmuschko/gradle-docker-plugin/commit/2f6b3374e6a3ba4b203dd96513442992dd2bcf90). I thought that we are selecting one main class from the list, however, that might not be the one you want. I'll look into some alternatives.

**Comment by ypoluektovich** [comment]
What was the reasoning behind changing the "use the main class setting from the application plugin" behavior? It looks perfectly reasonable to me.

**Comment by bmuschko** [comment]
@ypoluektovich There's no point in forcing users to apply the Gradle core application plugin. It simply add unnecessary overhead (in terms of Gradle lifecycle configuration time) and isn't really required for the tasks this plugin performs. In addition, the configuration of this plugin got even easier as you don't need to spell out the main class name. The use case we are talking about here only applies if you have more than one main class sitting in your source set. I'd say that's only relevant to 1-3% of users.

**Comment by bmuschko** [comment]
@Robouzou I opened a PR for this: https://github.com/bmuschko/gradle-docker-plugin/pull/892

**Comment by Robouzou** [comment]
It looks like that will resolve the issue. Thank you for your effort.
