### ISSUE TITLE
Cannot provide a main class that is in a dependency

### ISSUE THREAD

**Issue by michaelzangl** [bmuschko/gradle-docker-plugin#893]
### Expected Behavior
Use a java application with:
```
plugins {
    id 'application'
    id 'com.bmuschko.docker-remote-api' version '6.0.0'
    id 'com.bmuschko.docker-java-application' version '6.0.0'
}

dependencies {
    runtimeOnly project(':server') // ← This is where the actual main is
}

mainClassName 'my.server.Run'
```

### Current Behavior
```
Execution failed for task ':xxx:dockerCreateDockerfile'.
> Main class name could not be resolved
```

### Context
We have a server project that has Tomcat and sets up the spring context (not spring boot).
We have the actual application project with the @Components that get found by classpath scanning.

### Your Environment
Version 6.0.0

**Comment by bmuschko** [comment]
Can you explain the purpose of the module that contains the build logic above? Does it even contain any code?

Generally speaking, your use case will be supported by https://github.com/bmuschko/gradle-docker-plugin/pull/892.

A couple more comments on your build code:

1. The Gradle core application plugin is not required to use the `com.bmuschko.docker-java-application` plugin. You can add it if you like but there's no necessity to have it. Just wanted to point that out.
2. The `com.bmuschko.docker-java-application` plugin automatically applies the `com.bmuschko.docker-remote-api` plugin. That means you don't have to declare it.

**Comment by michaelzangl** [comment]
@bmuschko 
Thanks for the reply. In our case, I separated the build of the docker to an own subproject that only has dependencies on all the modules that should be included in the image (the server + all spring components)

My workaround for now is to have a buildscript:
```groovy
mainClassName 'my.server.FakeRun'
```

and a Class:
```java
package my.server;

public class FakeRun {
  public static void main(String args[]) {
    my.server.Run.main(args);
  }
}
```

The patch would make the workaround simplier. It would require to add this line (If I see it correctly) to the build.gradle to make both docker and the application plugin (for ./gradlew run) happy:
```groovy
mainClassName = 'my.server.Run`
docker {
  mainClassName = application.mainClassName
}
```
I would suggest to set the application.mainClassName as default for mainClassName. The default is 'null'. If the user sets the application mainClassName, then it is used as docker class. If he does not (null), old class search is used.

On your tipps:
(1) thanks, I just copied from https://bmuschko.github.io/gradle-docker-plugin/#usage_2
(2) That is good to know.

**Comment by bmuschko** [comment]
> In our case, I separated the build of the docker to an own subproject that only has dependencies on all the modules that should be included in the image (the server + all spring components)

While Gradle gives you all the options of modeling your build code as described, I don't think it's the best option. This code really belongs to your `server` project and not an empty module. Maybe that's more of a Maven methodology. I would break out the logic into a script plugin and then apply it in the `server` project or move that code under `buildSrc` as a binary plugin and then apply it in the `server` project. In both cases you will end up with a single line of code that needs to be added.

> I would suggest to set the application.mainClassName as default for mainClassName. The default is 'null'. If the user sets the application mainClassName, then it is used as docker class. If he does not (null), old class search is used.

I don't want to make our plugin more complex than it needs to be by having to react to other plugins. It's a matter of maintenance and as explained earlier there's no real correlation between the Gradle core application plugin and the `com.bmuschko.docker-java-application`. It will lead to 3 different options how the main class name can be found or declared and I think it will rather confuse end users. You may want to think about writing your plugin wrapper if you are concerned about additional logic.

> (1) thanks, I just copied from https://bmuschko.github.io/gradle-docker-plugin/#usage_2

Thanks for the pointer. Didn't realize we still had that in there. I will remove the second line from the documentation.
