### ISSUE TITLE
DockerPushImage using invalid format for X-Registry-Auth

### ISSUE THREAD

**Issue by dchesterman** [bmuschko/gradle-docker-plugin#895]
### Expected Behavior
If I have a docker config file that works with the docker cli, the same config could be consumed successfully by the plugin. The `X-Registry-Auth` header would match the documented format.  It seems the auth field in the `~/docker/config.json` should be decoded and re-encoded in the documented format with the explicit user and password fields.

### Current Behavior
Currently it seems the auth field is used directly and encoded in the `X-Registry-Auth` header but fails to authorize against the registry.

It seems like in 6.0.0, the plugin no longer _always_ uses the supplied registryCredentials, and instead will try to use the config file if it exists.  Seems like it would be preferable to have this behavior optional.

### Context
I am trying to push to a remote registry via the DockerPushImage task.

### Steps to Reproduce (for bugs)
I am using version 6.0.0.  When I have no `~/.docker/config.json` file, the credentials I supply in the `registryCredentials` configuration block are properly read and the following header is included in the POST to push

```
2019-12-08T13:45:24.388-0800 [DEBUG] [com.bmuschko.gradle.docker.shaded.org.apache.http.wire] http-outgoing-41 >> "POST /images/my.docker.registry/test/image:latest/push HTTP/1.1[\r][\n]"
2019-12-08T13:45:24.388-0800 [DEBUG] [com.bmuschko.gradle.docker.shaded.org.apache.http.wire] http-outgoing-41 >> "Accept: application/json[\r][\n]"
2019-12-08T13:45:24.388-0800 [DEBUG] [com.bmuschko.gradle.docker.shaded.org.apache.http.wire] http-outgoing-41 >> "User-Agent: Jersey/2.27 (Apache HttpClient 4.5.6)[\r][\n]"
2019-12-08T13:45:24.388-0800 [DEBUG] [com.bmuschko.gradle.docker.shaded.org.apache.http.wire] http-outgoing-41 >> "X-Registry-Auth: eyJ1c2VybmFtZSI6Im15dXNlciIsInBhc3N3b3JkIjoibXlwYXNzd29yZCIsInNlcnZlcmFkZHJlc3MiOiJodHRwczovL215LmRvY2tlci5yZWdpc3RyeSJ9[\r][\n]"
```
The base64 content decodes as follows :

```
{"username":"myuser","password":"mypassword","serveraddress":"https://my.docker.registry"}
```
This matches the format documented here : https://docs.docker.com/engine/api/v1.39/#section/Authentication

If I have a `~/.docker/config.json` the `auth` encoded field is used directly and the POST to push fails.

My `~/.docker/config.json` is as follows :
```
{
  "auths" : {
      "https://my.docker.registry" : {
         "auth": "bXl1c2VyOm15cGFzc3dvcmQ="
      }
  }
}
```
The push call with the docker cli works as expected.

But the following header is used in the POST via the Gradle plugin :
```
2019-12-08T13:44:41.713-0800 [DEBUG] [com.bmuschko.gradle.docker.shaded.org.apache.http.wire] http-outgoing-39 >> "POST /images/my.docker.registry/test/image:latest/push HTTP/1.1[\r][\n]"
2019-12-08T13:44:41.713-0800 [DEBUG] [com.bmuschko.gradle.docker.shaded.org.apache.http.wire] http-outgoing-39 >> "Accept: application/json[\r][\n]"
2019-12-08T13:44:41.713-0800 [DEBUG] [com.bmuschko.gradle.docker.shaded.org.apache.http.wire] http-outgoing-39 >> "User-Agent: Jersey/2.27 (Apache HttpClient 4.5.6)[\r][\n]"
2019-12-08T13:44:41.713-0800 [DEBUG] [com.bmuschko.gradle.docker.shaded.org.apache.http.wire] http-outgoing-39 >> "X-Registry-Auth: eyJzZXJ2ZXJhZGRyZXNzIjoiaHR0cHM6Ly9teS5kb2NrZXIucmVnaXN0cnkiLCJhdXRoIjoiYlhsMWMyVnlPbTE1Y0dGemMzZHZjbVE9In0=[\r][\n]"
```

This decodes as follows :
```
{"serveraddress":"https://my.docker.registry","auth":"bXl1c2VyOm15cGFzc3dvcmQ="}
```

### Your Environment
Gradle 6.0.1
Plugin 6.0.0
docker version
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by bmuschko** [comment]
It seems like you are asking to get two different things addressed if I am not mistaken. Could you clarify?

> Currently it seems the auth field is used directly and encoded in the X-Registry-Auth header but fails to authorize against the registry.

If I am not mistaken then the [current logic](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocator.groovy#L195-L196) does not decode the username and password via base64. Furthermore, it also doesn't distinguish between username and password which is in the format `username:password` if I am not mistaken.

> It seems like in 6.0.0, the plugin no longer always uses the supplied registryCredentials, and instead will try to use the config file if it exists. Seems like it would be preferable to have this behavior optional.

I believe you are saying that the credentials provided by the plugin extension does not precedence if the config file has been resolved. Is that a correct interpretation? For now I would like to avoid introducing a flag to disable the automatic parsing of the config file...at least as long as you can successfully overwrite the values.

**Comment by bmuschko** [comment]
@kgrech Do you have the bandwidth to look at this issue as well?

**Comment by kgrech** [comment]
@bmuschko I have. How exactly you would like it to behave? It looks like it working as expected. Do you want to overwrite the credentials from the config json object X?

**Comment by bmuschko** [comment]
@kgrech I'd say let's get started by working on the handling of the value for `X-Registry-Auth`.

1. Start by adding a functional test case that shows that it use case doesn't work properly. The test case fails.
2. Make the relevant changes in the code.
3. Test case should pass.

I can look into the use case for overwriting the credentials via the plugin extension. We might have altered that behavior with the change.

**Comment by kgrech** [comment]
I believe the ``X-Registry-Auth`` is just a serialized value of the docker's java ``AuthConfig`` object: https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocator.groovy#L196

The problem is that auth field object in a  config JSON ``"auth": "bXl1c2VyOm15cGFzc3dvcmQ="`` decodes as just myuser:mypassword. This is a basic auth encoded string. Since [AuthConfig|https://github.com/docker-java/docker-java/blob/master/docker-java-api/src/main/java/com/github/dockerjava/api/model/AuthConfig.java#L35] class contains auth field, we just set it there without parsing.

**Comment by bmuschko** [comment]
@kgrech OK, thanks for the background. Would you be interested in working on a PR for this?

**Comment by kgrech** [comment]
@kgrech yes, however, it might be a bit hard to find a time before the new year holidays, but I will try to allocate it

**Comment by kgrech** [comment]
Looks like we indeed need to decode it: https://github.com/tourea/docker-java/blob/98f44966280603a69e1f5594809ea822a2dc7342/src/main/java/com/github/dockerjava/core/AuthConfigFile.java#L133

**Comment by schnabel** [comment]
Hi, you might want to add @Requires({ TestPrecondition.DOCKER_PRIVATE_SECURE_REGISTRY_REACHABLE }) to the new test case.

**Comment by bmuschko** [comment]
@schnabel Can you point me to the test case you are referring to via a GitHub line link?

**Comment by schnabel** [comment]
@bmuschko I was referring to the new test case from the pull request. Sorry for being to imprecise. Here is the [line](https://github.com/bmuschko/gradle-docker-plugin/blob/5402439398542d3c94953e9a907fa9c6a5ae7c7f/src/functTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginFunctionalTest.groovy#L250)

**Comment by bmuschko** [comment]
@schnabel Thanks, done! https://github.com/bmuschko/gradle-docker-plugin/commit/366fe98fb536cec0a704780e2e54a0e10897a849
