### ISSUE TITLE
Is the documentation for older versions available?

### ISSUE THREAD

**Issue by tgoldina** [bmuschko/gradle-docker-plugin#896]
Thank you for very nice documentation at https://bmuschko.github.io/gradle-docker-plugin/
Unfortunately, we are limited to an older version of gradle and hence the plugin.
Is there a way to get the documentation for an older release by its version number (like v4.3.0)?

**Comment by bmuschko** [comment]
At the moment the documentation is overwritten everything it is published. As of now, we are not keeping historical records. I believe this should be possible with GitHub Pages but I'd have to try it out. You'd probably need to write the documentation to a folder representing a specific version. Moreover, it would also require the user guide to point to a concrete version of the API docs which would need to stored per version as well.

As a workaround, you can check out the GitHub tag of the version you are using and then generate the documentation manually by running the `:asciidoc` task.

**Comment by bmuschko** [comment]
I am going to close the issue for now. I won't be able to get to it anytime soon, however, I love to see a contribution from the community.
