### ISSUE TITLE
Add labels during gradle execution phase

### ISSUE THREAD

**Issue by igordumchykov** [bmuschko/gradle-docker-plugin#897]
I`m trying to add labels to my docker image during execution phase:

`task buildDocker(type: DockerBuildImage) {
doLast {
labels.put("MyLabelName", some_function_that_runs_only_in_execution_and_produces_HelloWorld())
}
}`

### Expected Behavior
I expect my label will present in image in docker inspect:
`
...
    "Labels" : {
      "MyLabelName" : "HelloWorld"
    },
...`

### Current Behavior

But I see empty Labels field:

`
...
    "Labels" : {},
...`
### Context
I don`t want to run my some_function_that_runs_only_in_execution_and_produces_HelloWorld() during configuration phase

### Steps to Reproduce (for bugs)
1. Create a task with type DockerBuildImage
2. Add snippet: `doLast {
labels.put("MyLabelName", "helloWorld)
}`
3. Inspect image after creation and look for field Labels.
4. Labels is empty

### Your Environment
My some_function_that_runs_only_in_execution_and_produces_HelloWorld() is run only in execution phase because it depends on some content that is generated in execution phase in step that is run before current step.

**Comment by cdancy** [comment]
@igordumchykov this is more a standard gradle question than anything else. You should be able to do something like:
```
labels = project.provider { return labels at runtime with some code here }
```

**Comment by bmuschko** [comment]
`labels.put` should work but you are doing this too late in Gradle execution lifecycle by putting it into `doLast`. You this to happen during the configuration phase. For more information, see the Gradle user guide.

**Comment by igordumchykov** [comment]
> @igordumchykov this is more a standard gradle question than anything else. You should be able to do something like:
> 
> ```
> labels = project.provider { return labels at runtime with some code here }
> ```
