### ISSUE TITLE
support 'agent' parameter for spring-boot

### ISSUE THREAD

**Issue by n0mer** [bmuschko/gradle-docker-plugin#90]
Currently spring-boot allow to specify java agents as

```groovy
springBoot {
    agent = file("my-agent.jar")
}
```

Generated startup scripts does not include instructions to run agent.

However, `./gradlew run` starts agent perfectly.

So, can you please support java agents defined in spring-boot config?

**Comment by bmuschko** [comment]
Can you elaborate on the follow questions?

- When you refer to spring-boot are you talking about the Spring Boot Gradle plugin?
- What plugins do you apply at the moment? I am assuming the `com.bmuschko.docker-java-application` plugin but what else?
- Given that you are using the Spring Boot Gradle plugin, you say that the agent configuration when executing the `run` task but not for the start script generation? If that's the case, then I'd recommend letting the SpringSource guys adding this functionality.

It really isn't the responsibility of this plugin to tweak the generated start scripts. This is the responsibility of the application plugin. Keep in mind that you can still provide JVM parameters as described in the user guide for the application plugin.

**Comment by n0mer** [comment]
@bmuschko ,

what plugin are you using to generate startup scripts in ./bin folder?

**Comment by bmuschko** [comment]
> what plugin are you using to generate startup scripts in ./bin folder?

The [application plugin](https://docs.gradle.org/current/userguide/application_plugin.html).

**Comment by n0mer** [comment]
thank you
