### ISSUE TITLE
java.lang.StackOverflowError with java:98 dependency missing

### ISSUE THREAD

**Issue by vinnyasa** [bmuschko/gradle-docker-plugin#900]
We are seeing issues with docker-remote-api
Using Gradle 6.0.1
In running build gradle getting:
java.lang.StackOverflowError at org.gradle.api.internal.provider.AbstractProperty.maybeVisitBuildDependencies(AbstractProperty.java:98)

The build is trying to pull an image from a private registry, but it never gets to that task

This is a Gradle 6.0.1 project building in a Windows Server 2019

**Comment by bmuschko** [comment]
Can you please post the full stack trace? Given the error message you posted above I think this is a Gradle core issue.

**Comment by bmuschko** [comment]
I am going to close this issue as I haven't gotten any more details. Let us know if you still want to dive deeper into this issue. Please reopen as needed. Generally speaking, I don't think this is an issue with the plugin.
