### ISSUE TITLE
JDK 11 OK Now?

### ISSUE THREAD

**Issue by robert-smith-911** [bmuschko/gradle-docker-plugin#904]
Hi been following along and have a JDK 11 project I'm working on. Is JDK 11 supported now?

**Comment by bmuschko** [comment]
Not at the moment because of https://github.com/docker-java/docker-java/issues/1244.

**Comment by bmuschko** [comment]
I am going to close this issue for now. I will release a new version of the plugin as soon as we have a version of Docker Java that fully supports Java 11. Alternatively, you could probably add the `javax.xml.bind` to your build which should make it work.
