### ISSUE TITLE
Retrieve all known credentials for DockerBuildImage custom task

### ISSUE THREAD

**Issue by vierbergenlars** [bmuschko/gradle-docker-plugin#908]
The `DockerBuildImage` task uses registry credentials that are configured on the task/project configuration.

Recently, `DockerPushImage` and `DockerPullImage` gained the ability to read credentials from the native `docker login` authentication, but `DockerBuildImage` does not yet support this and only uses credentials configured inside Gradle.

I am willing to contribute this change, but I first wanted to open an issue to have some feedback from you before I start implementing it.

### Expected Behavior

Similar to `DockerPushImage` & `DockerPullImage`, `DockerBuildImage` also uses `docker login` credentials when it needs to authenticate to pull images.

For `DockerBuildImage`, multiple credentials can be sent at the same time, so the application does not need to know which credentials it needs. (there can be multiple `FROM <image>` in a `Dockerfile` going to different private registries)

The `RegistryAuthLocator` will gather a list of all credentials and will place them all inside `AuthConfigurations` in this block of code: https://github.com/bmuschko/gradle-docker-plugin/blob/7e725b65aea32d8fa77dd33e2a579941694c395c/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy#L270-L273

How to discover all available credentials is something that needs to be researched a bit, but I think reading the `"auths"` section from `~/.docker/config.json`, combined with the hostnames discovered from `docker-credential-?? list` should give us a list of all the available credentials to send.

### Current Behavior

Currently, `DockerBuildImage` only uses the `registryCredentials` configured on the task to authenticate.

### Context

We are building private docker images on top of other private docker images (all in the same registry). To make sure we are always using the latest version of the images, we set `pull = true` on `DockerBuildImage`, which always pulls the `FROM ???` images configured in a Dockerfile.

Currently, we configure `registryCredentials` with credentials read from `~/.gradle/gradle.properties` on each developers computer. We want to get rid of this file with plain text credentials, and instead delegate this credential management to docker.

**Comment by bmuschko** [comment]
> Currently, DockerBuildImage only uses the registryCredentials configured on the task to authenticate.

I am not sure that's the case. The logic is pretty much the same between `DockerPushImage`, `DockerPullImage` and `DockerBuildImage` when comes down to consuming credentials and providing it to Docker Java. Can you explain why you think `DockerBuildImage` behaves differently?

From what I understand, you will want to gather all credentials for `DockerBuildImage` and then pass them to Docker Java. I think that should be possible. For the push and pull operations, you can only provide one credential I think. Does this summarize your request?

**Comment by vierbergenlars** [comment]
> I am not sure that's the case. The logic is pretty much the same between `DockerPushImage`, `DockerPullImage` and `DockerBuildImage` when comes down to consuming credentials and providing it to Docker Java. Can you explain why you think `DockerBuildImage` behaves differently?

The logic for `DockerBuildImage` is slightly different. `DockerPushImage` and `DockerPullImage` have the same logic to look up credentials, passing the image name to the `RegistryAuthLocator#lookupAuthConfig()` to look up the correct credentials.

https://github.com/bmuschko/gradle-docker-plugin/blob/0b925626ea69159382316a80344d5f6240a12f65/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy#L55-L56

However, `DockerBuildImage` does something different: It uses `RegistryAuthLocator#createAuthConfig()`, and the only thing that does is creating an `AuthConfig` object with the passed credentials.

https://github.com/bmuschko/gradle-docker-plugin/blob/7e725b65aea32d8fa77dd33e2a579941694c395c/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy#L270-L273

> From what I understand, you will want to gather all credentials for `DockerBuildImage` and then pass them to Docker Java. I think that should be possible. For the push and pull operations, you can only provide one credential I think. Does this summarize your request?

That is correct.
You can pass multiple credentials to `DockerBuildImage`, because you can pull from multiple repositories when performing a build (in case of multiple `FROM`s in a Dockerfile) We could try to be smart, and parse the `Dockerfile` to find out which credentials we need, but this seems like excessive complexity if we can just send all credentials (`docker build` also sends all credentials)

For push and pull operations, you can only provide one credential. That's okay, because you know which credential you need from the image name.

**Comment by bmuschko** [comment]
Oh, didn't see that when I had a look at the code. If you want to provide a PR for this, go ahead. Please add tests that verify the behavior.
