### ISSUE TITLE
how to specify CMD option for Dockerfile generated using  Java application plugin

### ISSUE THREAD

**Issue by ransingh** [bmuschko/gradle-docker-plugin#91]
I am using the Java application plugin of this Docker plugin. But  in my case I need the CMD option in the generated Dockerfile  so that when container runs the application is provided with the option given to CMD.

I could not see any extension points to do that in the Java application plugin. Could point to in the right direction? Thanks.

**Comment by bmuschko** [comment]
You can add more commands to the task `dockerDistTar`. Have a look this [test](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginFunctionalTest.groovy#L62) for an example.

**Comment by bmuschko** [comment]
I am going to close the issue as I didn't get a response from you. Let me know if you need additional help.
