### ISSUE TITLE
Configuration issues when using docker tasks in new plugin

### ISSUE THREAD

**Issue by schnabel** [bmuschko/gradle-docker-plugin#910]
I am trying to use some of the docker tasks in my own plugin:

public class MyPlugin implements Plugin<Project> {
    public void apply(Project project) {

        MyExtension extension = project.getExtensions().create("myext", MyExtension.class);

        project.getTasks().register("pull", DockerPullImage.class, new Action<DockerPullImage>() {

            @Override
            public void execute(DockerPullImage task) {
                task.getImage().set(extension.getImage());
            }

        });
    }
}
This does not work as expected because the extension.getImage() is null (although it is set in the buildscript).

**Comment by schnabel** [comment]
This is related to [https://github.com/bmuschko/gradle-docker-plugin/issues/674]()

**Comment by bmuschko** [comment]
I don't think this is related to https://github.com/bmuschko/gradle-docker-plugin/issues/910. https://github.com/bmuschko/gradle-docker-plugin/issues/910 is just about using the `register` method etc. in the convention plugins.

I'd need to see your full code. Please create a GitHub repository that full reproduces the issue. IMHO I think your issue is just how you map a value from an extension to a task property. Did you have a chance to read this? https://guides.gradle.org/implementing-gradle-plugins/#capturing_user_input_to_configure_plugin_runtime_behavior

**Comment by schnabel** [comment]
Hi @bmuschko , 

I guess we both have a point. Lazy Configuration with Property solves my problem as you suggested. Nevertheless you might want to take a look at [my-plugin](https://github.com/schnabel/gradle-my-plugin) and [my patch](https://github.com/schnabel/gradle-docker-plugin/tree/ISSUE-910).
With this patch of the gradle-docker-plugin one can still use extensions without Property attributes.

**Comment by bmuschko** [comment]
The Provider concept and the task configuration avoidance API are somewhat orthogonal in its functionality. For https://github.com/bmuschko/gradle-docker-plugin/issues/674 I'd like to see the complete change to the task configuration avoidance API. Switching this over one by one can easily lead to unexpected side effects. Feel free to submit a PR for it.

**Comment by schnabel** [comment]
Did you have a look at the patch? All tests and functional tests still pass. I am certainly not an expert on this stuff. I just thought if it is recommended to use the register API and all tests pass with the patch it might be a good choice. It would help those that are not aware of the Provider/Property stuff :-).

**Comment by bmuschko** [comment]
> Did you have a look at the patch? 
I did have a look at the patch.

> It would help those that are not aware of the Provider/Property stuff.
The `Provider` API is the recommended way to implement lazy evaluation. The `register` method is more of a workaround here for your use case.

> I just thought if it is recommended to use the register API and all tests pass with the patch it might be a good choice.
I am not going to mix "register" and "create" methods to avoid unexpected side effects as mentioned above. I'd be happy to switch over to the task configuration avoidance API but it should be done across the board in this plugin.
