### ISSUE TITLE
Some Questions Task DockerStartContainer

### ISSUE THREAD

**Issue by chhex** [bmuschko/gradle-docker-plugin#911]
### Context
I am migrating docker scripts and docker-compose scripts  to the gradle builds using the gradle-docker-plugin, since we see a great potential for automated  functional integrations tests and this great plugin looks exactly like what we need.  What we are testing:  Gradle Bluilds with in-house developed Plugins used in Jenkins Pipelines. 

Specifically we are using a dockerized version of   https://github.com/jenkinsci/jenkinsfile-runner, see also https://github.com/jenkinsci/jenkinsfile-runner/blob/master/Dockerfile for Integration testing our Jenkins Pipeline code

Doing this i have come up with a couple questions, where i am stuck. Probably the answers are obvious. Naturally since the plugin is using a Java implementation of Docker Remote API, which is most likely using a Http based API, the API cannot naively mapped to docker commands .... 
but still ... Also probably the questions are covered in the documentation and i just missed them. Any pointer is welcomed. 

If this not the right place for the questions, please let me know.  

#### Command arguments in DockerStartContainer task
How to add command arguments  for example the following command to DockerStartContainer: 
`docker run -v /local/Jenkinsfile:/workspace/Jenkinsfile -v /local/jenkinsHome:/jenkinsHome ourJenkinsRunnerImage:lastest   --runHome /jenkinsHome --runWorkspace  /jenkinsWorkspace`

#### Docker run -v option
Does the docker run -v option as used in the above example correspond to the hostConfig.bind property of the DockerCreateContainer task ?
```
 hostConfig.binds = ["${projectDir}/Jenkinsfile":"/workspace/Jenkinsfile",
            "${projectDir}/jenkinsHome":"/jenkinsHome",  "${modulesToTestDir}":"/jenkinsWorkspace" ....]
```
#### Docker run -a Option 
Can i attach the STDIN, STDOUT or STDERR of the Running Docker Container, resp Run the Container not detached? Or is there a way of retrieving the log output of a running container?

Best thanks for the great work.

**Comment by chhex** [comment]
Looking into extending AbstractDockerRemoteApiTask and into https://github.com/docker-java/docker-java/wiki Examples and taking it from there

**Comment by bmuschko** [comment]
FYI: Various options may or may not be supported by this plugin. It's just a matter of keeping them in sync. I suggest you have look at the [Groovydoc](https://bmuschko.github.io/gradle-docker-plugin/api/) of this plugin.

**Comment by chhex** [comment]
Great, yes that helps. Actually i am backtracking again. I think most are supported. 
One quick question though

**Comment by chhex** [comment]
> FYI: Various options may or may not be supported by this plugin. It's just a matter of keeping them in sync. I suggest you have look at the [Groovydoc](https://bmuschko.github.io/gradle-docker-plugin/api/) of this plugin.

Everything is supported! Best thanks, the GroovyDoc helped.
