### ISSUE TITLE
Typing CTRL-C stops gradle but leave running containers

### ISSUE THREAD

**Issue by kazvictor** [bmuschko/gradle-docker-plugin#916]
Typing CTRL-C stops gradle but leave running containers. Is there a way to have it also stop the running containers. For example see this simple build.gradle
```groovy
plugins {
    id 'com.bmuschko.docker-remote-api' version '6.1.3'
}

import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer
import com.bmuschko.gradle.docker.tasks.container.DockerStartContainer
import com.bmuschko.gradle.docker.tasks.container.DockerWaitContainer
import com.bmuschko.gradle.docker.tasks.container.DockerLogsContainer

task createDockerfile(type: Dockerfile) {
    from('ubuntu')
    runCommand('printf "while : \\ndo \\necho "." \\nsleep 1 \\n done" > loop.sh && chmod +x loop.sh')
    entryPoint('/bin/bash')
    defaultCommand('./loop.sh')
}

task buildMyAppImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    images.add('mvn-builder:latest')
}

task createMyAppContainer(type: DockerCreateContainer) {
    dependsOn buildMyAppImage
    targetImageId buildMyAppImage.getImageId()
    attachStdout = true
    attachStdin = true
    tty = true
    hostConfig.autoRemove = true
}

task startMyAppContainer(type: DockerStartContainer) {
    dependsOn createMyAppContainer
    targetContainerId createMyAppContainer.getContainerId()
}

task logContainer(type: DockerLogsContainer) {
    dependsOn startMyAppContainer
    targetContainerId createMyAppContainer.getContainerId()
    follow = true
    tailAll = true
    onNext { message ->
        logger.quiet message.toString()
    }
}

task runMyContainer(type: DockerWaitContainer) {
    dependsOn logContainer
    targetContainerId createMyAppContainer.getContainerId()
}
```

### Expected Behavior

Run `gradle runMyContainer`
This will output '.' on a new line every second.
Type CTRL-C 
This stops the gradle process.
I would like this to also stop the running container.

### Current Behavior

The running container is not stopped. You can check that by typing:
`docker ps`
```log
CONTAINER ID        IMAGE               COMMAND                 CREATED             STATUS              PORTS               NAMES
2b03d4c58cbf        ead96e8359fe        "/bin/bash ./loop.sh"   21 seconds ago      Up 19 seconds                           nervous_allen
```

### Context

I'm using gradle to start a build docker container that will build my project. In this case I might want to prematurely cancel the build. When I do that by typing `CTRL-C` the gradle processes that started the build container is stopped the the actual build is still going on in the running build container.

### Steps to Reproduce (for bugs)

Using the above build.gradle run `gradle runMyContainer` then  type `CTRL-C`

### Your Environment

```
gradle --version

------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_242 (Private Build 25.242-b08)
OS:           Linux 4.15.0-74-generic amd64
```

**Comment by bmuschko** [comment]
> Type CTRL-C. This stops the gradle process.

CTRL+C does not stop the Gradle process, only the the build is canceled. The Gradle daemon will continue to run.

This plugin doesn't really start a process anyway. It simply communicates via the Docker remote API. You'd have to implement some sort of hook yourself if you want something to happen if the build ends. I am not sure which one would be most appropriate. Maybe `gradle.afterProject`? I'd ask about it on the Gradle forum, also check https://docs.gradle.org/current/userguide/build_lifecycle.html#build_lifecycle_events.

**Comment by amimas** [comment]
I'm running into the same issue. Unfortunately `gradle.buildFinished` doesn't execute when I cancel the build by `CTRL + C`. 

I'm on Gradle `6.4.1` and `6.4.0` of this plugin.

**Comment by cdancy** [comment]
@amimas have tried registering a shutdown hook?

**Comment by amimas** [comment]
I don't think so. Do you have a reference on how to do this?

**Comment by cdancy** [comment]
@amimas it's not specific to this plugin just an OOTB groovy feature. Check out [THIS ](https://mrhaki.blogspot.com/2010/01/groovy-goodness-add-shutdownhook.html)blog post for a simple explanation.

**Comment by caiolopes** [comment]
@cdancy I tried the `addShutdownHook` and is not working... Any other ideas?

**Comment by cdancy** [comment]
@caiolopes what exactly did you try to do? The containers themselves are part of docker and not this plugin. If you want to stop the container you need to invoke the necessary commands to do so in whatever context that may be. In this case all you really have is the shutdown hook. I've used this before with great success. Have you tried playing and confirmed that _some code_ gets executed when you do so? I posted a link below that you can use to vet that things are working as expected.

https://stackoverflow.com/questions/1611931/catching-ctrlc-in-java

**Comment by caiolopes** [comment]
@cdancy I have `build.gradle` very similar to the one in the issue showed by @kazvictor, but the container I start is an application dependency of the main java intended for local development not just to build (so, the only way to stop is by manually stopping with ctrl+c)

So, I mapped a task called `run` to a `DockerLogsContainer`, which keeps the terminal busy by running `./gradlew app:run`, but when I do a `ctrl+c` it stops the gradle build but not the container. I need to manually do a `docker rm app`

Right now my workaround is to have a `DockerStopContainer` and run it before starting again (catching error in case it does not exists), at least to avoid crashing the exposed port and name in case any developer forget and run a run again.

I tried the `addShutdownHook` you mentioned without success... Even tried with `--no-daemon` flag as [suggested here](https://stackoverflow.com/questions/22671927/shutdown-hook-of-java-process-doesnt-trigger-in-gradle-daemon).

I don't want to catch ctrl+c in java like you suggested because there is no java code on this module. This "application" is only a `build.gradle` with `docker-remote-api` tasks.

**Comment by caiolopes** [comment]
The perfect behaviour would be the same as running:

```
docker run --rm -p XXX:XXX image
```

Since it keeps attached and showing the stdout from the container, and if stopped (with ctrl+c) it removes the container.

But as I researched through the docs, there is no `DockerRunContainer`, so, I need to go through the steps:

- DockerCreateContainer
- DockerStartContainer
- DockerLogsContainer

**Comment by cdancy** [comment]
> I don't want to catch ctrl+c in java like you suggested because there is no java code on this module

@caiolopes it's all java underneath the hood despite what the build scripts would have you believe.

> So, I mapped a task called run to a DockerLogsContainer, which keeps the terminal busy by running ./gradlew app:run, but when I do a ctrl+c it stops the gradle build but not the container

This is expected as you're essentially doing the equivalent of `docker logs <my-container>`. Exiting out of that would not stop/kill the container and you shouldn't expect it to do so here.

> I need to manually do a ./gradlew app:stop

We do something similar here in that we have an `app:start` and `app:stop` and `app:destroy` tasks. This I believe is the more proper gradle way of doing things and fits better within the overall model. Expecting to catch a `ctrl-c` in build script code fundamentally feels wrong in my opinion (though it can be done as I noted above and I personally have done this in the past though I don't recommend it). You're already manually doing a `:app:start` to get things off the ground and so following up, when you're doing using the application, with a `:app:stop` feels like the right approach as far as gradle is concerned.
