### ISSUE TITLE
Support for npipes in docker-java upcoming. Any plans for integrating this?

### ISSUE THREAD

**Issue by berntie** [bmuschko/gradle-docker-plugin#917]
### Current Behavior
As of now, the gradle-docker-plugin requires that on Windows 10 tcp://localhost:2375 is exposed (cf. #854). This is due to limitations of docker-java (explained in #769).

As a consequence, you cannot use this plugin under Windows 10 with Linux containers, because in recent versions of Docker Desktop exposing the port [only works with Windows containers](https://github.com/docker/for-win/issues/453). (I've never tried this [horrible workaround](https://youtrack.jetbrains.com/issue/WI-32733#comment=27-1549346).)

Surprisingly, after 3 years of waiting, there's a [release candidate of docker-java](https://github.com/docker-java/docker-java/issues/765#issuecomment-584524438) that's supposed to fix the underlying issues.

It would be very helpful, if a)someone could verify that using this RC of docker-java fixes the problem on Windows and b)maybe provide a rough estimate about how long it would take until a release that uses the new docker-java version after it's released.

Thanks

**Comment by bmuschko** [comment]
> a)someone could verify that using this RC of docker-java fixes the problem on Windows

I don't have Windows so it would need to be someone else from the community. You could give it a shot assuming that you have a Windows machine.

> b)maybe provide a rough estimate about how long it would take until a release that uses the new docker-java version after it's released

Within in a week of the release of the final version of Docker Java.

**Comment by berntie** [comment]
Thanks for the estimate.

I dread the effort to build a test version (never built a gradle plugin before), but if nobody else will do it, maybe I'll give it a shot.

**Comment by bmuschko** [comment]
I am going to close this issue for now. We will definitely integrate the latest version of Docker Java as soon as they release the final. After that you can see if it fixes the issue. I don't suspect anyone to proactively try it out with an RC.

**Comment by berntie** [comment]
I see you've already switched to docker-java 3.2.0, thank you. Just to let you know: docker-java only supports npipe for windows [via OkHttp](https://github.com/docker-java/docker-java/issues/765#issuecomment-588942835). 

Do you have plans to switch to OkHttp (as far as I can tell, you're still [using netty](https://github.com/bmuschko/gradle-docker-plugin/blob/0ae511f9b0a7f95c8614d676fc54c142713a01a3/src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy#L180))? If not, would you be willing to switch, if I provided a patch?

**Comment by cdancy** [comment]
@berntie would it be something like "if windows then use this factory else use this one"?

**Comment by bmuschko** [comment]
@cdancy I'd vote for "no magical behavior". I'd make OkHttp simply the default with the option to switch to other implementation. Jersey is a poor option anyway. Moreover, the TestContainers project seems to have used OkHttp for a long time and it seems to be working pretty well for them.

**Comment by cdancy** [comment]
Agreed. Nothing but good things to say around `OkHttp` from my end and if the default "just works" across the board then lets use that. We've got lots of folks here who use native docker on windows (I don't because I'm not a crazy person :) ) and so this would be a win for them as they'd be able to use the plugin without having to expose ports and have things just work.

**Comment by bmuschko** [comment]
@cdancy Switching to OkHttp may also remove the requirement for having to support that Netty switch if it just works fine.

@berntie Go ahead. In the code that switches between the implementations, make OkHttp the default.

**Comment by cdancy** [comment]
Yeah we've been using the switch here in production since I put it in with no issues to speak of thus far. I don't know if I'd call that a win, or an OK to move forward, but it's working in our pipeline with no issues which is massive and so that has to count for something ;)

**Comment by berntie** [comment]
Easy, @bmuschko , easy, please. I've already failed a quick try to build a version with OkHttp. ;-)

Nonetheless, if you don't plan to do the switch yourself I might give it another shot. I assume your plugin would make my life a lot easier.

**Comment by bmuschko** [comment]
@berntie 
> If not, would you be willing to switch, if I provided a patch?

You made it sound like you wanted to provide a PR. ;-) I am not planning to work on that particular change myself in the near future.

**Comment by berntie** [comment]
Sorry for the misunderstanding. To make it clear: No, I don't quite _want_ to provide a PR, but I might if I have to _and_ if I can produce a fairly reasonable patch. ;-)

**Comment by AceHack** [comment]
Any plan to support this?

**Comment by bmuschko** [comment]
@AceHack As mentioned in the discussion above, we'll support if someone from the community provides a pull request for it.
