### ISSUE TITLE
Keep the Network Name and Network Id separate in DockerCreateNetwork

### ISSUE THREAD

**Issue by avinash-traceable** [bmuschko/gradle-docker-plugin#920]
There should be a clear distinction between Network Name and Network Id for the DockerCreateNetwork task similar to the Container Name and Container Id in DockerCreateContainer task

We have a case where we register a common task for all sub projects with a fixed name like this:
```
tasks.register<DockerCreateNetwork>("createTestNetwork") {
            networkId.set("test-network")
        }
```
There is another task say `createTestContainer` within each of the sub projects that depends on the `test-network` above

```
tasks.register<DockerCreateContainer>("createTestContainer") {
            dependsOn("createTestNetwork")
            network.set(tasks.getByName<DockerCreateNetwork>("createTestNetwork").networkId)
            ...
        }
```
Now because of the parallel execution, the sub project's `createTestContainer` tasks step over the test-network created by other sub projects because DockerCreateNetwork sets the network name(i.e test-network) as the networkId

**Comment by bmuschko** [comment]
I think the implementation of `DockerCreateNetwork` isn't right at the moment. The input property should be the name of the network. In addition, the network ID should be captured from the response of creating the network. Care you send a pull request?

**Comment by bmuschko** [comment]
Will be fixed with the next version.
