### ISSUE TITLE
SpringBootApplication ECR-Gradle-Plugin dockerPushImage not working due to TAG

### ISSUE THREAD

**Issue by hamdijaw** [bmuschko/gradle-docker-plugin#921]
The problem that I am facing is that I am not able to push docker image to ECR.
Docker Image is getting built successfully but it's not getting pushed as I am not aware how do I prepend the ECR url to my Docker Tag for Docker Push to work for ECR. I tried using 'tag' but then got the error :
_> Could not set unknown property 'tag' for extension 'springBootApplication' of type com.bmuschko.gradle.docker.DockerSpringBootApplication_.

**---- Gradle File Starts ----**
plugins {
        id 'org.springframework.boot' version '2.2.4.RELEASE'
        id 'io.spring.dependency-management' version '1.0.9.RELEASE'
        id 'java'
        id "com.patdouble.awsecr" version "0.6.0"
        id 'com.bmuschko.docker-spring-boot-application' version '6.1.3'
}

docker {
        springBootApplication {
                baseImage = 'openjdk:8-alpine'
                ports = [9091, 9091]                
                images = ['my_ecr_repo/firstms:1.4']
        }

        registryCredentials {
                url = 'https://123456789.dkr.ecr.us-east-1.amazonaws.com'
        }
}
**---- Gradle File Ends ----**
**---- dockerPushImage command  Starts ---**
[user@localhost firstms]$ ./gradlew dockerPushImage -PawsAccessKeyId=MY_ACCESS_ID -PawsSecretAccessKey=MY_SECRET

> Task :dockerPushImage
Pushing image 'my_ecr_repo/firstms:1.6'.

_> Task :dockerPushImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerPushImage'.
> Could not push image: denied: requested access to the resource is denied_

**---- dockerPushImage command  Ends ---**

**Comment by orzeh** [comment]
@hamdijaw please try to add ECR url to `images` property like:
````groovy
images = ['123456789.dkr.ecr.us-east-1.amazonaws.com/my_ecr_repo/firstms:1.4']
````
Also you have to specify username and password in `registryCredentials` closure. User your AWS credential there.

**Comment by hamdijaw** [comment]
Thanks Orzeh for the suggestion, I had earlier tried url in images earlier but then it's not able to distinguish my repo.
If I give this: images = ['123456789.dkr.ecr.us-east-1.amazonaws.com/my_ecr_repo/firstms:1.4']
I am getting following error:
---- Error Starts ----
Successfully built 886843c7d314
Successfully tagged 123456789.dkr.ecr.us-east-1.amazonaws.com/my_ecr_repo/firstms:1.4
Created image with ID '886843c7d314'.

> Task :dockerPushImage
Pushing image '123456789.dkr.ecr.us-east-1.amazonaws.com/my_ecr_repo/firstms:1.4'.

> Task :dockerPushImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerPushImage'.
> Could not push image: name unknown: The repository with name 'my_ecr_repo/firstms' does not exist in the registry with id '123456789'
---- Error Ends ----

**Comment by bmuschko** [comment]
You may rather want to stick to the issue you created for the other plugin: https://bitbucket.org/double16/gradle-aws-ecr-plugin/issues/20/springbootapplication-ecr-gradle-plugin. I am not exactly sure if the version of `com.patdouble.awsecr` is still compatible with the latest version of `com.bmuschko.docker-spring-boot-application`.

**Comment by hamdijaw** [comment]
Thanks bmuschko. Which version do you recommend of "com.patdouble.awsecr" and "com.bmuschko.docker-spring-boot-application" that are known to be compatible?

**Comment by hamdijaw** [comment]
@bmuschko : Thanks for your help.
I found the fix, the issue was with my tag. Note this was causing the issue ":1.4"
Earlier (did not work):  images = ['123456789.dkr.ecr.us-east-1.amazonaws.com/venu_docker_repo:firstms_**:1.4**_']
**Later (worked)**: images = ['123456789.dkr.ecr.us-east-1.amazonaws.com/venu_docker_repo:firstms']

**Comment by orzeh** [comment]
@hamdijaw as per [AWS ECR documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html) image tag has the following scheme:
````
[aws_account_id].dkr.ecr.region.amazonaws.com/[repository_name]:[tag]
````
I guess `[repository_name]` can't contain `/` characters so in your case `my_ecr_repo/firstms` won't work. If `firstms` is your tag, then the solution you found is correct.

**Comment by hamdijaw** [comment]
Thanks @orzeh
