### ISSUE TITLE
Cannot mutualize registry credentials in a multi-project

### ISSUE THREAD

**Issue by bgranvea** [bmuschko/gradle-docker-plugin#922]
### Expected Behavior
In a multi-project context, I would like to define registry credentials in root build.gradle

### Current Behavior
I get an error "could not push image: errors: denied: requested access to the resource is denied. unauthorized: authentication required".

If I define the credentials in the subproject, it works.

### Steps to Reproduce (for bugs)
- unzip testDockerPush.zip
[testDockerPush.zip](https://github.com/bmuschko/gradle-docker-plugin/files/4274496/testDockerPush.zip)

- execute gradle pushDockerImage

### Your Environment
Gradle 6.2.1, Windows 10, Docker desktop 2.2.0.3

**Comment by bmuschko** [comment]
I briefly had a look at your sample project. Why are you applying the plugin on the root level and then again in the subproject? It likely causes things to be changed that you set in the root project.

I'd just do the following:

```
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:6.1.4'
    }

subprojects {
    apply plugin: 'com.bmuschko.docker-remote-api'
}
```

Remove all other references of the plugin. Also, you might just want to use the [plugin extension](https://bmuschko.github.io/gradle-docker-plugin/#extension) which automatically injects the credentials into the necessary tasks.

**Comment by bgranvea** [comment]
yes it seems better if plugin is not defined at root level, thanks! I'm new to Gradle and I'm still struggling to structure my multi-project.

**Comment by bmuschko** [comment]
Does that mean you could get it to work and we can close this issue?

**Comment by bgranvea** [comment]
yes it's working now, thanks.
