### ISSUE TITLE
Setting working directory for exec command

### ISSUE THREAD

**Issue by danez** [bmuschko/gradle-docker-plugin#924]
### Proposed Feature

Add support for changing the working directory in `DockerExecContainer` for the current command. It should be possible as docker-java has an option for it: https://github.com/docker-java/docker-java/blob/master/docker-java-api/src/main/java/com/github/dockerjava/api/command/ExecCreateCmd.java#L55

**Comment by orzeh** [comment]
@danez are you interested in submitting PR for this?

**Comment by danez** [comment]
Yeah I can look into this at some point.
