### ISSUE TITLE
Redirect DockerExecContainer output to a variable?

### ISSUE THREAD

**Issue by pskowronek** [bmuschko/gradle-docker-plugin#928]
Is there some swift way to redirect DockerExecContainer output to a variable? I mean without hacking with gradle standard output redirection. For example Exec task has standardOutput which can be overridden so the output can be set to a variable.

Any hint appreciated :)

**Comment by bmuschko** [comment]
It doesn't look like Docker Java's `ExecCreateCmd` supports passing in a Writer some or other reference to capture the output. I guess you could provide your own `nextHandler` to process each line and do something with it. I believe that should work.

**Comment by pskowronek** [comment]
Thanks for an update.

For future reference, to log the output from DockerExecContainer one must do something like this:
```
task testDockerExecContainer(type: DockerExecContainer) {
        targetContainerId { theContainerId }
        withCommand(['excho', 'it works'])
        user = 'some user'
        successOnExitCodes = [ 0 ]

        onNext { frame ->
           def consoleOut = new String(frame.payload, "UTF-8")
           println("Got results: ${consoleOut}")
        }
}
```

Thinking out loud, having an easier way could be beneficial, something similar to gradle's Exec:
```
task testExec(type:Exec) {
  commandLine "echo", "it works"
  standardOutput new FileOutputStream("${buildDir}/testtest.out")
}
```
However you say that Docker Java's `ExecCreateCmd` won't help here much, right?

**Comment by bmuschko** [comment]
> However you say that Docker Java's ExecCreateCmd won't help here much, right?

AFAIK, no. But have a look at their API or ask on their Gitter account.
