### ISSUE TITLE
Push images with dash in image namespace name

### ISSUE THREAD

**Issue by HelmutZechmann** [bmuschko/gradle-docker-plugin#93]
Hi, 
when I try to push an image with a dash in the namespace name using DockerPushImage, I get the following error message:

    Invalid namespace name (cdh-images), only [a-z0-9_] are allowed, size between 4 and 30

The follwoing does not work:

    task pushWithDatasetManagementImage(type: DockerPushImage) {
        imageName '<repository-ip>:5000/cdh-images/dashes-are-allowed-here'
    }

This works:

    docker push <repository-ip>:5000/cdh-images/dashes-are-allowed-here
This works:

    task pushWithDatasetManagementImage(type: DockerPushImage) {
        imageName '<repository-ip>:5000/cdh_images/dashes-are-allowed-here'
    }

**Comment by bmuschko** [comment]
The error message is triggered by the underlying [Docker Java library](https://github.com/docker-java/docker-java). Can you please raise an issue there?

**Comment by HelmutZechmann** [comment]
Thank you, 

I raised https://github.com/docker-java/docker-java/issues/290.
