### ISSUE TITLE
How can I set a dynamic tag (project version) when creating docker images

### ISSUE THREAD

**Issue by cowrytekdev** [bmuschko/gradle-docker-plugin#930]
### Expected Behavior
I want to be able to provide a dynamic docker image tag for the image to be created in my build.gradle
`springBootApplication {
        baseImage = 'adoptopenjdk/openjdk11:alpine-jre'
        maintainer = 'maintainer@example.com'
        ports = [8080]
        images = ['localhost:8082/my-service:${project.version}'] <---- something like this
    }`

### Current Behavior
When I run `./gradlew dockerBuildImage`, it says `The template variable 'project.version' has no value`

### Context
I want to be able to build images with a dynamic tag without having to explicitly set the tag every time the version changes

### Your Environment
The environment consists of a java 11 microservice using spring boot.

**Comment by bmuschko** [comment]
Are you asking about Docker's `latest` tag? I think I'd like to understand what you mean by "dynamic" tag and what your use case is you are trying to solve. Can you clarify?

**Comment by cowrytekdev** [comment]
Hi, Thanks for your quick response. I have a gradle project with a version 1.0.0. I want to be able to set my docker image tag using that version in a dynamic way. That means my image would be myimage:1.0.0. The next time the project version changes to 1.0.1, the image tag should be 1.0.1 after a new build --> myimage:1.0.1 and this without me having to change the version in the plugin settings like this. `images = ['myimage:1.0.1]`

**Comment by bmuschko** [comment]
What you are describing is not really a feature of a Docker plugin. The Docker plugin uses whatever you provide to it. Version management and how/when you want to release your project is a different concern. I wrote a blog post a while ago: [Implementing an intuitive versioning and release strategy](https://bmuschko.com/blog/gradle-release-strategy/). It describes _one_ strategy but which one you prefer is really up the requirements of your project.

**Comment by bmuschko** [comment]
Closing the issue as the concerns are orthogonal.
