### ISSUE TITLE
Allow the specification of an access mode when mounting volumes using volumesFrom

### ISSUE THREAD

**Issue by d-vesely** [bmuschko/gradle-docker-plugin#931]
The plugin's `DockerCreateContainer` class/task does not support mounting volumes from a container (via `--volumes-from` respectively `hostConfig.volumesFrom`) in **read-only** mode.

### Expected Behavior

`DockerCreateContainer.HostConfig` does not facilitate the mounting of existing volumes via `--volumes-from` in **read-only** mode. By using a `mapProperty` instead of a `listProperty`, users should be able to append an access mode enum value (`com.github.dockerjava.api.model.AccessMode.java`) as a String (either `"ro"` or `"rw"`).  In `setContainerCommandConfig()`, the list of `com.github.dockerjava.api.model.VolumesFrom.java` objects (`List<VolumesFrom>`) would be created analogously to binds, using `VolumesFrom.parse()` instead of the constructor, which adds the default access mode, which is read-write. 

### Current Behavior

Currently, a list of container names can be passed to `hostConfig.volumesFrom`. These container names are then passed into the constructor `public VolumesFrom(String container)` in `com.github.dockerjava.api.model.VolumesFrom.java`. Said constructor adds the default access mode, which is read-write. Thus, there is no possibility of mounting a container's volume in read-only mode.

### Context

I am trying to mount a volume of an existing container (via `--volumes-from`) in read-only mode, which is possible but cannot be done using this plugin as of now.

**Comment by bmuschko** [comment]
Can you please provide a pull request for this? I am not going to get around to implementing this.

**Comment by bmuschko** [comment]
I am going to close this issue as we haven't received a pull request. Let me know if you are up for providing a PR.
