### ISSUE TITLE
extraHosts should have effect?

### ISSUE THREAD

**Issue by Bartman0** [bmuschko/gradle-docker-plugin#941]
### Expected Behavior

I would expect this: 

task buildImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    extraHosts.add("env-185611laioeuw1:10.202.11.170")
    images.add("${System.env.DOCKER_REGISTRY}/led/rda:latest")
}

... to add extra host entries in the container.

### Current Behavior
I see no effect of the extraHosts.add("env-185611laioeuw1:10.202.11.170")

From the original docker docs I gather that the way to go is to use:
docker run --add-host="" ......

So, does that extraHosts have any effect?
If so, how to see that back?
### Context
I would like to have an additional host entry effective in the container.

**Comment by bmuschko** [comment]
I am not fully sure how Docker Java handles this internally. Be aware that the Docker daemon might handle it differently than the Docker command line executable. Any chance you can look into adding a functional test for the use case?

**Comment by bmuschko** [comment]
What's the status on this?

**Comment by Bartman0** [comment]
no progress so far.



Richard Kooijman
Advanced Analytics Architect
Inergy
Pelmolenlaan 2 • 3447 GW Woerden • T: +31 348 457 666 • M: +31 631 673 387 • www.inergy.nl
Magazine Inergy | Heb jij het al gelezen?
Summer school | Geef je snel op voor een webinar of training
Blog | Met Managed Data Platform hoeft de klant zich geen zorgen te maken over de data omgeving
On 9 Jul 2020, at 14:49, Benjamin Muschko <notifications@github.com<mailto:notifications@github.com>> wrote:



What's the status on this?

**Comment by bmuschko** [comment]
OK, I'll close this issue for now. Feel free to reopen when you have time to provide more information or gained deeper insight.
