### ISSUE TITLE
registryCredentials in build script do not take precedence

### ISSUE THREAD

**Issue by matteomazza91** [bmuschko/gradle-docker-plugin#944]
### Expected Behavior
if registryCredentials is used, it could override other credentials (e.g. `~/.docker/config.json`). 

If authentication is done through an auth token that can expire, the build script can automatically generate one and use it in registryCredentials. registryCredential should override any (possibly expired) token configured on the machine (e.g. in `~/.docker/config.json` or cred stores)

```
task pushMyDockerImage(type: DockerPushImage) {
  registryCredentials {
    username = tasks.createAuthToken.username
    password = tasks.createAuthToken.authToken
    url = ....
  }
images = ....
}
```

### Current Behavior
The auth configured in credStore take precedence and force the user to run a `docker login` command with a new auth token.

### Context
automating a deployment in aws that require to build and push a docker image to AWS ECR

**Comment by bmuschko** [comment]
Reading your issue report, I would argue that the build script should overwrite everything it already finds in existing credentials. Can you describe your use case and why you think it should behave differently? IMHO it works as expected right now.

**Comment by artemananiev** [comment]
I have just updated docker plugin to version 6.4.0 in my project and immediately hit this issue. I second to @matteomazza91, it looks like a bug. At the very least it should be configurable, whether credentials provided in the build script should override existing docker client auth credentials in ~/.docker.

My use case is the following. I have two docker registries, where I need to push my images. Host names for both are the same (let's call them docker.mycompany.com/r1 and docker.mycompany.com/r2), so from docker perspective this is a single registry, but they actually aren't, and they have different credentials. For development, I use one of them, this is where I run `docker login` for. So my ~/.docker/config.json contains an entry for "docker.mycompany.com" with "r1" credentials. When I'm done with development, I need to push the image to the other registry. This process is automated, I can run gradle with different properties and modify registryCredentials on the fly. However, it doesn't work as ~/.docker/config.json takes precedence, and it always uses "r1" auth, even if registryCredentials in gradle corresponds to "r2".

A workaround is simple, but annoying: just run "docker logout" before running gradle. Given than the use case above is simplified (there may be more than just two registries), it may become quite painful.

**Comment by bmuschko** [comment]
> At the very least it should be configurable, whether credentials provided in the build script should override existing docker client auth credentials in ~/.docker.

Why should that be configurable explicitly with some sort of flag? If you set credentials in the build script then it overwrites the ones the plugin find under `~/.docker`? I'd argue that is configurability right there. Furthermore, remember that you can have any logic in a Gradle build so if want something more configurable then use an if/else block, project properties or whatever you think is suitable.

I think what @matteomazza91 brought up is that you _cannot_ override the credentials found in `~/.docker` through the plugin extension. I would suggest the following:

1. Add a functional test as pull request that proves that the credentials found in `~/.docker` can or cannot be override at the moment. Any takers?
2. Fix the underlying the problem if there is one.

**Comment by matteomazza91** [comment]
I'll try to add the functional test because I do have some auth issues that #945 fixes.

**Comment by bmuschko** [comment]
@matteomazza91 That'd be great. Thanks!

**Comment by matteomazza91** [comment]
functional test added in the same PR #945  
@bmuschko let me know if it looks good to you or if I should change/refactor something 👍
