### ISSUE TITLE
Invalid permissions when COPY/ADD

### ISSUE THREAD

**Issue by tomaszmichalak** [bmuschko/gradle-docker-plugin#947]
Original file permissions are lost.

### Expected Behavior

Keep the original file permissions (`600`):
```
-rw------- 1 root root 2635 Jun 24 14:06 /var/jenkins_home/.ssh/id_rsa
```

### Current Behavior
File permissions are changed from `600` to `644`.

So we have:
```
-rw-r--r-- 1 root root 2635 Jun 24 14:06 /var/jenkins_home/.ssh/id_rsa
```
instead of:
```
-rw------- 1 root root 2635 Jun 24 14:06 /var/jenkins_home/.ssh/id_rsa
```

### Steps to Reproduce (for bugs)

I created a sample Dockerfile:
```
FROM jenkins/jenkins:2.222.4-lts-jdk11

ADD ./config/user/.ssh/id_rsa ${JENKINS_HOME}/.ssh/
RUN /bin/bash -c 'ls -al ${JENKINS_HOME}/.ssh/id_rsa'
```
When I build image with command:
```
docker build -t tm-jenkins-test:latest .
```
then in output I can see:
```
-rw------- 1 root root 2635 Jun 24 14:06 /var/jenkins_home/.ssh/id_rsa
```

When I use the Gradle plugin I get:
```
 ---> Running in 08e78803b963
-rw-r--r-- 1 root root 2635 Jun 24 14:06 /var/jenkins_home/.ssh/id_rsa
```

### Your Environment

Docker Desktop 2.3.0.3 (45519) for Mac.
Engine: 19.03.8.

**Comment by bmuschko** [comment]
From what I can see you are only referencing Docker-internal tooling e.g. a `Dockerfile` and `docker build`. Could you please provide sample code that you use fro this plugin?

**Comment by tomaszmichalak** [comment]
This is how we build Docker image:
```
val buildImage = tasks.register<DockerBuildImage>("buildImage") {
    group = "docker"
    inputDir.set(file("$buildDir"))
    images.add("${project.property("docker.image.name")}:latest")

    # some preparation step, here I copy .ssh/id_rsa file to $buildDir
    dependsOn("removeImage", "prepareDocker")
}
```

**Comment by tomaszmichalak** [comment]
I will public the solution soon on GitHub.

**Comment by bmuschko** [comment]
If you are not using the `Dockerfile` task of this plugin to build the content dynamically then this plugin is not changing the permissions. The `DockerBuildImage` just calls off to Docker Java and the actually building of the image happens there.

**Comment by bmuschko** [comment]
Did you figure out the root cause of the issue in the meantime?

**Comment by bmuschko** [comment]
Closing, as we haven't heard back. Let us know if you want to further discuss.
