### ISSUE TITLE
DockerBuild runs forever

### ISSUE THREAD

**Issue by Writtscher** [bmuschko/gradle-docker-plugin#948]
I have a simple spring-boot-gradle application and applied the spring-boot and remote-api plugin. Running dockerBuildImage takes ages without doing anything. Cannot figure out what is happening as nothing is logged. Not even exception thrown after 15 min..

### Expected Behavior
* DockerFile created (Works)
* Docker image created

### Current Behavior
Running forever..

### Steps to Reproduce (for bugs)
I have a very basic gradle project and applied the required plugins. 

### Your Environment
Docker: 2.2.0.0
Gradle: 6.5
Plugin: 6.4.0
OS: OSX

**Comment by bmuschko** [comment]
My guess is that it takes a while to download your base image and/or other tools you need in your Docker image. You can [register a callback handler](https://bmuschko.github.io/gradle-docker-plugin/#reactive_streams) to look at deals while the operation runs.

**Comment by bmuschko** [comment]
Did this issue clear up for you?

**Comment by Writtscher** [comment]
Hi. I switched to https://github.com/GoogleContainerTools/jib. More complicated plugin but enables kubernetes as well.

So I have not debugged it any longer.

I close it.
