### ISSUE TITLE
Add the ability to perform a docker image prune

### ISSUE THREAD

**Issue by ArvinB** [bmuschko/gradle-docker-plugin#950]
Enhancement request to perform a `docker image prune` with all the switches

-a for all images
-f for force (enabled by default)
--filter

### Expected Behavior
As a gradle task of type `DockerPruneImage`

### Current Behavior
This functionality doesn't exist to prune unused images.

### Context
The benefit of having this feature is to start out with a clean Docker registry

**Comment by bmuschko** [comment]
Remember that the plugin doesn't use the Docker command line executable. It uses the Docker daemon. So if Docker Java exposes the functionality then we could build something like that. I am not going to have to time to implement it. Are you interested in working on a pull request? Happy to review.

**Comment by ArvinB** [comment]
@bmuschko Yep I can work on it in my spare time. The [Docker Java doc](https://javadoc.io/doc/com.github.docker-java/docker-java-api/latest/com/github/dockerjava/api/command/PruneCmd.html) I believe supports this as well.

**Comment by bmuschko** [comment]
I am going to close this issues for now. Feel free to reopen when you get around to working on it.
