### ISSUE TITLE
Question Is it possible to call the functions as an extension from a single task

### ISSUE THREAD

**Issue by ArvinB** [bmuschko/gradle-docker-plugin#951]
Quick question, since I'm struggling with having multiple tiny tasks and would prefer to consolidate a bit (even though gradle is not designed for it).

What I would like to do is something like this:

```

task myTask {

    doLast {
    
        DockerBuildImage { 
           ....
        }

        DockerPushImage { 
           ....
        }

        DockerRemoveImage { 
           ....
        }
    }
}
```

**Comment by bmuschko** [comment]
This is really more of a general Gradle question. Please ask those at the [Gradle forum](https://discuss.gradle.org/).

In short, you can't compose tasks. You'll need to model the use case with the help of task dependencies. Something like this:

```
task dockerBuildImage(type: DockerBuildImage)

task dockerPushImage(type: DockerPushImage) {
    dependsOn dockerBuildImage
}

task dockerRemoveImage(type: DockerRemoveImage) {
    dependsOn dockerPushImage
}

myTask.dependsOn dockerBuildImage, dockerPushImage, dockerRemoveImage
```

**Comment by ArvinB** [comment]
Thank you @bmuschko 

The reason why I was asking here is because of how the source code for `DockerBuildImage` and other types were authored. I am not familiar with the source which is why I was asking. I dug through the code to look for something like this or some other implementation that does the same thing but could not find it.

```
public void apply(Project project) {
        project.getExtensions().create("dockerbuildimage", DockerBuildImage.class, project);
        ExtraPropertiesExtension extraProperties =
                project.getExtensions().getExtraProperties();
        extraProperties.set(DockerBuildImage.class.getSimpleName(), DockerBuildImage.class);
}
```

**Comment by bmuschko** [comment]
You cannot bind a task to an extension as that is not the intention of the concept. If you want to use the "build image" or "push image" functionality then you'll need to use Docker Java directly without the tasks provided by this plugin. The tasks are really only a wrapper around Docker Java for the most part.

**Comment by bmuschko** [comment]
When you try to create something you proposed in the code above, also ask yourself "why". What's the benefit of doing something like you describe you can just configure tasks without an extension. That's definitely something you'd need to describe when you open an issue. I don't even understand what you are trying to achieve.

**Comment by ArvinB** [comment]
I'm not meaning to come across as arguing. I believe the code snippet I gave doesn't bind a task to an extension, but rather it adds the `DockerBuildImage.class` as a project extension then sets it as a property available to the project. The intent is to call the class as I originally was asking, as a property.

For reference, here is another plugin that does this.

https://github.com/michel-kraemer/gradle-download-task

You can see from the read me, you can call the plugin one of two ways:

A.
```
task myTask( type: Download ) { ... }
```

B.
```
task myTask {
    doLast {
         download { ... }
    }
}
```

I should have been clearer in my original question and for that I am very sorry.

**Comment by bmuschko** [comment]
Got it. I understand why the plugin author wants to do here but that's not how it should be implemented from my perspective. He's in fact binding a task type to an extension property. First of all, I'd completely decouple the download functionality from the task type if you want to be able to reuse it. Then, I'd not use the extension concept but bind it through an extra method. Those are two different concepts. I understand that Gradle core didn't provide distinguishing naming here. There are many open source Gradle plugins out there. A lot of them use concepts incorrectly unfortunately. So if you beginners to Gradle look at other plugins, it doesn't necessarily mean that those plugins are "good" implementations. It's a Gradle documentation and education issue for the most part.

Either way. In the Gradle Docker plugin a task wraps the Docker Java functionality for the most part. So if you want to have "build image", "push image", "remove image" as part of a task action then simply use the Docker Java API without any kind of DSL weirdness. There's no benefit to it. Furthermore, implement the task as a custom task and not an ad hoc task inside of the build script. Here's an example: https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTaskFunctionalTest.groovy#L21-L47. Modify that example by calling the relevant Docker Java methods for building, pushing and removing an image. You already have an instance of the client.

**Comment by ArvinB** [comment]
@bmuschko Thank you, exactly what I was looking for. Also I get that some implementations are done correctly versus others that could be done better. I can tell you clearly know how things should be, which is the other reason why I was asking here.

Again thank you very much!
