### ISSUE TITLE
How to pass docker registry URL at build time?

### ISSUE THREAD

**Issue by asarkar** [bmuschko/gradle-docker-plugin#953]
I've a use case where the docker registry URL depends on the build environment, so we need to pass the URL at build time instead of hard coding it. How can this be achieved using Spring Boot 2.3.1.RELEASE and plugin version 6.6.0?

**Comment by bmuschko** [comment]
This is more or less a general Gradle question. You can use any imperative logic you like. For example:

```
docker {
    url = project.getProperty('registryUrl')
}
```

**Comment by asarkar** [comment]
@bmuschko Of course I can write code, but I was curious to know if there’s an extension property on the plugin that could be set. If not, can we convert this ticket to a feature request for that purpose?

**Comment by bmuschko** [comment]
We are not planning to implement and maintain "magic properties". This is something a project can easily implement itself if needed.

**Comment by asarkar** [comment]
You mean almost _every_ project can implement, instead of implementing in one place? OK.
