### ISSUE TITLE
Issue with remote api and DockerBuildImage

### ISSUE THREAD

**Issue by leforthomas** [bmuschko/gradle-docker-plugin#960]
I want to build my image using a remote docker daemon. When I run it I get Status 500: {"message":"Cannot locate specified Dockerfile: /C:/Users/thomas/xxxx/docker/Dockerfile"}. It looks as if the files are not copied across to the remote server?

### Expected Behavior

It should copy the files to the remote server and run the docker build.

### Context

These are my gradle files

docker {
    url = 'tcp://xxx.yyy.zzz.uuu:2376'
}

// Import task types
import com.bmuschko.gradle.docker.tasks.image.*

// Use task types
task buildImage(type: DockerBuildImage) {
    dockerFile = file('docker/Dockerfile')
    inputDir = project.layout.buildDirectory.dir('libs')
    images.add('geocento/orderhandler:latest')
}

I then run the task using the gradle window (I'm in Intellij). The task connects fine to the remote daemon but fails with the above mentioned error message.

### Your Environment

Intellij Ultimate, Gradle, remote server is under Ubuntu 18.04. I can build the image on my remote server using the docker support from Intellij but I would like to do this in an automated way with Gradle.

**Comment by bmuschko** [comment]
Please provide a pull request if you'd like to see this functionality. Thanks!
