### ISSUE TITLE
Option to add --no-cache and --pull

### ISSUE THREAD

**Issue by jorkzijlstra** [bmuschko/gradle-docker-plugin#961]
Is there an option to completely disable caching for the base images, usually by using the --no-cache and --pull on the docker build commands?

### Context

We would like to reference a base image like openjdk:11-jre. Once a specific version is pulled it becomes part of the local docker cache. However this image is being updated with each release. Which is why we need to option to force pull the image, which is usually done by adding the build args `--no-cache` and `--pull` to the docker command.

**Comment by bmuschko** [comment]
Yes, the Groovydocs list all available properties for all custom tasks. The Groovydocs are linked in the user guide and can be accessed from the README as well.

* https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#noCache
* https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#pull

**Comment by bmuschko** [comment]
As of now, it looks like we are only providing those properties for the build task. I am sure Docker Java supports them though. Are you asking specifically for pull or will build fulfill the use case?

**Comment by jorkzijlstra** [comment]
Build time is actually what I'm looking for. Did I overlook something in the documentation on how to enable this?

**Comment by jorkzijlstra** [comment]
In my mail I see that you actually gave the answer earlier, but somehow its not showing here?

For reference:
```
Yes, the Groovydocs list all available properties for all custom tasks. The Groovydocs are linked in the user guide and can be accessed from the README as well.

https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#noCache
https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#pull
```

**Comment by jorkzijlstra** [comment]
Thnx for the quick reply

**Comment by bmuschko** [comment]
Yeah, I was thinking you needed it at build-time. But then saw that you mentioned "pull". Looks like we are on the same page.
