### ISSUE TITLE
RegistryAuthLocator is not supported on Windows

### ISSUE THREAD

**Issue by tomqwpl** [bmuschko/gradle-docker-plugin#965]
### Expected Behavior
To have the same behaviour when pushing images through docker command line

### Current Behavior
Doesn't honour credential store on Windows

### Context
I've been struggling to push images.  I have the windows credential helper configured for docker.
Issue #899 lead me to the trace log entries to search for, and an indication that it ought to be using  the credential helper to resolve credentials, but it turns out that instead I get a trace log message of "RegistryAuthLocator is not supported on Windows". 

### Your Environment
Windows 10.
Plugin version 6.6.1

**Comment by tomqwpl** [comment]
Note that having removed "credStore" from the ~/.docker/config.json file and done a docker login again, I _still_ get "unauthorized: The client does not have permission to push to the repository." out of the gradle plugin.

I can however push the same image to the same place with the normal docker command line.

I can find nothing obvious in the gradle debug output that indicates what credentials it might be resolving or where if might be resolving them from.

**Comment by bmuschko** [comment]
I am not quite sure how to help you out with this. I do not have a Windows machine. Maybe some other community member has an idea on what's going on.
