### ISSUE TITLE
Feature Request: containerUser configuration item for java application plugin

### ISSUE THREAD

**Issue by matthew-long** [bmuschko/gradle-docker-plugin#966]
It would be nice to have the ability to set a containerUser property in the javaApplication extension which results in the application running as a non root user.

### Expected Behavior
The remote api plugin provides primitives to allow for COPY/ADD instructions with CHOWN.
Allow a user to define a containerUser in the javaApplication extension that is used to set a UserInstruction, and add withChown calls to all CopyFile/AddFile instructions when constructing the Dockerfile.

### Current Behavior
This would allow easy configuration for the container to execute as a non root user.

### Context
I'd like to take advantage of the opinionated javaApplication plugin to minimise the amount of code in my build.gradle, while maintaining the ability to have my container execute as a non root user.

### Your Environment
Pop!_OS 20.04

**Comment by bmuschko** [comment]
You are right that there's no convenient way to set a different user and then add files with that user. This might be a worthwhile enhancement to the plugin functionality as you shouldn't actually run the container with the root user. Would you be interested in proposing a pull request for this?

**Comment by bmuschko** [comment]
I won't have time to work on this anytime soon. Closing it for now. Happy to review pull requests for this feature.
