### ISSUE TITLE
Would it be possible to use the buildx command?

### ISSUE THREAD

**Issue by lamba92** [bmuschko/gradle-docker-plugin#967]
Maybe a `DockerBuildxImage` task with added list of target architectures would be really useful!

**Comment by bmuschko** [comment]
At this time, the `buildx` command is not available. I am not even sure if Docker Java currently supports it. If you plan to look into it and/or provide a pull request then we can go from there. Other than that there's no plan from the maintainers of the plugin to work at the functionality at the moment.

**Comment by lamba92** [comment]
Actually the command is very much similar to `build`, just few options more. I forked the project and started looking at it, but I am not used to Groovy. Is there a proper channel to ask guidance or explanation on the source code of `gradle-docker-plugin`?

**Comment by bmuschko** [comment]
The plugin doesn't use the Docker command line tool. It uses the Docker Java library which communicate via the Docker daemon. You can find the link to the Gitter channel in the README, however, I don't think there are a lot of people that can answer questions on the code. It's meant for end users.

**Comment by bmuschko** [comment]
I am going to close this issue for now except if somebody from the community is planning to contribute the feature.

**Comment by bmuschko** [comment]
AFAIKT, the Docker API does not support the creation of multi-platform images. What you can provide though is a single platform when creating an image: https://bmuschko.github.io/gradle-docker-plugin/current/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#platform

**Comment by Joker9944** [comment]
For anyone stumbling upon this issue I have solved it like this by creating creating a new task in my build.gradle. Please keep in mind that you still have to create a builder which is capable of multiplatform builds.

```
docker {
	springBootApplication {
		baseImage = 'openjdk:17-bullseye'
	}
}

task dockerBuildxImage(type:Exec) {
	group 'docker'
	dependsOn dockerCreateDockerfile
	workingDir 'build/docker'
	executable 'docker'
	args = ['buildx', 'build', '--platform', 'linux/amd64,linux/arm64', '-t', "$registry/$project.name:$project.version", '-t', "$registry/$project.name:latest", '--push', '.']
}
```
