### ISSUE TITLE
Can't get example custom docker client handling to work with kotlin build.grade.kts (or buildSrc)

### ISSUE THREAD

**Issue by sean-abbott** [bmuschko/gradle-docker-plugin#969]
### Expected Behavior
I should be able to copy the example into my code to bootstrap me into making changes

### Current Behavior
compile step complains "Not enough information to infer type variable T" for Action on the line `onNext(Action {` in the constructor in the file. 

I tried to set up a simple example repo to demonstrate this, but it worked in a bare minimum example and it doesn't work in my actual project.

### Steps to Reproduce (for bugs)
I tried dropping the example in build.gradle.kts at the top level, along with `import com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask` at the top.

### Your Environment
Ubuntu 18.04
kotlin 1.3.7
gradle 6.6

**Comment by sean-abbott** [comment]
Actually, this is failing in my example project to: https://github.com/sean-abbott/sample-docker-plugin-fail

**Comment by sean-abbott** [comment]
(I understand that this is almost certainly user error; perhaps I can help expand the docs if you can tell me what I'm doing wrong)

**Comment by bmuschko** [comment]
I am sorry but I won't be able to look at Groovy vs. Kotlin DSL-related issues. This is probably best asked on the Gradle forum. Just wondering...the[ plugin user guide has an example in Kotlin](https://bmuschko.github.io/gradle-docker-plugin/#reacting_to_data_returned_by_an_operation). Why did you chose to use a different syntax?

**Comment by bmuschko** [comment]
Closing as we haven't gotten a response from you.
