### ISSUE TITLE
Reading DOCKER_HOST and DOCKER_CERT_PATH environment variables

### ISSUE THREAD

**Issue by stellingsimon** [bmuschko/gradle-docker-plugin#97]
Thanks for this well-crafted plugin!

We currently need the following code in our `build.gradle` to make sure the build works out of the box on each developer's machine, regardless of whether they installed Docker natively (on Linux) or in a boot2docker/dockermachine environment:

    docker {
      url = dockerHostUrl()
      certPath = dockerCertPath()
    }

    String dockerHostEnv() {
      System.getenv('DOCKER_HOST')
    }

    String dockerHostUrl() {
      if (dockerHostEnv()) {
        dockerHostEnv()
      } else {
        org.gradle.internal.os.OperatingSystem.current().isLinux()
        ? 'unix:///var/run/docker.sock'
        : 'http://localhost:2375'
      }
    }

    File dockerCertPath() {
      String certPathEnv = System.getenv('DOCKER_CERT_PATH')
      certPathEnv ? file(certPathEnv) : null;
    }

With boot2docker, the idiomatic approach is to run `$(boot2docker initshell)` in the terminal beforehand. docker-machine uses a similar approach, also setting the environment variables. It would be very nice if the gradle-docker-plugin would also adhere to `DOCKER_HOST/DOCKER_CERT_PATH` without the above additional configuration.

**Comment by bmuschko** [comment]
I can see the need for this. At the moment I cannot take on the maintenance cost though. It requires quite a bit of test code; optimally for different OSes. What I'd recommend is to wrap your code into a plugin that applies the plugin `com.bmuschko.docker-remote-api` and publish it to a binary repository. Then you can share it among multiple projects internally at your organization.

**Comment by stellingsimon** [comment]
Thanks, I'll do that. I updated the code in the original question for those who don't want to create an additional plugin.
