### ISSUE TITLE
Issue with attaching stdout/stdin to terminal

### ISSUE THREAD

**Issue by cilki** [bmuschko/gradle-docker-plugin#973]
I'd like to attach the stdout (and eventually stdin) of a container started with `DockerStartContainer` to my terminal:
```
val createTestContainer by tasks.creating(DockerCreateContainer::class) {
	dependsOn(imageBuild)
	targetImageId(imageBuild.getImageId())
	hostConfig.autoRemove.set(true)

	// I've tried a bunch of combinations of the following:
	//attachStdout.set(true)
	//attachStderr.set(true)
	//attachStdin.set(true)
	//tty.set(true)
	//stdinOnce.set(true)
	//stdinOpen.set(true)
}

val startTestContainer by tasks.creating(DockerStartContainer::class) {
	dependsOn(createTestContainer)
	targetContainerId(createTestContainer.getContainerId())
}
```

### Expected Behavior
The `DockerStartContainer` task should output the container's stdout to the terminal.

### Current Behavior
No output from start task:
```
> Task :createTestContainer
Created container with ID '63cfb4684cfc36034c27a53a196c8424bfa7e8c82b198f383b8ba6c7d6e37903'.

> Task :startTestContainer
Starting container with ID '63cfb4684cfc36034c27a53a196c8424bfa7e8c82b198f383b8ba6c7d6e37903'.

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 executed
```
I can verify that the container actually ran and wrote to stdout.

### Steps to Reproduce (for bugs)
I can provide a minimal reproducer if desirable.

### Your Environment
Plugin version 6.6.1, Kotlin DSL, Linux.

**Comment by bmuschko** [comment]
Not quite sure what the right combination of flags is supposed to be. This may be a better question for the Docker Java project.

**Comment by cilki** [comment]
Apologies, I'm sure you get way too many docker-java issues here. Thanks.

**Comment by bmuschko** [comment]
Yeah, you may want to open an issue with the Docker Java project. If they propose a solution that works for Docker Java but not with the plugin then we can reopen.
