### ISSUE TITLE
Windows will ocassionally truncate logs in LivenessProbe - use a shorter probe string

### ISSUE THREAD

**Issue by doctorpangloss** [bmuschko/gradle-docker-plugin#975]
Based on the source of `DockerLivenessContainer`, it is possible to process logs in a way where the string that is being searched for is split across two chunks of logs.

### Expected Behavior
`DockerLivenessContainer` should try to read logs line by line.

### Current Behavior
`DockerLivenessContainer` on Windows does not appear to read line by line or has some other weird behavior.

### Context
Using a liveness probe on Windows is glitchier than on macOS. Using a shorter liveness probe string seems to resolve the issue

### Steps to Reproduce (for bugs)
The reproduction involves starting the Keycloak docker image, which is a pretty complex one that emits a lot of logging information. Seeking `Admin console` instead of `Admin console listening on` greatly improves the likelihood of the probe passing. On macOS the probe always passes.

### Your Environment
Windows 10, JDK 11

**Comment by bmuschko** [comment]
We are aware that some of those extra tasks have bugs. We will deprecate those tasks and remove them with the next major version: https://github.com/bmuschko/gradle-docker-plugin/pull/981

If you want similar functionality, then you'll have to implement it on your end.
