### ISSUE TITLE
hangs task dockerBuildImage if tag invalid

### ISSUE THREAD

**Issue by Monax111** [bmuschko/gradle-docker-plugin#976]
### Expected Behavior
I execute task dockerBuildImage and it must return error 
```
Execution failed for task ':dockerBuildImage'.
> Status 500: {"message":"invalid reference format: repository name must be lowercase"}
```

### Current Behavior
task dockerBuildImage hangs  more than 20 minutes

### Context
i generate image name automatically and spend more time to debug

### Steps to Reproduce (for bugs)
clone [repository ](https://github.com/Monax111/testLibrary) and execute dockerBuildImage 
If comment dependency kotlin-reflect it's work, and i see error. But with kotlin-reflect it hangs.
First i think it mistake docker-java and create [issue](https://github.com/docker-java/docker-java/issues/1502). But they replied that it was not their fault.

```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by bmuschko** [comment]
Honestly, I won't have time to debug the interaction with Kotlin here. Not sure in what subtle ways Kotlin reflect runs some magic.

**Comment by bmuschko** [comment]
I am going to close the issue as I won't look into it. Maybe asking on the Kotlin user forum may give you a clue.
