### ISSUE TITLE
Cannot set `DockerRemoveImage.targetImageId` using `DockerBuildImage.imageId`

### ISSUE THREAD

**Issue by rkrisztian** [bmuschko/gradle-docker-plugin#977]
I believe, ever since `DockerBuildImage.images` was introduced, it is not possible anymore to reuse `DockerBuildImage.imageId`. So in fact, none of the documented examples relying on it should work, e.g.:

```groovy
import com.bmuschko.gradle.docker.tasks.container.*
import com.bmuschko.gradle.docker.tasks.image.*

plugins {
    id 'com.bmuschko.docker-remote-api' version '6.6.1'
}

task buildMyAppImage(type: DockerBuildImage) {
    inputDir = file('docker/myapp')
    images.add('test/myapp:latest')
}

task createMyAppContainer(type: DockerCreateContainer) {
    dependsOn buildMyAppImage
    targetImageId buildMyAppImage.getImageId()
    hostConfig.portBindings = ['8080:8080']
    hostConfig.autoRemove = true
}
```

Because I get:

```none
Caused by: org.gradle.api.InvalidUserDataException: No value has been specified for property 'imageId'.
```

What works for me is:

```groovy
task removeMyAppImage(type: DockerRemoveImage) {
	force = true
	targetImageId { buildImage.images.get().first() }
}
```

Can you tell me if I'm doing something wrong? Like, I can set up an example project with Gradle 6.7.1 if needed. But I was hoping you could quickly reproduce the error.

**Comment by bmuschko** [comment]
The task `DockerBuildImage` doesn't deal with a single image ID anymore. The underlying data type is now a list. `DockerBuildImage.imageId` has been removed from the API. What you are doing right now is the correct way.

**Comment by rkrisztian** [comment]
The **docs are misleading**/outdated then. They make us believe that the `getImageId()` still works, but not. Look at 2.5.3 and 2.5.4. As I said before:

> none of the documented examples relying on it should work`.

And I wanted to clarify that first.

**Comment by bmuschko** [comment]
I didn't really look at this project for months now. My previous statement was not correct.

Whenever you can and when in doubt, look at the API docs. Examples are really only examples and show a specific use case. BTW: All examples in the user guide are tested and should work as-is.

[`DockerBuildImage.html#imageId`](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#imageId): The id of the image built.

Your initial example works fine for me. Do you have other code you are not showing? Please provide a GitHub repo with a reproducible project.

```
gradle createMyAppContainer --console=verbose

> Task :buildMyAppImage
Building image using context '/Users/bmuschko/dev/tmp/bla/docker/myapp'.
Using images 'test/myapp:latest'.
Step 1/1 : FROM nginx
 ---> ae2feff98a0c
Successfully built ae2feff98a0c
Successfully tagged test/myapp:latest
Created image with ID 'ae2feff98a0c'.

> Task :createMyAppContainer
Created container with ID 'ef00837063a865acf782488980d497c3993b8ff1b8bb8ea71e27fbab949d36e6'.

BUILD SUCCESSFUL in 9s
2 actionable tasks: 2 executed
```

**Comment by bmuschko** [comment]
And be aware that the image ID is only populated if you actually run the build task first. A task dependency needs to be established.

```
task removeMyAppImage(type: DockerRemoveImage) {
    dependsOn buildMyAppImage
    force = true
    targetImageId buildMyAppImage.getImageId()
}
```

**Comment by rkrisztian** [comment]
OK, thanks, this was an embarrassing mistake from my part then. I did have a `removeMyAppImage` task where I did not want to depend on `buildMyAppImage`. There I confused the image name with the image ID...

Do you think the following APIs could use a clearer description?

1. https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#images

> The images including repository, image name and tag used e.g. vieux/apache:2.0. 

This is confusing because it doesn't tell what kind of images it means. I know only 1 image, and that's the one we're building. So my suggestion is:

> The name(s) of the built image. Repositories and tags can also be specified, e.g. vieux/apache:2.0.

2. https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#imageId

I'm quite hesitant to ask this, but maybe consider adding that this ID will be set only after the task runs, so for tasks like cannot have that dependency, then you should use `images` or save the image name to a constant. Should be fairly trivial if you have worked with Dockerfiles before, so I can imagine you would disagree. I tripped on it, I shouldn't have, I know. Your call. After all, `targetImageId` has "ID" in its name, like, it was designed for IDs... That naming lures you into the trip. Maybe it should be called `targetImage` so then I decide how to refer to it.

Alternatively, consider extending at least one of the examples for `DockerRemoveImage` so that they take in the `images` of the build task. You could also ask: why would I do that, I can just define a common constant and pass it to the build tasks... The problem with constants though is that they aren't lazy, which may again trip you up sometimes.

Yet another alternative: make a `targetImageId` method overload that takes a `DockerBuildImage` task. Then the method would determine the target image ID or name from the task. Note: of course we should not implicitly add `dependsOn` association, that's too frequently not what we would want.

Finally, in your examples, it's not idiomatic Groovy to say `buildMyAppImage.getImageId()`. It should be just `targetImageId buildMyAppImage.imageId`. We should really think of it as a (lazy) property and use Groovy's property access notation for the getter.

**Comment by bmuschko** [comment]
> This is confusing because it doesn't tell what kind of images it means. I know only 1 image, and that's the one we're building.

I clarified some of the Javadocs: https://github.com/bmuschko/gradle-docker-plugin/commit/68f92f195330d13677efaf43bdd6f022bbf5fbb0

> After all, targetImageId has "ID" in its name, like, it was designed for IDs... That naming lures you into the trap. Maybe it should be called targetImage so then I decide how to refer to it.

The Javadocs already said ID or name. The field should be renamed to `targetImage` but it's going to be a breaking change and will affect a lot of consumers. If we wanted to do that then we'll need to deprecate the field first and introduce the new one + change all references. Feel free to send a PR if you feel strongly about it.

> Alternatively, consider extending at least one of the examples for DockerRemoveImage so that they take in the images of the build task. 

Feel free to send a PR.

> Finally, in your examples, it's not idiomatic Groovy to say buildMyAppImage.getImageId(). It should be just targetImageId buildMyAppImage.imageId. We should really think of it as a (lazy) property and use Groovy's property access notation for the getter.

I did this because Gradle users often times do not understand the subtleties of the Groovy language. There are too many questions that prove it. With a method call, end users know what method is actually called here. Anyone that does understand the properties concept in Groovy can use the notation.

**Comment by rkrisztian** [comment]
I'll consider the PRs, but first:

> I did this because Gradle users often times do not understand the subtleties of the Groovy language. There are too many questions that prove it.

Wow. That's so sad. I call this the anti-pattern of **Defense-Against-Ignorance-Driven Development**. This is what makes me want to switch profession, because people can't even learn the very basics of a language now. They work with a language they don't even understand. That is so unprofessional, and having to defend ourselves against it... Just crazy! People only knowing Java, but not Groovy, should learn about the language first, otherwise they just create a huge pile of maintainability issues for us. A clean coder (even those that aren't overboard with their practices) would never allow that to happen.

Well, what about this: the API documents a property, not a getter. So we got an inconsistency there. Now to correct that inconsistency (because you wouldn't want to confuse your users, right?), you would actually have to introduce boilerplate code, so that it will just get worse. Why not just link this very fine guide: https://groovy-lang.org/style-guide.html. It's what I throw at people every time. It's a low-effort way of teaching people what they should have known in the first place. If makes things better, link this as a requirement in your docs (or ask them to switch to Kotlin), I don't mind. But I'd rather have this than derogate our practices. For sure I'm not going that low if there is a better solution, but I do understand your position as well.

Anyways, your argument feels proven, indeed, I was supposed to know the basics of Docker too, and I wasted your time. I'm sorry for that. But your documentation changes, I think are going to help future users. And that's what I believe in.

**Comment by rkrisztian** [comment]
Sorry if my previous message offended you. That's of course never my intention, but to try and improve things.

> >     Alternatively, consider extending at least one of the examples for DockerRemoveImage so that they take in the images of the build task.
 
> Feel free to send a PR.

Done.

**Comment by bmuschko** [comment]
No worries. I didn't even have time to look at the repository in the past couple of weeks. I will have a look at the PR in the next couple of days.
