### ISSUE TITLE
Support upToDateWhen for DockerBuildImageTask 

### ISSUE THREAD

**Issue by ajmath** [bmuschko/gradle-docker-plugin#98]
First off, thanks for the awesome plugin!

It would be great if the plugin could detect when it doesn't need to invoke the API to try to build a new docker image.  You should be able to save the image id to the build directory and then in the upToDate check for the buildImageTask, call the remote API to see if the previous image exists in the daemon.

I've implemented a hacked up version of this using the cli and it appears to work rather well, saving over 17 seconds for some image builds.

Is this something that you are interested in?  Are there any reasons this shouldn't work?

**Comment by cdancy** [comment]
Closed due to #139
