### ISSUE TITLE
How to add --ssh=default flag

### ISSUE THREAD

**Issue by akumaf** [bmuschko/gradle-docker-plugin#984]
I'm currently using an experimental build feature which requires me to add the equivalent configuration of --ssh=default to the final build procedure. However, i couldn't find a way in the documentation on how to do it. The equivalent cli command i would like to accomplish is

docker build --ssh=default .

**Comment by bmuschko** [comment]
This plugin doesn't use the command line executable of Docker. It uses the remote API. The remote API may or may not support the option. If it does support the option, then Docker Java also needs to support it. And if it does, then this plugin can incorporate it. If you are looking for a specific option, then look at the [Groovydocs of corresponding custom task](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html) first. I don't see it here right now so you will have to check with the Docker Java project.

**Comment by bmuschko** [comment]
I am going to close this for now. We need to Docker Java to provide the flag first before we can support it. Please go ahead and create an issue or pull request for them.
