### ISSUE TITLE
single string ENTRYPOINT and CMD not supported

### ISSUE THREAD

**Issue by xpusostomos** [bmuschko/gradle-docker-plugin#986]
### Expected Behavior
In Docker, ENTRYPOINT and CMD can be either a string or an array. If it's a string it eventually becomes "sh -c 'string'", but if an array it is executed directly. As far as I can tell, this plugin only supports the array format, not the single string format. Now I guess, sure, you could manually add your own "sh", "-c", but it seems to me that the build system should support any feature natively as provided by Docker.

Now if I was designing this plugin, I would make it mirror Docker. i.e.
entryPoint ['java']
results in:
ENTRYPOINT ["java"]
but
entryPoint 'java'
results in:
ENTRYPOINT "java"

I don't know how you solve this now and deal with backwards compatibility.

### Current Behavior
entryPoint 'java'
results in:
ENTRYPOINT ["java"]

### Context
To tell you the truth, maybe this doesn't matter. The worst part about it is, the documentation has few examples, and figuring out that it doesn't work as one would intuitively expect, required me to read the source code. Personally, I don't like that this feature is missing, but at the least can we document with examples usage of all the commands and how they're used, showing what Dockerfile output we get?

**Comment by bmuschko** [comment]
A couple of comments:

1. In practice, the difference of executing the entrypoint with `sh -c` vs. without is IMHO a non-issue.
2. The canonical documentation for the API is Groovydoc linked in the README. It explains all methods and their usage for the [Dockerfile custom class](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html). You can't possibly document all usage patterns as examples. There are far too many use cases and combinations.
3. The API documentation could be improved to also explain the generated instruction. Pull requests welcome!
4. You can provide any generic instruction with [this method](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html#instruction(java.lang.String)).
5. The Dockerfile custom task is something you can use but don't have to. It's really only an abstraction layer that allows the dynamic creation of a Dockerfile at build-time. You might as well just write your own Dockerfile, check it into SCM and then feed it into the task that builds the image.

**Comment by xpusostomos** [comment]
Maybe this is some kind of ignorance on my part, but when the documentation lists this:
```
entryPoint(Provider<List<String>> provider)
```

It suggests to me that entry point accepts some kind of array. I don't know. It just seems like you have to understand a lot about gradle and groovy, when all you want to do is build something. I'm not sure that the "generic instruction" thing or the pattern for just writing your own Docker file are given enough coverage in the user guide either considering how fundamental those features would be.

**Comment by bmuschko** [comment]
[Provider](https://docs.gradle.org/current/userguide/lazy_configuration.html) is a Gradle concept for providing configuration that is evaluated lazily. It's correct that you will have to understand this concept and its use cases. It's usually not the responsibility to explain Gradle core concepts so I can only point you to the docs.

Sure, we could add documentation for those use cases. The docs could be better. It's just a matter of putting in the effort. At the moment, I simply do not have the time to do so.

**Comment by bmuschko** [comment]
I am going to close this issue as either notation for defining ENTRYPOINT or CMD should have the same runtime behavior.

**Comment by xpusostomos** [comment]
Funnily enough, I started working on another project the other day, and ran into the exact same problem. And I'd forgotten all about this bug report, and had to discover all over again the weird behavior of this plugin. I still think the plugin should reflect docker's way, by differentiating how arrays vs single arguments work.
