### ISSUE TITLE
Gradle Configuration Cache incompatibilities

### ISSUE THREAD

**Issue by dsvensson** [bmuschko/gradle-docker-plugin#987]
When trying to use the new gradle configuration cache, the build fails with:

```
invocation of Task.project at execution time is unsupported
```
The relevant gradle documentation:
https://docs.gradle.org/6.8/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

and:
```
registration of listener on Gradle.buildFinished is unsupported
```
The relevant gradle documentation:
https://docs.gradle.org/6.8/userguide/configuration_cache.html#config_cache:requirements:build_listeners

In the following method: 
https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy#L144

Perhaps more to fix once those two are taken care of, but at least a start. Would be nice to be able to enable configuration cache in gradle.properties.

**Comment by bmuschko** [comment]
Thanks for making me aware of this. The Gradle documentation is little wishy-washy on how to change the code exactly. Unfortunately, I am short on time at the moment but would be interested I creating a pull request for this?

**Comment by bmuschko** [comment]
Closing as the issue hasn't gotten any traction.

**Comment by Sineaggi** [comment]
I'm commenting here, but we can create a new issue if preferred.

The first issue, calling project at execution time, should be fixed well enough by caching an `ObjectFactory` as a final field as per this branch https://github.com/bmuschko/gradle-docker-plugin/compare/master...Sineaggi:gradle-docker-plugin:remove-project-call-at-runtime

The second issue is a bit more complex. Gradle has been pushing developers a bit more towards [build services](https://docs.gradle.org/7.5.1/userguide/build_services.html#build_services) for cases where a task potentially wants to share state. A quick an dirty implementation that replaces the existing `getDockerClient` call with a DockerClient provider service (with a bit of caching as well) https://github.com/bmuschko/gradle-docker-plugin/compare/master...Sineaggi:gradle-docker-plugin:add-build-service
