### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by orzeh** [bmuschko/gradle-docker-plugin#988]
As per [recent announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) JCenter will be shut down at 30 Apr 2021.

We need to refactor plugin build scripts, check documentation and functional tests.

**Comment by bmuschko** [comment]
It's a mess. Interested in helping out?

**Comment by orzeh** [comment]
Yeah, I'll try to put together something.

**Comment by bmuschko** [comment]
Awesome, thanks!

**Comment by cdancy** [comment]
Wow this is crazy news.

**Comment by bmuschko** [comment]
@orzeh Did you make any progress on this?

**Comment by orzeh** [comment]
@bmuschko not yet. I plan to crack on this during the weekend.

**Comment by bmuschko** [comment]
@orzeh Thanks! We will also need to switch publishing of the plugin artifacts should be switched to using the `com.gradle.plugin-publish` so that it goes directly to the Gradle plugin portal. But as a first step, let's change `jcenter()` references to `mavenCentral()` as much as we can.

**Comment by cdancy** [comment]
Have you guys noticed a trend one way or another of folks in the community/industry moving towards one service over another for general artifacts? I always got the impression developers used jcenter for ease of use (I know I sure did) and just wondering if there is an alternative poking it's head up somewhere. I know github has some sort of artifact repository as well though not sure how good it is.

**Comment by bmuschko** [comment]
For organizations, the inhouse product is usually Artifactory. For Open Source, it's probably still Maven Central in the JVM space. I personally haven't tried GitHub's repo yet and haven't heard much about it recently. It may be a good fit for generic artifacts primarily but not for artifacts with a standardized organizational structure like a Maven repo.
