### ISSUE TITLE
Only treat pem files in DOCKER_CERT_PATH as an input

### ISSUE THREAD

**Issue by ajmath** [bmuschko/gradle-docker-plugin#99]
When switching to docker-machine, I noticed that it uses a single flat directory for each machine's configuration.  For virtualbox, this includes things like the vm disk image.  With the certPath defined as a input directory, this means changes to any file in that directory will need to be scanned by gradle.  For large files, this can take several seconds.

**Comment by cdancy** [comment]
Closing as per #100. If we need to re-open we can.
