### ISSUE TITLE
improve Dockerfile.addFile(File) method documentation

### ISSUE THREAD

**Issue by matteomazza91** [bmuschko/gradle-docker-plugin#990]
### Expected Behavior
documentation of addFile(File) method in Dockerfile class should link to [Dockerfile.File](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.File.html) instead of [java.io.File
](https://docs.oracle.com/javase/8/docs/api/java/io/File.html)

### Current Behavior
at the moment, both in the summary and in the method description of this page: https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html#addFile(java.io.File),  
the link for the File type of the addFile parameter is pointing to java.io.File: https://docs.oracle.com/javase/8/docs/api/java/io/File.html

### Context
Improve documentation

**Comment by bmuschko** [comment]
Oooops, care to send a PR?

**Comment by matteomazza91** [comment]
today I tried to checkout the repo and generate the doc. I got this error in compilation:
```
'forRemoval'is not part of the annotation java.lang.Deprecated -> java.lang.Deprecated in @java.lang.Deprecated
 @ line 37, column 1.
   @Deprecated(forRemoval = true)
```
I saw there is 'sourceCompatibility = JavaVersion.VERSION_1_8' on the buildscript but `forRemoval` is not present in java 8. 

anyway, I guess I would need a newer JDK.

**Comment by bmuschko** [comment]
What task did you run? `javadoc`?

**Comment by matteomazza91** [comment]
I tried both `javadoc` and `groovydoc` actually. The error happens at compilation time in `compileGroovy` task

**Comment by bmuschko** [comment]
You are right. The attribute has been introduced with Java 9: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Deprecated.html#forRemoval(). Looks like `sourceCompatibility` doesn't have an effect on `groovydoc`. We'll probably want to build that code with Java 11 anyway. There's no point in sticking with Java 8 anymore.

**Comment by bmuschko** [comment]
Master is building with source and target compatibility 11 now. You can go ahead and work on a fix.

**Comment by bmuschko** [comment]
I just fixed it: https://github.com/bmuschko/gradle-docker-plugin/commit/dcad57f2bad1be13a34bcfb9a3836858d8e6be8c

**Comment by matteomazza91** [comment]
sorry for the delay on this.  
I propose some additional changes to the doc in #997 mainly to fix the links to `addFile()` in "see also" sections in the generated doc
