### ISSUE TITLE
Not all release artifacts are signed

### ISSUE THREAD

**Issue by dsvensson** [bmuschko/gradle-docker-plugin#993]
I'll just quote the conclusion on gradle's slack

> Ok, so you have id("com.bmuschko.docker-remote-api") version "6.7.0"
Which means Gradle adds com.bmuschko.docker-remote-api:com.bmuschko.docker-remote-api.gradle.plugin:6.7.0 dependency to the build script (check ./gradlew buildEnvironment )
Apparently, that pom it is not signed, so you have this “unsigned artifact”: https://plugins.gradle.org/m2/com/bmuschko/docker-remote-api/com.bmuschko.docker-remote-api.gradle.plugin/6.7.0/
The solution is:
a) Convince com.bmuschko.docker-remote-api maintainers to publish the plugin to Central (they would have to comply with “every publication to Central must be signed” rule :slightly_smiling_face: )
b) Convince Gradle team to enforce PGP signatures for the plugins (so plugin authors would have to publish PGP signatures). Hint: you could send them https://sigstore.dev/what_is_sigstore/ link which might get @Jonathan Leitschuh excited :slightly_smiling_face: (or not, I don’t know)
c) Convince plugin authors to publish the signatures for all the poms
d) Keep using SHA256 checksums. At the end of the day, checksums are more secure than PGP keys alone since they prevent unexpected artifact drift. Of course, PGP signatures might help to validate the origin (e.g. it is safer to update the dependency if it is signed with the same key as the previous version)

**Comment by bmuschko** [comment]
Can you provide some background information on this? What's the actual issue or reason this question was asked? What's the blocker for you?

**Comment by dsvensson** [comment]
To get the gradle dependency verification fully working, as described above, not all artifacts are signed leading to gradle incorrectly adding the following to the verification manifest:

```xml
      <component group="com.bmuschko.docker-remote-api" name="com.bmuschko.docker-remote-api.gradle.plugin" version="6.7.0">
         <artifact name="com.bmuschko.docker-remote-api.gradle.plugin-6.7.0.pom">
            <sha256 value="0d0aeb215c75be560c866ad7259064473f8fcbc08c36a2cc436a820a12e0e739" origin="Generated by Gradle because artifact wasn't signed"/>
         </artifact>
      </component>
```

**Comment by dsvensson** [comment]
Very much related to #988 as the citation notes.

**Comment by bmuschko** [comment]
@dsvensson Do you know how I can get the artifacts signed? Does this happen automatically if I publish to the Gradle plugin portal directly?

**Comment by dsvensson** [comment]
Unfortunately not. I'm very cluless in this area and my issue filed here came from my questioning around on gradle slack why some parts of for example the docker plugin only had sha256 verification. The answer suggested that as maven central requires all artifacts to be signed, publishing to central should cover the signing part.

**Comment by bmuschko** [comment]
Starting with plugin version 7.0.0, we will only publish to the Gradle plugin portal. I'd assume that the plugin for publishing to it does the right thing.
