### ISSUE TITLE
is there anyway to change the build dir for docker task?  I want to configure the directory where docker commands are run. instead of build\docker directory

### ISSUE THREAD

**Issue by gxa82** [bmuschko/gradle-docker-plugin#996]

**Comment by bmuschko** [comment]
Are you asking about the context directory (containing the Dockerfile and other files copied into the image) or the working directory used in the Dockerfile?

**Comment by bmuschko** [comment]
Closing as I haven't gotten a response. Feel free to reopen if you can clarify your question.
