### ISSUE TITLE
Support for JDK 16

### ISSUE THREAD

**Issue by abrudin** [bmuschko/gradle-docker-plugin#999]
The current version, 6.7.0, does not work with projects using JDK 16.

The task dockerCreateDockerFile fails with `Unsupported class file major version 60`

The issue seems to be the dependency, org.ow2.asm:asm, where this plugin uses version 7.3.1. When updating this to use the latest version, 9.1, the plugin appears to be working.

**Comment by bmuschko** [comment]
Do you want to provide a pull request for this?

**Comment by abrudin** [comment]
I realize it may be too late, but it would certainly be nice to have this in the 7.0.0 release, if not for the aesthetic reason that the newly released gradle 7.0 introduced Java 16 support :)
